### ISSUE TITLE
Proton version 'none' not found

### ISSUE THREAD

**Issue by simcye** [sonic2kk/steamtinkerlaunch#1002]
## System Information
- SteamTinkerLaunch version:   v12.12 
- Distribution:  Arch Linux 
- Installation Method:  ProtonUp-QT 

## Issue Description
Attempting to launch MO2 GUI from game menu spams "Proton version 'none' not found" messages and it fails to run. Also on starting steam I get those same messages. Not sure if i'm doing something wrong or my install is bugged.

## Logs

Sat Dec 30 12:57:57 AM PST 2023 INFO - setflatpak - started SteamTinkerLaunch from /home/sydney/stl/prefix/steamtinkerlaunch
Sat Dec 30 12:57:57 AM PST 2023 INFO - initAID - Set AID from STEAM_COMPAT_APP_ID to '489830'
Sat Dec 30 12:57:57 AM PST 2023 INFO - initAID - Set OSCDP to STEAM_COMPAT_DATA_PATH '/mnt/SL1/sydney/SteamLibrary/steamapps/compatdata/489830'
Sat Dec 30 12:57:57 AM PST 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Sat Dec 30 12:57:57 AM PST 2023 INFO - loadLangFile - Language from command line is 'english'
Sat Dec 30 12:57:57 AM PST 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/sydney/stl/prefix/lang'
Sat Dec 30 12:57:57 AM PST 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Sat Dec 30 12:57:57 AM PST 2023 INFO - loadLangFile - Found user-installed /home/sydney/.config/steamtinkerlaunch/lang/english.txt, attempting to update it
Sat Dec 30 12:57:57 AM PST 2023 INFO - loadLangFile - Found lang file to replace the existing user-installed file with under '/home/sydney/stl/prefix/lang/english.txt'
Sat Dec 30 12:57:57 AM PST 2023 INFO - loadLangFile - Loading found user-installed /home/sydney/.config/steamtinkerlaunch/lang/english.txt
Sat Dec 30 12:57:57 AM PST 2023 INFO - loadLanguage - Loading STLLANG from '/home/sydney/.config/steamtinkerlaunch/global.conf'
Sat Dec 30 12:57:57 AM PST 2023 INFO - loadLanguage - STLLANG from '/home/sydney/.config/steamtinkerlaunch/global.conf' is 'english'
Sat Dec 30 12:57:57 AM PST 2023 INFO - setLocalInstall - Looks like we have a non-root local install here - Updating paths...
Sat Dec 30 12:57:57 AM PST 2023 INFO - updateConfigEntry - Option 'GLOBALCOLLECTIONDIR' is updated with the new value '/home/sydney/stl/prefix/collections' in config 'global.conf'
Sat Dec 30 12:57:57 AM PST 2023 INFO - getCurrentCommandline - No Proton in command line arguments 'dcp'
Sat Dec 30 12:57:57 AM PST 2023 INFO - saveOrgVars - Storing some original variables to restore them later
Sat Dec 30 00:57:57 PST 2023 INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
Sat Dec 30 00:57:57 PST 2023 INFO - emptyVars - Set $PATH to '/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl::'
Sat Dec 30 00:57:57 PST 2023 START - ######### Initializing Game Launch 489830 using SteamTinkerLaunch v12.12 #########
Sat Dec 30 00:57:57 PST 2023 INFO - main - Starting with a clean log
Sat Dec 30 00:57:57 PST 2023 INFO - main - Start creating default configs
Sat Dec 30 00:57:57 PST 2023 INFO - createDefaultCfgs - START
Sat Dec 30 00:57:57 PST 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Sat Dec 30 00:57:57 PST 2023 INFO - loadLangFile - Language from command line is 'english'
Sat Dec 30 00:57:57 PST 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/sydney/stl/prefix/lang'
Sat Dec 30 00:57:57 PST 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Sat Dec 30 00:57:57 PST 2023 INFO - loadLangFile - Found user-installed /home/sydney/.config/steamtinkerlaunch/lang/english.txt, attempting to update it
Sat Dec 30 00:57:57 PST 2023 INFO - loadLangFile - Found lang file to replace the existing user-installed file with under '/home/sydney/stl/prefix/lang/english.txt'
Sat Dec 30 00:57:57 PST 2023 INFO - loadLangFile - Loading found user-installed /home/sydney/.config/steamtinkerlaunch/lang/english.txt
Sat Dec 30 00:57:57 PST 2023 INFO - loadLanguage - Loading STLLANG from '/home/sydney/.config/steamtinkerlaunch/global.conf'
Sat Dec 30 00:57:57 PST 2023 INFO - loadLanguage - STLLANG from '/home/sydney/.config/steamtinkerlaunch/global.conf' is 'english'
Sat Dec 30 00:57:57 PST 2023 INFO - createDefaultCfgs - setSteamPaths:
Sat Dec 30 00:57:57 PST 2023 INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
Sat Dec 30 00:57:57 PST 2023 INFO - getGameOS - Starting game OS detection
Sat Dec 30 00:57:57 PST 2023 WARN - getGameOS - Could not extract the full game binary path from the incoming game launch command, so assuming this is a Windows game!
Sat Dec 30 00:57:57 PST 2023 INFO - setWin - '' determined to be a Windows Game
Sat Dec 30 00:57:57 PST 2023 INFO - createDefaultCfgs - createProtonList:
Sat Dec 30 00:57:57 PST 2023 INFO - createDefaultCfgs - createProtonList end
Sat Dec 30 00:57:57 PST 2023 INFO - listAllSettingsEntries - '/dev/shm/steamtinkerlaunch/setentries.txt' already exists - nothing to do
Sat Dec 30 00:57:57 PST 2023 INFO - createDefaultCfgs - STOP
Sat Dec 30 00:57:57 PST 2023 SKIP - listSteamLibraries - not recreating already available '/dev/shm/steamtinkerlaunch/SteamLibraries.txt'
Sat Dec 30 00:57:57 PST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_LIBRARY_PATHS set to '/mnt/SL1/sydney/SteamLibrary/steamapps:/home/sydney/.local/share/Steam/steamapps'
Sat Dec 30 00:57:57 PST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_MOUNTS set to '/home/sydney/.local/share/Steam/steamapps/common/Steamworks Shared:/mnt/SL1/sydney/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier:/mnt/SL1/sydney/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper'
Sat Dec 30 00:57:57 PST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_TOOL_PATHS set to '/home/sydney/.local/share/Steam/steamapps/common/Steamworks Shared:/mnt/SL1/sydney/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier:/mnt/SL1/sydney/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper'
Sat Dec 30 00:57:57 PST 2023 INFO - main - Checking internal dependencies:
Sat Dec 30 00:57:58 PST 2023 INFO - checkIntDeps - Result of version check for yad binary '/usr/bin/yad' is '13.0'
Sat Dec 30 00:57:58 PST 2023 INFO - main - Initializing first Proton:
Sat Dec 30 00:57:58 PST 2023 INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/steamtinkerlaunch/ProtonCSV.txt' which was created during a previous run
Sat Dec 30 00:57:58 PST 2023 INFO - initFirstProton - Initializing Proton
Sat Dec 30 00:57:58 PST 2023 INFO - fixProtonVersionMismatch - Incoming category is 'USEPROTON' with value 'none'
Sat Dec 30 00:57:58 PST 2023 INFO - fixProtonVersionMismatch - Looking for an alternative similar version for 'none'
Sat Dec 30 00:57:58 PST 2023 INFO - fixProtonVersionMismatch - Automatically selecting newest official one
Sat Dec 30 00:57:58 PST 2023 INFO - setNOP - Selecting newest official Proton available
Sat Dec 30 00:57:58 PST 2023 SKIP - setNOP - Haven't found anything
Sat Dec 30 00:57:58 PST 2023 INFO - fixProtonVersionMismatch - Automatically updating USEPROTON to 'none' in '/home/sydney/.config/steamtinkerlaunch/default_template.conf'
Sat Dec 30 00:57:58 PST 2023 INFO - updateConfigEntry - Option 'USEPROTON' is updated with the new value 'none' in config 'default_template.conf'
Sat Dec 30 00:57:58 PST 2023 INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/sydney/.config/steamtinkerlaunch/default_template.conf' is 'none'
Sat Dec 30 00:57:58 PST 2023 INFO - main - Initializing default window resolution
Sat Dec 30 00:57:58 PST 2023 INFO - setInitWinXY - Using '1920x1080' from config '/dev/shm/steamtinkerlaunch/defres.txt'
Sat Dec 30 00:57:58 PST 2023 INFO - main - Welcome to SteamTinkerLaunch
Sat Dec 30 00:57:58 PST 2023 INFO - removeEmptyFiles - Removing empty files from '/home/sydney/.config/steamtinkerlaunch/games/appinfo'
Sat Dec 30 00:57:58 PST 2023 INFO - removeEmptyFiles - Removing empty files from '/home/sydney/.config/steamtinkerlaunch/games/header'
Sat Dec 30 00:57:58 PST 2023 INFO - main - Checking command line: incoming arguments 'dcp'
Sat Dec 30 00:57:58 PST 2023 WARN - createDLProtList - 'jq' is not installed - Can't generate list of online Proton versions
Sat Dec 30 00:57:58 PST 2023 ERROR - createDLProtList - Could not generating list of online available custom Proton builds - Probably https://github.com changed something
Sat Dec 30 00:57:58 PST 2023 INFO - dlCustomProtonGUI - Opening dialog to choose a download
Sat Dec 30 00:57:58 PST 2023 INFO - getRes - Detected screen resolution '2560x1440'
Sat Dec 30 00:57:58 PST 2023 INFO - pollWinRes - Using GEOM '--geometry=1920x1080+0+0' from '/home/sydney/.config/steamtinkerlaunch/guicfgs/2560x1440/489830/SteamTinkerLaunch-DownloadCustomProton.conf'
Sat Dec 30 00:57:58 PST 2023 INFO - updateWinRes - Starting resolution-poll for '/home/sydney/.config/steamtinkerlaunch/guicfgs/2560x1440/489830/SteamTinkerLaunch-DownloadCustomProton.conf' with incoming '1920x1080'
Sat Dec 30 00:57:58 PST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadCustomProton'
Sat Dec 30 00:57:59 PST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadCustomProton'
Sat Dec 30 00:58:00 PST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadCustomProton'
Sat Dec 30 00:58:01 PST 2023 SKIP - updateWinRes - Timeout waiting for Window 'SteamTinkerLaunch-DownloadCustomProton'

**Comment by sonic2kk** [comment]
Don't use STL v12.12, use the latest master where possible, and see the notes on the wiki: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Troubleshooting#steamtinkerlaunch-proton-version-list-isnt-updating

Clearing `/dev/shm/steamtinkerlaunch` and/or ensuring a valid version of Proton is selected for MO2.

And again, don't use STL v12.12 please.

Also, in future, please don't just copy and paste logs into a GitHub issue, no developer likes this. Attach a log file instead :-)
