### ISSUE TITLE
[Feature Request]Russian localisation

### ISSUE THREAD

**Issue by IDeathByte** [sonic2kk/steamtinkerlaunch#102]
I made a partial ru-localisation. 
Can you add it? 
[russian.txt](https://github.com/frostworx/steamtinkerlaunch/files/5378334/russian.txt)
Maybe someone finish it later

**Comment by frostworx** [comment]
Thank you very much @IDeathByte!
Just added it with commit https://github.com/frostworx/steamtinkerlaunch/commit/04745b19f30c0ec8fc071a4df458d99ffe9fe4cc

**Comment by frostworx** [comment]
Oh, I've just seen that you've also created a fork. Is your static url above up2date or are you going to create a pull request?

**Comment by frostworx** [comment]
Thank you very much for your help and time!
