### ISSUE TITLE
Mono is not detected by another app running alongside game

### ISSUE THREAD

**Issue by bugtrac** [sonic2kk/steamtinkerlaunch#1023]
## System Information
- SteamTinkerLaunch version: v14.0.20240119-1
- Distribution: Arch Linux
- Installation Method: Package Manager

## Issue Description
I am attempting to run the game Phoenix Wright: Ace Attorney Trilogy alongside a text hooker called [`agent`](https://github.com/0xDC00/agent) so that I may extract the text for the purposes of study (see another example [here](https://github.com/Artikash/Textractor)). Both programmes do run well but unfortunately, when I attempt to execute a process within `agent`, it throw an error with the following error message;

`Error: Mono not found!`

As far I understand, mono ships with all versions of proton since [4.2-3](https://github.com/ValveSoftware/Proton/issues/18#issuecomment-484887026), so it is not quite clear to me why `agent` is not picking up on this. Is there some setting I need to turn on in `steamtinkerlaunch` to get this to work? Apologies, I could not find such when looking in the Game Menu.

## Logs

Deleted (see comment below).

**Comment by bugtrac** [comment]
Apologies, this should be closed. I figured out how to attach the process properly, utilising the drag and drop feature from `agent`. It is now functioning as intended. Thank you very much for this tool.

**Comment by sonic2kk** [comment]
Glad you got it resolved! Happy gaming!
