### ISSUE TITLE
Duplicate keys and bad allignment

### ISSUE THREAD

**Issue by IDeathByte** [sonic2kk/steamtinkerlaunch#104]
Names of keys in a bottom row are duplicated, but work differently. I think Its not localisation trouble (in locales this buttons has different names - rows 12-17 as i see)
![1](https://user-images.githubusercontent.com/41571062/96021902-845d6400-0e69-11eb-822f-9d01543426a7.png)
![2](https://user-images.githubusercontent.com/41571062/96021905-858e9100-0e69-11eb-9456-db79c764f96b.png)

Also too big list selectors  looks bad - maybe allignment work little worst and you need to set limits for width

upd: find : rows 12-13 in langs has similar names BUT_RELOAD

**Comment by frostworx** [comment]
thank you! *found the typo*

**Comment by frostworx** [comment]
Regarding the alignment I think I can't do much to improve it. The bundled stl-gtk css is pretty much incomplete (css is not my world) and TBH I do not even use it (instead I just use adwaita dark)
