### ISSUE TITLE
Games won´t launch with SteamTinkerLaunch 

### ISSUE THREAD

**Issue by morpheustrue** [sonic2kk/steamtinkerlaunch#1051]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Fedora 39
- Installation Method: manual

## Issue Description
If I start a Game it will close immediately
 Previously I had problems with steamtinkerlaunch so I reinstalled it. After that I had an Error because steamtinkerlaunch couldn´t find my Steam installation path, so I created a shortcut and that fixed the problem. 

## Steam Console Output
/bin/sh\0-c\0/home/morpheus/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=227300 -- /home/morpheus/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/morpheus/.var/app/com.valvesoftware.Steam/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch'/steamtinkerlaunch waitforexitandrun '/home/morpheus/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Euro Truck Simulator 2/bin/win_x64/eurotrucks2.exe' -rdevice gl -rdevice_gl\0
chdir "/home/morpheus/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Euro Truck Simulator 2"
ERROR: ld.so: object '/home/morpheus/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/morpheus/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/morpheus/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Uploaded AppInterfaceStats to Steam

## I tried to fix the current issue by adding the following to ~/.config/steamtinkerlaunch/global.conf 

Skip dependency check for internally used programs
-SKIPINTDEPCHECK="0"

Skip dependency check for internally used programs
+SKIPINTDEPCHECK="1"

**Comment by sonic2kk** [comment]
First off, you shouldn't be using v12.12. The issue template even told you this already. I am tired of repeating myself on this.

It looks like you're trying to use regular SteamTinkerLaunch with Flatpak Steam (assuming so anyway, based on the Steam path `/home/morpheus/.var/app/com.valvesoftware.Steam/.local/share/Steam`, which is obviously where Flatpaks go), which is incorrect. I am assuming this based on the fact that you note your installation method as "manual" and that you edited files in `~/.config/steamtinkerlaunch`, and the path to the SteamTinkerLaunch config is different for Flaptak SteamTinkerLaunch.

You should be using Flatpak SteamTinkerLaunch with Flatpak Stea, [which is described on the Readme](https://github.com/sonic2kk/steamtinkerlaunch?tab=readme-ov-file#how-do-i-install-it), and the associated [Steam Flatpak wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Flatpak), as well as the [Steam Flatpak section](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#steam-flatpak) of the Installation wiki page.

You did not attach a log as the issue template requested, and this sounds like user-error, not to mention you're using a version almost a year out of date despite the issue template telling you to use a version based on the latest master before opening an issue, so I will close this issue.
