### ISSUE TITLE
Check if steam is installed

### ISSUE THREAD

**Issue by Mte90** [sonic2kk/steamtinkerlaunch#1058]
So right now executing STL without steam you get this:

```
ven 15 mar 2024, 11:56:37, CET WARN - setSteamPaths - Steam 'userdata' directory not found, other variables depend on it - Expect problems
grep: : File o directory non esistente
grep: : File o directory non esistente
ven 15 mar 2024, 11:56:38, CET ERROR - checkIntDeps - '' was not found! Check 'steamtinkerlaunch --help' for alternatives and/or read 'https://github.com/sonic2kk/steamtinkerlaunch/wiki/Yad'
ven 15 mar 2024, 11:56:38, CET ERROR - checkIntDeps - Yad version '0' is too old. You need to update to at least '7.2'
```

So I think that the tool should check if the steam binary exists, also in my case I don't have yad but is still reporting a version.

**Comment by sonic2kk** [comment]
I noted this on the PR but just for continuity of anyone reading this, we will only do this if we're not running Steam Flatpak (`INFLATPAK -eq 0`).

> also in my case I don't have yad but is still reporting a version.

It's giving `0` which is invalid, so this is fine imo. But also as noted on #1059, we could have improved logging for missing Yad.
