### ISSUE TITLE
Giana Sisters

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#108]
~~Proton 5.13-1 adds SteamLinuxRuntime command line parameters
which currently conflicts _(seems non-fatal)_ with stl as Steam Launch Option.
Might be better for now to use stl as Steam Compatibility Tool for now.~~

_This is a Giana Sisters support ticket now_

**Comment by frostworx** [comment]
~~Looks like this also breaks mangohud, gamemode and probably other tools which are added as Steam Launch Option.
I'll try to write a proper fix, which automatically disables SteamLinuxRuntime when one of the affected programs is enabled.
will need some changes in the code, probably won't happen today.~~

_(nope, I added a warning instead)_

**Comment by afettouhi** [comment]
So stl doesn't with with Proton 5.13 currently? Because I can't get the Giana Sisters games working with Proton 5.13 and stl.

**Comment by frostworx** [comment]
oh, this bug is fixed.
stl works good with proton 5.13.
As already said you can even disable the steam linux runtime with it.
I even tested both Gianas as I changed wmp10 installation.
as both titles refused to work with proton 5.13 I expanded the tweaks
https://github.com/frostworx/steamtinkerlaunch/tree/master/tweaks/user
Are yours up2date?
Might also help to restart with a clean WINEPREFIX

**Comment by afettouhi** [comment]
I have the latest version installed 2.4.0 and I have tried to run both Giana titles from clean WINEPREFIXes and I can only get to the logo and then it closes.

**Comment by frostworx** [comment]
Please check/attach the logs

**Comment by frostworx** [comment]
I assume cabextract is installed?

**Comment by afettouhi** [comment]
Yes, it is installed. The game works fine with Proton 5.0-9 and stl.

**Comment by frostworx** [comment]
Just checked both titles with a clean wineprefix and bot work fine.
I know they work with proton 5.0-9, that's why I set it in the tweakfiles.
https://github.com/frostworx/steamtinkerlaunch/blob/master/tweaks/user/223220.conf

**Comment by afettouhi** [comment]
I am trying to get it generate a log file with PROTON_LOG=1 but nothing is generated.

**Comment by afettouhi** [comment]
I am using stl via the "stl %command%" btw.

[steam-223220.log](https://github.com/frostworx/steamtinkerlaunch/files/5395217/steam-223220.log)

**Comment by frostworx** [comment]
You're doing it wrong apparently:

- https://github.com/frostworx/steamtinkerlaunch/issues/93
- this is the wrong log
- the wrong log anyway shows that you're using proton-5.13-1b, so above tweak is not used...

**Comment by afettouhi** [comment]
Sorry about that. This should be the correct logs now:

[223220.log](https://github.com/frostworx/steamtinkerlaunch/files/5395234/223220.log)
[lastrun.txt](https://github.com/frostworx/steamtinkerlaunch/files/5395235/lastrun.txt)

**Comment by frostworx** [comment]
Aaah!
`Sat Oct 17 10:56:05 CEST 2020 INFO - switchProton - Tried to switch to Proton 'proton-5.0-10-rc4', but it is not available`

Your Proton 5.0-9 does not have the internal name "proton-5.0-10-rc4", because you don't use the "next" branch.
You could

- switch your Proton 5.0-9 to the next branch
- or copy `/usr/share/stl/tweaks/user/223220.conf` to `/home/af/.config/stl/tweaks/user/` and change WANTPROTON to your minor version

**Comment by afettouhi** [comment]
I am confused now? Do I need to have 5.0-9 installed?

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/issues/112

For Giana, I'll change both tweaks to change to "proton-5.0-9" in a few minutes, which should fix your problem.
It is more sane to depend on a stable than on a "next" version

**Comment by frostworx** [comment]
damn, my steam download is extremely slow again (happens pretty often recently here).
Can you give me the exact version of your stable Proton 5.0
as shown in  `steamapps/common/Proton 5.0/version`?

**Comment by frostworx** [comment]
> I am confused now? Do I need to have 5.0-9 installed?

Yes of course! Giana doesn't seem to work with proton 5.13, that's why I changed the tweak to force an older version.
Does this mean you uninstalled 5.0? This would explain the problem as well.

**Comment by afettouhi** [comment]
Yes, I only have 5.13 installed as of now.

**Comment by afettouhi** [comment]
1591828072 proton-5.0-9

is what shown in steamapps/common/Proton 5.0/version

**Comment by frostworx** [comment]
ok, then there's apparently nothing I could do...
Would have been nice to know before spending any time into this.
https://github.com/frostworx/steamtinkerlaunch/issues/108#issuecomment-710774612
was very misleading then.

**Comment by afettouhi** [comment]
My apology for that. That wasn't my intension. I was under the understanding that the game working with Proton 5.13-1b with the version 2.4.0 that was released yesterday. So the game only works with the 5.0 branch as of now?

**Comment by frostworx** [comment]
Ok, no problem.
Yes, unfortunately Giana doesn't seem to work with 5.13 (looks like some dotnet is broken somehow). That's why I updated the tweak files for both Giana titles yesterday to automatically switch to an older Proton version (the "hardcoded" WANTPROTON="proton-5.0-10-rc4" in the tweakfile does this).
With https://github.com/frostworx/steamtinkerlaunch/issues/108#issuecomment-710774612 I mean that a WANTPROTON needs some check to also accept similar version if the exact one was not found.
Probably most people use the next branch, but I'll change the tweaks in a few minutes to `proton-5.0-9` as it the regular release version.

**Comment by afettouhi** [comment]
OK, sorry for the confusion. So if I understand correctly. If I run Giana Sisters with Proton 5.13, stl will then just switch to the 5.0 branch and launch it with that instead?

**Comment by frostworx** [comment]
Yes, exactly that is the point of `WANTPROTON`
Just updated https://github.com/frostworx/steamtinkerlaunch/commit/cae57d61d0be624e16e2b16d05b4787650e39e41
*works for me*

**Comment by afettouhi** [comment]
Are going to make new release for this change?

**Comment by frostworx** [comment]
no

**Comment by afettouhi** [comment]
For this switching of Proton versions doesn't seem to work. If I launch Giana Sisters with Proton 5.13 stl attempts it seems to switch to 5.0-9 but for some reason it says it is not available but I have it installed. I just tested it with the new 2.4.1 release.

**Comment by frostworx** [comment]
Did you start Proton 5.0-9 at least once after the reinstall. It is probably not extracted yet.
Also possible that the auto-generated `/dev/shm/ProtonCSV.txt` wasn't automatically updated. In that case just remove it.

**Comment by afettouhi** [comment]
No I hadn't launched Proton 5.0-9 after reinstalling it. But I have now, I launched Giana Sisters by forcing it to use Proton 5.0-9 and everything worked a previously. But if I go back and turn off forcing Proton 5.0-9 and just rely on my globally set Proton 5.13 and the switching of stl the game only reaches logo screen and then closes. Here are the logs from that launch

[223220.log](https://github.com/frostworx/steamtinkerlaunch/files/5395554/223220.log)
[lastrun.txt](https://github.com/frostworx/steamtinkerlaunch/files/5395555/lastrun.txt)

**Comment by frostworx** [comment]
So did you check `/dev/shm/ProtonCSV.txt`?

**Comment by afettouhi** [comment]
I did just now and it says

proton-5.13-1b;/home/af/.steam/steam/steamapps/common/Proton 5.13/proton

**Comment by frostworx** [comment]
Hhm, looks like the autodetection in getAvailableProtonVersions fails.
What is the absolute path of your proton 5.0-9 installation? Maybe I simply don't check that path.
No idea if that is fixable, but what you can do is simply adding it manually

**Comment by afettouhi** [comment]
/home/af/.steam/steam/steamapps/common/Proton 5.0/proton

is the path of my Proton 5.0-9 installation

**Comment by frostworx** [comment]
"but what you can do is simply adding it manually
https://github.com/frostworx/steamtinkerlaunch#adding-local-custom-proton"

**Comment by afettouhi** [comment]
> "but what you can do is simply adding it manually
> https://github.com/frostworx/steamtinkerlaunch#adding-local-custom-proton"

I don't see a button to add `Add local Custom Proton`
