### ISSUE TITLE
cheat engine button not click able

### ISSUE THREAD

**Issue by bullghost** [sonic2kk/steamtinkerlaunch#1098]
button on popup window from cheat engine was not click able

## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Arch Linux
- Installation Method: protonup qt Package Manager appimage

## Issue Description
- game setup
  using tinker launch
- tinker launch setup
   tested using protonG 9.4 and protonG 9.2
- tested using cheat engine version 1.7.1 and 1.7.5 

two other game work normal using cheat engine, like ff lightning return, re3
but when i use on hades cheat engine button wont click on any popup window from cheat engine, on cheat engine main window the button work fine

**Comment by sonic2kk** [comment]
SteamTinkerLaunch doesn't support Chest Engine in v12.12, support was removed in v12.0. There is no Cheat Engine button on the UI that I'm aware of.

If this is a game specific issue that you're trying to report then that's not something you do here. If you have a game-specific problem you have to fix it yourself.

**Comment by sonic2kk** [comment]
Also, you're using an outdated version of SteamTinkerLaunch. You should be using a version from master. You can install this with ProtonUp-Qt in Advanced Mode, [as explained on the ProtonUp-Qt wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/ProtonUp-Qt).
