### ISSUE TITLE
STL doesn't load at all, but no clear errors in logs 

### ISSUE THREAD

**Issue by xtrilla** [sonic2kk/steamtinkerlaunch#1106]
## System Information
- SteamTinkerLaunch version: 14.0 20240512-2
- Distribution: Steam Deck
- Installation Method: git master version via Protonup Qt

## Issue Description
I have installed STL via Protonup Qt (Tried both with the non git version and the git version) and when I try to execute a game after changing the compatibility to STL it doesn't open STL menu or the game. I've been checking the logs and I don't see any clear issue. 

I'm sorry if it's something super obvius that I'm missing, but I've been reading different tutorials, watching videos and googling around and I don't seem to be able to find the issue.

I've also tried executing it from desktop mode and game mode, same result (Except in desktop mode I see more messages than in game mode).
## Logs

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/15300546/steamtinkerlaunch.log)

Here is the steamtinkerlaunch log from the last execution, I can add other logs but I don't really know which ones are relevant.

**Comment by sonic2kk** [comment]
I don't use STL on SteamOS and will soon no longer officially advertise support SteamTinkerLaunch on SteamOS, but I'll try to help out.

A lot of the time issues like this are a result of Yad not being correctly downloaded. There was a PR to try to help resolve this but it looks like the internal dependencies check is still being skipped on SteamOS, so perhaps it didn't do too much.

From Desktop Mode, go to `/home/deck/stl/deps/usr/bin` and see if the Yad AppImage file (the actual file or symlink) are > 0 bytes.

You can also run `steamtinkerlaunch cleardeckdeps` if you did not already do so after updating from v12.12 to master, to make sure all dependencies are up-to-date.

If the issue persists after that, run `steamtinkerlaunch settings` from the commandline and copy and paste the terminal output, as it may give some hints on the issue.

I also had a look at your log and I'm not seeing any clear issue either. In a worst case, SteamTinkerLaunch may simply no longer work on SteamOS.

Hopefully something here yields a result! :-)

**Comment by xtrilla** [comment]
Hi!

Yeah, looks like there was an issue with Yad, it was not the right file.

To help anybody that might have the same issue:

- Just clean dependencies with: steamtinkerlaunch cleardeckdeps
- Trigger a new reinstall with for example steamrickerlaunch help
- Check if the app image and symlink are correct in: /home/deck/stl/deps/usr/bin

Thanks for your help @sonic2kk ! It’s a pity that you won’t support SteamOS, but I totally understand it. SteamOS is a nice OS for a gaming handheld, but I guess all the features that make it pretty resilient might also be a pain to work around them.

Anyway, thanks again!

**Comment by sonic2kk** [comment]
Happy gaming!

Yes, SteamOS is not good for tinkering (people even try to heavily mod games on SteamOS) and also I don't use SteamTinkerLaunch on my Steam Deck anymore (got an OLED to replace my LCD). Some people have stepped up to do some testing and while that is awesome there would need to be a "SteamOS support maintainer" otherwise it wouldn't be right to advertise SteamTinkerLaunch support on Steam Deck.

SteamTinkerLaunch won't stop working but I will close issues from anyone who isn't a developer reporting technical limitations. I will just stop advertising support because I don't think it is fair to advertise support for a platform I don't test against.
