### ISSUE TITLE
Allignment and box sizes

### ISSUE THREAD

**Issue by IDeathByte** [sonic2kk/steamtinkerlaunch#111]
Check this 
[gtk.zip](https://github.com/frostworx/steamtinkerlaunch/files/5394575/gtk.zip)
i try fix theme with available options, and now interface look like this
![1](https://user-images.githubusercontent.com/41571062/96319840-2f1c8080-102a-11eb-8f9c-d9c39b30a770.png)

and please, make resizeble window not only from cfg.conf*  :)

**Comment by frostworx** [comment]
I checked the attached zip. A smaller min-width here and there probably is a good idea, but the css in the archive has several parsing errors, so I assume it is work and process, right?
Sorry ,what do you mean with "resizable window not only from cfg.conf"? Did I forget a gui entry?

**Comment by IDeathByte** [comment]
Yep, i just get your entries and tried make a little fixes, like auto-margin and some width changes, for the moment, when him canceling looking like in #104. I never worked with *yad* before and don`t know whats css entries him gets for interface.

And in global settings tab i seem only option *Settings Size Autosave*, but current options for change - only columns for tabs. resize like for typical windows with drag corners not work.

**Comment by frostworx** [comment]
Hehe, I never worked with yad before as well and know nothing about css :)
I used `GTK_DEBUG=interactive` to find the entry names, which was not always easy as well.

Do you say that when `Settings Size Autosave` is enabled and you resize the windows the window sizes are not saved?
This should not happen. Did you check the logs if stl complains about something missing?
If this is the case either updateWinRes or saveNewRes has a problem on your system.

**Comment by IDeathByte** [comment]
No, i mean i can`t change window size by another ways, except edit gui.conf. 
launch log get me this 

[launch_log.txt](https://github.com/frostworx/steamtinkerlaunch/files/5395504/launch_log.txt)

Him try find window_decorations.css for gtk, but cant. I don`t know, maybe KDE haven`t it, or gtk theme what`s i use, but i haven`t troubles with another apps.

hm also i see he drop max-width option. i try to change auto to another values like inherit/50% etc, but it continuously dropped like unsupported option as well.

**Comment by frostworx** [comment]
Well the stl windows don't have a window decoration, but are normally resizable.
You just have to hold left-Alt while resizing the window with holding the right mouse button.
Alternatively you can re-enable the window decoration _(temporarily)_ with some random tool.
_(I have a small "toggle-decorations" _(unknown source)_ mapped on left-Alt + MMB which works here for years)_
Or did I get you wrong again? :)

You know that the errors in your log come from your css changes, don't you?
Sorry, can't help with css, that's why I do no longer work on the css-

**Comment by IDeathByte** [comment]
Oh. By this way resize works properly :)

Yep, as i see it can will be conflict between DE/yad used css engine and current standarts, but i wan`t go so deep :D Now him just drop width value to none/unset and work what i need =)

**Comment by frostworx** [comment]
Ha, nice. Maybe it is a good idea to make window decoration optional.
Yeah, it is really not worth the effort to write a fully fledged gtk css theme for this little gui, that's why I left it at that half good looking state :)

**Comment by frostworx** [comment]
:)
https://github.com/frostworx/steamtinkerlaunch/commit/7cb4e6e1289a1424aebabfda2ba54f0f95bfdb06

**Comment by frostworx** [comment]
Are you still trying something with the css or do you have any unresolved issues in this issue?
Else I'd close this issue.
Btw would you worry a lot if I removed our unfinished transation-README's?
Doesn't look like there's a major interest in the translations at all, so leaving stray incomplete files lying around doesn't make it better. I personally totally have no interest in finishing the german translation at least.

**Comment by frostworx** [comment]
Removing the unfinished READMEs now.
Stay safe!

**Comment by IDeathByte** [comment]
No, i stopped on this version and didn`t make changes any yet.

Unsure about README - i just haven`t time last 2 weeks for finish him, but if you think  are it not critical, no problem with delete him. I just will drop him :)

i will update interface translation on this weekend maybe

**Comment by frostworx** [comment]
Glad to hear from you!
It would be great if you would keep up the core translation whenever you find the time for it.
I just removed the README blobs, as they simply take too much work to keep them up2date (I'm sure you agree with that :))

**Comment by IDeathByte** [comment]
About next ccs changes - debugging its not best way for interface making :D Yad have WebKit support, but without correct entry points, all tries making changes very painful. I try watching yad docs, but all whats i see it`s nude bash in examples :O

All work with css in yad seems something like this:
``` 
yad –center –window-icon=”./Data-icons/scalable/stork.png” –borders=10 –paned –orient=”horizontal” –width=”1200″ 
–height=”640″ –key=”$llkey” \

–title=”Setting_Styles” –sticky –auto-kill –text-align=”left” –focus-field=”2″ \

**Comment by frostworx** [comment]
hehe, to be honest I gave up the css file as it totally is not my cup of tea and the gui looks good for me with already available other gtk themes _(I wonder though why there is not already a complete steam gtk theme after all those years)_
