### ISSUE TITLE
MO2 Fails to Launch Game

### ISSUE THREAD

**Issue by GodPhase777** [sonic2kk/steamtinkerlaunch#1116]
## System Information
- SteamTinkerLaunch version:  v14.0.2024526-3
- Distribution: Arch Linux, SteamOS
- Installation Method: ?

## Issue Description
Regardless of setting MO2 fails to detect steam and fails to launch any game. It seems there's no way to launch a modded game aside from through MO2 but it doesn't function.

## Logs
Tue May 28 02:49:49 PM EDT 2024 INFO - setflatpak - started SteamTinkerLaunch from /home/deck/stl/prefix/steamtinkerlaunch
Tue May 28 02:49:49 PM EDT 2024 INFO - initAID - Set AID from STEAM_COMPAT_APP_ID to '22380'
Tue May 28 02:49:49 PM EDT 2024 INFO - initAID - Set OSCDP to STEAM_COMPAT_DATA_PATH '/home/deck/.local/share/Steam/steamapps/compatdata/22380'
Tue May 28 02:49:49 PM EDT 2024 INFO - main - Current SteamTinkerLaunch working directory is '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas'
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLangFile - Language from command line is 'english'
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/deck/stl/prefix/lang'
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLangFile - Loading language file from script directory '/home/deck/stl/prefix/lang/english.txt'
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLanguage - Loading STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf'
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLanguage - STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf' is 'english'
Tue May 28 02:49:49 PM EDT 2024 INFO - steamdedeckt - Seems like we have a Steam Deck here - making some specific settings
Tue May 28 02:49:49 PM EDT 2024 INFO - steamdedeckt - Did not detect a running 'gamescope' process - assuming we're running in Desktop Mode
Tue May 28 02:49:49 PM EDT 2024 INFO - steamdedeckt - Set 'FIXGAMESCOPE' to '0'
Tue May 28 02:49:49 PM EDT 2024 INFO - steamdedeckt - Set 'SMALLDESK' to '1'
Tue May 28 02:49:49 PM EDT 2024 INFO - steamdedeckt - Looks like we have a game but we're running from the Steam Deck install Prefix, not doing any updating here!
Tue May 28 02:49:49 PM EDT 2024 INFO - steamdedeckt - Seems like we're being run by Steam here, not doing any installation steps
Tue May 28 02:49:49 PM EDT 2024 INFO - setLocalInstall - Looks like we don't have a local non-root install
Tue May 28 02:49:49 PM EDT 2024 INFO - updateConfigEntry - Option 'GLOBALCOLLECTIONDIR' is updated with the new value '/home/deck/stl/prefix/collections' in config 'global.conf'
Tue May 28 02:49:49 PM EDT 2024 INFO - getCurrentCommandline - No Proton in command line arguments 'mo2 start'
Tue May 28 02:49:49 PM EDT 2024 INFO - saveOrgVars - Storing some original variables to restore them later
Tue May 28 02:49:49 PM EDT 2024 INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
Tue May 28 02:49:49 PM EDT 2024 INFO - emptyVars - Set $PATH to '/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/deck/stl/deps/usr/bin::/home/deck/stl/deps/usr/bin:'
Tue May 28 02:49:49 PM EDT 2024 START - ######### Initializing Game Launch 22380 using SteamTinkerLaunch v14.0.20240526-3 #########
Tue May 28 02:49:49 PM EDT 2024 INFO - main - Starting with a clean log
Tue May 28 02:49:49 PM EDT 2024 INFO - main - Start creating default configs
Tue May 28 02:49:49 PM EDT 2024 INFO - createDefaultCfgs - START
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLangFile - Language from command line is 'english'
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/deck/stl/prefix/lang'
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLangFile - Loading language file from script directory '/home/deck/stl/prefix/lang/english.txt'
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLanguage - Loading STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf'
Tue May 28 02:49:49 PM EDT 2024 INFO - loadLanguage - STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf' is 'english'
Tue May 28 02:49:49 PM EDT 2024 INFO - createDefaultCfgs - setSteamPaths:
Tue May 28 02:49:49 PM EDT 2024 INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
Tue May 28 02:49:50 PM EDT 2024 INFO - getGameOS - Starting game OS detection
Tue May 28 02:49:50 PM EDT 2024 WARN - getGameOS - Could not extract the full game binary path from the incoming game launch command, so assuming this is a Windows game!
Tue May 28 02:49:50 PM EDT 2024 INFO - setWin - '' determined to be a Windows Game
Tue May 28 02:49:50 PM EDT 2024 INFO - createDefaultCfgs - createProtonList:
Tue May 28 02:49:50 PM EDT 2024 INFO - createDefaultCfgs - createProtonList end
Tue May 28 02:49:50 PM EDT 2024 INFO - listAllSettingsEntries - '/dev/shm/steamtinkerlaunch/setentries.txt' already exists - nothing to do
Tue May 28 02:49:50 PM EDT 2024 INFO - createDefaultCfgs - STOP
Tue May 28 02:49:50 PM EDT 2024 SKIP - listSteamLibraries - not recreating already available '/dev/shm/steamtinkerlaunch/SteamLibraries.txt'
Tue May 28 02:49:50 PM EDT 2024 INFO - setSteamLibraryPaths - STEAM_COMPAT_LIBRARY_PATHS set to '/home/deck/.local/share/Steam/steamapps:/run/media/deck/General 1TB/steamapps'
Tue May 28 02:49:50 PM EDT 2024 INFO - setSteamLibraryPaths - STEAM_COMPAT_MOUNTS set to '/home/deck/.local/share/Steam/steamapps/common/Steamworks Shared:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'
Tue May 28 02:49:50 PM EDT 2024 INFO - setSteamLibraryPaths - STEAM_COMPAT_TOOL_PATHS set to '/run/media/deck/General 1TB/steamapps/common/Proton 9.0 (Beta)::/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime:/home/deck/.local/share/Steam/steamapps/common/Steamworks Shared:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'
Tue May 28 02:49:50 PM EDT 2024 INFO - main - Checking internal dependencies:
Tue May 28 02:49:50 PM EDT 2024 INFO - checkIntDeps - Skipping yad version check on SteamDeck
Tue May 28 02:49:50 PM EDT 2024 INFO - main - Initializing first Proton:
Tue May 28 02:49:50 PM EDT 2024 INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/steamtinkerlaunch/ProtonCSV.txt' which was created during a previous run
Tue May 28 02:49:50 PM EDT 2024 INFO - initFirstProton - Initializing Proton
Tue May 28 02:49:50 PM EDT 2024 INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/deck/.config/steamtinkerlaunch/default_template.conf' is 'proton-9.0-beta16'
Tue May 28 02:49:50 PM EDT 2024 INFO - main - Initializing default window resolution
Tue May 28 02:49:50 PM EDT 2024 INFO - setInitWinXY - Using '1280x800' from config '/dev/shm/steamtinkerlaunch/defres.txt'
Tue May 28 02:49:50 PM EDT 2024 INFO - main - Welcome to SteamTinkerLaunch
Tue May 28 02:49:50 PM EDT 2024 INFO - removeEmptyFiles - Removing empty files from '/home/deck/.config/steamtinkerlaunch/games/appinfo'
Tue May 28 02:49:50 PM EDT 2024 INFO - removeEmptyFiles - Removing empty files from '/home/deck/.config/steamtinkerlaunch/games/header'
Tue May 28 02:49:50 PM EDT 2024 SKIP - setGDKBackend - XDG_SESSION_TYPE is defined and is not Wayland, it is 'x11' - No need to set GDK_BACKEND=x11 as it will already default to X11
Tue May 28 02:49:50 PM EDT 2024 INFO - main - Checking command line: incoming arguments 'mo2 start'
Tue May 28 02:49:50 PM EDT 2024 INFO - setMO2Vars - Found the variable for the game wineprefix '/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx', so using a portable instance of 'mo2'
Tue May 28 02:49:50 PM EDT 2024 INFO - setMO2Vars - The mo2 helper-file is set to '/home/deck/stl/prefix/misc/mo2games.txt'
Tue May 28 02:49:50 PM EDT 2024 INFO - setMO2Vars - Preparing Proton variables for a portable mo2 instance
Tue May 28 02:49:50 PM EDT 2024 INFO - setMO2Vars - Using proton version 'proton-9.0-beta16', which is currently configured for the game none
Tue May 28 02:49:50 PM EDT 2024 INFO - setMO2Vars - Using proton-9.0-beta16 for ModOrganizer
Tue May 28 02:49:50 PM EDT 2024 INFO - setModWine - DNPROTON is '/run/media/deck/General 1TB/steamapps/common/Proton 9.0 (Beta)/proton'
Tue May 28 02:49:50 PM EDT 2024 INFO - setModWine - DNPROTON is a file -- it is '/run/media/deck/General 1TB/steamapps/common/Proton 9.0 (Beta)/proton'
Tue May 28 02:49:50 PM EDT 2024 SKIP - prepareMO2 - portable instance running - nothing to prepare
Tue May 28 02:49:50 PM EDT 2024 INFO - prepareMO2 - No ModOrganizer instance provided
Tue May 28 02:49:50 PM EDT 2024 INFO - setMO2Vars - The 'mo2' instance was already set to 'portable' during this run
Tue May 28 02:49:50 PM EDT 2024 INFO - setMO2Vars - The mo2 helper-file is set to '/home/deck/stl/prefix/misc/mo2games.txt'
Tue May 28 02:49:50 PM EDT 2024 INFO - setMO2DLMime - Desktopfile '/home/deck/.local/share/applications/ModOrganizer-steamtinkerlaunch-dl.desktop' looks to be up2date
Tue May 28 02:49:50 PM EDT 2024 INFO - startMO2 - Starting '/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/Modding/MO2/ModOrganizer.exe'
Tue May 28 02:49:50 PM EDT 2024 INFO - updateMO2PortConf - Updating '/home/deck/.config/steamtinkerlaunch/mo2/dldata/newvegas.conf' with up to date data
Tue May 28 02:49:50 PM EDT 2024 INFO - startMO2 - WINEDEBUG="-all" WINEPREFIX="/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx" "/run/media/deck/General 1TB/steamapps/common/Proton 9.0 (Beta)/files/bin/wine" "/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/Modding/MO2/ModOrganizer.exe"

**Comment by sonic2kk** [comment]
What version of ModOrganizer 2 is being used here? Did you perhaps try to install ModOrganizer 2 v2.5.0 with an older version of SteamOS first? Also, what have you already tried before reporting the issue? This can help give an idea of what steps to provide apart from general troubleshooting.

Modding games on SteamOS usually does not work, some have reported success, others not. You can try a few things:
- Verify the MO2 version. If you are trying to use ModOrganizer v2.5.0, follow the [guidance on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#modorganizer-2-v250) to remove it and try re-installing. The only confirmed working version of ModOrganizer 2 is v2.4.4 (there are ***zero*** one-hundred-percent-confirmed working versions on SteamOS).
    - Note that if you previously installed an older version of SteamTinkerLaunch you should have ran `steamtinkerlaunch cleardeckdeps` with the version from master in order to pull updated dependencies.
- Ensure that you have a working Standalone Mode MO2 installation (installed with `steamtinkerlaunch mo2 start`) at `~/.config/steamtinkerlaunch/mo2/compatdata/pfx`. Make sure the expected MO2 files are installed at the right place in the prefix, etc.
- Check to see if `/dev/shm/steamtinkerlaunch` has any additional logs that might be useful.
- Check if `steamtinkerlaunch mo2 start` works from Desktop Mode. If not, provide the error output.
    - If it is something along the lines of kernel32 error, try `steamtinkerlaunch mo2 repairpfx`.
- Check if MO2 launches with your game from Desktop Mode.
-  Anything else you can think of that I may have missed (I don't use MO2).

However I would suggest not modding games on SteamOS, and expecting them to not work is a given. I don't even use SteamTinkerLaunch on SteamOS anymore and will soon no longer advertise support for the platform.

Out of interest, are you using SteamOS Preview? Perhaps the `innoextract` dependency needs bumped again for the newer Arch base.

<hr>

As an aside, it was noted in passing that ModOrganizer 2 v2.5.0 cannot launch games in #1110. If ModOrganizer 2 actually launches for you, verify the location of the executable is correct as well.

**Comment by GodPhase777** [comment]
1. I tried after using 2.4.4 to update to see if that would fix it, but I had to reinstall MO2 after moving Fallout New Vegas off my C drive (Which also deleted all my mod files ;[ )
2. Checked that path, there is no /pfx. I am still quite a noob so maybe I didn't do something right?
3. Not sure which ones will be useful, so I'll just send these unless you know of any other useful ones. Hopefully this is it.
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/15478050/steamtinkerlaunch.log)
[steamtinkerlaunch-launchSteamGame-STARTDEBUG.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/15478051/steamtinkerlaunch-launchSteamGame-STARTDEBUG.txt)
[steamtinkerlaunch-iscriptevaluator-22380.log](https://github.com/sonic2kk/steamtinkerlaunch/files/15478054/steamtinkerlaunch-iscriptevaluator-22380.log)
[startMO2_.log](https://github.com/sonic2kk/steamtinkerlaunch/files/15478056/startMO2_.log)
4. I opened konsole and tried it out, both with and without a /. infront, since I think I read that worked for someone. Said steamtinkerlaunch isn't a command so I think I somehow didn't install it properly? I'm not sure.
5. MO2 doesn't launch in any circumstance, regardless of how I set things up. Game never launches modded.
6. How do I find the executable? I'm not quite sure where to look for it. For me it seems modding data is downloaded to home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/ but from there I have no clue where stuff for this is stored.

**Comment by sonic2kk** [comment]
> (Which also deleted all my mod files ;[ )

I would expect to lose all mod files at any time when modding in general. Remember that MO2 by default installs mods in the prefix for that game, so if you want to preserve them you can try moving them elsewhere.

I have heard that there are issues with games being installed and modded on external storage, so perhaps putting your game on the main drive and setting the mod folder to another location would help.

Although, I'm not sure how you had any mod files to begin with, if ModOrganizer 2 doesn't work? If you tried to mod the game before, or had an existing modded installation from another PC, please note that this will **not** work. **All** modding must be done on one device only. If you are using any external storage also make sure this is formatted to ext4 and not NTFS (Proton does not support NTFS very well).

> Checked that path, there is no /pfx. I am still quite a noob so maybe I didn't do something right?

Remove any existing MO2 installation in your game prefix(es) and run `/home/deck/stl/prefix/steamtinkerlaunch mo2 start`. It would be interesting to know if it errors or if it hangs.

Also, keep in mind that SteamTinkerLaunch is for Linux enthusiasts, on SteamOS it is primarily a tool for those more on the developer-side. If you're new to Linux and/or don't have much experience with Wine, modding games on Linux may need a bit of experimentation to get up-to-speed.

>  opened konsole and tried it out, both with and without a /. infront, since I think I read that worked for someone. Said steamtinkerlaunch isn't a command so I think I somehow didn't install it properly? I'm not sure.

I don't know how you installed SteamTinkerLaunch (you put "Installation Method" as "?" at time of writing) but did you add it to path? If not, you'll either need to do so, or you'll need to specify the full path (probably `/home/deck/stl/prefix/steamtinkerlaunch`.

> MO2 doesn't launch in any circumstance, regardless of how I set things up. Game never launches modded.MO2 doesn't launch in any circumstance, regardless of how I set things up. Game never launches modded.

If you mod games with MO2, it uses a Virtual Filesystem to load the mods, so launching with MO2 will not result in any mods. If MO2 itself doesn't launch it sounds like something went wrong with installation.

<hr>

Thanks for the logs but sadly they don't have much, which is quite unusual. `WSALookupServiceBegin` is fairly common, and I'm not seeing any information here that points to a crash. Is the process hanging and simply not launching, or does the entire process crash? A good way to check is if all Proton/Wine related processes disappear.

I would recommend re-installing MO2. The following steps may help (I will assume that the `steamtinkerlaunch` script is not on your PATH, so I'll fully qualify the path here for clarity):
1. Remove the existing installation in your New Vegas prefix (or the prefix for any other game you tried to use MO2 with). This is probably at the following location, although please confirm before deleting any files: `/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/Modding`. If this exists AND if it looks correct to you, you can remove, move, or rename this folder.
2. Run `/home/deck/stl/prefix/steamtinkerlaunch cleardeckdeps` to ensure the `innoextract` dependency in particular is up-to-date.
3. Run `/home/deck/stl/prefix/steamtinkerlaunch help` to redownload all dependencies.
4. Verify that the dependecies in `/home/deck/stl/deps/usr/bin` are not only present (a Yad AppImage, a symlink to this Yad AppImage, `cabextract`, and `innoextract`) but also ensure that they have a filesize above zero. You can also check if `innoextract` is correct by running from terminal `/home/deck/stl/deps/usr/bin/innoextract --version` and making sure that it returns expected output and not a segfault or something. If you encounter any issues here, repeat Steps 2 and 3.
5. Install ModOrganizer 2 with `/home/deck/stl/prefix/steamtinkerlaunch mo2 start`. I'm not sure how you installed it before but it isn't correct. I'm not sure at all actually how this keeps coming up [as the wiki gives guiidance](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#command-line) how to install ModOrganizer 2... Although some people are more inclined to read random guides on the internet than to read the docs or code.
6. If it still does not start, run `/home/deck/stl/prefix/steamtinkerlaunch mo2 start` and paste the output here.

**Comment by GodPhase777** [comment]
I'm currently working on switching over to rockerbacons MO2 for linux, maybe to keep the steamdeck support you could work with rockerbacon a bit as it seems a bit more stable. To clarify MO2 did work, however I couldn't get it to recognize steam being open, so it wouldn't open any steam related games.

**Comment by sonic2kk** [comment]
I'm not interested in SteamOS support in general these days, so the community are the ones that will have to contribute support, including for MO2 (someone who has it working on SteamOS already did so).

It's probably best to use a tool designed for modding, SteamTinkerLaunch is not a modding tool, it's an enthusiast tool, and is my contributions are almost exclusively for the Linux Desktop users 👍

And on the stability comment, modding on SteamOS isn't stable regardless of what you do. So remember to exercise caution and keep backups of your mods and mod profiles and so on.
