### ISSUE TITLE
How can I set,which start options will be used if I type "stl %command%" in the launch options?

### ISSUE THREAD

**Issue by ghost** [sonic2kk/steamtinkerlaunch#113]
Maybe I just missed it,but I can't find it in "How to use".

**Comment by frostworx** [comment]
The README is pretty big meanwhile.
What you are searchin is probably this chapter a little bit below:
https://github.com/frostworx/steamtinkerlaunch#game-specific-use

**Comment by ghost** [comment]
I can now go into the settings menu,but if I activate Mangohud for example,it doesn't work in game. (The game uses OpenGL)
Do I have to do something other to activate MangoHud for OpenGL Games? (Without `stl %command%` I would have to do `MANGOHUD_DLSYM=1 mangohud %command%` for OpenGL games).

**Comment by frostworx** [comment]
Sorry, you need to ask the MangoHud dev for this.
stl only uses the variable if MangoHud is enabled, no own code involved.

**Comment by ghost** [comment]
So I would have to do ">name of the program< stl %command%" If I want to use a program with stl,or do I get something wrong?
Edit:I forgot to type ">name of the program<"
