### ISSUE TITLE
MO2 won't downloads mod from Nexus.

### ISSUE THREAD

**Issue by hawari21** [sonic2kk/steamtinkerlaunch#1139]
So, i just install MO2 and activate my API key and so far so good, until i download mod from nexus and it won't download anything. And i go to option to associate with NXM link but no avail so far, any advice?

Edit : when i clicked NXM associated there is a message in mo2 logs : [2024-07-10 07:22:34.196 W] [creationgameplugins.cpp:131] Z:/home/haw/.config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/users/USERNAME/AppData/Local/ModOrganizer/Fallout 4/profiles/Default/plugins.txt empty

Edit : with XDG i got this gio: nxm://fallout4/mods/47327/files/191018?key=RYXiruOXF6fJY14MTz0mpw: The specified location is not supported

**Comment by hawari21** [comment]
Damn...somehow i got working again after i deleted ModOrganizer-steamtinkerlaunch-dl.desktop . So weird..

**Comment by sonic2kk** [comment]
You purposefully ignored the issue template, which means you didn't provide the SteamTinkerLaunch version you're using (are you using latest master which contains #1096?), your distribution (SteamOS for example is known to be entirely broken and is no longer tested against), and a log file.

Sounds like it's fixed anyway. But as the issue template that you removed from this issue noted, issues that don't follow the template are closed.

Also, for what it is worth, I don't recommend using these links with any software or operating system.
