### ISSUE TITLE
HMM starts, but is an empty window.

### ISSUE THREAD

**Issue by Rykita** [sonic2kk/steamtinkerlaunch#1144]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Arch Linux (kernel: 6.9.5-zen)
- Installation Method: ProtonUp-Qt

## Issue Description
Upon starting HMM after installing it, HMM displays as an "empty window". Alt-tabbing to it doesn't change anything either, it shows up in htop and the task bar but has no rendering at all and it's very hard for me to also tell if it's accepting input because of that (to determine if it's just the rendering or the entire app dying). 

## Logs
[steamtinkerlaunch.log](https://github.com/user-attachments/files/16385509/steamtinkerlaunch.log)
[startHMM.log](https://github.com/user-attachments/files/16385511/startHMM.log)

## Picture
![2024-07-26_03-28](https://github.com/user-attachments/assets/c6eb7da8-db36-4f86-94ee-073c3a0362b0)

**Comment by Rykita** [comment]
I forgot to apply a proper label for HMM, my apologies. Please feel free to add it.

**Comment by sonic2kk** [comment]
I don't think you can apply labels, it's fine.

This doesn't sound like a SteamTinkerLaunch issue but a Wine issue, as window rendering are not SteamTinkerLaunch bugs. If HedgeModManager starts then there's nothing I can do beyond that. This sounds like a problem with Wine and Hedge Mod Manager, maybe it would be worth trying some different Wine versions?

I have only tested HedgeModManager on KDE Plasma Wayland and it has traditionally worked fine, but I think the last version I tested with is still Proton 8.

Also, you're using a very out-of-date version of SteamTinkerLaunch (although no one has come forward to help out with Hedge Mod Manager... ever, actually, to my knowledge). Please use SteamTinkerLaunch from master, you can install this with `SteamTinkerLaunch-git` from ProtonUp-Qt.

**Comment by sonic2kk** [comment]
You could try running HedgeModManager from [GameScope](https://github.com/ValveSoftware/gamescope) if you have that installed (with `--backend sdl`). You can do that with `gamescope --backend sdl -- WINEPREFIX="/home/rykita/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx" "/home/rykita/.local/share/Steam/steamapps/common/Proton - Experimental/files/bin/wine" "/home/rykita/.config/steamtinkerlaunch/downloads/hedgemodmanager/HedgeModManager.exe"`. That tends to work around various rendering issues, although not all of them.

**Comment by Rykita** [comment]
I appreciate the quick response, by default I use KDE X11 but now I have tested using Wayland. I also enabled and disabled DXVK to see if that could be the culprit (it was not.)

I do have GameScope installed on my PC, as I run Steam from it. I executed your command, and after re-checking, it seems fine and all the directories match up, but I get an error returned to me:

$ gamescope --backend sdl -- WINEPREFIX="/home/rykita/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx" "/home/rykita/.local/share/Steam/steamapps/common/Proton - Experimental/files/bin/wine" "/home/rykita/.config/steamtinkerlaunch/downloads/hedgemodmanager/HedgeModManager.exe"

No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
vulkan: physical device 10de:1e84 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce RTX 2070 SUPER': queue family 0 (general queue family 0)
vulkan: physical device supports DRM format modifiers
wlserver: [backend/headless/backend.c:67] Creating headless backend
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344241 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344258 (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   RG16 (0x36314752)
vulkan:   NV12 (0x3231564E)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
vulkan: Creating Gamescope nested swapchain with format 64 and colorspace 0
wlserver: Using explicit sync when available
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:17] Starting headless backend
wlserver: Successfully initialized libei for input emulation!
wlserver: [xwayland/sockets.c:64] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:107] Starting Xwayland on :2
wlserver: [types/wlr_compositor.c:771] New wlr_surface 0x6537ebb1d3c0 (res 0x6537ebb17fb0)
wlserver: [xwayland/server.c:272] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 84
vblank: Using timerfd.
xwm: execvp failed: No such file or directory
gamescope: children shut down!
terminate called without an active exception
(EE) failed to read Wayland events: Broken pipe
Aborted (core dumped)


----

For the sake of clarity I will also list my GPU and CPU:

GPU: NVIDIA RTX 2070 Super 
CPU: AMD Ryzen 5 3600

I use nvidia-dkms drivers (so that they work with linux-zen)

I tried using GameScope via both Wayland and X11 but to no avail. I am grateful for the help along the way, even if the issue doesn't get solved or is out of scope.

**Comment by Rykita** [comment]
My wine version is also 9.11

**Comment by Rykita** [comment]
Just tried launching HedgeModManager.exe manually, without using SteamTinkerLaunch as an intermediate (i.e, not using stl hmm start) and the GUI displays properly.

**Comment by Rykita** [comment]
> Just tried launching HedgeModManager.exe manually, without using SteamTinkerLaunch as an intermediate (i.e, not using stl hmm start) and the GUI displays properly.

I installed a HUD mod, installing from a 7z archive didn't work but installing from a folder works just fine, I am assuming that it means any other mod works aswell... _really_ bizarre though.

**Comment by sonic2kk** [comment]
If you're not using SteamTinkerLaunch you're probably running with your system wine. The Wine version you gave is your system Wine. This suggests a problem with Proton Experimental / Valve Proton (which most Proton flavours are built against).

This does not sound like a SteamTinkerLaunch issue, but more of a system / Proton issue, which are not SteamTinkerLaunch bugs. So I will close this issue for now and keep the third-party limitation label.
