### ISSUE TITLE
I can't see a way to set steamtinkerlaunch as the default compatibility tool

### ISSUE THREAD

**Issue by Globetrotter129** [sonic2kk/steamtinkerlaunch#1146]
SteamTinkerLaunch is the only way I can get vkbasalt to work on bazzite which i need for using the XR Gaming plugin for xr glasses. So steamtinkerlaunch compatibility tool by default would be ideal.

**Comment by sonic2kk** [comment]
You can do this from the Steam settings, the same way you can for any other compatibility tool.

**Comment by sonic2kk** [comment]
Turned my laptop on and got a screenshot from the Steam Client for you.

![Screenshot_20240727_145332](https://github.com/user-attachments/assets/c0682966-7fe3-4b48-8662-d09837fbb83d)

This is not a SteamTinkerLaunch issue.
