### ISSUE TITLE
Flawless Widescreen Bug?

### ISSUE THREAD

**Issue by SlinkSalmon50** [sonic2kk/steamtinkerlaunch#1150]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Fedora/Nobara Linux
- Installation Method: ProtonUp-Qt(Flatpack)

## Issue Description
Whenever I enable Flawless Widescreen in the steamtinkerlaunch game settings (Watch_Dogs is the game I was using at the time) It will install vcredist packages every single time, boot Flawless Widescreen and then the game never boots unless I close FW which negates the point of installing it since it won't run with the game.

Unsure if this is a bug or if something is wrong with my install

**Comment by sonic2kk** [comment]
v12.12 is not supported (it is approximately 17 months old), only the latest commit to master is supported. Have you tried this with a supported version of SteamTinkerLaunch from master? There were a few FlawlessWidescreen issues that were fixed months ago. The [changelog](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog) also noted a couple of changes to FlawlessWidescreen in master.

You can download SteamTinkerLaunch-git from ProtonUp-Qt [as documented on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/ProtonUp-Qt#installation).

Only one application running at a time per-prefix is something Steam tries to enforce, SteamTinkerLaunch tries to workaround it and so far it seems to have worked for FlawlessWidescreen in my testing.

If it continues to not work, a PR would be appreciated.

**Comment by SlinkSalmon50** [comment]
You have no idea how much it means to me that you responded to this, that fixed it for me. I apologize if posting a bug report was the wrong way to go about this I posted elsewhere numerous times to no avail. Seriously thank you so much. Im new to Linux and so far things have been buttery smooth aside from a few hiccups, again thank you!!!!!

**Comment by sonic2kk** [comment]
No worries, happy gaming!

Although as a courtesy note, SteamTinkerLaunch is intended for experienced Linux users and tinkerers.
