### ISSUE TITLE
The SpecialK option does nothing

### ISSUE THREAD

**Issue by SmurgBurglar** [sonic2kk/steamtinkerlaunch#1163]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Garuda Linux
- Installation Method: Octopi Packager Garuda Builder <team@garudalinux.org>

## Issue Description
The SpecialK option in Game Menu does nothing in every game I have tried, whereas placing the Specialk32/64.dll's in their directories with the appropriate name does.

## Logs
[steamtinkerlaunch.log](https://github.com/user-attachments/files/16909618/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Have you tried tried with an up-to-date version of SteamTinkerLaunch? v12.12 is from March 2023, and only the latest commit to master is ever supported. There have been significant ReShade changes since v12.12 as well, see the changelog for details.

Be sure to remove any lingering ReShade files and follow the documentation on the wiki.

Also confirm that SteamTinkerLaunch is placing the ReShade DLLs in the right directory, and if not, choose an alternative EXE directory.

**Comment by sonic2kk** [comment]
Looking at the log, it looks like SteamTinkerLaunch is not attempting to install ReShade. It seems like it was not enabled correctly, or is no longer working in such an old version.

As above, try from `master`, and make sure ReShade is definitely enabled, following the guidance on the [SteamTinkerLaunch ReShade wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/ReShade#usage).

**Comment by SmurgBurglar** [comment]
> Looking at the log, it looks like SteamTinkerLaunch is not attempting to install ReShade. It seems like it was not enabled correctly, or is no longer working in such an old version.
> 
> As above, try from `master`, and make sure ReShade is definitely enabled, following the guidance on the [SteamTinkerLaunch ReShade wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/ReShade#usage).

Thanks, updating though ProtonUp-Qt to the git version did it, but even though it installs SpecialK games crash if I launch them with STL as the compatibility tool but not if I use GE-Proton.
[steamtinkerlaunch.log](https://github.com/user-attachments/files/16917395/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Sounds like a compatibility issue, GE-Proton is going to have better compatibility I would say.

I had the same issues before, disabling d3dcompiler_47 I think is what fixed it for me with regular Proton.

I think this is solved if SteamTinkerLaunch-git works with GE-Proton.
