### ISSUE TITLE
Unclear on the various Gamescope options

### ISSUE THREAD

**Issue by winteriscariot** [sonic2kk/steamtinkerlaunch#1171]
This isn't a bug, but discussions aren't enabled on this repo so I'll go ahead and post it here.

Currently there are at least 2 places that you can set gamescope options:

1. via the 'gamescope' button on the main menu
2. via the Default menu

I get that the Default menu should, presumably, be the default, if you don't change any gamescope settings for a specific game, and presumably a game-specific gamescope config would override the default. The confusion comes from the fact that you can set gamescope options in the 'default' title (31337; `systemtinkerlaunch settings default`)

If you set the 31337 game's gamescope options, and also set the Default menu gamescope options, which one is respected as the 'default'? Or is the gamescope config on 31337 ignored since it's not a real game?

**Comment by winteriscariot** [comment]
I think I answered my own question, as I believe the config on 31337 doesn't matter since you'll never actually launch that game.

**Comment by sonic2kk** [comment]
Indeed, 31337 is the placeholder AppID. You should not be using SteamTinkerLauch in the way you described, SteamTinkerLaunch is only for use with games launched via Steam. `steamtinkerlaunch settings` launches the settings menu for the last used game but is primarily a debugging command.

The "default" doesn't do anything. I don't know if that's even a valid argument?
