### ISSUE TITLE
STL menu not showing up when launching via Steam Library however shows up when running it via terminal

### ISSUE THREAD

**Issue by Oroborius** [sonic2kk/steamtinkerlaunch#1174]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Arch Linux (KDE Wayland)
- Installation Method: Package Manager (Pacman)

## Issue Description
When launching STL via compat tool through game launch no menu shows up. It had been working previously however isn't anymore unfortunately. Possible related issue to ffmpeg vs ffmpeg-obs? Only thing I had changed really. The menu will show up when launching `steamtinkerlaunch settings` for a different game at times and oddly enough opening this menu via mid "attempted" launch from in Steam Library and then closing it actually causes the end dialogue to show up stating the time that said game launched for post closing. Clicking the retry with new settings actually allows configuring of the program and launching it but that original launch will sit there for what a reason I'm not sure of an extremely long time to forever possibly.

## Logs
[steamtinkerlaunch.log](https://github.com/user-attachments/files/17156825/steamtinkerlaunch.log)

## Terminal Output
`steamtinkerlaunch settings
find: ‘/home/oroborius/.local/share/Steam/userdata/1822418133/config/grid’: No such file or directory`

**Comment by sonic2kk** [comment]
You are using SteamTinkerLaunch v12.12, despite the issue template asking you to use `master`. Please try updating. v12.12 is from March 2023, and there is no reason to be using stable releases of a Bash script.

This issue looks identical to #1170, it is a Proton version mismatch which the wiki already explains how to resolve; remove `/dev/shm/steamtinkerlaunch` if a Proton version updates. `master` has better mismatch version handling and may work as well. This appears to be caused in your case by updating to Proton 9.0-3 without clearing `/dev/shm/steamtinkerlaunch`. You can check the log file to confirm this.

Also, `steamtinkerlaunch settings` is not the primary way to use SteamTinkerLaunch. Launching it from Steam games is the correct way. I have no idea why there has been a surge the last week or so of people using `steamtinkerlaunch settings` and _only_ that. This command can be used, but you should be running SteamTinkerLaunch from Steam, with Steam games, when using the GUI. If you want to modify settings without the GUI you can always edit the config files manually, which is perfectly valid.

<hr>

The Terminal output given is harmless, it means you have never created manual game grids for this user.

**Comment by Oroborius** [comment]
Updating fixes the issue thanks. I didn't realize how dated the AUR package was.
