### ISSUE TITLE
Settings Menu Tabs don't work under wayland

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#118]
Despite being overdramatized and provocative I _(like probably many others)_ used the recent
discussion to check wayland again after a long time _(some glitches here and there and obvious things missing, but I liked wayfire, sway was not my cup of tea. Will stick with X for now - but that's not the point)_.

Just in case people using steamtinkerlaunch using wayland, the Settings Menu doesn't work correctly under wayland, because
yad tabs open up in a separate window instead of as tab, which breaks the whole menu.
@Faalagorn was so friendly to test this [here](https://github.com/frostworx/steamtinkerlaunch/issues/52#issuecomment-716210978) and while trying to find a small example for an upstream bugreport, I found that it doesn't work generally (see [bugreport/ feature request](https://github.com/v1cont/yad/issues/109))

**Comment by IDeathByte** [comment]
about wayland: now i use plasma under wayland. yep, window drawing incorrect, but i found this:
https://bbs.archlinux.org/viewtopic.php?pid=1662783#p1662783

with GDK_BACKEND=x11 it all work nice.
it possible to make pre-launch environment check?

**Comment by frostworx** [comment]
When you follow my bugreport above you see that this didn't work for me _(was just a quick test, maybe I botched it up :))_
Currently, I'm rewriting the whole gui anyway and might drop tabs completely in favor of separate menus,
so this might be no longer a problem whenever I'm done.

**Comment by frostworx** [comment]
fixed in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v3.1.335
