### ISSUE TITLE
stl installs 32-bit dll from reshade to witcher 3 game folder

### ISSUE THREAD

**Issue by dumbledurf** [sonic2kk/steamtinkerlaunch#1181]
## System Information
- SteamTinkerLaunch version: steam os 3.6 v14.0.20240705-1
- Distribution: steamos
- Installation Method: protonup-qt

pretty much what the title says. i was trying to figure out why reshade wasnt working on an unmodded game when someone suggested i check the version of the dxgi.dll and yeah stl installed a 32-bit dll. i cant imagine there are even any settings in stl that i could have accidentally ticked to cause that behavior. if there are please let me know. i could really use any advice i can get. Ty for your timerrrrsh
i dont have a log but i copied the dll to a visible folder and ran the file command on it to check the bit  version.
```
file /run/media/deck/4b0ee819-aa95-41eb-8093-597bd6194358/downloads/dxgi.dll
/run/media/deck/4b0ee819-aa95-41eb-8093-597bd6194358/downloads/dxgi.dll: PE32 executable (DLL) (GUI) Intel 80386, for MS Windows, 6 sections
```

**Comment by sonic2kk** [comment]
I'm going to need a log to help more, to know what executable SteamTinkerLaunch is checking and if that executable is 32bit.

Does The Witcher 3 use a launcher by any chance, and if so, is that launcher what SteamTinkerLaunch is checking as 32bit? If so, try selecting an Alternative EXE from the Game Menu to check, so that SteamTinkerLaunch will check the architecture of that.

If SteamTinkerLaunch is checking the right executable, and that executable is 32bit, then I don't know why 32bit ReShade would be invalid.

**Comment by dumbledurf** [comment]
sorry i cant provide a log because i uninstalled stl after finally realizing that it wouldnt be able to help me with my use case at this time. i didnt think to save the logs first, sorry. simply downloaded reshade manually and ran the executable in proton and reshade vwas installed properly. no adjustments necessary. i did have an alt exe selected in the stl game menu because there is a launcher for the witcher 3. reshade was installed to the right directory but a 32-bit dll was installed. i only realized this after many hours of troubleshooting different causes for why it might not be working so i promise i am absolutely not mistaken about that. i hope you wont write this off as user error because i dont think it was this time around. anyways ty for the work you guys do to improve the user experience on linux

**Comment by sonic2kk** [comment]
I will close this issue, if someone encounters this in future they can report it, but I will have to write it off as user error or some Steam Deck-specific problem.

On the Linux Desktop, ReShade does appear to work fine. If there is a specific issue with this game with detecting the architecture that may be a separate problem, or perhaps the launcher is intercepting the ReShade DLL. Or perhaps a different DLL name is needed.
