### ISSUE TITLE
installing under ubuntu 18.04

### ISSUE THREAD

**Issue by dragonfly-lover** [sonic2kk/steamtinkerlaunch#119]
maybe i need some help to install STL under ubuntu.
Here's what i get when i launch bash script
![image](https://user-images.githubusercontent.com/36678626/97362261-09507080-18a1-11eb-8a93-4e7da8f0eeb9.png)
couldn't find a ppa for yad 7.x . anyone can help?

**Comment by frostworx** [comment]
Hi,
just reopened and pinned this issue, which should help:
https://github.com/frostworx/steamtinkerlaunch/issues/98

**Comment by kadogo** [comment]
Î build an appimage for yad (for x86_64) and it looks like it work not so bad, there are some find issues but I'm not sure it's related to my appimage (I didn't test on my desktop that have yad).

[yad-appimage.zip](https://github.com/frostworx/steamtinkerlaunch/files/5451226/yad-appimage.zip)

```
$ whereis yad
yad:
```
```
$ unzip yad-appimage.zip
Archive:  yad-appimage.zip
  inflating: Yad-313ada9-x86_64.AppImage 
# Not needed normally but just in case the executable bit is lost
$ chmod +x Yad-313ada9-x86_64.AppImage 
```
```
$ yad=./Yad-313ada9-x86_64.AppImage $(pwd)/stl compat add
ERROR loadLangFile - language file '/home/user/.config/stl/downloads/SteamTinkerLaunch/lang/english.txt' missing - downloading ' https://github.com/frostworx/steamtinkerlaunch' and trying again
Clonage dans '/home/user/.config/stl/downloads/SteamTinkerLaunch'...
remote: Enumerating objects: 904, done.
remote: Counting objects: 100% (904/904), done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 1678 (delta 834), reused 833 (delta 777), pack-reused 774
Réception d'objets: 100% (1678/1678), 812.38 KiB | 1.93 MiB/s, fait.
Résolution des deltas: 100% (1255/1255), fait.
###############################
ERROR - no language file could be loaded! For the initial setup at least one file (default english) is required
ERROR - You can ether copy a valid file to '/home/user/.config/stl/lang' or '/usr/share/stl/lang' or provide an absolute path via command line using the lang= option
###############################
```
```
$ yad=./Yad-313ada9-x86_64.AppImage $(pwd)/stl compat add
find: ‘/usr/share/steam/compatibilitytools.d’: Aucun fichier ou dossier de ce type
find: ‘/home/user/.steam/root/steamapps/common’: Aucun fichier ou dossier de ce type
find: ‘/usr/share/steam/compatibilitytools.d’: Aucun fichier ou dossier de ce type
find: ‘/home/user/.steam/root/steamapps/common’: Aucun fichier ou dossier de ce type
mercredi 28 octobre 2020, 13:02:05 (UTC+0100) INFO - CompatTool - creating dir '/home/user/.steam/root/compatibilitytools.d/SteamTinkerLaunch'
mercredi 28 octobre 2020, 13:02:05 (UTC+0100) INFO - CompatTool - creating file '/home/user/.steam/root/compatibilitytools.d/SteamTinkerLaunch/compatibilitytool.vdf'
mercredi 28 octobre 2020, 13:02:05 (UTC+0100) INFO - CompatTool - creating file '/home/user/.steam/root/compatibilitytools.d/SteamTinkerLaunch/toolmanifest.vdf'
mercredi 28 octobre 2020, 13:02:05 (UTC+0100) INFO - CompatTool - creating symlink '/home/user/.steam/root/compatibilitytools.d/SteamTinkerLaunch/stl' pointing to '/home/user/GITS/steamtinkerlaunch/stl'
```

In steam I use this command as run

```
# Replace the yad appimage path and the stl path
yad="/home/user/GITS/steamtinkerlaunch/Yad-313ada9-x86_64.AppImage" /home/user/GITS/steamtinkerlaunch/stl %command%
```

I just did a test on CrossCode (it's a native game). Maybe it would need some test for Windows games...

**Comment by frostworx** [comment]
Nice, this probably comes in handy for debian users, so thanks!

**Comment by staticnation** [comment]
Linux Mint 20.04
ERROR yad version '0.40.0' is too old. You need to update to at least '7.0'

Solution place above app image and stl into /usr/local/bin
change line 26 of stl file from YAD=yad to YAD="Yad-313ada9-x86_64.AppImage"
now you can just stl %command% from steam

**Comment by kadogo** [comment]
I added informations on https://github.com/frostworx/steamtinkerlaunch/issues/98#issuecomment-720107680 about the AppImage that is stored with Dockerfile and script if the AppImage file not sound trustfull.

**Comment by frostworx** [comment]
Closing here. Obviously missing op feedback and #98 is still pinned

**Comment by ghost** [comment]
I need help.

I tried running the commands but it said:

user@debian:~$ yad=./Yad-313ada9-x86_64.AppImage $(pwd)/stl compat add
bash: /home/user/stl: File or directory not found

What am I doing wrong?

my current yad version is:
0.40.0 (GTK+ 3.24.38)

Unable to use SteamTinkererLaunch for days now.

**Comment by sonic2kk** [comment]
Did you download STL and put it into that path? Also, you can install STL using Pacstall on Ubuntu and derivatives.

Make sure you understand what commands are doing before you attempt to use a program like SteamTinkerLaunch. Blindly running commands from a 3-year-old issue is not a good idea.

The bundled Yad version sounds very old and likely you can just install STL from Pacstall, or do a manual install and install a Yad Appimage following the commands on the STL wiki.
