### ISSUE TITLE
problem during launch with dependency 

### ISSUE THREAD

**Issue by KiroShuriken** [sonic2kk/steamtinkerlaunch#1190]
## System Information
- SteamTinkerLaunch version: v14.0.20241023-1
- Distribution: SteamOS
- Installation Method: Followed the instructions

## Issue Description

So its been working perfectly until about an hour ago when it started to behave weirdly. i can install the dependency using the "stl ai" command but when it updates during the gamelaunch this happens
## Logs

when i try to start the game this happens
[steamtinkerlaunch.log](https://github.com/user-attachments/files/17514056/steamtinkerlaunch.log)

this is how it looks if i just run the script 
[steamtinkerlaunch.log](https://github.com/user-attachments/files/17514064/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Did you update to SteamOS 3.6 and did that cause this? If so, this is probably because of innoextract. I'll push the PR to bump the version anyway as it seems SteamOS 3.6 is in stable now anyway.

**Comment by sonic2kk** [comment]
Try removing dependencies and updating to latest master, #1136 was merged which bumps the `innoextract` dependency version.

**Comment by KiroShuriken** [comment]
omg thank you so much for the fast help. it worked now

**Comment by nl255** [comment]
It still didn't work for me and the log said the innoextract download failed.  I had to manually download it from https://archive.archlinux.org/packages/i/innoextract/innoextract-1.9-9-x86_64.pkg.tar.zst to $HOME/stl/deps via wget and then it worked.

**Comment by sonic2kk** [comment]
Sounds like you either didn't clear the dependencies with `steamtinkerlaunch cleardeckdeps` or you didn't update, as the "download failed" error is a red herring. The "download failed" log is actually triggered if the binary failed to run, which was confirmed in a previous issue.

Unless you confirmed the binary wasn't actually downloaded, you can ignore the misleading log.

**Comment by dosentmatter** [comment]
I ran `steamtinkerlaunch cleardeckdeps` and saw that the deps die was cleared. But every time I launched a game from steam with STL compatibility, it still kept trying to install innoextract 1.9.8 instead of 1.9.9.

Every time I reran `steamtinkerlaunch cleardeckdeps`, it would install 1.9.8 to start STL then remove deps. I checked logs and it said it successfully pulled the git repo.

I ended up just uninstalling and reinstalling STL master branch in protonupqt and it was fixed - started installing innoextract 1.9.9. I feel like I installed from master branch previously but I might have fat fingered it.

**Comment by nl255** [comment]
> Sounds like you either didn't clear the dependencies with `steamtinkerlaunch cleardeckdeps` or you didn't update, as the "download failed" error is a red herring. The "download failed" log is actually triggered if the binary failed to run, which was confirmed in a previous issue.
> 
> Unless you confirmed the binary wasn't actually downloaded, you can ignore the misleading log.

Considering that manually downloading innoextract-1.9-9-x86_64.pkg.tar.zst into ~/stl/deps fixed it, I would say it didn't get downloaded.  As for cleardeckdeps, wouldn't simply deleting the entire ~/stl folder and reinstalling from the latest git basically do the same thing?
