### ISSUE TITLE
Where and how do I put the launch options I use on steam into the game menu of the game I launch with Steamtinkerlaunch?

### ISSUE THREAD

**Issue by Saigaiii** [sonic2kk/steamtinkerlaunch#1191]
I am sorry since this must be a stupid question, but I am having issues with where and how to put my commands into the game menu on steamtinkerlaunch when using it with a game. This is the launch options I use on steam: "SteamDeck=0 %command% -FSRFG -DLSSFG"

I do not know where or how to put this in the game menu as no part of it works if I put it under custom command arguments (I use a custom command to launch a different exe of the same game). Please help me with this.

**Comment by zany130** [comment]
~~I remember I accidentally found out you could do this in the game ascope arguments setting after the last 

```
--
```
But I don't think that was ever intended.


Other than that I *think* there was support for adding global env in a text file you put I forgot where. 

But it's not per game it's global.

Afaik there is no official way to add
Env variables to the launch command of your game in STL ~~

EDIT: NVM

https://github.com/sonic2kk/steamtinkerlaunch/wiki/ENV-Variables

**Comment by Saigaiii** [comment]
Well damn that sucks. I like having everything in one place, but it’s fine. I’ll close the issue.
