### ISSUE TITLE
NieR: Automata with SpecialK crashing after about 5 seconds.

### ISSUE THREAD

**Issue by catgirlcataclysm** [sonic2kk/steamtinkerlaunch#1194]
## System Information
- SteamTinkerLaunch version: v12.12-r272.g4ef6565-1 (latest steamtinkerlaunch-git from AUR)
- Distribution: Arch Linux
- Installation Method: Package Manager

## Issue Description
I don't even know if this is where I should be asking, but considering I've been reading through the issues here and over at SpecialK's GitHub, I can't seem to find anyone else with this problem + SpecialK doesn't officially support Linux so I don't want to bother them.

So, I installed SpecialK through steamtinkerlaunch by just checking the checkbox and then pressing save and play, but I've also tried the manual install route.
As the title suggests, The game crashes pretty fast after starting it. The window appears and is solid white, and then a second or two later, it's gone. Now, I may be missing something simple, as this is my first time using steamtinkerlaunch, and in that case, I apologize for the unnecessary issue, but I've been digging at this for a few days now, and had absolutely no luck at improving it at all.

## Logs
I don't know which of the specialK/steamtinkerlaunch/game logs would be valuable in this scenario, so just go ahead and ask me and I'll provide any of them. (I don't want to make a massive issue by providing all of them right here).

**Comment by soupyfish** [comment]
also having this issue, exact same setup

**Comment by catgirlcataclysm** [comment]
Glad to know I'm not alone, that leads me to believe that something changed in either the game or specialK, in order to break it.

**Comment by saul178** [comment]
hello, I got it to work by using an older special k release (24.5.13). the latest release seems to have broken something, so i hope this helps in some way.

**Comment by sonic2kk** [comment]
This did indeed sound like an issue specific to a SpecialK version.

You can download  that specific SpecialK version and tell SteamTinkerLaunch to use it. There is some guidance on doing this from the [SteamTinkerLaunch wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/SpecialK#versions). I recall there being problems with allowing selecting specific SpecialK versions, and that the `custom` option was a compromse.

I will close this as this appears to be game-specific, SpecialK-version-specific, Wine-specific, or some combination.

One thing also worth noting is that I have observe NieR:Automata to be problematic with different Proton versions. See [this section of the SteamTinkerLaunch SpecialK wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/SpecialK#crashes-with-only-ge-protonvalve-protonetc) for guidance, in case it is also relevant.

<hr>

Given that this has a resolution and does not appear to be a regression or bug on the SteamTinkerLaunch side, I will close this issue. Thanks for troubleshooting and fixing a fix, @saul178 !
