### ISSUE TITLE
Cannot download dependency "no internet"

### ISSUE THREAD

**Issue by Ukrrooter** [sonic2kk/steamtinkerlaunch#1195]
Install script says no internet though it is not true. Tried switching network with no luck, rest of the internet is working .
Cant download dependency due to this.
Version v12.12 Steam Deck OS. Installed by the deck manual you provided.
[steamtinkerlaunch.log](https://github.com/user-attachments/files/17955850/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
SteamTinkerLaunch v12.12 is very out-of-date, please use the latest SteamTinkerLaunch from master. You also deliberately ignored the issue template for no reason.

Try removing all SteamTInkerLaunch files from `~/stl` and retrying installation with `master`.

Sometimes, certain sites of ISPs don't allow connections from scripts, and block commands like `ping`. This came up before in another issue where HedgeModManager couldn't even be downloaded.

There is not much I can do here I'm afraid, if SteamTinkerLaunch can't connect then that isn't something I'm aware of a way to resolve from my side.
