### ISSUE TITLE
Download link?

### ISSUE THREAD

**Issue by TheBitcoinBaron** [sonic2kk/steamtinkerlaunch#1198]
Hi how to download this I cant see a downloads section anywhere?

If i got to /releases the versions are all source code, just want like a zip or something easy to install.

**Comment by sonic2kk** [comment]
SteamTinkerLaunch is just a Bash script. You can download and run it anywhere. Also, you should not be using the releases section. The last release was almost 2 years ago, but the project is still actively developed with a _lot_ of changes that are not in a release. v12.12 may be entirely broken at this point.

I don't know what kind of "easy to install" step that you want, it's not like this is a program that gets compiled... Just extract and put it on PATH.

**Comment by PseudoResonance** [comment]
Perhaps you should update your readme then, because it clearly states that the "Preferred installation method" is through a package manager, almost all of which are out of date. Sorry, wrong issue... meant to comment on the one about the package manager versions, but my point still stands.
