### ISSUE TITLE
CUSTOMCMD is running outside the steam environnement

### ISSUE THREAD

**Issue by kadogo** [sonic2kk/steamtinkerlaunch#120]
Hello,

I'm playing a bit with STL for trying to load MangoHud (or anything else) without the need to make a reel setup.
In MangoHud case it's only changing LD_PRELOAD and LD_LIBRARY_PATH

But when I run a CUSTOMCMD (or a custom script) I not retrieve the same LD_PRELOAD and LD_LIBRARY_PATH that I have when I launch the game command directly trough Steam.

```
# Steam command: empty

# LD_PRELOAD
LD_PRELOAD=:/home/user/.steam/ubuntu12_32/gameoverlayrenderer.so:/home/user/.steam/ubuntu12_64/gameoverlayrenderer.so

# LD_LIBRARY_PATH
LD_LIBRARY_PATH=/home/user/.steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/user/.steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/usr/local/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib32:/usr/lib32:/lib:/usr/lib:/usr/lib/i386-linux-gnu/sse2:/usr/lib/i386-linux-gnu/i686:/usr/lib/i386-linux-gnu/i686/sse2:/home/user/.steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/user/.steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/user/.steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/user/.steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/user/.steam/ubuntu12_32/steam-runtime/lib:/home/user/.steam/ubuntu12_32/steam-runtime/usr/lib:
```

```
# Steam command: /home/user/GITS/steamtinkerlaunch/stl %command% and I use a custom script that dump the env output

# LD_PRELOAD
LD_PRELOAD=

# LD_LIBRARY_PATH
LD_LIBRARY_PATH=
```

I don't know if the behavior is wanted, if it's the case is there a launch the CUSTOMCMD in Steam environnement?

**Comment by frostworx** [comment]
I'm afraid I don't understand what you're trying to do, but it is a bash script  - you could simply read through it to find out yourself
what you want to know. I see no reason why I should read it for you.
In fact I already waste far too much of my time into programming with almost no feedback or even contribution, which makes me wonder if community driven open source even still exists/works.

**Comment by kadogo** [comment]
I did or I would have open this issue sooner...

I launch a custom command through STL and I not have the same environnement variable than if I launch it through Steam directly.
My question is the next one.

Is that the wanted behavior?

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L2617
edit:
...

**Comment by kadogo** [comment]
Thanks and sorry that it looks like a stupid question but I checked by searching "CUSTOMCMD" through the script and I didn't saw the extRun function.

So it's the wanted behavior and because of that I close the issue.

**Comment by frostworx** [comment]
It was no stupid question at all and sorry for being a bit rude.
