### ISSUE TITLE
Not Opening livesplit

### ISSUE THREAD

**Issue by Caitlynmcc234** [sonic2kk/steamtinkerlaunch#1203]
## System Information
- SteamTinkerLaunch version: I think its the newest (installed it today)
- Distribution: Endeavour OS (Based on arch)
- Installation Method: FlatPak

## Issue Description
I want to launch livesplit in the same prefix as OriWotW, but it isnt launching livesplit
![image](https://github.com/user-attachments/assets/e34e6e53-5965-4740-9171-2d405f04238f)
## Logs
[steamtinkerlaunch.log](https://github.com/user-attachments/files/18236874/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Does this work if you disable the Steam Linux Runtime (in case it's incompatible), or if you select "Only Custom Command"? If the latter works, you may need to set some kind of delay before opening the game rather than using "Inject". 

Have you also confirmed LiveSplit is compatible with the Proton version?

I will investigate the logs when I have time, and try myself once I can dig into this.

**Comment by sonic2kk** [comment]
Currently investigating this. I noticed in your screenshot that you have the "Fork" and "Inject" options for Custom Command both selected. As the tooltip states, enabling "Inject" will take priority over "Fork".

I am not sure which is more desirable for a tool like LiveSplit, but I will test both and report back.

**Comment by sonic2kk** [comment]
LiveSplit opens for me when using "Fork", but does not open until after the game process when using "Inject". Disabling the "Use Steam Linux Runtime with Custom Command" option fixes this issue.

From the log you attached it doesn't seem like this was a log from game execution, butthe EXE launched  perhaps from grabbing the screenshot? Therefore I can't say if SteamTinkerLaunch went through the process of starting the EXE properly, but I would say it likely did, as I can reproduce the problem you described with the same options.

This scenario is possibly some kind of quirk with injecting a tool like LiveSplit for some reason, or maybe inject doesn't work with the Steam Linux Runtime in most (all?) scenarios. However, it seems disabling the Steam Linux Runtime is one solution, although not ideal. If you need the Steam Linux Runtime, "Fork" appears to work more consistently.

There is likely nothing further that can be done here as this does not appear to be a compatibility issue, and the problem can be replicated and fixed on my side, so I will close this issue. Good luck!
