### ISSUE TITLE
Flatpak Beta branch eol and some other things

### ISSUE THREAD

**Issue by HanPrower** [sonic2kk/steamtinkerlaunch#1206]
I've marked the beta branch of the Flatpak end-of-life. I never used it for what I intended, it was just never really necessary and was constantly massively out-of-date (which is unhelpful in general for you).

With that in mind the wiki pages need a little edit to remove reference to the beta branch:
https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#steam-flatpak
https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Flatpak#beta-release

---

This issue used to say more, but I realised I was being dumb, so it's just the beta/wiki stuff 😓

**Comment by sonic2kk** [comment]
Thanks for the heads-up! I have removed reference to the Flatpak Beta on both wiki pages.
- Installation Wiki: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation/_compare/d3eecbc1fa66eeb80d63565da8e4236b32516add
- Steam Flatpak Wiki: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Flatpak/_compare/d38dc6219271f7353ccacebfbc878b04b2a9a674
