### ISSUE TITLE
Hint users of supported games to use Nexus Mod app instead of Vortex

### ISSUE THREAD

**Issue by RealSourceOfficial** [sonic2kk/steamtinkerlaunch#1207]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Arch Linux (kernel 6.12.7-lqx1-1-lqx)

## Feature Description
For games such as Cyberpunk 2077, the default Vortex Mod Manager has quite a few issues (e.g. deployment NOT BEING POSSIBLE) - though with the development of NexusMod's new Nexus Mods app, (such a creative name, I know) a lot of these bugs have been ironed out and mod deployment is significantly easier. For instance, I simply downloaded the AppImage directly off the repo, ran it, installed protontricks and promptly had a working modded version of Cyberpunk. _This was after spending SEVERAL hours messing with Vortex, all to get to "Mods can't be deployed"._

Just a simple hint to the Nexus Mod app for games that are supported (Cyberpunk, Stardew Valley, Baldur's Gate 3, and Bannerlord) would go the extra mile in preventing the user headaches that come with Vortex on linux.

**Comment by sonic2kk** [comment]
It's not my job to instruct users how to mod their games. Some users may want to use Vortex.

Fwiw, bugs with Vortex on Linux aren't SteamTinkerLaunch bugs. And you're using v12.12, so I wouldn't expect Vortex to work as you're using an unsupported version.

**Comment by RealSourceOfficial** [comment]
Unaware this was an unsupported version of Vortex - Installed directly from the AUR, thought it was green on the package list, assumed it was up to date/supported. My bad.
