### ISSUE TITLE
Shader Management

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#122]
Started work on implementing a Shader Management with at least the following features:
- Downloader of several Shader repositories
- A Shader Selection Menu
  - all available Shaders are automatically listed
  - all Shaders already installed in the current game directory are checked
  - all checked Shaders will be installed into the current game directory
  - all unchecked Shaders will be removed from the current game directory
  - The Shader Selection Menu can be started
    - via command line _(with any directory as destination path)_
    - directly from the Settings Menu
    - automatically before game start
    - via TrayIcon _(so Shaders could be installed while the game is already running)_
- for games with launchers not being in the same path as the actual game exe the destination path can be overridden
  _(used for both Shaders and ReShade)_

Considering:
Improving ReShade and vkBasalt implementation _(maybe some preconfiguring is possible?)_

Any other ideas or thoughts?

**Comment by kadogo** [comment]
Maybe it's not completely the right issue. When I tried to make SBS working for Amnesia I remark that ReShade didn't work for opengl because it set the wine dll to d3d9. I have on my desktop the correct value that work for Amnesia if it can help but I didn't checked yet if there is a proper way to detect directx or opengl.

A way to configure vkBasalt would be amazing (I did some experience with the AppImage that I build and I didn't really found a way to configure the shaders like). From the vkBasalt repo it look like there are a way to use some INI configuration but I was a bit lost on it to be honnest.

**Comment by frostworx** [comment]
Hm, the opengl settings could be interesting - I thought the current distinction already covers every possible constellation.
TBH I haven't touched vkBasalt very much yet for the exact same reason, and as ReShade shaders are (were?) very limited with vkBasalt and just work with ReShade (for a reason :).
So my personal interest in preconfiguring shader settings is mainly focused on ReShade `(I have not even checked if this can even be automated on a sane and general working way though)` but a more user friendly vkBasalt implementation would be nice to have as well indeed :)

**Comment by kadogo** [comment]
The implementation of vkBasalt look much like mangohud (vulkan layer implicit, 1 lib and a config file). Everything can be done through environnement variable if it can help you to have an idea I add few note on https://github.com/kadogo/easy-builder#vkbasalt (I think only the libvkbasalt.so is needed but I just tested the AppImage for now).

**Comment by frostworx** [comment]
Thanks!
Currently stl only creates a basic `VKBASALT_CONFIG_FILE` [here](https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L2633) and offers a switch for the ENABLE_VLBASALT boolean. My motivation to write a gui around every variable vkBasalt spits out is below zero though and I'd maximal "autogenerate" a basic config per game.

*(last but not least because my _(pre-steamtinkerlaunch)_  issue [here](https://github.com/DadSchoorse/vkBasalt/issues/80) 
pointing to my [howto to get regular games working in Stereo3D on linux](https://www.reddit.com/r/SteamPlay/comments/gbdiia/playing_regular_games_in_vr_works_on_linux_finally/) was closed without any comment. *rage-edited my comment after it was closed by simply pointing to ReShade* :))*

**Comment by kadogo** [comment]
I could made SBS work but it was not centered in front of me (i use HTC vive). The screen was like centered in the ground of my room. Maybe there is a way to setting video-player-vr but I need to dig that further. But I need to give some more tries and make opentrack work correctly too ^^.

But we are not for of something that could make any no vr game working in a HMD and that is cool ^^

**Comment by frostworx** [comment]
stl tries to focus the vr-video-player window and then virtually presses "w" to center the view.
This does often work, but can't be 100% reliable.
Of course the hmd has to point into the correct direction when this "keypress" happens :)
If everything goes well (this doesn't work 100% as well) all windows are minimized when the game and vr-video-player starts
and you can simply toggle between game window and vr window using alt+tab.
Then, with vr window in focus you can easily recenter the view (or zoom in/out) and then switch back to the game with alt+tab, so reconfiguring also is possible with hmd on.

**Comment by kadogo** [comment]
Ah ok it must be the reason because I only set my HMD on my head after it was launched ^^

I will give it a new try today evening and add here the info about opengl for reshade

**Comment by frostworx** [comment]
Hehe thought so. "Auto Pressing W" is the only possible method I can think of to have at least the chance to center the view correctly from `steamtinkerlaunch` side without touching the player code directly (likely though, that the controller settings have a key combo for this as well, never tried this though _(as apparently pancake games usually don't require the controllers :)) )_

**Comment by kadogo** [comment]
@frostworx no problem I didn't saw mention of the "w" when I checked the git of video-vr-player (but maybe I missed it it's possible too ^^).

**Comment by frostworx** [comment]
:)

**Comment by frostworx** [comment]
Added with https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.7.0

**Comment by frostworx** [comment]
Apparently the TrayIcon function isn't functional yet

**Comment by frostworx** [comment]
added in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.8.0
