### ISSUE TITLE
Check steam internal paths

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#126]
Looks like the whole steam user directory symlinking is even more complicated than it looks.
Based on #123 all used steam directories will centrally
- get availability checks
- be logged
- be user configurable

_(maybe even add a requester to initially pick corresponding directories if not found)_

**Comment by frostworx** [comment]
To sum up all currently used paths, could someone on Debian (derivate) please paste the corresponding path for following paths (I'm on Arch Linux)?
`~/.steam/root/userdata`  _(should have several "number directories - f.e. one is the steam userID  on is '7')_
`~/.steam/root/steamapps` (the default steamapps directory)
`~/.steam/root/compatibilitytools.d` _(the default path (by default directory does not exist) for user installed compatibility tools)_
`~/.steam/root/config/config.vdf` _( yeah, absolute path to config.vdf)_

All above paths are valid on Arch, but looks like at least some are not on Debian as here apparently a 
`~/.steam/root/steam/` directory[ is used](https://github.com/frostworx/steamtinkerlaunch/issues/123#issuecomment-719970197), which is a almost empty directory on Arch _(at least here)_
The issue initially came up [here](https://github.com/frostworx/steamtinkerlaunch/issues/116), but it is not completely fixed yet, as only [config.vfg](https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L157) is covered currently.

**Comment by kadogo** [comment]
@frostworx  that is what I have on Debian Buster but the install is pretty old already so maybe there are directories that have changed.

```
~/.steam/steam/userdata/
~/.steam/steam/steamapps/
~/.steam/root/compatibilitytools.d/
~/.steam/steam/config/config.vdf 
```

**Comment by frostworx** [comment]
Thanks again @kadogo! Good to have you on board :)

**Comment by frostworx** [comment]
Would be nice if someone could test this little script on debian derivate. I hope it finds all variables :)
[stl-steampathtest.txt](https://github.com/frostworx/steamtinkerlaunch/files/5483104/stl-steampathtest.txt)

**Comment by michaelneverwins** [comment]
> Would be nice if someone could test this little script on debian derivate.

Tested on Linux Mint 19.3:
```bash
mkdir temp
wget -P temp -- https://github.com/frostworx/steamtinkerlaunch/files/5483104/stl-steampathtest.txt
chmod u+x temp/stl-steampathtest.txt
temp/stl-steampathtest.txt
```
Result:
```
INFO setSteamPath - set 'SROOT' to '/home/michael/.steam/root/' E
INFO setSteamPath - set 'SUSDA' to '/home/michael/.steam/steam/userdata' E
INFO setSteamPath - set 'DEFSTEAMAPPS' to '/home/michael/.steam/root/' E
INFO setSteamPath - set 'DEFSTEAMAPPSCOMMON' to '/home/michael/.steam/root/' E
INFO setSteamPath - set 'STEAMCOMPATOOLS' to '/home/michael/.steam/root/compatibilitytools.d' E
INFO setSteamPath - set 'CFGVDF' to '/home/michael/.steam/steam/config/config.vdf' E
main SROOT /home/michael/.steam/root/
main SUSDA /home/michael/.steam/steam/userdata
main DEFSTEAMAPPS /home/michael/.steam/root/
main DEFSTEAMAPPSCOMMON /home/michael/.steam/root/
main STEAMCOMPATOOLS /home/michael/.steam/root/compatibilitytools.d
main CFGVDF /home/michael/.steam/steam/config/config.vdf
```

**Comment by frostworx** [comment]
Excellent, thanks for testing!
Looks like we have a nice little distribution-independant function here :)
Will likely add it tomorrow as I'm almost offline for today.

**Comment by kadogo** [comment]
@frostworx and for me

```
$ temp/stl-steampathtest.txt
INFO setSteamPath - set 'SROOT' to '/home/user/.steam/root/' E
INFO setSteamPath - set 'SUSDA' to '/home/user/.steam/steam/userdata' E
INFO setSteamPath - set 'DEFSTEAMAPPS' to '/home/user/.steam/root/' E
INFO setSteamPath - set 'DEFSTEAMAPPSCOMMON' to '/home/user/.steam/root/' E
INFO setSteamPath - set 'STEAMCOMPATOOLS' to '/home/user/.steam/root/compatibilitytools.d' E
INFO setSteamPath - set 'CFGVDF' to '/home/user/.steam/steam/config/config.vdf' E
 SROOT /home/user/.steam/root/
 SUSDA /home/user/.steam/steam/userdata
 DEFSTEAMAPPS /home/user/.steam/root/
 DEFSTEAMAPPSCOMMON /home/user/.steam/root/
 STEAMCOMPATOOLS /home/user/.steam/root/compatibilitytools.d
 CFGVDF /home/user/.steam/steam/config/config.vdf
```

**Comment by frostworx** [comment]
Great, thanks! Looks like this works as it should! :)
I'll try to make my current state releasable asap, but still have several construction sites open :)

**Comment by staticnation** [comment]
Linux Mint 20.04

```
$ ./stl-steampathtest.sh
INFO setSteamPath - set 'SROOT' to '/home/static/.steam/root/' E
INFO setSteamPath - set 'SUSDA' to '/home/static/.steam/root/userdata' E
INFO setSteamPath - set 'DEFSTEAMAPPS' to '/home/static/.steam/root/' E
INFO setSteamPath - set 'DEFSTEAMAPPSCOMMON' to '/home/static/.steam/root/' E
INFO setSteamPath - set 'STEAMCOMPATOOLS' to '/home/static/.steam/root/compatibilitytools.d' E
INFO setSteamPath - set 'CFGVDF' to '/home/static/.steam/root/config/config.vdf' E
 SROOT /home/static/.steam/root/
 SUSDA /home/static/.steam/root/userdata
 DEFSTEAMAPPS /home/static/.steam/root/
 DEFSTEAMAPPSCOMMON /home/static/.steam/root/
 STEAMCOMPATOOLS /home/static/.steam/root/compatibilitytools.d
 CFGVDF /home/static/.steam/root/config/config.vdf
```

**Comment by frostworx** [comment]
Very cool, thanks for testing @staticnation!
I'll add the setSteamPath function "as is" without any further additions as it seems to work pretty good.
_(already started to roll the new release which I'm planning to release within the next hours today)_

**Comment by frostworx** [comment]
_(hopefully)_ *fixed* in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.7.0
