### ISSUE TITLE
Proton autoupdate

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#127]
Add an optional function which automatically updates the configured proton version per game
or opens a heads-up requester before game launch with the option to update.

**Comment by IDeathByte** [comment]
you mean native(valve) proton or all builds?
my opinion - autoupdate not best option. because games can have different troubles with versions.
I think, as good variant you can make starting checker whats will notify user about availability new proton builds, and autodownload as second option, but without change current configurations.

**Comment by frostworx** [comment]
I only mean custom proton versions of one kind (and only if enabled of course).
So f.e. autoupdate a minor version bump pf Proton-5.9-GE-**X**-ST
Yeah an alternative little requester pointing to the new version was the idea.
Not sure yet generally, it's just an idea

**Comment by frostworx** [comment]
Idea update:
there's one function which checks if a newer proton version of the currently used custom proton is available
and one `CHECKPROTON` variable (per game) which can be `0,1,2,3,4`:

0 : the whole check is skipped
1 : call the function only when the settings menu is opened and open a "do you want to download requester"
2 : call the function only before the game is launched and open a "do you want to download requester"
3 : automatically download but don't replace the currently used custom proton version
4: automatically download and replace the currently used custom proton version

The "do you want to download requester" could also have a "use for this game option"

**Comment by frostworx** [comment]
Almost there and also added 
5: only pop up notifier

**Comment by frostworx** [comment]
added in https://github.com/frostworx/steamtinkerlaunch/commit/311b48d4c5b8bbb9d7286f6da20b2a98d8191500
