### ISSUE TITLE
[Feature request] Media Foundation install options

### ISSUE THREAD

**Issue by IDeathByte** [sonic2kk/steamtinkerlaunch#130]
You can add little checker for MF/ non MF proton builds - current open realization works properly not with all games (like bad playing intro-videos in borderlands 3 and skipped in some another titles). new option can check what`s proton build you may use in config and make active/inactive box with optional installation mfplat packages from here https://github.com/z0z0z/mf-install
(cab and non-cab versions for RE2 and etc)

**Comment by frostworx** [comment]
No sorry.
I already had this implemented and it is discouraged. As I want to keep the project clean I removed the function.
