### ISSUE TITLE
stl expects gawk, but doesn't check if is present, borks with mawk instead

### ISSUE THREAD

**Issue by DDzwiedziu** [sonic2kk/steamtinkerlaunch#131]
I know, I know, this is a dumb issue. Still it is one, similar to the yad version 0.40 vs 7.3.

stl version 2.7.0

This happened to me under Ubuntu 20.10:
```
❯ LANG=C ./stl compat
Wed Nov  4 14:45:56 CET 2020 ERROR - setSteamPath - 'compatibilitytools.d' not found for variable 'STEAMCOMPATOOLS' in '/home/dzwiedziu/.steam/root' or '/home/dzwiedziu/.steam/steam'!
awk: not an option: -i
find: '/steamapps/common': No such file or directory
awk: not an option: -i
find: '/steamapps/common': No such file or directory
awk: not an option: -i
Wed Nov  4 14:45:56 CET 2020 INFO - CompatTool - 'SteamTinkerLaunch' is not installed as Steam Compatibility Tool in ''

❯ LANG=C awk --version
awk: not an option: --version

❯ LANG=C awk -v
awk: option -v lacks argument

❯ LANG=C man awk

❯ LANG=C man mawk

❯ LANG=C awk -W version
mawk 1.3.4 20200120
Copyright 2008-2019,2020, Thomas E. Dickey
Copyright 1991-1996,2014, Michael D. Brennan

random-funcs:       srandom/random
regex-funcs:        internal
compiled limits:
sprintf buffer      8192
maximum-integer     2147483647

❯ awk -i
awk: not an option: -i

❯ sudo apt install gawk
---- 8< ----

❯ LANG=C awk -W version
GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.1.0, GNU MP 6.2.0)
Copyright (C) 1989, 1991-2019 Free Software Foundation.
---- 8< ----

❯ LANG=C awk -i
awk: option requires an argument -- i
---- 8< ----
```

**Comment by frostworx** [comment]
Thanks for reporting!
I wouldn't say it is a dumb issue `(it might be dumb that they are not compatible though)`
Before adding a special awk check though I'd suggest that I simply use AWK="gawk" instead and just depend on it.
_(correct me if I'm wrong, but I doubt there are that many people only using mawk)_

**Comment by frostworx** [comment]
fixed in https://github.com/frostworx/steamtinkerlaunch/commit/f6d82643bf0d08944075f5abe17b5d949066c187
please reopen if you think this is not enough

**Comment by frostworx** [comment]
nice, above commit is completely broken...

**Comment by DDzwiedziu** [comment]
> _(correct me if I'm wrong, but I doubt there are that many people only using mawk)_

I would think this also, but here I am on my Ubuntu, which I beat up semi-regularly power-user wise, and here I am reporting because by the fault `mawk` is installed (`base-files` depend on `mawk` or `gawk` and `mawk` is installed by default).

**Comment by frostworx** [comment]
A, there you are.
Just re-fixed the gawk issue.
mawk and gawk can live in parallel here on Arch, so simply installing both should not be a a problem I guess.

If this doesn't work for you I'm afraid you need to write a pull request, because I won't dig though all command line differences of both binaries to write a special distinction just to support a custom program I don't use. I'm sure this makes sense for you as well.

**Comment by DDzwiedziu** [comment]
Meh.You could just force gawk and chuck this one in the "done" bucket. I'm in for not overcomplicating.

**Comment by frostworx** [comment]
Meh. Assuming both this and your "No such file" message is properly fixed as it works here, I'll close here.
Glad I could help

**Comment by frostworx** [comment]
No idea if you're still around, but you might want to know, that I just replaced the gawk dependency by a generic gawk/mawk/awk solution:
https://github.com/frostworx/steamtinkerlaunch/issues/325
I hope it works as expected everywhere :)
