### ISSUE TITLE
Flag to skip dependency checks for yad

### ISSUE THREAD

**Issue by steeznson** [sonic2kk/steamtinkerlaunch#136]
The documentation suggests that yad is not an essential dependency for the settings menu, and that zenity can be used as an alternative. I realise that the script can easily be edited by hand but nice feature would be a flag which skips dependency checks if not all of them are essential.

As an aside, on my current distro (gentoo) yad is not in the official repos.

**Comment by frostworx** [comment]
thanks for the report!
I'll add a flag for skipping the dependencies soon.
(and might drop zenity soon)

**Comment by frostworx** [comment]
added in https://github.com/frostworx/steamtinkerlaunch/commit/311b48d4c5b8bbb9d7286f6da20b2a98d8191500
Feel free to reopen if there are issues.
