### ISSUE TITLE
Drop Zenity?

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#137]
Are there (m)any people who use steamtinkerlaunch only with the limited zenity support?
It really is often problematic to keep up basic support for it, so I'd love to completely remove it.

**Comment by frostworx** [comment]
I count an IRC channel with ~350 "idling" people ignoring the question as a -1

**Comment by kadogo** [comment]
I think that honnestly it could be dropped. The only reason I saw was the burden of an old yad but with the appimage it solved the issue.

**Comment by frostworx** [comment]
I think so as well. As usual thank you for the feedback :+1:

**Comment by frostworx** [comment]
*Dropping zenity!*
