### ISSUE TITLE
STL exits due to missing language file even after downloading one?

### ISSUE THREAD

**Issue by michaelneverwins** [sonic2kk/steamtinkerlaunch#138]
### Problem
I don't know much about the language files required by STL, but I've noticed something unusual: even though the script apparently has the ability to fetch missing language files from this repository, it still exits with an error after doing so. (Then, the next time STL runs, it works with no complaints about language files.)

### Details
I can reproduce the error consistently by deleting my `~/.config/stl` directory, but if you have anything important in there, moving it works too:
```bash
mv ~/.config/stl ~/.config/stl_backup
```
Then, when I try to bring up the settings window,
```bash
stl settings
```
I get the following output:
```
ERROR loadLangFile - language file '/home/michael/.config/stl/downloads/SteamTinkerLaunch/lang/english.txt' missing - downloading ' https://github.com/frostworx/steamtinkerlaunch' and trying again
Sat Nov  7 16:51:27 EST 2020 INFO - gitPullStl - updating '/home/michael/.config/stl/downloads/SteamTinkerLaunch' from 'https://github.com/frostworx/steamtinkerlaunch'
Cloning into '/home/michael/.config/stl/downloads/SteamTinkerLaunch'...
remote: Enumerating objects: 1026, done.
remote: Counting objects: 100% (1026/1026), done.
remote: Compressing objects: 100% (201/201), done.
remote: Total 1800 (delta 916), reused 905 (delta 814), pack-reused 774
Receiving objects: 100% (1800/1800), 859.82 KiB | 6.77 MiB/s, done.
Resolving deltas: 100% (1337/1337), done.
###############################
ERROR - no language file could be loaded! For the initial setup at least one file (default english) is required
ERROR - You can ether copy a valid file to '/home/michael/.config/stl/lang' or '/usr/share/stl/lang' or provide an absolute path via command line using the lang= option
###############################
```
It looks like the STL script, having failed to find a language file, acquired `english.txt` by downloading this repository but then exited with an error anyway. When I run it again,
```bash
stl settings
```
then there is no error about language files, and the settings window opens as expected.

I'm using the latest SteamTinkerLaunch script, with YAD 7.3, on Linux Mint 19.3.

### Workarounds
The only way I know how to avoid this error, if I'm running STL for the first time with no existing `~/.config/stl`, is to download the file to some valid location manually beforehand, e.g.:
```bash
mv ~/.config/stl ~/.config/stl_backup2
mkdir -p ~/.config/stl/downloads/SteamTinkerLaunch/lang
wget https://raw.githubusercontent.com/frostworx/steamtinkerlaunch/master/lang/english.txt -P ~/.config/stl/downloads/SteamTinkerLaunch/lang
stl settings
```
If doing some initial set-up in `~/.config/stl` is just a required step of the installation/setup process, that's perfectly fine. However, it's weird how STL gets the language file but still quits, so I assume that's not the intended behavior.

**Comment by frostworx** [comment]
Thanks, I'll check this soon!

**Comment by frostworx** [comment]
For the recently added option to skip the dependency check I moved the whole `createDefaultCfgs` function to the very beginning.
Likely that this broke loading the langauge function.
I just rewrote it a bit and it seems to work as it should.
https://github.com/frostworx/steamtinkerlaunch/commit/a5c18f49b398bc7b8a46611cfafccd52ed8f4ef7

**Comment by michaelneverwins** [comment]
I just pulled the latest changes in the master branch, including a5c18f49b398bc7b8a46611cfafccd52ed8f4ef7, and I've confirmed that `stl settings` now works on the first attempt after deleting or moving `~/.config/stl/`.
