### ISSUE TITLE
Steam Cloud problems?

### ISSUE THREAD

**Issue by michaelneverwins** [sonic2kk/steamtinkerlaunch#142]
Is there any reason that STL should be interfering with Steam Cloud?

Following the discussion on #123, I started using STL as a Steam Play compatibility tool rather than using it as a launch option to play Giana Sisters: Twisted Dreams (app ID 223220). However, I'm having a new problem, which I assume is unrelated to that earlier issue. In order to verify that everything was working out of the box following the #123-related fixes &mdash; from the WMP10 fix to the Proton version switch &mdash; I deleted the game's Wine prefix in `~/.steam/steam/steamapps/compatdata/223220` before running the game with the SteamTinkerLaunch compatibility tool (see https://github.com/frostworx/steamtinkerlaunch/issues/123#issuecomment-723623466). After doing so, I noticed the game was no longer using the save which I had started on Windows several years ago. I expected it to download the save from Steam Cloud, because it *had* loaded that old save when I had first gotten the game working by using the `stl %command%` launch option, but it just started a fresh save file instead.

I ended up copying the save files from my Windows partition and dropping them into the appropriate folder inside the game's Wine prefix, so I haven't actually lost anything, but the use of SteamTinkerLaunch as a compatibility tool appears to be preventing uploads to Steam Cloud as well. If I look at the Updates tab in the game's Properties window in Steam after running the game, I can see that the game's Steam Cloud storage is apparently getting wiped.

My exact test conditions, including a several-year-old save created on Windows, would be difficult to reproduce. I've also had some weird problems with Steam Cloud before, even on Windows, so I'm never really sure what to think when Steam's cloud save feature goes awry. But I tried launching the game a few different ways, and I am consistently seeing the following results:

* When I run the game with `stl %command%` in the launch options (which may require disabling Steam Linux Runtime in the STL settings per discussion in the later #123 comments), and then quit the game, the Updates tab in the game's Properties window in Steam shows 1.38 KB stored in Steam Cloud. :+1:
* When I run the game with SteamTinkerLaunch as the Steam Play compatibility tool (with no launch options), and then quit the game, the Updates tab in the game's Properties window in Steam shows 0 bytes stored in Steam Cloud. :-1:

Maybe it's just me, but I'm hoping someone else who has the game could try it. If it's not just me, I figure it might just be a problem with Steam itself. Maybe the Steam Cloud feature doesn't work when using non-Proton compatibility tools. If that is known to be the case, feel free to close this issue, because there's probably nothing to be done about it.

**Comment by frostworx** [comment]
There is no obvious reason why steamtinkerlaunch should interfer with the Steam Cloud and I haven't noticed any issues so far.
Not expecting any feedback _(generally)_, but I leave the issue open for a while to see if someone knows something.
edit: added a question mark to the headline for obvious reasons

**Comment by michaelneverwins** [comment]
Yeah, it's really strange. And I agree with the addition of that question mark.

Even if someone can just verify that Steam Cloud *is* working for them, then at least we'll have another data point. You mentioned that you haven't noticed any issues, but are you able to verify that it works on your system? I usually don't pay much attention to Steam Cloud because I don't switch between computers or operating systems very often &mdash; so, at least for me, it's easy for issues to go unnoticed.

Here's what I'm seeing in the game's Properties window after running it with SteamTinkerLaunch as a compatibility tool:

![cloud](https://user-images.githubusercontent.com/73746653/98483491-dd08ee00-21d6-11eb-8097-c6c67cff97db.png)

If others are running the game with the latest SteamTinkerLaunch selected as the compatibility tool and seeing more than 0 bytes in the Steam Cloud usage afterwards, then we'll know that this is a system-dependent issue at worst.

**Comment by frostworx** [comment]
I have some Giana data in the cloud:
![2020-11-09-072259_1037x128_scrot](https://user-images.githubusercontent.com/8840590/98506787-965dd700-225c-11eb-9e57-b02adee06594.jpg)

But as the Game doesn't work with linux at all if you want to play it regularly, I personally would not even care about the cloud.
As you see the bundled 223220.conf doesn't do anything extraordinary and with wmp10 already installed it shouldn't be really hard to play Giana without steamtinkerlaunch to find out.

edit:  missed the "stl %command%....1.38 KB" in the wall of text above, but the rest is still valid.

**Comment by michaelneverwins** [comment]
>As you see the bundled 223220.conf doesn't do anything extraordinary and with wmp10 already installed it shouldn't be really hard to play Giana without steamtinkerlaunch to find out.

That's what I thought. Weirdly, though, if I don't use STL at all and just set the game to launch with Proton 5.0-10, it actually doesn't work &mdash; i.e., the game doesn't even run &mdash; and this is *after* STL has already done the WMP10 fix. Then I put `stl %command%` back in the launch options and it works again. It seems to make a difference, even though STL doesn't seem to be changing the command that runs the game.

I don't see any obvious reason that STL would still be required after the WMP10 install is done, nor can I determine why using using STL as a compatibility tool breaks Steam Cloud for me. But, nagging curiosity aside, I don't care to poke at it much further. It's not a real problem, considering I've already found a way to make the game work perfectly for me: just using `stl %command%` as a launch option, and then avoiding any SLR-related problems either by setting Steam to use Proton 5.0-10 or by disabling the use of SLR in the STL settings. I'm just documenting the weirdness. :confused:

**Comment by frostworx** [comment]
In case you're still around, @michaelneverwins
It is fixed: https://github.com/frostworx/steamtinkerlaunch/issues/185

**Comment by michaelneverwins** [comment]
Oh, wow. Thanks for letting me know!

Since doing a fresh install of Linux Mint 20 back in December, I had been meaning to try this again to see if I would get the same results as on Mint 19.3... I just hadn't gotten around to it. But I'll try it again with your update as soon as I get a chance.
