### ISSUE TITLE
Favorites Menu

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#148]
I have the feeling that steamtinkerlaunch still is too complicated for one or another
and I wonder if the overwhelming Settings Menu could be a reason for this.
Not sure if this even is feasible, but I consider adding an option for setting up an individual "Favorites Menu".
In any case this will be pretty hard to implement, so I'm undecided yet.

**Comment by kadogo** [comment]
Hello,

I think maybe having some kind of double tab (or a window for the game mode) and after having tab for options could make it look less complexe but it would need to look which options can go together.

I think the favorite menu could be a good idea and more like "making his own menu". For example instead of having  1 long command with yad you can maybe split it in small one for example.

```
# yad function only for reshade
function yadReshade(){
	--field="     $GUI_INSTALL_RESHADE!$DESC_INSTALL_RESHADE ('INSTALL_RESHADE')":CHK "${INSTALL_RESHADE/#-/ -}" \
	--field="     $GUI_RESHADE_DEPTH3D!$DESC_RESHADE_DEPTH3D ('RESHADE_DEPTH3D')":CHK "${RESHADE_DEPTH3D/#-/ -}" \
	--field="     $GUI_USERESHADE!$DESC_USERESHADE ('USERESHADE')":CHK "${USERESHADE/#-/ -}" \
	--field="     $GUI_RESHADEUPDATE!$DESC_RESHADEUPDATE ('RESHADEUPDATE')":CHK "${RESHADEUPDATE/#-/ -}" \
	--field="     $GUI_RESHADEPRESET!$DESC_RESHADEPRESET ('RESHADEPRESET')":CB "${RESHADEPRESET/#-/ -}!$RSPRESETLIST" 
}

# array for which function we when we create our menu
yadfunctions=( "Reshade" )

# create big yad command
yad ... \
  $(echo "yad${yadfunctions[0]}")
```

It's just an idea but something like that. So it could help you to make the yad window more easier I think and maybe letting people having the menu like they want. I didn't really test it so I think it could work but it need some testing first ^^

**Comment by frostworx** [comment]
Hey @kadago!
Thank you for your thoughts!
With double tab you mean something like two visible settings levels, right? Like switching between "Basic", "Advanced" and "Expert" view similar to kodi. This is a good idea and I don't see (yet) any reason why this should not work.

I'm afraid it will not be so easy to create a favorite menu. In order to only update those options which actually were changed in the settings I currently use a bit [black magic](https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L4091) to parse them when leaving the menu.
Using this method and by using variables in the field lines, it is possible to re-arrange every line within its menu range, but
the favorite menu is outside this range and therefore the part is missing which tells where the selected options belong.
Or the other way around: not creating and drawing the favorite menu will be the hard part, but saving its settings.
Sorry, I just can't explain it better _(need more coffee :))_

**Comment by frostworx** [comment]
My basic idea for the favorite menu is to offer a checkbox menu with all available entries of all Settings Tabs,
where the user can choose from.
The checkbox menu is supposed to be auto-generated, so it self-maintains with future additions.
Auto generation will likely be some kind of grep in $0 in the correct places - this should not be a bigger problem.
All checked entries will be put into some kind of `favoritemenu.conf` (`FM`) _(which will be sourced of course when the checkbox menu is opened again)_
It should be possible to assign the checked items in the `FM` to their original config category, by simply searching them between above black magic lines _(game template Tab will be excluded, as the entries are apparently duplicates of the game Tab)_

It might be also nice to automatically use the `FM` instead of the regular Settings Menu (`SM`) whenever a `FM` is found `(or by simply activating it in a always available checkbox)`.
FM should have an option to open the `SM`.

Something like that :)

PS; I open an extra issue for the Settings Levels "Basic", "Advanced" and "Expert" here: https://github.com/frostworx/steamtinkerlaunch/issues/149

**Comment by kadogo** [comment]
I was more thinking about "gameconfig" "global" ... like now and under a tab like "proton" "vr" ...

But maybe basic, advanced and expert is better because it will be the options that we use the most ^^
Yes I saw a bit about black magic by parsing the template it look complex ^^

**Comment by frostworx** [comment]
It might be nice to have more topic specific tabs, but it is pretty time-consuming to rewrite everything for them.
Separating the menu into different levels probably is easier to write and to maintain.
Regarding the favorites menu _(edited my british spelling in here :) )_ I came along quite good and already have a live autogenereated checkbox menu with all possible menu entries (including description and tooltips).
I think this will become good when finished.

**Comment by kadogo** [comment]
I think the favorites menu would solve all the "wish" of everyone. At end we use the configurations only few time for lunching the game. When it works we not really go back to the configuration for fun ^^

**Comment by frostworx** [comment]
It already works very good, but I want this to become a mighty release :)

**Comment by frostworx** [comment]
added in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v3.1.335
