### ISSUE TITLE
[Question] Non-steam games

### ISSUE THREAD

**Issue by IDeathByte** [sonic2kk/steamtinkerlaunch#152]
As i see, stl not launch with non steam games - is a bug or realization not possible at this time? If i launch stl by console, him get me configs for edit.
I just need add some pre-launch options for couple of outside games, but it didn`t work on steam now(marked as bug).
I just didn`t know how stl worked inside - if it intercept steam launch command and start with new options by silent console launch, maybe possible realize this option?

**Comment by frostworx** [comment]
Hm, I need to find out what is wrong here, but in theory it should be possible to fix this.
It would probably save some time if you had a log from your test run to attach.

**Comment by frostworx** [comment]
Analyzed it a bit and found the core problems:
- the custom game has the `SteamAppId 0`, so stl needs an additional function to extract the artificial SteamAppId from env (f.e. from `STEAM_COMPAT_DATA_PATH`) - this would be easily fixable

- to distinguish if stl just launched a game or just the command line it checks if "steamapps/common" appears in the given command line parameters, which is not necessarily the case in a custom game.
One could just add a dummy game command line parameter like `-blah=steamapps/common` but pass that hurdle, but then already the next step - generating internal variables in setGameVars
will stumble over this "fake path"

I like the idea to support custom games, so I'll leave the issue open, but can't promise if I find a sane hassle free implementation for it.

**Comment by frostworx** [comment]
note for me - 
should be a valid solution to enter a new set**Custom**GameVars function instead of the regular setGameVars
whenever` [ "$SteamAppId" -eq "0" ]`

**Comment by frostworx** [comment]
note for me - 
should be a valid solution to enter a new set**Custom**GameVars function instead of the regular setGameVars
whenever `[ "$SteamAppId" -eq "0" ]`

**Comment by frostworx** [comment]
If `setGameVars` remains the only problem _(I'd even expect this)_
then this will be easier to implement than I initially thought.

**Comment by frostworx** [comment]
It wasn't the only problem, but looks like it works pretty good for the beginning.
Custom linux native games do work as well.

**Comment by frostworx** [comment]
added in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v3.1.335
