### ISSUE TITLE
Vortex

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#156]
Haven't touched Vortex for a while, but now I get the same black windows only, which were reported earlier here.
This NodeJS/electron stuff is an unmaintainable moving target _(at least in combination with wine/proton)_
and although it was pretty much work to implement it,
I consider dropping support for it completely.
Or someone interested in Vortex helps to debug this, I barely use it myself.

**Comment by frostworx** [comment]
The vortex wineprefix from a backup still works, looks like winetricks failed to install all deps on a fresh run...

**Comment by frostworx** [comment]
I'll try to recover it, but as I'm just removing Tabs anyway in favor of sortable single menus in a major rewrite (#154),
I'll re-add Vortex as a sub-category.

**Comment by kadogo** [comment]
Hello @frostworx 

If I'm right Vortex is used for downloading mods? If it's the case I would surely check on it one day because I'm planning to buy Skyrim so... kinda not possible to avoid mods ^^. But I have no idea when I will dig into it for now...

**Comment by frostworx** [comment]
Hey, @kadogo 
Yes, it is a Mod Manager and downloader for multiple games.
It would be a shame if I can't get it working anymore, but can't promise anything :)
Haven't even looked at it yet, as #154 is huge.

**Comment by frostworx** [comment]
OK, the problem is simply this one _(winetricks)_:
`"warning: This package (dotnet48) is broken in wine-5.13-634-gd6646652a2f. Broken since 5.12. Upgrade to >=5.18. See https://bugs.winehq.org/show_bug.cgi?id=49532 for more info. Use --force to try anyway."`

By default steamtinkerlaunch configures the wine binary from the Newest Official Proton as the VORTEXWINE binary.
I'll add some notifiers, but it is up to the user to take care of picking a compatible wine _(not my bug)._

**Comment by frostworx** [comment]
yay
`warning: This package (dotnet48) is broken in wine-5.21-233-g764a93f121c. Broken since 5.18. See https://bugs.winehq.org/show_bug.cgi?id=49897 for more info. Use --force to try anyway.`
