### ISSUE TITLE
Add direct Cheat Engine support

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#160]
Based on #159 I think it is a good idea to add direct Cheat Engine support.

Features should include *(if possible)*
- ~~download~~ *(implemented)*
-  ~~install (simple extraction of the installer would be nice, else install once into an own wineprefix)~~ *(implemented)*
- ~~simple checkbox to use it per game~~ *(implemented)*
- ~~close automatically when the game closes~~ *(implemented)*
- ~~automatically start the Cheat Engine when the started game is in the "CheatEngine" steam category~~  *(implemented)*

- ~~if the CE exe accepts exe names as command line arguments it makes sense to directly open it with the game exe~~
*(looks like a wontfix: https://github.com/cheat-engine/cheat-engine/issues/207 and pulling in this 3rd party tool is not worth the effort: https://github.com/mrexodia/CEAutoAttach)*

- anything else?

**Comment by frostworx** [comment]
@jcnils [pointed me](https://www.reddit.com/r/SteamPlay/comments/k1e4ja/protonhax_dose_not_work_with_513/ge9zzo1/?utm_source=reddit&utm_medium=web2x&context=3) to an official rar file of the Cheat Engine [here](https://www.cheatengine.org/download/CheatEngine7.2_MissingSetup.rar)
so installing the setup in a dummy wineprefix would not be required.
Will compare the two install directories soon.
Not wasting *(temporary)* space with a dummy wineprefix would be really nice and extraction would probably be much faster as well.
Edit: Damn, the rar url is 403.

**Comment by frostworx** [comment]
the setup exe  from https://github.com/cheat-engine/cheat-engine/releases is a "Inno Setup" which could be extracted using innoextract easily (the data directory is itentical to that installed in the wineprefix minus some 3uninst files, so probably usable out of the box).
It would pull in innoextract as optional dependency of course, which should ok though *(checking its own deps)*

Edit: hm, boost-libs are not a dependency I would have expected here...
~~Maybe a poll should decide this later.~~

I'll add innoextract as optional dependency. It will be used when found, if not fallback to "currently active wine" the used destination path will be identical for both variants.
This will be the last feature added for the next release.

**Comment by frostworx** [comment]
Optional support for extracting the setup with innoextract *(preferred method)* with fallback to wine is implemented and both methods tested. When using wine the dummy wineprefix is removed.

**Comment by jcnils** [comment]
Sorry for the delay,

Some download links need a _referer_ argument, it check the previous page as if you were navigating - it seems to be the case with cheat engine.

This is an example with curl.

`curl --referer https://www.cheatengine.org/download.php https://www.cheatengine.org/download/CheatEngine7.2_MissingSetup.rar -o CheatEngine7.rar`

`$ curl --referer Referer_URL target_URL ...`

I think `wget` has the same command. It is something like this 
`wget -O output.rar --referer http://subs.sab.bz/ 'http://subs.sab.bz/your-link-here'`


If I am not mistaken we can even use cookies and create sessions with those commands.

**Comment by frostworx** [comment]
Yeah, curl is pretty mighty. Anyway my above solution works fine for me and therefore I won't touch it again *(for now)*
_(I also prefer the github url, maybe because of php and rar :))_
In any case again thanks for trying to help!

**Comment by frostworx** [comment]
added in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v3.1.335
