### ISSUE TITLE
Makefile with install target

### ISSUE THREAD

**Issue by badly-drawn-wizards** [sonic2kk/steamtinkerlaunch#167]
I want to package steamtinkerlaunch for NixOS. I could write an install script for it's derivation (package) there, but I was wondering if it wouldn't be better to include a Makefile here. Let me know, then I can submit a PR.

**Comment by frostworx** [comment]
A Makefile (or some install management like cmake _(less/no hardcoding)_) would be nice indeed,
but I never found the time to make one.

**Comment by badly-drawn-wizards** [comment]
Unless I'm ignorant and missing something that adds complexity, the Makefile would basically do what the AUR package installer does, except with a PREFIX argument.

**Comment by frostworx** [comment]
Yes, that's right. A plain Makefile for this project would be perfectly fine _(I was more speaking in general regarding cmake and tbh my thoughts were elsewhere)_

**Comment by frostworx** [comment]
n1, ty

**Comment by TheOddler** [comment]
@badly-drawn-wizards Did you ever finish packaging this for NixOS? I'd love to use it there too.
