### ISSUE TITLE
Wow, just wow!

### ISSUE THREAD

**Issue by TheJoeSchr** [sonic2kk/steamtinkerlaunch#170]
I'm awed by the amount of work and features you put into this. 

I followed you from https://github.com/ValveSoftware/SteamVR-for-Linux/issues/337 to Reddit to here. Huge props for putting all the effort and time where your mouth is! :thumpsup:

I'm just glad I discovered this, before giving in to install Win once again so I can play Titanfall2 with VorpX. 

Btw. I don't even dare to ask, but fingers crossed, does this work with an Oculus Quest 2? Either via USB or Wirelessly? So far I haven't found a way to make emulate Oculus Link on Linux. For now I'm using Immersed VR to get a Virtual Display and then just play flat games normally. I assume SteamVR still needs to have a way, to know that Quest is connected and is a VRHMD and without Oculus Link on Linux it won't work.

Sorry for offrailing this, initially I just wanted to say, I'm impressed!

**Comment by frostworx** [comment]
Hi,
thanks for the rare friendly feedback!
Would be great if the Quest 2 would be usable under linux but currently it isn't.
I put all my hope into this project: https://github.com/alvr-org/ALVR/issues/269
and hope the author is successful.

**Comment by TheJoeSchr** [comment]
Oh yeah, I'm already subscribed on this issue! Was just hoping against hope!

Yeah, OSS can be very unthankful. Just know I'm really thankfull you share your work. 

I'm really impressed by your vortex implementation. I too played around with it, but didn't get it working. Maybe I can extract your work and use it without SteamVR until Quest 2 works on Linux :crossed_fingers:
