### ISSUE TITLE
Gamescope launch problem

### ISSUE THREAD

**Issue by IDeathByte** [sonic2kk/steamtinkerlaunch#171]
Looks like command not started when i try to launch non-steam game
I tryed to launch GOG-version cyberpunk. and him run without gamescope.

**Comment by frostworx** [comment]
Cyberpunk (steam) works fine here with gamescope, so apparently not my bug.
You could have tried at least checked the logs before opening a "doesn't work" issue without any content here. :(

**Comment by IDeathByte** [comment]
i found root of problem
`# start with gamemoderun:
		if [ "$USEGAMEMODERUN" -eq 1 ]; then
			if [ "$USEGAMESCOPE" -eq 1 ]; then
				writelog "SKIP" "${FUNCNAME[0]} - skipping '$GAMESCOPE' as '$GAMEMODERUN' is enabled as well"
			fi
`
this moment not written in manual
sorry if report non informative =(

**Comment by frostworx** [comment]
Should be working with https://github.com/frostworx/steamtinkerlaunch/commit/2588f0a2074ca61020314d3d4f6c2308687bb0e0
