### ISSUE TITLE
Scriptshows errors when trying to use.

### ISSUE THREAD

**Issue by trilin6** [sonic2kk/steamtinkerlaunch#173]
Installed with make.

Running stl shows :
`/usr/bin/stl: line 1724: : command not found
`
line 1724 in the script is 
`		"$NOTY" "$1"`

**Comment by frostworx** [comment]
Oh, good find. Looks like "notify-send"
(currently) is not as "optional" as it is supposed to be.
As a quick fix installing "notify-send" should work, but I'll try to fix it, so it becomes optional again. :)

**Comment by frostworx** [comment]
Hmm, either this is already fixed in my current version, or this isn't the problem.
Which stl version do you use and could you append the stl log file?
/dev/shm/stl/stl.log should be enough.
If you have one in ~/.config/stl/logs/stl/ this would be good as well.

**Comment by frostworx** [comment]
ah, when starting "stl settings" with removed notify-send
the gui opens but also fails with notify send. This is non-fatal though (but of course a glitch anyway).
I'm sure your log file will have some good hints.
Is your yad version new enough?

**Comment by trilin6** [comment]
yad version 0.40.0-1

**Comment by trilin6** [comment]
[stl.log](https://github.com/frostworx/steamtinkerlaunch/files/5721360/stl.log)

**Comment by frostworx** [comment]
It is really a shame yad is so ancient in debian derivates... :(
Anyway thanks for reporting, as the notifer was a glitch anyway.

**Comment by frostworx** [comment]
re-pinned this issue:
https://github.com/frostworx/steamtinkerlaunch/issues/98
