### ISSUE TITLE
Running SKSE doesnt work

### ISSUE THREAD

**Issue by farmboy0** [sonic2kk/steamtinkerlaunch#174]
I configured Skyrim VR to start with stl because I wanted to start it using sksevr_loader.exe instead of the main exe for the game.
Unfortunately stl determines that skesevr_loader.exe is a console app and tries to run it with wineconsole. This doesnrt seem to work and I havent found a way to tell stl to just run the exe through proton.

Is it possible to tell stl to just run the exe with proton and dont do this type check? I really only want proton to start with a different exe, nothing else.

STL Version: 3.5

**Comment by farmboy0** [comment]
[611670.log](https://github.com/frostworx/steamtinkerlaunch/files/5732497/611670.log)

**Comment by farmboy0** [comment]
[611670.conf.txt](https://github.com/frostworx/steamtinkerlaunch/files/5732498/611670.conf.txt)

**Comment by frostworx** [comment]
If you say that "stl already tries to do too much here and does it wrong to boot" _(the edit is still visible)_
you apparently know what you are talking about, so feel free to submit a pull request with your "fix".

**Comment by farmboy0** [comment]
It's a pity you read it anyway.

There is a reason I edited it out. And that is that I determined it was not helpful in the scope of this bug report and it would probably lead to the reaction it now obviously did.

I am sorry if I offended you. I was a bit frustrated because it took me 2 hours to get stl working at all.
I still think that stl is a cool way to set up and tweak proton games but in this case it does something I did not expect nor want.

**Comment by frostworx** [comment]
Ok, accepted.
Why did it take 2 hours to get it working?
It should be pretty much "plug&play" when all dependencies (f.e. yad) are installed, which apparently is not the job of stl.

Just to make sure you know it:
Using The Vortex implementation in stl it should be possible to automatically start SkyrimVR with sksevr_loader.exe, at least this worked fine for other games using SE.

Either way it should be correct that a windows console program is started with wineconsole, at least this worked with other SE exen. Are you sure this is wrong or are you guessing?
~~Tbh I do not know if @Patola's protola even supports SkyrimVR.~~ [It does](https://github.com/ValveSoftware/Proton/issues/1069#issuecomment-647757357)
For a quick test you can simply remove "$WICO"  from this line: https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L3997

**Comment by farmboy0** [comment]
It took me 2 hours because stl didnt find yad no matter what I tried when I installed it to ~/.local so I had to write an ebuild for yad. And for that I had to deal with gnome's idea of application settings to make that yad actually do something.

The reason I want stl to start skse_loader is so I can start Skyrim from within SteamVr. I already have a way to do it from the desktop. Can you tell Vortex to start a game without any interaction?

Shouldn't wine run wineconsole automatically if it determines that is needed? Why would stl need to concern itself with how to run this?

**Comment by frostworx** [comment]
I can confirm that sksevr_loader.exe starts when not using wineconsole.
Adding an option to not use wineconsole when a console binary was detected

**Comment by frostworx** [comment]
stl simply uses `which` to find required programs, so if your `~/local `installation wasn't found you should check your `PATH`.
In any case no stl problem.

Explicitely using wineconsole was required when I added SE support for Vortex, else I wouldn't have added it.

**Comment by farmboy0** [comment]
which did find it.
I used a console to run
which yad
and afterwards
stl
which found it stl complained about it.

**Comment by frostworx** [comment]
this leads nowhere without logs or at least knowing what "complained" means here.

**Comment by frostworx** [comment]
Should be fixed in https://github.com/frostworx/steamtinkerlaunch/commit/8bf3f728dccde8dd10752a3f6f0d89d09057b849
Please retest.

**Comment by farmboy0** [comment]
$ yad --version
7.3 (GTK+ 3.24.22)
$ which yad
/mnt/daten/Home/.local/bin/yad
$ stl
Mi 23. Dez 13:46:08 CET 2020 ERROR - checkIntDeps - yad not found!
Mi 23. Dez 13:46:08 CET 2020 ERROR - checkIntDeps - 'yad' was not found!
/mnt/daten/Home/.local/bin/stl: line 8015: yad: command not found
/mnt/daten/Home/.local/bin/stl: line 8018: yad: command not found
/mnt/daten/Home/.local/bin/stl: line 8019: yad: command not found

This is what I mean by complained.

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L147
https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L9562

PR for custom expanding PATH accepted.

now back on topic

**Comment by farmboy0** [comment]
Works now when started from Steam and SteamVr. Thanks.
