### ISSUE TITLE
Default Luxtorpeda setting conflicts with Steam Linux Runtime

### ISSUE THREAD

**Issue by Lucki** [sonic2kk/steamtinkerlaunch#175]
I wasn't able to use Luxtorpeda until I've changed the default argument from `wait-and-run` to `--wait-and-run` similar to the ones used for Roberta and Boxtron.

Steam terminal output with `wait-and-run`:
~~~
_v2-entry-point[289104]: Error: A command to run is required
Usage:
_v2-entry-point [OPTIONS] COMMAND [ARGS...]

Run a command in a container that is shared with other
invocations of the same Steam game.

Required arguments
COMMAND [ARGS...] Run this.

Options
--deploy=DIR      Deploy to this directory [default=SUITE].
--keep-logs       Do not remove the older logs of this same app id.
--log-to-file     Log to a file instead of the default stderr.
--suite=SUITE     Run in this runtime [default=scout].
--use-timestamp   Prepend the timestamp to the log entries [default with --log-to-file].
--verb=%verb%     Mode to operate in [default=waitforexitandrun].
--verbose         Be more verbose.
~~~

https://github.com/frostworx/steamtinkerlaunch/blob/8bf3f728dccde8dd10752a3f6f0d89d09057b849/stl#L1170

https://github.com/frostworx/steamtinkerlaunch/blob/8bf3f728dccde8dd10752a3f6f0d89d09057b849/stl#L1168

https://github.com/frostworx/steamtinkerlaunch/blob/8bf3f728dccde8dd10752a3f6f0d89d09057b849/stl#L1166

**Comment by frostworx** [comment]
There is no luxtorpeda `wait-and-run` command line argument, so I assume this was a typo.
The pasted terminal output seems to come from SLR and not from luxtorpeda.

Both luxtorpeda and luxtorpeda-dev use `wait-before-run` and not  `--wait-before-run` _(like roberta and boxtron do)_
as command line argument:
```
./luxtorpeda
usage: lux [run | wait-before-run] <exe> [<exe_args>]
```
And  this worked fine last time I tried.

Maybe SLR conflicts with  luxtorpeda here, so I assume you used stl as command line argument, as SLR would not be active when using stl as compatibility tool.
Could be easily tested/fixed by either disabling the SLR or by using stl as compatibility tool when using luxtorpeda.

**Comment by Lucki** [comment]
> I assume this was a typo.

Yes, sry.

> I assume you used stl as command line argument

Yes, that's correct.

I assume SLR is the Steam Linux Runtime? You're correct it works with `wait-before-run` when used as compatibility tool or disabled Steam Linux Runtime.
<details><summary>The first run gave me an error - but the following runs are working</summary>

~~~
/home/lucki/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/stl: Zeile 7745: [: : Ganzzahliger Ausdruck erwartet.
pid 36479 != 33962, skipping destruction (fork without exec?)
pid 36483 != 33962, skipping destruction (fork without exec?)
pid 36486 != 33962, skipping destruction (fork without exec?)
pid 36488 != 33962, skipping destruction (fork without exec?)
update_packages_json. found hash: e94bd4af67ab182b26d5371421c462b451497c63
update_packages_json. found hash and remote hash: e94bd4af67ab182b26d5371421c462b451497c63 27be32e444ff9b5bb13eae5b9ccbb90ed8fda2c7
update_packages_json. hash does not match. downloading
update_packages_json. downloading new packages.json
update_packages_json. new downloaded hash matches
tr1.zip found in cache (skip)
openlara-224960-1.tar.xz found in cache (skip)
pid 36495 != 33962, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/lucki/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
usage: lux [run | wait-before-run | manual-download] <exe | app_id> [<exe_args>]
pid 36505 != 33962, skipping destruction (fork without exec?)
pid 36507 != 33962, skipping destruction (fork without exec?)
pid 36509 != 33962, skipping destruction (fork without exec?)
>>> Adding process 36499 for game ID 224960
Game removed: AppID 224960 "", ProcID 33961 
Uploaded AppInterfaceStats to Steam
Exiting app 224960
~~~
</details>

A bit strange that it worked with `--wait-before-run` and SLR active.

Thanks for pointing me in the right direction. Is this still somewhat of an issue since I left everything default besides the Luxtorpeda command and that Luxtorpeda should be used?

**Comment by frostworx** [comment]
Thanks for testing!
"--" is used by bash to separate own command line args from those for subprocesses (not sure if I expressed this correctly so I hope you understand what I mean). I guess the "--" you added was interpreted as separator for the args for SLR _(yes, Steam Linux Runtime)_ and luxtorpeda and therefore made it working (would be funny).
Starting luxtorpeda regularly as compatibility tool would never use the SLR, so as my program allows this possibility
it should also take care that this is working.
The easiest fix would be to simply automatically set USESLR=0 when luxtorpeda is used.

The error in line 7745 is strange and I have no idea how this could have happened, so I'll skip it as one time glitch for now.

**Comment by frostworx** [comment]
The _(untested)_ commit autoclosed this issue. Feel free to reopen if it didn't fix the issue.

**Comment by Lucki** [comment]
It's working now even with the SLR "active" :+1:

> The error

I was talking some lines below - the one time usage example which prevented the game from running: `usage: lux [run | wait-before-run | manual-download] <exe | app_id> [<exe_args>]` but I agree with this as a one time glitch.

> The error in line 7745

however I can get reliably every time. Also it isn't preventing the game from running.
I've tried starting with `LC_ALL=C` to get the english translation but that wasn't successful.
It roughly translates to `Integer expression expected.`

`/usr/bin/stl: Zeile 7745: [: : Ganzzahliger Ausdruck erwartet.`

**Comment by frostworx** [comment]
Thanks for testing, glad to hear it is fixed!
The 7745 error should not be fatal, but I'll try to find out why it is even triggered.
_(btw I'm from germany as well, so "Ganzzahliger Ausdruck erwartet" is fine for me :))_
As the function checkVortexSELaunch is only called once, I [just added](https://github.com/frostworx/steamtinkerlaunch/commit/69f34ae1e7f3495fc49b020f83223253a9e82fa0) logging of the given parameter, which should reveal the wrong parameter and also should make it easier to find out where it does even come from.

**Comment by Lucki** [comment]
Well, it's empty: 
~~~
[…]
So 17. Jan 16:26:06 CET 2021 INFO - checkSBSVRLaunch - checkSBSVRLaunch - Incoming gamewindow name is 'none'
So 17. Jan 16:26:06 CET 2021 INFO - prepareLaunch - CheckDepth3DUse:
So 17. Jan 16:26:06 CET 2021 INFO - prepareLaunch - CheckVortex:
So 17. Jan 16:26:06 CET 2021 SKIP - checkVortex -  Vortex is disabled
So 17. Jan 16:26:06 CET 2021 INFO - prepareLaunch - CheckVortexSELaunch with argument '':
So 17. Jan 16:26:06 CET 2021 INFO - prepareLaunch - CheckCustomLaunch:
So 17. Jan 16:26:06 CET 2021 INFO - prepareLaunch - CheckStraceLaunch:
So 17. Jan 16:26:06 CET 2021 INFO - prepareLaunch - CheckNetMonLaunch:
So 17. Jan 16:26:06 CET 2021 INFO - launchSteamGame - disabling USESLR is enabled as a conflicting tool is used
[…]
~~~

**Comment by frostworx** [comment]
whoops, is the error still in line 7745? Either way I [added](https://github.com/frostworx/steamtinkerlaunch/commit/ce7501758b09368697c2655e81344a68f1cfd063) addition logging directly in checkVortexSELaunch

**Comment by Lucki** [comment]
`/usr/bin/stl: Zeile 7751: [: : Ganzzahliger Ausdruck erwartet.`

~~~
So 17. Jan 16:42:52 CET 2021 INFO - checkSBSVRLaunch - checkSBSVRLaunch - Incoming gamewindow name is 'none'
So 17. Jan 16:42:52 CET 2021 INFO - prepareLaunch - CheckDepth3DUse:
So 17. Jan 16:42:52 CET 2021 INFO - prepareLaunch - CheckVortex:
So 17. Jan 16:42:52 CET 2021 SKIP - checkVortex -  Vortex is disabled
So 17. Jan 16:42:52 CET 2021 INFO - prepareLaunch - CheckVortexSELaunch with argument '':
So 17. Jan 16:42:52 CET 2021 INFO - checkVortexSELaunch - using fix '2' as SECHECK
So 17. Jan 16:42:52 CET 2021 INFO - prepareLaunch - CheckCustomLaunch:
So 17. Jan 16:42:52 CET 2021 INFO - prepareLaunch - CheckStraceLaunch:
So 17. Jan 16:42:52 CET 2021 INFO - prepareLaunch - CheckNetMonLaunch:
So 17. Jan 16:42:52 CET 2021 INFO - launchSteamGame - disabling USESLR is enabled as a conflicting tool is used
~~~

**Comment by frostworx** [comment]
ah, I initially checked the wrong line as "7745" 
7751 makes more sense.
should be fixed now.

**Comment by Lucki** [comment]
> should be fixed now.

It is!
