### ISSUE TITLE
Cleaning up the Readme/making a wiki or docs

### ISSUE THREAD

**Issue by podiki** [sonic2kk/steamtinkerlaunch#176]
Awesome tool, thanks for the excellent work here! As noted in the Readme, the Readme has gotten huge and there's just so much this tool can do that it can be overwhelming for someone just finding it. I'd like to propose moving the vast majority of the Readme into either a Github wiki in this project, or in some documentation system (markdown files or something more sophisticated). I'm happy to start on this and help edit the contents as well. Here is what I see as a plan:

1. Copy nearly everything that isn't basic starting information (installation, requirements, etc.) into the project wiki (or doc system).
2. Separate out into appropriate pages with links as needed and a main page listing features, where to find info, and so on.
3. Replace most of the Readme now with a link to the wiki
4. The Readme can then have recent changes or added features, but overall be much more stable with new information or changes going into the wiki

Does that sound helpful and doable to you? I think most of this can be done pretty quickly and make it much more approachable.

**Comment by Faalagorn** [comment]
I'd think either a GitHub wiki or a linux `man` (since it's a Linux tool after all) would be a good choice.

**Comment by frostworx** [comment]
Thanks for the friendly offer, @podiki!
Your plan to improve the documentation by splitting it up/outsourcing it into a wiki
sounds very good and your work on it is more than welcome!
Nice to see you're still around, @Faalagorn! Would be great if you would like to contribute a manpage _(maybe based on @podiki wiki?)_

**Comment by podiki** [comment]
I haven't done any fancy doc stuff before, presumably there's an easy way to have docs that become a manpage? Or to be generated form the git wiki? I can do some searching if no one knows off hand already.

**Comment by Faalagorn** [comment]
Yup, I'm still around watching the repo but not contributing much at the moment. :)

Personally I'm all up for extensive wiki pages personally which can include images and more than basic formatting, but man pages shouldn't be hard to host here as well – I haven't done one myself, but formatting should be unified on Linux and a lot of projects host them on GitHub. :)

**Comment by podiki** [comment]
Is there any easy way to derive a man page from the wiki (or source files that become the wiki)?

Anyway, I can start working on the basics. Not sure if it is easier to set that up directly in this repository or if that can be handled through a fork/pull request. That seems [a little complicated](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) so perhaps it is easiest to do that directly here. ([Github wiki docs](https://docs.github.com/en/github/building-a-strong-community/documenting-your-project-with-wikis))

**Comment by Faalagorn** [comment]
> Is there any easy way to derive a man page from the wiki (or source files that become the wiki)?

Not sure about making man page from wiki automatically, but I think it's best to copy the respective changes by hand; man pages have different structure than GitHub wiki pages and it's fine, let's focus on GitHub wiki first and bother about man pages later. :)

**Comment by frostworx** [comment]
Just opened a dummy wiki [here](https://github.com/frostworx/steamtinkerlaunch/wiki/SteamTinkerLaunch-Wiki)
The linked stackoverflow url looks helpful.
I don't think that creating man-pages from an existing text is very hard, 
but target number one should be the wiki with later man pages based on it. 
To keep things clean it would make sense to use this issue for the wiki and simply open a new one for man-pages later.

**Comment by podiki** [comment]
Thanks for setting up the dummy wiki. I will follow the stackoverflow suggestions to fork and update the wiki on my side, and once I have a preliminary setup (getting all the readme info to the wiki) I'll let you know. We can then merge the changes if it looks fine, and update the readme to point to the wiki.

**Comment by frostworx** [comment]
Sounds like a good plan! Thanks for your help and take your time!

**Comment by podiki** [comment]
Okay, I have forked this project and got the wiki via [this answer](https://stackoverflow.com/questions/7197937/on-github-can-i-fork-just-a-wiki/56480628#56480628) and once I have the preliminary wiki we can follow [this gist](https://gist.github.com/larrybotha/10650410) to pull in the changes (found from following the previous stackoverflow link I gave).

I'll update here once I have the first version to look at for the basics, and then we can go about making it more complete and nicer looking.

**Comment by frostworx** [comment]
Nice!
forgot to link the [stackoverflow link](https://stackoverflow.com/questions/7197937/on-github-can-i-fork-just-a-wiki/56480628#56480628) mentioned in the [dummy wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/SteamTinkerLaunch-Wiki) [above](https://github.com/frostworx/steamtinkerlaunch/issues/176#issuecomment-766336576), so nice that you did it :)

**Comment by frostworx** [comment]
More work than initially expected _("can be done pretty quickly")_, eh? :)

**Comment by podiki** [comment]
haha yeah yeah. But more like needing to find some time to set aside and just got through it. Should have some this weekend and will report back.

**Comment by frostworx** [comment]
Hehe, no problem, take your time really!
Just wanted to tickle a bit. But thanks for the reply anyways! ;)

**Comment by podiki** [comment]
Progress! Lots of typing, thank you emacs for making it easier (really should have figured out macros though). Anyway I have an initial set of wiki pages here: https://github.com/podiki/steamtinkerlaunch/wiki

Right now it is most of the README (parts that were linked in the feature list mostly and a few other big parts). I removed these parts from the readme on my fork, but it is not linked to the wiki yet (need to use absolute links and ran out of steam tonight).

Still need to link within the wiki, organize, redo the readme, etc. But getting closer to an initial version and wanted to get thoughts on what should be in the readme, how to consolidate the wiki pages, etc.

**Comment by frostworx** [comment]
Wow, thank you very much for your work! :+1: 

I think the Readme itself should be more or less empty now.
My rough suggestions *(I hope more follow, as I mostly don't have to read it)* are:

As text maybe only
- An initial description
- Basic usage
- The other chapters up to the Features List should probably migrate into separate Wiki-Chapters as well.

The Feature List could be more or less as it is, just pointing to the Wiki-Chapters now.
It would be great though, if they would be sorted into separate Categories, ideally identical to those available in steamtinkerlaunch itself _(where it is perfectly possible to change those as well, as I wasn't sure which would be best)_.
Current categories are
- Gui
- Misc
- Proton
- Shader
- Stl
- Tools
- Tweaks
- Urls
- VR
- Vortex
- Wine
- PressureVessel

If there's anything unclear, bad, missing please let me know.
Again, Suggestions for a different/better sorting are welcome of course!

**Comment by podiki** [comment]
Sounds good, that was roughly what I was thinking too. I'll try to keep things in those categories, maybe combine a few separate (short) pages together. Agree that the Readme will be short with just the basic info/quickstart. I'll get things to look presentable and then you can decide if it'll be ready to merge or want to polish more on the fork first.

**Comment by frostworx** [comment]
Thank you very much! :+1:

**Comment by podiki** [comment]
Hi @frostworx, sorry it has been a while again. I thought I could add links in the wiki without using absolute URLs, but can't do that for markdown pages. So what that means is that if I linked within all the wiki pages, it would be to my forked repo's wiki and would all needed to be changed when merged here. Same for links in the Readme. I also know I am a few minor tweaks behind the current Readme here.

So I can clean up the wiki I have and link it up, but it will need a quick find/replace before merging here (but not before, so can make sure links are okay). I'm fine with doing that (working on it right now), and doing the same with the Readme. Just wanted to check if you'd prefer something else on your end. I want to have a version you can check out tonight and get this merged soon after.

**Comment by podiki** [comment]
Okay! The basics are in place: Readme greatly reduced and linked to wiki (incomplete); everything removed is in wiki pages and links should all work. Still to be done, but I think it would be good for you to have a look and decide what state you want it to be for merging:

1. Readme could use some more cleanup and some categories (from your comment above) I wasn't sure what to link
2. Wiki could use a better homepage with a more detailed (but brief) table of contents to navigate
3. Some wiki pages could be merged, but will also need to fix any links between pages or in readme
4. All links need to point to this repo (should be a one off find/replace in readme and wiki files)

Please take a look at my forked repo at https://github.com/podiki/steamtinkerlaunch and the wiki at https://github.com/podiki/steamtinkerlaunch/wiki

**Comment by frostworx** [comment]
Hello @podiki! Thank you very much! I'm very grateful for your huge help!
Regarding the missing pieces:

1. 
For the missing categories, it would be nice if you could add some "dummy" topics.
I could expand them later where required.

**Misc**
```
All configuration options which can't be put into a generic category
usually can be found here.
```

**Shader-Management**
Has an own link you've missed:
https://github.com/frostworx/steamtinkerlaunch#Shader-Management

**Stl**
`This category simply contains multiple Stl path configuration options.`

**Tools**  _(better, more obvious category name?)_
```
All external 3rd party programs which can be enabled for game launch
can be found here, including their corresponding options.
```

**Urls**
`All urls used within stl can be found in this category.`

I think the rest of the Readme is fine and covers everything required for a first overview.

2. 
For the Wiki Landing page it might be a good idea to start with the initial program description
followed by the "General usage" and "Game specific use" parts from the Readme
and then list wiki contents:
The Main Chapter List could be the "Features" List, where (hopefully) every wiki (sub-) chapter finds a home.

3. Whatever helps to simplify the Wiki is a good idea. Feel free to merge whatever you want. I fully trust your judgement.
   If I can be of any help _(I doubt though, sometimes my own readme is hard to read for myself :))_ please let me know.

4. An offline `sed "s:podiki:frostworx:g"` on all files should fix that completely if I haven't forgotten anything obvious _(only had one coffee so far today :))_

I hope I was able to help with the remaining points. If any answer was not that what you expected please let me know!
Thanks again for your great help! :+1:

**Comment by frostworx** [comment]
Would you mind me creating a 4.0 release before the wiki merge?
Initially I wanted to wait until you're done, but the [current yad-9.0 bug](https://github.com/frostworx/steamtinkerlaunch/issues/196) breaks the last v3.9 release
and adding a different branch to get [this simple workaround](https://github.com/frostworx/steamtinkerlaunch/commit/bd7f9d35bb0bd6a651631d6a6b6ea81b18469ca2) only into a hotfix release 3.9.1 would be overkill :)

**Comment by podiki** [comment]
Your suggestions look good to me, I'll try to get that all in at least a minimal working order today so we can get this in here (and more eyes on it to improve). I'm not sure what you mean by the URLs category, links to all external tools and thing linked to? (we can sort that out later if it something not documented right now)

And yes, that looks like the right `sed` command, which I finally learned some basics to do a lot of the link updating in all the wiki files.

Oh, 4.0 release, sure go ahead! Don't wait for me :-)

**Comment by frostworx** [comment]
You're probably right, the URLs category doesn't make any sense, as there's nothing to see there, so just ignore that brainfart :)
Ok, cool, then I'll roll a v4.0 tomorrow - too late for today, I'm sure I'd make mistakes :)

**Comment by podiki** [comment]
Sounds good, and should hopefully be ready to merge the readme/wiki after that

**Comment by frostworx** [comment]
Sounds great, but no need to hurry _(I can imagine though, that you want to get to an end though :))_

**Comment by podiki** [comment]
Okay....I think everything is in a base working state. Probably there are links that got broken but I tried to update everything. The wiki homepage is now a list of all the detailed features, which is everything from the original readme (there might be some wiki pages that were not in that original list, but I haven't checked).

I didn't move the basic config and usage from the readme to the wiki, but linked in the wiki homepage back to Readme for that. I didn't do 3 (not ready for more big organizational changes) or 4 (to see everything working on my fork first).

But I think this is a good starting place, what do you think? Let me know if there are glaring errors or things to change, but I think I want to hold off on restructuring the many wiki pages. All (?) should be linked from the homepage feature list which is organized at least a bit.

**Comment by frostworx** [comment]
Wow, you were very busy, this is an amazingly good starting place! :)
Thank you very much for your huge help!
Whenever you are ready for a PR, I'll be happy to add it!

**Comment by podiki** [comment]
Woohoo! Thanks!

Just one of those things that's best to just do all at once and power through, or else would have become a huge mess. Any tips of how you'd like the PR? I should squash the readme changes to one commit, not sure how you want to handle the wiki (or how that works, I'll have refresh myself in those links, but I guess just like a regular fork/PR).

**Comment by frostworx** [comment]
I have no clue how to best merge the wiki to be honest.
To avoid confusion, I'd package the 4.0 release this morning before and then check those links again as well.

**Comment by frostworx** [comment]
yay [v4.0](https://github.com/frostworx/steamtinkerlaunch/releases/tag/v4.0) is out.
I'm not done with my forst coffee, so I might have missed something, but your url https://gist.github.com/larrybotha/10650410
from above looks not too complicated. Is there anything I can help you with?

**Comment by podiki** [comment]
Ok, this sounds like the plan to me:

1. Check that the wiki looks usable for a first version
2. Once it looks good, either you clone it and run `sed` to change all the internal links, or I can
3. Follow the gist we saw (basically clone the wiki and pull my changes, then push to here)
4. Check that all works on this end
5. Then we can update the readme here, doing that last since all the info is removed from it (again need to run `sed` to update links). I guess this can be done through normal PR.

**Comment by frostworx** [comment]
I haven't checked every single link in the wiki, but IMHO it looks excellent for an initial launch.
Maybe users have suggestions or fixes, but this would be more welcome than a problem.

The point I was actually missing was that I can simply clone my wiki the using ssh like any project. So it would be very simple to 
1. pull your wiki **done**
2. `sed` **done**
3. ssh pull my dummy wiki **done**
4. add your wiki files **missing**
5. commit my updated wiki **missing**

The problem though is, that using this method you are not listed as contributor to the project _(if that is ok for you, I'd finish 4+5)_
You could finish the Readme though with the final changes (`sed`) and PR that regularly, which would add you at least, although just with just a few changes lines of course.

**Comment by podiki** [comment]
Well I guess another option is if I have access to the wiki git (or access on the web interface?), then I can push the changes. Not a big deal for me, don't worry about that (although hopefully you get more and more help and can make a contributors page or something). Though we can think about going forward to have others help maintain and contribute to the wiki.

Anyway, I'll make the readme PR later today and once the wiki is operational on this end.

Edit: and appreciate the question about contribution!

**Comment by frostworx** [comment]
This would be great indeed, I need to find a way though where this can be configured :)
I'll report back if I found something out.
Thanks for the friendly and patient communication!

**Comment by frostworx** [comment]
If understood [this](https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis) correctly,
I just opened editing the wiki for everyone. A per-user rule would be better of course.

**Comment by frostworx** [comment]
Just sent a collaboration invitation. I guess that's the only thing needed _(closed the public wiki access of course)_

**Comment by podiki** [comment]
Thanks! Do you want me to push the wiki changes then? The readme I'll still do a PR (makes me nervous pushing to someone's repository directly, and this will probably need to be forced due to commits after I forked to the Readme, though I think I incorporated those changes too).

**Comment by frostworx** [comment]
Thank you! Yeah, feel free to push your wiki! It would be perfectly fine of course if you prefer to PR the readme.

**Comment by podiki** [comment]
Great, will get those both done later today!

**Comment by frostworx** [comment]
W00000t!!!!!!!!!!!!!!!!!!!11111111111111

**Comment by podiki** [comment]
Ah, a short readme and easy to find stuff in the wiki. Nice new base to work from, if I do say so myself! Thanks for the patience and support, was very happy to contribute!

**Comment by frostworx** [comment]
Thank you VERY MUCH for your great help, @podiki 
https://www.reddit.com/r/SteamTinkerLaunch/comments/m6hbvv/steam_tinker_launch_has_a_wiki/

**Comment by frostworx** [comment]
Just also updated the [4.0 announcement](https://www.reddit.com/r/SteamTinkerLaunch/comments/m62sos/release_steam_tinker_launch_40_four_play/)
