### ISSUE TITLE
Refactor determining the game window

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#183]
I'm going to refactor the determination of the current gamewindow.
It will be simplified, easier to read and more central.
The plan is to autodetect it in the background and save it as game metadata in any case.
This will obsolete most/all window-detect functions in SBS VR mode and might even temporarily break them until it is done.
Feel free to comment or add suggestions if you use the SBS VR feature.

**Comment by frostworx** [comment]
Implemented in https://github.com/frostworx/steamtinkerlaunch/commit/fa7c2564a11f54ab502c72eef9096fc24c636163
Sent my Valve Index to RMA, so if the `startSBSVR` function
was only tested/optimized in
`waitForGameWindowName` and `waitForGameWindowXid`
subfunctions.
Feel free to test/report `SBSinitVRVideoPlayer` and `SBSstopVRVideoPlayer` 😮‍💨

When no one reports any issues within the next days, I assume it is working as expected and prepare slowly a new release.

**Comment by frostworx** [comment]
Added in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v3.9

**Comment by gu1ll0me** [comment]
I'm not sure if it is related but closing Tomb Raider 2013 now triggers the "User stop command". That was not working with this game with v3.8.

Thanks!
