### ISSUE TITLE
Use both Gamemode and Gamescope

### ISSUE THREAD

**Issue by gu1ll0me** [sonic2kk/steamtinkerlaunch#188]
I read on lines 9304-9316 that it is impossible to launch a game with both Gamemode and Gamescope. 

I do some tests on my side and it should be possible with : `gamemoderun gamescope -w 3840 -h 2160 -W 1920 -H 1080 -f -- %command%` - `gamemoded --status` indicates that gamemode is active.

Is there a reason why it is not possible by design?

Thanks.

**Comment by frostworx** [comment]
The reason is nobody committed a pull request and I didn't care.
Thanks.

**Comment by gu1ll0me** [comment]
Great, maybe there was an incompatibility that I was not aware of.

I will try to figure out how to create a pull request for that.

**Comment by frostworx** [comment]
Sounds good. Thanks for trying!

**Comment by frostworx** [comment]
Still trying?

**Comment by frostworx** [comment]
Shouldn't be too hard to add, so feel free to stop or not start trying.
I'll add it.

**Comment by frostworx** [comment]
Should be working with https://github.com/frostworx/steamtinkerlaunch/commit/2588f0a2074ca61020314d3d4f6c2308687bb0e0
