### ISSUE TITLE
Add Non-Steam Game via command line and gui

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#190]
Started to implement as standalone feature to
add a Non-Steam Game via command line or gui.
Command line functionality is almost finished _(offline_) with the following options _(from offline `README.md`)_ :

----------

#### Add Non-Steam Game
Adding a Non-Steam Game to Steam using **stl** is very easy.
This can be done either completely via [Command Line](#Command-Line) or via Gui.

The Gui can either be started via commandline using the `addnonsteamgame` *(ansg)* parameter without any further arguments
or from the main [Settings Menu](#Settings-Menu) under [Extra Buttons Menu](#Extra-Buttons)

For [Command Line](#Command-Line) only mode the following options followed by the `addnonsteamgame` *(ansg)* parameter are accepted:
-	`-an=|--appname=`				*(App Name - optional)*
-	`-ep=|--exepath=`				*(Full gamepath **required!**)*
-	`-sd=|--startdir=`				*(Start Dir - optional)*
-	`-ip=|--iconpath=`				*(Icon Path - optional)*
-	`-lo=|--launchoptions`			*(Game Launch Options - optional)*
-	`-hd=|--hide=`					*(Hide Game - optional, default disabled)*
-	`-adc=|--allowdesktopconf=`		*(Allow Desktop Conf - optional, ?, default disabled)*
-	`-ao=|--allowoverlay=`			*(Allow Overlay - optional, default disabled)*
-	`-vr=|--openvr=`				*(OpenVR - optional, default disabled)*
-	`-t=|--tags=`					*(Tags - comma-separated, default empty)*

A working example for a bare minimum command line is:
`stl ansg -ep=/media/B4-1/GOG/Pirates\!/start.sh`
*(the game will be added with Title start.sh to the Games Library as no `-an` was provided, as `-sd` the game directory will be used automatically)*

**To actually see the added games, the Steam Client needs to be reopened, as the created/modified 'shortcuts.vdf' isn't reloaded on runtime!**

**NOTICE: Looks like it is not enough to add Tags to the shortcuts.vdf, as they do not show up.
The tags option is more or less useless for now, but in the hope to find the missing puzzle piece I'll keep it implemented
If this would work it would f.e. also be possible to add all Linux native games automatically into a 'Linux' or 'Non-Steam' Games into a 'Non-Steam Steam Category'**

**Comment by frostworx** [comment]
Regarding the non working Tags in 'shortcuts.vdf' I just found this:
https://github.com/Depressurizer/Depressurizer/issues/172#issuecomment-585030363
Haven't tested if this still works _(or if it works at all under Linux)_, but maybe someone reads my issues and is interested.

Edit: Gave it a very quick test, and **yay** it works! :)

**Comment by tr1p0p** [comment]
So, i confirm this feature not properly working, even with the reload of steamlibrary and all. Steam really don't want to show my non-steam games added with this tools, and don't care about tags..

**Comment by frostworx** [comment]
Of course this can always break, when steam changes something, but at least for now I can't reproduce your problem.
Adding a custom program still works as it did before.
Please add more details what you are doing exactly.
