### ISSUE TITLE
Looking for a 4.0 release title

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#194]
I'm looking for a 4.0 Release title.
Would be nice if you'd help to find one either here or on [r/SteamTinkerLaunch](https://www.reddit.com/r/SteamTinkerLaunch/comments/lw5n9r/looking_for_a_40_release_title/)

As there's only one chance for a special "4.0 title", I'd prefer something like

"Live Free or Play Hard"

**Comment by frostworx** [comment]
via steamgriddb discord:
```
EASY name for 4.0
The Fourth Horseman
```

**Comment by podiki** [comment]
...."Four Play"....?

**Comment by frostworx** [comment]
We have a winner! :)
