### ISSUE TITLE
cheatengine

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#200]
apparently the ce download was removed from the github page https://github.com/cheat-engine/cheat-engine/releases.
feel free to PR sane patches with a sane dl url. [this](https://github.com/frostworx/steamtinkerlaunch/issues/160#issuecomment-736897776) might help.
#199 #198

**Comment by frostworx** [comment]
the md5 of my old download is 
`8ce5de1b284bc9f865865902fea09489  CheatEngine72.exe`

**Comment by frostworx** [comment]
https://github.com/cheat-engine/cheat-engine/issues/1523

**Comment by frostworx** [comment]
After reading [this](https://www.cheatengine.org/downloads.php) I doubt that a "a clean install file" will become available again on github.

**Comment by esotericDisciple** [comment]
Uh, no. The game menu says 7.1 is the cheatengine version. I haven't used cheatengine in four months, so I've might have forgotten how to use steamtinkerlaunch entirely, but the docs on getting cheatengine to work weren't helpful at all; there's no screenshots for the process at all...

**Comment by neurodiverseEsoteric** [comment]
So basically this issue can't be fixed and therefore steamtinkerlaunch is not longer usable?

**Comment by frostworx** [comment]
Looks like there's no other valid download url for the removed "clean install file", and those who want to use CE via steamtinkerlaunch either have it downloaded before or are unwilling to help _(and/or unable to read)_.
Of course I could simply host the last "clean install file" myself without any legal issues and use that as source,
but there is apparently no reason to do so currently.
There's still a chance that upstream reacts on my issue of course.

**Comment by frostworx** [comment]
Someone reminded me in the upstream issue that there's still the rar file to download _(already linked [above](https://github.com/frostworx/steamtinkerlaunch/issues/200#issue-837364978) ='this' )_.
If someone is intererested in creating a PR for the download, extract and unrar dependency check _(instead of innoextract)_
a (currently) valid wget command would be
`wget -O CheatEngine72.rar --user-agent="Mozilla" --referer=https://www.cheatengine.org/download.php 'https://www.cheatengine.org/download/CheatEngine7.2_MissingSetup.rar'`
Should be very easy to change, so this might be your chance to actually contribute instead of only expecting a "fix".

**Comment by neurodiverseEsoteric** [comment]
I've never used stl language/code before...

**Comment by frostworx** [comment]
It is pure bash.
I also commented the [upstream issue](https://github.com/cheat-engine/cheat-engine/issues/1523) _(as mentioned this is not my bug)_
Might help to comment as well _(or at least read it , if the problem still is not clear)_

**Comment by neurodiverseEsoteric** [comment]
What is pure bash? I don't have time for reading the source code, let alone editing it...

**Comment by frostworx** [comment]
@neurodiverseEsoteric Just check the shebang...
Until you're not able to show a little decency if you are unwilling to help,
please be so kind and stop commenting anything on this project. It is pure waste of energy, space and time.

**Comment by frostworx** [comment]
invalid with [this commit](https://github.com/frostworx/steamtinkerlaunch/commit/f3bab03866c165d3446296309fa18a92f0f5e770) and this [wiki entry](https://github.com/frostworx/steamtinkerlaunch/wiki/Cheat-Engine)
