### ISSUE TITLE
Conty support

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#202]
Might be a nice idea to _(optionally)_ auto-use [Conty](https://github.com/Kron4ek/Conty) if a 32bit game executable is found.
Haven't tried it yet, so no idea if this would even work - I just like the idea.

~~I also still like my _(I'm sure there were others as well)_ ancient idea to have a `WINEPREFIX` in a squashfs image - maybe it is worth a try to try something based on the Conty scripts.~~ ~~_(Edit: No, Conty is no help here, but in case a steam game is even working with a fully read-only image, I'll consider adding this as an option)_~~ (_Edit: No, proton doesn't accept a readonly pfx)_

**Comment by Kron4ek** [comment]
I assume there might be some problems with running Proton 5.13 and newer using Conty, because Valve uses similar container (also with bubblewrap) for Proton 5.13, so it will be like runinng bubblewrap inside bubblewrap, i don't know if this will work, some testing is needed. However, native games and older Proton version (5.0-x and older) should work fine.

**Comment by frostworx** [comment]
Thanks for the feedback!
In case they don't work together it would be still possible to disable the SteamLinuxRuntime in favor of Conty. Probably allowing this should be an additional option then.

**Comment by frostworx** [comment]
Rough list of option ideas:
- Checkbox to "Auto Conty" whenever a 32bit game exe was found
- Checkbox to "Force Conty" (f.e. required for wrapper start scripts where the archtitecture can't be determined)
- Option to define the path to Conty
- Option to download Conty from the project page automatically into the stl downloaddir
- _(if required)_ Option to disable the SLR in favor of Conty, as they [might interfere](https://github.com/frostworx/steamtinkerlaunch/issues/202#issuecomment-808703157)

**Comment by frostworx** [comment]
- Added [Conty Steam Category](https://github.com/frostworx/steamtinkerlaunch/wiki/Conty)

**Comment by frostworx** [comment]
- Added Auto-Update for Conty and improved its download function  ([commit](https://github.com/frostworx/steamtinkerlaunch/commit/20ca40616580e07f5cd053ad245aed1c60c3ef42), [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Conty))
