### ISSUE TITLE
WINE DLL Override Support?

### ISSUE THREAD

**Issue by Leaguesman** [sonic2kk/steamtinkerlaunch#205]
Hi, apologies if stl is already capable of this, but I wasn't able to find explicit mention of how to do it in the wiki or in any other raised issues. I want to set the WINEDLLOVERRIDES environment variable, as I'm using a custom patch for a game that hooks in via replacing a dinput dll. Does stl have a setting for this?

**Comment by frostworx** [comment]
Hi,
you're right. It is not yet implemented directly. I thought there's no need for it, as it is just one variable anyway (which could be simply added with the editor into the corresponding gamecfg file). If you think this would be a useful feature, I can implement it as well though. At least a basic implementation (like WINEDEBUG f.e) would be pretty easy. An extra gui for setting a variable to (n|b|d) would be nice, but harder to write.

**Comment by Leaguesman** [comment]
Thanks for the quick response, I didn't realise the editor worked that way, so I've simply added it there. I'd say it's likely not worth adding as a GUI feature at this stage, anecdotally speaking at least, a lot of the games I play which used to require DLL overrides have had the underlying issue resolved in newer Proton releases, and no longer need it.
