### ISSUE TITLE
Gamescope gui

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#220]
Adding a Gamescope gui

**Comment by frostworx** [comment]
https://raw.githubusercontent.com/frostworx/repo-assets/master/pics/gamescope-settings.jpg

**Comment by frostworx** [comment]
in next release

**Comment by Termuellinator** [comment]
Would it be possible to add more Frame Limiter options in the GUI Dropdown? Like 90 or (for me) 120 fps?
Or should i create a new issue for that?

**Comment by frostworx** [comment]
Sure, no problem.
Will be pushed with the next monster commit :)
Re-Opened so I won't forget it.

**Comment by frostworx** [comment]
Already added live in git :)
Feel free to reopen if something is wrong.

**Comment by Termuellinator** [comment]
that was quick, thank you! :D
