### ISSUE TITLE
{Suggestion} Automatically Stop Gamemoded Process After Game Exits

### ISSUE THREAD

**Issue by Nano-Ocelot** [sonic2kk/steamtinkerlaunch#234]
Pretty self explanatory suggestion. I think it would be nice if gamemode were to stop after the game stops. This could be a toggleable option for those that don't like it.

**Comment by frostworx** [comment]
GameMode is supposed to already stop automatically together with the game without the help of stl,
which afaik only does not work when the game hasn't exited correctly.
In this case there's nothing though what stl could do automatically, so closing the game with the Kill Switch button would be the only option.

**Comment by Nano-Ocelot** [comment]
Very strange. Mine has never stopped on its own for any game ever.

**Comment by frostworx** [comment]
Any chance you mean the gamemoded systemd --user service?

**Comment by frostworx** [comment]
If so it should be possible to simply stop it with calling a custom [stop script](https://github.com/frostworx/steamtinkerlaunch/wiki/Start-Stop-Scripts)

**Comment by Nano-Ocelot** [comment]
I'm talking about the process named 'gamemoded' that appears in my system monitor after starting a game. It doesn't close itself after the game exits and I'm understanding now that it's supposed to? I have wrote a script and selected it in the 'user stop script' section of stl that includes 'pkill -f gamemoded' but for some reason that isn't working either despite the other commands in the script working fine.

**Comment by frostworx** [comment]
yes, this is the 
`systemctl --user status gamemoded`
service

**Comment by Nano-Ocelot** [comment]
So then should I just call a command like 'systemctl --user stop gamemoded' to stop it instead?

**Comment by frostworx** [comment]
I guess that should work, but never tried it and this is out of the scope of stl of course.

**Comment by Nano-Ocelot** [comment]
Thank you. I'll separately file a bug report on their page now that I know that this isn't intended behaviour.

**Comment by frostworx** [comment]
Not sure if it is supposed to behave differently, but worth a try to ask in any case :)

**Comment by frostworx** [comment]
Would be nice if you'd ping back here what the result was with your upstream bug report.
TBH I never cared about the daemon keeps running in the background, but generally the question of why it even has to be running as service is a good one, as gamemode "client" is started together with the game anyway _(and the daemon is running with user priviledges anyway, so a "client" should be enough)_

**Comment by frostworx** [comment]
Any news or upstream issue to share already?

**Comment by Nano-Ocelot** [comment]
I don't believe this is an issue or bug. I was uneducated on it. Now I see that when a game exits the service reverts to reporting a status of something along the lines of 'awaiting game start.' So it wasn't actually doing anything, just waiting patiently in the background for the next time I launched a game.
