### ISSUE TITLE
/steamapps no such file or directory

### ISSUE THREAD

**Issue by UltraBlackLinux** [sonic2kk/steamtinkerlaunch#242]
Hey there,
I recently started using STL until now I have some weird problems:
I am currently trying to manage my stl config, so I ran `stl launcher menu` but for some reason, the list is completely empty (and it was full at some point) so I tried running `stl update allgamedata`, and that actually did something, but always errored with `find: ‘/steamapps’: No such file or directory"`.
I think this is related to my steam folder being on a separate drive, instead of the default folder (My games take up too much space lmao)
What can I do to fix this?
Thanks!

**Comment by frostworx** [comment]
Hi there,
I wouldn't have really expected that someone uses the little launcher function in stl, but for someone exactly reported the very same problem some days ago.
I assume you use the latest release v.6.8, right?
Would be nice if you'd check the latest master, as I'm pretty sure that [my fix](https://github.com/frostworx/steamtinkerlaunch/commit/9a8bcdb3863fdc1d4be803cb776a5cdd427a299c) does work (haven't received any feedback from the previous report).

**Comment by UltraBlackLinux** [comment]
Oh that worked perfectly fine! Thanks alot!

**Comment by frostworx** [comment]
cool!, thanks for testing and reporting!
