### ISSUE TITLE
Game Config not working

### ISSUE THREAD

**Issue by UltraBlackLinux** [sonic2kk/steamtinkerlaunch#243]
Hey there again,
I am still trying to configure my game, this time, it isn't showing a config screen - the global config doesn't seem to exist, and same for the game itself.
While trying to get this to work, I also deleted the stl configs via the Edit button. It still doesn't work (Now even my game's progress is wiped for some reason. fml)
What am I doing wrong?
Thanks!

**Comment by frostworx** [comment]
Hard to tell what went wrong without logs here.
Please check/attach them. See - https://github.com/frostworx/steamtinkerlaunch/issues/93

**Comment by UltraBlackLinux** [comment]
[Nova Drift.log](https://github.com/frostworx/steamtinkerlaunch/files/6526392/Nova.Drift.log)
Oh sorry, yeah, here it is.

**Comment by frostworx** [comment]
the log looks good, it even found the window of the running game.
are you sure this is the correct one?
You could also remove /deb/shm/stl/*
could be possible that a part of an autogenerated menu was left, after you updated stl in the previous issue.

Also the initial resolution of game, defaul, global and favorite menu are pretty small and, depending on yout gtk theme you might not see the scrool bar of the windows (wich could explain your empty menus). You could try to resize them and also press F1 (with a new enough yad version, afaik >10.0) to configure the amount of columns of the open menu (you need to re-open that window when changing the value).

**Comment by UltraBlackLinux** [comment]
> the log looks good, it even found the window of the running game.
> are you sure this is the correct one?
> You could also remove /deb/shm/stl/*
> could be possible that a part of an autogenerated menu was left, after you updated stl in the previous issue.
> 
> Also the initial resolution of game, defaul, global and favorite menu are pretty small and, depending on yout gtk theme you might not see the scrool bar of the windows (wich could explain your empty menus). You could try to resize them and also press F1 (with a new enough yad version, afaik >10.0) to configure the amount of columns of the open menu (you need to re-open that window when changing the value).

Ok, after desperately trying this for a while, I give up, this did not work.

**Comment by UltraBlackLinux** [comment]
@frostworx after some random copying files' content over into other files, I found the cause for the menu being empty:
The /dev/shm/menutemp/gamemenu-template is always an empty file - after pasting the contents of rawentries.txt into that, the menu works. At least for now lmao

**Comment by frostworx** [comment]
pretty sure this is a local problem.
I suggest you rename `~/.config/stl`, remove recursively `/dev/shm/stl` and then start
`stl settings`
from a terminal.
then open the game menu.
if it still does not work, please upload the fresh log again `(also check `/dev/shm/stl/stl.log`)`

how did you install stl btw and which ditro?

**Comment by UltraBlackLinux** [comment]
I completely forgot to tell you, what I did and whatnot: 
1st of all: It now works surprisingly.
I installed stl via the chaotic-aur.

**Comment by UltraBlackLinux** [comment]
Oh, before I create another issue, that will lead you to saying me, that it's a local problem:
I set my game to launch in a virtual desktop once, and disabled it again, but since then, my game is always starting in a virtual Desktop - I think the disabling is broken, I will try to disable it manually via the winecfg checkbox

**Comment by frostworx** [comment]
Likely that the virtual desktop option is removed anyway.

**Comment by frostworx** [comment]
It was easier to implement disabling the previously enabled virtual desktop than removing the whole function.
will be pushed with the next commit
