### ISSUE TITLE
Feature Request: Ignore removed games

### ISSUE THREAD

**Issue by UltraBlackLinux** [sonic2kk/steamtinkerlaunch#245]
Hey, there,
I don't like my old removed games to appear in stl, when running `stl update allgamedata` - Could you remove that or add a flag or something similar to ignore them?
Thanks!

**Comment by frostworx** [comment]
If you find a sane way to parse all not deleted games from the steam datafiles, feel free to tell me and I check if it is implementable.
Won't parse binary vdfs though.

**Comment by UltraBlackLinux** [comment]
oh well xD
I will look into it

**Comment by UltraBlackLinux** [comment]
@frostworx well I am not very familiar with shell, so it'd rather let you do this:
In the folder steampath/uesrdata/steamuser/config/ is a file called localconfig.vdf - if you scroll down a bit (maybe to around line 180), you get to a section, that contains all your games' ids and last-played-date - I would suggest, to just add the game to a list, if it wasn't played for x days/if the playtime was lower than x, or something like that.
(all installed games also have BadgeData, Playtime2wks and ViewedLaunchEula on top of LastPlayed and playTime (only for some))

**Comment by frostworx** [comment]
Yes, I already [use localconfig.vdf](https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L274).
I'm not interested in writing some weird calculation for this though, sorry.
I would accept a sane PR though, if the function is implemented optional.
Closing here
