### ISSUE TITLE
Hey, @alanjjenkins,

### ISSUE THREAD

**Issue by j03prap** [sonic2kk/steamtinkerlaunch#247]
Hey, @alanjjenkins,
good idea indeed.
I planned to make a break after v6.8 to travel through the nature, but it is still damn cold for late May here, so I might add it sooner than I would like to :)
I suggest we use this ticket for collecting ideas. It might not even too hard to implement (depending on how many ideas we have),
but if you want to help implement it this would be great of course!

some loose ideas:

- make the feature generally optional and by default disabled
- compdata directory names could be simply "${GAMEID]-${USEPROTON}"
- work with symlinks if possible _(so symlink  "${GAMEID]}" points to real directory  "${GAMEID]-${USEPROTON}")_
- what to do on proton version bump? and which options to offer?
- option to migrate users/steamuser _(maybe bound to enabled [backup](https://github.com/frostworx/steamtinkerlaunch/wiki/Backup-Support))_
- propably more to come :)

_Originally posted by @frostworx in https://github.com/frostworx/steamtinkerlaunch/issues/240#issuecomment-845424853_

**Comment by frostworx** [comment]
Closing here. If there was a serious reason, feel free to reopen and elaborate.
