### ISSUE TITLE
⚠️👋Break

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#248]
I'm taking a break from working on steamtinkerlaunch.
PRs are welcome of course meanwhile
_(not only from those who announced contributions ;))_
cu later _(maybe)_

**Comment by Faalagorn** [comment]
No rush and don't burn out, the project should be mature enough to be fine on its own I guess, if I'll get some time I might send some minor PRs but nothing major either – at least my GitHub notification will thank you, as they'll be less crowded! :D

**Comment by frostworx** [comment]
I'm more or less back :)
