### ISSUE TITLE
Cheat Engine filesystem access bug?

### ISSUE THREAD

**Issue by SerraraFluttershy** [sonic2kk/steamtinkerlaunch#249]
Hello. I am currently running the latest version of STL, and have attempted to use CE to hack a game by enabling it in the game's wineprefix config. The problem is that while CE launches fine and can detect the game's EXE, this game loads corresponding .BIN files into memory which Cheat Engine is unable to see despite (from my understanding) running as administrator by default within Wine/Proton. 

Is there any way I could get CE to see these files and edit their corresponding memory regions? I've attached my game's respective log file in case I've missed something that could fix my issue.

[DoDonPachi Resurrection.log](https://github.com/frostworx/steamtinkerlaunch/files/6589914/DoDonPachi.Resurrection.log)

**Comment by frostworx** [comment]
Hi there.
As CE seems to start using the game exe correctly I'm afraid I can't help you with that. The log file seems to look sane as well, so I wonder if it could be a problem directly in CE. Maybe worth to ask upstream(?)
I see you use the older 7.1 version, maybe they fixed their bug in the later "paywalled" 7.2 version.

**Comment by frostworx** [comment]
Feel free to reopen if you still think this is steamtinkerlaunch related.
If so, a step by step howto to reprocuce this would be nice.
_(I do not really use CE and never searched for a .BIN file for it)_
