### ISSUE TITLE
Downloading failing for d3dcompiler_47_64.dll

### ISSUE THREAD

**Issue by podiki** [sonic2kk/steamtinkerlaunch#250]
Was trying to play around with ReShade and ran into all sorts of weird errors (lots of syntax errors, no shaders loading or even the ReShade interface itself). Finally figured out that not everything was downloaded because at some point https://dege.freeweb.hu/dgVoodoo2/bin/D3DCompiler_47.zip became unavailable (I previously had downloads, but when removing to start over I lost them). This is noted in the logs if you look for it, relevant lines below:

```
../logs/stl/title/Bayonetta.log:Fri Jun  4 09:55:26 PM EDT 2021 404 - prepareReshadeFiles - '/home/.../.config/stl/downloads/reshade/d3dcompiler_47_64.dll' missing - downloading
../logs/stl/title/Bayonetta.log:Fri Jun  4 09:55:33 PM EDT 2021 SKIP - installRSd3d47dll - Sourcefile '/home/.../.config/stl/downloads/reshade/d3dcompiler_47_32.dll' missing - skipping this file
```

Is there a better source for this file? And can an error like this be reported more clearly to the user, as otherwise diagnosing what went wrong is difficult? Though that might be on ReShade to notify that it doesn't have the proper compiler it needs.

No rush on this, I know you are taking a break #248 :-)

**Comment by podiki** [comment]
Just found out this dll can be made available via protontricks: `protontricks appid d3dcompiler_47`. I assume this would also do the trick, though I know stl does everything on its own (though this might lead to a better source for the file?).

EDIT: or winetricks more directly. And here is where they get it from: https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L6263

**Comment by frostworx** [comment]
looks like the ssl certificate is botched.
http://dege.freeweb.hu/dgVoodoo2/bin/D3DCompiler_47.zip
still works. I'd guess this is a temporariy glitch on the dege.freeweb.hu webserver
I'm not too much interested in implementing a different download url by downloading and extracting a firefox setup exe and downloading the dll from there tbh.

**Comment by podiki** [comment]
That whole domain doesn't work for me (https or not). Understandable you don't want to deal with the convoluted extraction like winetricks, and I'm guessing you don't want to rely on winetricks more than you need to?

I tried searching for an alternative download location that seems stable/not sketchy, but didn't find any right away. I'll look some more.

**Comment by podiki** [comment]
I see the dll in this repository: https://github.com/xlgames-inc/XLE (under the Final_ folders). Not sure if they are the same version exactly as from where stl was downloading (based on quick sha256sum, was from 6 years ago), and what difference that might make. Likewise from other programs like Krita (https://steamcommunity.com/sharedfiles/filedetails/?id=1726034225).

Can probably just redistribute the dlls directly (https://stackoverflow.com/questions/33250832/is-it-necessary-to-redistribute-directx-from-the-windows-sdk)? I could make a repository just for the dll.

EDIT: Lutris has the file (again not sure on versions, etc.): https://lutris.net/files/tools/dll/d3dcompiler_47.dll

**Comment by frostworx** [comment]
thanks for searching!
Likely this has to be a specific version of the dll. I'll compare those you found with the dege one (strange that both downloads don't work for you). If all are different, I consider uploading the old one on the repo-assets repo.

**Comment by frostworx** [comment]
Looks like all versions above are different _(haven't digged out the krita dll from their code though)_.
both the old and new (`wget http://dege.freeweb.hu/dgVoodoo2/bin/D3DCompiler_47.zip` still works for me) downloaded dll from dege have
`c971cde5194dd761456214dd5365bdc7` as md5sum.
I'll simply add it to the repo-assets and *fixed*

**Comment by podiki** [comment]
Awesome, thanks!
