### ISSUE TITLE
WINEDLLOVERRIDES set by ReShade

### ISSUE THREAD

**Issue by podiki** [sonic2kk/steamtinkerlaunch#251]
Related to #205. If ReShade is enabled as an option in the Game Menu, then `WINEDLLOVERRIDES` is set (as needed for ReShade) which will overwrite the variable set in the config file. For example, if you need a dll override for a particular game (or a mod), but then also enable ReShade, game will not run with both. A workaround is to use the ReShade overrides in the game config along with whatever else you need (don't enable ReShade through the menus). Minor wrinkle is if you are using this for Depth3D VR stuff, will need to manually open `vr-video-player`.

Solution I think is easy, changing https://github.com/frostworx/steamtinkerlaunch/blob/0cdf8bda1688b9c616661732182068a93c6a5596/stl#L5607 to

`export WINEDLLOVERRIDES="$WINEDLLOVERRIDES;dxgi=n,b;d3d9=n,b;d3dcompiler_47=n,b"`

I'll make a PR for that to review at your leisure.

(Returning to #205, it would be nice to have at least an empty box in the Game Menu for specifying `WINEDLLOVERRIDES`)

(I know you are on break, again no rush! Just spent more time playing with ReShade.)

**Comment by frostworx** [comment]
Maybe implement "an empty box in the Game Menu for specifying `WINEDLLOVERRIDES`" later.

**Comment by podiki** [comment]
Sounds good!

**Comment by frostworx** [comment]
Just added https://github.com/frostworx/steamtinkerlaunch/commit/477b00406c4305aaa8f3f60e1bc07bd67e0a6381
Not really tested, but doesn't look bad :)
*(I still like the idea in #205 to have a "wysiwyg" WINEDLLOVERRIDES menu, but not sure if it is worth the effort yet)*

**Comment by podiki** [comment]
Great, will have to try it out.

As for the idea in #205, that does sound good but maybe a lot of work? Maybe there is a list, or way to scrape protondb or similar, of frequent dll overrides? So we could have some suggested ones, as well as a type what you want box and checks for native, builtin, etc. Not sure if it is worth making so fancy, I would figure most of the time you'd be copy and pasting what you've seen someone do or instructions from somewhere.

**Comment by frostworx** [comment]
Yeah, probably copy/paste is enough in most cases.
I [once](https://github.com/frostworx/steamtinkerlaunch/issues?q=is%3Aissue+protondb+is%3Aclosed) planned to scrape the protondb, but parsing tons of loose, unformatted text without an api isn't too much fun.
