### ISSUE TITLE
ReShade repositories

### ISSUE THREAD

**Issue by podiki** [sonic2kk/steamtinkerlaunch#253]
Looks like ReShade on Windows includes several other repositories. Unfortunately I can't seem to find the list it actually uses (is an embedded resource in the code, would be `Setup/Config/EffectPackages.ini` I think). For now I looked at some YouTube videos of ReShade installation and see a list of interesting packages. I also found the previous list before it was moved: https://github.com/crosire/reshade/blob/1f8df3187f51d565dbf3653448a46495d475fb02/setup/Dialogs/SelectEffects.xaml.cs#L36

More immediately, I noticed that https://github.com/crosire/reshade-shaders defaults to the `slim` branch, which has few shaders compared to `master`.

Can we change the branch of that repository and add some others? If that's fine with you I can make the changes and a PR later.

EDIT: Ah, here is a list from the PCGamingWiki: https://www.pcgamingwiki.com/wiki/ReShade#List_of_known_shader_repositories

EDIT2: I think a lot of the shaders that are not in the `slim` branch moved to the SweetFX respository, based on commit logs.

**Comment by frostworx** [comment]
I'd prefer to keep just a few core shader repos with the most important shaders as global shaders, as with enabled shaders auto update every repo would get updated.
A better approach would probably be to add user defined shaders (thinking about it when my break is over :))
Would mind a PR with a minor change of one of the repos with a better/more active one of course.

**Comment by podiki** [comment]
Gotcha. I think including SweetFX at least would be good as that was originally bundled with ReShade, I can add it with a simple PR. I'll look at the others, maybe the RetroArch one for emulators/CRT effects especially. Those look very nice for pixel art games. But yeah, can keep it minimal, easy enough for anyone to download them for a game.

As for user shaders, maybe can set a custom directory where you put them, and stl can copy (or symlink to keep updated) to a game... That could use the same Shader Menu as right now, picking up ones from the user folder and enabling/disabling. Not sure, but if it fits in with what stl currently does, could be nice. Not necessary probably.

No rush, just been diving into this recently as you can tell. Of course right when you go on break :-)

**Comment by frostworx** [comment]
Hehe, perfect timing indeed, but no problem :)
I thought SweetFX was some Re-Shade incompatible shader format _(tbh I don't know very much about shaders, as I barely use them besides Depth3D)_. I'll check what can be improved when the engine restarts.

**Comment by podiki** [comment]
I think before SweetFX did shader injection in a different way (or something), but now there is a ReShade format SweetFX shaders: https://github.com/CeeJayDK/SweetFX

I also never used ReShade stuff before, but have been investigating for an stl guide for Boiling Steam, and wanted to show off a few things you can do with stl. Coming soon....

**Comment by frostworx** [comment]
Oh, sounds good. I hope you have fun digging through all those options (wouldn't be surprised if I forgot some myself :D) amd also have a use for some yourself.

**Comment by frostworx** [comment]
Might be a nice feature to check for all repos in https://www.pcgamingwiki.com/wiki/ReShade#List_of_known_shader_repositories
_(and remove all shader urls from the stl config)_ and parse a blocklist, where the user can add unwanted repos _(f.e. via checkbox menu)_.
**pros:**
* "self-maintaining" shader repos
* less confusing urls to configure/smaller url.conf
* would fix this feature request properly

**cons:** 
* changes of the pcgamingwiki url can break the automation
* an auto-pulled repo might have a different file structure, in which case the installation function would not work

**Comment by frostworx** [comment]
I'm going to add above during my break - in fact I even started working on it _(damnit!)_

**Comment by podiki** [comment]
Hahah sorry @frostworx!

Sounds like a great idea though. I wish I knew how to extract the ini file ReShade uses, as that would have the info you want already in a more easy to use way I think (based on what I understood from ReShade's installation code). Might take care of any repository differences too, but not sure.

Let me know if I can help!

**Comment by podiki** [comment]
Awesome, will do! I'll have a getting started guide out on Boiling Steam today/tomorrow I think, and can update that if this changes any of the instructions I wrote.

**Comment by frostworx** [comment]
Wow great! Thanks a lot for your help.

**Comment by frostworx** [comment]
Just pushed the changes: https://github.com/frostworx/steamtinkerlaunch/commit/77098bc4227a8571d78421889942e4bc2c3f43bc
Wiki is up as well: https://github.com/frostworx/steamtinkerlaunch/wiki/Shader-Management
_(opening the wiki via F1 from the Shader-Management gui already tested :))_

**Comment by frostworx** [comment]
Just successfully enabled, toggled, and removed _(individually and by disabling repos)_ more than 250 shaders in one game session. seems to work pretty fine.
It was a great idea to add more shaders - there are really nice new ones :)

**Comment by frostworx** [comment]
OH,  just found you already released your article!
Thank you very much for your great help, @podiki! :)
*now going reading it*

**Comment by frostworx** [comment]
Make sure to pull
https://github.com/frostworx/steamtinkerlaunch/commit/75916f35d7b9065328b1e309c231a2285d266d85
when testing.

**Comment by podiki** [comment]
Awesome! That's a lot to play with, I'll definitely give it a shot.

If you like the article, maybe we can make a section on the Readme or on the wiki to collect tips, guides, coverage (with the caveat that it may not be up to date with current stl though).

**Comment by frostworx** [comment]
Oh, this is of course a good idea :)

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/commit/4166c329883244780ee1aa55ebd26ce6c8124915
+
https://github.com/frostworx/steamtinkerlaunch/wiki

**Comment by podiki** [comment]
Also didn't see that you added the F1 key to wiki page, nice! I'll have to add a few updates to the Boiling Steam article

**Comment by frostworx** [comment]
*closing here* I guess it is working as expected :)
