### ISSUE TITLE
Custom command fork does not work as expected

### ISSUE THREAD

**Issue by NyaomiDEV** [sonic2kk/steamtinkerlaunch#255]
Hello. I am trying to run a custom Windows executable file (Bloodstained RoTN Widescreen Patch) before a game of mine (Bloodstained RoTN) launches (so I need to fork the custom command into background). While using the GUI, setting the custom command to fork does not run the patch at all. I assume this is where you'd put game patchers (like the community-made widescreen memory-hack ones). Am I missing something?

**Comment by frostworx** [comment]
Hi. I guess you forgot to enable "Custom command mode" - the checkbox directly above "Custom command".
If not, please append the log.

edit: added words, to make a complete sentence :)

**Comment by NyaomiDEV** [comment]
[Bloodstained Ritual of the Night.log](https://github.com/frostworx/steamtinkerlaunch/files/6665723/Bloodstained.Ritual.of.the.Night.log)

This is the log I got. It seems to be doing something but it doesn't work at all. Does 'starting regularly' mean it is started with vanilla Wine perhaps?

**Comment by frostworx** [comment]
So the exe is found and stl attempts to start it. In this case it is no stl problem, but probably simply a missing dependency of the exe (maybe a specific dotnet version?).
"starting regularly" isn't related, and just means that it is not started as console program.

**Comment by frostworx** [comment]
I don't have the game, but just digged out your exe from the net and started it with a different game.
When starting it in place of the game exe, a requester opens which tells you to launch the game first.
Means starting the exe works.
No idea why it doesn't open for you at all. Maybe a timing problem, or (more likely) the exe tries to patch the game exe which fails with proton/wine.

**Comment by NyaomiDEV** [comment]
> I don't have the game, but just digged out your exe from the net and started it with a different game.
> When starting it in place of the game exe, a requester opens which tells you to launch the game first.
> Means starting the exe works.
> No idea why it doesn't open for you at all. Maybe a timing problem, or (more likely) the exe tries to patch the game exe which fails with proton/wine.

I wonder if this exe's error logs can be, in fact, logged. Can there be a commandline instance (cmd.exe)?

**Comment by frostworx** [comment]
Wasn't @home. I guess you found [this](https://github.com/frostworx/steamtinkerlaunch/wiki/Wineconsole) meanwhile yourself.
closing here
