### ISSUE TITLE
Special K

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#256]
Never used it before, but looks like Special K is a very nice tool
https://wiki.special-k.info
and it seems to be pretty simple to add fully automated support for it _(similar to the [ReShade implementation](https://github.com/frostworx/steamtinkerlaunch/wiki/ReShade))_
_(not sure when I continue with working on stl though)_

**Comment by Faalagorn** [comment]
Special K is very popular tool under Windows recently, I never used it myself since I'm on Linux since, not sure how it works under Wine? More info here: https://www.pcgamingwiki.com/wiki/Special_K

**Comment by frostworx** [comment]
Hm, there's not much usable info on the web about Special K via proton, and no idea which are still valid,
so I tested with Alien Isolation like this:

- copied SpecialK32.dll as dxgi.dll into the game dir _(optionally also with SpecialK32.pdb for debugging symbols)_
- dxgi=n,b
- started the game once, to create a dxgi.ini
- changed this _(also tested some other settings)_:
```
[NVIDIA.API]
Disable=true
...
[Steam.Log]
Silent=true
```

I think that this should be enough, to  basically get it running, but the latest version crashes at once
and the one from https://steamcommunity.com/groups/SpecialK_Mods/discussions/0/3570700856110421443/?ctp=475#c2577697791651390592
hooks in, but the game window remains black forever (while specialk dxgi.log grows).

Help from people who actually used Special K before using proton (or still do with an up to date proton version) is very welcome,
as I'd like to avoid toggling every possible config option.

I could append logs, in case someone is interested to help, but I guess above issue can be easily reproduced on other machines as well.

**Comment by frostworx** [comment]
Just registered on the official forum, hoping there are some people using linux :)
https://discourse.differentk.fyi/t/linux-proton-dxvk-compatibility/1895

**Comment by frostworx** [comment]
A nice guy from [here](https://discourse.differentk.fyi/t/linux-proton-dxvk-compatibility/1895/4?u=frostworx) sent me [here](https://gitlab.special-k.info/Volla/SpecialK/-/commits/20210726-WineFixes)

**Comment by frostworx** [comment]
Looks like the main problem with latest special-k version is that it uses the function
`PowerSettingRegisterNotification` in `powrprof.dll` which is not implemented in wine:

`wine: Call from ... to unimplemented function POWRPROF.dll.PowerSettingRegisterNotification, aborting`

Older Special K builds _(tried [0.8.66](https://github.com/Kaldaien/SpecialK/releases/download/sk_0_8_50/SpecialK_0_8_66.7z), found in an older Proton Special K wiki)_ don't use that function and seem to work _(at least with some further configuration - just gave it a quick try and it crashed early after opening the game window -> other problem, probably configuration related)_

**Comment by frostworx** [comment]
No matter if it can be made to work or not, I'll start adding Special K support anyway within the next days.
If it doesn't work by the end of October, the code will be disabled before the upcoming release.

**Comment by frostworx** [comment]
Still doesn't seem to work...
Anyway I added a [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/SpecialK)
Suggestions welcome.

**Comment by frostworx** [comment]
Upstream tried to help on discord and suggested the ini option
```
[Compatibility.General]
UsingWINE=true
```

Unfortunately this didn't seem to help with both `stable` and `testing`, but shortly after I got the old `SpecialK 0_8_66` working with `Saints Row The Third Remastered` using Proton-6.18-GE-2 _(without the UsingWINE option)_
Trying some more games and might just default to the old specialk for the release.
latest version would be better of course, but still better than nothing.

**Comment by frostworx** [comment]
- updated the [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/SpecialK)
- **TODO** _(if possible)_: when both [ReShade](https://github.com/frostworx/steamtinkerlaunch/wiki/ReShade) and [SpecialK](https://github.com/frostworx/steamtinkerlaunch/wiki/SpecialK) are enabled, the ReShade installation should be redirected as SpecialK plugin ~~nah, too many quirks necessary for low benefit~~
- edit2: Will try anyway :)

**Comment by frostworx** [comment]
Just started Witcher 3 successfully with enabled FSR, SpecialK and Vortex :)

**Comment by frostworx** [comment]
Upstream hid my initial support thread as spam for unknown reasons, so I'm not interested in enhancing the current implementation. wiki updated accordingly.
Having "finished" this earlier than expected, I'm starting to prepare the main commit now.

**Comment by frostworx** [comment]
landed: https://github.com/frostworx/steamtinkerlaunch/commit/eda1929798b4d61eb7580c4fb3f592f81bd16da9

**Comment by frostworx** [comment]
# discord Version
The newest SpecialK version can only be found on the SpecialK discord channel and therefore needs to be installed manually
to `~/.config/stl/downloads/specialk/discord/SpecialK.7z` when using `discord`
This version does work, as it has a `UsingWINE` configuration option, which disables all non-working functions automatically.

**Comment by frostworx** [comment]
I think the best implementation would be to let `old` as default _(because automatic download is possible, as that version kind of works)_, let `test` and `stable` as _(currently broken)_ options for testing/trying _(and change default to one of them as soon as they work)_ and use `discord` automatically, when the user downloaded it manually.
Updated the [wiki]([SpecialK](https://github.com/frostworx/steamtinkerlaunch/wiki/SpecialK)) accordingly.

I'll add an auto-enable for the `UsingWINE` option if possible.

**Comment by frostworx** [comment]
added support for the discord version including auto-enabling `UsingWine` in https://github.com/frostworx/steamtinkerlaunch/commit/cbfb2380595f05e42db172c6be816256b8cc3508

**Comment by frostworx** [comment]
_from the wiki:_

# using [ReShade](https://github.com/frostworx/steamtinkerlaunch/wiki/ReShade) and [SpecialK](https://github.com/frostworx/steamtinkerlaunch/wiki/SpecialK) together
SpecialK supports loading ReShade as a plugin, but unfortunately this leads to a crash _(currently)_.
The functionality is already implemented _(apart from auto-adding ReShade to the SpecialK ini if enabled)_, but commented out because it crashes.
Edit `function setShadDestDir`, `function useReshade` and `function prepareSpecialKReshade` if you want to play with it.

**Comment by frostworx** [comment]
*works for me*
