### ISSUE TITLE
Fatal: value too great for base

### ISSUE THREAD

**Issue by bekopharm** [sonic2kk/steamtinkerlaunch#258]
SteamTinkerLaunch fails to start:

> /usr/bin/stl: line 6062: 1200_60: value too great for base (error token is "1200_60")

That's function `setInitWinXY` and the error happens in calculating with the "detected" height of `1200_60`:

```
function setInitWinXY {
        SCREENRES="$(getScreenRes)"

        SCRW="${SCREENRES%x*}"
        SCRH="${SCREENRES#*x}"

        WINX=$(( SCRW * 3 / 4))
        WINY=$(( SCRH * 3 / 4))
        writelog "INFO" "${FUNCNAME[0]} - Using '${WINX}x${WINY}' as default resolution for all windows without a configured resolution"
}
```

I guess it doesn't like my VIRTUAL display naming (used to simulate a big display that games can see for fullscreen over multiple monitors):

```
xrandr | grep -A1 VIRTUAL
VIRTUAL1 connected primary 5760x1200+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   5760x1200_60.00  60.00* 
VIRTUAL2 disconnected (normal left inverted right x axis y axis)
  5760x1200_60.00 (0x775) 579.470MHz -HSync +VSync
```

It's created like this (and basically the default naming when using a tool like `gtf` or `cvt`):

> xrandr --newmode "5760x1200_60.00"  579.47  5760 6144 6768 7776  1200 1201 1204 1242  -HSync +Vsync

There is (to my knowledge) no rule for naming a mode so maybe it's better to parse width and height from the `--verbose` output of `xrandr` in function `getScreenRes` and not assume that the mode naming is always a valid resolution.

**Comment by frostworx** [comment]
Thanks for reporting - should be trivial to fix.
I'm currently on vacation, so won't fix it too soon.
PR welcome of course.

**Comment by frostworx** [comment]
Please test if
`SCRH="$(sed "s:[^0-9.].*::" <<< "${SCREENRES#*x}")"`
works for you  [here](https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L6059)

**Comment by frostworx** [comment]
And please also test
```
	SCRH1="${SCREENRES#*x}"
	SCRH="${SCRH1%%[^0-9.]*}"
```
instead _(which would be nicer)_.

**Comment by bekopharm** [comment]
Both work, the one-liner better.
The two-liner raises a much bigger menu with lots of empty space.

It does fix this very issue (I did simply hardcode it after reporting this because all my screens have the same height).

It will still fail if someone names the mode without any dimensions to parse tho, no? :confused: 

Thanks for coming back to this so fast - didn't expect this due to the VC announcement :+1:

**Comment by frostworx** [comment]
thanks for testing!
Interesting regarding the bigger menu - need to investigate this, as it might explain bigger menus in other functions as well.
Sure, the function might not be bullet-proof, but very likely it works for 99% of all systems.
And improving PRs are welcome always :)
I'll close here, and reopen another issue for me, so I won't forget the "bigger menus"

**Comment by frostworx** [comment]
Sorry, I haven't read your previous comment carefully enough _(and probably would have missed it completely, if shellcheck wouldn't have complained about above one-liner solution :))_
You're right, modes without the resolution in its name would fail in the current state.
I already rewrote the whole getScreenRes _(offline)_ which no longer depending on the mode names.
Will be pushed when #264 & #265 are ready for an initial commit.
