### ISSUE TITLE
Annoying bugs

### ISSUE THREAD

**Issue by maplepy** [sonic2kk/steamtinkerlaunch#261]
So basically, I changed some default settings to my liking for stl in the "DEFAULT" section. But whenever I'm trying to launch a game, it doesn't launch because of that "Custom Command" being empty or being linked to another game while it has to be the path to the game. I don't understand why I have to set the path for each game manually and if there is a way of resetting the settings to default to avoid this annoying bug?
![image](https://user-images.githubusercontent.com/28269333/126053414-851a1505-9ba5-4fd1-add9-09da7e114f70.png)

Another annoying bug is having the "Game crashed menu" popping up when the game launched just fine (it happens on every game even though they don't crash and launch perfectly), it might be linked to the first issue I was talking in this post but I'm not sure on how I could resolve it either. 

Finally, is having the default value not change any _non set_ value for a specific game config normal ? Or should I change it manually on every game even though I want it to be changed by default and applied to every game where I haven't defined that particular value yet

Thank you

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/issues/93
