### ISSUE TITLE
Add arguments for user start and stop command.

### ISSUE THREAD

**Issue by rathel** [sonic2kk/steamtinkerlaunch#267]
Hello, I just love this project. I would like to be able to add arguments to the user start and stop commands. I have create a simple backup script I'm using for a game that doesn't have cloud saves that backs up the saves to a shared folder when the game closes and a separate script to restore the files on start. It would be nice to combine the two and use one script with arguments.

**Comment by frostworx** [comment]
Hi there.
Thanks for the friendly feature request!
I might have not understood you correct, but just to be sure:
You've seen that stl has direct [Backup-Support](https://github.com/frostworx/steamtinkerlaunch/wiki/Backup-Support).
If that is not what you wanted: The [Start-Stop-Scripts](https://github.com/frostworx/steamtinkerlaunch/wiki/Start-Stop-Scripts) currently accept
* SteamAppID as argument1
* the absolute path to the game exe as argument2
* and the Wineprefix of the game as argument 3

So you just want to have an other argument 4 as boolean?
Or maybe even add further customizable(?) args (maybe using a separate per-game start-stop config where "to be executed functions" can be defined).

**Comment by rathel** [comment]
Thanks for the reply, I was aware of the direct backup-support, but I wasn't sure it would backup saves in a non-steam directory, the game in question saves are in ~/.local/share/Neverwinter Nights/saves. So I'm just using 2 simple scripts to back up and restore that folder on Game Start and Stop. Hope that clarifies.

**Comment by frostworx** [comment]
Ic, so you want to combine your two separate scripts using the [Start-Stop-Scripts](https://github.com/frostworx/steamtinkerlaunch/wiki/Start-Stop-Scripts) into one script, where stl provides f.e. a 4th argument `'1'` for the start and `'0'` for the stop script, so the correct function can be executed. Shouldn't be a problem, and I see no reason why it shouldn't be added.

**Comment by frostworx** [comment]
I'll add `1` for the start script and `0` for the stop script as **argument 1**, so the existing args will be appended.
Will be pushed with the next commit _(when #264 and #265 are ready)_

**Comment by frostworx** [comment]
Added in release [v6.13](https://github.com/frostworx/steamtinkerlaunch/releases/tag/v6.13)
Feel free to reopen if something went wrong :)
