### ISSUE TITLE
Steam game launch process seems to have changed recently

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#269]
Looks like Steam is about to change its way to launch games on linux,
as recently _(no idea when exactly, but can't be long)_ a new
command was added to the launch process _(maybe only in steam-beta?)_

Until now the commands "under the hood" were

`run $HOME/.local/share/Steam/legacycompat/iscriptevaluator.exe legacycompat\evaluatorscript_435400.vdf`
_(launching the [Steam-First-Time-Setup](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-First-Time-Setup))_

and

`waitforexitandrun /$PATHTO/steamapps/common/HiddenFolks/Hidden Folks.exe`
_(command line options for the game launch)_

recently the new command 

`$HOME/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=435400 -- $HOME/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/stl waitforexitandrun /$PATHTO/steamapps/common/HiddenFolks/Hidden Folks.exe`

was added between the previous command. There doesn't seem to be much info about the reaper process, but skipping it is no option, as it seems to be required _(now)_ to launch the game.

_(Hopefully the only)_ side effect is that the stl [Wait Requester](https://github.com/frostworx/steamtinkerlaunch/wiki/Wait-Requester) is opening twice currently, which needs to be fixed of course.
I also noticed that "manually" launching the [Steam-First-Time-Setup](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-First-Time-Setup) started to segfault newer protons recently, which might be related(?).
Haven't checked yet if any env changed/was added.

If you have any info about this please feel free to share.
~~_(I hope this is no sign, that possible tinker doors are about to be shut down before the big steam deck launch)_~~

**Comment by frostworx** [comment]
_the comment here was not meant for this issue :)_

**Comment by timvisee** [comment]
This (reaper) may be used to clean up parentless threads, which would otherwise leak. I've heard the term 'reaper' before for such thing.

https://en.wikipedia.org/wiki/Wait_(system_call)#Zombies_and_orphans

>  (...) If a child is not waited on by its parent, it continues to consume this resource indefinitely, and thus is a resource leak. Such situations are typically handled with a special "reaper" process[citation needed] that locates zombies and retrieves their exit status, allowing the operating system to then deallocate their resources.

**Comment by frostworx** [comment]
Thanks, @timvisee! This is indeed its main purpose. By simply letting it execute silently I guess this issue is solved for now.
