### ISSUE TITLE
Move 'DEFAULT' button elsewhere?

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#276]
It is not really often necessary to change something in the game config template,
therefore, I wonder if it would be a good idea to move it elsewhere.
Maybe as Tray Icon menu entry or simply as command line option.
Any thoughts?

**Comment by Faalagorn** [comment]
> It is not really often necessary to change something in the game config template,
> therefore, I wonder if it would be a good idea to move it elsewhere.
> Maybe as Tray Icon menu entry or simply as command line option.
> Any thoughts?

I'd have to see, plus it's specific to one WM, but keep in mind that tray doesn't work under sway currently https://github.com/swaywm/sway/issues/3799

**Comment by frostworx** [comment]
Thanks for the info regarding missing sway tray features.
I'm not totally sure what you mean with "I'd have to see, plus it's specific to one WM" though, but I assume you don't like the command line option, right? _(I don't like it as well :))_

The bottom buttons in a yad window can't be scaled down, so the minimal window width is at least the sum of the used buttons.
Using the DEFAULT button as [Extra-Button](https://github.com/frostworx/steamtinkerlaunch/wiki/Extra-Button) would improve this a bit. On the other hand, it probably is not worth the extra work.

**Comment by Faalagorn** [comment]
> Thanks for the info regarding missing sway tray features.
> I'm not totally sure what you mean with "I'd have to see, plus it's specific to one WM" though, but I assume you don't like the command line option, right? _(I don't like it as well :))_

I mean, I'd have to see how it looks currently ;)

**Comment by frostworx** [comment]
> I mean, I'd have to see how it looks currently ;)

I haven't changed anything yet, so the look hasn't changed from that you already know. :)
Not sure yet, but I tend to cancel the idea anyway, so no worries :)

**Comment by frostworx** [comment]
*Canceling the idea* :)
