### ISSUE TITLE
SteamLinuxRuntime

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#281]
It is still true *(for now)* that there are no [Steam Linux Runtime](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Linux-Runtime) parameters in the Steam Game launch,
when using stl (anything) as Compatibility Tool, which allows an easy proton override from inside stl.

While rewriting several parts in the code for properly fixing [this bug ](https://github.com/frostworx/steamtinkerlaunch/issues/279) *(which started since steam changed its [launch processes](https://github.com/frostworx/steamtinkerlaunch/issues/269))*
and [iscriptevaluator.exe syntax](https://github.com/frostworx/steamtinkerlaunch/issues/270)
I recognized, that it is not possible *(anymore)* to disable the SLR completely when using stl as Steam Launch Option *(stl %command%)* *like before, because the SLR is immediately hooked in on start. Therefore, overriding the proton version coming from steam isn't possible with *(stl %command%)* so easily.
The only chance would be to manipulate theSteamLinuxRuntime by

- removing the SteamLinuxRuntime_soldier directory
- exit the `_v2-entry-point` at the beginning
- replacing the `--verb=run` parameter coming via command line with some nonsense *(untested)*
- something else
-
I'm not sure if it is a good idea to automatically mess around with this, so I consider removing *(or at least disabling for now)* the
`OVERRIDEPROTON` boolean completely, which would have only had an effect with *(stl %command%)*, because it is used with stl as Compatibility Tool anyway (as there is no proton in the command line and therefore one needs to be provided by stl  anyway). So the proton version configured as Compatibility Tool inside steam would be always automatically used when using 
*(stl %command%)* with a windows game.

Any thoughts?

**Comment by frostworx** [comment]
~~I just decided to wait with further development until the major ongoing switch *(for Steam Deck)* has been released.~~
No, still working on it, but no new major features for now.
Among other reasons, there are several signs under the hood that future tweaking might become more complicated,
and I don't want to beat a dead horse. Doesn't make much sense to play Don Quijote until the "launch system" is public and still tweakable.

**Comment by rodrigo21** [comment]
I've never used the Proton override option with `stl %command%` , so for me it can removed without any problem.
I prefer to set the proton version on Steam itself so I can see what the game is using.

**Comment by u83rmensch** [comment]
I use proton override with the stl %command% option, its the only real easy way with a UI to use custom proton. 

I cant even get the stl menu to open launching games anymore, just skips right over it and opens the game directly. I had an issue downloading proton custom version earlier.. I cant really tell if my problems are due to this bug, or some other bigger issues with my stl install. 

can I force launch the menu from cli some how to see if it even works?

**Comment by Termuellinator** [comment]
Personally i never used that option, so for me it would be fine to limit it to the compatibility-tool-way.

@u83rmensch shameless self promoting: i wrote a small tool to download custom proton from GE and TKG: https://github.com/Termuellinator/Proton-Community-Updater
maybe thats an acceptable replacement for this functionality :)

**Comment by frostworx** [comment]
`stl %command%` is not required to use a custom proton version, using stl as compatibility tool works just fine, so it must be a local user problem. Please check your logs and report separately, @u83rmensch
Downloading GE and TKG is [directly implemented](https://github.com/frostworx/steamtinkerlaunch/wiki/Download-Custom-Proton) in stl and still works just fine, but if someone just wants a slim downloader I'm sure your Proton-Community-Updater is the better choice, @Termuellinator

Generally I hope I do not have to remove **any** functions because of "upstream" changes.

**Comment by frostworx** [comment]
It is not my intention to conflict with "upstream" and apparently I do not waste any time on trying to.
So I will remove the option to override the proton version when using `stl %command%`, as this is the only logical solution.
Also it is a nice (and the only) option to use stl, but still choose the proton version from the steam-side without any extra configuration. I even think that several other functions can be simplified this way.

**Comment by frostworx** [comment]
Major rewrite of checking the startmode entered with [this commit](https://github.com/frostworx/steamtinkerlaunch/commit/0b4a12bc912bbbb0a1173e6f6f9db06d3be0877a).
I think it works fine, but please test and report back.

**Comment by rodrigo21** [comment]
I think [proton_tkg](https://github.com/Frogging-Family/wine-tkg-git) also forks its command into background. I'm getting a notification that the game have finished before it even starts, but the game runs normally.
Proton GE is based on proton_tkg, so maybe add the same change when running proton_tkg.

**Comment by frostworx** [comment]
Thanks, @rodrigo21. Haven't received an email from github, else I'd have replied earlier _(they had major outtakes yesterday)_
I'll check this and fix it _(if possible)_.

**Comment by frostworx** [comment]
Should be fixed with above commit. Thanks again for reporting @rodrigo21!

**Comment by rodrigo21** [comment]
It's working. Thanks.

**Comment by frostworx** [comment]
Ty, @rodrigo21 

The rewrite probably requires some more tweaks, but generally it seems stable enough to close this for now

**Comment by rodrigo21** [comment]
Sorry to bother again but I think this only work with Proton-6.13-GE-1 or newer. Just tested with Proton-6.12-GE-1 and the game didn't start.

**Comment by frostworx** [comment]
np, but please open a new issue with logs. Also make sure to re-test with a clean or without a compatdata dir, maybe it simply got corrupted

**Comment by frostworx** [comment]
Just tried with switching from last tgk to 6.14-GE and then to 6.12-GE and the game always started.
I even had the new [Fix Symlink](https://github.com/frostworx/steamtinkerlaunch/wiki/Symlinks#fix-symlinks) function enabled _(which needs a few seconds when there's much to do)_, but everything worked fine.

**Comment by rodrigo21** [comment]
Sorry, it's working fine with Proton-6.12-GE-1. It's just seems the game is messing with me.

Thank you.

**Comment by frostworx** [comment]
np, thanks for the feedback. which game? maybe I have it and can try to help :)

**Comment by rodrigo21** [comment]
I don't think you have, but the game is [Kinkoi: Golden Loveriche](https://store.steampowered.com/app/1277940/Kinkoi_Golden_Loveriche/).

The game runs fine. The problem I'm having now is that when I use stl a video doesn't run and it crashes the game, without stl the video plays normally.
This is a Unity visual novel that uses mfplat for the videos, so it needs Proton-GE or Proton-tkg which have the mfplat patches. And the videos only play with wine 6.12 or older I think.

So don't worry about it, videos are the biggest problem with wine that I have. Thanks again.

**Comment by frostworx** [comment]
Sure I don't have, but I can be nice sometimes :)
I don't have the game though.
There is technically nothing though in stl, which would prevent the videos from working.
Are you 100% sure it is stl related? Is it reproducible with the game demo?

**Comment by rodrigo21** [comment]
Here's what I found:
- If I use stl as a Compatibility Tool the game runs and the video doesn't play, with USEGAMEMODERUN enable or not.
- If I use `stl %command%` with USEGAMEMODERUN **disable** the game runs and the video plays.
- If I use `stl %command%` with USEGAMEMODERUN **enabled** the game doesn't run.
- If I use `gamemoderun stl %command%` the game runs and the video plays.

Here the gamecfg: [1277940.conf.txt](https://github.com/frostworx/steamtinkerlaunch/files/6977607/1277940.conf.txt)

**Comment by frostworx** [comment]
Interesting,
please provide stl logs for every combination in a new issue.
Might also help to set STARTDEBUG (line 54) to 1 and provide `"/tmp/stl-startmode-DEBUG-XXXXXXXXX"`
for every combination as well
