### ISSUE TITLE
Tool - Dependency Walker

### ISSUE THREAD

**Issue by UltraBlackLinux** [sonic2kk/steamtinkerlaunch#283]
Hey there,
I thought, that [Dependency Walker](https://www.dependencywalker.com/) could be a pretty good tool, to figure out, what dlls a program is missing - I just somewhat  stumbled upon it while trying to solve my other stl dll problems.
Is this any good?
Thanks!

**Comment by frostworx** [comment]
Haven't touched dependency walker for years, but it was a nice tool indeed.
So if you want to write a PR, I'd merge it for sure.

**Comment by UltraBlackLinux** [comment]
> Haven't touched dependency walker for years, but it was a nice tool indeed.
> So if you want to write a PR, I'd merge it for sure.

Sadly I have close to no shell experience at all, so probably not, even if it's just copying the vortex installer and changing the url :/

**Comment by frostworx** [comment]
...

**Comment by frostworx** [comment]
"even if it's just copying the vortex installer and changing the url"
I just gave it a quick try:
-the [project page](https://www.dependencywalker.com/) is not _(easily)_ parsable, and there is no `latest` download url, so it would require manual version bumps.
- `depends.exe` segfaults on a test run using `Proton-6.14-GE-2`. Haven't debugged this and won't

**Comment by frostworx** [comment]
@UltraBlackLinux, just have seen your reply [here](https://github.com/Matoking/protontricks/issues/113) 
and regret that I even tried to help you in here, [here](https://github.com/frostworx/steamtinkerlaunch/issues/282) and [here](https://github.com/frostworx/steamtinkerlaunch/issues/278)

If a user is unwilling to help, fine, but I can dispense with those who additionally backstab the project they asked for help.

edit: fun fact: the reason for why I found the protontricks issue, is because I was curious if you did not reply here, because you were not active on github generally or because you were really so impolite... :+1:

**Comment by UltraBlackLinux** [comment]
@frostworx 

Oh was I impolite? - I did not mean to be; I am truly sorry.
I also completely forgot this issue after finding the solution/problem over at the protontricks repo and also got no more notifications (Maybe since it's closed?).
There's nothing more, that I can say, as it would sound rather stupid.

**Comment by UltraBlackLinux** [comment]
> "even if it's just copying the vortex installer and changing the url"
> I just gave it a quick try:
> -the [project page](https://www.dependencywalker.com/) is not _(easily)_ parsable, and there is no `latest` download url, so it would require manual version bumps.
> 
>     * `depends.exe` segfaults on a test run using `Proton-6.14-GE-2`. Haven't debugged this and won't

I just gave it another try, and this time I found an ["updated" github version](https://github.com/lucasg/Dependencies/), or rather fork

**Comment by frostworx** [comment]
@UltraBlackLinux 
I believe you that you didn't mean it like that. Maybe I had a bad day and overreacted, so I'm sorry as well.

**Comment by frostworx** [comment]
> I just gave it another try, and this time I found an ["updated" github version](https://github.com/lucasg/Dependencies/), or rather fork

Ok, thx. I'll give it a shot when I find the time.

**Comment by frostworx** [comment]
just added with above commit. works for me, but please test.
[little wiki entry](https://github.com/frostworx/steamtinkerlaunch/wiki/Dependencies-Program)
