### ISSUE TITLE
How can I disable notification ?

### ISSUE THREAD

**Issue by MGMehdi** [sonic2kk/steamtinkerlaunch#284]
Hello, 

each time I play, quit I've got a lot of notifications. How can I disable this ? I'm on Gnome40

**Comment by frostworx** [comment]
You can disable all notifications in the GLOBAL menu _(uncheck "Enable notifier" under GUI options)_
See also here:
https://github.com/frostworx/steamtinkerlaunch/wiki/Notifier

**Comment by frostworx** [comment]
ping

**Comment by MGMehdi** [comment]
Thanks !

In the meantime I can't run game with STL. It no longer displays the available proton versions

![image](https://user-images.githubusercontent.com/48625769/128603147-1730be1b-4422-415e-966f-2993328bcdbe.png)

**Comment by frostworx** [comment]
Please read this: https://github.com/frostworx/steamtinkerlaunch/issues/93
Also: The list of available proton versions is usually updated on the first launch (and in some other situations)
and can be found in /dev/shm/stl/
That directory is used by stl generally for temporary files. Whenever it is removed, its files are re-generated on the next stl start.
Closing here anyway as this is a different "issue"
