### ISSUE TITLE
STL doesn't find proton

### ISSUE THREAD

**Issue by MGMehdi** [sonic2kk/steamtinkerlaunch#287]
Hello, 

I don't know why but STL doesn't find proton. I tried to reinstall STL `stl compat del`, delete all remnant files/folder `find / -name stl` for a "fresh install" but nothing work

![image](https://user-images.githubusercontent.com/48625769/128638586-cb88e723-4f21-48cf-ba0c-51be9d4d25d7.png)

What can I do ?

**Comment by frostworx** [comment]
Hi, looks like you totally ignored my previous answer here:
https://github.com/frostworx/steamtinkerlaunch/issues/284#issuecomment-894701002
Also, make sure to use stl as steam compatibility tool and not as steam launch option.

**Comment by MGMehdi** [comment]
Hi

I added stl as Steam Compatibility Tool and set it as default launcher in steam settings

> The list of available proton versions is usually updated on the first launch (and in some other situations)
and can be found in /dev/shm/stl/

Sorry but I don't know what I need to do with this information

> Whenever it is removed, its files are re-generated on the next stl start

When I run a game thought Steam it doesn't seem to work if it doesn't list any proton version

Here some logs I found hope it can help
[stl-iscriptevaluator-294100.log](https://github.com/frostworx/steamtinkerlaunch/files/6951152/stl-iscriptevaluator-294100.log)
[lastrun.txt](https://github.com/frostworx/steamtinkerlaunch/files/6951143/lastrun.txt)
[294100.log](https://github.com/frostworx/steamtinkerlaunch/files/6951146/294100.log)

**Comment by frostworx** [comment]
Hi,
ok good, the log looks sane so far.

Which proton versions _(including custom ones)_ do you have installed in which directory?
Looks like your only steamapps directory is the default one (`/home/mehdi/.steam/root/steamapps/common/`) - is this correct and are there any proton versions installed? _(stl doesn't install regular proton versions for you, you need to install them directly from steam)_

Do you have any custom proton version installed in your compatibility tool?
You could also install the latest custom proton version `(GE)` using 
`stl dcp l`
which should show up in the list of available proton version then.

Generally, please make sure that the directories stl searches for proton versions in the function `getAvailableProtonVersions`
do exist on your system, maybe you have a distro (which btw?) which uses different paths, but I hope stl already covers all possible steam path configurations.

**Comment by MGMehdi** [comment]
Hi

the default directory for steamapps is `/home/mehdi/Games/SteamLibrary` and I verified all version of proton that steam have downloaded are here

I don't use custom proton

I'm on Arch (newbie). Can I tell stl to check elsewhere ?

**Comment by frostworx** [comment]
Hi,
heh, this is the first time I heard of `/home/mehdi/Games/SteamLibrary` _(I'm on Arch as well)_.
Did you configure it yourself somewhere?
Your log shows though that the regular default directory `DEFSTEAMAPPSCOMMON`
does exist as well: '/home/mehdi/.steam/root/steamapps/common'
What is in there?

**Comment by frostworx** [comment]
A fresh steam installation with a new user doesn't create or use that directory as well, so I assume this is a handmade problem and not stl related.

**Comment by frostworx** [comment]
Ah, I guess you actually really created the directory yourself, right?
I just added it as well and it indeed does not show up anymore in `~/.local/share/Steam/config/config.vdf`
and therefore can't be found.
Steam stores the paths in a separate `libraryfolders.vdf` "now".
This needs to be added to stl _(probably no big deal, but I can't tell when I find the time)_
What you can do until then is move (using steam) your installed proton versions into the default steam library path.

Good find and thanks for reporting!

**Comment by frostworx** [comment]
Hi again,
Should be fixed with [this commit](https://github.com/frostworx/steamtinkerlaunch/commit/c40f02534acd902ce83e96534d35d18b7b845ee7)
Please test if it works for you.

**Comment by MGMehdi** [comment]
Hi
yes I changed the default path for my games (Games folder is on another drive)
Sorry but how can I test it ?

**Comment by frostworx** [comment]
Hi,
If nothing changed, the default steam library path is fix at `~/.local/share/Steam/steamapps/common/`
and can't be changed and removed, but this is not the problem.
Simply replace your installed stl file _(very likely `/usr/bin/stl`)_ with the one from current master.
Alternatively use the `steamtinkerlaunch-git` package from AUR instead of the stable one.

**Comment by MGMehdi** [comment]
Hi
Like before I've removed stl from steam,  uninstalled the stable stl, delete all residual files/folder and reinstall `steamtinkerlaunch-git` 
Everything work fine know, it detect all proton version !
![image](https://user-images.githubusercontent.com/48625769/128675309-6009c05d-c80c-40fa-8670-1bbd19c60ff5.png)

**Comment by frostworx** [comment]
n1
