### ISSUE TITLE
Depressurizer support?

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#293]
Never used it because I never used Windows, but [Depressurizer](https://github.com/Depressurizer/Depressurizer) seems to be a nice tool.
Mono support was [once considered, but cancelled](https://github.com/Depressurizer/Depressurizer/issues/14) _(, still doesn't magically work - just tried it)_,
but a **very** quick test revealed, that the exe opens with using dotnet from` Steamworks Shared/_CommonRedist/DotNet/4.8`
so no fully fledged, bloated and wine(tricks) problematic dotnet installation is required at least.
Assuming the whole program works _(really only checked if the gui opens)_ this would open the possibility to use the program in a separate wineprefix _(similar like in the vortex solution, only better because vortex requires a full dotnet install)_.

**Comment by frostworx** [comment]
from the WIP wiki:

# [Depressurizer](https://github.com/frostworx/steamtinkerlaunch/wiki/Depressurizer)

Depressurizer is a windows "Steam library categorizing tool" *(see [Project Page](https://github.com/Depressurizer/Depressurizer) for details)*

**stl** automates the whole *(download/install/configuration/start)* processes
required to use the program under linux via [Proton](https://github.com/frostworx/steamtinkerlaunch/wiki/Proton)/[Wine](https://github.com/frostworx/steamtinkerlaunch/wiki/Wine)
with following features/options:

- auto-download the latest [release](https://github.com/Depressurizer/Depressurizer/releases/latest) if not found locally or if auto-update *(`DPRSPAUTOUP`)* is enabled in the [Global Menu](https://github.com/frostworx/steamtinkerlaunch/wiki/Global-Menu)
- the newest exe version found in the download dir *( `~/.config/stl/downloads/depressurizer/`)* is always used automatically
- configurable *([Global Menu](https://github.com/frostworx/steamtinkerlaunch/wiki/Global-Menu))* own [Compatdata](https://github.com/frostworx/steamtinkerlaunch/wiki/Compatdata) *(default in `~/.config/stl/depressurizer`)*
- automatic installation of dotnet 4.8 via [Steam First Time Setup packages](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-First-Time-Setup) using an own *(bundled)* `iscriptevaluator` set
- individually configurable [Proton Version](https://github.com/frostworx/steamtinkerlaunch/wiki/Proton-Versions) in the [Global Menu](https://github.com/frostworx/steamtinkerlaunch/wiki/Global-Menu)
- option to symlink all required vdfs from the linux steam installation into the Depressurizer [Compatdata](https://github.com/frostworx/steamtinkerlaunch/wiki/Compatdata) directory
  *(default is working with copies, in which case the original vdf files remain untouched - use symlinks at your own risk!)*
- can be started directly from [Command Line](https://github.com/frostworx/steamtinkerlaunch/wiki/Command-Line) or from [Tray-Icon](https://github.com/frostworx/steamtinkerlaunch/wiki/Tray-Icon)

**Comment by Faalagorn** [comment]
I used to use Depressurizer once back in my WIndows days, not sure I need it now, but good it's merged. :)

**Comment by frostworx** [comment]
:)
