### ISSUE TITLE
Game crashes with stl 6.15 under Proton GE

### ISSUE THREAD

**Issue by maplepy** [sonic2kk/steamtinkerlaunch#296]
Whenever I launch my game (Starbase) with Proton GE, the game crashes
Using stl 6.15 and here's the log file:
[454120.log](https://github.com/frostworx/steamtinkerlaunch/files/7008135/454120.log)

It was working fine before updating to stl 6.15

**Comment by frostworx** [comment]
this is not stl related and you don't get any support from me anymore

https://github.com/frostworx/steamtinkerlaunch/issues/294#issuecomment-900445507

**Comment by maplepy** [comment]
> this is not stl related

Well kinda is since it is working fine without stl but okay I guess?
