### ISSUE TITLE
AMD FSR - Magpie

### ISSUE THREAD

**Issue by UltraBlackLinux** [sonic2kk/steamtinkerlaunch#297]
Hey there,
I just found [this tool](https://github.com/Blinue/Magpie), that allows you to patch every game to work with FidelityFX - As it's all in chinese, there is [a video tutorial](https://www.youtube.com/watch?v=xxDexYt9BUU) and even a [patched english version](https://github.com/7Brandyn7/Magpie), though as stated by 7Brandyn7, he will probably not update it anymore, since ".. Blinue is adding a Native English next patch"
As I am still not willing to learn bash (I am currently having C++ headache), I will just keep this as a suggestion (like #283).
Will this work? (I am gonna test this out myself, to see if it works. I have a few games that are currently dying to low performance.)
Thanks!

**Comment by UltraBlackLinux** [comment]
Oh big brain, I think Wine FSR already supports everything 😅

**Comment by frostworx** [comment]
Thanks for the suggestion anyway! Always good to get to know possibly useful tools to build in :)
Just in case you missed it, FSR support us already implemented in slr. Both for [regular](https://github.com/frostworx/steamtinkerlaunch/wiki/Wine-FSR) and for [openvr](https://github.com/frostworx/steamtinkerlaunch/wiki/OpenVR-FSR) games.
It wasn't much work to add support for it, but a useful feature for sure anyway :)
