### ISSUE TITLE
Weird folder renaming

### ISSUE THREAD

**Issue by UltraBlackLinux** [sonic2kk/steamtinkerlaunch#298]
Hey there,
I am currently running into some weird issues, where the Applicaton Data and My Documents folders in the wineprefix get renamed to ...BACKUP - I don't get why.
This just started to happen out of nowhere and took me hours to figure out, and I still have no clue how to fix it.
Why is this?
Thanks!

**Comment by frostworx** [comment]
I assume this has something to do with most recent path changes in proton. not stl related

**Comment by UltraBlackLinux** [comment]
> I assume this has something to do with most recent path changes in proton. not stl related

Huh?
I have played proton games today, that worked fine. I tried this with Proton GE 6.15-2, and it worked once (after switching back and forth), and then broke again

**Comment by UltraBlackLinux** [comment]
Hmm, does actually seem to be related to proton in some way, or another.
This is still happening with vanilla proton experimental.
I wonder, when they are gonna fix it...

**Comment by UltraBlackLinux** [comment]
Okay better news; It's actually not broken with Proton Experimental, it just actually moved some folders around without breaking them.
Thank you for the assistance!

**Comment by frostworx** [comment]
Sure. Anyway, please test before opening an issue if it is stl related at all - would save me some time.
And editing the last comment instead appending a new answer, would be nice as well to keep my mail inbox happy.
Also don't forget to test the `dependencies` implementation for which you opened a feature request.

**Comment by frostworx** [comment]
👎
