### ISSUE TITLE
Custom command Delay 

### ISSUE THREAD

**Issue by UltraBlackLinux** [sonic2kk/steamtinkerlaunch#299]
Hey there,
I am currently trying to get BeamMP working with Proton, and I ran into a "problem": If I use "fork custom command", BeamMP can't find the game, as only the prelauncher is running at that moment.
I don't see any way to have it launch automatically, when the game is presumably running, apart from manually executing it via the wineconsole.
Did I overlook something? If not, then this is a suggestion.
Thanks!

**Comment by frostworx** [comment]
please read the comprehensive wiki before opening an issue.
this is clearly documented.

**Comment by UltraBlackLinux** [comment]
> please read the comprehensive wiki before opening an issue.
> this is clearly documented.

Sorry, but I couldn't find anything regarding that in the wiki

EDIT: Oh whoops, I completely overlooked the user scripts; I hope they can do, what I need

**Comment by frostworx** [comment]
🙄
