### ISSUE TITLE
vortex installation hangup through stl

### ISSUE THREAD

**Issue by ghost** [sonic2kk/steamtinkerlaunch#30]
Not sure if this is a you problem or a me problem. I am but a novice with linux, just enough knowledge to make it dangerous, not enough to completely understand what does what. 

Copied from what my protondb shows up. Steam came loaded on the version of manjaro i used (plasma kde)
OS: Manjaro Linux
KERNEL: 5.7.9-1-MANJARO
CPU: AMD FX-8350 Eight-Core
GPU: NVIDIA GeForce GTX 780 Ti
GPU DRIVER: NVIDIA 440.100
RAM: 32 GB

I initially started with trying to launch a game to install vortex as instructed after installing from the aur provided for archlinux. It hung up hard, couldn't quit the game from steam. so I attempted the command line installation of vortex. It hung up in the same place as I experience now after doing a complete computer wipe, fresh install of everything as I had thought perhaps my novice level modifications of games using proton, protontricks, winetricks and various other stuff might have had something to do with it.

additionally i updated to your current fixes that were not implemented in the aur for archlinux to see if that would fix it (it hadn't). rolled back my computer to the backup I had made after a fresh install and tried again. so I'm getting hung up in the exact same location with no idea what to do about it. Currently it's been sitting at the same spot for 2.5 hours. The following are the last lines posted to the terminal.
```

Setting Windows version to default
Executing /usr/bin/wine regedit /S C:\windows\Temp\set-winver.reg
Executing /usr/bin/wine64 regedit /S C:\windows\Temp\set-winver.reg
------------------------------------------------------
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/$USER/.config/stl/vortex/wineprefix terminate
------------------------------------------------------
```

**Comment by frostworx** [comment]
I had those hangs as well, and it should be in the readme for sure (probably in a week, won't be at home for some days).
That's what I meant with "mostly depends on dotnets mind of its own" in the readme.
The problem is this is completely randomly, it simply does what it wants and not just that what it should.
A `pkill -9 mscorsvw.exe` will kill the dotnet process and continue with the program, but when the installation wasn't finished yet Vortex won't work as well. I already split it into an extra function, so it doesn't block the other installations at least, but this doesn't help when dotnet loops forever.
The good thing is, that this only happens during the dotnet installation, once it is installed everything seems to work fine.
What you could try is re-start with a clean Vortex WINEPREFIX and start the installation from commandline.
`stl vortex install`
This won't fix the dotnet hangs, but at least you get more winetricks output and see if the installation properly finishes.
It might be a good idea to have at least the option to start the winetricks dotnet installation not unattended.

**Comment by ghost** [comment]
I did read through the readme for stl. It's how I gave up finally on trying to get Skyrim SE to work with mods that required skse. I had previously been using winetricks and lutris vortex, then protontricks and lutris vortex... I'm 6 days in completely quitting windoze after spending a month or so with it installed on my bigger ssd and never launching it. I was a power user for m$, even did some .NET programing back in the 2000s and the only thing I really miss has to be the timestamps on every line in the terminals.

So, updating... I used Timeshift to basically wipe my entire computer back to my last clean install of the OS with the little setting tweaks I do. From there I installed wine, wine mono, wine gecko and winetricks followed by stl from the package manager. after a reboot I went ahead and did the stl vortex install command.

It was about 99% the same result as previously attempted. This time I was able to adjust the window enough to be able to read the terminal output data to figure out where the issue was coming from and it's the same problem I was having previously with winetricks and protontricks. dotnet40 doesn't like to play nice. I had actually abandoned trying dotnet40 when getting games to work and would use dotnet452 instead. The question I guess is, could this install process be forced to replace dotnet40 with dotnet452 OR could there be a way to install it differently that would prevent this particular hangup with this particular dotnet. However the pkill command did let it finally push pass the hangup spot and didn't have any issues with any other bits of dotnet stuff.

Vortex does launch before the game now, however first time launch it warned about having run Vortex with admin permissions which is unnecessary and will make problems worse.

--------------------------Edit 17/8/2020
I have found that using "winetricks --gui" after installing wine, winetricks and zenity and going through the prompts allows a hassle free install of dotnet40 without the hangup issues. Going to play with this stuff more, but if stl could somehow pull the dotnet's from the default wineprefix during the creation process this whole dotnet problem could be solved just by installing dotnet40 then dotnet48 through the "winetricks --gui" command and then installing stl/vortex. That or something to that effect... I know protontricks gui feature has a game pfx selection so the solution just might be an altered winetricks that targets stl's prefix as default through the gui interface.

**Comment by ghost** [comment]
I love being stupid <3, with a friend's help I realized that a simple `WINETRICKS="/home/$USER/.config/stl/vortex/wineprefix" winetricks --gui` does the trick.

If you add this to the README, to install the dotnet 40, then dotnet 48 to the stl vortex wineprefix in this way they shouldn't have trouble with dotnets during vortex installation.

--- Full Instructions/Walkthrough for No Fuss Vortex Install ---
Note 1 -- Repairing dotnet40 install through the gui doesn't work on my end, it just never gets to the Finished button
Note 2 -- These commands do not like shortcuts so using ~/.config or $USER were out of the question on my end so $USER should be replaced with the actual user folder name.

1) Install wine, winetricks, steamtinkerlaunch and restart your computer
2) Run `WINEPREFIX=/home/$USER/.config/stl/vortex/wineprefix winetricks --gui` from terminal
3) Install dotnet40 from the gui (images attached)
4) Once dotnet40 gui installer prompts "Finished" it should prompt a restart, if it does click "Restart Later" and go to step 6.
5) If it did not, open a terminal and run `pkill -9 mscorsvw.exe`
6) Winetricks gui will pop back up and you can click cancel until it closes completely, where you can now restart your computer
7) Run `WINEPREFIX=/home/$USER/.config/stl/vortex/wineprefix winetricks --gui` from terminal
8) Install dotnet48 from the gui
9) Once dotnet48 gui installer prompts "Finished" it should prompt a restart, if it does click "Restart Later" and go to step 11.
10) If it did not, open a terminal and run `pkill -9 mscorsvw.exe`
11) Winetricks gui will pop back up and you can click cancel until it closes completely, where you can now restart your computer
12) Open a terminal and run `stl vortex install` and it will do everything it needs to without any issue

![winetricksGUI01](https://user-images.githubusercontent.com/69735733/90449739-e6356380-e09c-11ea-8be5-2521dc72f2ef.png)
![winetricksGUI02](https://user-images.githubusercontent.com/69735733/90449745-e9305400-e09c-11ea-88ce-580a98c4813f.png)
![winetricksGUI03](https://user-images.githubusercontent.com/69735733/90449751-eb92ae00-e09c-11ea-8701-6e1e5022b0dc.png)

**Comment by frostworx** [comment]
winetricks installs dotnet40 before dotnet48 anyway as dependency. The mscorsvw.exe hangs are not my bug, but (probably) a winetricks bug. As I split the dependency installation anyway, I could add dotnet40 into the first run though, maybe it helps to workaround the issue. There's not more I can do.
