### ISSUE TITLE
WINEDLLOVERRIDES are not set up

### ISSUE THREAD

**Issue by farmboy0** [sonic2kk/steamtinkerlaunch#302]
stl uses STLWINEDLLOVERRIDES in the game config.
But it doesnt seem to be copied to WINEDLLOVERRIDES.
It works if i copy the STLWINEDLLOVERRIDES line and rename the variable to WINEDLLOVERRIDES in the game config.

stl version is 6.15.
The game config was created with 6.15.

**Comment by frostworx** [comment]
Heh, good find...
Looks like
I should change the ';' to a ':' [here](https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L2697) :)

**Comment by frostworx** [comment]
Apparently I never used/tested the variable here. Thanks for reporting and please test the fix.

**Comment by frostworx** [comment]
got autoclosed via commit. reopened, until fix is confirmed

**Comment by farmboy0** [comment]
That commit shouldnt work, as you are not concatenating paths but WINEDLLOVERRIDES.
Those are concatenated with semicolon.

**Comment by farmboy0** [comment]
if you revert 1fe7b41 and remove the backslashes from that line instead, this fixes the bug. The same needs to be done in prepareLaunch

**Comment by frostworx** [comment]
no, the backslashes should be fine here. please elaborate on both the backslashes and on prepareLaunch.
Yes true, the semicolon was correct and did not require any change. I was busy with other things currently.
Feel free to PR.

**Comment by frostworx** [comment]
oh my, of course the backslashes are nonsense here. I should drink my coffee before reading anything...

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/commit/8fc2db7c40f655d960af8d6c405b5e6e46beb792
and now coffee...

**Comment by farmboy0** [comment]
You need to do the same in setNewProtVars and revert the semicolon change there.
