### ISSUE TITLE
Tried to use custom yad binary

### ISSUE THREAD

**Issue by henres** [sonic2kk/steamtinkerlaunch#308]
Hello everyone,

I tried to use `stl yad /opt/bin/yad` but I don't understand the meaning of this command.

Is it an option ? Like `stl vortex install yad /opt/bin/yad`.
Or is it a config like option to set it globally and don't need to be added after end ?

None works for me.

I still have two errors :
WARNING - 'XXX' not found!
WARNING - YAD Version '0' found, ... (don't know what is after ... )

Thanks in advance

**Comment by frostworx** [comment]
`stl yad <YAD>` _(as in [Custom-Yad](https://github.com/frostworx/steamtinkerlaunch/wiki/Custom-Yad))_
is supposed to set the path to an alternative yad binary, in case there's none installed on your system.
The WARNING you posted indicates though that you `/opt/bin/yad` wasn't used.
Might be simply a bug, as I mostly tested
`stl yad conty` and `stl yad ai`
You don't seem to be sure why you even used that command. Which version does your `/opt/bin/yad` binary have and is it executable on your system?

**Comment by frostworx** [comment]
Just tested with a yad binary in `/tmp/1/2/3/yad` and it is configured in `~/.config/stl/global.conf` as `YAD="/tmp/1/2/3/yad"`
as expected and is working correctly, so I guess your `/opt/bin/yad` binary isn't executable on your system.

**Comment by henres** [comment]
Ok, Thanks for the answer, I will try to get yad to work better :

For now, it works like this :
```
henres at solus-home in ~ 
$ yad --version

(yad:18734): GLib-GIO-ERROR **: 09:21:54.145: Settings schema 'yad.settings' is not installed
[1]    18734 trace trap (core dumped)  yad --version

henres at solus-home in ~ 
$ export XDG_DATA_DIRS=/opt/yad/share:$XDG_DATA_DIRS

henres at solus-home in ~ 
$ yad --version
10.1 (GTK+ 3.24.30)
```

**Comment by frostworx** [comment]
Thanks for testing.
Ok, so it looks like expanding your `XDG_DATA_DIRS` _(as you did)_ f.e. in `~/.bashrc` should be enough to get your yad working in stl.

**Comment by frostworx** [comment]
hm, ok...
*closing here*
