### ISSUE TITLE
Update broke vortex probably

### ISSUE THREAD

**Issue by ghost** [sonic2kk/steamtinkerlaunch#31]
Now that i got vortex installed correctly, there was a big old update just the other day it seems so launching of vortex pops up some fun errors with vortex.exe

attached several backtrace logs from this, however they're nearly identical, of course with the exception of the memory addresses, and shouldn't really need to be looked after the first one but as a novice, I'll just put them all in as a just in case bit.

[backtrace.txt](https://github.com/frostworx/steamtinkerlaunch/files/5087413/backtrace.txt)
[backtrace2.txt](https://github.com/frostworx/steamtinkerlaunch/files/5087414/backtrace2.txt)
[backtrace3.txt](https://github.com/frostworx/steamtinkerlaunch/files/5087415/backtrace3.txt)
[backtrace4.txt](https://github.com/frostworx/steamtinkerlaunch/files/5087416/backtrace4.txt)
[backtrace5.txt](https://github.com/frostworx/steamtinkerlaunch/files/5087417/backtrace5.txt)
[backtrace6.txt](https://github.com/frostworx/steamtinkerlaunch/files/5087418/backtrace6.txt)
[backtrace7.txt](https://github.com/frostworx/steamtinkerlaunch/files/5087419/backtrace7.txt)

I'm willing to accept  that perhaps my installation technique borked it as well, but I'm keen to helping as much as possible and am set up to timeshift back to clean installs to make quick of the testing of stuff. I'll admit this vortex stuff is exactly what drew me to stl in the first place because I was having issues with lutris' version of it. On a last remark, I was able to update my aur install of stl with the two updated files not included in the currently available aur, if that makes any difference. If there's anything I can do to help

**Comment by frostworx** [comment]
Sorry, there's nothing I can do from my side to prevent Vortex from segfaulting under wine.
You could re-try with a fresh WINEPREFIX, if that doesn't work it might be a worth to open a bug on winehq.
