### ISSUE TITLE
I can't do anything despite folders being set up correctly

### ISSUE THREAD

**Issue by viceebun** [sonic2kk/steamtinkerlaunch#311]
gawk: fatal: cannot open file `/home/*/.steam/root/userdata/*
/home/*/.steam/root/userdata/*/7/remote/sharedconfig.vdf' for reading: No such file or directory
Sat 25 Sep 2021 02:04:10 AM EDT INFO - openGameLauncher - No desktop file found in '/dev/shm/stl/desktopfiles'
Sat 25 Sep 2021 02:04:10 AM EDT INFO - openGameLauncher - Found arument 'auto'. Automatically creating/downloading required data for all installed games found
gawk: fatal: cannot open file `/home/*/.steam/root/userdata/*
/home/*/.steam/root/userdata/*/7/remote/sharedconfig.vdf' for reading: No such file or directory
Sat 25 Sep 2021 02:04:12 AM EDT SKIP - GLgui - No games found in '/dev/shm/stl/desktopfiles/installed' or directory itself not found

**Comment by frostworx** [comment]
please elaborate

**Comment by viceebun** [comment]
So I've just installed it and I'm trying to run through the stl launcher auto but it seems that it's just pointing to the wrong directories or telling me they flat out don't exist despite clearly being there and I have no idea why, nothing on steam's end or stl's are working here

**Comment by frostworx** [comment]
Are you sure you want to use the tiny stl internal game launcher _(as described [here](https://github.com/frostworx/steamtinkerlaunch/wiki/Game-Launcher))_?
If so, please [add logs](https://github.com/frostworx/steamtinkerlaunch/issues/93)

**Comment by frostworx** [comment]
🙄
