### ISSUE TITLE
Wrong menu drawing

### ISSUE THREAD

**Issue by IDeathByte** [sonic2kk/steamtinkerlaunch#313]
Manjaro, Plasma 5.22.5
Wayland session
i has problems with settings menu draw when i chose ingame or global settings (maybe something else too)
like this 
stl locale settings doesn`t matter
![1](https://user-images.githubusercontent.com/41571062/135623178-ce3513ce-6c65-48b5-a898-b4de832c5581.png)

**Comment by frostworx** [comment]
which stl version is that? Can it be nailed down to be wayland related? Anything interesting in the logs?
If this is a wayland problem, then it is a yad problem.
I won't rewrite stl _(again)_ to be wayland compatible - already did so in the past, although I do not even use wayland.
Also likely that I won't make any major changes in stl anymore [soon](https://github.com/frostworx/steamtinkerlaunch/issues/309).

**Comment by IDeathByte** [comment]
hm. under x-session similar trouble

doesn't seem something interest in logs 

> `RUNPROTON="/home/deathbyte/.steam/root/compatibilitytools.d/proton_tkg_6.18.r3.gd8c1599a/proton"
> RUNWINE="/home/deathbyte/.steam/root/compatibilitytools.d/proton_tkg_6.18.r3.gd8c1599a/files/bin/wine"
> PROTONVERSION="Proton-tkg 6.18.r3.gd8c1599a"
> PREVAID="418370"
> PREVGAME="RESIDENT EVIL 7 biohazard"
> PREVEFD="/media/hdd_raid/Games/steam/steamapps/common/RESIDENT EVIL 7 biohazard"

> Пт 01 окт 2021 18:10:11 +05 INFO - Starting with a clean log
> Пт 01 окт 2021 18:10:11 +05 INFO - emptyVars - Emptied some original Variables as they slowdown several system calls when started from steam
> Пт 01 окт 2021 18:10:11 +05 INFO - createDefaultCfgs - START
> Пт 01 окт 2021 18:10:11 +05 INFO - loadLanguage - First load the default language to make sure all variables are filled
> Пт 01 окт 2021 18:10:11 +05 INFO - loadLangFile - Loading system wide /usr/share/stl/lang//english.txt
> Пт 01 окт 2021 18:10:11 +05 INFO - loadLanguage - Now load the language file 'russian'
> Пт 01 окт 2021 18:10:11 +05 INFO - loadLangFile - Loading system wide /usr/share/stl/lang/russian.txt
> Пт 01 окт 2021 18:10:11 +05 INFO - createDefaultCfgs - setSteamPaths:
> Пт 01 окт 2021 18:10:11 +05 INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/stl/steampaths.txt'
> Пт 01 окт 2021 18:10:11 +05 INFO - createDefaultCfgs - createProtonList:
> Пт 01 окт 2021 18:10:11 +05 INFO - createDefaultCfgs - createProtonList end
> Пт 01 окт 2021 18:10:11 +05 INFO - listAllSettingsEntries - Creating '/dev/shm/stl/setentries.txt'
> Пт 01 окт 2021 18:10:14 +05 INFO - createDefaultCfgs - STOP
> Пт 01 окт 2021 18:10:14 +05 INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/stl/ProtonCSV.txt' which was created during a previous run
> Пт 01 окт 2021 18:10:14 +05 INFO - initFirstProton - Initializing Proton
> Пт 01 окт 2021 18:10:14 +05 INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/deathbyte/.config/stl/default_template.conf' is 'proton-6.3-7'
> Пт 01 окт 2021 18:10:14 +05 INFO - getScreenRes - Found screen width '2560'
> Пт 01 окт 2021 18:10:14 +05 INFO - getScreenRes - Found screen height '1080'
> Пт 01 окт 2021 18:10:14 +05 INFO - setInitWinXY - Using '1920x810' as default resolution for all windows without a configured resolution
> Пт 01 окт 2021 18:10:14 +05 INFO - linkLog - Symlink '/home/deathbyte/.config/stl/logs/stl/title/RESIDENT EVIL 7 biohazard.log' already exists
> Пт 01 окт 2021 18:10:14 +05 START - ######### Game Launch: RESIDENT EVIL 7 biohazard (418370) #########
> Пт 01 окт 2021 18:10:14 +05 SKIP - writeDesktopFile - /home/deathbyte/.config/stl/games/desktop/418370.desktop already exists
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch - Game launch args '/media/hdd_raid/Games/steam/steamapps/common/RESIDENT EVIL 7 biohazard/re7.exe'
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch - Gamedir '/media/hdd_raid/Games/steam/steamapps/common/RESIDENT EVIL 7 biohazard'
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch - Proton wineprefix '/media/hdd_raid/Games/steam/steamapps/compatdata/418370/pfx'
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch -------------------
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch - CreateGameCfg:
> Пт 01 окт 2021 18:10:14 +05 SKIP - updateConfigFile - Config file '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' already at version 'v6.15.95'
> Пт 01 окт 2021 18:10:14 +05 INFO - linkGameCfg - Symlink '/home/deathbyte/.config/stl/gamecfgs/title/RESIDENT EVIL 7 biohazard.conf' already exists
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch - First LoadCfg: /home/deathbyte/.config/stl/gamecfgs/id/418370.conf
> Пт 01 окт 2021 18:10:14 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' START
> Пт 01 окт 2021 18:10:14 +05 INFO - loadCfg - Loading game config '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf'
> Пт 01 окт 2021 18:10:14 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' STOP
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch -  Initial Proton version from the game config: ''
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch - Initializing internal Proton Vars for '' using setNewProtVars
> Пт 01 окт 2021 18:10:14 +05 INFO - setNewProtVars - Setting new Proton Variables based on '/home/deathbyte/.steam/root/compatibilitytools.d/proton_tkg_6.18.r3.gd8c1599a/proton'
> Пт 01 окт 2021 18:10:14 +05 INFO - setNewProtVars - Continuing with RUNPROTON='/home/deathbyte/.steam/root/compatibilitytools.d/proton_tkg_6.18.r3.gd8c1599a/proton'
> Пт 01 окт 2021 18:10:14 +05 INFO - setRunWineServer - Initiated from 'setNewProtVars'
> Пт 01 окт 2021 18:10:14 +05 INFO - setRunWineServer - Entering checkProtonBump
> Пт 01 окт 2021 18:10:14 +05 SKIP - checkProtonBump - Need Proton version as argument 1
> Пт 01 окт 2021 18:10:14 +05 INFO - setRunWineServer - Set the wine binary for proton in path '/home/deathbyte/.steam/root/compatibilitytools.d/proton_tkg_6.18.r3.gd8c1599a/proton'
> Пт 01 окт 2021 18:10:14 +05 INFO - setRunWineServer - to '/home/deathbyte/.steam/root/compatibilitytools.d/proton_tkg_6.18.r3.gd8c1599a/files/bin/wine'
> Пт 01 окт 2021 18:10:14 +05 INFO - setRunWineServer - and wineserver to '/home/deathbyte/.steam/root/compatibilitytools.d/proton_tkg_6.18.r3.gd8c1599a/files/bin/wineserver'
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch - OpenTrayIcon:
> Пт 01 окт 2021 18:10:14 +05 INFO - openTrayIcon - Opening trayIcon:
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch - sortGameArgs:
> Пт 01 окт 2021 18:10:14 +05 SKIP - sortGameArgs - Sorting the game arguments is disabled
> Пт 01 окт 2021 18:10:14 +05 INFO - prepareLaunch - AskSettings:
> Пт 01 окт 2021 18:10:14 +05 INFO - askSettings - Using game specific requester timeout '2'
> Пт 01 окт 2021 18:10:15 +05 INFO - askSettings - Opening Requester with timeout '2'
> Пт 01 окт 2021 18:10:15 +05 INFO - getGameTextFiles - Searching for at least one editable textfile in '/media/hdd_raid/Games/steam/steamapps/compatdata/418370/pfx/drive_c/users/steamuser'
> Пт 01 окт 2021 18:10:15 +05 INFO - getRes - Detected screen resolution '2560x1080'
> Пт 01 окт 2021 18:10:15 +05 INFO - setShowPic - Determining game picture
> Пт 01 окт 2021 18:10:15 +05 INFO - setShowPic - Using '/home/deathbyte/.config/stl/games/header/418370.jpg' as game picture
> Пт 01 окт 2021 18:10:17 +05 INFO - prepareMenu - Opening Menu
> Пт 01 окт 2021 18:10:17 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/global.conf' START
> Пт 01 окт 2021 18:10:17 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/global.conf' STOP
> Пт 01 окт 2021 18:10:17 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' START
> Пт 01 окт 2021 18:10:17 +05 INFO - loadCfg - Loading game config '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf'
> Пт 01 окт 2021 18:10:17 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' STOP
> Пт 01 окт 2021 18:10:17 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/url.conf' START
> Пт 01 окт 2021 18:10:17 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/url.conf' STOP
> Пт 01 окт 2021 18:10:17 +05 INFO - prepareMenu - Entering checkProtonBump
> Пт 01 окт 2021 18:10:17 +05 SKIP - checkProtonBump - Need Proton version as argument 1
> Пт 01 окт 2021 18:10:17 +05 SKIP - updateConfigFile - Config file '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' already at version 'v6.15.95'
> Пт 01 окт 2021 18:10:17 +05 INFO - linkGameCfg - Symlink '/home/deathbyte/.config/stl/gamecfgs/title/RESIDENT EVIL 7 biohazard.conf' already exists
> Пт 01 окт 2021 18:10:17 +05 INFO - createWineList - Updating the Wine Dropdown List
> Пт 01 окт 2021 18:10:17 +05 INFO - getGameTextFiles - Searching for at least one editable textfile in '/media/hdd_raid/Games/steam/steamapps/compatdata/418370/pfx/drive_c/users/steamuser'
> Пт 01 окт 2021 18:10:17 +05 INFO - setShowPic - Determining game picture
> Пт 01 окт 2021 18:10:17 +05 INFO - setShowPic - Using '/home/deathbyte/.config/stl/games/header/418370.jpg' as game picture
> Пт 01 окт 2021 18:10:17 +05 INFO - setOPCustPath - Default path for custom exe file requester is '/media/hdd_raid/Games/steam/steamapps/common/RESIDENT EVIL 7 biohazard/re7.exe'
> Пт 01 окт 2021 18:10:17 +05 INFO - getRes - Detected screen resolution '2560x1080'
> Пт 01 окт 2021 18:10:19 +05 INFO - MainMenu - Clicked '6' - 'ИГРЫ MENU'
> Пт 01 окт 2021 18:10:19 +05 INFO - MainMenu - exiting 'Settings Menu' and opening 'Game Menu'
> Пт 01 окт 2021 18:10:19 +05 INFO - prepareMenu - Opening Menu
> Пт 01 окт 2021 18:10:19 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/global.conf' START
> Пт 01 окт 2021 18:10:19 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/global.conf' STOP
> Пт 01 окт 2021 18:10:19 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' START
> Пт 01 окт 2021 18:10:19 +05 INFO - loadCfg - Loading game config '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf'
> Пт 01 окт 2021 18:10:19 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' STOP
> Пт 01 окт 2021 18:10:19 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/url.conf' START
> Пт 01 окт 2021 18:10:19 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/url.conf' STOP
> Пт 01 окт 2021 18:10:19 +05 SKIP - updateConfigFile - Config file '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' already at version 'v6.15.95'
> Пт 01 окт 2021 18:10:19 +05 INFO - linkGameCfg - Symlink '/home/deathbyte/.config/stl/gamecfgs/title/RESIDENT EVIL 7 biohazard.conf' already exists
> Пт 01 окт 2021 18:10:19 +05 INFO - createWineList - Updating the Wine Dropdown List
> Пт 01 окт 2021 18:10:19 +05 INFO - getGameTextFiles - Searching for at least one editable textfile in '/media/hdd_raid/Games/steam/steamapps/compatdata/418370/pfx/drive_c/users/steamuser'
> Пт 01 окт 2021 18:10:19 +05 SKIP - updateConfigFile - Config file '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' already at version 'v6.15.95'
> Пт 01 окт 2021 18:10:19 +05 INFO - linkGameCfg - Symlink '/home/deathbyte/.config/stl/gamecfgs/title/RESIDENT EVIL 7 biohazard.conf' already exists
> Пт 01 окт 2021 18:10:19 +05 INFO - createWineList - Updating the Wine Dropdown List
> Пт 01 окт 2021 18:10:20 +05 INFO - loadCfg - Loading game config '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf'
> Пт 01 окт 2021 18:10:20 +05 INFO - getRes - Detected screen resolution '2560x1080'
> Пт 01 окт 2021 18:10:20 +05 INFO - openMenu - Starting  createMenu "/dev/shm/stl/menutemp/gamemenu" "launchGameMenu" "/home/deathbyte/.config/stl/games/header/418370.jpg" "EMPTY" "EMPTY" "Настройки для Игры 'RESIDENT EVIL 7 biohazard (418370)'" "MainMenu" "MENU_GAME"
> Пт 01 окт 2021 18:10:20 +05 INFO - createMenu -  got '9' elements: '0 /dev/shm/stl/menutemp/gamemenu launchGameMenu /home/deathbyte/.config/stl/games/header/418370.jpg EMPTY EMPTY Настройки для Игры 'RESIDENT EVIL 7 biohazard (418370)' MainMenu MENU_GAME'
> Пт 01 окт 2021 18:10:20 +05 INFO - createMenu - Creating menu template '/dev/shm/stl/menutemp/gamemenu-template'
> Пт 01 окт 2021 18:10:20 +05 INFO - getFilteredEntries - No blocked elements found in '/home/deathbyte/.config/stl/menublock.conf' - working with '/dev/shm/stl/rawentries.txt'
> Пт 01 окт 2021 18:10:20 +05 INFO - getFilteredEntries - Sort config '/home/deathbyte/.config/stl/menusort.conf' found - sorting
> Пт 01 окт 2021 18:10:20 +05 INFO - openMenu - Currently used tempfile is '/dev/shm/stl/menu.ehHSwLPg'
> Пт 01 окт 2021 18:10:24 +05 INFO - openMenu - Clicked '1' - 'BACK'
> Пт 01 окт 2021 18:10:24 +05 INFO - openMenu - exiting 'Game Menu' and opening 'MainMenu'
> Пт 01 окт 2021 18:10:24 +05 INFO - prepareMenu - Opening Menu
> Пт 01 окт 2021 18:10:24 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/global.conf' START
> Пт 01 окт 2021 18:10:24 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/global.conf' STOP
> Пт 01 окт 2021 18:10:24 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' START
> Пт 01 окт 2021 18:10:24 +05 INFO - loadCfg - Loading game config '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf'
> Пт 01 окт 2021 18:10:24 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' STOP
> Пт 01 окт 2021 18:10:24 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/url.conf' START
> Пт 01 окт 2021 18:10:24 +05 INFO - loadCfg - '/home/deathbyte/.config/stl/url.conf' STOP
> Пт 01 окт 2021 18:10:24 +05 SKIP - updateConfigFile - Config file '/home/deathbyte/.config/stl/gamecfgs/id/418370.conf' already at version 'v6.15.95'
> Пт 01 окт 2021 18:10:24 +05 INFO - linkGameCfg - Symlink '/home/deathbyte/.config/stl/gamecfgs/title/RESIDENT EVIL 7 biohazard.conf' already exists
> Пт 01 окт 2021 18:10:24 +05 INFO - createWineList - Updating the Wine Dropdown List
> Пт 01 окт 2021 18:10:24 +05 INFO - getGameTextFiles - Searching for at least one editable textfile in '/media/hdd_raid/Games/steam/steamapps/compatdata/418370/pfx/drive_c/users/steamuser'
> Пт 01 окт 2021 18:10:24 +05 INFO - setShowPic - Determining game picture
> Пт 01 окт 2021 18:10:24 +05 INFO - setShowPic - Using '/home/deathbyte/.config/stl/games/header/418370.jpg' as game picture
> Пт 01 окт 2021 18:10:24 +05 INFO - setOPCustPath - Default path for custom exe file requester is '/media/hdd_raid/Games/steam/steamapps/common/RESIDENT EVIL 7 biohazard/re7.exe'
> Пт 01 окт 2021 18:10:24 +05 INFO - getRes - Detected screen resolution '2560x1080'
> Пт 01 окт 2021 18:10:26 +05 INFO - MainMenu - Clicked '0' - 'ВЫХОД'
> Пт 01 окт 2021 18:10:26 +05 INFO - MainMenu - exiting 'Settings Menu' and opening 'Exit'
> Пт 01 окт 2021 18:10:26 +05 INFO - closeSTL - closing STL
> Пт 01 окт 2021 18:10:26 +05 INFO - closeSTL - Creating '/dev/shm/stl/stl-closing.tmp'
> Пт 01 окт 2021 18:10:26 +05 INFO - checkPlayTime - The game was not started via 'stl' but directly from Steam - skipping Crash Requester
> Пт 01 окт 2021 18:10:26 +05 INFO - closeSTL - Game 'RESIDENT EVIL 7 biohazard (418370)' exited - cleaning up custom processes if necessary
> Пт 01 окт 2021 18:10:26 +05 INFO - closeTrayIcon - Closing TrayIcon '6019'

**Comment by frostworx** [comment]
so current master...
Tried with a clean `/dev/shm/stl`?

**Comment by IDeathByte** [comment]
yep. no changes

**Comment by frostworx** [comment]
and with a clean `~/.config/stl/`?

**Comment by IDeathByte** [comment]
seens like cleaning config helped.
strange, but i didnt' change anything between builds

**Comment by frostworx** [comment]
a diff might be interesting

**Comment by frostworx** [comment]
nice! 👍
