### ISSUE TITLE
steamtinker takes several minutes to load or open a new page

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#317]
When I try to open any of the steamtinker settings it takes several minutes to load, Running it through the terminal gives this so maybe the issue is that's it's trying to access directory's it doesn't have permission to?

```
Wed Oct  6 05:36:27 PM EDT 2021 ERROR - loadLangFile - Language file '/home/zany130/english.txt' missing
find: ‘/home/zany130/pCloudDrive/Crypto Folder’: Permission denied

find: ‘/home/zany130/.cache/paru/clone/kwin-effects-appear2/pkg’: Permission denied
find: ‘/home/zany130/.cache/paru/clone/kwin-effects-disappear2/pkg’: Permission denied
find: ‘/home/zany130/.cache/paru/clone/kwin-effects-appear3/pkg’: Permission denied
find: ‘/home/zany130/.cache/paru/clone/kwin-effects-disappear3/pkg’: Permission denied
find: ‘/home/zany130/.cache/paru/clone/kwin-effect-osdclock-git/pkg’: Permission denied
find: ‘/home/zany130/.cache/paru/clone/kwin-effects-appear1/pkg’: Permission denied
find: ‘/home/zany130/.cache/paru/clone/kwin-effects-disappear1/pkg’: Permission denied
find: ‘/home/zany130/.cache/paru/clone/kwin-effects-minimize1/pkg’: Permission denied
find: ‘/home/zany130/.cache/paru/clone/kwin-effects-unminimize1/pkg’: Permission denied
find: ‘/home/zany130/pCloudDrive/Crypto Folder’: Permission denied
```
this is on a fully up to date version of Garuda Linux based on arch

so basically opening the main menu by either pressing spacebar or through the terminal takes about 5+ minutes. then going it global settings takes another 5+ min for example and then going back to the main would take another 5+ minutes

**Comment by frostworx** [comment]
steamtinkerlaunch doesn't search any unusual directories, the reason for your paste and the slow loading therefore must come from your system. So please check your logs.
Also how did you install the program? '/home/zany130/english.txt' is no valid search path, assuming your installation is broken
_(logs will tell here as well, maybe the same reason)_

**Comment by frostworx** [comment]
Even with a completely broken _(as in none)_  installation, `stl` just logs here as expected:

```
Do 7. Okt 07:32:13 CEST 2021 INFO - loadLanguage - First load the default language to make sure all variables are filled
Do 7. Okt 07:32:13 CEST 2021 ERROR - loadLangFile - Language file '/usr/share/stl/lang//english.txt' missing
Do 7. Okt 07:32:13 CEST 2021 ERROR - loadLanguage - ###############################
Do 7. Okt 07:32:13 CEST 2021 ERROR - loadLanguage - No language file could be loaded! For the initial setup at least one file (default english) is required
Do 7. Okt 07:32:13 CEST 2021 ERROR - loadLanguage - You can ether copy a valid file to '/home/frostwork/.config/stl/lang' or '/usr/share/stl/lang' or provide an absolute path via command line using the lang= option
Do 7. Okt 07:32:13 CEST 2021 ERROR - loadLanguage - ###############################

```

**Comment by zany130** [comment]
I installed the package from the chaotic aur repo for arch. I figured it out though I opened the global settings and edited the paths to be the corresponding folder under `/usr/share/stl` (I think that's how it should have been by default correct? By default on my install they where all set to `/home/zany130`) after doing the I don't get any more slowdowns and its doesn't try to search my whole home folder( it was set up to search `/home/zany130` and some folders like my pcloud crypto drive can't be accessed) The question I guess is why was it set up to search my home folder in the first place though that might be a problem with how it was packaged in the chaotic aur? (doubt it though)

**Comment by frostworx** [comment]
Can't answer what you or your system configured. logs would have been interesting.
You do not have to configure the default paths, because they are used by default of course, 
so removing all messed up configs would have been the easier way.
Can't answer chaotic aur questions, but I doubt as well that they alter default behavior.
So only you, your system or your logs could know what went wrong.

**Comment by zany130** [comment]
yup gonna close this as i did find a fix by setting the folders to their proper place. I tried uninstalling and deleting everything under `~/.config/stl` and `/usr/share/stl`and then reinstalling and I can't reproduce the issue anymore, it sets the correct paths by when I open the global config. So something must of gotten messed up on my initial install. Anyway thx for responding and I'll go ahead and close this now.
