### ISSUE TITLE
Having Trouble Getting Native Games to Run

### ISSUE THREAD

**Issue by Nano-Ocelot** [sonic2kk/steamtinkerlaunch#321]
The only native game I've managed to get working is Valheim where I could set 'proton version' to 'none'. However in other games I don't have that option therefore they can't be launched because they're forcibly trying to run with proton. How do I force games to run without a proton version? I have attached a screenshot showing the issue where 'none' isn't an option.

![Screenshot_20211014_154445](https://user-images.githubusercontent.com/34014750/137385183-b31a9523-c4b8-4db5-8ad7-a0a03aa2528a.png)

**Comment by frostworx** [comment]
You missed the wiki part below the picture here:
https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Launch-Option

_(the Proton version used can never be set to `none`, and I also cannot reproduce this happening with Valheim)_

Edit: Of course I belive you that you set the option to `none`, that's not what I meant.
Anyway it should not be possible, so you might have triggered a bug or used a stray/old tempfile in `/dev/shm/stl`

**Comment by Nano-Ocelot** [comment]
I actually am using the steam launch option and it still forces me to launch the game using a proton version so it obviously just crashes because it's native. This is very strange. I must've hit a weird bug then. I'll attach a screenshot later for proof. Hopefully I can get this figured out because it's really the best all in one tool for configuring and enabling other tools on Linux and I've been really bummed that I can't get it to work with my native games.

**Comment by frostworx** [comment]
Ok, good to know you're using the steam launch option already. I'll try to reproduce this, maybe Valve changed something and this doesn't work anymore or I added a regression somewhere
Edit: No need to proof - I believe you! :)

**Comment by frostworx** [comment]
I used Braid for testing, because it is small which makes switching between linux and windows version pretty fast.
Good news - the linux version still works with `stl %command%` so nothing seems to have changed.

When the game is installed and not using any compatibility tool please make sure the linux version is actually installed.
stl determines if a linux or windows game is launched by an env variable provided by Steam on game launch _(`STEAM_COMPAT_DATA_PATH`)_. When it is set we have a proton version, if not it is a linux game.
Only when this variable is set, choosing any proton version is actually used in stl, else proton is completely skipped and the game is treted as native game _(`ISGAME=2`)_.
If this doesn't work for you please attach the log file of the game launch, to find out if stl went a wrong way somewhere.

**Comment by Nano-Ocelot** [comment]
This is the log file for Splitgate, which crashes on launch when using `stl %command%`
[677620.log](https://github.com/frostworx/steamtinkerlaunch/files/7354576/677620.log)

**Comment by frostworx** [comment]
There is nothing in the log which crashes.
In fact the game launch function was not even started, so the game also wasn't started using proton.
Instead "Exit" was selected in the settings menu.
Also you might want to check your custom user stop script.

**Comment by Nano-Ocelot** [comment]
That's bizarre. I wonder why it won't launch then. My user scripts are just commands to stop and start the compositor because games launched with STL don't automatically suspend and resume the compositor for some reason. But also the scripts don't work in STL anyway for some reason but that's two different bug reports that I'll make later.

**Comment by frostworx** [comment]
user start/stop scripts are simply executed. If they do not work this is no stl bug, so no need to open a different bug.
feel free to write a good generic PR for compositor suspend/resume, I'm not interested in writing it myself, as I simply use gamemoderun start/stopscripts.
feel free to reopen here if you have useful logs with the game launch not working

**Comment by Nano-Ocelot** [comment]
Well the thing is they work fine when launched from the command line. They just don't work when run in STL.

**Comment by frostworx** [comment]
check function saveOrgVars and ~~saveOrgVars~~ emptyVars

**Comment by Nano-Ocelot** [comment]
Does this help? I might've accidentally opened STL and exited the game manually before sending the log last time.
[677620.log](https://github.com/frostworx/steamtinkerlaunch/files/7369422/677620.log)

**Comment by frostworx** [comment]
As you can see in the new log is no attempt to launch the game as well, so it must be something else crashing on your system.
I've just seen that Splitgate is free, so I'll try to reproduce it here - maybe I find something out (RL stuff like dentist before...)_

**Comment by frostworx** [comment]
Download finished earlier than expected.
It just works!
What I did:
- rename my `~/.config/stl/` to start with a clean default setup
- set `stl %command%`
- start the game
- let the `stl` requester timeout or enter the settings and start from there - both work
- the game starts correctly

Please try to reproduce, maybe one of your `stl` configs messed up somewhere _(would be interesting to see where then)_

**Comment by Nano-Ocelot** [comment]
I just renamed the whole config folder like you said and it still doesn't launch. Hopefully this log will be different and maybe give you more insight. What's confusing is that this is only an issue with native games (except one native game) and the native games work fine if I don't use stl. Every other game works fine.
[677620.log](https://github.com/frostworx/steamtinkerlaunch/files/7375067/677620.log)

**Comment by frostworx** [comment]
Cool, this time the log is complete, and it is indeed visible that the game was detected as Windows game.
*reopening as now it is clearly a bug*
I'll see if I can find anything before time is running out.

Which OS are you running and are you using Steam stable or beta client _(I'm on Arch with Steam Client Beta where it works)_

Please also check if `STEAM_COMPAT_DATA_PATH` is set when you start the game _(just add something like `env > "/tmp/stl-env"` before `main "$@"` at the end of `stl`)_ _(no need to  paste your whole env, just check if it is set - it usually should when a Linux game was started, maybe something changed (in SLR?))_
It would also help if you would test if `stl` reaches the `# win game` part in `function setCustomGameVars`
_(a simple `echo "setCustomGameVars set ISGAME to 2 " > "/tmp/stl-bug"` will do)_

**Comment by frostworx** [comment]
Your `ORIGINAL INCOMING LAUNCH COMMAND`
contains two SLR calls, have never seen that before.
_(I have none, but expected one)_
Pretty sure this is the core problem _(or at least triggers it)_ and might be part of what I wrote here
https://github.com/frostworx/steamtinkerlaunch/issues/324
_(which might point to the Steam command line option already being shut down)_

Can't tell yet if this specific issue is fixable.

**Comment by frostworx** [comment]
HAH!
Any change you have "Steam Linux Runtime" set as compatibility tool?
I can reproduce the issue when it is set, but it works correctly when setting it to "Steam Tinker Launch" _(which basically does nothing, but is a valid option to not switch to the windows build)_

**Comment by Nano-Ocelot** [comment]
> HAH! Any change you have "Steam Linux Runtime" set as compatibility tool? I can reproduce the issue when it is set, but it works correctly when setting it to "Steam Tinker Launch" _(which basically does nothing, but is a valid option to not switch to the windows build)_

Omg that was it! I must've forgot about testing the steam linux runtime a long time ago so they were still set as the compat tool for my native games. It works perfectly fine now.

**Comment by frostworx** [comment]
Relying on the initial existence of the variable `STEAM_COMPAT_DATA_PATH` is no longer a valid option to check if a Linux or Windows game was started in this combination.
Might be simply an upstream glitch, but could as well be part of the [container strategy](https://github.com/frostworx/steamtinkerlaunch/issues/324)
The double SLR appearance can be controlled, the "game OS detection" needs to be rewritten...

**Comment by frostworx** [comment]
Should be properly fixed with https://github.com/frostworx/steamtinkerlaunch/commit/dd3b804675875f02c762ecda040d60a29722cfd3

**Comment by frostworx** [comment]
ping

**Comment by frostworx** [comment]
So just give no feedback anymore, because the workaround works for you, @Nano-Ocelot?

**Comment by Nano-Ocelot** [comment]
Oh, sorry. I haven't tried the fix. I was just rolling with the workaround. I can test it though and report back.

**Comment by frostworx** [comment]
Would be nice, thanks! It should work, but two people testing something is always better than one.

**Comment by Nano-Ocelot** [comment]
Yep, works perfectly fine now. I just had to remove the old config files after updating and now it launches even when 'steam linux runtime' is set in compatibility options.

**Comment by frostworx** [comment]
Thanks for confirmation, glad this is fixed properly :)
*closing here*
