### ISSUE TITLE
Shader Screen not searchable

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#322]
if I open the shader screen and press ctrl+f I notice there is a search box but typing into does nothing(don't know if this is an intended feature or not couldn't find anything about it on the wiki just thought it would be useful to search here and I found the search box). this is on Arch based Garuda Linux and stl version 6.15-1

**Comment by frostworx** [comment]
It is not intended from stl side, but comes directly from yad. No idea why it doesn't work there, maybe it is not implemented.
I don't have the time to track the functionality in yad down, so *closing here*, but if you find something useful, why it doesn't work, feel free to reopen and I'll check if I can implement it before the next release.
