### ISSUE TITLE
breaks video support in trails of cold steel

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#323]
https://www.protondb.com/app/538680
Setting the proton version to stl with proton 6.19-GE-2 cause videos not to work. Setting 6.19-GE-2 directly trough steam instead of with stl does wo
[lastrun.txt](https://github.com/frostworx/steamtinkerlaunch/files/7358803/lastrun.txt)
[538680.log](https://github.com/frostworx/steamtinkerlaunch/files/7358804/538680.log)
[steam-538680.log](https://github.com/frostworx/steamtinkerlaunch/files/7358805/steam-538680.log)

**Comment by frostworx** [comment]
The 538680.log is incomplete and does not contain the game launch or the possibly changed game launch command.
A changed game launch command is the only cause I can imagine, which could lead to this problem.

**Comment by zany130** [comment]
idk how I would get more complete logs I just enabled proton logoing in the game tab of stl and uploaded the logs. Ill upload again. This is just starting the game until the opening cutscene starts and then exiting
[lastrun.txt](https://github.com/frostworx/steamtinkerlaunch/files/7360467/lastrun.txt)
[Trails of Cold Steel.log](https://github.com/frostworx/steamtinkerlaunch/files/7360472/Trails.of.Cold.Steel.log)

[steam-Trails of Cold Steel.log](https://github.com/frostworx/steamtinkerlaunch/files/7360475/steam-Trails.of.Cold.Steel.log)
g

**Comment by frostworx** [comment]
that log looks better (the functions launchSteamGame and startGame were executed).
Looks like you're using steamtinkerlaunch as steam command line option (`stl %command%`) and not as compatibility tool. When using the command line option, the game is always executed without the Steam Linux Runtime because it is not provided via game launch args, which might be required with your game to render the videos.
_("startGame - No SLR was provided via command line, so configuration USESLR '1' is ignored")_

I can't imagine any other reason for the videos not renderning, _(you could disable gamemoderun for testing, but I doubt that this is related.)_

**Comment by zany130** [comment]
it's showing as if I'm launching it a launch command? That's strange I'm using it as a compatibility tool.  could it be because I set it globally as a compatibility tool in steam instead of specifying it in the game?
also yeah I don't think it's game mode either as when i tried it by specifying proton- ge-2 in the steam play settings for the game I also put game mode in the command options and that worked fine. So the issue only happens when I use stl as the compat tool and then load ge-2 with that

EDIT: I still seem to get that same line startGame - No SLR was provided via command line, so configuration USESLR '1' is ignored when I run it as a compatibility tool specifically for this game instead of globaly

**Comment by frostworx** [comment]
maybe Valve changed something recently and the SLR no longer is provided via command line _(upstream changes can break everything anytime of course)_ - no idea.
you could set `STARTDEBUG` _(line 55)_ to `1` and check if the `/tmp/stl-startmode-DEBUG-XXXXXXXXX` logfile reveals something interesting.

**Comment by zany130** [comment]
it shows this 
```
cat /tmp/stl-startmode-DEBUG-XXXXXXXXX
File: /tmp/stl-startmode-DEBUG-XXXXXXXXX
Sun Oct 17 02:10:35 PM EDT 2021 - Trails of Cold Steel (538680) - ======================
Sun Oct 17 02:10:35 PM EDT 2021 - Trails of Cold Steel (538680) - HAVESCTP='0', and HAVEREAP='0' - assuming stl is used as comp
at tool - using regular base game command to continue
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - INITIAL LAUNCH COMAND 'waitforexitandrun /mnt/SSHD/SteamLibra
ry/steamapps/common/Trails of Cold Steel/ed8.exe'
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - HAVESCTP='0';HAVEREAP='0';HAVESLR='0';HAVEINPROTON='0'
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - REAPCMD ''
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - RUNSLR ''
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - INPROTCMD ''
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - INSTLCMD ''
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - ORGGCMD '/mnt/SSHD/SteamLibrary/steamapps/common/Trails of Co
ld Steel/ed8.exe'
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - ORG_STEAM_COMPAT_TOOL_PATHS ''
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - USEREAP='1'; USESLR=1';OVERRIDEPROTON='1'
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - FINAL LAUNCH RUNCMD '/usr/bin/gamemoderun /usr/share/steam/co
mpatibilitytools.d/proton-ge-custom/proton waitforexitandrun /mnt/SSHD/SteamLibrary/steamapps/common/Trails of Cold Steel/ed8.e
xe'
Sun Oct 17 02:10:36 PM EDT 2021 - Trails of Cold Steel (538680) - ======================
```

**Comment by frostworx** [comment]
oh, wait - I mixed it up:
https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Linux-Runtime
it is exactly the opposite, so the log is correct.
I don't see any reason why the video doesn't play with stl then

**Comment by frostworx** [comment]
stl unrelated, but do you have Shader Pre-Caching enabled in Steam?
Regularly it needs to be enabled to make the new gstreamer media foundation videos play, but it can also be enabled with some env variables. Maybe proton-ge does something like this

**Comment by zany130** [comment]
![Screenshot_Settings_1](https://user-images.githubusercontent.com/25832539/137639834-6ce23cdf-9d74-4c50-9b98-8a8acb64f036.png)
yeah, I have it set can't figure this out either as I'm using the same tweaks when I launch directly with proton-ge and stl (game mode, mangohud, shade (through a script https://github.com/kevinlekiller/reshade-steam-proton). I also tried just launching the game with no tweaks on both stl and directly with proton -ge and it doesn't work with stl, but does with proton-ge. I think there both using the exact same proton -ge version ( i have it installed as a package from the chaotic aur for arch and I think stl also uses the proton versions I have on my system?) I also tried using the download custom proton option and downloading ge there and using it with the same results

Logically I would think nothing in stl should break video playback in wine games (only tested with this game though) as that's not whats handling that, its the proton version in this case proton-ge-2

**Comment by frostworx** [comment]
I'm not sure if I [find the time](https://github.com/frostworx/steamtinkerlaunch/issues/309) to debug this, but I guess that the `function emptyVars` in stl requires some changes and just might empty too many variables and therefore proton-ge can't define its gst variables correctly _(~1080 ff in `proton`)

**Comment by frostworx** [comment]
Commenting out
```
LC_ALL="" 
LD_LIBRARY_PATH=""
LD_PRELOAD=""
```
in above function _might_ help (it might also break other things, so it would not be a committable change)

**Comment by zany130** [comment]
oh ok yeah make sense I'm looking into comparing steam log from directly using proton-ge and stl logs don't know if it will have anything useful though. Unfortunately, I'm still a very novice programmer and I'm still going to school but if I find anything on this and also the other issue I opened with yad ill see if I can contribute something even if it's just more information :sweat_smile: 

also ill post back if commenting that out works.

**Comment by frostworx** [comment]
Thanks a lot for trying to help :)

**Comment by zany130** [comment]
here is the proton log from running proton-ge directly doesn't seem to be different though
[steam-538680.log](https://github.com/frostworx/steamtinkerlaunch/files/7360998/steam-538680.log)
and commenting out those 3 lines  in the ```emptyVars``` function didn't help so I don't have any ideas as to where to even look ill post stl logs just in case there's something there
[Trails of Cold Steel.log](https://github.com/frostworx/steamtinkerlaunch/files/7361001/Trails.of.Cold.Steel.log)

[steam-Trails of Cold Steel.log](https://github.com/frostworx/steamtinkerlaunch/files/7361002/steam-Trails.of.Cold.Steel.log)

**Comment by frostworx** [comment]
Thanks for trying! _(In fact I even prefer to not change those 3 lines, because it worked fine so far for everything else, so I'm almost glad that this did not help ;))_
I'll test a bit too, but I do not have the game, so hard to say if I found something interesting :)

**Comment by frostworx** [comment]
Looks like pressure vessel/SLR is not used by default with `stl`, but is when using `proton-ge` directly.
`stl` doesn't disable this on purpose _(didn't know that it can be even deactivated when it does not come from steam launch args)_. Still need to find out why it is disabled _(I guess a missing/incomplete `STEAM_anything` variable needs to be changed)_.
When found it should be enabled by default of course _(maybe with an option to disable it, not sure yet)_
Looks like you found a very important bug here, congratulations! ;)

**Comment by frostworx** [comment]
I added some debug logs to SLR and proton, and it seems that both SLR and proton is started before `stl` (when using `stl` as launch option), so it might be impossible to active SLR/pressure vessel programmatically when `stl` was launched as compatibility tool.
At least overriding "all" _(only tried most usual suspects)_ doesn't enable SLR.
So no idea yet if this is fixable on my end _(maybe some changes in `compatibilitytool.vdf` or `toolmanifest.vdf` and not in `stl` directly can help?)_
Would be interesting though, if your videos play, when you use `stl` as command line option.

**Edit: Yes, updating `toolmanifest.vdf` seems to help! Needs more testing before a proper fix.**

**Comment by frostworx** [comment]
An updated `toolmanifest.vdf` triggers SLR with `stl` used as compatibility tool as well, but
- `compatibilitytools.d/SteamTinkerLaunch/stl` _(changed it to `proton`, to stay compatible here for possible future upstream checks)_ does no longer work as symlink _(rewrote the function CompatTool, so this is fixed in theory - but more complicated than before)_
- `stl` doesn't have the rights to use its own systemfiles in `/usr/share/stl/` because SLR blocks it, so it stops directly at the beginning when trying to load its language files → **possible showstopper** 
Edit: the own stl files could probably be fixed by loading them from $HOME or directly from  `compatibilitytools.d/SteamTinkerLaunch/`, but the (opt)-depends are required as well of course, so this isn't an option.
- more_(?)_

It is unclear if it is fixable, how much effort it requires, and how long it keeps working until upstream changes things again.

**Comment by frostworx** [comment]
Looking at similar SLR issues I think this is not fixable from `stl` side. Even worse, this might kill `stl` one day, as described [here](https://github.com/frostworx/steamtinkerlaunch/issues/324).
What might work is using stl as Steam Launch Option _(maybe installation of missing gstreamer libs required by the game video)_

```
no suitable plugins found:
Missing decoder: DivX MPEG-4 Version 5 (video/x-divx, divxversion=(int)5, framerate=(fraction)30000/1001, width=(int)1280, height=(int)720, parsed=(boolean)true, codec_data=(buffer)000001000000012008c80d40006f67c0184003800097530a5008b428307f, pixel-aspect-ratio=(fraction)1/1)
```
_(maybe gst-libav?)_
Good luck!

**Comment by zany130** [comment]
sorry, I haven't replied been busy. Yeah adding it as a launch command seems to fix the issue ( and is a good workaround for now) So If I'm understanding correctly it sounds like the issue is that stl is disabling SLR (when stl is used as a compat tool)  and the change that would have to be made to stl would cause some issues from the fact that SLR is a container and restricts access? (sorry noob programmer here lol) this reminds me an issue I read about in the steam update notes where they had to whitelist the Nvidia-xconfig to allow application profiles to work within SLR.

**Comment by frostworx** [comment]
Not completely - `stl` doesn't disable SLR, but SLR is started before `stl` and restricts access to system files which `stl` requires _(`/usr/share/stl/` and dependencies)_. Only `$HOME` is accessible, but IMHO it is no sane option to rewrite `stl` to work completely from there, to make a tool happy which prevents `stl` from running _(more or less :))_. I also won't probably find the time to do it.
Good to hear that videos do work with `stl` being started as launch option. Without using a compatibility tool, the SLR is started directly via game launch parameter, so `stl` is able to handle it. The fact that you can see the video _(probably)_ means that SLR and `stl` work together here _(so the SLR container function fails?)_.
Yeah, sounds like the `nvidia-xconfig` whitelist fix is the same issue.
It is nice to have a working environment, but I don't like to be forced to use, so I hope the "v1" `toolmanifest.vdf` and the steam launch option are not shut down.
Have fun playing! *closing here*
