### ISSUE TITLE
Problem with fork custom command on stl-v6.18.307 version

### ISSUE THREAD

**Issue by martinezpenya** [sonic2kk/steamtinkerlaunch#326]
With `stl-v6.18.307` I've tried to launch `dash.exe` (otterhud) with `RaceRoom` (Proton-GE) and dash window open correctly, but Raceroom only starts when I close `dash.exe`.
With same config file I've downgraded to latest release `stl-v6.15` and everything worked fine... `dash.exe` and `RaceRoom` started and worked at the same time.

**Comment by leillo1975** [comment]
I have exactly the same problem

**Comment by frostworx** [comment]
logs might help to find it faster

**Comment by martinezpenya** [comment]
> logs might help to find it faster

Here you have the config file:
[211500.conf.txt](https://github.com/frostworx/steamtinkerlaunch/files/7378974/211500.conf.txt)

And the logs when raceroom opens after closing dash.exe:
[211500.log.NOTWORKING.txt](https://github.com/frostworx/steamtinkerlaunch/files/7378984/211500.log.NOTWORKING.txt)

And finally the log when raceroom opens at the same time with dash.exe:
[211500.log.WORKING.txt](https://github.com/frostworx/steamtinkerlaunch/files/7378995/211500.log.WORKING.txt)

If you need more info, please ask me.

**Comment by frostworx** [comment]
Thanks for the logs _(unfortunately nothing obvious to see here)_.
For whatever reason current master has a 60 seconds sleep [here](https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L8532). Probably a leftover of some debugging I already forgot.
Would you please test if removing/uncommenting that line already fixes the issue?
this is the only difference in the corresponding part in the `function launchCustomProg` between current master and v.6.15, so with some luck that's already all :)

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/commit/62a4e5faf28e8bc57639ca1d8e607651042aff28

**Comment by martinezpenya** [comment]
Yes! removing this two lines from my stl file made it work again. Thank you!

**Comment by frostworx** [comment]
nice, thanks for reporting and testing!
