### ISSUE TITLE
Support stand-alone ModOrganizer2 instances

### ISSUE THREAD

**Issue by ajventer** [sonic2kk/steamtinkerlaunch#333]
Wabbajack has a hard dependency on stand-alone ModOrganizer2 instances, in order to support a future Linux-capable Wabbajack STL should switch, or at least support, the use of stand-alone rather than shared MO2 instances, which are specific to the bottles of the games they apply to.

**Comment by frostworx** [comment]
Unlikely that I will find the time to add Wabbajack support. I left the [issue](https://github.com/frostworx/steamtinkerlaunch/issues/305) open, in case someone wants to contribute a PR.
For a better overview, I'll migrate your hint to the [Wabbajack issue](https://github.com/frostworx/steamtinkerlaunch/issues/305).
