### ISSUE TITLE
Can't set DXVK FPS or custom environment commands

### ISSUE THREAD

**Issue by jarrard** [sonic2kk/steamtinkerlaunch#335]
It be nice if this was a feature. Sometimes I need to set custom commands like limit fps, but I can't because there is no pre launch environmental custom command options... .

**Comment by frostworx** [comment]
You can add any custom variable easily via the Editor menu. Either add it per game by editing the game config or globally in the global.conf. [No idea when](https://github.com/frostworx/steamtinkerlaunch/issues/309) I find the time to add DXVK FPS directly.

**Comment by jarrard** [comment]
Yeah I discovered I could just add it to the config file myself. Cheers. 
Maybe you can make it so people can add in custom actions to STL themselves by editing a config and just adding things in themselves which can then be toggled in any stl instance.

**Comment by frostworx** [comment]
Do you mean something like the [Start-Stop-Scripts](https://github.com/frostworx/steamtinkerlaunch/wiki/Start-Stop-Scripts)?

**Comment by jarrard** [comment]
Possibly, can you pass environmental variables there that enable DXVK FPS limits?

**Comment by frostworx** [comment]
the accepted arguments are described in the wiki and all already exported variables should be available.
of course you can just set variables in your scripts if you want.

**Comment by jarrard** [comment]
Yeah sorry doesn't make sense just looking at wiki. 

I like how Lutris does it and you can just slap in environmental arguments into a list and be done with it.

**Comment by frostworx** [comment]
Not sure where the difference is here, but PRs welcome as usual.

**Comment by jarrard** [comment]
Well Lutris doesn't force you to write a script or edit cfg files :)

**Comment by frostworx** [comment]
Have fun with Lutris then! 😏)

**Comment by jarrard** [comment]
> Have fun with Lutris then! smirk)

Yeah I do. But that's ok, not a big issue. 
Was only a suggestion to make it a little easier to add in own environmental arguments within STL gui. 
If you happen to use NON-STEAM game option you can't do this via steam itself due to an annoying bug valve has yet to fix.
