### ISSUE TITLE
Add Flawless Widescreen Support for Proton Games

### ISSUE THREAD

**Issue by ChaosBlades** [sonic2kk/steamtinkerlaunch#336]
https://www.flawlesswidescreen.org/

> Flawless Widescreen was created in an effort to make it easier to craft fixes and patches to get games functioning correctly in UltraWide/Surround/Eyefinity gaming resolutions, often developers neglect these types of users leaving them to fend for themselves and find their own solutions, or in some unfortunate cases - live without the wonderful world of ultra-wide support.
> 
> With simplicity in mind, designed to be as simple as possible to use - simply select a supported game from the list, configure any basic desired configurable options and launch your game.

> Linux
> A Linux build may be available at a later time - several people have reported Flawless Widescreen runs very well under WINE however mileage may vary per plugin and game.

They have said `A Linux build may be available at a later time` for a very long time now.

I have read in multiple places it works on linux via proton games but no guides exist that I can make sense of. It would be very helpful for new users if this was easier to use. Not being able to get this to work are my main reason I have yet to buy Mass Effect Legendary Edition and Tales of Arise.

**Comment by frostworx** [comment]
Looks interesting. I doubt though that I will [find the time](https://github.com/frostworx/steamtinkerlaunch/issues/309) soon to look into it, so I hope someone wants to create a PR for it.

**Comment by frostworx** [comment]
Just gave it a quick try with Mirrors Edge and it _just works_ as forked custom command.
For a full implementation, it probably only requires
a `USEFWS` option.
If enabled:
- automatic download and extraction of "fws"
- automatic vcrun2010 installation into the game `WINEPREFIX`
- game architecture determination to launch the correct fws exe
- start "fws" forked together with the game

Looks like an installation function of "fws" into the game `WINEPREFIX` or any automated configuration of it is not required.

**Comment by frostworx** [comment]
With [this commit](https://github.com/frostworx/steamtinkerlaunch/commit/a9e8f97943c5ae5cbecda9d43e2e295aada3ab08) initial support for [https://www.flawlesswidescreen.org/](https://www.flawlesswidescreen.org/) was added.

*(see* [*wiki*](https://github.com/frostworx/steamtinkerlaunch/wiki/FlawlessWidescreen)*).*

I haven't tested very much. If you have issues, please report them.

**Comment by VasyaSovari** [comment]
First test: Devil May Cry 5
Initial launch of Registry Edit window, which has to be closed for FWS & game to launch.
FWS is then completely frozen. NO fix is applied, screen remains in 16:9
Second test: DS2:SOTFS
Again, Registry editor launches. On closing-
FWS can be interacted with, but game will not launch.
Third test: Forgive me Father
Again, registry
Game doesn't have FWS plugin, but FWS can be interacted with. Unsurprisingly, does nothing

**Comment by frostworx** [comment]
thx for testing.
FWS does work fine with Mirrors Edge, so the basic implementation is apparently working (would be nice if this can be reproduced on other systems).
I wonder why the registry editor pops up. Do you have it enabled for those games or does FWS open it?
When all your tests fail, it is very likely that wine/proton has a compatibility issue or requires additional 3rd party components to work correctly. I don't have the time to test every single game for functionality, though.
If possibly required 3rd party packages would be known I could add them of course.
Leaving this open for testing/debugging for now.

**Comment by VasyaSovari** [comment]
welcome

Nope, registry isn't enabled. I just went into the UI and ticked the Flawless checkbox for each game. The same instance of Flawless appeared for Forgive, DS2 and DMC3 (I had tabs open for DS2 & DMC5) and did not detect the games
Installed Mirros's Edge to verify: yes, it worked. Interesting - ME appeared to use its own instance of FWS and detected the game instantly.
I tried playing with install paths but that didn't work either

**Comment by frostworx** [comment]
thx for elaboration, @undeadbydawn.
when I find the time I'll play around with some other random game, but don't plan to spend much time into this.
@ChaosBlades any test results are welcome of course.

**Comment by VasyaSovari** [comment]
1. I am an idiot. I didn't actually try changing in-game video settings while testing DMC. This seems painfully obvious now but didn't occur at all at the time.
2. I tried standalone FWS via wine (with it unchecked in stl) and... it worked. After I changed in-game video settings.
3. I then tried FWS again via stl and it worked.
4. I re-opened standalone FWS and disabled the fix, so only the stl version was enabled. 21:9 still worked. The stl version of FWS was still 'frozen'
5. Then removed stl %command% from the DMC5 options. 21:9 still worked 

So, FWS most likely works via wine, since I could interact with it. The 'fix' still works even if deselected. And my testing for FSW via stl is completely redundant cos I forgot to do the one thing I needed to do.

**Comment by frostworx** [comment]
Oh nice, thanks for re-trying! 👍
Just to make sure I understood you correctly: there's nothing left which does not work with `stl`, but does without it, right?
_(even if something is left (point 4?), I would blame the used proton/wine version, because `stl` does nothing unusual 😀)_

**Comment by VasyaSovari** [comment]
yeah, I just confused the bejeezes out of myself.
It's entirely possible stl FWS DMC5 works perfectly, cos I didn't try changing resolution until I tried FWS wine (which I've now uninstalled).
stl FSW definitely does work for Mirrors Edge. I can't retest DMC5 for a negative cos the 'fix' remains in place even with no FWS running at all.
I'm now failing to find other games to test

**Comment by frostworx** [comment]
Nice, thanks for confirmation! :)

**Comment by VasyaSovari** [comment]
Just confirmed stl FWS also works for The Wolf Among Us.

**Comment by frostworx** [comment]
any comment,  @ChaosBlades?

**Comment by frostworx** [comment]
👍, @ChaosBlades

**Comment by ChaosBlades** [comment]
Sorry for ghosting. I have not had any time to test or play any games. R.I.P. the money I paid to sub to SWTOR. I appreciate you adding this. One of the last few annoyances of switching to Linux full time can now be marked off my list.

**Comment by frostworx** [comment]
Thanks for the reply - even if late :)
