### ISSUE TITLE
Skyrim crashes on startup when launching from MO2 with SteamTinkerLaunch

### ISSUE THREAD

**Issue by hazelnot** [sonic2kk/steamtinkerlaunch#338]
For some reason launching Skyrim through MO2 through STL makes it crash the second it reaches the main menu.

I've used Skyrim with MO2 in Linux before with a Lutris script (which no longer works), and I was able to play it. Fallout New Vegas and Skyrim SE work with STL and MO2, which makes this even more puzzling.

Now it doesn't work even with all mods disabled, and even with a new blank instance, and even with a complete reinstall of the game. Some crash logs which were supposed to help me here aren't getting generated at all (not STL related), and I have no idea why it's doing this.

I'm using the AUR version of STL.

Sorry if this is the wrong place for this, but I tried getting support elsewhere and got no replies.

**Comment by frostworx** [comment]
Hi,
do you start Skyrim through Steam using stl (so MO2 is started "via" Steam instead of the game, or do you start MO2 from stl command line or gui?
Only in the first case the game would start inside the game wineprefix, in the latter case it would start in the MO2 wineprefix, which might work but is not recommended.
If you start it through Steam it should just work and if it doesn't it might possibly be the wineprefix or the used proton version itself which prevent the game from running.
I hope some people gather in the discord/matrix channels to help each other, because I won't find the time anymore to help there.
Good luck so far!

**Comment by hazelnot** [comment]
I'm starting it through Steam from the game's wineprefix. That's part of why it's so weird, if I start it directly it works, but if I start it through MO2 through the same prefix without any mods, even if I start the launcher instead of SKSE or the game directly, it just crashes after the Bethesda logo

**Comment by frostworx** [comment]
Very strange indeed then. Is this Skyrim SE (489830) or the classic Skyrim (72850)?
Does it work with using stl, but without MO2? It doesn't seem to be really a stl problem and I'm not sure if I can help, especially as I do not really use MO2 myself.
I'll try to get help in the [closed MO2 issue](https://github.com/frostworx/steamtinkerlaunch/issues/304) by pointing to this issue, maybe someone can help.

**Comment by hazelnot** [comment]
Classic Skyrim. It seems to work if I launch it without MO2. I'd ask in MO2 support places maybe, but I'm a bit concerned that they'd just tell me to go away since Linux isn't officially supported lol

**Comment by frostworx** [comment]
Nah, as discussed on discord meanwhile, it works fine here using MO2, and the error you pasted looks like a broken wineprefix install

**Comment by desmond27** [comment]
If you have logging enabled, you could also check your papyrus logs in <prefix>/drive_c/Users/steamuser/Documents/my\ games/<game name>/logs (Writing the path from memory, actual path might be slightly different).

This should give you a hint as to what might be causing the issue.

**Comment by hazelnot** [comment]
I completely reinstalled the game (including deleting the wineprefix) and I'm still having this issue. I also have no idea if I have logging enabled or where to even enable it.

Edit: OK I managed to enable it. The log says

```
[11/03/2021 - 03:58:46PM] Papyrus log opened (PC)
[11/03/2021 - 03:58:46PM] Update budget: 1.200000ms (Extra tasklet budget: 1.200000ms, Load screen budget: 500.000000ms)
[11/03/2021 - 03:58:46PM] Memory page: 128 (min) 512 (max) 76800 (max total)
[11/03/2021 - 03:58:55PM] Cannot open store for class "dlc1scwispwallscript", missing file?
[11/03/2021 - 03:58:56PM] Cannot open store for class "DLC2BenthicLurkerFXSCRIPT", missing file?
```

I also skipped MO2 and I got pretty much the same log but with different timestamps and 

```
[11/03/2021 - 04:00:26PM] VM is freezing...
[11/03/2021 - 04:00:26PM] VM is frozen
```
at the bottom, presumably because I manually quit the game

**Comment by frostworx** [comment]
Does not really look like a stl issue, does it?

**Comment by hazelnot** [comment]
I have no idea what kind of issue it is though, and where I could even get help for it. I just know that I could play Skyrim with MO2 with a Lutris script before, but unfortunately that doesn't work anymore for unrelated reasons (Lutris dropped Proton support)

**Comment by frostworx** [comment]
Assuming the "missing file" errors above are not the fatal problem, have you tried other proton versions to see if that changes something? Lutris is unrelated indeed as well.

**Comment by desmond27** [comment]
In MO2, perhaps you could check whether all plugins are enabled? If they are not, just click the checkbox next to them and then try running the game again.

**Comment by rawardy** [comment]
I've had this problem a few times. Switch the steam compat tool away from stl (to for example proton-GE-6.20) and launch game directly through proton. Allow it to compile vulkan shaders. Then once you've made it into the game, exit, switch back to stl and launch with THE SAME version of proton through stl (eg. proton-GE-6.20). Then it should work. (I skip MO2 first time.) You can change Proton versions to whatever you like in stl after following these steps with no issues.
 
  I don't know if it's when an update to stl, the AUR version of proton-GE, or Steam that causes this issue for me. But it's always after a system update that this occurs, if it occurs at all.

**Comment by rawardy** [comment]
If it still doesn't work you could try removing your ./.config/stl/mo2 folder. Repeating the steps above making sure MO2 is disabled in STL config and then reinstalling MO2 via 'stl mo2 i' after you've successfully booted Skyrim through stl once.

**Comment by hazelnot** [comment]
> I don't know if it's when an update to stl, the AUR version of proton-GE, or Steam that causes this issue for me. But it's always after a system update that this occurs, if it occurs at all.

Well it's not the AUR version of Proton-GE cause I'm not using Proton-GE, so it must be one of the other things. I'll try your suggestion anyway though

**Comment by rawardy** [comment]
I use Proton-GE because the regular version has issues running Skyrim for me. Maybe try a GE Proton version if all else fails?

**Comment by hazelnot** [comment]
Soooo turns out I *was* using Proton-GE, and your trick worked. Thanks so much!
