### ISSUE TITLE
Line 4861: : command not found

### ISSUE THREAD

**Issue by blurryberry** [sonic2kk/steamtinkerlaunch#339]
Hello, I hope I am not bothering too much with my issue.

I wish to give your program a shot after watching Hex DSL's video about STL. I am on Pop_OS! 21.04 and my problem is that I cannot manage to get STL working. I checked the steamtinkerlauncher.desktop file to see what command is being executed and when I run this very command under the terminal I get the following error message: 

find: ‘’: No such file or directory
/usr/bin/stl: line 4861: : command not found

I followed your installation instructions from the wiki to the teeth, installed all the hard dependencies and compiled myself a newer version of YAD (version 10.1 (GTK+ 3.24.25) by the time I am writing this issue report).

Also certain commands do work like "stl meta" or "stl wiki" which prompts the YAD window to show up. I searched into the previous closed issue reports but I couldn't one that matched my current problem. 

If you need more information I will be glad to help in order to be able to try STL.
Thank you.

**Comment by frostworx** [comment]
Hi,
Hm, strange. Please retry from scratch _(remove the directory `/dev/shm/stl` when it exists, stl creates temp files there)_
with `stl settings` and attach the `/dev/shm/stl/stl.log` here.

**Comment by blurryberry** [comment]
Hello again,
I removed the directory as instructed and ran "stl settings" again (with the same error that I mentioned previously

Here's the log file:
[stl.log](https://github.com/frostworx/steamtinkerlaunch/files/7472651/stl.log)
).

**Comment by frostworx** [comment]
Hi,
thx for the log and sorry for the short answer. I'm afk in a few minutes.
It might be possible that it fails with setting up an initial proton version for the template config, probably because you seem to use a native linux game. Might help to rename `~/config/stl` and start from scratch with `stl settings` or with starting a proton game via stl in steam. will try to debug this later. good luck so far!

**Comment by blurryberry** [comment]
That is fine (also with work),
I have renamed the stl folder and ran "stl settings" again. This time it worked successfully (and generated another stl folder) and the settings window came onto my screen. I don't know what exactly happened that could've caused the issue but I will keep the renamed stl folder in case you need anything from there.

As for the Linux native game, I was actually trying to run Batman: Arkham Asylum GOTY Edition which needs Steam Proton so yeah no native executable.

Thank you again and if I can be of help regarding why the issue happened in the first place I will stay in touch.

**Comment by frostworx** [comment]
Thanks for testing. Glad to hear this "solved" itself automatically :)
When Batman was detected as Linux game, something went really wrong apparently.
If you like, you could diff the old/new `global.conf`, `default_template.conf` and the `gamecfgs/id/35140.conf`
maybe an important variable was empty for some weird reason.

**Comment by frostworx** [comment]
¯\_(ツ)_/¯

**Comment by Faalagorn** [comment]
> ¯\\_(ツ)_/¯
You dropped this: \\ – it needs to be doubled :D

**Comment by frostworx** [comment]
hrhr, I often do that - it is on a hotkey I never fixed :)
