### ISSUE TITLE
Please add way to run winecfg and winetricks in the vortex prefix

### ISSUE THREAD

**Issue by monyarm** [sonic2kk/steamtinkerlaunch#340]
The main use for this would be to get different modding tools working when ran through Vortex.
As an example xEdit's drag and drop is broken unless the xEdit executables are set to winxp.

**Comment by frostworx** [comment]
No idea if and when I find the time to implement this, but I leave the issue open, of course.
Still hoping for community rising with some PRs in the bag :)

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/commit/1158b2b667e84aa55c650548928509683c187d29 should work

**Comment by frostworx** [comment]
so?

**Comment by monyarm** [comment]
Ya, that should work, though MO2 should also have it as an option.
