### ISSUE TITLE
Can't install vortex due to wine error

### ISSUE THREAD

**Issue by itsspher** [sonic2kk/steamtinkerlaunch#342]
Hello, I can't seem to install vortex due to a problem with wine. Attached is the console output, with all instances of USER to be censored for privacy:

```
SSL_INIT
SSL_INIT
Sun Nov  7 11:57:03 PM PST 2021 INFO - installVortex - Using '/home/[USER]/.config/stl/proton/custom/Proton-6.17-STL-1/files/bin/wine' for installation
SSL_INIT
wine: could not load kernel32.dll, status c0000135
Sun Nov  7 11:57:25 PM PST 2021 INFO - installVortex - Installing '/home/[USER]/.config/stl/downloads/vortex/vortex-setup-1.4.16.exe' into '/home/[USER]/.config/stl/vortex/compatdata/pfx'
wineserver: using server-side synchronization.
wine: could not load kernel32.dll, status c0000135
Sun Nov  7 11:57:26 PM PST 2021 INFO - installVortex - Base Vortex installation finished
```

I'll be glad to provide more logs if necessary, just point me to their location and/or how to generate them

**Comment by frostworx** [comment]
This shouldn't happen, of course.
Can you please check the md5sum of the downloaded `Proton-6.17-STL-1.tar.gz` in `~/.config/stl/downloads/proton/custom/`?

```
# md5sum Proton-6.17-STL-1.tar.gz 
ce74e86f03ab37724426f4d807b8613d  Proton-6.17-STL-1.tar.gz
```

I never found the time to implement a real validity check for any downloaded files _(and likely won't in the future)_
so a partially broken download might already be the cause of the issue.

A game independent log file is created in `/dev/shm/stl/stl.log`, game releated logfiles can be found under
`~/.config/stl/logs/stl/id/${SteamAppID}.log` with a symlink in
`~/.config/stl/logs/stl/title/${GameTitle}.log`

**Comment by itsspher** [comment]
Hi, the md5sum is as follows:

```
md5sum Proton-6.17-STL-1.tar.gz 
ce74e86f03ab37724426f4d807b8613d  Proton-6.17-STL-1.tar.gz
```

No such logfile exists in `/dev/shm`, no `stl` folder either.

**Comment by frostworx** [comment]
`/dev/shm` is in ram. you need to reproduce your commands for a log.

**Comment by frostworx** [comment]
missing feedback
