### ISSUE TITLE
Mod Organizer 2 appmanifest error

### ISSUE THREAD

**Issue by shinnova** [sonic2kk/steamtinkerlaunch#344]
After installing Mod Organizer 2 it won't actually start because of what I am assuming is the automatic instance creation failing. 

Here is the cli output when trying to start it:
```
> stl mo2 s
grep: /home/shinnova/.local/share/Steam/steamapps/appmanifest_489830.acf
/home/shinnova/.local/share/Steam/steamapps/appmanifest_489830.acf: No such file or directory
grep: /home/shinnova/.local/share/Steam/steamapps/appmanifest_489830.acf
/home/shinnova/.local/share/Steam/steamapps/appmanifest_489830.acf: No such file or directory
on. 10. nov. 22:45:43 +0100 2021 INFO - startMO2 - Starting '/home/shinnova/.config/stl/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe' in standalone mode with command:
on. 10. nov. 22:45:43 +0100 2021 INFO - startMO2 - WINEDEBUG="-all" WINEPREFIX="/home/shinnova/.config/stl/mo2/compatdata/pfx" "/home/shinnova/.local/share/Steam/compatibilitytools.d/Proton-6.15-GE-2/files/bin/wine" "/home/shinnova/.config/stl/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe" -i "Skyrim Special Edition"
```

And this is a screenshot of the error I get right after:
![mo2_error](https://user-images.githubusercontent.com/12647312/141199475-09055bc3-4e0e-4603-a460-508b7f1e0c51.png)

The confusing thing is that the appmanifest file does in fact exist and can be read just fine.

**Comment by frostworx** [comment]
Please check/provide the corresponding [log(s)](https://github.com/frostworx/steamtinkerlaunch/issues/93).
Hard to tell what could have gone wrong without them.

**Comment by shinnova** [comment]
Admittedly the only thing that stands out to me in the log is stl failing to find the game install and then finding it after all. Here is the [Skyrim Special Edition.log](https://github.com/frostworx/steamtinkerlaunch/files/7530428/Skyrim.Special.Edition.log).

**Comment by frostworx** [comment]
- `manageMO2GInstance` skips setting up a MO2 game instance, if it finds a `ModOrganizer.ini` for the `$GAME` in
`~/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/$GAME/ModOrganizer.ini`
I didn't implement a function which checks if the game path in that file is _(still)_ valid.

- only if that file is missing **and** if the game directory was found from the `appmanifest` _(via `getGameDirFromAID` called from  `manageMO2GInstance`)_ the initial `ModOrganizer.ini` is created.
Looks like this function had problems with your two games.
Is it possible that you moved 'Skyrim Special Edition (489830)' and 'No Man's Sky (275850)' once or reinstalled them and there are old stray `appmanifest` files left somewhere, or you're using some self-made symlinks?
You might want to check the game paths found in the `appmanifests` and compare them with the actual game path and those added into `ModOrganizer.ini`.

Can't tell when/if I find the time to add some error checks in those functions.

Would be interesting if your games are added correctly, when you remove
`~/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/$GAME/ModOrganizer.ini`
for both games.
If you try this, please do so in the following order:
- close `stl`
- remove both files
- remove recursively `/dev/shm/stl/` _(if it exists - it is a temporary directory)_
- start mo2 via `stl mo2 s`
- check `/dev/shm/stl/stl.log`

**Comment by shinnova** [comment]
I've uninstalled No Man's Sky for now as I am only trying to manage Skyrim SE. The game path in the appmanifest matches the actual game path. Can't check ModOrganizer.ini as it doesn't exist due to the instance never being created. 

After cleaning up and running `stl mo2 s` this is my Local folder:
```
> ls /home/shinnova/.config/stl/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/
cache  LOOT  Microsoft
```

Here is my [stl.log](https://github.com/frostworx/steamtinkerlaunch/files/7532126/stl.log)

**Comment by frostworx** [comment]
"You might want to check the game paths found in the appmanifests and compare them with the actual game path and those added into ModOrganizer.ini."
**Please check this**. Only the wineprefix/compatdata of your game is found, but not the actual game directory.
Pretty sure this is no stl problem in the first place.

**Comment by shinnova** [comment]
```
> grep "installdir" /home/shinnova/.local/share/Steam/steamapps/appmanifest_489830.acf 
        "installdir"            "Skyrim Special Edition"
```
with `/home/shinnova/.local/share/Steam/steamapps/common/Skyrim Special Edition/` being my game install. That matches, does it not? I still can't check ModOrganizer.ini as it wasn't created. 

Any ideas as to what it could be if it isn't stl?

**Comment by shinnova** [comment]
I got Mod Organizer 2 to start now after completely wiping stl and reinstalling it, though it still fails to automatically create the Skyrim instance. After manually creating the instance everything works as it should. Guess something was really wrong with my stl install. So while the appmanifest problem isn't resolved, I can work around it.

**Comment by frostworx** [comment]
> with `/home/shinnova/.local/share/Steam/steamapps/common/Skyrim Special Edition/` being my game install.

That looks correct indeed.
A full log "after completely wiping stl and reinstalling it" could have been interesting to see what went wrong on your system.
Closing here anyway.
