### ISSUE TITLE
Name collision for stl executable

### ISSUE THREAD

**Issue by bekopharm** [sonic2kk/steamtinkerlaunch#346]
Didn't run `stl` for a while and was kinda confused when it stopped working.

Turns out I installed `python3-numpy-stl` meanwhile which provides `/usr/bin/stl`.

![image](https://user-images.githubusercontent.com/5016428/141688600-efc72384-273c-43cb-83c4-6e901e2623f8.png)

I'm not sure what the best course of action is here. I mean I know to work around this and adjust this manually using `$PREFIX`  or `$PATH` alas I understood that the idea of `steamtinkerlauch` is to prevent the user from having to do command line wizardry. I'd wager this will happen to other users as well that need this library for working with STL files in CAD and well… it was kinda there first :sweat_smile:

**Comment by frostworx** [comment]
Oh, thanks for the heads-up! I knew STL exists in the CAD context _(and I didn't really care tbh)_,
but I was unaware that there's also a binary `stl` which is a problem indeed.
Maybe I should take this as an opportunity to reconsider the name completely, as `steamtinkerlaunch` could be pretty helpful with non-steam games as well.
I think I'll start a little survey for the new name within the next days.

**Comment by frostworx** [comment]
Me again :)
Although it might be nice to have a "steam" independent project name, I'm not even sure if relabeling and migrating the whole project to a new place makes much sense _(especially as I do no longer work on it as much as before and therefore restarting with an even less known project name might be contra-productive :))_.

So the better approach might be to simply rename the main program to `steamtinkerlaunch`.
The `PROGCMD` variable _(which is used as base for all variables using `stl` currently)_
is created from the executable name anyway, so no further adjustments should be required in the code itself
_(apart from a little temporary migration function for old configs and removal of all "hard-coded" `stl`-paths in the configs)_.

So everybody who wants to use a short executable name _(and/or keep/use `stl`)_ can simply create a symlink pointing to
`/usr/bin/steamtinkerlaunch`

People who use `stl` as Steam command line option either have to change their command lines everywhere or create the `stl` symlink `stl` manually, so at least here this will be a breaking change 

Edit: of course any thoughts and suggestions welcome :)

**Comment by bekopharm** [comment]
Sounds perfect! :+1: 

I'd expect `steamtinkerlaunch` anyway based on the project name. (Something vscode e.g. is driving me crazy with cuz it's just `code`)

**Comment by frostworx** [comment]
Hehe, thanks for the feedback! :) 👍

**Comment by frostworx** [comment]
Just fyi: I started working on adding a checksum check for several downloads. As soon as this is releasable ("soon" 😀), I'll fix this issue shortly after.

**Comment by frostworx** [comment]
fyi: https://www.reddit.com/r/SteamTinkerLaunch/comments/qwwz6l/renaming_the_program_name_stl_soon_to/

**Comment by frostworx** [comment]
The fix just went live with https://github.com/frostworx/steamtinkerlaunch/commit/967822e973f480e48374c790a303eb99aa1b2c09
See also [here](https://github.com/frostworx/steamtinkerlaunch/issues/350#issuecomment-974633396) for details.

**Comment by frostworx** [comment]
Closing as `fixed`.
Feel free to reopen when you have issues.
