### ISSUE TITLE
stl breaks steam's exit game function

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#347]
stl prevents the game from exiting from the steam overlay. Trying to causes stl to send  notifications that it is closing but the game keeps running. Seams to happen when stl is used as a launch command and reshade is enabled ? 
[Trails of Cold Steel.log](https://github.com/frostworx/steamtinkerlaunch/files/7541915/Trails.of.Cold.Steel.log)

this has happened in several games once I enable reshade in stl. running these games without stl (but still with reshade) allows the steam exit function to work

**Comment by frostworx** [comment]
Probably not steamtinkerlaunch itself prevents the game from existing, but a third-party software.
Proton-GE did so as well, so I added a workaround for it. Can't tell if a workaround is possible for ReShade as well.

Are you sure this only happens in Steam launch command mode? Probably Steam Linux Runtime related then.
The log is incomplete or not the correct one, please re-check.

**Comment by zany130** [comment]
ok intrestlingy runnnig stl as a launch command prevents the game from exiting like i said here is the log (this is all it printed i 
[lastrun.txt]
[Trails of Cold Steel.log](https://github.com/frostworx/steamtinkerlaunch/files/7547845/Trails.of.Cold.Steel.log)
(https://github.com/frostworx/steamtinkerlaunch/files/7547844/lastrun.txt)
tried exiting immediately which made stl think it crashed)

launching it as a compat tool allows the game to exit 
[Trails of Cold Steel.log](https://github.com/frostworx/steamtinkerlaunch/files/7547880/Trails.of.Cold.Steel.log)

**Comment by frostworx** [comment]
The actual launch command is identical in both runs:
`STL LAUNCH COMMAND: '/usr/bin/gamemoderun /home/zany130/.local/share/Steam/steamapps/common/Proton 6.3/proton waitforexitandrun /mnt/SSHD/SteamLibrary/steamapps/common/Trails of Cold Steel/ed8.exe'`

but you disabled the SLR in the Steam launch option run:
`USESLR is disabled, so skipping 'SteamLinuxRuntime' found in the commandline`
...
`ORIGINAL INCOMING LAUNCH COMMAND: '/home/zany130/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=538680 -- /mnt/SSHD/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/zany130/.local/share/Steam/steamapps/common/Proton 6.3/proton waitforexitandrun /mnt/SSHD/SteamLibrary/steamapps/common/Trails of Cold Steel/ed8.exe'`
which might cause this issue _(in fact I see no other reason why it should behave differently here and the possibility to actually disable SLR will very likely be shut down completely upstream ASAP anyway)_

**Comment by zany130** [comment]
I disabled SLR as it messes with this game when ran with STL (see issue https://github.com/frostworx/steamtinkerlaunch/issues/323) also I have to disable SLR in the settings if I run STL as a launch command it immediately closes.

Anyways the game exit works when STL is ran as a compat tool even with SLR so IDK if SLR is the issue. Again also I have no issues running this game with reshade, mangohud etc.. normally(as in without STL) and I can exit the game fine its only when I try to use STL as a launch command

**Comment by frostworx** [comment]
SLR with stl as compat tool is triggered totally different.
edit: you now also started with "mangohud, etc...", so please elaborate under which exact constellation you think this is an issue and when it is not

**Comment by zany130** [comment]
when I use STL game exit doesn't work when I don't use STL game exit works
i mention manghud and others  to point out that the issue only happens when I try to use STL as a launch command, and does not happen when I run the game without STL even if I use manghud, reshade and other tools

**Comment by frostworx** [comment]
very confusing "bug" report imho...
I'll see when/if I find the time to decrypt this.

**Comment by zany130** [comment]
Sorry I'll record a video of what the issue is so that it is easier to understand.

**Comment by frostworx** [comment]
No, please don't. I don't like video "documentations".
It might be just me, but I find all this unrelated bonus information a bit confusing.

**Comment by frostworx** [comment]
I'll try to summarize this, please correct me if I'm wrong somewhere, if my summary is unclear or if I missed something:

When steamtinkerlaunch is used as "Steam launch option", the game _(no matter which game(?))_
fails to exit _(from "Steam view", so the "Play" button is stuck on "Exit/Quit" although the game already exited)_
Here it might be interesting if you have this behavior with all or just with specific Proton versions.

The same game, with overall identical steamtinkerlaunch settings, exits properly when steamtinkerlaunch is used as compatibility tool.

**Comment by zany130** [comment]
yup pretty much to add to it and sum it up

- launching any game WITH steamtinkerlauncher as a launch tool  ~~with reshade, gamemode, and manghud(henceforth referred to as tweaks) configured~~ causes steam in-game overlay game exit not to work

- launching any game WITH steamtinkerlauncher as a compact tool ~~with the same tweaks~~ allows steams in-game overlay game exit to work properly

- launching any game WITHOUT steamtinkerlauncher ~~with the same tweaks~~ allows steams in-game overlay game exit to work properly

~~- issue was ONLY reproducible in other games when configured similarly (same tweaks) in steamtinkerlauncher~~ EDIT: was mistaken no tweaks needed


Hopefully, I made it a little clearer I was trying to add my observations and I think that kinda made everything overly complicated so a bullet point might help. I think its best to report my observations as short and concise as possible and not add my opinion or any other unessecary stuff

**Comment by frostworx** [comment]
Thanks for summing it up.
Just to be clear:
When using steamtinkerlaunch as "Steam launch option" WITHOUT reshade, gamemode, mangohud the game exists as expected in the Steam client?
Does any of those 3 tweaks (not) trigger the bug when enabled standalone (so without the other two enabled)?

**Comment by zany130** [comment]
ok, IDK why I thought my tweaks were necessary to reproduce the issue  (To be honest I did write the issue right before having to go to class so I was in a rush prob, not a good idea in hindsight:sweat_smile:)  so no tweaks are necessary. running steamtinkerlaunch (as a launch command) with no settings set causes the issue as well  so let me fix my list

**Comment by frostworx** [comment]
Ok, this is indeed good to hear, as it should make easier to find the issue. I can't promise that I can fix it though,
because the SLR might cause it `(indirectly)`. Can you confirm that this also happens with using an official proton version?

**Comment by zany130** [comment]
I am using proton 6.3-7 in all these test I have not yet tried other versions I try that now and edit this comment

EDIT: yeah proton version doesn't seem to matter tried experimental as well as ge

**Comment by frostworx** [comment]
perfect! I'll see what I can do (soon)

**Comment by zany130** [comment]
I think I figured this out. You were right. this is happening because I am disabling Steam reaper and SLR in the steamtinkerlaunch settings. apparently, steam reaper is needed for the game exit to work (which makes a lot of sense) so this issue is completely my fault and I wasted everyone's time . Sorry. I was disabling steam reaper and SLR as it was causing issues with the game I am playing (trails of cold steel) when launched with steamtinkerlauncher

**Comment by frostworx** [comment]
You tried to help to find the issue, so imho this was no waste of time and it is perfectly fine for me.
In fact I'm always happy that some users are willing to help fixing bugs.
Of course I'm glad anyway that I do not have to hunt this bug :)
