### ISSUE TITLE
STL prints "Closing tray icon '28767'" and closes itself whenever it's launched

### ISSUE THREAD

**Issue by SimplyTadpole** [sonic2kk/steamtinkerlaunch#348]
I've installed STL's v7.0 release through make install, as specified in the installation page. However, I'm on Linux Mint 20.2, therefore I had to manually download, compile and install the updated version of Yad because Mint's repository only offers an incredibly outdated version of Yad. Installation of Yad 10.1 went fine (if frustrating due to me needing to hunt down several other dependencies that also aren't in the Mint repository), but when I launched STL, it seemed to directly skip the prompt for me to open up it settings menu and immediately open the game. And if I try to manually open the Steam Tinker Launch (Settings) app, it automatically closes itself while showing "Closing tray icon '28767'" as a system notification. That exact same message appears when I launch a game with the "stl %command" launch option before it shows a message that it's launching the game, skipping the STL settings.

I'm sorry if this report is inconclusive, bad, or otherwise sounds rude and mean-spirited. That's not my intention, I'm just kind of stunned at what happened and hope that the cause of this issue can be pinpointes to help out other people who may suffer from this as well. I'm also not very experienced with writing issues, either.

**Comment by frostworx** [comment]
Please try the following:
- (optionally remove/rename `~/.config/stl/` to restart from scratch)
- remove `/dev/shm/stl/` recursively if it exists _(only temporary steamtinkerlaunch files in here)_
- run `stl settings` from a terminal
- check/attach the just created `/dev/shm/stl/stl.log` log-file, which hopefully helps to find your problem.

**Comment by frostworx** [comment]
ping?

**Comment by frostworx** [comment]
closing as `invalid`
Feel free to re-open when you have logs.
When testing with git master don't miss this announcement:
https://github.com/frostworx/steamtinkerlaunch/issues/350
