### ISSUE TITLE
Mod Organizer 2 NXM Associate / URL Broken

### ISSUE THREAD

**Issue by Spoons** [sonic2kk/steamtinkerlaunch#349]
Seems that the proton binary is not being set or detected. 
```
stl mo2 u "nxm://skyrimspecialedition/mods/12604/files/35407?key=9g0LwfT-vBYqi5lglnN_4w&expires=1637337976&user_id=1804140"
Wed Nov 17 11:14:46 AM EST 2021 INFO - dlMod2nexurl - Download Url 'nxm://skyrimspecialedition/mods/12604/files/35407?key=9g0LwfT-vBYqi5lglnN_4w&expires=1637337976&user_id=1804140' for game 'skyrimspecialedition'
STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/username/.local/share/Steam" STEAM_COMPAT_DATA_PATH="/home/username/.config/stl/mo2/compatdata" "" "run" "ModOrganizer.exe" "$1"
/usr/bin/stl: line 11948: : command not found
```

Your shell scripting is impressive!

**Comment by frostworx** [comment]
Thanks for reporting!
I can reproduce this - "$MO2RUNPROT" is definitely empty.
I don't have much time for steamtinkerlaunch anymore and started a bigger change recently _(adding checksum comparison for several downloads)_, so I'm afraid this needs some days until I have a fix.

**Comment by frostworx** [comment]
Looks like this is a bug "double-feature" (strange , that nobody noticed this before, must have been broken somewhere in between):
- In `function setDotNetWine`
an
`export "$2"=$DNPROTON"
is required, so `$MO2RUNPROT` survives until it is needed.
- the MO2 compatdata needs to be created initially using Proton and not using wine, as else
`tracked_files`, which is mandatory for running the `$MO2RUNPROT` later.

I hope the latter doesn't trigger a new issue, as I initially created it using Proton iirc
(and might have switched to wine later maybe for dotnet compatibility)

**Comment by frostworx** [comment]
Yeah, I can confirm fixing both issues above also fix this issue.
Will push it separately from my current offline changes within the next minutes.

**Comment by frostworx** [comment]
If I haven't forgotten anything, this commit https://github.com/frostworx/steamtinkerlaunch/commit/706166b3ea38b215b7fcc7c32768025dbc1a4fd8
should fix the issue.
If "`tracked_files`" is missing in your `~/.config/stl/mo2/compatdata/ `you probably have to recreate it unfortunately.

**Comment by Spoons** [comment]
Tested and confirmed working. Thank you. 

I have written scripts professionally and it never occurred to me to pass in the name of a variable for a function to export, setting its value like a pass by reference. Neither had I considered using expansion on the left side of export. I'm glad you wrote out that explanation or I would not have made the connection.
