### ISSUE TITLE
Wait requester not showing

### ISSUE THREAD

**Issue by pinduzera** [sonic2kk/steamtinkerlaunch#357]
I am not sure if that was my error or how to find more debugging info. 
But following the steps and installing everything plus yad 10.90 (had to build manually).
Then added it to steam launcher. it seems to be using the tool correctly (I am sure because it redirects to the wrong proton version), but the 2 seconds wait dialog does not show up to make any edits. Any idea how to proceed?

Thanks :)

**Comment by pinduzera** [comment]
Fixed, I think my yad install was not global so I had to point the stl to the right binary path:

`steamtinker launch yad /usr/local/bin/yad`

**Comment by frostworx** [comment]
Glad you fixed it, but when you have binaries in `/usr/local/bin`, `/usr/local/bin` should be in your `$PATH` anyway.

**Comment by humanplayer2** [comment]
@pinduzera Thank you for this. I'm on Pop!_OS and had to build yad manually too. Wait requester didn't show until I did as you suggest.
