### ISSUE TITLE
gameshader options not working and spams notifications and prevents steamtinkerlauncher from reopening

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#361]
EDIT: this happened on a clean install
opening the game shader option in the main menu causes the steam tinker launcher to spam requested proton 'none' not found. [/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log](https://bin.garudalinux.org/?48b152fb75f078dc#3A2Hugve8ocNA9vb66YPqeFk2FuqdWJGfayL7o36SVqx )
seems it messed up steamtinkerlaunch config files so I have to recreate them.

**Comment by frostworx** [comment]
Thanks for reporting. Sounds like a recently introduced regression.
I really need more testers on the git version, so those bugs don't make it into a release :)

**Comment by frostworx** [comment]
I can't reproduce this. Starting "Game Shaders" from the settings menu on a clean install currently just stops with
the message
```
INFO - GameShaderDialog - Using Shader destination directory ''
SKIP - GameShaderDialog - Dest Dir '' does not exist and could not be created - skipping
```
which could be improved when starting without a valid SteamAppID, but is valid.

Please re-test from scratch `(maybe you had some temporary files in `/dev/shm/steamtinkerlaunch/` from a previous run?)`.
Your log also doesn't contain any shader related functions.

**Comment by zany130** [comment]
my bad l can't reproduce it anymore either maybe I did have something leftover in the /dev/shm/ folder that messed something up. I was using a git package from a few days ago and was having some issue so I decided to do a clean install of steamtinker I deleted the `.config/steamtinkerlaunch/` folder but didn't reboot so maybe the `/dev/shm/steamtinkerlaunch` was left behind as I think /dev/shm/ is stuff stored in ram right?  I did reboot before testing so whatever it was might of been cleared

**Comment by frostworx** [comment]
yeah, `/dev/shm` is ram. steamtinkerlaunch re-uses several temporary files in `/dev/shm/steamtinkerlaunch` to speed up things, but this might cause errors, when you change steamtinkerlaunch versions. Might be worth to add a version check on launch.

**Comment by frostworx** [comment]
Heh, I already have a version check in function `initShmStl`.
So you must have bad luck and picked two git versions where I didn't change the program version.
