### ISSUE TITLE
steamtinkerlaunch prevents DXVK options other than 1

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#363]
Like the title says options other than 1 do not work. (does not show the hud)
setting it in steam launch options and running steamtinker as a launch tool does not work either, but 
setting it in steams launch options and launching without steamtinker does work however so I guess it's a problem with steamtinker?
log
[steamtinkerlaunch.log](https://hastebin.com/cahagoguqa)

**Comment by zany130** [comment]
figured out the issue when you select multiple DXVK HUD options it saves it as  `DXVK_HUD=' devinfo fps frametimes'` which is incorrect it should be `DXVK_HUD=devinfo,fps,frametimes` for example

as for passing it a steam launch option not working that probably because steamtinker is overriding the DXVK HUD environment variable set in the launch options (which makes sense)

**Comment by frostworx** [comment]
Above fix should work. Don't have the time to test it.

**Comment by frostworx** [comment]
works for me

**Comment by zany130** [comment]
yup works here to. The only thing I would add is that the dxvk scale option is still missing. from dxvk readme 
scale=x: Scales the HUD by a factor of x (e.g. 1.5)
I tried to take a look at the code to see if I can do a PR but never really done that before but I think I should be looking here https://github.com/frostworx/steamtinkerlaunch/blob/511b36095c4952f54eba3439d396e7e8689cc108/steamtinkerlaunch#L8726
specifically here I think is where we can add more options if I'm understanding the code correctly https://github.com/frostworx/steamtinkerlaunch/blob/511b36095c4952f54eba3439d396e7e8689cc108/steamtinkerlaunch#L8735
but the problem is that it can take several values so I guess there would have to be a place where the user can input a value

**Comment by frostworx** [comment]
adding support for the scale factor would be a bit of an overkill, because it would be pretty much work for just one more option.
it would take a complete rewrite of the currently pretty slim gui function _(yes, it's in `DxvkHudPick`)_.
also yad doesn't seem to support floats as form filed option, so this would require another workaround.
an easier and cheaper solution would be to simply add another DXVK_SCALE option independantly from the dxvk settings gui.

**Comment by frostworx** [comment]
should work: https://github.com/frostworx/steamtinkerlaunch/commit/7cf2eb316ed75940a267552e90bc27807538c9cb
edit: it does :)
