### ISSUE TITLE
Can't Get "Arguments: -issteam" to Go Away

### ISSUE THREAD

**Issue by con5cience** [sonic2kk/steamtinkerlaunch#365]
I'm trying to intercept and remove `-issteam` from a game and am having a ridiculous amount of trouble doing what seems to be a very simple task. In the Game Menu I tick the `SORTGARGS` box and have tried nulling out the `HARDARGS` box or just leaving it set to `none`, and in either case after I save and go back to the main menu, I always see `Arguments: -issteam` on the program description.

What do?

**Comment by frostworx** [comment]
🤨 @ "ridiculous amount" of trouble ... simple task"_
I haven't touched the functions since the `HARDARGS` changes, maybe something broke.
Attach a log!

**Comment by frostworx** [comment]
Also last paragraph
https://github.com/frostworx/steamtinkerlaunch/wiki/Game-Command-Line-Arguments

**Comment by frostworx** [comment]
*invalid*
