### ISSUE TITLE
Downgrading from v8.0+ effectively wipes config

### ISSUE THREAD

**Issue by MattSturgeon** [sonic2kk/steamtinkerlaunch#371]
I noticed while looking into a seperate issue that v8.0 will rename `~/.config/stl` to `~/.config/steamtinkerlaunch` on first run. However the pre-8.0 versions obviously don't have any code to do the reverse, which means that if one downgrades from v8.0+ to an earlier version a fresh `~/.config/stl` is generated (and `~/.config/steamtinkerlaunch` becomes redundant and ignored).

This might seem obvious, but it could be confusing to a user who doesn't realise the config directory has been renamed. From their perspective this will probably just look like their settings (and vortex/mo2 **mod lists**/config) have been wiped.

Not sure there's anything we can do about this, other than maybe mentioning it on the v8.0 release notes?

**Comment by frostworx** [comment]
Thanks for the report. Just added a warning on the release notes.
Should be more than enough for an unknown and very little number of users who would run into this.

`When downgrading from v8.0 to a previous version, be aware that you have to take care of downgrading your ~/config/steamtinkerlaunch/ configs yourself manually.`
