### ISSUE TITLE
Feature Request: Easier installation with yad bundled

### ISSUE THREAD

**Issue by o-bri** [sonic2kk/steamtinkerlaunch#373]
Is it possible for you, to make the installation on Ubuntu and derivates easier?

My son was interested in stl but he was driven away by the uneasy yad installation. Shouldn't it be possible, to just have a binary version of yad that comes with steamtinkerlaunch?
So that one can just do "sudo make install" on Ubuntu and derivates too? All the other dependencies are easy to install and mostly installed anyways.

Steamtinkerlaunch seems to be really a great tool and thanks for sharing your work with others for free. I think it could be more widely used, if it was easier to install (I know, it is easy when the aur is available).

**Comment by frostworx** [comment]
**short answer:**

Sorry, no. Not my job.

**long answer:**
Sorry, no.

It is generally not the job of development upstream to provide packages for any distribution.
In some cases, they provide packages for the distribution they use themselves, but that is usually basically everything.
In this case, it would not even be my own package to provide packages for, but `yad`.
You could try to as yad upstream, if they want to provide ubuntu _(or whatever other distro)_ packages, but likely you will get more or less the same answer.

Users who use one specific distro which is lacking any package they are interested in should either provide a package themselves or try to encourage a package maintainer to do so.
I already did much more than most devs would do to make life easier for people using "yad free" distributions.
You might want to read my [yad wiki entry](https://github.com/frostworx/steamtinkerlaunch/wiki/Yad) for details, which basically answers the question as well.

Of course anybody who is willing to contribute to the project by providing packages for their distribution is still welcome.

I'll leave this open for a while for general discussion, hoping it attracts someone willing to help.

**Comment by frostworx** [comment]
→ https://bugs.launchpad.net/ubuntu/+source/yad/

**Comment by o-bri** [comment]
Thanks for your answer, but I must confess, that I do not really understand the mindset behind it (if I understand it right).

> Sorry, no. Not my job.

Yeah, of course! You do not get paid for it and if you are not interested in doing it, that is of course absolutely OK.
But "not my job" is kinda strange answer to me, as it is also not your job to provide steamtinkerlaunch at all.
It is very friendly, that you provide your work please do not get me wrong. But of course it is not your job nor can anyone demand that from you.
So I would have understood an answer like "I have no desire to do so in my spare time"

> It is generally not the job of development upstream to provide packages for any distribution.

I think that is nonsense, to be honest. 
If one provides software and want it to be used by others, it makes no sense to say "it is not the job of me to make sure, users can use the software" - and that is what you are generally saying.
Also i think the more modern approach is "devops like" and that would also help Linux in general. Providing software the enduser can easily use surely an important thing to get more people to the platform. And not like: "There is the source code. You do not have the skill to get it working? I do not care!"

But hey who am I! It is just my opinion and I am thankful for your contributions anyways.

Perhaps I will find a way to make a deb package that can easily be used on Ubuntu, when the christmas holiday comes. But that will depend on the demand of my son and if I am able to get it working - I never had something to do with things like that.

**Comment by frostworx** [comment]
Looks like you did not really read my reply. Closing here.

**Comment by frostworx** [comment]
someone pointed out on discord that the 3rd part appimage has undefined symbols, which I could reproduce.
Initially I disabled the functions using the appimage,
but I just played some minutes with building a new yad appimage and it was pretty easy with the tools kadogo provided _(after some minor modifications)_ _(see this [issue](https://github.com/frostworx/steamtinkerlaunch/issues/98#issuecomment-720107680))_
I might host a new appimage binary here https://github.com/frostworx/steamtinkerlaunch-tweaks/releases
but it will be unsupported _(and likely unmaintained as well)_ from my end.

*reopening, as I'm curious if people are actually willing to help keeping this updated*

**Comment by frostworx** [comment]
fyi: https://github.com/kadogo/easy-builder/pull/12

**Comment by frostworx** [comment]
https://www.reddit.com/r/SteamTinkerLaunch/comments/rfnqrn/added_support_for_new_yad_appimage_using_yad_1090/

**Comment by TassieDevyl** [comment]
I would be interested in attempting it.
Though I haven't done anything quite like this before.
If I can get one successful build, then sure I will keep on with it.
It's likely I would need to ask questions from time to time if thats ok?

**Comment by frostworx** [comment]
Thanks for the kind offer, @TaliesinEmrys.
I haven't rolled any AppImages before as well, but it was pretty straightforward using the scripts.
Sure feel free to ask anytime, can't promise that I can of any help regarding AppImages though ;)

**Comment by o-bri** [comment]
So i tried to create a debian package, which does not seem to be complicated, but then the details come along....

I was able to build the yad debian package, but using yad does not work, as it tells me: `yad.settings not installed.`

I found this issue https://github.com/v1cont/yad/issues/119, but the infos did not really help me.
Perhaps someone has a hint, otherwise I will investigate further when I have time again.

Actually I thought to just compile the binaries and put them in a debian package. Maybe that is to naive, who knows...

**Comment by frostworx** [comment]
Indeed it is not complicated.
I don't know that error, but did you actually try what yad upstream suggested in the url you posted?
what were your configure parameters?
depending on what you used as `PREFIX=`, `make install` should have installed
share/glib-2.0/schemas/yad.gschema.xml into that `PREFIX`.
Sp I guess a valid command for PREFIX="/usr" would be
`lib-compile-schemas /usr/share/glib-2.0/schemas/`

you know that appimage above is a working workaround already for using yad on your yad-free distribution, right?

**Comment by TassieDevyl** [comment]
Hallo frostworx.
I'll attempt my first yad appimage build using kadogo's easy-builder later on today or tomorrow time permitting.
Once question for the yad build if I may.
Do I use the yad-10.1.tar.xz or one of the source options.
Newbie question, sorry.

**Comment by o-bri** [comment]
> Indeed it is not complicated. I don't know that error, but did you actually try what yad upstream suggested in the url you posted? 

I think it did not work, as /opt/yad/share is not available. I just did the make without install. As my plan was to just bundle the binarys made by the make command into the deb file.
But that was obviously not the right thing to do. 


> what were your configure parameters? depending on what you used as `PREFIX=`, `make install` should have installed share/glib-2.0/schemas/yad.gschema.xml into that `PREFIX`. Sp I guess a valid command for PREFIX="/usr" would be `lib-compile-schemas /usr/share/glib-2.0/schemas/`

Perhaps that seems to be dumb, but I just did `./configure && make` and then used the created binaries.

> 
> you know that appimage above is a working workaround already for using yad on your yad-free distribution, right?

I saw that. I wanted to try to make a deb package for easy installation of yad and if that is successfull, maybe try to make one to install steamtinkerlaunch.
So it would be very easy to install on Ubuntu and derivates.
Just an idea, perhaps it is useless in the light of the existing appimage.

**Comment by frostworx** [comment]
Hallo @TaliesinEmrys :)
You might want to try with my [fork](https://github.com/kadogo/easy-builder/pull/12) of kadogos [easy-builder](https://github.com/kadogo/easy-builder), as it has some minor fixes.
Creating an AppImage is pretty much straightforward:
- checkout the repo (or my fork)
- `cd easy-builder/yad/`
- _(check dependencies.sh or execute it if using a debian/ubuntu derivate for installing yad dependencies)_
- `./build.sh` _(this pulls yad from git and compiles it, which probably answers your question)_
- `./download-linuxdeploy.sh` downloads a binary from [this repo](https://github.com/linuxdeploy/linuxdeploy/), required for the AppImage
- `./create-appimage.sh` _(this creates the AppImage within the `./git/` directory)_

Good luck so far! :)

**Comment by frostworx** [comment]
@o-bri 
Creating and maintaining a package _(on any distro)_ is a bit more than a 
`./configure && make && make install`
and **expecting** anybody else to do the rest.


> > It is generally not the job of development upstream to provide packages for any distribution.
> 
> I think that is nonsense, to be honest. If one provides software and want it to be used by others, it makes no sense to say "it is not the job of me to make sure, users can use the software" - and that is what you are generally saying.

This says pretty much everything already.
I develop a program, write a wiki, help with (polite) reports _(even if invalid)_ and accept _(polite)_ feature requests in my free time,
and then there are people like you, whose only motivation to "contribute" to a **community driven** open-source project is their egoism.
And even then still expect support...

I'm very sure this is nonsense for you as well and you still think that you are right, but no, you are not ;)
**EOD!**

**Comment by o-bri** [comment]
> Creating and maintaining a package (on any distro) is a bit more than a
./configure && make && make install
and expecting anybody else to do the rest.

That was not my intention. Even if I obviously did not transport my message very well.
It was clear to me, that I have to do more and research things. But asking a question and "expecting anybody else to do the rest" is surely not the same and you surely know that.

> This says pretty much everything already.

Sorry when you are offended, but you should learn to tolerate other peoples opinions. And do not take things personally, that are not meant as an offense against you.

> I develop a program, write a wiki, help with (polite) reports (even if invalid) and accept (polite) feature requests in my free time,
and then there are people like you, whose only motivation to "contribute" to a community driven open-source project is their egoism.

As it is nothing I have an advantage from, how can it be an egoism? Sorry, but that does not make any sense.

> I'm very sure this is nonsense for you as well and you still think that you are right, but no, you are not ;)

Hell, you mix up a question on a technical thing, with a statement on another thing.
If you are angry because of my statement, I am sorry. I did **not** want to blame you.
But driving someone away who tries to learn new things to then be able to help in the future because of a statement you dislike is not necessary.

> EOD!

I will not come back to that topic or to you and wish you best of luck and success with your project.

**Comment by kadogo** [comment]
I'm a bit late to the issue, but I have merged the changes of frostworx

**Comment by frostworx** [comment]
Thanks, @kadogo! 👍

**Comment by kadogo** [comment]
Welcome @frostworx ^^

I also updated the AppImage, but I still build it against Debian stretch, so let me know if I need to build it against buster or to have multiple releases. If there is maybe a "command" for testing the AppImage I can test it too

**Comment by frostworx** [comment]
Good to see you're still here, @kadogo :)
I could add another option for `steamtinkerlaunch yad ai` where you could either provide a yad AppImage
- download url or 
- absolute local path

What do you think?

**Comment by kadogo** [comment]
I think it's a good idea, it will let people only change the "path" for yad or instead download the binary that you provide or from another source.

It's best to wait, the thought of other peoples, but I only see benefit for these features ^^

**Comment by frostworx** [comment]
Snippet from the upcoming `yad` [ wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Yad):

## AppImage

The `ai` or `appimage` command line option accepts multiple options:

`steamtinkerlaunch yad ai` 									→ **current default AppImage is downloaded/used from [here](https://github.com/frostworx/steamtinkerlaunch-tweaks/tags)**
`steamtinkerlaunch yad ai /path/to/a/local/yad-appimage`  	→ **sets the absolute path as `yad` command**
`steamtinkerlaunch yad ai http/s/url`						→ **multiple options:**
  - valid URL
    - the URL ends with AppImage → the filename will be used from the URL
    - the URL does not end with AppImage → the filename will be created from `Yad-$(date +%Y%m%d)-x86_64.AppImage`
  - invalid URL → **the failed download won't be accepted, leaving currently set `yad` command untouched**

`steamtinkerlaunch yad ai /path/to/an/unusable/file`  		→ **ignored, leaving currently set `yad` command untouched**
`steamtinkerlaunch yad ai /invalid/absolute/path` 			→ **skipped and current default AppImage is downloaded/used**


- the default destination directory for downloads is `~/config/steamtinkerlaunch/downloads/yadappimage/`
- the default AppImage download is sha512sum checked

**Comment by frostworx** [comment]
I just pushed the new options with [this commit](https://github.com/frostworx/steamtinkerlaunch/commit/78de21111595d6109290044b757a870062d05604)
and updated [the wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Yad#appimage) accordingly. have fun!

**Comment by frostworx** [comment]
hey @TaliesinEmrys, did you have success?

**Comment by TassieDevyl** [comment]
Yes I did thankyou it worked successfully.
Followed your above instructions to the letter.
Sorry for the late reply.

**Comment by frostworx** [comment]
Great to hear!

**Comment by frostworx** [comment]
Seems like this can be closed...
