### ISSUE TITLE
MO2/Vortex installer stuck

### ISSUE THREAD

**Issue by pikasalt** [sonic2kk/steamtinkerlaunch#376]
The installers for MO2/Vortex get stuck at the step where it uses Proton-6.17-STL for installation.
![image](https://user-images.githubusercontent.com/52518103/145756328-fe48944a-9b04-4df8-adc8-11fb036b0fd1.png)
I have tried switching between the stable and git versions on the AUR, as well as deleting the steamtinkerlaunch folder in .config before each attempt.
This is the terminal output when running `steamtinkerlaunch vortex install`:
```
wine: created the configuration directory '/home/preston/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/share/default_pfx'
wineserver: using server-side synchronization.
wine: could not load kernel32.dll, status c0000135
```

**Comment by frostworx** [comment]
Please check/provide the [log](https://github.com/frostworx/steamtinkerlaunch/issues/93)

**Comment by pikasalt** [comment]
Sorry, should've done that from the start. Here's the log.
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/7701296/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
_(will test this later that day, but)_
how long did you wait for the installer?
Especially, installing dotNet takes a very long time,
so maybe it just wasn't finished yet.
Removing the steamtinkerlaunch folder in .config was a good idea already, but it might be also worth to remove `/dev/shm/steamtinkerlaunch/` which hold seom temporary files (and might be re-used when you try from scratch).

**Comment by pikasalt** [comment]
The longest I've let it sit is about 20 minutes. I tried deleting the folders in shm/.config and I'm getting the same result.

**Comment by frostworx** [comment]
Just gave it a quick try. For me it works fine and your logs unfortunately look fine so far.
Could you please swap [this line](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L11647)
with [that one](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L11648)?

Just curious if the variables are all fine (so alternatively commenting out [this first line](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L11647)) and adding an exit after the other one should be enough for logging the line.
I'm sure we'll find this bug (soon or later)

**Comment by frostworx** [comment]
ping

**Comment by frostworx** [comment]
please reopen if you're ready
