### ISSUE TITLE
Steam Tinker Launcher does not exit after game exits

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#377]
here is the log https://hastebin.com/ipudizovax  but doesn't seem to be anything there ( I think it got overwritten as the timestamps inside the logs are recent but the yad tray icon presits after the game is closed and is even fully functional ( can open the different settings like shaders etc..)

**Comment by frostworx** [comment]
sometimes games and/or third part tools hang. it is impossible to say what went wrong here of if it is even fixable
*invalid*
_(I'd prefer logs directly uploaded here instead of having to follow some 3rd party side)_
