### ISSUE TITLE
Feature request: protongbd

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#378]
May be useful to have this as an option for debugging proton games
 https://github.com/Joshua-Ashton/protongdb

**Comment by frostworx** [comment]
Good idea, let's see how complicated it is to implemented it to work ootb for the user without any configuration

**Comment by frostworx** [comment]
Hm, two issues on that one:
- the project itself has no release or tag
- it depends on protontricks

Doesn't make much sense then to add support for it as
- `protongdb` would require an own package _(at least for Arch/AUR)_ _(which might be ok-ish to create/maintain one when it had a release)_
- depending on a wip script with some python lines which wrap some Steam variables around gdb and also pulls in protontricks _(which probably does nothing what steamtinkerlaunch does as well - no idea)_ seems to be more work as it helps.

I like the idea though to have gdb support, so I might(!) add gdb support directly instead -nothing promised. :)

Meanwhile you might want to play with the [already implemented x64dbg](https://github.com/frostworx/steamtinkerlaunch/wiki/X64dbg-Support) instead _(I hope it still works, haven't touched it for a while, but there were also no bug-reports)_

Leaving this open until I decided if I'll add native gdb support _(or until it is added :D)_

**Comment by frostworx** [comment]
Heh, just have seen that `protongbd` calls `steam.exe` through proton _(assuming the dummy one in
`$COMPATDATA/pfx/drive_c/Program Files (x86)/Steam/`)_ which might be interesting for other things.
It is not needed though when `gdb` is integrated in steamtinkerlaunch, as you should be able to simply enable `USEGDB`
_(f.e. by dragging it into a Steam Category `GDB`)_ and then start the game through `gdb` regularly by simply starting it through steam _(should be run through a terminal automatically though, no idea if this could become problematic)_

Still nothing promised, but I think it is pretty simple to implement `gdb` support into steamtinkerlaunch _(though not sure yet with the terminal mentioned above)_

**Comment by frostworx** [comment]
Not sure yet how to best open a terminal on game launch **(is there are mime-type for bash scripts, so `xdg-open` can be option number one?)**, but I'll add `gdb` support.

Edit: by default `xdg-open` ignores shebang and ".sh" filename suffix, so this doesn't seem to be an option :(

**Comment by frostworx** [comment]
🙄

**Comment by zany130** [comment]
yeah, might be difficult to implement. My knowledge is really limited but couldn't you do something like `konsole -e gdb` if the gdb option is set? the problem would be figuring out what terminal the user has, but maybe that can be done in the global config?

**Comment by frostworx** [comment]
You have a good timing. I already implemented the core part _(offline)_. The only thing left is the terminal :)
fortunately, the "-e" option is more or less an option for every terminal emulator available, so I set this at least as default.
Initially, I considered to autodetect available terminals and choose one, but I think I will just use a global variable and let the user set it manually (I do not think anyway that many people will use the `gdb` feature, so this wouldn't be worth the effort).

For autodetecting available terminals a rough `grep -i TerminalEmulator  /usr/share/applications/*` might be a good starting point, but... well... no.

The final launch command of `gdb` will look something like this:
`"$USETERM" "$TERMARGS" "bash -c \"$GDBRUN\""`

Where `USETERM` is the terminal emulator program
`TERMARGS` are the command line arguments ;D _(by default simply `-e`)_
and `GDBRUN` is the auto-generated `gdb` launch script, which uses the same args as `protongbd`

The game launch process is started similar like in `protongbd` as well, but using my own functions and not `protontricks`
and also taking care of older proton versions which had the "dist/" paths instead of "files/".

The feature might be ready for a wip commit within the next days, but not sure yet.

**Comment by zany130** [comment]
That might be a good way to do it especially if later you want to do some other function in the terminal though can't really think of any use case for calling a terminal other then debugging. Also agree wouldn't be worth auto detecting the term as i  think this is a nice to have but won't be used as much as other options as this would only be used by people with some Debugging knowledge.

**Comment by frostworx** [comment]
hehe, I wondered the same :)
Maybe for only opening the terminal instead of the game to adjust things manually.
Game specific vars would be set then and pwd would be the game dir automatically but that's pretty much all :)

**Comment by frostworx** [comment]
Upcoming  [Gdb wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Gdb-Support):

# [Gdb](https://github.com/frostworx/steamtinkerlaunch/wiki/Gdb-Support)

**The current gdb implementation is mainly untested and might be even incomplete.
Basically it seems to work correctly, but no idea how stable using gdb with wine/proton should be generally.
During basic testing I got access violations f.e. with specific games.
Can't tell if this could be fixed from steamtinkerlaunch side, it might be as well a problem with a specific proton version, which also happens with [X64dbg](https://github.com/frostworx/steamtinkerlaunch/wiki/X64dbg-Support)
Any contributions welcome as usual _(I should stop mentioning this everywhere)_**

A game can automatically be started using the debugger gdb [gdb](https://www.sourceware.org/gdb/)
either by enabling "Debug with gdb" in the [Game Menu](https://github.com/frostworx/steamtinkerlaunch/wiki/Game-Menu)/[Game Config](https://github.com/frostworx/steamtinkerlaunch/wiki/Configuration-Files#Game-Config) or by simply putting the game into the "GDB" [Steam Category](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Categories).

The terminal used for gdb _(`USETERM`)_ and its default command line option to directly start a command _(`TERMARGS`)_
need to be set by the user in the [Global Menu](https://github.com/frostworx/steamtinkerlaunch/wiki/Global-Menu)/[Global Config](https://github.com/frostworx/steamtinkerlaunch/wiki/Configuration-Files#Global-Config)

The default values are 
- USETERM="xterm" _(likely the terminal emulator which is available on most systems)_
- TERMARGS="-e" _(should be valid for most terminal emulators)_

## Special thanks
The [initial feature request](https://github.com/frostworx/steamtinkerlaunch/issues/378) was support for [protongdb](https://github.com/Joshua-Ashton/protongdb) by [Joshua-Ashton](https://github.com/Joshua-Ashton).
I [decided](https://github.com/frostworx/steamtinkerlaunch/issues/378#issuecomment-995914993) to not use it directly, but it helped a lot to get all bits and pieces together.
The [helper function](https://gist.githubusercontent.com/rbernon/cdbdc1b0e892f91e7449fcf3dda80bb7/raw/d8cf549bf751d99ed0fe515e36f99ff5c01b7287/WineReload.py) by [rbernon](https://github.com/rbernon)
used in protongdb is used in **steamtinkerlaunch** as well, so thanks to both authors here!

**Comment by frostworx** [comment]
I just pushed the initial gdb support with [this commit](https://github.com/frostworx/steamtinkerlaunch/commit/78de21111595d6109290044b757a870062d05604)
and updated [the wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Gdb-Support) accordingly. have fun!

**Comment by zany130** [comment]
so just tried it out a couple of things.

1. it wasn't launching with Konsole (KDE Terminal) until I installed xterm for some reason don't know why (didn't have xterm on my system) so maybe making xterm at least an optional dependcy in the aur package might be nice (don't know if you already did that though EDIT: don't see it also I don't know if gdb is included by default on most distros but I think it would be pretty obvious that  it is needed for this function :smile: )

2. If used in combination with game mode, the game is not launched with game mode which is strange here is a log
[Trails of Cold Steel.log](https://github.com/frostworx/steamtinkerlaunch/files/7741831/Trails.of.Cold.Steel.log) (long-ass game about to finish lol)

like you said this is a low priority feature so if it is too difficult to solve maybe just making a note on the wiki would be enough for now? I'll test with protongdb script to see if the same issue is there as I feel like it might be

**Comment by frostworx** [comment]
1) I don't use kde, no idea which arguments are required for konsole to immediately start a bash script
I'll add gdb in the pkgbuild as optdepend for sure, but not a bunch of terminals - yes, maybe xterm - no idea
2) this was intended as I see no reason to start anything besides the game and it would have bloated the code anyway

The feature is not really difficult to add _(see the commit)_, but the general functionality seems to be a bit hacky.
I don't think I will expand the README again, but please don't hesitate to enhance it.

**Comment by zany130** [comment]
1. Yeah agreed not a good idea to mark different terminals as a optional dep just maybe xterm as that would be one of the ones that is most likely installed anyway and compatible

2. Makes sense the main use case for this would be debugging some crash or issue  so normally you would want to run a vanilla as possible. I was running game mode as i use it to setup my displays  for gaming. Most people wouldn't need this though.

Anyway i think this can be closed now as gdb was implemented and is working
