### ISSUE TITLE
Two more SBS games

### ISSUE THREAD

**Issue by bo3b** [sonic2kk/steamtinkerlaunch#379]
Sorry if this is a bad approach, but I use your SBS list of games as the definitive list for anyone using 3D.  And thought you might like to add two more games to your Wiki: https://github.com/frostworx/steamtinkerlaunch/wiki/Side-by-Side-VR

Avatar 
Elite Dangerous

Both have built in SBS renders, and should work in Linux as well.

**Comment by frostworx** [comment]
Thanks for the suggestion, @bo3b! Nice to see you here!
Just added both titles to the wiki, and now I want Avatar! ;(
