### ISSUE TITLE
Check for game child processes

### ISSUE THREAD

**Issue by MithicSpirit** [sonic2kk/steamtinkerlaunch#381]
Some games fork & exit when launched (e.g. Warframe), which makes stl think that it has closed and makes it prematurely open the window asking if I would like to restart the game with different settings. I think that the best way to fix this would be to wait on all of the child processes of the game to exit before considering it to be closed (though I am not sure how to implement this).

**Comment by frostworx** [comment]
Yeah, I'm not sure as well how to best implement this _(without breaking other things)_
I already have some functions which help here, but as you noticed, some games still get though anyway.
I probably won't find the time to look deeper into this, so I can only suggest to simply disable the "restart" requester for those few games by choosing `DON'T ASK AGAIN`

**Comment by frostworx** [comment]
¯\_(ツ)_/¯
