### ISSUE TITLE
[BUG] ReShade Enable/Disable is Broken

### ISSUE THREAD

**Issue by Arcitec** [sonic2kk/steamtinkerlaunch#382]
Hi frostworx,

This is one of the coolest projects I have ever seen, thank you so freaking much for creating it! :)

I noticed that the ReShade enable/disable code is broken. I have currently unchecked all ReShade options for the game (no enable, no install, no update). However, ReShade still loads in the game.

I figured out the reason:

```
 data                   'NieR Replicant ver.1.22474487139.exe'
 BloomingHDR.fx          Overwatch.fxh
 check-steam_appid.txt   ReShade.ini
 d3d9.dll_disabled       ReShade.ini_disabled
 d3dcompiler_47.dll      ReShade-steamtinkerlaunch-disabled.txt
 dxgi.dll                steam_api64.dll
 dxgi.log
```

1. I have both `ReShade.ini` and `ReShade.ini_disabled`. I assume the `ReShade.ini` was auto-created due to the fact that ReShade is not properly disabled by SteamTinkerLaunch.
2. The real issue is that I have `d3d9.dll_disabled` AND `dxgi.dll`.

So SteamTinkerLaunch disables the DirectX 9 API dll (d3d9), but leaves the DirectX 11 API dll (dxgi). Therefore, ReShade is not disabled. (Deleting or renaming `dxgi.dll` manually properly disabled ReShade for me.)

I had a look at the code briefly, and I can see that it assumes that there's only 1 ReShade DLL, and I guess it thinks d3d9 is the one. This needs to be capable of renaming every DirectX version DLL that ReShade uses. :)

Is there any extra info that I should provide?

Edit: I'm on the latest Git Master version of steamtinkerlaunch by the way.

Edit: The contents of `ReShade-steamtinkerlaunch-enabled.txt` is a single line saying `d3d9.dll`, which confirms that SteamTinkerLaunch is misdetecting which DLL is used, and is only disabling one of the DLLs. This needs refactoring to enable/disable every ReShade DLL at the same time.

**Comment by frostworx** [comment]
Hehe, thanks a lot for the feedback! Very appreciated! :)
I hope you don't mind that I'll close this issue here and just point to it from the ReShade overhaul issue #383.
_(I simply like an easy overview over open issues)_

**Comment by Arcitec** [comment]
@frostworx Hey thanks a lot, sounds good to me! :)
