### ISSUE TITLE
[TEST?] Support NVIDIA DLSS and Raytracing

### ISSUE THREAD

**Issue by Arcitec** [sonic2kk/steamtinkerlaunch#384]
Proton recently added support for DLSS and RayTracing, but it needs to be enabled game-by-game with some environment variables, described at the official Proton page:

https://github.com/ValveSoftware/Proton/#runtime-config-options

And at the VKD3D (DX12 to Vulkan) project:

https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.5

- To enable DLSS: Environment `PROTON_ENABLE_NVAPI=1` (article: https://www.phoronix.com/scan.php?page=news_item&px=Proton-6.3-7-Plus-DLSS-Exp)
- To enable raytracing: Environment `VKD3D_CONFIG=dxr11` for DXR 1.1 or `VKD3D_CONFIG=dxr` for DXR 1.0, and some games also need a `-dx12` or similar launch flag to force the game itself to run as DX12 (examples: https://www.protondb.com/app/870780)

Proposed GUI:

- Per-game settings: "NVIDIA" section: "Enable NVAPI (DLSS)" checkbox.
- Per-game settings: "DirectX12 Raytracing" section: Version dropdown, with None (default), DXR 1.0, DXR 1.1.
- I am unsure how to implement the optional launch flags that some games need (such as Control's `-dx12` flag for raytracing).

The raytracing is a universal feature that should work with AMD cards too. DLSS/NVAPI is only for NVIDIA.

Edit: As you can see in the vkd3d-proton release notes I linked to above, they're planning to remove the `VKD3D_CONFIG=dxr` flag in the future, and only `VKD3D_CONFIG=dxr11` OR something entirely different will be required for enabling both DXR 1.0 and 1.1. But that day isn't here yet, so in the meantime, both variable values exist.

**Comment by frostworx** [comment]
Personally I do not care for that option, but of course would accept a proper PR.

**Comment by Continous** [comment]
I don't think this is necessary given that NVAPI already has a toggle box, and that vkd3d has the DXR options as a stop-gap solution while they are in active development.

**Comment by Arcitec** [comment]
@Continous I read carefully through the Game Config page now, and I see it!

### Regarding DLSS/NVAPI:

- `Proton NVAPI`. Checking the source code, I see that this setting enables `PROTON_ENABLE_NVAPI=1` environment variable. This tells Proton to load the [DXVK-NVAPI](https://github.com/jp7677/dxvk-nvapi) DLL file.
- More steps are needed. This is not enough. ;-) See https://github.com/jp7677/dxvk-nvapi#proton.
- `PROTON_HIDE_NVIDIA_GPU=0` is required, otherwise Proton will pretend that you have an AMD GPU which means NVAPI is still not used.
- The game itself needs a dxvk.conf with this content: `dxgi.nvapiHack = False`, which tells DXVK to expose the real NVAPI.dll (the one from DXVK-NVAPI project) instead of a fake/dummy one.
- So to sum it up, SteamTinkerLaunch needs to *also* add `PROTON_HIDE_NVIDIA_GPU=0` when "Proton NVAPI" is enabled in the GUI. And the actual player/user needs to create a dxvk.conf in the game directory and set `dxgi.nvapiHack = False`.

### Regarding game arguments such as "-dx12":

- Looks like it's already doable via the "Use custom command" checkbox and the "Custom command arguments: `-dx12`". Great!

### Regarding VKD3D-Proton's DXR Raytracing:

- First of all, this isn't just NVIDIA code. It's the generic DirectX 12 DXR Raytracing which works on both AMD and NVIDIA. So it's of interest to every gamer except Intel users.
- The DXR 1.0 code seems stable, but has some issues. When it's mature (maybe 1 year from now), they will enable it by default.
- The DXR 1.1 code is not mature at all and will take 2-3 years from now.
- In the meantime there needs to be a way to enable "DirectX 12 DXR Raytracing: None/1.0/1.1" in the STL GUI. Otherwise there's no way for people to play with raytracing yet.
- Raytracing is stable in a lot of games now, and the work is ongoing. So the feature matters.

I have had many deep looks in steamtinkerlaunch's file and in the commit history (to see how features are added) but it confuses the heck out of me, it's a massive file. If it was more approachable I would implement it... :(

**Comment by frostworx** [comment]
Good research job @Bananaman!
I'll see what I can do to help with implementing it - looking at your summary it looks pretty simple.
Can't tell when I find the time and I'm also not too motivated on working on steamtinkerlaunch currently tbh.
I think though, that implementing DLSS is more fun than refactoring ReShade, so I might start with this one.

Btw, custom command (and arguments) is only required if you want to start a different executable (instead/besides/before/after) the actual game exe. But you can of course also append custom command line options to your regular game exe as well.

**Comment by frostworx** [comment]
When
- `PROTON_ENABLE_NVAPI=1`
- `PROTON_HIDE_NVIDIA_GPU=0`
- a `dxvk.conf` with `dxgi.nvapiHack = False`
- (optionally a `-dx12` command line argument)
is everything to get this working, it will probably be ready quickly.

All of above could be even configured automatically, by flipping a _(to be added)_ `USE_DLSS` option, which in turn could be enabled by simply dropping the corresponding game into a DLSS steam category

steamtinkerlaunch already has support for a `dxvk.conf` per game:
When a game config is created the commented out option
`#STLDXVKCFG="~/.config/steamtinkerlaunch/dxvk/$SteamAppID.conf"`
is added automatically.
If this line is commented in and the config file does exist, 
steamtinkerlaunch exports
`export DXVK_CONFIG_FILE="$STLDXVKCFG"`
so dxvk uses it automatically.

When enabling `USE_DLSS` it should be enough to export the variable to a _(bundled)_ dxvk.conf_
with `dxgi.nvapiHack = False`
_(appending the option to an existing config when DXVK_CONFIG_FILE is already set might be a bonus option, though  messing with external config files should not be default then at least)_

**Comment by frostworx** [comment]
[added](https://github.com/frostworx/steamtinkerlaunch/commit/ed6ae7a3aa34e6c3bd9fe33c6811c95442387420) Proton hide Nvidia GPU option

**Comment by frostworx** [comment]
[ more changes for DLSS ](https://github.com/frostworx/steamtinkerlaunch/commit/43f42ff6a2860b6024cd427a65929f00be6648fc)

- added per game option USEDLSS
- added dxvk-no-nvapiHack.conf
- added DLSS steam category config
- with enabled USEDLSS:
  - export DXVK_CONFIG_FILE="$DXDLSSCFG"
  - export PROTON_ENABLE_NVAPI=1
  - export PROTON_HIDE_NVIDIA_GPU=0

Totally untested

**Comment by frostworx** [comment]
Of course the current DLSS implementation should be tested, ideally by several interested nvidia people.

The [vkd3d-proton options](https://github.com/frostworx/steamtinkerlaunch/issues/386) are already mostly implemented offline, including a `USERAYTRACING` option which both sets
`VKD3D_CONFIG=dxr11` and also appends "-dx12" to the game command line.
Also added a "Raytracing" [Steam Category](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Categories) config.

**Comment by frostworx** [comment]
upcoming wikis:

# [DLSS](https://github.com/frostworx/steamtinkerlaunch/wiki/DLSS)

By enabling `USEDLSS` in the [Game Menu](https://github.com/frostworx/steamtinkerlaunch/wiki/Game-Menu)/[Game Config](https://github.com/frostworx/steamtinkerlaunch/wiki/Configuration-Files#Game-Config)
or by simply putting the game into the "DLSS" [Steam Category](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Categories)
all options required for DLSS are enabled automatically.

- the bundled `/usr/share/steamtinkerlaunch/misc/dxvk-no-nvapiHack.conf`, which sets `dxgi.nvapiHack = False`
  is loaded automatically by DXVK, by pointing the `DXVK_CONFIG_FILE` to it
- sets `PROTON_ENABLE_NVAPI=1`
- sets `PROTON_HIDE_NVIDIA_GPU=0`

Also check [Raytracing](https://github.com/frostworx/steamtinkerlaunch/wiki/Raytracing) _(works on Nvidia and AMD)_


###########

# [Raytracing](https://github.com/frostworx/steamtinkerlaunch/wiki/Raytracing)

By enabling `USERAYTRACING` in the [Game Menu](https://github.com/frostworx/steamtinkerlaunch/wiki/Game-Menu)/[Game Config](https://github.com/frostworx/steamtinkerlaunch/wiki/Configuration-Files#Game-Config)
or by simply putting the game into the "Raytracing" [Steam Category](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Categories)
all options required for Raytracing are enabled automatically.

- sets `VKD3D_CONFIG=dxr11`
- `-dx12` is appended automatically to the game command line arguments

Also check Nvidia-only [DLSS](https://github.com/frostworx/steamtinkerlaunch/wiki/DLSS)


############

# [Vkd3d](https://github.com/frostworx/steamtinkerlaunch/wiki/Vkd3d)

**steamtinkerlaunch** offers all_(?)_ possible [vkd3d-proton options](https://github.com/HansKristian-Work/vkd3d-proton#environment-variables) in the
[Game Menu](https://github.com/frostworx/steamtinkerlaunch/wiki/Game-Menu)/[Game Config](https://github.com/frostworx/steamtinkerlaunch/wiki/Configuration-Files#Game-Config)

A [Category Menu](https://github.com/frostworx/steamtinkerlaunch/wiki/Category-Menus) is available as well

Also check related [Raytracing](https://github.com/frostworx/steamtinkerlaunch/wiki/Raytracing) _(works on Nvidia and AMD)_

**Comment by Arcitec** [comment]
Hey man! :) That's great progress, wow!

> [added](https://github.com/frostworx/steamtinkerlaunch/commit/ed6ae7a3aa34e6c3bd9fe33c6811c95442387420) Proton hide Nvidia GPU option

This should default to 1 (hide) because that's the Proton default. Masking NVIDIA as AMD is the default Wine/Proton setting, to prevent bugs in games that try to use NVIDIA features (mainly NVAPI I think).

So "unhide NVIDIA" should only be done by people who also have enabled NVAPI/DLSS.

Therefore it's important that hiding is done by default, and that unhiding is automatically tied to the "Enable DLSS" option in Steamtinkerlaunch.

> more changes for DLSS

All of that looks totally awesome! The new `USEDLSS` feature does everything correct, even dxvk config! :)

> The vkd3d-proton options are already mostly implemented offline, including a USERAYTRACING option which both sets
VKD3D_CONFIG=dxr11 and also appends "-dx12" to the game command line.

I will help test this. But `-dx12` is a per-game thing that comes from the game Control. It's not universal for all games. So I don't know if we wanna automate that flag since some games may complain that it's an unknown flag?

> wiki

Loooooooks awesooooooooome! :) The `-dx12` is still the only thing that may not be right.

**Comment by frostworx** [comment]
Thanks for the feedback! Of course you're right with the Nvidia GPU default flag - I was in a hurry :)
Will push the new default with the vkd3d stuff _(likely tomorrow)_

I wondered the same regarding the `-dx12` flag, but I doubt that it has a negative effect for games which do not have that option.
If it does, it can still be removed _(which would render the `USERAYTRACING` pretty much useless, though :))_

**Comment by Arcitec** [comment]
@frostworx Sounds great. I will help you test it when that commit is ready. :)

About `-dx12`, I guess it's harmless, most games just ignore unknown flags. We could do it and then if someone complains in the future that the flag causes a launch error in some game, we'll know then. ^^

I agree that adding the flag is kinda nice because it automates it for games that use that flag. :)

**Comment by frostworx** [comment]
Just gave it a very quick try with Control.
vkd3d variable and dx12 command line are auto applied correctly, but the game crashes with enabled raytracing.
`Radeon RX 6900 XT`, but the game has weak performance in 4k as well. ¯\_(ツ)_/¯
Anyway I think the implementation is ready so far.
More tomorrow _(probably)_ 👋

**Comment by frostworx** [comment]
[just landed](https://github.com/frostworx/steamtinkerlaunch/commit/63d99cfd975c49000b2078eac02034dc8eb9e8f5)
happy testing

**Comment by frostworx** [comment]
Should be more or less functional with above commit.
Possible that not all functions do work 100% correctly yet,
but I assume this state will make it more or less into next and foreseeable last release.

**Comment by frostworx** [comment]
@Bananaman 👍

**Comment by frostworx** [comment]
When nobody is willing to give any feedback on the rewrite, I silently assume it is either fully functional or nobody uses it at all.
Either way I'm going to make a new release soon.

**Comment by Arcitec** [comment]
I am ashamed that I didn't see your message. I'm sorry. I have to download games to test.

# First test: Use DLSS.

Game: No Man's Sky. DirectX11, only DLSS.


The STL code looks good. I don't know why it aborts the "use DLSS" envs if a "STLDXVKCFG" config exists and points to a file, but I guess it's a bypass that advanced users can use.

```sh
		# export DXVK_CONFIG_FILE if STLDXVKCFG was found or if USEDLSS is enabled:
		DXDLSSCFG="$GLOBALMISCDIR/dxvk-no-nvapiHack.conf"

		if [ -f "$STLDXVKCFG" ]; then
			export DXVK_CONFIG_FILE="$STLDXVKCFG"
		elif [ "$USEDLSS" -eq 1 ] && [ -f "$DXDLSSCFG" ]; then
			writelog "INFO" "${FUNCNAME[0]} - DLSS is enabled and '$DXDLSSCFG' was found - enabling all options required for DLSS"
			export DXVK_CONFIG_FILE="$DXDLSSCFG"
			export PROTON_ENABLE_NVAPI=1
			export PROTON_HIDE_NVIDIA_GPU=0
		fi
```

Anyway game result:

- Without setting anything in SteamTinkerLaunch: I do not see DLSS in game.
- Enabled "Use DLSS" checkbox (I didn't enable "Use NVAPI"): DLSS is visible in the game and I can use it. I confirm that it works. When I set it to lowest quality I got a very blurry image, and when I set it to max quality I got a sharp image.


I will try to get one of the supported raytracing games next.

**Comment by frostworx** [comment]
Thank you very much for picking this up again and for testing!
I seriously wondered where the problem was, because you did not respond anymore after the initial excellent reports :)

**Comment by frostworx** [comment]
regarding the STLDXVKCFG, as "dxgi.nvapiHack = False" is required for DLSS _(at least as far I understood)_
I preferred not to force-enable it in the $STLDXVKCFG.

**Comment by Arcitec** [comment]
Yeah I have just beeen sick a lot around christmas and forgot.

# Second test: DXR Raytracing.

To test raytracing I'm using the Ghostrunner Demo. Started in Steam as "Play with DirectX 12 (RTX)".

- Without setting anything in SteamTinkerLaunch: DLSS is grayed out in the game. The RTX switch is visible and can be set to On but doesn't seem to do anything (the reflections are fake, just reflecting the environment map, nothing else).
- Enabling "USE RAYTRACING" in STL: DLSS still not possible to enable (because NVAPI is not enabled), this is to be expected. And RTX raytracing is definitely being enabled in VKD3D but the game crashed as soon as I started New Game.
- Enabling RAYTRACING and DLSS: I can now see DLSS options in the game. Game still crashes.
- To check if `export VKD3D_CONFIG=dxr` works better than `export VKD3D_CONFIG=dxr11`, I edited the STL binary (script) and made this change: No difference.

Conclusions:

1. STL is doing the right thing.
2. There doesn't seem to be a reason to use "dxr" instead of "dxr11".
3. I don't have any of the games listed as supported in VKD3D. It's clearly gonna work if I had a supported game. Because I can see that it's trying to use raytracing.
4. DLSS/NVAPI is a separate feature, which is unrelated to raytracing and can be enabled/disabled separately. This is correct. Because both AMD and NVIDIA support DXR.
5. Your raytracing feature is complete.

PS: It was hard to find "use raytracing" checkbox because the option menu lacks the text for some reason and I had to hover over this empty box to find it:

![image](https://user-images.githubusercontent.com/38923130/149368980-6e0478de-e588-463a-9d8e-d6a24b4fbdd9.png)

**Comment by Arcitec** [comment]
> regarding the STLDXVKCFG, as "dxgi.nvapiHack = False" is required for DLSS _(at least as far I understood)_ I preferred not to force-enable it in the $STLDXVKCFG.

Yeah that's right, that config file is required for DLSS. Although it seems that's only for DX9/10/11 (DXVK). For DX12, the VKD3D dll is used instead, which seems to have its own DLSS handling that uses the same environment variables as DXVK but doesn't need the conf file. Either way your solution there is fine!

And this ticket is ready to close. The checkbox text label is missing, no other issues here. DLSS and DXR settings work. Thanks a lot, this is awesome! :)

**Comment by frostworx** [comment]
Wow, thank you very much for your excellent testing! I wished you had found steamtinkerlaunch eariler ;)

**Comment by frostworx** [comment]
I'll check the empty string - probably a typo somewhere. Thanks for heads-up!

**Comment by frostworx** [comment]
hehe, `GUI_USERAYTRACING` and `DESC_USERAYTRACING` are simply completely missing in the translations... :)

**Comment by frostworx** [comment]
Added missing translations with https://github.com/frostworx/steamtinkerlaunch/commit/a43633d2e1ed61f1e043cabb998c604eb38176aa
Thanks again, very appreciated!

**Comment by Arcitec** [comment]
> Wow, thank you very much for your excellent testing! I wished you had found steamtinkerlaunch eariler ;)

:O Aw thanks so much. Sorry again that I didn't see the updates earlier. I will test #383 next.
