### ISSUE TITLE
Autoupdate yad system path, when yad was moved

### ISSUE THREAD

**Issue by ghost** [sonic2kk/steamtinkerlaunch#388]
I've tried my best to diagnose the issue myself but I'm stuck. Opening it in a text editor and going to line 4806 shows something to do with $YAD but no matter what path I give it with exporting it doesn't seem to recognize the command. 
I followed the yad installation instruction to a T and it's in /usr/local/bin and version 10.90
Why is it complaining?

**Comment by ghost** [comment]
Not a minute later I find the "steamtinkerlaunch yad" command. But yeah, maybe add that to the documentation since it seeems to always happen with Ubuntu, even after restarting so that environment variables update.

**Comment by frostworx** [comment]
log and exact steamtinkerlaunch version would have been nice.
edit: also https://github.com/frostworx/steamtinkerlaunch/wiki/Yad#custom-yad
and almost certain this is a local setup problem _(f.e. `/usr/local/bin/` in `$PATH`?)_

**Comment by ghost** [comment]
> log and exact steamtinkerlaunch version would have been nice. edit: also https://github.com/frostworx/steamtinkerlaunch/wiki/Yad#custom-yad and almost certain this is a local setup problem _(f.e. `/usr/local/bin/` in `$PATH`?)_

Sorry for the lack of logs. Had to deal with a lot of dependency installation and was a lil tired. Essentially, it *only* worked if I specified the path via steamtinkerlaunch itself. /usr/local/bin is in my path already, but steamtinkerlaunch only recognized it when I specified it via the "steamtinkerlaunch yad" command.

**Comment by frostworx** [comment]
The initial default `yad` path is defined as `command -v "yad"` and is written into the `global.conf` as variable `$YAD`
If that variable is **empty**, there is also a 2nd attempt, which tries to find it again - this should be more than enough in almost all constellations, but I'm very sure you had the following problem:

You installed the ancient `yad` version coming from your package management, and therefore it was found in `/usr/bin/yad`.
That path was stored in the `global.conf`
You recognized then, that this `yad` version is too old, uninstalled it, manually compiled `yad` and installed it into `/usr/local/bin/`
`command -v "yad"` now would point correctly to `/usr/local/bin/yad`, but your `global.conf` still has the previous `/usr/bin/yad`, which does no longer exist.
Removing the `global.conf` completely or fixing the old path would have fixed that.
Please confirm if this or a similar scenario could have been the cause of your issue.

I guess this is a very rare issue, but I could add another check, to see if an already configured path is still valid or needs an update, so **reopening**

**Comment by frostworx** [comment]
This [giant commit](https://github.com/frostworx/steamtinkerlaunch/commit/29b736e97bb5d6f2f49a9becd59b1e83c649b4c0)
also contains an additional check for above scenario.

**Comment by ghost** [comment]
> The initial default `yad` path is defined as `command -v "yad"` and is written into the `global.conf` as variable `$YAD` If that variable is **empty**, there is also a 2nd attempt, which tries to find it again - this should be more than enough in almost all constellations, but I'm very sure you had the following problem:
> 
> You installed the ancient `yad` version coming from your package management, and therefore it was found in `/usr/bin/yad`. That path was stored in the `global.conf` You recognized then, that this `yad` version is too old, uninstalled it, manually compiled `yad` and installed it into `/usr/local/bin/` `command -v "yad"` now would point correctly to `/usr/local/bin/yad`, but your `global.conf` still has the previous `/usr/bin/yad`, which does no longer exist. Removing the `global.conf` completely or fixing the old path would have fixed that. Please confirm if this or a similar scenario could have been the cause of your issue.
> 
> I guess this is a very rare issue, but I could add another check, to see if an already configured path is still valid or needs an update, so **reopening**

That seems to have been the issue.
