### ISSUE TITLE
listAppManifests breaks when Steam Library contains spaces

### ISSUE THREAD

**Issue by MattSturgeon** [sonic2kk/steamtinkerlaunch#389]
The wiki says that stl will do the following when starting vortex:

> create and update symlinks for all found game config directories of all found games in the SteamUser directory

Can you clarify how this is supposed to work, as I have to manually symlink `My Games` and `%LOCALAPPDATA%`  to get bethesda games to work. I'm assuming either I'm doing something wrong in my setup or the _“create and update symlinks”_ feature is incomplete?

#### Expected behaviour

I would expect that running `steamtinkerlaunch vortex start` would scan the installed games to see which are compatible with vortex and create the necessary links from vortex's WINEPREFIX to the relevant game(s) WINEPREFIX(s).

Perhaps the wiki note referrs to _other_ symlinks 

----

I have the following symlinks on my system (all manually created):

```
    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Local/FalloutNV
 -> ~/.config/steamtinkerlaunch/compatdata/Fallout New Vegas/pfx/drive_c/users/steamuser/Local Settings/Application Data/FalloutNV

    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Fallout4
 -> ~/.config/steamtinkerlaunch/compatdata/Fallout 4/pfx/drive_c/users/steamuser/Local Settings/Application Data/Fallout4

    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Skyrim Special Edition
 -> ~/.config/steamtinkerlaunch/compatdata/Skyrim Special Edition/pfx/drive_c/users/steamuser/Local Settings/Application Data/Skyrim Special Edition/

    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/Documents/My Games/FalloutNV
 -> ~/.config/steamtinkerlaunch/compatdata/Fallout New Vegas/pfx/drive_c/users/steamuser/My Documents/My Games/FalloutNV

    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/Documents/My Games/Fallout4
 -> ~/.config/steamtinkerlaunch/compatdata/Fallout 4/pfx/drive_c/users/steamuser/My Documents/My Games/Fallout4

    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/Documents/My Games/Skyrim Special Edition
 -> ~/.config/steamtinkerlaunch/compatdata/Skyrim Special Edition/pfx/drive_c/users/steamuser/My Documents/My Games/Skyrim Special Edition/
```

(Well, actually I just link `My Games` to `~/Games` in all my WINEPREFIXes, but it's effectively the same, I still link all the APPDATA directories as above, for now):

```
    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/Documents/My Games
 -> ~/Games

```

Additional screenshot for reference:

![Vortex Symlinks](https://user-images.githubusercontent.com/5046562/147420312-f9529ca8-c554-4ddb-bb4c-d564d72c14ca.png)

----

#### Sidenote

I noticed that Steam uses `Local Settings/Application Data` while stl/vortex uses `AppData/Local`. 
Also, Steam uses `My Documents/My Games` while stl/vortex uses `Documents/My Games`...
I'm guessing that each WINEPREFIX may have been initially created using different proton versions/configs? It doesn't seem to have caused an issue anyhow, just pointing out that they aren't using the same directory structure.

**Comment by frostworx** [comment]
For me everything worked fine, so I need to re-check that.
Regarding the Sidenode, some months back multiple paths were merged and symlinked in wine/proton _(it was recommended to create new wineprefixes)_. Can't remember which paths changed, but very likely this is related.

**Comment by frostworx** [comment]
Haven't re-tested it yet, but steamtinkerlaunch indeed symlinks "all" _(assuming)_ required dirs and files inside the steamuser dir from vortex-compatible wineprefixes to the corresponding path in the vortex wineprefix. This worked fine with all my tests previously. As stated above, proton changed several paths, so please retest with a clean game wineprefix.
`steamtinkerlaunch` does not symlink anything to `~/Games` (and tbh I do not understand the reason for what this should be good for)

**Comment by frostworx** [comment]
Just retested completely from scratch without configuring anything _(`~/.config/steamtinkerlaunch` initially did not even exist)_
$ `steamtinkerlaunch vortex start`
installed everything correctly, ~28 installed games, including multiple bethesda games were autodetected
and all symlinks were set as expected:

![vortex-syms](https://user-images.githubusercontent.com/8840590/147469431-7d27c258-81b3-4aff-b470-38304d3daff2.jpg)

**Comment by MattSturgeon** [comment]
That's helpful. I'll have to try and identify what edge case I have in my setup then.

My first guess would be having created some of my own symlinks (either in the game compatdata or in vortex's) might be breaking something 🤔

I've already tested with brand new game installs (at least for 2/3 games) but if it is caused by an old vortex WINEPREFIX I'll see if I can identify the issue. Asking users to wipe that WINEPREFIX without an easy way to backup their vortex settings and mod lists would be a bit of a pain!

**Comment by frostworx** [comment]
what do you suggest then? stick with old proton/wine versions which did not refactor the paths?

**Comment by MattSturgeon** [comment]
> what do you suggest then? stick with old proton/wine versions which did not refactor the paths?

Well, in my case I don't think my vortex WINEPREFIX has ever migrated from one wine version to another. So I'm don't think this is the issue.

Looking into the issue, the first thing I've found is that supported games are not being found at all. Also, the `list-installed` command is throwing an error (rather than printing `no games found` or whatever):

```
$ steamtinkerlaunch vortex list-supported
Mon 27 Dec 12:53:28 GMT 2021 INFO - commandline - Games With Vortex Support found in the Vortex installation:

$ steamtinkerlaunch vortex list-installed
;A Game ID is required as argument

$ steamtinkerlaunch vortex reset
Mon 27 Dec 13:00:40 GMT 2021 INFO - prepareAllInstalledVortexGames - Preparing all installed games supported by Vortex
Mon 27 Dec 13:00:40 GMT 2021 SKIP - prepareVortexGame - Skip game '' is not supported by Vortex or the ID is not listed in '/usr/share/steamtinkerlaunch/misc/vortexgames.txt'
Mon 27 Dec 13:00:40 GMT 2021 INFO - prepareAllInstalledVortexGames - Applying Vortex settings for all games via autogenerated cmd '/dev/shm/steamtinkerlaunch/vortset.cmd'
Mon 27 Dec 13:00:44 GMT 2021 INFO - prepareAllInstalledVortexGames - Symlinks, registry entries and vortex settings for all found supported games should be ready at this point for Vortex
Mon 27 Dec 13:00:46 GMT 2021 INFO - resetVortexSettings - Diff between Vortex settings before and after reset:
```

However, `list-owned` & `list-online` work as expected:

```
$ steamtinkerlaunch vortex list-owned
Mon 27 Dec 13:06:37 GMT 2021 INFO - commandline - Games owned with Vortex Support:
"newvegas";"Fallout New Vegas";"22380"
"kotor2";"Knights of the Old Republic II";"208580"
"payday2";"Payday 2";"218620"
"prisonarchitect";"Prison Architect";"233450"
"citiesskylines";"Cities: Skylines";"255710"
"gta5";"Grand Theft Auto V";"271590"
"fallout4";"Fallout 4";"377160"
"skyrimspecialedition";"Skyrim Special Edition";"489830"
```

It seems that a couple variables are unset when running `getVortexSupported`, leading to unprefixed paths:

```
VORTEXINSTDIR=
RABP=resources/app.asar.unpacked/bundledPlugins
VORTEXPFX=
DRCU=drive_c/users
STUS=steamuser
APDA=Application Data
VGPDIR=/resources/app.asar.unpacked/bundledPlugins
VUPDIR=/drive_c/users/steamuser/Application Data/Vortex/plugins
```

EDIT: testing now if I can reproduce any of this with a clean `~/.config/steamtinkerlaunch`

**Comment by MattSturgeon** [comment]
Running `steamtinkerlaunch vortex start` after moving/removing `~/.config/steamtinkerlaunch` seems to go ok... Vortex launches and various games are shown as "available" under the Games tab:

```
$ steamtinkerlaunch vortex start
Mon 27 Dec 13:19:51 GMT 2021 INFO - setDotNetWine - Downloading: 'https://github.com/frostworx/steamtinkerlaunch-tweaks/releases/download/Proton-6.17-STL-1/Proton-6.17-STL-1.tar.gz'
wine: created the configuration directory '/home/matt/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/share/default_pfx'
wineserver: using server-side synchronization.

(wine:20590): GStreamer-WARNING **: 13:20:34.765: Failed to load plugin '/home/matt/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/lib64/gstreamer-1.0/libprotonmediaconverter.so': /home/matt/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/lib64/gstreamer-1.0/libprotonmediaconverter.so: wrong ELF class: ELFCLASS64
wine: configuration in L"/home/matt/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/share/default_pfx" has been updated.
Proton: Upgrading prefix from None to 6.17-0 (/home/matt/.config/steamtinkerlaunch/vortex/compatdata/)
esync: up and running.
SSL_INIT
wineserver: using server-side synchronization.
wineserver: using server-side synchronization.
wineserver: using server-side synchronization.
wineserver: using server-side synchronization.
Mon 27 Dec 13:23:11 GMT 2021 INFO - startVortex - Starting Vortex without options
```

![vortex](https://user-images.githubusercontent.com/5046562/147476363-888a0cf3-ff02-4378-b23b-514017ebfc12.png)

#### However

Symlinks don't appear to have been generated correctly:

![symlinks](https://user-images.githubusercontent.com/5046562/147476174-086412f9-cbcc-4871-b420-b508c0a59a0f.png)

`list-supported` and `list-installed` still behave the same:

```
$ steamtinkerlaunch vortex list-installed
;A Game ID is required as argument
$ steamtinkerlaunch vortex list-supported
Mon 27 Dec 13:31:23 GMT 2021 INFO - commandline - Games With Vortex Support found in the Vortex installation:

# Latest git with all logs going to stdout and a few additional echos:
$ ./steamtinkerlaunch vortex list-supported
Mon 27 Dec 13:31:30 GMT 2021 INFO - initAID - Set AID to PLACEHOLDERAID '31337'
Mon 27 Dec 13:31:30 GMT 2021 INFO - loadLangFile - Loading system wide /usr/share/steamtinkerlaunch/lang//english.txt
Mon 27 Dec 13:31:30 GMT 2021 INFO - getCurrentCommandline - No Proton in command line arguments 'vortex list-supported'
Mon 27 Dec 13:31:30 GMT 2021 INFO - saveOrgVars - Storing some original variables to restore them later
Mon 27 Dec 13:31:30 GMT 2021 INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
Mon 27 Dec 13:31:30 GMT 2021 INFO - emptyVars - Set $PATH to '/home/matt/.cache/zsh/zplugin/polaris/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/opt/android-sdk/build-tools/27.0.3:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/android-sdk/build-tools/27.0.3:/usr/lib/jvm/default/bin:'
Mon 27 Dec 13:31:30 GMT 2021 START - ######### Initializing Game Launch 31337 #########
Mon 27 Dec 13:31:30 GMT 2021 INFO - main - Starting with a clean log
Mon 27 Dec 13:31:30 GMT 2021 INFO - main - Start creating default configs
Mon 27 Dec 13:31:30 GMT 2021 INFO - createDefaultCfgs - START
Mon 27 Dec 13:31:30 GMT 2021 INFO - loadLanguage - First load the default language to make sure all variables are filled
Mon 27 Dec 13:31:30 GMT 2021 INFO - loadLangFile - Loading system wide /usr/share/steamtinkerlaunch/lang//english.txt
Mon 27 Dec 13:31:30 GMT 2021 SKIP - updateConfigFile - Config file '/home/matt/.config/steamtinkerlaunch/global.conf' already at version 'v8.1.20211223'
Mon 27 Dec 13:31:30 GMT 2021 INFO - createDefaultCfgs - setSteamPaths:
Mon 27 Dec 13:31:30 GMT 2021 INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
Mon 27 Dec 13:31:30 GMT 2021 SKIP - updateConfigFile - Config file '/home/matt/.config/steamtinkerlaunch/global.conf' already at version 'v8.1.20211223'
Mon 27 Dec 13:31:30 GMT 2021 SKIP - updateConfigFile - Config file '/home/matt/.config/steamtinkerlaunch/url.conf' already at version 'v8.1.20211223'
Mon 27 Dec 13:31:30 GMT 2021 INFO - getGameOS - Starting game OS detection
Mon 27 Dec 13:31:30 GMT 2021 INFO - getGameOS - STEAM_COMPAT_DATA_PATH is dot defined, so this is (very likely) either a Linux Game or no game was started at all
Mon 27 Dec 13:31:31 GMT 2021 SKIP - updateConfigFile - Config file '/home/matt/.config/steamtinkerlaunch/default_template.conf' already at version 'v8.1.20211223'
Mon 27 Dec 13:31:31 GMT 2021 INFO - listAllSettingsEntries - '/dev/shm/steamtinkerlaunch/setentries.txt' already exists - nothing to do
Mon 27 Dec 13:31:31 GMT 2021 INFO - createDefaultCfgs - STOP
Mon 27 Dec 13:31:31 GMT 2021 INFO - main - Checking internal dependencies:
Mon 27 Dec 13:31:31 GMT 2021 INFO - setAwkBin - Found 'gawk' as an 'awk' variant. It should work without any issues, because 'gawk' was tested completely
Mon 27 Dec 13:31:31 GMT 2021 INFO - main - Initializing first Proton:
Mon 27 Dec 13:31:31 GMT 2021 INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/steamtinkerlaunch/ProtonCSV.txt' which was created during a previous run
Mon 27 Dec 13:31:31 GMT 2021 INFO - initFirstProton - Initializing Proton
Mon 27 Dec 13:31:31 GMT 2021 INFO - initFirstProton - No Proton version available in template yet - searching for one
Mon 27 Dec 13:31:31 GMT 2021 INFO - initFirstProton - Updated 'USEPROTON' in '/home/matt/.config/steamtinkerlaunch/default_template.conf' to ''
Mon 27 Dec 13:31:31 GMT 2021 INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/matt/.config/steamtinkerlaunch/default_template.conf' is ''
Mon 27 Dec 13:31:31 GMT 2021 INFO - main - Initializing default window resolution
Mon 27 Dec 13:31:31 GMT 2021 INFO - setInitWinXY - Using '2880x1620' from config '/dev/shm/steamtinkerlaunch/defres.txt'
Mon 27 Dec 13:31:31 GMT 2021 INFO - main - Checking command line: incoming arguments 'vortex list-supported'
Mon 27 Dec 13:31:31 GMT 2021 INFO - commandline - Games With Vortex Support found in the Vortex installation:
Mon 27 Dec 13:31:31 GMT 2021 INFO - commandline - Games With Vortex Support found in the Vortex installation:
getVortexSupported
VORTEXINSTDIR=
RABP=resources/app.asar.unpacked/bundledPlugins
VORTEXPFX=
DRCU=drive_c/users
STUS=steamuser
APDA=Application Data
VGPDIR=/resources/app.asar.unpacked/bundledPlugins
VUPDIR=/drive_c/users/steamuser/Application Data/Vortex/plugins
gVSIDs - Directory not found: '/resources/app.asar.unpacked/bundledPlugins'
gVSIDs - Directory not found: '/drive_c/users/steamuser/Application Data/Vortex/plugins'

```

----

There's definitely something weird about my setup that stl doesn't like

**Comment by MattSturgeon** [comment]
Looks like `listAppManifests` might be the problem; it detects app manifests in the default steam library:

```
$ ./steamtinkerlaunch list appmanifests
/home/matt/.local/share/Steam/steamapps/appmanifest_7940.acf
/home/matt/.local/share/Steam/steamapps/appmanifest_228980.acf
/home/matt/.local/share/Steam/steamapps/appmanifest_7940.acf
/home/matt/.local/share/Steam/steamapps/appmanifest_228980.acf
```

but not those in custom steam libraries:

```
❯ ls ~/Games/Steam\ Library/steamapps
 appmanifest_1113280.acf   appmanifest_201700.acf   appmanifest_220.acf      appmanifest_224760.acf   appmanifest_234190.acf   appmanifest_255220.acf   appmanifest_282140.acf   appmanifest_319630.acf   appmanifest_377160.acf   appmanifest_409720.acf   appmanifest_489830.acf   appmanifest_70.acf     libraryfolders.vdf   workshop
 appmanifest_1245040.acf   appmanifest_203160.acf   appmanifest_221910.acf   appmanifest_225420.acf   appmanifest_239140.acf   appmanifest_255710.acf   appmanifest_286690.acf   appmanifest_337000.acf   appmanifest_380.acf      appmanifest_41070.acf    appmanifest_4920.acf     appmanifest_8870.acf  'Proton Prefixes'
 appmanifest_1391110.acf   appmanifest_206420.acf   appmanifest_223470.acf   appmanifest_231160.acf   appmanifest_242880.acf   appmanifest_255870.acf   appmanifest_287390.acf   appmanifest_340.acf      appmanifest_4000.acf     appmanifest_420.acf      appmanifest_550.acf      common                 shadercache
 appmanifest_1420170.acf   appmanifest_208580.acf   appmanifest_22380.acf    appmanifest_233450.acf   appmanifest_247750.acf   appmanifest_271590.acf   appmanifest_301910.acf   appmanifest_354240.acf   appmanifest_400.acf      appmanifest_440.acf      appmanifest_55230.acf    compatdata             sourcemods
 appmanifest_1580130.acf   appmanifest_218620.acf   appmanifest_224260.acf   appmanifest_233720.acf   appmanifest_250820.acf   appmanifest_282070.acf   appmanifest_310560.acf   appmanifest_362890.acf   appmanifest_409710.acf   appmanifest_487390.acf   appmanifest_620.acf      downloading            temp
```

This section of `listAppManifest` breaks when the steam library path contains spaces:

```bash
writelog "INFO" "${FUNCNAME[0]} - Searching appmanifest files in '$CFGVDF' and '$LFVDF'" "X" "$APPMALOG"
while read -r BIF; do
	  findAppMa "${BIF//\"/}/$SA"
done <<< "$(grep "BaseInstallFolder\|\"path\"" "$CFGVDF" "$LFVDF" 2>/dev/null | awk '{print $3}' | sort -u)"
```

The problem is the `awk '{print 3}'` part of this pipe `<<< "$(grep "BaseInstallFolder\|\"path\"" "$CFGVDF" "$LFVDF" 2>/dev/null | awk '{print $3}' | sort -u)"`...


awk is splitting

```
/home/matt/.local/share/Steam/config/config.vdf:                                "BaseInstallFolder_1"           "/data/lin/matt/Games/Steam Library"
```

into 4 records (space separated), so `"data/lin/matt/Games/Steam` and `Library"` are two separate records, `$3` and `$4` respectively

We could hack this by splitting on multiple spaces only, or by manually matching `"` characters, but both of these would lead to more edge cases if a path has multiple spaces or " characters within it... Ideally we want bash to evaluate the line and produce an array of strings but that doesn't sound ideal either....

**Comment by MattSturgeon** [comment]
A regex `"(BaseInstallFolder[^"]*|path)"\s+"(.*)"$` that prints group 2 `(.*)` would probably do the trick... I'll try and work on a PR later if you haven't beaten me to it.

**Comment by frostworx** [comment]
Very good diagnostics, thanks for reporting!
Shouldn't be a major problem to fix this properly and hope I'll find the time this year to fix it :)

**Comment by frostworx** [comment]
Replacing  `awk '{print $3}'` with `cut -d '"' -f4` seems to do the trick as well, but it might be a good idea, to explicitly log what it found, as this is a pretty weak point, apparently.

**Comment by MattSturgeon** [comment]
> Replacing `awk '{print $3}'` with `cut -d '"' -f4` seems to do the trick as well, but it might be a good idea, to explicitly log what it found, as this is a pretty weak point, apparently.

That should work, although the [`getBIF`](https://github.com/frostworx/steamtinkerlaunch/pull/391/files#diff-77c6d4bb1bf7c1988ff5a068c856b6c24e113663f2e61cb3a2c98723c0fafc04R1267) function in my PR should be more robust if it is possible for (escaped) `"` characters to be in the path... That said assuming the filesystem even supports `"` in file paths. I wasn't entirely sure if this is even supported at filesystem level, but:

```
$ mkdir testing\ \"123\"
$ ls testing* -d
'testing "123"'
```

I don't know how well steam would support this, but I don't see why we shouldn't try to?

**Comment by frostworx** [comment]
I'd prefer your `getBIF` function as well, that's why I haven't changed anything regarding this in this [giant commit](https://github.com/frostworx/steamtinkerlaunch/commit/29b736e97bb5d6f2f49a9becd59b1e83c649b4c0)
