### ISSUE TITLE
Proton-6.17-STL-1 depends on GLIBC_2.32 (lib32-glibc 2.33-5 on Arch)

### ISSUE THREAD

**Issue by benhighley** [sonic2kk/steamtinkerlaunch#390]
looks like the proton file that gets downloaded doesn't have the path where it's expecting it to be, so we get this bad path '/home/username/.config/steamtinkerlaunch/mo2/compatdata/pfx//dosdevices/c:'
I imagine this is a simple fix, but I've already spent several hours fighting to get this far.

```
teamtinkerlaunch mo2 i
wine: could not load ntdll.so: /home/username/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/lib/ntdll.so: cannot open shared object file: No such file or directory
/home/username/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/bin/wineserver: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/username/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/bin/wineserver)
Proton: Upgrading prefix from None to 6.17-0 (/home/username/.config/steamtinkerlaunch/mo2/compatdata/)
Traceback (most recent call last):
  File "/home/username/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/proton", line 1483, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/username/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/proton", line 1241, in init_session
    g_compatdata.setup_prefix()
  File "/home/username/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/proton", line 649, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/home/username/.config/steamtinkerlaunch/mo2/compatdata/pfx//dosdevices/c:'
grep: /home/username/.config/steamtinkerlaunch/mo2/compatdata/pfx/*.reg: No such file or directory
wine: could not load ntdll.so: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/username/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/bin/../lib/wine/i386-unix/ntdll.so)
```

**Comment by frostworx** [comment]
`wine: could not load ntdll.so: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/username/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/bin/../lib/wine/i386-unix/ntdll.so)`

looks like Proton-6.17-STL-1 is incompatible with your systems glibc :(
there's nothing I can do here. It is not very difficult to roll an own proton TKG though.
Alternative would be to wait for an other Proton version to no longer fail with DotNet.
(recently a wine bug was fixed, which caused other issues, so a Proton with an up2date wine version might be already enough)

**Comment by frostworx** [comment]
This upstream warning pretty much explains it:
https://github.com/Frogging-Family/wine-tkg-git/releases/tag/6.17.r0.g5f19a815

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/issues/393

**Comment by frostworx** [comment]
no need to keep this open for a monologue
