### ISSUE TITLE
Mod Organizer 2 install never completes

### ISSUE THREAD

**Issue by mxKaZVN** [sonic2kk/steamtinkerlaunch#394]
![Screenshot_20211231_115319](https://user-images.githubusercontent.com/67602990/147833255-28d38508-6ece-4fa2-8ab8-a6890b5fdb8a.png)
I cannot get past this point. I deleted the /.config/steamtinkerlaunch to start over and tried with the gui and command line [https://github.com/frostworx/steamtinkerlaunch/wiki/Mod-Organizer-2](https://github.com/frostworx/steamtinkerlaunch/wiki/Mod-Organizer-2)
I am on manjaro and installed fine through AUR. I feel like I'm the only one that has issues like this...

**Comment by frostworx** [comment]
Please tell me which exact steamtinkerlaunch version you're using (there are multiple fixes in git, also improving/fixing MO2) and please also provide a log file.

**Comment by mxKaZVN** [comment]
Version 8 and where can i get the log? Want me to paste console output? I can get it in about an hour.

**Comment by frostworx** [comment]
Please see [this sticky](https://github.com/frostworx/steamtinkerlaunch/issues/93) for the log path.
Take your time, I'll probably be offline very soon for this year :)

**Comment by mxKaZVN** [comment]
[377160.log](https://github.com/frostworx/steamtinkerlaunch/files/7797031/377160.log)
This is what I get on a fresh .config where it is stuck installing.
After closing out and trying to launch MO2 again it acts like a loop finishing install over and over.
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/7797033/steamtinkerlaunch.log)

Enjoy your weekend and new year and get back when you're ready :)

**Comment by frostworx** [comment]
Good morning and happy new year!
The logs don't seem to have any obvious errors _(the dotnet installation does not seem to have even started though)_
Please try again with current master, to make sure your problem was already resolved.

**Comment by mxKaZVN** [comment]
Hello again, the latest git master is also stuck at the same prompt unfortunately. I tried command line and with the menu.
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/7797671/steamtinkerlaunch.log)
command line output has these

WARNING: radv is not a conformant Vulkan implementation, testing use only.
wine: could not load kernel32.dll, status c0000135

**Comment by frostworx** [comment]
Hhm, looks like this is not really a `steamtinkerlaunch`, but a Proton _(version)_ problem _(maybe related to https://github.com/frostworx/steamtinkerlaunch/issues/390)_
Please test if
`~/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/bin/winecfg`
works for you _(make sure to set a different `WINEPREFIX` if you want to avoid using the default `~/.wine` one)_

**Comment by mxKaZVN** [comment]
Yes this does seem like the same issue, gclib is incompatible with proton just like 390.

**Comment by frostworx** [comment]
Sad to hear. Unfortunately, there's nothing I can do then, but suggesting rolling your own proton TKG _(which is pretty much straightforward)_. Let's hope one of the next proton versions no longer has those `DotNet` issues and the self-rolled Proton no longer is necessary generally.

**Comment by frostworx** [comment]
.
