### ISSUE TITLE
[Non-Steam Game] Attempting to Use Winetricks or Shader Menu via GUI Doesn't Work

### ISSUE THREAD

**Issue by ThisNekoGuy** [sonic2kk/steamtinkerlaunch#398]
Attempting to navigate several menus including the Winetricks and Shader selection menus open a window to run them as if they were games instead of tools to manage non-Steam games and attempts to run these with Proton, to then close or fail immediately.

![image](https://user-images.githubusercontent.com/28468662/148812423-9de339d1-8d88-4188-a92e-2f398b2c8e89.png)

**Comment by frostworx** [comment]
Please append a log

**Comment by frostworx** [comment]
Oh, and while testing.
Would be great if you tested your game (plus mentioned functions) with this new implementation as well:
https://github.com/frostworx/steamtinkerlaunch/wiki/Standalone-Launcher

**Comment by frostworx** [comment]
I can reproduce your initial issue, thanks for reporting.
I hope it is easy to fix...
Would be nice anyway if you'd test above function.

**Comment by frostworx** [comment]
The problem only occurs when started directly from Steam and doesn't when started from command line.
Should be easy to fix _(soon)_

**Comment by ThisNekoGuy** [comment]
[3778187382.log](https://github.com/frostworx/steamtinkerlaunch/files/7841360/3778187382.log)
[lastrun.txt](https://github.com/frostworx/steamtinkerlaunch/files/7841361/lastrun.txt)
[wt.log](https://github.com/frostworx/steamtinkerlaunch/files/7841362/wt.log)
[update.log](https://github.com/frostworx/steamtinkerlaunch/files/7841363/update.log)
[cfi.log](https://github.com/frostworx/steamtinkerlaunch/files/7841364/cfi.log)
[ccd.log](https://github.com/frostworx/steamtinkerlaunch/files/7841365/ccd.log)

> Oh, and while testing.
Would be great if you tested your game (plus mentioned functions) with this new implementation as well

I'll try that next

**Comment by ThisNekoGuy** [comment]
Every time I try to use the `play` or `play gui` arguments, `steamtinkerlaunch` spits out the help terminal output. :/

**Comment by frostworx** [comment]
thanks for the logs _(sorry, with "I can reproduce..." I meant that I do no longer need them)_
The `play` option needs an absolute path to your game exe.
When that worked correctly, it should have created a `steamtinkerlaunch` config and
`play gui` should be able to find it and open a menu then.

**Comment by ThisNekoGuy** [comment]
> The `play` option needs an absolute path to your game exe.

Sorry that I didn't clarify, I did try this also earlier and it did the same as I mentioned with the help output

**Comment by frostworx** [comment]
Oh, ic. Would you mind sharing that log? `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log` should be enough.
For the initial issue, the problem is obvious and in theory easy to fix, but it would be ugly as well:
In [this line ](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L18311) the SteamAppId is checked.
If it exists and is 0 steamtinkerlaunch assumes that a non-steam game is started.
This is correct, but any further command line parsing is skipped at that location.

The ugly fix would be to check if any valid command line argument is given and then start the `commandline` function instead of the `prepareLaunch` function.
The cleaner fix would be to check generally the `commandline` first and everything else afterwards, but I'm afraid this would lead to multiple new issues.
I guess I need to think about how to best fix it :)

**Comment by frostworx** [comment]
I got an easy to implement _(and not too ugly)_ idea - let's see...

**Comment by frostworx** [comment]
Above commit seems to fix it :)

**Comment by ThisNekoGuy** [comment]
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/7841673/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
I guess you do not use current git master. The standalone function is just a few days old and therefore not in the last release from november.

**Comment by ThisNekoGuy** [comment]
Ah, I suppose I should use `steamtinkerlaunch-git` from the AUR, then

**Comment by frostworx** [comment]
_(that's why I set [this info issue](https://github.com/frostworx/steamtinkerlaunch/issues/93) sticky btw)_

**Comment by ThisNekoGuy** [comment]
I tested it; the original issues are fixed now but if you try to target the executable and play from the terminal, no prefix is made and Proton fails to run

[eldorado.exe.log](https://github.com/frostworx/steamtinkerlaunch/files/7841792/eldorado.exe.log)

**Comment by ThisNekoGuy** [comment]
Also, already downloaded shader repos aren't read by `steamtinkerlaunch` when non-Steam games are being configured

**Comment by frostworx** [comment]
> Also, already downloaded shader repos aren't read by `steamtinkerlaunch` when non-Steam games are being configured

not reproducible here. all shader repos are available for a freshly launched non-steam game.

**Comment by ThisNekoGuy** [comment]
What I meant was that, if I downloaded them for Steam games, my non-Steam game thinks that stl never downloaded them before and prompts to select repos to enable for that game?

**Comment by frostworx** [comment]
log!

**Comment by frostworx** [comment]
menu for enabling shader repos != downloading repos btw.
The shaders are downloaded in one central place and are used when you enable them via CHOOSESHADERS _(='Shader Menu')_

**Comment by ThisNekoGuy** [comment]
![image](https://user-images.githubusercontent.com/28468662/148997180-0c84f3a2-f17a-43a3-9092-aa3989155a3c.png)
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/7848923/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
try to be more polite and verbose.
You want to use shaders and that's why you get a shader menu...

**Comment by ThisNekoGuy** [comment]
Sorry, I'm not trying to be rude?
I was trying to clarify that I expected it to just open the shader selection menu rather than moving shaders to a subfolder in the game directory; when all of the above shaders are already on the disk, I didn't see a reason to use more disk space by copying them. :/

**Comment by frostworx** [comment]
Sorry, looks like I misunderstood your short replies then.
Shaders are not copied, but symlinked - so no matter how many games use shaders, they all use the same source.
  - all checked shaders repos will be installed into the current game directory using symlinks
  - all unchecked shaders repos will be removed from the current game directory using symlinks

via  [Shader-Management](https://github.com/frostworx/steamtinkerlaunch/wiki/Shader-Management)

I guess this solves your problem then, right?

**Comment by ThisNekoGuy** [comment]
Yep, that's fine then; sorry for the confusion

**Comment by frostworx** [comment]
perfect, closing here then

**Comment by ThisNekoGuy** [comment]
@frostworx Sorry to bring this up again;

Probably what confused me here, in addition, was that in previous versions, choosing a shader to apply to games meant selecting _that shader_ but I was thrown off that a folder is made with all of the shaders from a repo symlinked to it but none of them are actually _applied._

The current implementation makes it slightly confusing (for users that are new to shaders) because STL doesn't place the specific ones a user wants in the game's executable directory anymore via the GUI (only the repos are selectable, not the shaders a user wants to enable and apply)

**Comment by ThisNekoGuy** [comment]
Whoops--
It seems I made a mistake, it's just implemented differently; sorry

**Comment by Arcitec** [comment]
@ThisNekoGuy Yeah the new system is more foolproof and easier. You enable repos of shaders instead of the individual shaders. It is faster than selecting all of the individual files, and it prevents mistakes, since most repos contain important helper libraries (`.fxh` files) that must also be installed.
