### ISSUE TITLE
automatic game configuration import from multiple other platforms

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#40]
Would be nice to have an optional search for required tweaks from various different platforms.
Most interesting ones would be probably
- Lutris
- protondb
- directly proton issues https://github.com/ValveSoftware/Proton/issues

Lutris has an open api which could be used - I asked here if using it from stl would be ok: https://github.com/lutris/lutris/issues/3117
- protondb doesn't seem to have any usable api, but if the data could be reached, some basic functions searching for required tweaks could be done. I only found this (half-official?)half-maintained project https://github.com/bdefore/protondb-data
which only offers huge static tarballs of monthly reports. opened an issue here 6 weeks ago asking for improvements : https://github.com/bdefore/protondb-data/issues/28

- the proton issue tracker is probably full of useful informations, but haven't found(/searched) for a way yet to automatically search in there.

**edit**:
- would be great to also import [protonfixes](https://github.com/simons-public/protonfixes) gamefixes : just opened a request here: https://github.com/simons-public/protonfixes/issues/137

any other sources I forgot/don't know?

**Comment by frostworx** [comment]
ok, pulling all issues from proton issue tracker (keeping those allrady downloaded to not flood) is pretty easy

**Comment by frostworx** [comment]
protonfixes implementation is already working pretty fine (offline)

**Comment by arrowgent** [comment]
automating fixes in this way seems like an AI Heuristics method to find strings that work and then translate that into pass/fail criteria
i couldnt even imagine the parsing language to find a fix

lutris atleast is just scripts ready to go.


if you are going to use these, atleast make them Optional/Manual
and transparent, (we can open the fix and look at its contents from within the menu) before accepting.

**Comment by frostworx** [comment]
Of course this will be optional. The whole concept is pretty stable.
No platform, no matter how good the import works will be enabled by default.
Weaker platform imports (looking at you #47) will get a warning
_(parsing plain text will be very basic of course)_.
Platforms which the user decides to use will always(!) have a lower priority than all other configs, as they will be loaded at first and therefore will be overridden by all other configs following.
The autotweak will be opened together with the main config when WAITEDITOR is enabled
_(edit: It will use ATEDITOR which will fall back to WAITEDITOR if empty)._

**Comment by frostworx** [comment]
protonfixes and lutris fixed in fixed in https://github.com/frostworx/steamtinkerlaunch/commit/1278f8a9c90270e66056c5063e93a6dea23a5976

**Comment by frostworx** [comment]
Remaining "platforms" which might be added are in #47 and #48
