### ISSUE TITLE
MO2 fails to install

### ISSUE THREAD

**Issue by AndrewCloss** [sonic2kk/steamtinkerlaunch#400]
# Please see this [sticky note](https://github.com/frostworx/steamtinkerlaunch/issues/93) for what is required for a good issue

When installing MO2 via GUI or CLI, it hangs on 'Done'. [The log](https://github.com/frostworx/steamtinkerlaunch/files/7882830/steamtinkerlaunch.log)

If I run it through CLI after a few CTRL-C (cause of the hangs) here is the [the log](https://github.com/frostworx/steamtinkerlaunch/files/7882874/steamtinkerlaunch.log) and the console output:

> steamtinkerlaunch mo2 s
> /usr/bin/steamtinkerlaunch: line 11017: : command not found
> Wine cannot find the FreeType font library.  To enable Wine to
> use TrueType fonts please install a version of FreeType greater than
> or equal to 2.0.5.
> http://www.freetype.org
> Wine cannot find the FreeType font library.  To enable Wine to
> use TrueType fonts please install a version of FreeType greater than
> or equal to 2.0.5.
> http://www.freetype.org
> ^C/usr/bin/steamtinkerlaunch: line 11017: : command not found
> Wine cannot find the FreeType font library.  To enable Wine to
> use TrueType fonts please install a version of FreeType greater than
> or equal to 2.0.5.
> http://www.freetype.org
> Wine cannot find the FreeType font library.  To enable Wine to
> use TrueType fonts please install a version of FreeType greater than
> or equal to 2.0.5.
> http://www.freetype.org
> ^Cgrep: /home/andrewc/.local/share/Steam/steamapps/appmanifest_489830.acf
> /home/andrewc/.local/share/Steam/steamapps/appmanifest_489830.acf: No such file or directory
> /usr/bin/steamtinkerlaunch: line 11017: : command not found
> Wine cannot find the FreeType font library.  To enable Wine to
> use TrueType fonts please install a version of FreeType greater than
> or equal to 2.0.5.
> http://www.freetype.org
> Wine cannot find the FreeType font library.  To enable Wine to
> use TrueType fonts please install a version of FreeType greater than
> or equal to 2.0.5.
> http://www.freetype.org

**Comment by frostworx** [comment]
```
Wine cannot find the FreeType font library. To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
```
so did you check this?

`/usr/bin/steamtinkerlaunch: line 11017: : command not found`
indicates that wine could not be started, likely because of the missing dependency above.

**Comment by AndrewCloss** [comment]
I had it already installed with `sudo pacman -S freetype2`

Turns out Wine needed `sudo pacman -S lib32-freetype2`

**Comment by frostworx** [comment]
you're welcome!
