### ISSUE TITLE
false crash detection when overriding proton version to aur proton-ge

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#401]
When steamtinkerlaunch is used as  a compat tool and the proton version is overridden to this [version from the aur] (https://aur.archlinux.org/packages/proton-ge-custom/).
Should mention I installed the chaotic aur version specifically but there shouldn't be a difference. It thinks the game crashes after a few seconds
[steamtinker_proton-ge-custom.log](https://github.com/frostworx/steamtinkerlaunch/files/7885674/steamtinker_proton-ge-custom.log)
game continues normally however and everything works  so a false detection i guess.

However, when  the same version of ge is downloaded from the custom proton main menu option and used steam tinker launch works as expected
[steamtinker_proton-ge.log](https://github.com/frostworx/steamtinkerlaunch/files/7885682/steamtinker_proton-ge.log)

I don't see any differences in the logs that could point to what is going wrong , it should be noted that this version of proton-ge used to work with steamtinker but, after an update, not sure to which, it no longer works.

EDIT:  found this line in the steamtinker proton ge log (so the working one)
```Mon Jan 17 09:06:17 PM EST 2022 INFO - startGame - Proton 'Proton-7.0rc6-GE-1' forks its command into background, so waited for the wineserver RUNWINESERVER '/home/zany130/.local/share/Steam/compatibilitytools.d/Proton-7.0rc6-GE-1/files/bin/wineserver' with pid '437192' to finish instead```

that's missing when the aur version is used so based on that it seems steamtinker has check for proton-ge to fix this and its not being used for the aur version?

EDIT2: seems like the issue might be here https://github.com/frostworx/steamtinkerlaunch/blob/24eacf3b8e195615cdf6ef42ded7b127bf4cf8fd/steamtinkerlaunch#L14437

wouldn't it be enough to add i option to the grep command for proton-ge so that it ignores case? so the line would be rewritten to 
`	if [ "$ISGAME" -eq 2 ] && [ "$USEWINE" -eq 0 ] && { grep -qi "\-GE\-" <<< "$USEPROTON" || grep -qi "\-TKG" <<< "$USEPROTON";}; then`

tested and it seems to work

**Comment by frostworx** [comment]
merged your fix. thx
