### ISSUE TITLE
Vortex does not automatically symlink installed games

### ISSUE THREAD

**Issue by KennethHoff** [sonic2kk/steamtinkerlaunch#402]
I completely deleted the `steamtinkerlaunch` folder under `.config` and then did the following:

1. `steamtinkerlaunch dcp l` to install latest proton (Proton-7.0rc6-GE-1 as of this issue)
2. `steamtinkerlaunch settings` => global => set this newly installed version to be used by Vortex
3. `steamtinkerlaunch vortex start` => install => opens, and nothing shows.

As you can see in the following image, it registers the game `7 Days to Die` as being installed.
![image](https://user-images.githubusercontent.com/17124533/150656714-eb17f0eb-87d7-46b5-b86f-e197a976c396.png)

However, Vortex itself is not able to see the game itself in its GUI.

![image](https://user-images.githubusercontent.com/17124533/150656741-d8de4abc-fedc-460a-bc9b-2aa3711e4e98.png)

I'm an utter noob at Wine, so I have no idea to manually symlink it either.

This is the `steamtinkerlaunch vortex getset` output
[getset.txt](https://github.com/frostworx/steamtinkerlaunch/files/7919374/getset.txt)

```
Operating System: OpenSUSE Tumbleweed 20220121

SteamTinkerLaunch version: steamtinkerlaunch-v9.1.20220119
```

**Comment by KennethHoff** [comment]
As an aside, adding games to a steam collection (specifically `VORTEX`) does not seem to have any effect - it still says it's not a part of the category\* 
![image](https://user-images.githubusercontent.com/17124533/150657081-a6444639-181a-4028-b87c-5e0c5c0bbbfd.png)

\* Is `Category` and  `Collection` two different things; [The showcase on the wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Vortex#steamtinkerlaunch-vortex-gif) seems to show `Collection` - should probably rename all uses of the word `Category` into `Collection` if that's the case

**Comment by KennethHoff** [comment]
Uhm.

No idea what I did, but after like 30 minutes I reloaded the game and it now detects it. No idea what caused it. All I know is that I installed a few random packages related to compressing a PNG (optipng and maybe some others). No idea how that relates to anything, but now it detected it. Maybe there was some backround process that was running without me realizing

**Comment by KennethHoff** [comment]
If you have nothing to contribute to this, then close it (Reopened it because maybe you want to read it and/or add something to this)

**Comment by frostworx** [comment]
`Vortex depends on dotnet48 see DotNet. Unlike Mod-Organizer 2, Vortex does not work with Mono instead, so Vortex is always used inside its own Wineprefix/Compatdata steamtinkerlaunch automatically/by default uses an own DotNet compatible Proton version for that pfx and also installs DotNet automatically.` (via [Vortex wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Vortex) which also points to [dotnet wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/DotNet))

Apparently you also did not read the [sticky note](https://github.com/frostworx/steamtinkerlaunch/issues/93)
when creating a new issue a "issue template" even points to it additionally...

At least for me it is not very clear what your actual problem even was. The "7 days to die" icon is clearly colored on your first screenshot, which indicated that it was detected.

Generally it is always a good idea to check the logs first.

edit: fixed some broken md urls :)

**Comment by macinsight** [comment]
Adding my input, as, using Arch, STL v9.0.1, and Proton-7.1-GE-2, STL fails to symlink anything relating to Vortex successfully, as I have found.

Also (Going to open a separate issue for this): `steamtinkerlaunch vortex getset` returns `sed: -e expression #1, char 0: no previous regular expression`, resulting in absolutely no output except that error message when run.

**Comment by frostworx** [comment]
`steamtinkerlaunch vortex getset` works fine for me using default STL proton version though, so I guess this is all caused by the same glitch.
Should be easy to fix, but no idea when I'll find the time and logs would help for sure _(or directly a PR of course)_
