### ISSUE TITLE
Add app-name for KDE Plasma notifications

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#403]
SteamTinkerLaunch notifications on KDE Plasma display the process as "notify-send". It would be nicer if it said "SteamTinkerLaunch" as it's more in line with what a user would expect. Below is a small example of a notification I was able to trigger on my system, though for what it's worth, most applications do not display this name correctly on KDE Plasma and the only one I can actually think of that properly displays its process name is Firefox (as just "Firefox" or "Firefox Developer Edition", etc).

![Screenshot_20220124_211008](https://user-images.githubusercontent.com/7917345/150867236-f505f1e0-d051-4eb5-bc31-9736b3ea8def.png)

I took a look into how this might be implemented and I'm not sure exactly how this is done. It seems like this information can be taken in from a "desktop" file. An example I was testing was `notify-send foo bar -h STRING:desktop-entry:steamtinkerlaunch`, which still displays "notify-send" as the process name, but will display the steamtinkerlaunch icon, which does not normally happen with SteamTinkerLaunch notifications at all either (and may not be desired behaviour, either).

It is very much just a "nice to have" feature but would add extra clarity as to where notifications are coming from for users.

**Comment by zany130** [comment]
this is what https://github.com/frostworx/steamtinkerlaunch/wiki/Notifier is trying to address. I guess you would want to use the native KDE notifier program instead of the generic notify-send that would allow better integration on KDE. You can in theory do read the linked wiki page but never really bothered to get it working. I just remember someone asking for that feature in the old discord and then the feature  being implemented 

if you figure it out though please do post how you did it for others and it could maybe even be contributed to the wiki page as an example on how to use that option in KDE

**Comment by sonic2kk** [comment]
Thanks! I'll give the wiki a read, apologies for not investigating the wiki more thoroughly.

It seems adding the `-a SteamTinkerLaunch` flag sets the application name, at least in my tests with using notify-send to send test notifications. I will test with SteamTinkerLaunch now and see how I get on, and if it works, I'll see about contributing to the wiki! :smile:

**Comment by sonic2kk** [comment]
Well that was much easier than expected. Simply updating the line for the Notifier in the Global Menu settings with `-a SteamTinkerLaunch` seems to correctly set the title, resolving my issue.

Would most Linux distributions support this flag? It is not mentioned in the manual pages for my distro, I found it on [this](http://vaskovsky.net/notify-send/linux.html) page. Is `notify-send` implemented differently across distros? If not, and this is desireable behaviour, this additional argument could be added to the notifier arguments.

**Comment by frostworx** [comment]
thanks for the PR @sonic2kk 
and thanks for helping here @zany130
very appreciated! 👍
