### ISSUE TITLE
Facilitate installation/use of Vortex betas and alphas, such as the collections open alpha.

### ISSUE THREAD

**Issue by Continous** [sonic2kk/steamtinkerlaunch#405]
Currently STL automatically downloads and installs the latest Vortex release. This is fine, but at the moment Nexus mods are running an open beta/alpha of the collections feature, and this is distributing in a different manner. Currently, I simply run the installer myself within the wine prefix, however a more novice user may find this unapproachable or otherwise unsatisfactory. Allowing the user to provide their own installer executable or perhaps even providing access to open alphas/betas ourselves may be a good idea.

**Comment by frostworx** [comment]
I'm not convinced that spending time into this makes much sense. A novice user is usually happy with a one click installation already and is less interested in installing a custom installer.
And even if they do want to install a custom exe they should be able to do so. Either completely manually like you did, or simply use https://github.com/frostworx/steamtinkerlaunch/wiki/One-Time-Run or https://github.com/frostworx/steamtinkerlaunch/wiki/Custom-Program
If you're willing to open a PR, I'd add it though.

**Comment by frostworx** [comment]
please refrain from opening issues, if you're not willing to communicate
