### ISSUE TITLE
SteamTinkerLaunch spams notifications when a Proton version is removed trying to find a "similar" version

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#406]
When I downloaded and extracted `Proton-7.0rc6-GE-1`, I removed the older rc3 build I had installed. When I opened Steam, SteamTinkerLaunch seemed very upset about this :sweat_smile: 

![Notification spam](https://user-images.githubusercontent.com/7917345/151608130-6329897a-7e62-4e8a-b339-fcfc641e8443.png)

It kept spamming these notifcations, this is as many as my desktop environment will display in one vertical line. When closing one, more of the same would appear to take its place. I only had Steam opened for about a minute at most, and after closing Steam there was still a huge backlog of notifications to dismiss. I ended up having to kill a shell process from my system monitor. This happens every time I open Steam.

This hasn't happened with other versions of Proton-GE that I have deleted, for example going from `rc2` to `rc3` was fine.

I'll see what workarounds I can find for now, apart from setting Plasma to "Do Not Disturb". Although the notification process is still using 2% of my CPU and memory usage is climbing. I left it for a minute and it ended up using almost 100mb ram! I had to send a `KILL` command from KSysGuard to stop the process, but this would need to be done every time Steam opens.

**Comment by sonic2kk** [comment]
My solution for now was to add the `rc3` build of Proton back for now. I would guess if I set any games that use `rc3` to use `rc6` it would also resolve the issue.

Without the `rc3` version that SteamTinkerLaunch was expecting, I could even open the launcher however. Perhaps the notifications were stopping the process? I can open the launcher menu fine now, but I could not before adding`rc3` back into my `compatibilitytools.d`.

I had a look through the code and I'm not exactly sure what could be causing it. I'll leave it to someone with more contributing experience to investigate on the technical side :smile:

**Comment by frostworx** [comment]
I know this rarely happens, but I wasn't in the mood to fix this, because it can be easily workarounded with a fresh (non-existant)
`/dev/shm/steamtinkerlaunch`
Unlikely I will find the time and motivation to add a check for this any time soon, but I'll leave the issue open for a while for possible PRs.

**Comment by frostworx** [comment]
I might have a good and easy to implement idea to fix this.
Can you provide logs for this issue, so I can implement it without debugging it first?

**Comment by sonic2kk** [comment]
I'll be happy to provide logs, can you tell me where I can find them? I'll remove the version of Proton-GE again and then provide the logs.

**Comment by frostworx** [comment]
Please check [this sticky](https://github.com/frostworx/steamtinkerlaunch/issues/93)
_(when creating a new issue a "template" is also pointing at it btw)_

**Comment by frostworx** [comment]
.

**Comment by frostworx** [comment]
¯\\_(ツ)_/¯
