### ISSUE TITLE
Discord and Matrix invites expired

### ISSUE THREAD

**Issue by macinsight** [sonic2kk/steamtinkerlaunch#413]
Hey Frostworx,

figured I'd bring it to your attention that all publically accessible links to the Discord Server have expired, and the Matrix server requires an invite (Unless this is all intentional to cut down on support-channels, in which case I'm sorry)

**Comment by frostworx** [comment]
hey, macinsight.
Thanks for your help! Indeed, this is intentional, as I simply do no longer have the time to keep an eye on those channels.
Have you also found links somewhere on my project page here? If so, I forgot to remove them :)

**Comment by macinsight** [comment]
Hey frostworx,

> Indeed, this is intentional

Very well then!

> found links somewhere on my project page

Nope, but I'll have a look around and attach links to this issue if I should see any. Gonna keep this open for ~24hrs while I look around, then close it.

I'm gonna go back to battle Vortex into playing nice with F:NV, Vortex keeps complaining about a broken .NET installation. Which I know is not an issue if using `Proton-6.17-STL-1`, but for some reason (unable to pin down why exactly), mods that are installed do not change game behavior. Nothing weird in the logs, so I'm flying pretty much blind here.

Also, from what I can see, Proton-7.1-GE-2 is working nice with Vortex (At least no change to the previous behavior). Want me to add to #393, or should it remain closed?
I'm gonna strangle it a bit more and see i it turns blue. If it does, I'll open another issue.

Have a good one!

**Comment by frostworx** [comment]
_(just reopened #393)_

**Comment by macinsight** [comment]
Closing this one as said above, no further links found.
