### ISSUE TITLE
Mod Organizer 2 - appmanifest_72850.acf: No such file or directory upon launch, need to select Portable profile each time

### ISSUE THREAD

**Issue by ghost** [sonic2kk/steamtinkerlaunch#415]
Hello,

This might just be my own stupidity, but is it possible for me to set my Portable profile as default so I can skip a few steps each time I run MO2? I have to switch to a Portable instance each time. I'm afraid I have a ton of mods installed so it isn't trivial for me to reinstall. At least, I don't know an easy way to migrate without breaking everything.

Here's some output:

prime steamtinkerlaunch mo2 start
grep: /home/tod/.local/share/Steam/steamapps/appmanifest_72850.acf
/home/tod/.local/share/Steam/steamapps/appmanifest_72850.acf: No such file or directory
grep: /home/tod/.local/share/Steam/steamapps/appmanifest_72850.acf
/home/tod/.local/share/Steam/steamapps/appmanifest_72850.acf: No such file or directory
Wed Feb 16 11:32:37 AM MST 2022 INFO - startMO2 - Starting '/home/tod/.config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe' in standalone mode with command:
Wed Feb 16 11:32:37 AM MST 2022 INFO - startMO2 - WINEDEBUG="-all" WINEPREFIX="/home/tod/.config/steamtinkerlaunch/mo2/compatdata/pfx" "/home/tod/.config/steamtinkerlaunch/proton/custom/Proton-6.17-STL-1/files/bin/wine" "/home/tod/.config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe" -i "Skyrim"

Then a window pops up saying 
Instance at 'C:/users/steamuser/AppData/Local/ModOrganizer/Skyrim' not found. Select another instance.

I'm guessing standalone mode isn't what I want, but I can't figure out how to change it.

I attached a log too, not sure if it's the one you want. Added a txt extension to it in case there's some MIME weirdness.
[31337.log.txt](https://github.com/frostworx/steamtinkerlaunch/files/8082573/31337.log.txt)

**Comment by ghost** [comment]
Version is 9.0.1

**Comment by ghost** [comment]
MO2 also can't seem to find my Steam install right away. For example, when I run SKSE through it, it says "Please press OK once you're logged into steam."

**Comment by frostworx** [comment]
Hi,
sorry for the quick reply. I'll need some time to look into this, but I'm afraid I won't find the time to import "externally" installed mods (or did I misunderstand you?).
Please also elaborate on how you're starting MO2
_(haven't checked your log yet)_

I personally do not use MO2 at all, so I do not even know for sure if I implemented portable or non-portable MO2 mods.
You might be interested in [this still open issue](https://github.com/frostworx/steamtinkerlaunch/issues/305) though _(especially that what @ajventer says)_

**Comment by ghost** [comment]
Hm, no, everything is already working well (thanks by the way!). I'm not doing anything fancy,  everything I use is already installed and works.

The problems I mentioned are mostly cosmetic: having to select the Portable profile each time. The file it says it can't find definitely exists, which is weird. Also everytime I run anything through MO2 I get a prompt for confirmation about starting Steam, even though it's already running.

That "prime" thing just passes some environment variables, nothing that affects steamtinkerlaunch:
__NV_PRIME_RENDER_OFFLOAD=1 __NV_PRIME_RENDER_OFFLOAD_PROVIDER="NVIDIA-G0" __GLX_VENDOR_LIBRARY_NAME="nvidia" __VK_LAYER_NV_optimus="NVIDIA_only" exec "$@"

**Comment by ghost** [comment]
I never used MO2 on Windows so I'm not really sure how the portable profiles are supposed to work, so I probably shouldn't have chosen it. I think it was the default option and I went with it.

**Comment by ghost** [comment]
I just run "steamtinkerlaunch mo2 start" or "prime steamtinkerlaunch mo2 start" from a terminal

**Comment by frostworx** [comment]
Thanks for the quick reply!
When starting MO2  "manually" _(so as you do using: `steamtinkerlaunch mo2 start`)_
the special MO2 wineprefix/compatdata and proton version is used. That mod is supposed for modding a game (here it is mostly not possible to start a game through MO2, because the game is in a different wineprefix!).

When starting a Game with MO2 enabled through steam, MO2 is started in the game wineprefix (which f.e. usually does not have dotnet installed) using the proton version the game uses as well. It is not perfect, but this is the only solution I found to make it usable as good as possible without any deeper configuration.
I also tried to describe the functionality in the [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Mod-Organizer-2) _(I'm sure it is hard to understand)_

I'll need to recheck this to give a clear answer, but usually the implementation does not give you the option to choose a non-portable installation.

**Comment by frostworx** [comment]
Hm, I can't reproduce this:

`steamtinkerlaunch mo2 start` starts normally here using the last game selected without any requesters.
It si using the only existing "Default" Profile, and I can change games with the "Instance Manager" Icon.

Your logfile looks fine as well, you might want to check your Skyrim (72850) installation though _(did you move it or something?)_

I never used Windows and MO2 so I can't help with its internals, but I'm afraid this doesn't look like a steamtinkerlaunch issue for me. Leaving this open, in case you have further questions or maybe also hints.

**Comment by ghost** [comment]
Thanks for looking into it.

No, I didn't move anything, but this old version isn't listed in the Steam store anymore. And I added some texture pack DLC through Steam as well. Hm, and I installed FNIS and ENB manually because it wasn't working with MO2. I can ask on the MO2 github.

**Comment by ghost** [comment]
Oh, and before STL I did try https://github.com/rockerbacon/modorganizer2-linux-installer which didn't work at all for me, so it's possible I subtly broke my Steam installation. I think that I could wipe my Steam/Skyrim installation to test without affecting the mods too much. I'll look into it.

**Comment by ghost** [comment]
I created a ModOrganizer/Skyrim symlink and it starts without issue, but it's not pointing to the portable profile anymore:

~/.config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local$ file ModOrganizer/Skyrim
ModOrganizer/Skyrim: symbolic link to /home/tod/.local/share/Steam/steamapps/compatdata/72850/pfx/drive_c/users/steamuser/Local Settings/Application Data/Skyrim

I think I see what's happening.

**Comment by ghost** [comment]
I solved my problem by copying all mods over to that working profile:
realpath .config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/Skyrim/mods/
/home/tod/.local/share/Steam/steamapps/compatdata/72850/pfx/drive_c/users/steamuser/AppData/Local/Skyrim/mods

So now I have this: 
![Screenshot from 2022-02-18 02-23-18](https://user-images.githubusercontent.com/94070930/154654728-8133f15d-f058-463c-8549-e006f6d17d2d.png)

This was the problematic instance: 
![Screenshot from 2022-02-18 02-24-28](https://user-images.githubusercontent.com/94070930/154654863-82e2d1ce-a84b-4d96-9334-765d122cf7eb.png)

So we can close this if you like.

**Comment by frostworx** [comment]
Still a mystery where the original problem came from, but glad to hear you sorted it out. :)
happy gaming/modding!
