### ISSUE TITLE
Unable to launch Non-Steam Proton titles

### ISSUE THREAD

**Issue by Sterophonick** [sonic2kk/steamtinkerlaunch#416]
When adding a non-Steam Windows game to Steam, it is impossible to get the game working, no matter what I tried.
KDE brings up the following notifications and nothing happens.
Not sure of any other information I can provide, other than the fact that the Wiki page shows the game Diablo II being added.

![image](https://user-images.githubusercontent.com/34801996/154335769-3d5712f9-118d-495c-a86e-0666ec1d2088.png)
Log file: [steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8082674/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
Funny coincident - I fixed exactly this issue today [four hours ago](https://github.com/frostworx/steamtinkerlaunch/commit/c1d687e8d4b8b378c9ef48c1bad811f25bce3b3c)
Please re-test with current git-master

**Comment by Sterophonick** [comment]
Oh my god what a coincidence.

Well, fantastic! Thank you so much!
