### ISSUE TITLE
⚠ [HOWTO] Vortex Game Mods can't be deployed

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#418]
`steamtinkerlaunch` tries to autodetect and autoconfigure all Vortex compatible games installed.
That feature _(for now)_ utilizes a static self-rolled list _(`/usr/share/steamtinkerlaunch/misc/vortexgames.txt`)_ 
with their SteamAppid , the actual name and the "nexusgameid".
Most games should work, bur several others can't be setup automatically, often because the nexusgameid changed.
[This commit](https://github.com/frostworx/steamtinkerlaunch/commit/f29197f9b1a81ddcedb06a3b234c1b0a22a36b06) fixes the issue for Fallout New Vegas, Skyrim SE and several other titles.

**If someone has an idea how to best drop that static list completely, you're very welcome to share it.**
Until then, the bundled list needs to be tested and maintained permanently.

When you enable an autodetected game in Vortex and see something like this

![broken2](https://user-images.githubusercontent.com/8840590/154503691-1a7f406d-0818-4a60-afeb-ac05d25dfd1c.png)

you can check if the Vortex internal name _(underlined in the scrot)_ is equal to the one ion above static list.
If not, it might help to replace the string in the list with that you found. Either way it would be nice if you contribute your finding here and therefore help others with the same problem.

When everything looks correctly _(like in the next scrot)_, it would be nice as well if you confirmed it here.
![154318870-0601610d-118e-46ab-807d-2564a38e1f86](https://user-images.githubusercontent.com/8840590/154502901-6a3798d6-1511-4d7e-81bc-c0e93b8e987a.png)

Of course any hints or PRs for wrong, outdate or missing entries are very welcome as well.

Compatibility List _(checked means working - unchecked is untested, plrease report non-working in separate comments)_
_(I barely mod anything, so I leave it up to you to fill the checks)_

- [ ] "7daystodie";"7 Days To Die";"251570"
- [ ] "acecombat7skiesunknown";"Ace Combat 7: Skies Unknown";"502500"
- [ ] "ahatintime";"A Hat In Time";"253230"
- [ ] "baldursgate3";"Baldur's Gate 3";"1086940"
- [ ] "battlebrothers";"Battle Brothers";"365360"
- [ ] "battletech";"BattleTech";"637090"
- [ ] "bayonetta";"Bayonetta";"460790"
- [ ] "beatsaber";"Beat Saber";"620980"
- [ ] "blackmesa";"Black Mesa";"362890"
- [ ] "bladeandsorcery";"Blade & Sorcery";"629730"
- [ ] "bloodstainedritualofthenight";"Bloodstained: Ritual of the Night";"692850"
- [ ] "bloonstd6";"Bloons TD6";"960090"
- [ ] "borderlands2";"Borderlands 2";"49520"
- [ ] "breakingwheel";"Breaking Wheel";"545890"
- [ ] "callofcthulhudarkcornersoftheearth";"Call of Cthulhu: Dark Corners of the Earth";"22340"
- [ ] "citiesskylines";"Cities: Skylines";"255710"
- [ ] "codevein";"Code Vein";"678960"
- [ ] "commandandconquerremastered";"Command & Conquer Remastered Collection";"1213210"
- [ ] "conanexiles";"Conan Exiles";"440900"
- [ ] "control";"Control";"870780"
- [ ] "counterstrikesource";"Counter-Strike: Source";"240"
- [ ] "cyberpunk2077";"Cyberpunk 2077";"1091500"
- [ ] "daggerfallunity";"Daggerfall Unity";"31337"
- [ ] "darkestdungeon";"Darkest Dungeon";"262060"
- [ ] "darksouls";"Dark Souls";"211420"
- [ ] "darksouls2";"Dark Souls 2";"335300"
- [ ] "dawnofman";"Dawn of Man";"858810"
- [ ] "dayofdefeatsource";"Day of Defeat: Source";"300"
- [ ] "daysgone";"Days Gone";"1259420"
- [ ] "devilmaycry5";"Devil May Cry 5";"601150"
- [ ] "divinityoriginalsin2";"Divinity: Original Sin 2";"435150"
- [ ] "divinityoriginalsin2definitiveedition";"Divinity: Original Sin 2 - Definitive Edition";"1101230"
- [ ] "dontstarvetogether";"Don't Starve Together";"322330"
- [ ] "dragonage";"Dragon Age: Origins";"17450"
- [ ] "dragonage2";"Dragon Age 2";"1238040"
- [ ] "dragonsdogma";"Dragon's Dogma: Dark Arisen";"367500"
- [ ] "teso";"The Elder Scrolls Online";"306130"
- [ ] "elex";"ELEX";"411300"
- [ ] "enderal";"Enderal";"933480"
- [ ] "enderalspecialedition";"Enderal Special Edition";"976620"
- [ ] "endzoneaworldapart";"Endzone - A World Apart";"933820"
- [ ] "fableanniversary";"Fable Anniversary";"288470"
- [ ] "factorio";"Factorio";"427520"
- [ ] "fallout3";"Fallout 3";"22300"
- [ ] "fallout3";"Fallout 3: Game of the Year Edition";"22370"
- [ ] "fallout4vr";"Fallout 4 VR";"611660"
- [x] "fallout4";"Fallout 4";"377160"
- [ ] "fallout76";"Fallout 76";"1151340"
- [ ] "fantasygroundsunity";"Fantasy Grounds Unity";"1196310"
- [ ] "farmingsimulator19";"Farming Simulator 19";"787860"
- [ ] "fellsealarbitersmark";"Fell Seal: Arbiter's Mark";"699170"
- [ ] "finalfantasy12";"Final Fantasy XII: The Zodiac Age";"595520"
- [ ] "galacticcivilizations3";"Galactic Civilizations III";"226860"
- [ ] "gardenpaws";"Garden Paws";"840010"
- [ ] "goingmedieval";"Going Medieval";"1029780"
- [ ] "greedfall";"GreedFall";"606880"
- [ ] "grimdawn";"Grim Dawn";"219990"
- [ ] "grimrock";"Legend of Grimrock";"207170"
- [ ] "gta5";"Grand Theft Auto V";"271590"
- [ ] "hacknet";"Hacknet";"365450"
- [ ] "halflife2";"Half-Life 2";"220"
- [ ] "halothemasterchiefcollection";"Halo: The Master Chief Collection";"976730"
- [ ] "intothebreach";"Into the Breach";"590380"
- [ ] "jurassicworldevolution";"Jurassic World Evolution";"648350"
- [ ] "kenshi";"Kenshi";"233860"
- [ ] "kerbalspaceprogram";"Kerbal Space Program";"220200"
- [ ] "kingdomcome-deliverance";"Kingdom Come: Deliverance";"379430"
- [ ] "kingdomhearts02birthbysleepafragmentarypassage";"Kingdom Hearts 0.2 Birth by Sleep A fragmentary passage";"31337"
- [ ] "kingdomhearts3";"Kingdom Hearts III";"31337"
- [ ] "kotor";"Knights of the Old Republic";"32370"
- [ ] "kotor2";"Knights of the Old Republic II";"208580"
- [ ] "left4dead2";"Left 4 Dead 2";"550"
- [ ] "masseffect";"Mass Effect";"17460"
- [ ] "masseffect2";"Mass Effect 2";"901242"
- [ ] "masseffect3";"Mass Effect 3";"1238020"
- [ ] "masseffectlegendaryedition";"Mass Effect Legendary Edition";"1328670"
- [ ] "mbwarband";"Mount & Blade: Warband";"48700"
- [ ] "mbwithfireandsword";"Mount & Blade: With Fire & Sword";"48720"
- [ ] "microsoftflightsimulator";"Microsoft Flight Simulator";"1250410"
- [ ] "monsterhunterworld";"Monster Hunter: World";"582010"
- [ ] "moonlighter";"Moonlighter";"606150"
- [ ] "morrowind";"Morrowind";"22320"
- [ ] "mountandblade";"Mount & Blade";"22100"
- [ ] "mountandblade2bannerlord";"Mount & Blade II: Bannerlord";"261550"
- [ ] "nehrim";"Nehrim: At Fate's Edge";"1014940"
- [ ] "neverwinter";"Neverwinter Nights";"704450"
- [ ] "neverwinter2";"Neverwinter Nights 2";"2760"
- [ ] "falloutnv";"Fallout New Vegas";"22380"
- [ ] "nomanssky";"No Man's Sky";"275850"
- [ ] "oblivion";"Oblivion";"22330"
- [ ] "octopathtraveler";"Octopath Traveler";"921570"
- [ ] "outerwilds";"Outer Wilds";"753640"
- [ ] "outward";"Outward";"794260"
- [ ] "oxygennotincluded";"Oxygen Not Included";"457140"
- [ ] "pathfinderkingmaker";"Pathfinder: Kingmaker";"640820"
- [ ] "payday2";"Payday 2";"218620"
- [ ] "phoenixpoint";"Phoenix Point";"839770"
- [ ] "pillarsofeternity2";"Pillars of Eternity 2: Deadfire";"560130"
- [ ] "portal2";"Portal 2";"620"
- [ ] "prisonarchitect";"Prison Architect";"233450"
- [ ] "projectwingman";"Project Wingman";"895870"
- [ ] "reddeadredemption2";"Red Dead Redemption 2";"1174180"
- [ ] "residentevil22019";"Resident Evil 2 (2019)";"883710"
- [ ] "residentevilvillage";"Resident Evil Village";"1196590"
- [ ] "rimworld";"Rimworld";"294100"
- [ ] "sekiro";"Sekiro: Shadows Die Twice";"814380"
- [ ] "shadowrunreturns";"Shadowrun Returns";"234650"
- [ ] "shewillpunishthem";"She Will Punish Them";"1213740"
- [ ] "siegesurvivalgloriavictis";"Siege Survival: Gloria Victis";"21122"
- [ ] "skyrim";"Skyrim";"72850"
- [ ] "skyrimse";"Skyrim Special Edition";"489830"
- [ ] "skyrimvr";"Skyrim VR";"611670"
- [ ] "slimerancher";"Slime Rancher";"433340"
- [ ] "soulcaliburvi";"Soul Calibur VI";"544750"
- [ ] "spyroreignitedtrilogy";"Spyro Reignited Trilogy";"996580"
- [ ] "stalkercallofchernobyl";"S.T.A.L.K.E.R.: Call of Chernobyl";"41700"
- [ ] "stalkercallofpripyat";"S.T.A.L.K.E.R.: Call of Pripyat";"41700"
- [ ] "stalkerclearsky";"S.T.A.L.K.E.R. - Clear Sky";"20510"
- [ ] "stalkershadowofchernobyl";"S.T.A.L.K.E.R.: Shadow of Chernobyl";"4500"
- [ ] "starbound";"Starbound";"211820"
- [ ] "stardewvalley";"Stardew Valley";"413150"
- [ ] "starsector";"Starsector";"31337"
- [ ] "starwarsbattlefront22017";"Star Wars: Battlefront II (2017)";"1237950"
- [ ] "starwarsjedifallenorder";"Star Wars Jedi: Fallen Order";"1172380"
- [ ] "stateofdecay";"State of Decay";"329430"
- [ ] "stateofdecay2";"State of Decay 2";"495420"
- [ ] "streetsofrogue";"Streets of Rogue";"512900"
- [ ] "subnautica";"Subnautica";"264710"
- [ ] "subnauticabelowzero";"Subnautica: Below Zero";"848450"
- [ ] "survivingmars";"Surviving Mars";"464920"
- [ ] "teamfortress2";"Team Fortress 2";"440"
- [ ] "thesims3";"The Sims 3";"47890"
- [ ] "thesims4";"The Sims 4";"1222670"
- [ ] "torchlight2";"Torchlight II";"200710"
- [ ] "totalwarsagatroy";"A Total War Saga: TROY";"1099410"
- [ ] "totalwarthreekingdoms";"Total War: Three Kingdoms";"779340"
- [ ] "trialsofmana";"Trials of Mana";"924980"
- [ ] "undermine";"UnderMine";"656350"
- [ ] "untitledgoosegame";"Untitled Goose Game";"837470"
- [ ] "valheim";"Valheim";"892970"
- [ ] "vtmbloodlines";"Vampire: The Masquerade - Bloodlines";"2600"
- [ ] "warhammer40000gladiusrelicsofwar";"Warhammer 40,000: Gladius - Relics of War";"489630"
- [ ] "warthunder";"War Thunder";"236390"
- [ ] "witcher";"The Witcher";"20900"
- [ ] "witcher2";"The Witcher 2";"20920"
- [ ] "witcher3";"The Witcher 3";"292030"
- [ ] "witcher3";"The Witcher 3";"499450"
- [ ] "wolcenlordsofmayhem";"Wolcen: Lords of Mayhem";"424370"
- [ ] "worldoftanks";"World of Tanks";"1407200"
- [ ] "x4foundations";"X4: Foundations";"392160"
- [ ] "xcom2";"XCOM 2";"268500"
- [ ] "xrebirth";"X: Rebirth";"2870"

**Comment by frostworx** [comment]
**A _(more than)_ complete list with steps for a clean test _(to iron out possible 3rd party side effects/bugs)_**

_using Fallout New Vegas for the example_:


- `$ stl version`
  steamtinkerlaunch-v9.1.20220217

- `$ mv ~/.config/steamtinkerlaunch ~/.config/steamtinkerlaunchOLD`

- `$ rm -rf /dev/shm/steamtinkerlaunch`

- fresh NV install _(at least no old 22380 compatdata, no old vortex/mod files in the game dir - redownload not necessarily required)_

- start NV with proton-7.0-1 _(initially using steamtinkerlaunch won't install steam common redistributables - never finished debugged this and possibly won't)_

- exit NV

- $ `steamtinkerlaunch vortex start` _(*wait*)_

- click Games-> Fallout: New Vegas -> Manage

- "Give permission" on Access denied requester

- make sure that the "Mod staging folder" path is correct under Settings -> MODS _(here Z:\media\ssdeam4\SteamLibrary\Vortex\{GAME}\mods)_

- optionally compare the path with
  $ `grep falloutnv /dev/shm/steamtinkerlaunch/vortset.cmd`
  Vortex.exe --set settings.mods.installPath.falloutnv=true
  Vortex.exe --set settings.mods.installPath.falloutnv=\"Z:\\media\\ssdeam4\\SteamLibrary\\Vortex\\{GAME}\\mods\"
  Vortex.exe --set settings.mods.activator.falloutnv=\"hardlink_activator\"

- _(authorize nexus)_

- install/enable some mods

- close Vortex

- enable Vortex for NV in steam using steamtinkerlaunch _(f.e. drag&drop the game into the 'Vortex' category)_

- enable steamtinkerlaunch as compatibility tool for NV

- Start the game _(I let timeout steamtinkerlaunch and Vortex requester, optionally make a choice in an additional requester when you installed ScriptExtender)_

- report [here](https://github.com/frostworx/steamtinkerlaunch/issues/418) including the logfile _(`/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`)_

**Comment by henkery** [comment]
Following the steps exactly as writting above on Pop_Os! 21.10, clean up first by reinstalling new STL and clean FNV

Vortex does not autodetect FNV so I set the path myself to my z drive
the step ""Give permission" on Access denied requester" does not occur when setting my managed path to "Z:\home\iroha\\.steam\debian-installation\steamapps\common\Fallout New Vegas"
instead vortex gives me "game location not writeable: Z:\Vortex\falloutnv\mods"

Comparing the values with `grep falloutnv /dev/shm/steamtinkerlaunch/vortset.cmd`
Give me:
Vortex.exe --set settings.mods.installPath.falloutnv=true
Vortex.exe --set settings.mods.installPath.falloutnv=\"Z:Vortex\\{GAME}\\mods\"
Vortex.exe --set settings.mods.activator.falloutnv=\"hardlink_activator\"

Which seem to refer to invalid paths

I do note some warnings and errors in the terminal that starts vortex:
sed: -e expression #1, char 0: no previous regular expression
df: '': No such file or directory
df: '': No such file or directory
df: '': No such file or directory
df: '': No such file or directory
Sat Feb 19 01:10:54 PM CET 2022 INFO - startVortex - Starting Vortex without options

I assume it fails an attempt to symlink to the vortex prefix
also Vortex compains about dotnet not being properly installed but that doesn't seem to stop it from running
Edit: attached log
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8102162/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
Thanks for testing. Please append the corresponding log _(will add that to the steps above as well)_

**Edit**: Seems like autogenerating/creating a compatible staging directory did not work for you (maybe a more common problem(?)
You could check `~/.config/steamtinkerlaunch/vortex/stages.txt` for invalid/incomplete paths _(and/or remove them, and add compatible paths instead)_

Adding a staging path is also possible via steamtinkerlaunch commandline like:
`steamtinkerlaunch vortex stage /some/valid/path`

**Edit2:** Please see also the corresponding wiki: https://github.com/frostworx/steamtinkerlaunch/wiki/Vortex#vortex-stages

**Comment by henkery** [comment]
Setting a stagepath using `steamtinkerlaunch vortex stage /some/valid/path` before starting vortex for the first time seems to work (delete .config/steamtinkerlaunch, reinstall vortex and set stargepath to in my case /home/iroha/Vortex/) and mods can be installed/managed
Adding a stagepath after vortex has already started once results in the previous behaviour
Edit, added log
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8102199/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
Please append the corresponding log

edit: ah, thx for the log.
This clearly helps for further debugging:
`setGameVortexStaging - Mount point of partition where the game is installed: ''`

I'll _soon_ add some more corresponding logs and validity checks in functions `prepareVortexGame` and `setGameVortexStaging`
Probably only requires a simple fix after some more debugging/testing.

**Comment by frostworx** [comment]
please retest with above commit.

**Comment by henkery** [comment]
Running with the new commit
when no stagepath is added manually, stages.txt is not generated
When adding a stagepath after a first run of vortex, vortset.cmd does not contain any of the plugin paths causing vortex to misbehave
Adding stagepath before a first run also causes the plugin paths to not be added to vortset.cmd

[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8102524/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
Excellent - those two lines are important:
```
Sat Feb 19 04:51:22 PM CET 2022 INFO - setGPfxFromAppMa - Found WINEPREFIX '/home/iroha/.steam/debian-installation/steamapps/appmanifest_220200.acf
/home/iroha/.steam/debian-installation/steamapps/compatdata/220200/pfx' in 'appmanifest_220200.acf'
Sat Feb 19 04:51:22 PM CET 2022 ERROR - prepareVortexGame - variable VGAMEDIR '' is no valid directory - can't continue
```

Will look into this soon when I find the time.

**Comment by frostworx** [comment]
@henkery what does
`steamtinkerlaunch list am | grep 220200`
return?

**Comment by henkery** [comment]
> @henkery what does `steamtinkerlaunch list am | grep 220200` return?

iroha@pop-os:~$ steamtinkerlaunch list am | grep 220200
/home/iroha/.steam/debian-installation/steamapps/appmanifest_220200.acf
/home/iroha/.steam/debian-installation/steamapps/appmanifest_220200.acf

**Comment by frostworx** [comment]
thx for the quick test. Please test if above commit already fixes the problem.

**Comment by henkery** [comment]
With the new commit it works straight away regardless if I set a stagepath before run
Thanks a lot for the help!
I will leave the log here if you want to take a peek regardless
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8102739/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
Thanks a lot for testing, very appreciated! :)

**Comment by name-changer** [comment]
Edit: I fixed it by changing the file permissions, so that my user can access the txt-file. Now Fallout 4 is detected and added to Vortex! I'll test if I can actually add mods now. No idea why the permissions weren't correct though. 

In any case: sorry for the noise, and thanks for your work!

Edit2: Everything including f4se seems to work now! Great!

Previous message:

---

Hi, I use the latest STL (steamtinkerlaunch-v9.1.20220220) on Linux Mint 20.3. 
Just for context: since Mint has the glibc-problem and doesn't work with `Proton-6.17-STL-1`, I have set `USEVORTEXPROTON="Proton-7.2-GE-2` in `global.conf` before installing Vortex. This seems to work fine for the dot.net and Vortex install.

Unrelated to this I have a problem though: when STL tries to detect the games I see an error in the console: 
`grep: /usr/share/steamtinkerlaunch/misc/vortexgames.txt: Permission denied` 
This is printed four times. 

After that Vortex starts fine, but it doesn't show any autodetected games (Fallout4 in my case, which has the steam id 377160).

Here is the relevant section in the stl.log, the IDs are reported as not listed, but that's probably simply the failing grep calls.

```
Sat 19 Feb 2022 09:39:31 PM CET SKIP - prepareVortexGame - Skip game '219990' is not supported by Vortex or the ID is not listed in '/usr/share/steamtinkerlaunch/misc/vortexgames.txt'
Sat 19 Feb 2022 09:39:31 PM CET SKIP - prepareVortexGame - Skip game '367500' is not supported by Vortex or the ID is not listed in '/usr/share/steamtinkerlaunch/misc/vortexgames.txt'
Sat 19 Feb 2022 09:39:31 PM CET SKIP - prepareVortexGame - Skip game '377160' is not supported by Vortex or the ID is not listed in '/usr/share/steamtinkerlaunch/misc/vortexgames.txt'
Sat 19 Feb 2022 09:39:31 PM CET SKIP - prepareVortexGame - Skip game '427520' is not supported by Vortex or the ID is not listed in '/usr/share/steamtinkerlaunch/misc/vortexgames.txt'
Sat 19 Feb 2022 09:39:31 PM CET INFO - prepareAllInstalledVortexGames - Applying Vortex settings for all games via autogenerated cmd '/dev/shm/steamtinkerlaunch/vortset.cmd'
Sat 19 Feb 2022 09:39:31 PM CET INFO - updateWinRes - Window 'SteamTinkerLaunch-PrepareVortexGameStatus' is running - polling the resolution
Sat 19 Feb 2022 09:39:31 PM CET INFO - updateWinRes - Found new Window Resolution '1029x37' for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Sat 19 Feb 2022 09:39:37 PM CET INFO - prepareAllInstalledVortexGames - Symlinks, registry entries and vortex settings for all found supported games should be ready at this point for Vortex
Sat 19 Feb 2022 09:39:37 PM CET INFO - startVortex - Starting Vortex without options
```

I could try to change the owner for `/usr/share/steamtinkerlaunch/misc/vortexgames.txt`, but I'm not sure whether that's a good idea?

**Comment by frostworx** [comment]
apparently there is no interest to contribute to this list, so closing here
