### ISSUE TITLE
add obs

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#42]
add obs support
with waiting for game window (similar soultion already implemented in sbs-vr).
I personally don't stream/record anything so no idea which features make sense here.
--startstreaming
--startrecording
--startreplaybuffer
each with an own shortcut (steam category) should do it, right?

**Comment by arrowgent** [comment]
instead of bloating with obs/ssr maybe consider a straight FFMPEG configuration
if your goal is to record the gameplay

ive no idea how recording with terminal using ffmpeg works however.
i dont know if mic can be added, how any input/output works
nothing useful


but suggestion to bypass obs entirely and use the actual tool that is doing the recording
SSR might be useful as a window so you can click record and some basic options, however.

**Comment by frostworx** [comment]
Adding ffmpeg might be an option in theory, but most people simply use obs and/or SSR, so I see no reason to not support it
_(as in the decision to install this "bloat" was already made before)_
The function should just save the user some clicks to start the recorder when the game is ready, not more, not less.
ffmpeg on the other hand requires very much fine-tuning and as I'm personally totally not interested in recording any gameplay I won't mess around with finding a good default recording command. I don't like bloat as well, so understand your motivation though.

**Comment by thomasfinstad** [comment]
I used OBS with as a shadowplay replacement so I could just click a hotkey to save the last X minutes of gameplay. I think obs would fit perfectly into this tinkering system, but be aware that if the replay buffer (and probably record/stream too) is running obs will have a pop-up of "do you want to stop even though you are recording/streaming" so maybe a signal or automatic key press to stop stuff before sending the stop signal is needed.

This all becomes unclear and probably very individual, as you would not want your stream to stop if the game crashes etc.

**Comment by frostworx** [comment]
stl already has support for
https://github.com/frostworx/steamtinkerlaunch#ReplaySorcery
which practically does the same (right?)

**Comment by frostworx** [comment]
[Looks like](https://obsproject.com/wiki/Launch-Parameters) obs has no command line option to directly record/stream a specific window id. Strange but true.
Makes implementing it into stl pretty useless then though.

**Comment by frostworx** [comment]
won't happen
