### ISSUE TITLE
Commands starting with "steamtinkerlaunch launcher" do nothing

### ISSUE THREAD

**Issue by wing798213** [sonic2kk/steamtinkerlaunch#422]
Hello.

CLI commands such as "steamtinkerlaunch launcher auto" or "steamtinkerlaunch launcher menu" do nothing. I've tried on several arch linux machines (with zen kernel and vanilla one) and with clean install on debian 11 virtual machine. Using "steamtinkerlaunch settings" or "steamtinkerlaunch gs <game_id>" opens GUI window properly. Also "steamtinkerlaunch list <owned|installed>" outputs correct ids list.

STL versions: 9.1.20220225 (debian), 9.0.1 (arch linux)
OSes: Linux debian 5.10.0-11-amd64 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux, Linux winghost 5.16.11-arch1-1 SMP PREEMPT Thu, 24 Feb 2022 02:18:20 +0000 x86_64 GNU/Linux

Also tried to strace not working CLI auto command which gived me some ENOTTY, ESPIPE and EBADF errors while working with *.desktop files, so i think problem could be on my side, but i don't know what next step to do to solve said errors.

Arch logs: ["steamtinkerlaunch launcher menu"](https://github.com/frostworx/steamtinkerlaunch/files/8146323/arch_menu.log) (same after auto command), ["steamtinkerlaunch launcher auto"](https://github.com/frostworx/steamtinkerlaunch/files/8146327/arch_auto.log) also ["steamtinkerlaunch launcher auto" strace log"](https://github.com/frostworx/steamtinkerlaunch/files/8146328/arch_auto_strace.log).

Debian logs: ["steamtinkerlaunch launcher menu"](https://github.com/frostworx/steamtinkerlaunch/files/8146337/debian_menu.log), ["steamtinkerlaunch launcher auto"](https://github.com/frostworx/steamtinkerlaunch/files/8146339/debian_auto.log) and ["steamtinkerlaunch launcher auto" strace log](https://github.com/frostworx/steamtinkerlaunch/files/8146340/debian_auto_strace.log).

**Comment by frostworx** [comment]
Hi there,
thanks for the comprehensive report!
tbh I'm surprised to see that anybody even uses the "launcher" option :)
I can't reproduce it here (yet), but it looks like something is wrong with your desktop files indeed.
I don't think this is a bigger problem _(probably just some missing function somehere)_ and I'll add some more debug options soon

**Comment by wing798213** [comment]
Thanks. Looking forward for it.

**Comment by frostworx** [comment]
Hi again!
I just re-tried with a complete clean `~/.config/steamtinkerlaunch` and `/dev/shm/steamtinkerlaunch` directory, to check if the "auto" download still works, and it is working fine for me.
So I re-checked your [steamtinkerlaunch launcher auto](https://github.com/frostworx/steamtinkerlaunch/files/8146327/arch_auto.log) log again and noticed this line:
`Сб 26 фев 2022 12:48:21 +04 SKIP - GLgui - No games found in '/dev/shm/steamtinkerlaunch/desktopfiles/installed' or directory itself not found`

which is very likely the problem. Would you please check if the directory `/dev/shm/steamtinkerlaunch/desktopfiles/installed`
does even exist? It should contain symlinks to your `auto` created desktopfiles in
`~/.config/steamtinkerlaunch/games/desktop/`
_(please also check if the latter dir exists and contains some desktop files)_

**Comment by frostworx** [comment]
Would be great if you could also try
`steamtinkerlaunch update gamedata`
_(ideally with clean config again)_
and check the corresponding log.
It basically does the same what the "auto" part would do in the original command.

edit:
would be interesting as well if
`steamtinkerlaunch list installed`
returns some ids. It should show all the SteamAppIds of all your installed games.
If it doesn't, your installed games are not found for whatever reason, which would explain the core problem as well.

edit2: just added checks everywhere, where the autodetected list of games is used.

**Comment by wing798213** [comment]
> /dev/shm/steamtinkerlaunch/desktopfiles/installed
> /.config/steamtinkerlaunch/games/desktop/

Both directories exist and empty.

> steamtinkerlaunch update gamedata

Downloads headers of steam games and stores them correctly in ~/.config/steamtinkerlaunch/games/header/.


>steamtinkerlaunch list installed

I've already tried this command and mentioned this at first message. It gives correct output at clean install as well.

Also strace log says:
>newfstatat(AT_FDCWD</home/wing>, "/home/wing/.config/steamtinkerlaunch/games/desktop/362890.desktop", 0x7ffcb3fa9f10, 0) = -1 ENOENT

But previous command
>newfstatat(AT_FDCWD</home/wing>, "/home/wing/.config/steamtinkerlaunch/games/header/362890.jpg", {st_mode=S_IFREG|0644, st_size=42041, ...}, 0) = 0

Works well.

Clean install successfully creates all (or most) directories both in .config and in /dev/shm with configs and stuff.

**Comment by wing798213** [comment]
Forgot to mention that read and write rights at that *.desktop files directory given to current user. I didn't changed anything but first of all checked permissions.

**Comment by frostworx** [comment]
> > steamtinkerlaunch list installed
> 
> I've already tried this command and mentioned this at first message. It gives correct output at clean install as well.

whoops, sorry. apparently I haven't checked close enough _(going offline soon)_

After the header files were downloaded
`steamtinkerlaunch cdi all` should generate all corresponding desktop files in `~/.config/steamtinkerlaunch/games/desktop`

Would be interesting if this works for you _(or what the log says)_

**Comment by wing798213** [comment]
>steamtinkerlaunch cdi all

Works without any output. No *.desktop files generated.
Same strace output with ENOENT errors.

**Comment by frostworx** [comment]
log please

**Comment by wing798213** [comment]
[31337.log](https://github.com/frostworx/steamtinkerlaunch/files/8146468/31337.log)

**Comment by frostworx** [comment]
Please re-test with current git master. Just added some more changes.
For unknown reason your installation tries to create a desktop file in `desktopfiles` instead of `desktop`
which should work of course as well, but only is used when the variable `STLPLAY` is not 1.
Need to find out why I introduced that variable if logs of your re-test don't help further.

**Comment by wing798213** [comment]
[31337.log](https://github.com/frostworx/steamtinkerlaunch/files/8146506/31337.log)
[31337 menu.log](https://github.com/frostworx/steamtinkerlaunch/files/8146509/31337.menu.log)
>~/.config/steamtinkerlaunch/games/desktop/

Contains no files.

**Comment by frostworx** [comment]
add more logging just right now - please check again.
as far as I can tell currently the only option which is left ist that getGameName function doesn't find the game names for your games.
if so this needs deeper debugging, but I'm afraid not today.

**Comment by wing798213** [comment]
[31337_r667_auto.log](https://github.com/frostworx/steamtinkerlaunch/files/8146540/31337_r667_auto.log)
[31337_r667_menu.log](https://github.com/frostworx/steamtinkerlaunch/files/8146544/31337_r667_menu.log)
Look like it is the case.

**Comment by frostworx** [comment]
bingo! thanks for testing, very appreciated! I'll see what I can do

**Comment by wing798213** [comment]
Thanks to you. You're making amazing software.

**Comment by frostworx** [comment]
If you want, it was great if you would test if
`steamtinkerlaunch createappinfo installed`
generates binary files in `~/.config/steamtinkerlaunch/games/appinfo/`
(might take some time, depending on how big your game collection is :)).

The generated files are extracted from the steam appinfo binary blob and
are optionally used for finding the game name in the function [getGameName](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L732)

If those files are generated correctly, I'd guess that `steamtinkerlaunch cdi all` should work correctly afterwards.

**Comment by wing798213** [comment]
>steamtinkerlaunch createappinfo installed

[r668_createappinfo.log](https://github.com/frostworx/steamtinkerlaunch/files/8146610/r668_createappinfo.log)

Actually creates *.bin files.

>steamtinkerlaunch cdi all

[r668_cdi_all.log](https://github.com/frostworx/steamtinkerlaunch/files/8146612/r668_cdi_all.log)
Cycles 4 times over every *.bin file but with static id.

[r668_menu.log](https://github.com/frostworx/steamtinkerlaunch/files/8146615/r668_menu.log)
And sorry, but no luck.

**Comment by frostworx** [comment]
thanks for testing! giving up for today (really weird bug)

**Comment by wing798213** [comment]
You are welcome.

**Comment by frostworx** [comment]
just added some more log output which should catch any possible result in the getGameName function.
Would be great if you'd test again.

**Comment by wing798213** [comment]
Sure.
[r669_createappinfo.log](https://github.com/frostworx/steamtinkerlaunch/files/8147024/r669_createappinfo.log)
[r669_cdi.log](https://github.com/frostworx/steamtinkerlaunch/files/8147026/r669_cdi.log)
[r669_menu.log](https://github.com/frostworx/steamtinkerlaunch/files/8147027/r669_menu.log)

~/.local/share/Steam/steamapps/appmanifest_257420.acf is on its place. Also it's probably strange that there are two same strings in one file path one by one.

**Comment by frostworx** [comment]
Yeah that is probably the main problem _(maybe one of those weir Steam symlinks?)_
Do you also get a duplicate with 
`steamtinkerlaunch list am | grep 257420`
?
Sorting duplicates out of `listAppManifests` probably fixes this, but it would be still interesting why this happens.

**Comment by wing798213** [comment]
Yeah, got duplicate.

**Comment by frostworx** [comment]
thx! just checked here as well and also have some duplicates _(4/506)_
mom, will check if `sort -u` in `listAppManifests` should be find and commit it if so

**Comment by frostworx** [comment]
Just made a new commit, which should fix this properly. This could have caused several other problems as well, so thanks a lot for your patient testing! 👍

**Comment by wing798213** [comment]
That's strange. Now one *.desktop file was created at ~/.config/steamtinkerlaunch/games/desktopfiles/ but without symlink to /dev/shm/steamtinkerlaunch/desktopfiles/installed/ directory. Also application names were detected correctly.

[r670_createappinfo.log](https://github.com/frostworx/steamtinkerlaunch/files/8147210/r670_createappinfo.log)
[r670_cdi.log](https://github.com/frostworx/steamtinkerlaunch/files/8147211/r670_cdi.log)
[r670_menu.log](https://github.com/frostworx/steamtinkerlaunch/files/8147212/r670_menu.log)

**Comment by frostworx** [comment]
Seems like you have a talent for ugly bugs :)
I already located the problem and just need to find out how to properly fix it.

**Comment by frostworx** [comment]
I hope this commit should fix that issue as well.

**Comment by wing798213** [comment]
Now there are *.desktop files for all games but no links to /dev/shm/steamtinkerlaunch/desktopfiles/

[r671_createappinfo.log](https://github.com/frostworx/steamtinkerlaunch/files/8147280/r671_createappinfo.log)
[r671_cdi.log](https://github.com/frostworx/steamtinkerlaunch/files/8147288/r671_cdi.log)
[r671_auto.log](https://github.com/frostworx/steamtinkerlaunch/files/8147289/r671_auto.log)
[r671_menu.log](https://github.com/frostworx/steamtinkerlaunch/files/8147290/r671_menu.log)

Manual copy of *.desktop files allow normal launch of GUI of the main menu.

**Comment by frostworx** [comment]
I just tried to reproduce this with a clean `/dev/shm/steamtinkerlaunch` and `~/.config/steamtinkerlaunch/`, but 
`steamtinkerlaunch launcher auto`
just works fine without any other commands required.
Could you please re-test only
`steamtinkerlaunch launcher auto`
also with both directories cleaned?
_(clean `/dev/shm/steamtinkerlaunch` could be already enough)_

**Comment by wing798213** [comment]
[r671_auto_re.log](https://github.com/frostworx/steamtinkerlaunch/files/8147356/r671_auto_re.log)

**Comment by frostworx** [comment]
oh, the problem seems to be simply that your `sharedconfig.vdf` doesn't contain your games `(1 found)`.
Maybe they changed something again and moved it into some other file _(did so as well with some other settings I just don't remember)_. My installation is pretty old and therefore might have both files.

**Comment by wing798213** [comment]
Just copying those files is not as difficult. Maybe i should just write alias for launcher auto with copying files.

**Comment by wing798213** [comment]
Also i'm using family sharing for two accounts. Both of them have several games so it's maybe not a case.

**Comment by frostworx** [comment]
It shouldn't be a big deal, now after the 2 other ugly bugs are fixed.
Can you confirm, that there is only 1 game in your `sharedconfig.vdf`?
This would _(probably)_ mean, that you do not use tags in Steam.
For the launcher with all installed games available the file `sharedconfig.vdf` is not even required though, so I'll replace the source here and it should work.

edit: ah, the symlinks created in `/dev/shm/steamtinkerlaunch/desktopfiles/installed/` are based on those desktop files which were found for the other steam tags found. as none is found on your systems, the installed dir is empty.
this needs to be changed in function `createCategoryMenus`

**Comment by frostworx** [comment]
above commit should fix this as well

**Comment by wing798213** [comment]
Works like a charm.

**Comment by wing798213** [comment]
I have checked several found sharedconfig.vdf and don't actually know which of them were used. Some of them had many apps ids. Current account have no entries at all.

**Comment by frostworx** [comment]
> Current account have no entries at all

ok, that explains the previously empty directory already.

**Comment by frostworx** [comment]
bumped [changelog](https://github.com/frostworx/steamtinkerlaunch/wiki/Changelog#changes-in-git-master) and closing here
