### ISSUE TITLE
Unable to open game menu, launches game anyway

### ISSUE THREAD

**Issue by ademlabs** [sonic2kk/steamtinkerlaunch#425]
Using version 9.2 (issue was present in previous release as well)
Configured Borderlands 3 and from Steam, on clicking play the countdown prompt appears. I click on the game menu to open the configuration but it doesn't do anything and launches the game anyway. Attaching log file [379720.log](https://github.com/frostworx/steamtinkerlaunch/files/8190252/379720.log)

I don't have this issue with other games (e.g. Doom 2016, Apex Legends, etc.)

Is there a way to completely reset the configuration for a game and starting anew?

**Comment by frostworx** [comment]
Please attach a Borderland 3 log. Can't think of any reason why single games should behave differently, but you never know...
Of course you can simply remove the game specific config from `~/.config/steamtinkerlaunch/gamecfgs/`
Alternatively you can check any time in the
CATEGORY -> GameCfgDiffers menu, which settings for your game are different to those configured in your DEFAULT settings

**Comment by ademlabs** [comment]
Oh sorry, I attached the wrong log file. Here is the Borderlands 3 one: [397540.log](https://github.com/frostworx/steamtinkerlaunch/files/8192593/397540.log)

I get an error when I try to open the settings for the game:

```
$ steamtinkerlaunch settings 397540
Unable to parse command line: Invalid byte sequence in conversion input
```

Here is my config file (had to append .md to it so that GitHub allows me to upload): 
[397540.conf](https://github.com/frostworx/steamtinkerlaunch/files/8192844/397540.conf.md)

I managed to open the favourites menu with `steamtinkerlaunch fav 397540` though, but once I click on "MAIN MENU", it seems to loop multiple time with the same error.

```
Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found

Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4840: : command not found
/usr/bin/steamtinkerlaunch: line 8095: writelog: maximum function nesting level exceeded (100)
```

**Comment by frostworx** [comment]
Thanks for the update!
I just pushed a little change, which should at least fix your "Invalid byte sequence" loop error.
For the main problem please elaborate on the following questions:
Looking at the new log it seems like the game started correctly. So, just to make sure I understood you correctly, the game starts fine using steamtinkerlaunch, but only the steamtinkerlaunch settings menu doesn't open, right?

If so I would have guessed that you cancelled the [Wait-Requester](https://github.com/frostworx/steamtinkerlaunch/wiki/Wait-Requester) "too often" (by default 3 times), so steamtinkerlaunch no longer asks, but looking at your config, this doesn't seem to be the case.

Could you please test, if you also do have the same problem after
- renaming/removing your '/home/arvind/.config/steamtinkerlaunch/meta/id/general/397540.conf' 
- or even rename the whole '/home/arvind/.config/steamtinkerlaunch' directory?

_(In both cases it would be best to test with a clean `/dev/shm/steamtinkerlaunch/` temp dir as well )_

**Comment by ademlabs** [comment]
> So, just to make sure I understood you correctly, the game starts fine using steamtinkerlaunch, but only the steamtinkerlaunch settings menu doesn't open, right?

Yes, that is correct.

> If so I would have guessed that you cancelled the [Wait-Requester](https://github.com/frostworx/steamtinkerlaunch/wiki/Wait-Requester) "too often" (by default 3 times) ...

I do see the Wait-Requester, but if I click on the MAIN MENU, it doesn't show the settings and instead launches the game. I believe that it errors out with the invalid byte sequence and proceeds to launch the game.

Thanks for the code update, I downloaded the latest script from the repository and although I don't see the looping errors, I do get them when invoking either settings or fav then clicking on the MAIN MENU.

```
$ grep ^PROGVERS /usr/bin/steamtinkerlaunch
PROGVERS="v9.3.20220306"

$ steamtinkerlaunch settings 397540
Unable to parse command line: Invalid byte sequence in conversion input

$ steamtinkerlaunch fav 397540
Unable to parse command line: Invalid byte sequence in conversion input
/usr/bin/steamtinkerlaunch: line 4785: : No such file or directory
/usr/bin/steamtinkerlaunch: line 4839: : No such file or directory
```

However, right after that I deleted the meta file 397540.conf and I can now view the settings window again!. Given that the error message mentions invalid byte sequence, I checked that meta conf file again and there was a UTF-8 character present:

```
GAMEWINDOW="Borderlands® 3  "
```
After removing that `®` character, the game settings window shows up.
Since this meta file is auto-generated, is there a way to correctly process those characters in the future?

**Comment by frostworx** [comment]
Hm, weird. I see no reason why this should fail here.
Sure, it would be possible to work around this by using base64, but TBH I'm not convinced that it is worth the time for the handful of games with those problems.

**Comment by frostworx** [comment]
The problem is, that GAMEWINDOW is used in multiple parts of the code.
I do not have the time and motivation to spend mucht time into this tbh, but you could try, if commenting out the three lines starting from [here](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L5139) fixes it for you. (I could simply remove the "@" from ther variable there then.
Sorry if this is a stupid question, but is there a special reason, why your system doesn't support UTF-8. I thought every language/charset is supported by it(?)

**Comment by ademlabs** [comment]
My system does support UTF-8, I don't have issues in any applications from what I could tell. Not sure why in that shell script it was problematic, I can try debugging the code and find the root cause.
Here is the output from `locale`:
```
$ locale
LANG=en_MU.UTF-8
LC_CTYPE=mfe_MU.UTF-8
LC_NUMERIC=mfe_MU.UTF-8
LC_TIME=mfe_MU.UTF-8
LC_COLLATE=mfe_MU.UTF_8
LC_MONETARY=mfe_MU.UTF-8
LC_MESSAGES=mfe_MU.UTF-8
LC_PAPER=mfe_MU.UTF-8
LC_NAME=mfe_MU.UTF-8
LC_ADDRESS=mfe_MU.UTF-8
LC_TELEPHONE=mfe_MU.UTF-8
LC_MEASUREMENT=mfe_MU.UTF-8
LC_IDENTIFICATION=mfe_MU.UTF-8
LC_ALL=
```

Quick conversion tests:
```
$ echo "Êàêèå-òî êðàêîçÿáðû" | iconv -t latin1 | iconv -f cp1251 -t utf-8
Какие-то кракозябры

$ echo "Какие-то кракозябры" | iconv -f utf-8 -t cp1251 | iconv -f latin1
Êàêèå-òî êðàêîçÿáðû
```

I'll leave this open for a few more days and see if I can find a solution, if not I'll close the issue.

**Comment by ademlabs** [comment]
Well, nevermind.
I added the `GAMEWINDOW="Borderlands® 3  "` line back in my meta file and issued a `steamtinkerlaunch settings 397540` and it seems to be working (you can see the Windowname in the UI correctly):

![capture](https://i.imgur.com/s9FU3B0.png)

As you said, there might have been an issue with encoding, and I believe my locale might have been messed up at a point, and recently I had changed some configs related to it and I cannot reproduce the issue anymore.
I'm closing this issue, thanks for the help!

**Comment by frostworx** [comment]
https://store.steampowered.com/app/502320/Boulder_Dash__30th_Anniversary/
does have a "®" as well in its gamewindow name, but I can't reproduce the issue here
_(won't download 138GB to test it with BL3)_
As steamtinkerlaunch does nothing regarding charsets, I'd suspect this is a yad glitch on your system.
(in case you want to compare, the Arch compiler flags for yad are [here](https://github.com/archlinux/svntogit-community/blob/packages/yad/trunk/PKGBUILD))

**Comment by frostworx** [comment]
heh, nice timing :)
glad you got it resolved.

**Comment by sonic2kk** [comment]
Apologies for bumping this closed issue. Just throwing my hat into the ring here: This affects, and I quote the game name: `LEGO® Star Wars™: The Skywalker Saga`. Other games like `LEGO® Star Wars™: The Complete Saga` works fine. Using latest git release of STL.

I read through and sort of see what's going on, but I just wanted to put somewhere here that the game is affected, in case others were confused :)

**Comment by frostworx** [comment]
weird issue, but I'm sure it is a yad issue.
I don't have above Lego games, so can't test.
can you find out the game window names of both games?

**Comment by sonic2kk** [comment]
So sorry for the late response (I just happened to come back to this issue out of curiosity). I had a look at the game window name for Skywalker Saga (920210) and the actual display game window name, and the name in `~/.config/steamtinkerlaunch/gamecfgs/title/920210.conf` is `LEGO Star Wars - The Skywalker Saga`. It doesn't have any of the trademark symbols used. This is also how the name is displayed in the SteamTinkerLaunch "Wait Timer" menu.

For Complete Saga (32440), the game window title (what shows up on the actual game's window) is `LEGO® Star Wars™: The Complete Saga`. What shows up in `32440.conf` is different: `Lego Star Wars Saga`. The symlinked name in `~/.config/steamtinkerlaunch/gamecfgs/title/` is also called `Lego Star Wars Saga`. As above, this is the name that is used by SteamTinkerLaunch as well.

Running `steamtinkerlaunch settings 920210` (the AppID for Skywalker Saga) returns `Unable to parse command line: Invalid byte sequence in conversion input`. Running `steamtinkerlaunch settings 32440` gives no error. I'm also getting some other output, but I've had this on pretty much every KDE install I've done (Arch or otherwise), but it might be relevant to the issue.

```
(process:23445): Gtk-WARNING **: 16:00:22.498: Locale not supported by C library.
        Using the fallback 'C' locale.
```

I had an issue a couple of years ago with Protontricks (a Zenity program) related to locales, but I fixed that by updating my locales (still using the same install). Protontricks also pushed a change back then to strip non-ASCII characters when necessary.

Perhaps I just need to sit down and figure out if something is up with my locales, maybe a KDE update messed something up :sweat_smile:

**Comment by frostworx** [comment]
thanks for testing @sonic2kk!
hm, sure, we could filter out some incompatible chars, but this would workaround a bug which should be properly fixed somewhere else `(so either yad or in its direct dependencies)`. tbh I do not really see a reason _(yet)_ to spend much time into it within steamtinkerlaunch for a handful of games. IMHO the correct approach would be debugging yad and send a PR or open an issue upstream (I guess a minimal example yad command line which reproduces this would already help).

**Comment by ademlabs** [comment]
@sonic2kk 
This error:
`(process:23445): Gtk-WARNING **: 16:00:22.498: Locale not supported by C library.
        Using the fallback 'C' locale.`

Is similar to what I had been experiencing. It's an issue with your locale not set up correctly. I managed to fix up my locales and this error of locale not being supported disappeared. This also fixed my issue with steamtinkerlaunch.

Can you perform a `locale` command and show the output? Can you also show the output of `env | grep LC_`?
