### ISSUE TITLE
Issues with starting stl on Steam Deck

### ISSUE THREAD

**Issue by bkamphues** [sonic2kk/steamtinkerlaunch#427]
Hey there, I've been experimenting with `steamtinkerlaunch-v9.3.20220306` on the Steam Deck to install some mods with Vortex, but I'm having some difficulties running `stl settings`. Installing and running Vortex itself worked great, but when I try to open the main menu (either through the command line or through the KDE shortcut) I get the following error:
`/usr/bin/steamtinkerlaunch: line 5156: : command not found`

Taking a look at that line it seems as though it's a problem with yad, but I haven't found a solution yet. 

I've tried installing through both the AUR and manually. Both seem to install fine...

Thanks in advance!

**Comment by frostworx** [comment]
Hi there,
good to hear that steamtinkerlaunch _(even with Vortex)_ basically works on the SteamDeck _(don't have mine yet)_.
Please upload a [logfile](https://github.com/frostworx/steamtinkerlaunch/issues/93), so I can _(try to)_ debug this further _(I hope the immutable system or some unknown valve customization doesn't conflict here)_

**Comment by bkamphues** [comment]
Included are logs for no ID and Skyrim Special Edition. I should mention that I disabled the read-only filesystem to install it in the first place.

[31337.log](https://github.com/frostworx/steamtinkerlaunch/files/8239519/31337.log)
[489830.log](https://github.com/frostworx/steamtinkerlaunch/files/8239520/489830.log)

**Comment by frostworx** [comment]
thx for the logs. Unfortunately nothing suspicious here _(the "`ERROR`" is simply wrong and should be removed, but is not related)_, so there is nothing I can do for now.

I can order my reserved Deck in Q2, but RL (summer) will prevent me from longer private computer sessions when I get it, so no idea when this can be fixed from my side.
I'll leave this open anyway, maybe someone is willing to look into this already before.

**Comment by bkamphues** [comment]
Alright, thank you for taking a look! My personal theory after taking a look at that line is that `$YAD` is not being found/used. I tried looking where that variable gets initialised, but couldn't find it. Maybe that contains a clue?

**Comment by frostworx** [comment]
`$YAD` is defined by default in this line:
https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L2375
which in turn will be written into your
`~/.config/steamtinkerlaunch/global.conf`
_(I hope both `~` and `/dev/shm/` are writable without any workarounds/tweaks required)_

so when `command -v "yad"` works for you in a terminal, it should be also found from steamtinkerlaunch.

edit: if you want to test if it is really found from within steamtinkerlaunch, you could for example add 
`command -v "yad" > /tmp/test.txt`
before the `main "$@" [line](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L18506)`
_(maybe also `env > /tmp/env.txt` has some interesting env variables(?))_

**Comment by bkamphues** [comment]
Alright, so I did both your suggestions. First thing I noticed, VIM/Nano/GNU Editor wouldn't let me edit it directly in `/usr/bin` because it had 'Too many symbolic links'. Which is weird, because the file properties don't show it being a symlink. Copied it over to my home folder and ran and edited it from there. The test.txt shows exactly what running it in the terminal does, but I still get that error. I found nothing weird in the env either. Eager to figure this out once you'll get your steam deck!

**Comment by frostworx** [comment]
thanks for the quick test! I'm curious as well where this ends :)

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/issues/431

**Comment by frostworx** [comment]
fyi: https://github.com/frostworx/steamtinkerlaunch/issues/437
