### ISSUE TITLE
Allow to set env variables either in global.conf or default_template.conf

### ISSUE THREAD

**Issue by leon22heart** [sonic2kk/steamtinkerlaunch#428]
There are some variables which are nvidia or dxvk specific which would be nice to be allowed to be custom set. 
3 of those DXVK_STATE_CACHE_PATH and _GL_SHADER_DISK_CACHE_PATH as well as _GL_SHADER_DISK_CACHE would pose no problem to be set by user.
Now we should either start steam through lutris with those env variables or terminal .
It would also be feasible although a little redudant to read those variable through an additinional custom Global.conf so that to avoid overwrite when upgrading steamtinkerlaunch.
One problem that i can guess is that some variables set by the users may conflict with those set by the dev in the other conf files.

**Comment by frostworx** [comment]
I guess [this](https://github.com/frostworx/steamtinkerlaunch/wiki/ENV-Variables) should already cover pretty much everything.
Users overriding any variable _(no matter how)_ are always on their own imho.

**Comment by leon22heart** [comment]
True. Everyone should take their own risks. Then for clarification any other variable (i only need those 3 cause i have a partition only for caches shared between systems) added to the default_template or global.conf is automatically loaded ? Cause the wiki did not clarify if those .confs are only for steamtinkerlaunch internal variables or custom ones may be added . Just to avoid messing anything too hard.

**Comment by frostworx** [comment]
You're right, it is not very clear indeed,
but yes, I meant ANY variable, it doesn't need to be known by steamtinkerlaunch.
Never tried to set it in the default_template though _(I'd guess it should work as well though)_, but only directly in the game config and the global config.

edit: just changed [the wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/ENV-Variables) a bit.

**Comment by leon22heart** [comment]
Perfect. Thank you. I was debating whether i should ask this in reddit as a question or post it here as a feature request.
You can close this issue since i am covered that it works at least in global.conf.

**Comment by frostworx** [comment]
both is fine.
For whatever reason I do not get a notifing mail on reddit when a new post is opened, but only for replies. Never looked into it and probably never won't. :)
Feature requests are generally fine of course, but I can't promise that I find the time to also actually implement it.

btw, whenever an issue is clearly solved (f.e. by confirming that everything works), it is perfectly fine for me, when the OP closes the issue themselves.
*closing here* :)
