### ISSUE TITLE
shaders function is missing the .fxh files for some shaders

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#429]
So I went ahead and tried out the reshade function and noticed that it's not downloading the complete shader files. Several .fxh shader files which are needed are missing such as ReShadeUI.fxh and ReShade.fxh which most shaders depend on and comes from https://github.com/crosire/reshade-shaders/tree/master/Shaders. 

To make sure that it wasn't some problem with my configuration or maybe an incomplete download  I deleted `.config/steamtinkerlaunch/` and `/dev/shm/steamtinkerlaunch/` and I can still reproduce the issue as you can see in this 
[ReShade.log](https://github.com/frostworx/steamtinkerlaunch/files/8274155/ReShade.log)

here is a 
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8274164/steamtinkerlaunch.log)
 as well though I don't see anything there.
 
 EDIT:  upon further investigation, the issue seems to be it's not downloading this reshade repo https://github.com/crosire/reshade-shaders/tree/master (which  I did select in shader download screen ) 
 
 EDIT2: manually downloading the repo fixed and using the shader repo installer function to install the manually downloaded files fixed all the compile issues except 
 for 
 ```
 Failed to compile "Z:\home\zany130\.local\share\Steam\steamapps\common\The Legend of Heroes Trails of Cold Steel III\bin\x64\reshade-shaders\Shaders\GrainSpread.fx":
Z:\home\zany130\.local\share\Steam\steamapps\common\The Legend of Heroes Trails of Cold Steel III\bin\x64\reshade-shaders\Shaders\GrainSpread.fx(65,16-92): error X4566: offset texture instructions must take offset which can resolve to integer literal in the range -8 to 7
```
 which is probably something else unrelated to STL.
 
 also, interestingly the first time it installed shaders it did so in a reshade-shaders folder in the root directory of the game and the second time it installed them in the same folder as the main executable like I originally expected it to

**Comment by frostworx** [comment]
the reshade-shaders repo, containing the core fxh files is not only still downloaded automatically,
but even is automatically enabled by steamtinkerlaunch _(even if deactivated by the user)_
to make sure the fxh files are always found. This has been heavily tested just a few months ago.
the whole shader management received a major overhaul at the same time, so I assume
you have some weird leftovers of a previous shader installation (had a temporary steamtinkerlaunch cleanup function, which covered most situations which you might have missed) or manually messed it up somewhere.
of course it is also possible that upstream changed something, but as the download still works as expected, this doesn't seem to be the case.
I won't look into this any time soon, because I don't find the time.

**Comment by zany130** [comment]
That's strange then i just tested again, after deleting all the reshade files in the game directory and `.config/steamtinkerlaunch` and `/dev/shm/steamtinkerlaunch/` the issue still persists. it does not download the main shader repo and when i go to install the shaders it's still missing

**Comment by frostworx** [comment]
the downloaded files are not in the game dir, but in the download dir...
the selected shader repos are completely **symlinked** into the gamedir _(wiki)_.

`: preprocessor error: could not open included file 'Z:\home\zany130\.local\share\Steam\steamapps\common\The Legend of Heroes Trails of Cold Steel III\reshade-shaders\Shaders\ReShade.fxh'`
-> this path has to be a symlink into the download dir.

**Comment by zany130** [comment]
yeah thats what I was saying. It's missing in the `.config/steamtinkerlaunch/downloads/shaders/` folder I have to manually add it there so when I install it, it gets symlinked into the game folder
after downloading the shaders and installing( or symlinking) them into the game folder this is how it looks 
```
ls .config/steamtinkerlaunch/downloads/shaders/
drwxr-xr-x    - zany130 16 Mar 17:04  fxshaders
drwxr-xr-x    - zany130 16 Mar 17:04  lord of lunacy reshade repository
drwxr-xr-x    - zany130 16 Mar 17:04  originalnicodr reshade repository
drwxr-xr-x    - zany130 16 Mar 17:04  pirate shaders
drwxr-xr-x    - zany130 16 Mar 17:04  prod80 reshade repository
drwxr-xr-x    - zany130 16 Mar 17:04  shaders (brussell1)
drwxr-xr-x    - zany130 16 Mar 17:04  sweetfx
.rw-r--r--   51 zany130 16 Mar 17:04  lastdl.txt
.rw-r--r--  171 zany130 17 Mar 00:26  repoblocklist.txt
.rw-r--r--  205 zany130 16 Mar 16:54  repocustomlist.txt
.rw-r--r-- 3.6k zany130 16 Mar 17:33  repolist.txt
```
When  I say Im downloading the main shader repo manually I'm putting it in there  so that the folder looks like this

```
ls .config/steamtinkerlaunch/downloads/shaders/
drwxr-xr-x    - zany130 16 Mar 17:04  fxshaders
drwxr-xr-x    - zany130 16 Mar 17:04  lord of lunacy reshade repository
drwxr-xr-x    - zany130 16 Mar 17:04  originalnicodr reshade repository
drwxr-xr-x    - zany130 16 Mar 17:04  pirate shaders
drwxr-xr-x    - zany130 16 Mar 17:04  prod80 reshade repository
drwxr-xr-x    - zany130 16 Feb  2021  reshade-shaders-master
drwxr-xr-x    - zany130 16 Mar 17:04  shaders (brussell1)
drwxr-xr-x    - zany130 16 Mar 17:04  sweetfx
.rw-r--r--   51 zany130 16 Mar 17:04  lastdl.txt
.rw-r--r--  171 zany130 17 Mar 00:26  repoblocklist.txt
.rw-r--r--  205 zany130 16 Mar 16:54  repocustomlist.txt
.rw-r--r-- 3.6k zany130 16 Mar 17:33  repolist.txt
```

**Comment by frostworx** [comment]
the directory is autocreated in `createProjectDirs`...

**Comment by zany130** [comment]
it doesn't get created for me for some reason that's why I have to put it in manually 

I mean the `reshade-shaders-master` folder everything else was downloaded and created by STL correctly

**Comment by frostworx** [comment]
just look at the code, if you don't believe me. or what exactly do you want?
ah: again they edited the initial comment and something completely different comes out.

**Comment by zany130** [comment]
I just wanted to help by reporting a bug in the code I don't want anything and I'm not saying I don't belive you. All I'm saying is that when I tested the the reshade function with this game this is want happens

**Comment by frostworx** [comment]
> I mean the `reshade-shaders-master` folder everything else was downloaded and created by STL correctly

"of course it is also possible that upstream changed something" - so maybe that?

**Comment by zany130** [comment]
the end result is the same something would need to be changed in STL for it to work as expected no? If its a bother for me to report bugs I will gladly keep them to myself its time that I could of been using for other things  just like you I don't have all the time in the world to be contributing or reporting bugs

**Comment by frostworx** [comment]
mom, why do you actually write "reshade-shaders-master"? where is the "-master" from?

**Comment by frostworx** [comment]
in case you missed it: the list of available shaders is created from `https://www.pcgamingwiki.com/wiki/`
see function `createShaderRepoList` and/or wiki.
if something changes there this can break things, so if that is broken then


```
I mean the reshade-shaders-master folder everything else was downloaded and created by STL correctly
"of course it is also possible that upstream changed something" - so maybe that?
```

Yes, that! This needs to be debugged and possible be fixed in the "$WGET" linke in the `createShaderRepoList` function.

**Comment by frostworx** [comment]
sorry, it was totally not my intention to close this bug one hour ago (in fact I did not even notice it up to now)

**Comment by frostworx** [comment]
so yes,
spent some more time into checking above function and wget line:
- still works
- no "-master" in reshade-shaders anywhere
- symlinks are still created correctly

*closing*...

**Comment by zany130** [comment]
Strange I'll look into it some more when I have time. I don't think it could be game-specific as none of that has anything to do with the game as it all things STL is doing in the background before the game even starts as I understand it, so maybe it's some bug with wget or something, if not STL?

Really strange, to confirm you did try the same reproduction steps I mentioned right?
I'll lay them out as a list so that it is easier to follow instead of a block of text 😅
So

1. delete all STL  files in the config and `/dev/shm/` folder
2. Delete all reshade files in the game directory
3. Start the game from steam with STL as a compat tool (don't think this should matter as long as your using STL to start the game)
4. go to the shader download tab (shader repos) in the main menu
5. Select all the repos you would like to use. ( I also selected the crosire repo ill try seeing what happens if I don't select it as you mentioned it should download it anyway?)
6.  go into the game menu to configure the game options
7. enable the 3 reshade options (enable, install, and update)
8. go into the game shaders option
9. select all the repos to install (at this point crosire repo is not listed for me, but all other previously selected repos in shader repos are)
10. launch the game
11. see the compiler error complaining about missing files
12. see that indeed crosire repo was not downloaded and symlinked

**Comment by zany130** [comment]
Just tested with different games and leaving the corsire repo disabled in the downloader to see if its some strange bug where if you enable it, it won't download. corsire repo is still NOT downloaded and needs to be downloaded manually. If it is helpful I can provide a video of this behavior.

here is the video https://youtu.be/cjHKCR3ZRjY

**Comment by zany130** [comment]
I think I may have figured something out @frostworx.  By default STL downloads all the repos it seems, and if I let it do that instead of specifying what repos I want it DOES download corsire repo and it gets symlinked correctly when you install the shaders. So there might be a bug in the shader selection logic

**Comment by frostworx** [comment]
Now after initial Steam Deck support landed, I took a look at this again.
Maybe it is my bad english, but imho your bug report is partly hard to understand.
f.e. you write something about `reshade-shaders-master` and never explain where this comes from, then the `.config/steamtinkerlaunch/downloads/shaders/` is missing.

I can reproduce though, that crosire reshade-shaders are not automatically enabled, downloaded when I f.e. only select one other repo in the shader repos gui. as a result repos/shaders which require that shader collection do not work.
There is definitely something wrong and needs to be fixed under certain circumstances. I'm sure it is a simple fix, but probably hard to find. This will be main next task to fix. promised :)
*reopening*

**Comment by frostworx** [comment]
I think [this commit](https://github.com/frostworx/steamtinkerlaunch/commit/dbeb6f974c3fa778a19ac552f274dbae2ecfeb94)
fixes the issue _(might be a bit bloated, but better too many checks, than too few)_
Thanks for detailed and patient reporting!

**Comment by zany130** [comment]
sorry, I'll try to be a bit more clear and concise `reshade-shaders-master` I got by git cloning the crosire repo since it was the master branch  I think it adds `master` at the end so that's why it had that.

So I am able to still reproduce the issue but it's very strange.

1. If I leave all shader repos enabled everything including crosire repo gets downloaded as normal

2. If I only disable ashtray everything downloads as normal

3. if I set it up like the following image 
![Screenshot_SteamTinkerLaunch-ShaderRepoDialog_2](https://user-images.githubusercontent.com/25832539/160962302-d65ce74f-d906-4467-aea0-dca09a78b9c5.png)

crosire repo is not downloaded. looking at 
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8385375/steamtinkerlaunch.log)
I can see it is being skipped for some reason

as you can see in the [repoblocklist.txt](https://github.com/frostworx/steamtinkerlaunch/files/8385379/repoblocklist.txt)
 
the crosire repo is not listed there (before the fix it would get written there)

**Comment by zany130** [comment]
So I tested by enabling repos I was disabling one by one (and deleting everything but the `repoblocklist.txt` in `/home/zany130/.config/steamtinkerlaunch/downloads/shaders/`)

 and found that disabling either `dh-reshade-shaders` or `reshade-shaders (daodan)` causes `reshade-shaders` from crosire to not download

so adding those two to the list from the image above allowed everything to download correctly

adding those two repos even fixes the issue on the older version (tried release 9.2) so maybe the recent fixes are not needed?

**Comment by frostworx** [comment]
thx for testing.
most changes in the recent commit are cosmetical _(the function `unblockrssub` automatically removes `reshade-shaders` from the block list in multiple places, so it is always checked)_
[this change](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L6912=) though, takes care that the grep for `reshade-shaders` starts and ends with `reshade-shaders` _(so both `dh-reshade-shaders` and `reshade-shaders (daodan)` are left alone)_
When you still have the  same problem I'd guess there's another function in the code which needs the same fix. *checking later today*

**Comment by frostworx** [comment]
another [fix](https://github.com/frostworx/steamtinkerlaunch/commit/c183e27b61cf85d27a5b0f52211c6517a4946ab7) just landed and should fix this properly now.
There's [another function](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L6940=) which might require a fix, but it is more complicated and probably is harmless _(for now)_

**Comment by zany130** [comment]
yup working as expected now just tested by deleting `/home/zany130/.config/steamtinkerlaunch/downloads/shaders/` don't know if you prefer to leave the issue open as you mentioned there is still another function that might need fixing? Though as it is now it's working for me don't see any issues.
