### ISSUE TITLE
SteamDeck and further steamtinkerlaunch development [outdated]

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#431]
My wifes steam deck arrived today:
after some minutes of initial configuration _(system update, set passwd, enable ssh, set / read-write, install steamtinkerlaunch using makepkg and several of its (optional) dependencies)_
I was able to successfully start steamtinkerlaunch via terminal/icon and also was able to install Vortex with the steamtinkerlaunch settings menu. So this seems to basically work so far.
~~Haven't tried configuring/starting any game with it yet though.~~

Edit: Just successfully started "Giana Sisters Twisted Dreams" using steamtinkerlaunch.
- steamtinkerlaunch menu opened
- I was able to auto-download the latest Proton GE and use it (gui is not very SteamDeck touch optimized though)
- the game starts fine!

But generally speaking using any custom system wide program installation will always be problematic on the SteamDeck, as future "firmware" updates will always delete your custom installations. This is no fun of course.
The only valid way seems to be either a full installation _(including all dependencies)_ within the /home directory or, probably more user-friendly a steamtinkerlaunch flatpak.

~~I'm still not interested in spending any time on working [flatpak support](https://github.com/frostworx/steamtinkerlaunch/issues/27) and as a "full installation working directory" is not really maintainable, I currently consider no longer working on SteamDeck compatibility _(or maybe steamtinkerlaunch generally)_ publicly.
_(for the same reason I also set the steamtinkerlaunch sub to private recently)_~~

Edit2: looks like adding automatic SteamDeck support without depending on flatpak is not too complicated, as most functions do already work as expected. So I'd say I'll add SteamDeck support, but no idea how long it takes.

Edit3: See WIP SteamDeck Wiki [below](https://github.com/frostworx/steamtinkerlaunch/issues/431#issuecomment-1079998760). Happy brainstorming!

**Comment by zany130** [comment]
ah ok understood would you mind it if I forked it and kept working on it? going to have a break from school soon so ill have some time to work on it. no promises I would be able to really do much as I'm still learning to code, but would suck to see such a cool project die.

**Comment by frostworx** [comment]
sure, you're still welcome to contribute patches and features.
a community needs to be vivid, any contribution helps to keep it alive of course.

**Comment by frostworx** [comment]
**WIP** SteamDeck Wiki _(happy suggesting!)_:


# [Steam Deck](https://github.com/frostworx/steamtinkerlaunch/wiki/SteamDeck)

So the SteamDeck is more or less available and fortunately my wife was lucky enough to get one early _(for me :))_

Currently _(2022.03)_ it is possible to install custom packages systemwide _(f.e. using the regular Arch Linux package management using pacman)_,
but as any custom changes will be lost after a "firmware" update, installing steamtinkerlaunch and its dependencies systemwide is not sane option.

The alternative idea is, to use a special SteamDeck detect function, which automatically changes several configuration options required for the SteamDeck
and also installs missing dependencies into a seperate directory within the home directory.
Fortunately most hard-dependencies are already preinstalled in the official steamos installation, so just a few additional packages need to be installed.
_(of course you're still invited to contribute [flatpak support](https://github.com/frostworx/steamtinkerlaunch/issues/27))_


# How to install on SteamDeck

Simply download the main `steamtinkerlaunch` script and start it as deck `user`.
_(the downloaded script can be removed afterwards, as it creates a new full installation itself - see below)_

The script will automatically configure everything required to make using `steamtinkerlaunch` a seamless experience on the SteamDeck:
- the script will create a new full `steamtinkerlaunch` installation into the `/home/deck/stl/prefix/` by cloning the current master from the steamtinkerlaunch` git project
- _(for now)_ this installation will always be updated to the latest commit automatically on every `steamtinkerlaunch` launch
- missing dependencies _(maybe also some optional)_ will be automatically downloaded and installed and extracted into `/home/deck/stl/deps/` and the `PATH` is expanded using it automatically
- yad, the main missing dependency, will be automatically installed from the default AppImage into `/home/deck/stl/deps/`
- `steamtinkerlaunch` will be automatically added a "Steam Compatibility Tool" by using a symlink to the `steamtinkerlaunch` executable in the `/home/deck/stl/prefix/` directory
- the default resolution for all steamtinkerlaunch windows without a resolution preset will be 1280x800 (SteamDeck screen resolution)
- all notifiers are automatically disabled, they seem to conflict with Steam running
- probalby multiple things are still missing in above list
- some features might not be available at all on the SteamDeck(?)

For SteamDeck related issues, suggestions, discussions please use this [extra Steam Deck issue](https://github.com/frostworx/steamtinkerlaunch/issues/272)
_(for flatpak [this one](https://github.com/frostworx/steamtinkerlaunch/issues/27))_

**Comment by frostworx** [comment]
new **Steam Deck** sticky upcoming _soonish_
