### ISSUE TITLE
backup prefix option not working

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#436]
compat delete option in the game menu deletes any backup prefix STL makes. Tried both unchecking and checking the backup option below it. According to the [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Compatdata-Delete) it should make a backup of the prefix before deleting it, which is why I thought maybe the backup prefix option was conflicting with this, but I tried with it both enabled and disabled and there is no backup of the folder after I run the game. Worse steam syncs this empty game prefix to steam cloud overriding my steam cloud backup.

**Comment by zany130** [comment]
So forgot to  mention that from what I understand  stl is supposed to make a copy of the folder in `/home/zany130/.local/share/Steam/steamapps/compatdata/` and it should be named `STEAMID_steamtinkerlaunch` apparently that folder is never made
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8375889/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
I had a look at the log, line 256 stands out to me: `Tue Mar 29 08:48:20 PM EDT 2022 INFO - backupSteamUser - backing up directory '/home/zany130/.local/share/Steam/steamapps/compatdata/991270/pfx/drive_c/users/steamuser' to '/home/zany130/.config/steamtinkerlaunch/backup/steamuser/id/991270'`

`backupSteamUser` is the function called to backup the steamuser directory (the Windows "user" folder in Proton) as far as I can tell. I did a test with the game Geometry Wars: Retro Evolved, started it up with a fresh prefix and chose the delete option in the game menu, clicked Save and Play, and the prefix was deleted. However, the folder for the steamuser was backed up to `~/.config/steamtinkerlaunch/backup/steamuser/id/`, as the log file stated.

Is a `steamuser` folder available at the path mentioned in the log file line I posted? If so, can you delete the `steamuser` folder at `/home/zany130/.local/share/Steam/steamapps/compatdata/991270/pfx/drive_c/users/` and replace it with the one found at `/home/zany130/.config/steamtinkerlaunch/backup/steamuser/id/991270'`?

If all that works, this may be a documentation issue.

**Comment by zany130** [comment]
NVM this was completly my bad I did consider that it might  no longer backup up to `/home/zany130/.local/share/Steam/steamapps/compatdata/` but I just looked through the wrong folders for it didn't relize that ther is a nicely named `backup` folder in stl config folder 😅 also just checked the wiki for the backup option it is also mentioned there so my bad 

@sonic2kk  no this is all properly been documented in the wiki this was just a case of user stupidity lol Nah  i was going by outdated info and didn't bother to check if it was up to date also realised it when I went trough the log which I also didn't look at beforehand 😓
