### ISSUE TITLE
Question: SBS 3d on a 3d TV possible?

### ISSUE THREAD

**Issue by oblitum** [sonic2kk/steamtinkerlaunch#443]
Hi. I wonder whether it's possible to have SBS 3d without having VR headset device? I just have an old 3d TV and glasses. I noticed from logs and wiki seems to imply that stl will always check the presence of a HMD when `RUNSBSVR` or `SBSVRRS` is `1`?

The wiki mentions it's possible to launch Vk3DVision, but it's confusing whether it's able to work and provide SBS 3D or just launch without errors but not functioning.

**Comment by frostworx** [comment]
hi,
it shouldn't be too complicated to enable SBS without depending on VR. I'll check that.
No, last time I tried, Vk3dVision was not working via Proton. I only added it to the wiki as further solutions which possibly could be added later:
[other implementations which hopefully do work one day using Linux/Proton](https://github.com/frostworx/steamtinkerlaunch/wiki/Side-by-Side-VR#other-implementations-which-hopefully-do-work-one-day-using-linuxproton=)

**Comment by oblitum** [comment]
> it shouldn't be too complicated to enable SBS without depending on VR. I'll check that.

I'm eager to try :)

**Comment by frostworx** [comment]
just gave it a quick look what needs to be done to make SBS working without vr.

Just to be sure, that we are talking about the same:
steamtinkerlaunch does no additional tricks to get the games with native SBS _(see [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Side-by-Side-VR#games-with-built-in-stereo3d-support=))_  working in VR - it just enables all VR stuff, automatically picks their game window and draws that window using vr-video-player in vr.

So the only thing I can do is adding non-vr support for [Playing games in Stereo3D using ReShade and Depth3D shader](https://github.com/frostworx/steamtinkerlaunch/wiki/Side-by-Side-VR#playing-games-in-stereo3d-using-reshade-and-depth3d-shader=)
If this is it what you want, this should be implemented very quickly.

Would be nice if you'd try it, by
commenting out `export RUNSBSVR=1` [here](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L13374=) and then enabling `SBSVRRS` in the corresponding game config _(or simply by adding the game to a `ReShadeVR` [Steam-Category](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Categories))_

If it works as expected I'd simply duplicate the `SBSVRRS` option to `SBSRS` with the required changes.

**Comment by frostworx** [comment]
whoops,. forgot to mention that I added `SBSRS` support in [this commit](https://github.com/frostworx/steamtinkerlaunch/commit/2f959bea1bcf9ad03bf34d7cced053a2e77505e8) (untested)

**Comment by oblitum** [comment]
I'm about to recompile the project and test this out now if life does not interrupt me at the moment. So, can you state what exactly I should do to try this, just set `SBSRS` to `1` is it? Okay. Also, about 

> steamtinkerlaunch does no additional tricks to get the games with native SBS _(see [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Side-by-Side-VR#games-with-built-in-stereo3d-support=))_ working in VR

I'm a little confused on this thing. I have a few old games that have this native SBS support, like, I have all Trines. It worked when I still used a Windows partition long time ago, I'm now just all into Proton. Okay, thing is, in Trine in Proton, this SBS 3D section has always been inactive on Linux. I have a GTX 1080TI with latest closed source drivers on Arch Linux. Will steamtinkerlaunch make something that will make this in-game SBS 3D settings page active? Is this what that section on Wiki is about? Or does this ReShade + Depth3D thing will kinda fake SBS regardless whether that section of the game is activated or not. Also, can it work on a game that doesn't come with such built in 3D settings page, say, can I pick Doom (not Eternal, the previous one) and have it with SBS 3D, I'm asking this because the ReShade + Depth3D section in the wiki refer to SBS 3D working on "regular games", and it's not precisely clear whether that means any game or games that have had SBS 3D natively.

**Comment by frostworx** [comment]
there is nothing to recompile - steamtinkerlaunch is a bash script.
Depth3d is a SBS Shader. ReShade loads that shader automatically and renders every regular game in SBS with it.
steamtinkerlaunch just automated that process. I'm not going to explain the functionality of ReShade or Depth3d in detail though, because they have their own project pages. Any contribution to steamtinkerlaunch wikis are welcome of course.

For almost all games with native/builtin sbs support you need to use the windows versions using Proton - the linux native builds do not have sbs mode as you already found out (besides the few where explicitely linux support is mentioned in the wiki).

steamtinkerlaunch has multiple "settings override configs which you can find in https://github.com/frostworx/steamtinkerlaunch/tree/master/misc/sbstweaks.
using `RUNSBSVR` those are automatically loaded and the supported games should start supporting their internal sbs
as automatable as possible. Adding another `RUNSBS` option which loads those settings without VR shouldn't be a bigger problem.

**Comment by oblitum** [comment]
> there is nothing to recompile - steamtinkerlaunch is a bash script.

Heh, sorry, I did notice that later (I'm just `paru -S`ing at the moment).

**Comment by frostworx** [comment]
`yay -S paru` up and running :)

**Comment by oblitum** [comment]
> the linux native builds do not have sbs mode as you already found out (besides the few where explicitely linux support is mentioned in the wiki)

Okay. To avoid any confusion, on

> this SBS 3D section has always been inactive on Linux

I meant just Proton games, and inactive sections in there (I know most native Linux games won't have it at all).

Let's see how it goes.

**Comment by frostworx** [comment]
wait a few minutes, atm I only added ReShade Depth3D support for you.
Just adding support for the native sbs games.

**Comment by oblitum** [comment]
I'm re-reading this to get it in detail, from your explanation I should `SBSRS = 1` but that doesn't mean I will get "multiple settings override configs which you can find in misc/sbstweaks", so I'll start a game, say, Trine 2 or 3, or Doom, without any of such settings specific of such games (in cases there's any), for that I would need a `RUNSBS` that's still to be made.

**Comment by oblitum** [comment]
FWIW, my TV has a generic emulated 3D option, which I'm unsure whether it's gonna have the same effect as ReShade + Depth3D on a regular game. I tried it on Mario in yuzu, very faint effect...

**Comment by frostworx** [comment]
just pushed the new commit.
now current master has SBS support for
- regular games by using Reshade/Depth3D (can be enabled using `SBSRS` (=`Stereo3D ReShade` in the GAME MENU - Shader section)). Alternatively drop the game into a "ReShadeSBS" Steam category
- games with built-in SBS support (can be enabled using `RUNSBS` (=`Stereo3D` in the GAME MENU - Misc section))  Alternatively drop the game into a "SBS" Steam category

**Comment by oblitum** [comment]
I'm trying it out atm... well, nothing is working and I'm trying to figure out from logs what's going on. At first I'm trying `SBSRS = 1` with DOOM. One important thing I guess for these window picking scripts is the window manager I'm using, and I use i3, and only have this one on my PC (I don't know how to use other stuff anymore). Do you know whether this works on i3? The most suspicious thing I'm hitting seems:

```
Mon Apr  4 06:01:45 PM -03 2022 INFO - updateWinRes - The Window 'SteamTinkerLaunch-OpenSettings' was closed - the resolution didn't change - nothing to do
```

So it seems for some reason resolution is not changing, and I dunno why. Can you state a relevant raw command I should try from command line to see error output or something? I'm checking source code anyway.

**Comment by oblitum** [comment]
It seems window picking is going fine on this test due:

```
Mon Apr  4 06:01:42 PM -03 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-OpenSettings'
Mon Apr  4 06:01:43 PM -03 2022 INFO - updateWinRes - Window 'SteamTinkerLaunch-OpenSettings' is running - polling the resolution
```

On this last test, just to avoid any conflict at that, as soon as I launch the game on steam, I swap to an empty desktop so that just the game window alone shows up in it (and the steamtinkerlaunch windows, which seems the one being picked/polled above).

I have this in `/dev/shm/steamtinkerlaunch/winres.log`:

```
Mon Apr  4 06:01:42 PM -03 2022 INFO - pollWinRes - Using GEOM '--geometry=1920x1080+0+0' from '/home/francisco/.config/steamtinkerlaunch/guicfgs/1920x1080/379720/SteamTinkerLaunch-OpenSettings.conf'
Mon Apr  4 06:01:42 PM -03 2022 INFO - updateWinRes - Starting resolution-poll for '/home/francisco/.config/steamtinkerlaunch/guicfgs/1920x1080/379720/SteamTinkerLaunch-OpenSettings.conf' with incoming '1920x1080'
Mon Apr  4 06:01:42 PM -03 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-OpenSettings'
Mon Apr  4 06:01:43 PM -03 2022 INFO - updateWinRes - Window 'SteamTinkerLaunch-OpenSettings' is running - polling the resolution
Mon Apr  4 06:01:45 PM -03 2022 INFO - updateWinRes - The Window 'SteamTinkerLaunch-OpenSettings' was closed - the resolution didn't change - nothing to do
Mon Apr  4 06:01:48 PM -03 2022 INFO - pollWinRes - Using GEOM '--geometry=929x1040+0+0' from '/home/francisco/.config/steamtinkerlaunch/guicfgs/1920x1080/379720/SteamTinkerLaunch-DownloadShadersStatus.conf'
Mon Apr  4 06:01:48 PM -03 2022 INFO - updateWinRes - Starting resolution-poll for '/home/francisco/.config/steamtinkerlaunch/guicfgs/1920x1080/379720/SteamTinkerLaunch-DownloadShadersStatus.conf' with incoming '929x1040'
Mon Apr  4 06:01:48 PM -03 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadShadersStatus'
Mon Apr  4 06:01:49 PM -03 2022 INFO - pollWinRes - Using GEOM '--geometry=929x1040+0+0' from '/home/francisco/.config/steamtinkerlaunch/guicfgs/1920x1080/379720/SteamTinkerLaunch-DownloadCustomProtonStatus.conf'
Mon Apr  4 06:01:49 PM -03 2022 INFO - updateWinRes - Starting resolution-poll for '/home/francisco/.config/steamtinkerlaunch/guicfgs/1920x1080/379720/SteamTinkerLaunch-DownloadCustomProtonStatus.conf' with incoming '929x1040'
Mon Apr  4 06:01:49 PM -03 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadCustomProtonStatus'
Mon Apr  4 06:01:49 PM -03 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadShadersStatus'
Mon Apr  4 06:01:50 PM -03 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadCustomProtonStatus'
Mon Apr  4 06:01:50 PM -03 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadShadersStatus'
Mon Apr  4 06:01:51 PM -03 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadCustomProtonStatus'
Mon Apr  4 06:01:51 PM -03 2022 SKIP - updateWinRes - Timeout waiting for Window 'SteamTinkerLaunch-DownloadShadersStatus'
Mon Apr  4 06:01:52 PM -03 2022 SKIP - updateWinRes - Timeout waiting for Window 'SteamTinkerLaunch-DownloadCustomProtonStatus'
```

**Comment by oblitum** [comment]
Now, I just tried native SBS on Trine 3, it's working absolutely stunning, really nice! Now I just wish to try it on regular games :-/ (not working as above).

While trying Trine 3, the SteamTinkerLaunch Game GUI simply didn't list Stereo3D, I've found Stereo 3D ReShade, but not simply "Stereo3D" alone, nor is that listed in `Trine 3.conf` file, so I just added `RUNSBS=1` manually, and it worked.

**Comment by frostworx** [comment]
append a full log please

**Comment by oblitum** [comment]
[DOOM.log](https://github.com/frostworx/steamtinkerlaunch/files/8417063/DOOM.log)

**Comment by oblitum** [comment]
Full log for initial run for `SBSRS = 1` of DOOM sent. As side note, not particularly relevant to this issue but notice the 404 line for `d3dcompiler_47_32.dll`:

```
Tue Apr  5 06:55:50 AM -03 2022 404 - prepareReshadeFiles - '/home/francisco/.config/steamtinkerlaunch/downloads/reshade/d3dcompiler_47_32.dll' missing - downloading
Tue Apr  5 06:55:50 AM -03 2022 INFO - dlCheck - Downloading 'd3dcompiler_47_32.dll' into '/home/francisco/.config/steamtinkerlaunch/downloads/d3dcompiler_47'
Tue Apr  5 06:55:50 AM -03 2022 INFO - notiShow - Message 'Downloading '/home/francisco/.config/steamtinkerlaunch/downloads/d3dcompiler_47/d3dcompiler_47.zip'' should go to StatusWindow
Tue Apr  5 06:55:50 AM -03 2022 INFO - dlCheck - 'wget -q --show-progress http://dege.freeweb.hu/dgVoodoo2/bin/D3DCompiler_47.zip -O /home/francisco/.config/steamtinkerlaunch/downloads/d3dcompiler_47/d3dcompiler_47.zip'
```

It's checking its presence at `/downloads/reshade/d3dcompiler_47_32.dll`, but at the end downloads/extracts it to `/downloads/d3dcompiler_47/`.  So this 404 always happens, I avoided that on restarts by putting in place a symlink.

**Comment by frostworx** [comment]
- forgot to upload the actual script changes, so support for games with builtin sbs was not even activated Edit: [fixed](https://github.com/frostworx/steamtinkerlaunch/commit/0795cacd007a34abfb586c8ff3e21617e9804370)
- minor dl glitch is fixed
- the logs looks sane and I just tested it. it works as expected. of course you still have to enable the autoinstalled shader in the autoinstalled reshade. some games might not work with reshade, this is out of steamtinkerlaunch scope of course

**Comment by oblitum** [comment]
> you still have to enable the autoinstalled shader in the autoinstalled reshade

That means exactly? Care to share wiki entry on that? I simply enabled `SBSRS = 1` and after the auto installs etc I just expected it to work. Also, can you state a good game (or game list) to try this that you know it works? I tried DOOM at first, which didn't work (I don't have DOOM eternal).

**Comment by oblitum** [comment]
I noticed that Alien Isolation has a sbstweak, but it's not listed on wiki for a game with native stereo 3d (nor does it have any internal game option at that), so, this one has been tried with ReShade I suppose? I have this game.

**Comment by frostworx** [comment]
You're welcome!
Also, "I'm not going to explain the functionality of ReShade or Depth3d in detail though, because they have their own project pages. Any contribution to steamtinkerlaunch wikis are welcome of course."
I personally don't use ReShade that often and I'm no source for a ReShade compatibility list. So check upstream here as well.

**Comment by oblitum** [comment]
Okay thanks.

> the logs looks sane and I just tested it.

This is a bit confusing to me, so the log:

```
Tue Apr  5 06:56:10 AM -03 2022 INFO - updateWinRes - The Window 'SteamTinkerLaunch-DownloadShadersStatus' was closed - the resolution didn't change - nothing to do
```

Is harmless. I'll try further and check ReShade docs. I'll close this as question and feature seems mostly solved. Many thanks for the additional options.

**Comment by frostworx** [comment]
steamtinkerlaunch automatically stores the window size of resized windows (to reload them in that resolution on the next run)
`Tue Apr  5 06:56:10 AM -03 2022 INFO - updateWinRes - The Window 'SteamTinkerLaunch-DownloadShadersStatus' was closed - the resolution didn't change - nothing to do`
just means, that the window size of the 'SteamTinkerLaunch-DownloadShadersStatus' window hasn't changed at all.

**Comment by oblitum** [comment]
Okay. Sadly it seems I'm struggling to make this work, almost giving up. I noticed the DOOM game folder has a normal `ReShade.ini`, and that `DOOM/reshade-shaders/enabled` have `depth3d` and `reshade-shaders`. When first clicking Game Shaders button on STL, it downloaded 3GB of shaders, then I noticed `depth3d` checkbox is ticked, and only this one. Not sure what to do anymore, will check with Alien Isolation.

**Comment by frostworx** [comment]
somewhere in the gamedir _(near the ReShade.ini and the reshade-shaders directory with the shaders)_
should be the d3dcompiler_47.dll and a d3d9.dll and/or a dxgi.dll. depending on the game, the game exe is in a separate subdirectory. Everything the dlls, the ReShade.ini and the reshade-shaders directory need to be besides the game exe.
steamtinkerlaunch automates here very much and mostly succeeded everywhere, so there is not much left a user maybe has to configure themself, but might guess the destination here wrong sometimes.

**Comment by oblitum** [comment]
Okay. I just tried with Alien Isolation, it worked out of the box, the game started with a ReShade overlay where I followed a tutorial and checked Stereo3d for the game, out of the box it isn't great as native Trine 3 for sure, possibly some tweaking can make it better. Not sure why it failed on DOOM, will check it later.

**Comment by oblitum** [comment]
> Everything the dlls, the ReShade.ini and the reshade-shaders directory need to be besides the game exe

Can't see any issue at that for DOOM in comparison to Alien Isolation:

```
❯ ls /mnt/disk1/Steam/steamapps/common/DOOM/
base          CChromaEditorLibrary.dll  d3d9.dll            DOOMx64.exe    dxgi.dll         ReShade.ini      ReShade.txt      superscriptx64.dll
bink2w64.dll  check-steam_appid.txt     d3dcompiler_47.dll  DOOMx64vk.exe  EmptySteamDepot  reshade-shaders  steam_api64.dll  virtualtextures

❯ ls /mnt/seagate/Steam/steamapps/common/Alien\ Isolation
AI.dxvk-cache  AMD_AGS.DLL  BENCHMARK_TEMPLATE.TXT  CRASHREPORTER32.DLL  d3dcompiler_47.dll  dxgi.dll  Extras       ReShadePreset.ini  ReShade.txt  STEAM_API.DLL
AI.exe         ATIAGS.DLL   check-steam_appid.txt   d3d9.dll             DATA                dxgi.log  ReShade.ini  reshade-shaders    share        steam_shader_cache
```

**Comment by frostworx** [comment]
hmm, I'm not really much into the newer Dooms, but didn't it use vulkan by default? Could explain why dxgi.dll is not loaded (no dxgi.log). additionally you could compare the filesize of dxgi.dll with that in AI -maybe Doom shipped its own one already.
this is really totally out of scope of steamtinkerlaunch, so I'm running out of ideas. goods luck so far.

**Comment by oblitum** [comment]
> but didn't it use vulkan by default?

No it does not (maybe Eternal does). I have to change inside the game. Notice that I left game exe in STL as-is (DOOMx64.exe), but there's a DOOMx64vk.exe in the game folder. Not sure whether I should tweak STL to that given I enabled vulkan in-game.

> additionally you could compare the filesize of dxgi.dll with that in AI -maybe Doom shipped its own one already.

They're different indeed.

**Comment by oblitum** [comment]
Notice though that AI is 32bit, and DOOM is 64. Just noticed in logs. No need to dig further, really thanks for your help till now.

**Comment by frostworx** [comment]
steamtinkerlaunch automatically detects the game binary architecture and uses the corresponding reshade.dll (mostly dxgi.dll).
Sometimes a game has an additional launcher though, which, with bad luck is 32bit and the game exe itself is 64bit.
this doesn't happen often, but those weird combinations do exist indeed. steamtinkerlaunch can't see the real game exe, so there's nothing which could be done here automatically.

**Comment by oblitum** [comment]
> Alternatively drop the game into a "ReShadeSBS" Steam category

I'm starting everything from scratch now to start clean. I wanted to use Steam categories solely when possible, it seems simpler  to just set the game to start with STL and then drop it into a category. Solely doing just this didn't work to get previously working SBS setup for Alien Isolation (ReShade/Depth3D doesn't start at all). I can only make it work going through the GAME MENU and checking the Stereo3D box. Is there anything extra that's needed for stuff to work just by dropping into a Steam category? [I've checked wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Categories#steam-categories) and it seems to imply some category configuration files are expected to exist, _a priori_, if I'd need to put a config file in place manually, then I'd just prefer to stick with the GAME MENU checkbox.

**Comment by frostworx** [comment]
assuming you installed it correctly you should have a `/usr/share/steamtinkerlaunch/categories/` directory.
the filenames of those files are compared to the games steam categories.
On success they are automatically loaded. Every category and loading of its corresponding config is logged, so you can easily check if it was used.
As already explained [here](https://github.com/frostworx/steamtinkerlaunch/issues/443#issuecomment-1087919552)
games supposed to use Reshade need to be put into the ReShadeSBS category, those with builtin sbs support into the SBS category.

**Comment by oblitum** [comment]
The configuration file does exist: `/usr/share/steamtinkerlaunch/categories/ReShadeSBS.conf`. I've set the steam category to `ReShadeSBS`, it didn't work, I deleted it and set it to `RESHADESBS`, also didn't work.

The logs regarding categories seem:

```
Wed Apr  6 10:59:36 AM -03 2022 INFO - autoCategorySettings - Searching categories for game '214490' in 'sharedconfig.vdf'
Wed Apr  6 10:59:36 AM -03 2022 SKIP - autoCategorySettings - Config '/usr/share/steamtinkerlaunch/categories/.conf' not found - skipping
Wed Apr  6 10:59:36 AM -03 2022 SKIP - autoCategorySettings - Config '/home/francisco/.config/steamtinkerlaunch/categories/.conf' not found - skipping
Wed Apr  6 10:59:40 AM -03 2022 INFO - autoCategorySettings - Searching categories for game '214490' in 'sharedconfig.vdf'
Wed Apr  6 10:59:40 AM -03 2022 SKIP - autoCategorySettings - Config '/usr/share/steamtinkerlaunch/categories/.conf' not found - skipping
Wed Apr  6 10:59:40 AM -03 2022 SKIP - autoCategorySettings - Config '/home/francisco/.config/steamtinkerlaunch/categories/.conf' not found - skipping
```

**Comment by frostworx** [comment]
incomplete...

**Comment by frostworx** [comment]
also explicitely documented "(case-sensitive, but written uppercase in Steam !)"

**Comment by oblitum** [comment]
> also explicitely documented "(case-sensitive, but written uppercase in Steam !)"

That's a bit confuse, because I can't know whether you meant it's Steam that "writes" it in uppercase, or whether I should do that while creating it in Steam. In any case, I did both.

What I think you meant is the former, Steam ___displays___(~written~) it in uppercase, even if I write it case-sensitively. Though that's not all true information, because Steam in Big Picture does display it as I've written, only Steam non-Big-Picture that displays it all caps. So for a person that mostly uses Big Picture, that may sound confusing.

**Comment by frostworx** [comment]
again: you're invited to improve the wiki everywhere

**Comment by frostworx** [comment]
check your `~/.local/share/Steam/userdata/$SteamUserID/7/remote/sharedconfg.vdf` for your categories
that ancient function still works fine for me here. logs look fine, but a variable in autoCategorySettings is empty
_(coming from sharedconfg.vdf)_

**Comment by oblitum** [comment]
I have it at my current user id (notice though there's lots of other user ids in my machine):

```
"UserRoamingConfigStore"
{
	"Software"
	{
		"Valve"
		{
			"Steam"
			{
				"SteamDefaultDialog"		"#app_store"
				"StartMenuShortcutCheck"		"0"
				"DesktopShortcutCheck"		"0"
				"Apps"
				{
					"214490"
					{
						"tags"
						{
							"0"		"ReShadeSBS"
						}
```

(The above does not exist for any of the other user id's `sharedconfg.vdf`)

**Comment by frostworx** [comment]
multiple users on the same machine might be the problem _(see [here](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L540=))_
you could try to set the correct `STEAMUSERID` in the `global.conf` to "hardcode" it, but I never tested that function _(and can'T remember anybody reported anthing about it)_

**Comment by oblitum** [comment]
I confirm it's picking the wrong user id by default (I wonder whether that may have affected other functions of the script):

```
~ cd /dev/shm/steamtinkerlaunch/
~ rg STEAMUSERID
steampaths.txt
12:STEAMUSERID="WRONG ID"
```

I've put `STEAMUSERID="CORRECT ID"` at the end of `~/.config/steamtinkerlaunch/global.conf` (no previous `STEAMUSERID` entry there, with small explanation) and saved, restarted Steam, but still, it didn't work, and `/dev/shm/steamtinkerlaunch/steampaths.txt` is still with the wrong id. Should I wipe `/dev/shm/steamtinkerlaunch/`?

Okay, did it all again, but wiped `/dev/shm/steamtinkerlaunch/`, now this finally worked!
