### ISSUE TITLE
Update GameScope Wiki page

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#444]
GitHub doesn't seem to have a standard "pull request" feature for wikis, so I'll use an issue for this :) I loosely followed the recommendations found in [this](https://gist.github.com/larrybotha/10650410) GitHub Gist. If there is a better workflow or I need to do something differently, I'll be happy to. Even if it means attaching the markdown file somewhere :laughing: 

I spent some time over the weekend writing an updated wiki page for Gamescope. It outlines briefly what Gamescope is, the features Steam Tinker Launch exposed related to Gamescope, and should be fully up-to-date with the latest Steam Tinker Launch Gamescope changes :partying_face: 

The Gamescope Menu image could use an update to show the updated Gamescope menu, we could use the one from #441 :slightly_smiling_face: 

The docs can be found on the [wiki section](https://github.com/sonic2kk/steamtinkerlaunch/wiki/GameScope) of my Steam Tinker Launch fork. I have tried to condense and organise the information as best as I can, but any ideas for making it better are welcome! The goal is to make it as useful and easy to follow for users.

Information on other pages of the wiki may need updating, though I didn't comb through all of it, I remember briefly seeing a page that might have needed updating. I can't remember it now, but if I or someone else comes across it in future, it can always be updated :smile: 

Thanks!

**Comment by frostworx** [comment]
Oh wow! Thank you very much for the new Wiki!
_(I haven't read it yet, because real life work starts soon 😀)_

If you want I can add you to the wiki editors directly, so you can edit it directly.

**Comment by frostworx** [comment]
excellent wiki, thanks a lot! :)

**Comment by sonic2kk** [comment]
Thank you, and also for the invite! I'll update the wiki now :partying_face:

**Comment by sonic2kk** [comment]
Updated, we can close this issue now :)

**Comment by frostworx** [comment]
Thanks a lot again! \o/ 😀
