### ISSUE TITLE
`SteamTinkerLaunch-NeedNewProtonVersion` Doesn't Take Inputs and Won't Go Away

### ISSUE THREAD

**Issue by ThisNekoGuy** [sonic2kk/steamtinkerlaunch#447]
Version: `9.2` (was formerly `steamtinkerlaunch-git`)

[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8440269/steamtinkerlaunch.log)
(The below file is the most recently updated file in its folder)
[31337.log](https://github.com/frostworx/steamtinkerlaunch/files/8440271/31337.log)

# Description:
I've encountered an issue where this window:
![Screenshot_20220407_014636](https://user-images.githubusercontent.com/28468662/162136923-647508c6-b100-40a2-b74c-7af67bf41e00.png)
won't go away no matter what I do; it won't take any options as valid, it persists even if Steam is closed, rolling back to version 9.2 didn't fix it, and killing the process doesn't stop it either...

Originally, before this started, I was trying to force it to recognize my Proton versions in `compatibilitytools`, because it wasn't behaving after I manually added new ones and removed old ones, so I edited files directly to change the name of what to use to what I wanted...
Then it started doing this and always never takes input here...

**Comment by frostworx** [comment]
looking at the logs it looks like you added an empty line manually which causes this loop:
`getAvailableProtonVersions - Checking line '' in '/home/neko-san/.config/steamtinkerlaunch/protonlist.txt'`
removing it should fix it.
Although this was caused manually, ~~I'll add~~ I [just added](https://github.com/frostworx/steamtinkerlaunch/commit/89f273eec1523706a4923cd4f3b9c79a5d140499#diff-77c6d4bb1bf7c1988ff5a068c856b6c24e113663f2e61cb3a2c98723c0fafc04=)  an additional line, which does this automatically in the future.
~~commit will pop up shortly :)~~

**Comment by ThisNekoGuy** [comment]
@frostworx That helped, thanks

**Comment by ThisNekoGuy** [comment]
@frostworx Also, just to let you know, Proton-tkg using the "valve" preset in its config file, produces a proton build that confuses STL for some reason; it just refuses to acknowledge it as a valid build in compatibilitytools for some reason (which is what originally caused me to start this mess Lol)

**Comment by frostworx** [comment]
Hm, thanks for the warning When reports regarding this grow, I might just drop tkg completely _(although I always prefer to have an option and like the tkg project, although I barely use it tbh)_
*closing here, as the opening issue is fixed*

**Comment by ThisNekoGuy** [comment]
_I mean, Proton-tkg is about 1/3 the reason why I use STL, but okay_

**Comment by frostworx** [comment]
then please elaborate what Proton-tkg using the "valve" preset in its config file means.
but okay

**Comment by ThisNekoGuy** [comment]
When you compile `Proton-tkg`, it comes with a config file.
This config file has a value called "`_LOCAL_PRESET`":
```
# WINE FLAVOUR SETTINGS

# Override config with one of the presets from /wine-tkg-profiles dir. Leave empty to use wine upstream trees.
# Custom presets for proton : "valve" (builds against current valve proton tree), "valve-exp" (builds against current valve proton-experimental tree)
_LOCAL_PRESET=""
```

Changing this value to "valve" before compiling is what I was referring to.
I take it you've never compiled Proton-tkg?

**Comment by frostworx** [comment]
my Proton-STL is tkg based. I take it you've never read the wiki?
I have no clue what your point is to mention a tkg compile option. why should I even care?
If someone rolls an incompatible proton version, it is their private fun

**Comment by ThisNekoGuy** [comment]
I'm going to pretend I wasn't being condescended upon; I was asking a genuine question
That aside, the STL wiki is massive; it's not unexpected nor unreasonable that everyone besides yourself would only skim it

As for the issue I mentioned, I don't expect you to care if we're going to be candid about it, I'm only notifying you that if you're going to provide a custom Proton selection feature: obviously expect a report when STL, a program built upon using the software of others, has a problem when an explicit "feature" doesn't behave as expected.
