### ISSUE TITLE
Question: How to set arbitary env vars through GUI

### ISSUE THREAD

**Issue by IcyAlmond** [sonic2kk/steamtinkerlaunch#450]
I've found https://github.com/frostworx/steamtinkerlaunch/wiki/ENV-Variables but and it seems to work if i set it through the configuration file. But is there a way to add custom environmental variables through the GUI? I wasn't able to find it if there is

**Comment by frostworx** [comment]
No, adding them manually is the only option.
Imho not worth the time to add a gui option (of course I'd accept PRs anyway)

**Comment by frostworx** [comment]
just merged the new feature and also updated the [ENV Variables](https://github.com/frostworx/steamtinkerlaunch/wiki/ENV-Variables) wiki.
global and per-game configs are autocreated and ignored if empty.

please test and report back @Latrolage 

edit: thanks here as well for the [initial commit](https://github.com/frostworx/steamtinkerlaunch/pull/453), @sonic2kk ;)

**Comment by IcyAlmond** [comment]
The new configuration file works for env variables without issue.
