### ISSUE TITLE
STL Not Functioning On Pop!_OS

### ISSUE THREAD

**Issue by RyuRaiko** [sonic2kk/steamtinkerlaunch#451]
[logs.zip](https://github.com/frostworx/steamtinkerlaunch/files/8491834/logs.zip)
 
(WIP) more info will be added later

**Comment by frostworx** [comment]
[context](https://www.reddit.com/r/SteamTinkerLaunch/comments/u3ooag/steam_tinker_launch_not_functioning_on_pop_os_2010/)

**Comment by frostworx** [comment]
before going offline, I just gave it a quick look.
the logs do not reveal any significant problem, but indicate that you're using latest release 9.2
Please install current master and retry,
describe exactly how you installed steamtinkerlaunch and if the installed files are in place.

the privileges problems you pasted into github
```
find: ‘/usr/share/steamtinkerlaunch/lang’: Permission denied

grep: /usr/share/steamtinkerlaunch/misc/helpurls.txt: Permission denied

grep: /usr/share/steamtinkerlaunch/misc/helpurls.txt: Permission denied

/usr/bin/steamtinkerlaunch: line 5153: : command not found
```
indicate that your user is not allowed to read those files. you need to check that - this is not steamtinkerlaunch related, but apparently the main issue.
may some firewall or selinux service blocking access?

Also:
- don't zip logs
- only upload the requested one and not a bunch of some random ones

**Comment by frostworx** [comment]
missing feedback _(also on reddit, but active there)_
-> invalid
