### ISSUE TITLE
toggle steamwebhelper not working 

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#456]
on version SteamTinkerLaunch v9.3.20220421
 the  [steamwebhelper function](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L10840=) does not stop the steamwebhelper process ( tested with trails of cold steel 3)
 
 EDIT:
 for now my workaround is to create a bash script that
  `for i in $(pidof steamwebhelper); do kill -SIGSTOP $i;done` 
  in it and another one that has 
  `for i in $(pidof steamwebhelper); do kill -SIGCONT $i;done`
   and add them to  the start and end section of the gamemode config
   Trying to figure out how to fix the code myself unfortunately I never really have worked with bash before (in fact I didn't come up with the above command someone on discord help me with it)  I worked with c++, python, and java but very little in bash

**Comment by frostworx** [comment]
Interesting to see that the function is even used. Should be fixed soon. Thanks for reporting.
edit: function `StateSteamWebHelper` does basically the same like your one-liners.
Strange that it doesn't work anymore. Will add either way some logs, so it doesn't `SIGSTOP`/`SIGCONT` silently.

**Comment by frostworx** [comment]
above commit should fix it. good find! 👍

**Comment by zany130** [comment]
Yeah just started using this feature as I noticed as disabling `steamwebhelper` can improve fps sightly if your maxing out your GPU as I am in cold steel 3 (running a lot of reshade shaders will do that plus im running at 1440p upscaled to 4k with FSR).

yup launching a game with toggle `steamwebhelper` enabled stops the `steamwebhelper` processes correctly when the game is launched, however when I exit the game the processes are still stopped. Based on the name and a quick look through the code I thought this function automatically re enables  `steamwebhelper` on game exit, but it currently does not do that correct?

**Comment by frostworx** [comment]
It should do so correctly, as it is executed at the end of the `startGame` function.
please check/append the corresponding log.
it should be directly after the `GAMESTOP after '$duration' seconds playtime` logline.
_(worked fine for me when testing above fix, so maybe your game errored out too early? log will tell)_

**Comment by zany130** [comment]
[The Legend of Heroes Trails of Cold Steel III.log](https://github.com/frostworx/steamtinkerlaunch/files/8549897/The.Legend.of.Heroes.Trails.of.Cold.Steel.III.log)
Ahh. Yup as you can see its never running `GAMESTOP` so it could be a detection issue with this game (The Legend Of Heroes: Trails of Cold Steel III) where its not seeing when the game exits. I'll try with a different game

EDIT: opps I linked the symlinked log I don't think that will show anything for you right here is the log for 
[trails](https://github.com/frostworx/steamtinkerlaunch/files/8549911/991270.log)


also tried [A Hat in Time](https://github.com/frostworx/steamtinkerlaunch/files/8549916/253230.log) and there it works as expected so  its indeed a  game exit detection issue with trails 

EDIT2: so I guess this can be closed now?

**Comment by frostworx** [comment]
Thanks for the update! I agree the initial issue is solved, but I'd like to find out why your game does not exit properly.
If you don't mind I'd try to find the reason for this, but I might need your help with further logging.
If you agree, I'd rename this issue, so there's no need to re-open another one.

**Comment by zany130** [comment]
sure I don't mind helping to troubleshoot but one thing that comes to mind is this game already has issues exiting normally (meaning from the title screen or the menu option) and needs to either be force-closed or exited with the steam overlay option so IDK if thats the causes it.

 I did test a few other games that do exit through there menus (such as a hat in time) and they also exhibit the same issue when closed trough steam so that might be why

**Comment by frostworx** [comment]
Ah ic, ok then there is no need to further debug this.
No idea if you knew it already, but steamtinkerlaunch also does have a [Kill-Switch](https://github.com/frostworx/steamtinkerlaunch/wiki/Proton-KillSwitch) for Proton games.

you can stop any game f.e. via hotkey using it.
As an example, I have
```
#!/bin/bash
KS="/dev/shm/steamtinkerlaunch/KillSwitch"
if [ -x "$KS" ]; then
 "$KS"
fi
```
on the St**r**eam Deck

_(the kill switch is also in the steamtinkerlaunch tray icon)_ 

*closing here*
