### ISSUE TITLE
Add dgVoodoo2 to help running much older Games

### ISSUE THREAD

**Issue by NightHammer1000** [sonic2kk/steamtinkerlaunch#459]
dgVoodoo2 can be used with older Games.
It can upconvert 
Glide 2.11, Glide 2.45, Glide 3.1 and Glide 3.1 Napalm
DirectX 1-7 (all versions of DirectDraw and Direct3D up to version 7)
Direct3D 8.1
Direct3D 9
to either DX11 for DXVK or DX12 for vkd3d-proton

I use it manually a lot to get old GoG Games to run on the Deck.
You loose a bit of Performance but that does not matter for 20 Year old Games I would say.

http://dege.freeweb.hu/dgVoodoo2/

**Comment by frostworx** [comment]
Is this an announcement for a PR you're planning? Nice, I'd accept it.

If it is a feature request, please elaborate which dll constellations are possible/required, which src urls need to be downloaded and placed where under which name. Are there any options which can/need to be configured and if so, which? If there's anything else important to know please add it as well.

**Comment by frostworx** [comment]
ping

**Comment by frostworx** [comment]
OP apparently no longer interested. 👎

**Comment by Faalagorn** [comment]
You could have keep this open in case someone want to PR this though, dgVoodoo2 is quite popular, though not the only solution for older games: https://www.pcgamingwiki.com/wiki/Glossary:Display_wrapper

Sadly I'm not up for the task, at least not at the moment, but might be worth taking look if it's worth to add support for some of these wrappers missing here :thinking:… Maybe add a new metaissue for it?

**Comment by frostworx** [comment]
sure I could have left it open, but it doesn't contain any useful information.
Anybody is invited to re-open it with some details anytime of course.
I once considered dgVoodoo2 support _(using its d3dcompiler47 for reshade already)_, but never used it personally and didn't want to read through its docs to find out what it needs.

**Comment by Faalagorn** [comment]
Oh yeah, now that you mention it I might have remembered it (I wasn't searching for it; just browsing my github notifications). I'm not a huge fan of dgVoodoo2 either, partially since we have better alternatives for Linux nowadays (Vulkan with FLOSS licences and better code quality), though it's hard to dismiss dgVoodoo indeed.
