### ISSUE TITLE
Support System Wine

### ISSUE THREAD

**Issue by sad-goldfish** [sonic2kk/steamtinkerlaunch#460]
Does [steamtinkerlaunch](https://github.com/frostworx/steamtinkerlaunch) support using system wine like `/usr/bin/wine`? If not, I think it should be supported.

**Comment by sad-goldfish** [comment]
Setting `WINEXTDIR=/usr/lib` and `WINEVERSION=wine` (or something along those lines) works.

**Comment by frostworx** [comment]
you could have checked the [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Wine-Support)
