### ISSUE TITLE
steam deck install help

### ISSUE THREAD

**Issue by BrianBarnaik** [sonic2kk/steamtinkerlaunch#461]
i'll be honest yall, no clue how to install this. i have no idea what "start as deck [user]" means. theres literally negative videos of anyone installing steam tinker launcher

**Comment by zany130** [comment]
It means exactly that.
 You need to run the script file `steamtinkerlaunch` in a terminal with the user account `deck` which i think is the default user account on the steam deck. You do that by opening a terminal and running
`./pathtoscript`

Google how to open a terminal and how to run a shell script if you need more info.

**Comment by BrianBarnaik** [comment]
that is not working for me as it continues to state no such file or directory . i appreciate the help

**Comment by zany130** [comment]
did you download the program? you need to download it and then run it in a terminal. you might have to `chmod a+x filename` to make it executable if it gives you an error

**Comment by frostworx** [comment]
🤨
