### ISSUE TITLE
Where do I throw the money?

### ISSUE THREAD

**Issue by AliceDTRH** [sonic2kk/steamtinkerlaunch#462]
You've finally solved the last issue that I had with Linux, where do I give you money?

**Comment by frostworx** [comment]
Thank you for the offer!
I do not work on steamtinkerlaunch for money though. I once added an option to allow people supporting the project via donations, but this did not really work out and therefore I removed it quickly.
If you like you could support it though by contributing translations, wiki improvements, pull requests or simply by making the project more popular.

**Comment by AliceDTRH** [comment]
Okay, thank you very much! I'll do my best to contribute in some other way then :)
