### ISSUE TITLE
Add Steam-Metadata-Editor support

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#467]
Recently I found the very useful tool [Steam-Metadata-Editor](https://github.com/tralph3/Steam-Metadata-Editor)
I think it would be nice feature to have direct support for it in steamtinkerlaunch.

**Comment by frostworx** [comment]
corresponding [upstream issue](https://github.com/tralph3/Steam-Metadata-Editor/issues/18)

**Comment by frostworx** [comment]
I will mostly stop working on steamtinkerlaunch soon and only occasionally add one or another feature.
This project is still interesting, so *leaving the issue open*

**Comment by sonic2kk** [comment]
~~There has been no change on this upstream, but~~ this would still be pretty nifty to have, so leaving this issue open :smile: 

Upstream is still interested too, no ETA (though not planned for next release). Leaving this open until this feature is implemented :-)

**Comment by sonic2kk** [comment]
I am not sure how I wanted to integrate this at the time. The maintainer of the project is really friendly, and I encourage anyone reading to check it out, but I think now there is no need for any integration :-)

Closing.
