### ISSUE TITLE
Can't add steamtinkerlaunch as compatibility tool for Steam

### ISSUE THREAD

**Issue by degradka** [sonic2kk/steamtinkerlaunch#472]
I have installed stl using dnf package and I can't add stl as compatibility tool for Steam
Here's the error

> `/usr/bin/steamtinkerlaunch: line 16258: /home/degradka/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/compatibilitytool.vdf: No such file or directory

> /usr/bin/steamtinkerlaunch: line 16258: /home/degradka/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/toolmanifest.vdf: No such file or directory

> Wed May 25 02:16:55 PM 2022 

> INFO - CompatTool - Creating symlink '/home/degradka/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/steamtinkerlaunch' pointing to '/usr/bin/steamtinkerlaunch'

> ln: failed to create symbolic link '/home/degradka/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/steamtinkerlaunch': No such file or directory`

OS: Fedora 36
STL Version: v10.0

**Comment by frostworx** [comment]
I doubt this is a steamtinkerlaunch problem, else someone would have noticed it already.
How exactly are you trying to add steamtinkerlaunch as compatibility tool?
might also be useful to have a related log file from your attempt

**Comment by degradka** [comment]
> How exactly are you trying to add steamtinkerlaunch as compatibility tool?

steamtinkerlaunch compat add
> Might also be useful to have a related log file from your attempt

[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8771554/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
> > How exactly are you trying to add steamtinkerlaunch as compatibility tool?
> 
> steamtinkerlaunch compat add

this is correct and still works for me.

> > Might also be useful to have a related log file from your attempt
> 
> [steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8771554/steamtinkerlaunch.log)

the log logs fine as well. so where is your error snippet you initially posted?
Looking at your log I'd say
`~/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/`
is ready. Is it?

**Comment by degradka** [comment]
compatibilitytools.d only contains "GE-Proton7-17" and there is no SteamTinkerLaunch

**Comment by frostworx** [comment]
then I assume your system is blocking write access to compatibilitytools.d/

**Comment by degradka** [comment]
thank you, but how do I fix this?

**Comment by frostworx** [comment]
`ls -la ~/.local/share/Steam/compatibilitytools.d/`
shows owner/group of your compatibilitytools.d and their access to the dir.
you can `chown` the dir to your needs.

Anyway I'll add some more log output, so the log gives a note for such a situation in the future.

**Comment by frostworx** [comment]
a good example output would be:

```
drwxr-xr-x  2 degradka users 4096 25. Mai 15:44 SteamTinkerLaunch
```

**Comment by degradka** [comment]
That did the trick, thank you so much!

**Comment by frostworx** [comment]
great to hear! :)

**Comment by frostworx** [comment]
just added better logging so finding such a problem is easier in the future :)
