### ISSUE TITLE
STL does not recognise Subnautica as a Vortex Supported game

### ISSUE THREAD

**Issue by dermalikmann** [sonic2kk/steamtinkerlaunch#474]
I found this issue with Subnautica (not BZ) but by the nature of the "bug" this could probably also affect other games.

STL Version: v10.0
Vortex Plugin: Subnautica Support v2.1.3

To make a somewhat long trail-and-error story short:

The Subnautica Vortex plugin defines its compatible Steam ID like this:
```typescript
const STEAMAPP_ID = '264710';
const EPICAPP_ID = 'Jaguar';
[...]

function main(context) {
  // Register Subnautica.
  context.registerGame({
[...]
    environment: {
      SteamAPPId: STEAMAPP_ID
    },
    details: {
      steamAppId: parseInt(STEAMAPP_ID),
      epicAppId: EPICAPP_ID
    },
```

This does not compute for STL, as it expects a simple SteamID after the colon.
The _"""buggy"""_ line is [here](https://github.com/frostworx/steamtinkerlaunch/blob/2463e3baa77bec1adc647d92b32e36d07d39e9dc/steamtinkerlaunch#L11711)

Thank you for your awesome work!!

**Comment by frostworx** [comment]
Thanks a lot for your report and the kind words! :)
I'll look into it soon - shouldn't be too hard to fix.
Especially as you were so kind and even looked for the correct line :)

**Comment by frostworx** [comment]
Hi again :)
[This commit](https://github.com/frostworx/steamtinkerlaunch/commit/fb0bb4db494cb2f48793e5df28c4deb74329a4d9) should already fix the problem.
Please let me know if it works for you.

**Comment by dermalikmann** [comment]
Works like a charm! Thank you very much 👍🏻 
Let's hope there aren't more cumbersome ways people do this. :D

**Comment by frostworx** [comment]
Thanks for testing :)
