### ISSUE TITLE
autoconfiguring Vortex game paths

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#475]
As reported on [reddit](https://www.reddit.com/r/SteamTinkerLaunch/comments/uztunw/why_does_stl_not_autoconfigure_the_game_paths_for/) the function `setupGameVortex` is not even used at all.
Need to find out why :)

**Comment by frostworx** [comment]
The required Vortex configuration settings are done in the function `setGameVortexStaging`:
```
setVortSet "settings.mods.installPath.$NEXUSGAMEID=true"
setVortSet "settings.mods.installPath.$NEXUSGAMEID=\\\"$GAMESTAGINGWINFOLDER\\\""
setVortSet "settings.mods.activator.$NEXUSGAMEID=\\\"hardlink_activator\\\""
```

which is the reason, why setupGameVortex is no longer used.
I guess I left the function in the code, in case the commented vortex configs are required one day.

**Comment by dermalikmann** [comment]
I think that my post on reddit was a bit confusig and I am sorry for that.

The problem with `settings.mods.installPath.$NEXUSGAMEID=\\\"$GAMESTAGINGWINFOLDER\\\` ist, that it is not actually the directory of the game installation, but the directory where Vortex places the mods. So the mods get """installed""" there. After that, Vortex """enables""" these mods through one of two ways, which can defined by `settings.mods.activator.$NEXUSGAMEID=\\\"hardlink_activator\\\"`

The actual GAME installtion path (so where the game binaries are) is set thourgh `settings.gameMode.discovered.<GAME>.path`

I hope i could clarify things

**Comment by frostworx** [comment]
In fact it is still confusing for me.
I know that `settings.mods.installPath` is the Vortex mod path aka "staging path" and `setGameVortexStaging` exactly configures it as such.
As mentioned in reddit, I think the other vortex configurations are not required and therefore were commented out in the no longer used function `setupGameVortex`.
The game paths are determined in `setModGameSyms`, which seems to still work fine _(might not find all installed games, iirc most tests were done by me and I do not really mod much)_.

Please elaborate on what exactly is missing and/or of course you're invited to play around with re-adding `settings.gameMode.discovered.<GAME>.path` and contribute any improvements :)

**Comment by frostworx** [comment]
I just re-tested from scratch _(renamed my complete "productive" `~/.config/steamtinkerlaunch/` and removed `/dev/shm/steamtinkerlaunch`)_
and think I understand what you mean:
only the installed Bethesda games and a few others _(The Witcher, Torchlight II)_ were marked as found in Vortex _(=colored picture)_ although several more installed Vortex compatible games were found by steamtinkerlaunch _(check `~/.config/steamtinkerlaunch/vortex/compatdata/seenvortexgames.txt`)_

Probably should be easy to fix but it still might take some time, because I do not work on steamtinkerlaunch very much
in the upcoming months _(nature is calling :))_
Of course PRs are still welcome :D

**Comment by dermalikmann** [comment]
Ah, ok. I only tried it with Subnautica, therefor I couldn't tel that it is working for other games. I will try again with Witcher and Skyrim and maybe I can bodge a PR together :D
Don't stress yourself, as there is a very simple Workaround: Just select the path yourself in `Z:` 😂

**Comment by frostworx** [comment]
fyi: I already started to debug this.
Seems like Vortex upstream changed multiple things under the hood again.
f.e. there is a
` settings.gameMode.discovered.$NEXUSGAMEID.environment.SteamAPPId`
configuration entry now which might come in handy.
unfortunately there is something wrong or weird in programmatically filling some paths.
no idea yet when or if this will get an update.

edit: the Vortex internal format handling of `settings.gameMode.discovered.$NEXUSGAMEID.path`
is different to all other paths - f.e. to
`settings.mods.installPath.$NEXUSGAMEID`
so it might be impossible atm to write the `discovered` paths programmatically atm(?).
could be an upstream bug.

**Comment by frostworx** [comment]
Faster than expected. [This commit](https://github.com/frostworx/steamtinkerlaunch/commit/9aaf3a88df529a0eb0b6bb1cac3b087b644eef41) works fine for me :)

**Comment by frostworx** [comment]
ping

**Comment by dermalikmann** [comment]
Whoah boy. Didn't expected it to be that fast, so I did not check here :D
I will check this tonight and will let you know if it works for me :)

**Comment by frostworx** [comment]
Thanks for the reply! No hurry, I'm afk for ~ the next two weeks \o/

**Comment by frostworx** [comment]
ping
