### ISSUE TITLE
trying to run another .exe program with current game

### ISSUE THREAD

**Issue by tuxtergames** [sonic2kk/steamtinkerlaunch#477]
Hello, sorry to post this here if its not the correct palce, I don't find a place to help about steamthinkerlaunch,

I need to run, 2 programs at the same time, my objective is for PES21 and ETS2 and ATS2, I try to set one ramdom program with NFS hot pursuit, in this case vlc portable, but its happen the same problem when I try to run through cli command, the first program start, in this case vlc portable, and the game don't, to the game starts I need to close vlc, and the porpose its to mantain the program running in background, I appreciate any help and again sorry if its the wrong place, bellow one screen of my STL.

![image](https://user-images.githubusercontent.com/26095484/171014047-01bd892e-5e5a-4ae1-9b19-b197af9cb519.png)

log game:
[Need for Speed Hot Pursuit.log](https://github.com/frostworx/steamtinkerlaunch/files/8799279/Need.for.Speed.Hot.Pursuit.log)

**Comment by frostworx** [comment]
Hi, this is the right place to ask :)
To make sure I understood you correctly:
You're planning to start one additional programs besides the regular game exe, right?
(not two additional programs)

This could be done by using the custom command function _(see the [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Custom-Program), in case you missed it)_
so in your screenshot you need to click the "custom command" option and choose your VLCPortable.
Make sure to remove the "User start command" entry - it is meant for custom scripts.
Depending on, when the additional exe is supposed to start (before, after, instead of the game exe, you also need to set Fork/Only/Inject(plus inject wait)).
Sound like you simply need to set the  "Fork custom command", so your VLCPortable is started forked, and the game almost simultaneously afterwards.

_(you also enabled IGCSInjector in your screenshot, no idea if this was intended)_
If something goes wrong feel free to attach the corresponding log - maybe we find something :)

**Comment by tuxtergames** [comment]
> 

Hi, 
Tks for reply, Yes you're right, follow your tip here, still the same, if I can't close vlc the game won't start, I send two logs before ad after close programs running, this still happen if I try with cli, follow my screen, I believe my distro have nothing to do with this, btw I using Fedora nobara 36.

![image](https://user-images.githubusercontent.com/26095484/171036927-5791614d-0023-4d5c-9a82-c8ce98157598.png)





logs before close vlc
Id log
[47870.log](https://github.com/frostworx/steamtinkerlaunch/files/8799862/47870.log)
 title log
[Need for Speed Hot Pursuit.log](https://github.com/frostworx/steamtinkerlaunch/files/8799870/Need.for.Speed.Hot.Pursuit.log)

logs after close vlc

id log 
[47870.log](https://github.com/frostworx/steamtinkerlaunch/files/8799871/47870.log)
title log
[Need for Speed Hot Pursuit.log](https://github.com/frostworx/steamtinkerlaunch/files/8799875/Need.for.Speed.Hot.Pursuit.log)

**Comment by frostworx** [comment]
your logs reveal that your exe is still executed via user start script:
`seg 30 mai 2022 13:58:28 -03 INFO - customUserScriptStart - Starting custom user startscript '/home/tuxter/Downloads/VLCPortable/VLCPortable.exe'`

so the actual custom program command never is used.
You might have some leftovers in `/dev/shm/steamtinkerlaunch/` from a previous broken run, so I'd start with removing that dir recursively (safe to do so, only steamtinkerlaunch temp files inside, which recreate).
If you have nothing important configured yet, you can also re-try with cleaning/removing/renaming `~/.config/steamtinkerlaunch/`

**Comment by frostworx** [comment]
ping

**Comment by sonic2kk** [comment]
@tuxtergames I just tried this (on Arch, don't have a Fedora machine to test on sadly) and I didn't have any issues. I downloaded VLCPortable and tested it out with Sonic Mania, and both the game and VLC opened at basically the same time. I don't have any Origin games on Steam installed to test with but could it be that Origin is potentially throwing a spanner in the works here?

If I get a chance I'll try out some Origin games but deleting `/dev/shm/steamtinkerlaunch` as Frostworx recommended tends to be a good cure-all in my experience for weird behaviour. Good luck!

**Comment by tuxtergames** [comment]
Hy @sonic2kk and @frostworx sorry my delay, I was so busy last week, finally I can run both with mudrunner game, I really don't know if was a problem, but I supposed its a EA games problems like always, finally I go to my targets, euro truck 2 and american truck and pes21 game, I don't know if its possible to leave open this thread to report my testes, anyway tks for your help here until here.

**Comment by frostworx** [comment]
The function hasn't changed much since it exists and should work fine generally, but of course, both unknown old and new bugs and glitches still can happen, so testing and reporting issues is always good
(until the reports are complete and sane, like yours 😀)

You're welcome to use this issue for further tests of course, but don't wait for a reply from my side within ~ the next 2 weeks though \o/
happy tinkering and testing!

**Comment by tuxtergames** [comment]
> The function hasn't changed much since it exists and should work fine generally, but of course, both unknown old and new bugs and glitches still can happen, so testing and reporting issues is always good (until the reports are complete and sane, like yours grinning)
> 
> You're welcome to use this issue for further tests of course, but don't wait for a reply from my side within ~ the next 2 weeks though \o/ happy tinkering and testing!

Hy, tks for all help, I finally make progress with my tests, now I have another question, to run my second aplication I have to install some dlls with winetricks, so I using winetricks menu, in this case I install dotnet48 and vcrun2019 to run sider.exe with  pes21 game to run mods and play, my doubt is, every time that I try a different wine or proton version a popup appeared with "installing dotnet48 and vcrun2019" and always I'll play this message appered and looks like that installing this dlls every time that I play my games, its a problem or it will happen always, maybe its confusion to explain, english its not my native language, attached a image of this message when I start game.

![image](https://user-images.githubusercontent.com/26095484/173361063-73ea544b-564a-4ee5-93ab-71d836f24639.png)

**Comment by sonic2kk** [comment]
Hi, I don't think this message should be appearing every time you open the game. If the game works I think it's fine for now but it sounds like it could be a bug.

Does your game work? If not as a temporary workaround you could install these DLLs manually with Winetricks or [Protontricks](https://github.com/Matoking/protontricks) :smile:

**Comment by tuxtergames** [comment]
> Hi, I don't think this message should be appearing every time you open the game. If the game works I think it's fine for now but it sounds like it could be a bug.
> 
> Does your game work? If not as a temporary workaround you could install these DLLs manually with Winetricks or [Protontricks](https://github.com/Matoking/protontricks) smile

Hi, removing all configurations and make all steps again stop this messages, now I go to second step, make pickup software work with STL, its a sotfware to work with euro truck simulator 2 and american truck simulator to registry Delivery and send to a virtual company, throught lutris works nice but with STL can't make registry of Delivery, looks like the app works bot nt send information through the app.

**Comment by sonic2kk** [comment]
It sounds like there could be a disconnect between the app and the game then when using STL, but not with Lutris. I wonder why that would be. Are you perhaps playing the native Linux version but running the Windows version of the software?

Also, could you provide a link to this software? I own American Truck Simulator, so I could do some testing :smiley:

**Comment by tuxtergames** [comment]
> It sounds like there could be a disconnect between the app and the game then when using STL, but not with Lutris. I wonder why that would be. Are you perhaps playing the native Linux version but running the Windows version of the software?
> 
> Also, could you provide a link to this software? I own American Truck Simulator, so I could do some testing smiley

Hi, thats it, I using steam native with windows version of this software, this is the website https://pickupvtm.com/client or you can grab here "https://www.dropbox.com/s/2ugg2vw01j2yap4/PICKUP.zip?dl=1" fot lutris I just install dotnet48 and vcrun 2015 or the last version, pickup website provides links for dependencies but even with it, not work everytime, I can make it run here, but can't reproduce again, theres a braziliam portuguese tutorial "https://acrelinux.org/usando-o-cliente-pickup-vtm-no-linux/", you can use google translator to read this, tks for you help again budy....

**Comment by sonic2kk** [comment]
Thanks! I'll give it a try and see if I can figure out the problem :)

**Comment by tuxtergames** [comment]
> Thanks! I'll give it a try and see if I can figure out the problem :)

thank you!!!!! If you need I can send you a gift of ets2? just add me there on steam tuxtergames there

**Comment by sonic2kk** [comment]
That's very kind but I'll be fine :smile: I'll try to get to the bottom of it over the next few days

Could you check to see if Lutris is maybe using the Windows version of the game with Wine? The guide you sent seems to suggest that Lutris is running the Windows version of the game, but I'm relying on Google Translate so I could be wrong :sweat_smile: The paths to the game using the Pickup program look like they're pointing to `.exe` files.

If you need to use the Windows version of the game, check the checkbox on this screen and select SteamTinkerLaunch (it should download the Windows release)

![image](https://user-images.githubusercontent.com/7917345/174488961-a5912d55-2874-4662-9e59-a3ea5cb13211.png)

**Comment by sonic2kk** [comment]
Hmm, I'm having a bit of trouble testing this. I can't get the Pickup program to open at all for me with the native Linux release. I'll try running with Proton and seeing if I have any more luck, I think that's probably the right way to go about it :sweat_smile: 

EDIT: Not totally there yet but the guide seems to say the game relies on a DLL plugin for this program to work, so I think it's likely you'll need to use the Windows version of the game with Proton if you aren't already.

EDIT 2: Okay, so I have the Pickup software installed and I can't really tell if I'm having the same issue, or if I'm simply doing something wrong :sweat_smile: I'll have to look more into how it works, I assume I have to join some kind of company. Might take a while to investigate but I'm making progress. I wonder if the issue could be related to Proton and dotnet48, which doesn't seem to play nice. The Pickup software seems to raise errors every so often (as most GUI software I've tried ddotnet48 with on Proton has).

For reference, I'm using GE-Proton7-20 to test. At this moment I have the software running and it's not really registering anything, not even distance driven. Does it only measure distance driven when I have something to deliver?

**Comment by sonic2kk** [comment]
So I played a little bit more of the game, learned a bit more about how it works, and it seems like I can reproduce the problem. The Delivery program doesn't seem to register any deliveries for me, how odd.

I'll have to try it through Lutris next and see if it works.

**Comment by tuxtergames** [comment]
> So I played a little bit more of the game, learned a bit more about how it works, and it seems like I can reproduce the problem. The Delivery program doesn't seem to register any deliveries for me, how odd.
> 
> I'll have to try it through Lutris next and see if it works.

sorry my delay, I just can reply today, About all questions, You need to set windows version and run with proton to game works with pickup, I use proton to run games with STL, I've running ets2 with proton GE 7.10 and ats with proton GE 7.18, both are registering delivery, but I can't reproduce here again without error, for pickup works nice you have to set to .exe game files and leave a pickup-1.12_x64.dll inside plugins folder to run pickup with game, usually if you click in pickup options you'll see and error and delivery won't registry, maybe If you tell me what files or logs can I share to help with it, tks for help with this

**Comment by sonic2kk** [comment]
I haven't made much progress since the other day. I can get the program to run with the game but I can't get it to register the delivery. I had an idea but I haven't been able to test it yet. What if you choose to run only the custom command from SteamTinkerLaunch? Like this:

![image](https://user-images.githubusercontent.com/7917345/175133806-00da7122-6118-441d-b945-ae96cda2bbf6.png)

Then you can try launching either ETS2 or ATS using the buttons from the Pickup program. I tried this briefly and had trouble trying to make the Pickup program open again (I think it's a KDE Wayland bug). But you could give this a shot and see if Pickup registers deliveries.

Out of curiosity, how does this work through Lutris? Do you launch PICKUP.exe through Lutris and then the game through Steam?

**Comment by tuxtergames** [comment]
> I haven't made much progress since the other day. I can get the program to run with the game but I can't get it to register the delivery. I had an idea but I haven't been able to test it yet. What if you choose to run only the custom command from SteamTinkerLaunch? Like this:
> 
> ![image](https://user-images.githubusercontent.com/7917345/175133806-00da7122-6118-441d-b945-ae96cda2bbf6.png)
> 
> Then you can try launching either ETS2 or ATS using the buttons from the Pickup program. I tried this briefly and had trouble trying to make the Pickup program open again (I think it's a KDE Wayland bug). But you could give this a shot and see if Pickup registers deliveries.
> 
> Out of curiosity, how does this work through Lutris? Do you launch PICKUP.exe through Lutris and then the game through Steam?

Hi, I can made this test here, but I think we need to solve this error of print first, when I launch pickup and click on tools icon I get this error, but can't discouver how to fix it, maybe this is the problem to register delivery, I have prefix backup here that its not happen, but can't reproduce here again
![image](https://user-images.githubusercontent.com/26095484/175300838-d4f3c013-2eb8-489e-ad0f-73d2e9c99d98.png)
about lutris you're correct, I set to start steam and launch pickup with a command over the same prefix,

**Comment by frostworx** [comment]
the error window very likely is caused by an incomplete/broken dotnet installation, which should be fixed first.
I'm pretty sure the core problem is not steamtinkerlaunch related _(I like the fact though, that general support is happening here, thanks @sonic2kk 😀)_

**Comment by sonic2kk** [comment]
I'll need to test more and though this isn't strictly STL related, I have had trouble using dotnet48 with newer releases of Proton and Wine. I wonder if Lutris Wine has patches for this and that's why it works with Lutris?

I get these errors too, and I have also gotten them when I was messing around with some modloaders for other games, but I have never tested with Lutris. What version of Wine are you using with Lutris? You can find by right clicking on the Lutris entry > Configure > Runner options tab > Wine version.

I feel like though this might not be the directly related to STL, if we can figure out the problem and a solution, we could add a note about this to the Modding wiki :)

EDIT: I haven't tested this yet but it seems like Proton and Wine Mono conflicts with dotnet48. That would explain why it would work with Lutris (which likely doesn't install WineMono by default) and why Proton is causing issues. ~~There is a [Steam Guide](https://steamcommunity.com/sharedfiles/filedetails/?id=2386287653) (which seems to be for installing Vortex interestingly) that mentions you have to uninstall Wine Mono and then install dotnet48. It all seems like a bit of a pain~~ Seems like STL automatically removes Mono when installing dotnet, one step ahead as always :smile: I guess there's some other issue at play here. I would say the program just isn't compatible with Wine but I assume the error isn't there with Lutris?

**Comment by frostworx** [comment]
I troubleshooted dotnet _(mostly in vortex/mo2 combination)_ a lot and even wrote a separate [DotNet](https://github.com/frostworx/steamtinkerlaunch/wiki/DotNet) wiki.

It is a bit outdated now, but might be interesting to read for further information.

Before any newer Proton version successfully installed dotnet, I rolled my own Proton-STL, which just worked.
If interested it is still [here](https://github.com/frostworx/steamtinkerlaunch-tweaks/releases/tag/Proton-6.17-STL-1), but should no longer be required.
good luck so far!

edit: might be interesting to see what the lutris install script does, but probably it just installs dotnet with a compatible proton version

edit2: mono is auto removed by steamtinkerlaunch when installing dotnet
@zany130 you might find one of my replies in the Steam Guide @sonic2kk linked funny 😀

**Comment by sonic2kk** [comment]
I think the EXE is manually added to Lutris, I don't think there's an install script.

I'll have to check older versions of GE-Proton and see how those work with installing DotNet, maybe something broke again with a newer release. That seems like a helpful wiki page though, can't believe I hadn't seen it before haha

**Comment by tuxtergames** [comment]
> I think the EXE is manually added to Lutris, I don't think there's an install script.
> 
> I'll have to check older versions of GE-Proton and see how those work with installing DotNet, maybe something broke again with a newer release. That seems like a helpful wiki page though, can't believe I hadn't seen it before haha

I using lutris GE 7-7 here, you can get [here](https://github.com/GloriousEggroll/wine-ge-custom)  its outdate, but I use to leave when its working, but I think the newer versions will work nice, I can reproduce again here, I think I'm make progress here, soom I give you news

**Comment by tuxtergames** [comment]
> I troubleshooted dotnet _(mostly in vortex/mo2 combination)_ a lot and even wrote a separate [DotNet](https://github.com/frostworx/steamtinkerlaunch/wiki/DotNet) wiki.
> 
> It is a bit outdated now, but might be interesting to read for further information.
> 
> Before any newer Proton version successfully installed dotnet, I rolled my own Proton-STL, which just worked. If interested it is still [here](https://github.com/frostworx/steamtinkerlaunch-tweaks/releases/tag/Proton-6.17-STL-1), but should no longer be required. good luck so far!
> 
> edit: might be interesting to see what the lutris install script does, but probably it just installs dotnet with a compatible proton version
> 
> edit2: mono is auto removed by steamtinkerlaunch when installing dotnet @zany130 you might find one of my replies in the Steam Guide @sonic2kk linked funny grinning

tks for this, I miss the dotnet wiki page, downloading here this proton released for tests!!!!!!

**Comment by tuxtergames** [comment]
@sonic2kk @frostworx finally got working here, theres a problen with dotnet48 instalation and vcrun2015/2019 of winetricks, I don't know how but won't work with pickup software, here my steps to make it work, run game once to create a compatdata folder, Install dotnet48 of winetricks with proton 6.3-8c, download vcrun x64 [here](https://aka.ms/vs/16/release/vc_redist.x64.exe) and x86 from [here](https://aka.ms/vs/17/release/vc_redist.x86.exe), use one step run to install both with the same proton version 6.3-8c, set pickup to run with ats, set to GE-proton 7.18 save and close STL and run the game, pickup will work, just set directories from the games, to make sure that works, click on pickup option and it wont get error anymore, tks for all help here, both of you, soom I'll make a video tutorial in ptbr, maybe I can risk in english too, I'll continue testing but  I think now its solved. 
I dont know the reason but vcrun of winetricks don't work with proton, on lutris works nice, btw its working, thats the reason.....

**Comment by tuxtergames** [comment]
> @sonic2kk @frostworx finally got working here, theres a problen with dotnet48 instalation and vcrun2015/2019 of winetricks, I don't know how but won't work with pickup software, here my steps to make it work, run game once to create a compatdata folder, Install dotnet48 of winetricks with proton 6.3-8c, download vcrun x64 [here](https://aka.ms/vs/16/release/vc_redist.x64.exe) and x86 from [here](https://aka.ms/vs/17/release/vc_redist.x86.exe), use one step run to install both with the same proton version 6.3-8c, set pickup to run with ats, set to GE-proton 7.18 save and close STL and run the game, pickup will work, just set directories from the games, to make sure that works, click on pickup option and it wont get error anymore, tks for all help here, both of you, soom I'll make a video tutorial in ptbr, maybe I can risk in english too, I'll continue testing but I think now its solved. I dont know the reason but vcrun of winetricks don't work with proton, on lutris works nice, btw its working, thats the reason.....

Third try and works here, now I can spend my time playing......
![image](https://user-images.githubusercontent.com/26095484/175412652-b74784b4-9611-4391-b275-b6d66a27fbe2.png)

**Comment by frostworx** [comment]
glad you got it working, but there is really no reason to download vcrun and dotnet manually.
either way have fun playing.
*closing here*
