### ISSUE TITLE
[FEATURE] Mangoapp

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#478]
taken from flightless mango himself here https://github.com/flightlessmango/MangoHud/issues/625

"Mangoapp is a transparent background opengl application with a built in mangohud. It's designed to be run inside a gamescope instance which will display mangoapp ontop of gamescopes output. It also takes frame information from gamescope. The purpose of this is to "easily" make mangohud compatible with any application, or at least any application that gamescope can run. This solves issues with some OpenGL games and certain ports that have stdc++ issues as it's no longer directly injected into the game

Typical usage would look like this:
Create a script like run.sh containing the app you want to run and mangoapp

```
vkcube&
mangoapp
```
then run it with gamescope ./run.sh"

EDIT: 

This could probaly be added to the gamescope menu maybe and overides the other mangohud settings?

or don't know if it would be better for it to be another mangohud option in the gamemenu and it automaticly also enables gamescope as they are expected to be use together

also another benfit of this is this I belive adds a FSR indicator and shows how much sharping you are useing (might be wrong about the last one)

**Comment by frostworx** [comment]
might be nice, but when is it supposed to exit?
Looking at the code it doesn't have a keyboard shortcut _(or I didn't look close enough)_ and with two programs tested I had to
close it via window close button _(and accept the "is busy" requester)_
If the latter is the only option I guess this will lead to more problems than wanted, because imho hiding the window decoration is mandatory for this app. _(yeah killing it when closing the game/steamtinkleraunch would work, but not too nice as well)_

**Comment by zany130** [comment]
closing the game that is using `mangoapp` doesn't close `mangoapp`?
form the testing I did (which to be honest all i did was run it exactly like flightless mango said with a script and then `gamescope ./run.sh`  exiting vkcube also closes `mangoapp`. I still haven't found out exactly how I could inject `mangoapp` into a game

afaik mangoapp seems to be still wip and isn't even well documented yet the steam deck uses it supposedly though

**Comment by frostworx** [comment]
I simply started some random program with a corresponding script, assuming it shouldn't matter what it renders and should exit properly in any case.
the same script started via gamescope leads to a segfault in mangoapp.

**Comment by zany130** [comment]
well progress got some help from flightlessmango and i can get gamescope with mangoapp running in several games by adding this to the launch commands `gamescope -- sh -c "mangoapp& %command%"` however closing the game i can see a `mangoapp` proccses still running  in system monitor was that what you where talking about

**Comment by frostworx** [comment]
yes sure it was - process didn't exit correctly.
I'm not convinced that putting any effort into a mangoapp implementation currently makes much sense.
Waiting a bit until mangoapp closes reliably likely makes more sense here.

**Comment by zany130** [comment]
Fwiw i talked to flightless mango about it and he said it hadn't really been a issue till now since Mango app was pretty much exclusively ran on the steam deck and it's force killed there on game exit

**Comment by frostworx** [comment]
Ah ic. If upstream kills it on exit, I wouldn't mind doing so as well in steamtinkerlaunch.
I won't be able to implement this any time soon _(fortunately holiday season starts very soon :D)_
but if you'd like to work on a PR I'd try to help you when possible.

**Comment by zany130** [comment]
well this what flightlessmango said about it 

"it's possible there is a bug in mangoapp where it'll freeze
hasn't really been a problem since it's primarily used on steamdeck where the whole thing gets force closed"

so its still possible it could be done nicer anyway I wouldn't mind working on a PR but no promises. I have 0 experience with bash (just c++, java and a little bit of python) lol so I have tried taking a look at the code before but haven't really understood it 😅


  I guess I could start with looking at how mangohud was added and the refactor that was done recently I imagine it wouldn't be to diferen't form that, we would just have to change `mangohud` to `mangoapp` and add `sh -c mangoapp&` to the gamescope arguments maybe?

**Comment by frostworx** [comment]
It is mostly not that hard when you got used to it.
But no worries, you don't have to.
Can't tell yet, how to best implement this, need some tests before.
Don't expect anything in the near future :)

**Comment by frostworx** [comment]
main implementation is already done _(offline - see below)_,
but a game launched with mangoapp being enabled doesn't work as expected:
- it doesn't start at all when started through gamescope
- without gamescope both the game and the transparent mango app window start, but they are not merged apparently
  _(btw I guess the "merge" functionality basically is the core "issue/feature" in #490)_

I spent several hours on troubleshooting without any success _(seems like one of the issues might be the game launch parameter, as using other programs instead, f.e. vkcube is more successful)_
Would be a shame to drop the work being done for the general implementation, but I lost my interest in getting this to work for now. If someone wants to debug this, I'd push the changes _(commenting out the variable being written into the gameconfig and being shown in the settings gui, so other users experience isn't affected)_

**Comment by zany130** [comment]
hmm yeah might not be worth it if anything maybe you can push the changes to a diffrent github branch and then I can clone it an maybe play with it a little. 

The reason I say it might not even be worth it is I already messed around with launching mangoapp through the launch commands and while it does work theres some issues here and there and no real advantage as far as I can see ( i mentioned being able to see fsr sharpness within the hud but I haven't been able to get that to work so) from my understanding flightlessmango does intend to replace mangohud with mango app but not any time soon.

But like you said it would be a waste to just disregard all the work you have done so far to implement it so i think it might be nice to push it to a separate branch so it dosn't mess with the main branch

**Comment by frostworx** [comment]
I agree opening a separate branch would be the easiest way in theory. practically I find it easier to keep on working with one branch.
I'll push the changes later the day. Then you can test the function by adding USEMANGOAPP="1" to your test game and
play around with mangoapp part in the `startGame` function.
Will add a note here after the commit.

**Comment by frostworx** [comment]
**note** :)

**Comment by zany130** [comment]
trying to run it as is crashed on gamestart.

Tried uncommenting https://github.com/frostworx/steamtinkerlaunch/blob/96b3b75fb220e514964659246e797e83c6be4b16/steamtinkerlaunch#L15108= and vkcube shows withough mangoapp.

 I noticed when testing mangoapp on my own it has to be ran exactly like this otherwise it won't show 
`gamescope -- bash -c "mangoapp& cmdtorun"` where `cmdtorun` can be `vkcube` or when ran as a steam launch command its `%command%` which resolves to the game. 

So i wonder if that is the issue. Sorry might be completely wrong I'm a newb at bash.

EDIT: also couldn't this in theory just be added to the game scope argumants? So it would just add `bash -c "mangoapp& gamelaunch"` after the `--`
again sorry  If im misunderstanding your code and this is what it is doing

**Comment by frostworx** [comment]
Like I said, I already tested several hours multiple combinations, and yes, that was one of them.
The current state is for testing though, so why not test it again?
It feels cleaner when the "old" gamescope only code part is separated from this one, that's why it is triggered independently of it, but basically the new function does the same. Change it as you like, it is meant for testing :)
No offense, but I don't want and can't spend more time into this for now.
happy debugging!

**Comment by frostworx** [comment]
@zany130
even if you have no success please post it as a result here.
we can still elaborate if it is worth top keep the wip code changes or simply drop it again
no hurry

**Comment by zany130** [comment]
I been trying to get this to work for the last two days but couldn't figure it out. I tried copying the code from here down https://github.com/frostworx/steamtinkerlaunch/blob/18d2d15dce4e49c1768a70673c75a5fe5a65be01/steamtinkerlaunch#L15080

into a script to debug and I was able to get vkube to open but it doesn't show mangoapp. So my guess there something wrong with the way its written.

like I said above Im able to get it work as a steam launch command or through vkcube in a terminal if I type it exactly like this `gamescope -- bash -c "mangoapp& cmdtorun"` (to run it with steam i replace `cmdtorun` with `%command%` which I guess means the game launch command)

i was trying to rewrite your code like that because my guess is it doesn't have the `"` around mangapp and the game launch command (or vkcube) but I am very new to bash and couldn't figure it out. the furthest I got was this

```bash
───────┬─────────────────────────────────────────────────────────────────────────────────────────────
       │ File: test.sh
───────┼─────────────────────────────────────────────────────────────────────────────────────────────
   1   │ #!/bin/bash
   2   │ MANGOAPP="mangoapp"
   3   │ GAMESCOPE="gamescope"
   4   │
   5   │ #"$(command -v "$GAMESCOPE")" -- bash -c \""$(command -v "$MANGOAPP")" vkcube\" 2>&1
   6   │ "$(command -v "$GAMESCOPE") -- bash -c \"$(command -v "$MANGOAPP")\" /usr/bin/vkcube"
   ```
which gives 
`./test.sh: line 6: /usr/bin/gamescope -- bash -c "/usr/bin/mangoapp" /usr/bin/vkcube: No such file or directory`
 so its not including vkube in the `"`

**Comment by frostworx** [comment]
Gave it another quick test.
The main problem simply is that the variables used within the function need to be exported before.
Additionally `command -v` or `which` are incompatible in this combination.
Don't have a 100% working solution and very likely won't work on stl over the weekend,
but it should be easy to fix.

edit: the main problem will be exporting an array - here the RUNCMD array _([stackoverflow exporting an array in bash](https://stackoverflow.com/questions/5564418/exporting-an-array-in-bash-script))_

**Comment by frostworx** [comment]
Changed my mind an coded some hours instead of relaxing...
mangoapp should generally work fine after this monster commit
_(renamed "Steam Category" to "Steam Collection" everywhere, which is the huge part of the commit)_
would be nice if you added a some info to this [MangoApp](https://github.com/frostworx/steamtinkerlaunch/wiki/MangoApp) wiki dummy

_(I also added a "MangoApp" [Steam Collections](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Collections) file btw)_

**Comment by zany130** [comment]
WOW awesome work 😍. Had to move my config files into a backup folder so it can create the configs again as for some reason it was crashing immediately with a blank mangoapp window. Ill debug some more and provide a log in a bit. Also am I correct in assuming that this while disable the regularmango hud? (as it should) I tested with both enabled to see what would happen and only mangoapp showed up.

EDIT: configuring steamtinkerlaunch with the same exact settings doesn't crash so IDK whats going on with my old config here is a log from the old config where it immediately exits

[991270.log](https://github.com/frostworx/steamtinkerlaunch/files/9033377/991270.log)

**Comment by frostworx** [comment]
a diff between your old and new config might help.
checked the log quickly and didn't see anything suspicious.

**Comment by zany130** [comment]
[991270.diff.txt](https://github.com/frostworx/steamtinkerlaunch/files/9033641/991270.diff.txt)

it seems for some reason the old config was pointing to an invalid proton version or something changed it and now it works

anyway since I tested the mangoapp feature and everything works as expected I guess this can be closed now?

**Comment by frostworx** [comment]
.
