### ISSUE TITLE
"Quiet" launch option for SteamTinkerLaunch?

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#479]
We can set the timeout to 0 for a game but I believe then if a user wants to change this, they have to edit the STL config file for that game. It would be nice if a user could pass a launch option to a game to basically skip the wait requester, so that if they want to show it again they can just remove that launch option, if this is possible at all. For example passing `-stl-nowait` to a Proton game or `steamtinkerlaunch -stl-nowait` to a native Linux game would skip the wait requester for that game, but would show it once the option is removed. Something along these lines is what I had in mind:

![image](https://user-images.githubusercontent.com/7917345/171335408-bc9537b7-dc94-404f-aa9e-e7c6bee867b0.png)

The reason I preface it with `-stl` is to differentiate it from games that might take a regular launch option like this, however that leads into a potential problem I foresee with this. Passing a launch option like this would probably interfere with at *least* one game that might get angry if an unexpected launch option is passed to it. So STL might need to check for this launch option and remove it from the options passed to a game so that it doesn't crash. That might be a bit of a pain. There's also the unlikely event that a game might expect a launch option like this, so a unique name would need to be chosen. I attempted to suggest one as unique as possible but you never know :stuck_out_tongue: This is likely something that could be dealt with come the time, if such a time ever comes!

There's a point to be made, "if we add this feature, where do we draw the line with launch options?" Personally I see this as more of a convenience and the use-case can really apply to the wait requester. The idea is to have a more straightforward toggle for the wait requester that doesn't involve digging into the STL config files.

I couldn't find any info about this on the wiki but I could've missed it and something like this might already be in STL :sweat_smile:

**Comment by frostworx** [comment]
The base idea is good, but I don't like to mess around with steamtinkerlaunch internal commands mixed up with the original incoming game arguments. This will very likely cause a lot of work and trouble, far too much for a probably rarely used convenience feature.
A simpler and easier to maintain approach would be to simply check for a temporary file _(f.e. a "skipwaitrequester" file in `/dev/shm/steamtinkerlaunch/SWR.txt`)_
_(this could be expanded to another `/dev/shm/steamtinkerlaunch/USWR.txt`)_
to automatically "unskip" the corresponding gamecfg.
creation/deletion of those temp files could be achieved with a simple command line option.

**Comment by frostworx** [comment]
[just](https://github.com/frostworx/steamtinkerlaunch/commit/414d7648253870e686a6d414af442004f87f3880) added temporary (un)skip options for the [Wait Requester](https://github.com/frostworx/steamtinkerlaunch/wiki/Wait-Requester)
and also an option to re-enable a perpamently disabled wait requester for the next started game.

**Comment by sonic2kk** [comment]
Seems to work great in my tests, thank you!

**Comment by frostworx** [comment]
Thanks for testing! :)
