### ISSUE TITLE
FSR sharpness not working in gamescope

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#481]
the FSR sharpeness option in the gamescope menu is no longer working correctly its writing the sharpness value as `--sharpness 2` which is incorrect it should be `--fsr-sharpness 2` Im guessing this issue was introduced here  https://github.com/frostworx/steamtinkerlaunch/pull/471

leaving it as `--sharpness 2` (when using FSR) immediately crashes while `--fsr-sharpness 2` works (when using FSR)

@sonic2kk  can you reproduce this issue? you mentioned that both FSR and nis should be able to take the `-sharpness` parameter ?

**Comment by zany130** [comment]
so I guess the stable version of gamescope in the arch repos doesn't have NIS upscaling and more importantly doesn't understand the `--sharpness` parameter. I did test NIS with the stable version of gamescope and I thought it worked and it even didn't crash with the `--sharpness` parameter but apparently, it was just being ignored so that's why it would still boot but when I used FSR it was still expecting the old option

**Comment by sonic2kk** [comment]
Apologies for the late response but you're correct, Gamescope stable doesn't have this yet. I usually build Gamescope from git and didn't realise until I installed it from `community/gamescope`.

Perhaps a note about this could be added to the wiki, that some features available in the Gamescope menu might rely on a very new release. Gamescope doesn't seem to have "traditional" releases so I'm not sure if it's worthwhile mentioning specific features since they could be rolled into the arch repos at any time.

Sorry for the confusion here, and if there's a better way to handle this I'm open to suggestions :smile:

**Comment by zany130** [comment]
no my bad for assuming i had a supported version yeah a note maybe on the wiki might be good but if gamescope doesn't have traditional fixed releases then maybe it won't be to helpful. or if this could somehow be easily logged (doubt it though since its not steamtinkerlaunch that's failing but gamescope so gamescope would have to log the error I guess)

**Comment by frostworx** [comment]
good find!
We could simply grep for `--fsr-sharpness` in `gamescope --help`.
when found use it as parameter, else use `--sharpness`
Not nice apparently, but should do it, shouldn't it?

**Comment by frostworx** [comment]
please test if this commit fixes it

**Comment by zany130** [comment]
well on version `10.0.20220602.r799.cd50d1a-1` which i believe is the latest it still uses `--sharpness` instead of `--fsr-sharpness` also not sure about grep for `--fsr-sharpness` since both the git and stable version have that in there help. Wouldn't it be better the other way around? also maybe the wiki and this issue are enough for someone to be aware of this issue?

**Comment by frostworx** [comment]
```
$ yay -Qo /usr/bin/gamescope 
/usr/bin/gamescope ist in gamescope 3.11.30-1 enthalten
```

```
$ gamescope --help 2>&1 | grep -e "--fsr-sharpness"
  --fsr-sharpness                FSR sharpness from 0 (max) to 20 (min)
```

haven't tested this apart from the standalone grep ¯\\_(ツ)_/¯ 

Why care if the wiki is enough, when there already is a function? I'd guess chances are higher like this.

**Comment by frostworx** [comment]
totally forgot about this issue. Should this be reopened? any thoughts?

**Comment by zany130** [comment]
forgot about it too 😅 It still doesn't work for me on the latest git with gamescope from the arch repos 
```
pacman -Qi gamescope
Name            : gamescope
Version         : 3.11.30-1
Description     : SteamOS session compositing window manager
Architecture    : x86_64
URL             : https://github.com/Plagman/gamescope
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : gcc-libs  glibc  libcap.so=2-64  libdrm  libliftoff.so=0-64  libpipewire-0.3.so=0-64
                  libvulkan.so=1-64  libwlroots.so=10-64  libx11  libxcomposite  libxdamage  libxext
                  libxfixes  libxkbcommon.so=0-64  libxrender  libxres  libxtst  libxxf86vm  sdl2
                  vulkan-icd-loader  wayland  wayland-protocols  wlroots  xorg-server-xwayland
Optional Deps   : None
Required By     : None
Optional For    : mangoapp  steamtinkerlaunch-git
Conflicts With  : None
Replaces        : None
Installed Size  : 610.23 KiB
Packager        : Maxime Gauduin <alucryd@archlinux.org>
Build Date      : Tue 26 Apr 2022 04:23:00 AM EDT
Install Date    : Tue 07 Jun 2022 02:33:22 PM EDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

here is a log
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8855737/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
thx for testing. tested now myself.
it can't work because the variable "$GSC" does not exist in that function... 🙄

**Comment by frostworx** [comment]
now it works :)

**Comment by zany130** [comment]
👍 yup works on my end as well

**Comment by sonic2kk** [comment]
On the back of this, [I updated the wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/GameScope) with a note to point out that STL may expose very new Gamescope features, just to clarify :smile:

**Comment by frostworx** [comment]
thx 👍
edit: really impressive wiki! 😀
