### ISSUE TITLE
Vortex install was working perfectly until it randomly stopped working

### ISSUE THREAD

**Issue by domglusk** [sonic2kk/steamtinkerlaunch#485]
I have no other information that can be provided. there wasn't any crash log, it just doesn't work anymore. MO2 has never worked so I've been forced to use vortex, which has been great until for some reason I can't figure out it stopped.

**Comment by sonic2kk** [comment]
Unfortunately, Vortex can stop working randomly with Proton/Wine after updates. See the [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Vortex#additional-vortex-notes):
> Vortex can stop working under linux/wine anytime after an update (as it already did before)

It is possible that Vortex has updated and that's why it's not working. However, in the interest of trying to trace where the problem is coming from, there is some information you could provide :smile: 
- What version of SteamTinkerLaunch are you using? (If possible try using the latest git release that your package manager offers)
- What distribution/DE are you using?
- What game are you trying to use with Vortex? (In case someone can test it)
- Could you run STL again and try to launch Vortex again, and then upload the file in `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`? (Should generate a fresh log file)

I'm not sure where any potentially Vortex-specific logs might be logged out, perhaps somewhere in the compatdata folder for it. Frostworx might be able to shed more light on debugging Vortex-specific problems.

Additionally, I'd also strongly encourage you to at some point open an issue regarding MO2 not working, as it *should* work and it could help diagnose any potential issues with STL :slightly_smiling_face:

**Comment by domglusk** [comment]
I don't believe vortex has any crash logs or if it does its scattered somewhere I can't find it. I was able to get vortex working from running it just through wine with wine-ge-custom, same with mo2, problem is that they don't work with nexus links.

**Comment by frostworx** [comment]
First and foremost, thank you very much for your help @sonic2kk!

@TheKarion @sonic2kk already summed it up very good. 
atm you don't sound like you're truly interested in finding a solution or in helping yourself here,
but you might want to give the information you've been asked for.

_(btw it is a _bit_ more than starting vortex/mo2 through some wine flavor to get it working on every system automagically,
creating the mime type for the nexus link is the smallest problem)_

**Comment by domglusk** [comment]
Hi sorry, I am interested in finding a solution, I wasn't able to get on my laptop last night but wanted to give an update,
I've tried the chaotic aur and aur steamtinkerlaunch packages as well as steamtinkerlaunch-git in the aur.
I'm currently on Endeavour OS
I was modding New Vegas with TTW, which was working flawlessly, and as proof I can still play TTW with no problem, I just can't add any mods via a mod manager. I wouldn't be surprised if it is just a wine update but what confuses me is I was able to get vortex working via wine-ge-custom but without nexus link handling (making it pretty much useless). 
Thanks for telling me what file to upload, as requested here it is
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8855052/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
This is very likely no steamtinkerlaunch problem, but more likely some Vortex or wine/proton problem.
You should also have a `/dev/shm/steamtinkerlaunch/vwrun.txt` log, which should contain the stdout coming directly from wine/proton vortex. maybe it has some hints what went wrong.
apart from that I'd try to recreate the vortex compatdata by
renaming
`/home/frostwork/.config/steamtinkerlaunch/vortex`
and then running
`steamtinkerlaunch vortex install`
again.

**Comment by domglusk** [comment]
Will do and send an update, the vwrun.txt you suggested looking at is currently empty, anything I can do to fix that?

**Comment by frostworx** [comment]
hm, the `vwrun.txt` indeed isn't very useful.
just ran 
`steamtinkerlaunch vortex start` to create it and only got

```
logging started

logging started
Checking for update
Update for version 1.5.13 is not available (latest version: 1.5.13, downgrade is allowed).

```
I might add an option to remove the `WINEDEBUG="-all"` variable
_(or maybe even re-introduce the option to configure the `WINEDEBUG` options for vortex)_
but not in the near future

**Comment by domglusk** [comment]
Do you know if this is a per distro (arch vs ubuntu) issue or if its linux wide? I'm trying to learn more about how everything works

**Comment by sonic2kk** [comment]
> Do you know if this is a per distro (arch vs ubuntu) issue or if its linux wide?

More than likely this is Linux wide, basically Vortex does not even attempt to support Wine on Linux from what I understand, so updates can cause issues.

> I was modding New Vegas with TTW ...

I haven't tried TTW but I've been able to mod and play New Vegas with MO2. If you tried using MO2 a significantly long time ago you could try it again at some point in the future as there have been some changes to how it works in STL and on Linux. Changing over to a new mod manager can be a pain, I've been there so I'm not suggesting you do it right now :slightly_smiling_face: I recommend checking the [modding wiki page too](https://github.com/frostworx/steamtinkerlaunch/wiki/Modding#mo2) on installing mods with MO2 if you do switch, as there are a couple of quirks and I've documented some fixes for them.

The reason Wine-GE likely works correctly is that whatever version STL is using (perhaps Proton 7.0-2?) is based on an older version of Wine, but Wine-GE has fixes that might even indirectly have fixed Vortex. Vortex probably haven't released an update to break Wine but are using something that the default STL Vortex Wine version doesn't implement properly or correctly, but Wine-GE does implement this and thus Vortex works with that.

@frostworx is there a manual way to fix the Nexus links for Vortex? That would at least help mitigate the problem for now

**Comment by frostworx** [comment]
@TheKarion Should be distribution independent as you're using a custom proton/wine build which is not installed systemwide in every case.
It could be a distribution related issue, if you were using a wine/proton installation which comes from the distributions package management.

**Comment by frostworx** [comment]
@sonic2kk I guess you mean the mime type setting which opens nexus urls with vortex, right?
you can edit/read `~/.local/share/applications/vortex-steamtinkerlaunch-dl.desktop` or course anytime.
I'd also guess that renaming that file would automatically lead to a re-creating when starting vortex the next time via steamtinkerlaunch (too lazy to check the code right now 😀)

**Comment by domglusk** [comment]
Interesting, renaming ~/.config/steamtinkerlaunch/vortex and reinstalling made it launch just fine with no problems. As for @sonic2kk said, I know MO2 just is a superior mod manager, and I need to use it, but vortex has worked for me so far, but as soon as I get mo2 working I'll switch. TTW only takes about 15 minutes to get working with Vortex, all you need to do is make a TTW folder in the vortex mods storage folder, (so making a manual mod) and run the TTW installer and point it to install in said folder.

**Comment by domglusk** [comment]
Sadly MO2 isn't working via steamtinkerlaunch, I'm getting an error: /usr/bin/steamtinkerlaunch: line 12574: innoextract: command not found
After running steamtinkerlaunch mo2 install and then running steamtinkerlaunch mo2 start, theres no error in the terminal, but the gui pops open for a second only to close and not open anything

**Comment by frostworx** [comment]
you're welcome! for the "error", you might want to install innoextract

**Comment by domglusk** [comment]
I did but it's still not launching

**Comment by sonic2kk** [comment]
> Interesting, renaming ~/.config/steamtinkerlaunch/vortex and reinstalling made it launch just fine with no problems

Huh, that is interesting. If we can get to the bottom of this, perhaps we could add a note somewhere about it on the wiki :) Modding can be finicky!

As for innoextract, you could try removing `/dev/shm/steamtinkerlaunch`, restarting Steam and trying again (removing that folder is a bit of a cure-all for me).

**Comment by domglusk** [comment]
I don't have a /dev/shm/steamtinkerlaunch folder. I did install innoextract before doing mo2

**Comment by sonic2kk** [comment]
I just read up and to be more specific, could you try launching New Vegas with STL and opening MO2 that way? And enabling it in the Game Menu 🙂 

If no `/dev/shm/steamtinkerlaunch` folder exists after that, I'm not totally sure why that would be the case, however there should be a log file in `~/.config/steamtinkerlaunch/logs/steamtinkerlaunch/title/Fallout New Vegas.log`. Additionally, there should be MO2 logs (generated by MO2 itself) available in `~/.config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/New Vegas/logs`. I'm not entirely sure how useful the MO2 logs might be but it's worth nothing that they're there 🙂

**Comment by domglusk** [comment]
Running with stl launch option won't allow new vegas to run at all. There isn't a log folder in the .config location either, not even a /title/ folder

**Comment by sonic2kk** [comment]
Proton games should use the SteamTinkerLaunch compatibility tool, the launch option is intended for native Linux games.

My bad if my explanation was confusing, I meant for you to use STL as a compatibility tool, the same way you'd force a custom version of Proton. That option can be found by right clicking > Properties > Compatibility and ticking the checkbox.

EDIT: In case you haven't before, you add STL as a compatibility tool by running `steamtinkerlaunch compat add` in a Terminal and then restarting Steam (Steam needs to be restarted for new compatiblity tools to show up as far as I know)

**Comment by domglusk** [comment]
Thanks I hadn't done that before. The current issue right now is Vortex isn't handling links. On firefox it doesnt give me a error but on Opera it says it's trying to open mo2 xdg-open despite me not having any instance of mo2 installed, I uninstalled all of it. I've tried resetting the association but it refuses to go to nexus. I'm able to paste a link and nexus work that way luckily.

**Comment by domglusk** [comment]
Using the launch option opened mo2! Thanks! Still not handling links though sadly.

**Comment by sonic2kk** [comment]
For Vortex, I haven't looked into it much myself but [this reply](https://github.com/frostworx/steamtinkerlaunch/issues/485#issuecomment-1148990244) from Frostworx might be able to help. If not, I'll keep digging as best I can.

As for MO2, you could check to see if a similar file exists as above and modifying/deleting that. If that doesn't work, MO2 has an option somewhere to reset Nexus mod association links and it uses your default browser for this I believe.

> On firefox it doesnt give me a error

Does this mean it worked on Firefox? Just curious because I use Firefox and MO2 links work fine, so maybe it's a problem with Opera and/or Chromium based browsers.

We'll get to the bottom of this issue yet! 😄

**Comment by domglusk** [comment]
Sorry no I should've specified. On Firefox its a silent error, nothing happens, but on Chromium its the same issue (links not being handled) but it does give me an error message. And I'm not sure how to mime a link.

**Comment by sonic2kk** [comment]
I'm also not the most familiar myself but I had a look at `~/.local/share/applications` and found a file called `ModOrganizer-steamtinkerlaunch-dl.desktop`. I opened that with a text editor and it has a line `MimeType=x-scheme-handler/nxm;x-scheme-handler/nxm-protocol`. I imagine Vortex should have a file with a similar name in the same folder and should expect a similar line,

Try pasting that line into the `.desktop` file for MO2 and/or Vortex. As  Frostworx mentioned renaming (or removing) these files would likely have the same effect but you should be able to paste that line in and/or replace the existing `MimeType=` line in those `.desktop` files. If they don't exist, it shouldn't really matter where you paste it in those files :slightly_smiling_face: 

And if it does already have that MimeType line... I suppose try renaming the files so they get re-created? :sweat_smile:

**Comment by domglusk** [comment]
Aha that worked! I deleted the files in applications, relaunched it and so far its working with chromium. Firefox doesn't want to work right now but maybe when the cache refreshes it will.

**Comment by sonic2kk** [comment]
Woohoo that's great news! Fingers crossed you can get Firefox working too, it could indeed be a caching issue.

And hopefully now that they work they stay working, MO2 and Vortex 🎉 Keep us updated, and thanks for your patience!

**Comment by frostworx** [comment]
I guess this can be closed then.
Thank you so much for continued patient support, @sonic2kk 👍

**Comment by matt-laird** [comment]
Any idea how to get the `nxm` handler to work for the flatpak install? (Both Steam & Steamtinker) It seems that the `.desktop` file gets created in `~/.var/app/com.valvesoftware.Steam/.local/share/applications/`. If you copy that to the correct place being `~/.local/share/applications` it seems to not like the fact that the executable path in the desktop file is `/app/utils/steamtinkerlaunch/bin/steamtinkerlaunch vortex u %u`. I'm guessing cause its outside of the flatpak environment its not happy and can't the launch Is there any magic I can cast here to link this up to work? Or am I missing something else completely?

**Comment by frostworx** [comment]
I'd start with reading the corresponding wiki entry.

**Comment by matt-laird** [comment]
Appreciate the response, must have missed this earlier. For those who find have similar issue here is the wiki entry - https://github.com/frostworx/steamtinkerlaunch/wiki/Flatpak#caveats-of-the-flatpak-version-of-steamtinkerlaunch
