### ISSUE TITLE
Can't Select "Proton Experimental" from Proton List?

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#495]
Seemingly I can't choose to run a game with Proton Experimental from the list of Proton versions on the Game Menu. Typically that's fine since GEProton tends to be more up-to-date and I use that, but occasionally there are cases where one might want to use the Bleeding Edge branch of Proton Experimental which might be more recent.

**Comment by frostworx** [comment]
hm, this worked last time I tried. something must have changed since then.

**Comment by sonic2kk** [comment]
Hmm, SteamTinkerLaunch is actually missing a few versions of Proton that I can select from Steam normally. STL shows the following list, which matches the `ProtonCSV.txt` in `/dev/shm/steamtinkerlaunch`:

![STL Proton Versions](https://user-images.githubusercontent.com/7917345/172651073-f0540138-a0c1-4b5c-9b93-a67f3a5abb8c.png)

Steam gives me the following Proton versions (GE-Proton7-20 is cut off at the top)

![Steam Proton Versions](https://user-images.githubusercontent.com/7917345/172651568-d078fdd8-ff45-4ff6-80e7-3c47f1dd9350.png)

I don't actually have Proton 3.16-9 or Proton 3.7-8 installed yet Steam still shows it, so I think it's fine for STL to not show those versions. But I *do* have Proton 6.3-8 installed and STL isn't showing that. Interestingly this version of Proton is also installed on the same drive as Proton Experimental.

The name of this drive with the two missing versions of Proton has a space in it, could that be throwing STL off?

**Comment by frostworx** [comment]
good point, I guess the space in the mount path is related.
should probably be easy to fix, but can't tell when I find the time to look into this

edit: yes experimental is listed fine here, so very likely path related

**Comment by frostworx** [comment]
does your log list the corresponding path in `getAvailableProtonVersions`?

**Comment by frostworx** [comment]
I was able to reproduce this in a separate test script and likely just fixed it.

**Comment by sonic2kk** [comment]
Woohoo, that seems like its fixed!

![Fixed Proton list](https://user-images.githubusercontent.com/7917345/172707028-bcd4eb37-7dc6-4af7-b988-95097676438b.png)

Thank you once again for another quick turnaround on fixing bugs :smile:
