### ISSUE TITLE
feature request: have installing LOOT easier in MO2 prefix

### ISSUE THREAD

**Issue by justalinuxuser1997** [sonic2kk/steamtinkerlaunch#496]
LOOT is an essential utility for sorting mod load orders for besthesda games. currently installing it requires a non-obvious workaround to installing it, which is to activate the "explore virtual folders" option in MO2.

**Comment by frostworx** [comment]
`"LOOT is a program for sorting mod load orders. I made a github account and made a request there. But I feel like I shouldn't have to make an account there when I am not a programmer"`

[full reddit thread](https://www.reddit.com/r/SteamTinkerLaunch/comments/v7614g/how_does_one_get_loot_installed_in_the_mo2_prefix/) with reply...

**Comment by frostworx** [comment]
```
This is the current version. https://github.com/loot/loot/releases/tag/0.18.3

I don't know what else information to provide and how. like I said, i am not a developer so dissecting an installer to see how it works is not something I'm familiar with.

EDIT: okay I'm blind and didn't see the .7z archives bypassing the need to use the installer
```

[via](https://www.reddit.com/r/SteamTinkerLaunch/comments/v7614g/comment/ibqicop/?utm_source=share&utm_medium=web2x&context=3)

so does this mean the feature request is invalid, because extracting the 7z is already enough?

**Comment by sonic2kk** [comment]
I use LOOT with MO2 quite regularly, it came with the MO2 installation. Could you elaborate on what the problem is?

**Comment by justalinuxuser1997** [comment]
I wasn't aware that it came with MO2, i always installed it separately

**Comment by sonic2kk** [comment]
There should be a button on the right-hand side of MO2's mod list that says "Sort" and this uses LOOT, or at least it claims it does (and indeed the MO2 files show LOOT data files). Hopefully that should resolve the issue but I'm not going to close it in case there's anything further to add 😄

**Comment by sonic2kk** [comment]
Hi, was using either the LOOT that comes with MO2 or the 7z archives enough to solve this?

**Comment by frostworx** [comment]
I'd say [this](https://www.reddit.com/r/linux_gaming/comments/v9m7y0/what_modding_tools_are_available_for_linux/ibxqxv7/?context=3) explains it pretty good... 🤨

Thanks for all your help, @sonic2kk 👍
