### ISSUE TITLE
[User Error/Mistake] MO2 cannot launch from Steam Tinker Launch

### ISSUE THREAD

**Issue by DagothUrTheFalse** [sonic2kk/steamtinkerlaunch#498]
I have been unable to use mo2 through steam tinker launch since i made the mistake of manually deleting my mo2 installation in an attempt to migrate a portable profile to a standard mo2 one, now when using mo2 to run a game with mo2 it simply fails as far as I can tell. Apologies for the lack of intelligence on my part, I have no earlier logs.

[377160.log](https://github.com/frostworx/steamtinkerlaunch/files/8937167/377160.log)

**Comment by frostworx** [comment]
# in case it is not mo2 related:
seems like you do not have set a valid proton version _(maybe removed?)_
you might want to remove `/dev/shm/steamtinkerlaunch` _(always a good start with debugging, because the directory only has temp files, which are re-created when missing)_, then open the steamtinkerlaunch settings and choose a valid
proton version for your current game (in `GAME MENU`) and optionally as default for all your games in `DEFAULT`

# in case it is mo2 related:

not sure what you deleted manually exactly, but I'd suggest to re-try after removing the temp dir
`/dev/shm/steamtinkerlaunch` recursively.
If that is not enough it is probably the easiest to remove `/dev/shm/steamtinkerlaunch` again, but also remove/rename your 
`/home/jon/.config/steamtinkerlaunch/mo2/`

good luck so far

**Comment by DagothUrTheFalse** [comment]
After following your suggested steps i am still having the issue, the game launches perfectly well through both proton ge 2 as well as through steam tinker launch without mo2, it is also successful when skipping mo2 with it enabled. Of note is that it attempts to download mo2 every time even if i have not deleted anything after the first attempt with it enabled.

[377160.log](https://github.com/frostworx/steamtinkerlaunch/files/8942577/377160.log)
.

**Comment by DagothUrTheFalse** [comment]
oops, sorry, this is my first time using github, though clicking close would tell me more vefore doing it, thinking it was drop down menu and not a button.

**Comment by frostworx** [comment]
Thanks for retesting! Will need some days until I can look into this, so please have some patience.

**Comment by DagothUrTheFalse** [comment]
Alrighty, thank you for your time so far.

**Comment by frostworx** [comment]
I've seen you're using the last stable version 10.0.
Please retest with current git-master, as it might already have a fix for your issue.
The output of
`ldd "$(command -v innoextract)"`
might be intestesting as well.

**Comment by DagothUrTheFalse** [comment]
result of command 
	linux-vdso.so.1 (0x00007ffe70b10000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f68ee38b000)
	libboost_iostreams.so.1.74.0 => /lib/x86_64-linux-gnu/libboost_iostreams.so.1.74.0 (0x00007f68ee373000)
	libboost_filesystem.so.1.74.0 => /lib/x86_64-linux-gnu/libboost_filesystem.so.1.74.0 (0x00007f68ee353000)
	libboost_program_options.so.1.74.0 => /lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0 (0x00007f68ee30e000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f68ee0e2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f68edff9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f68edfd9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f68eddb1000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f68edd95000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f68edd82000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f68edcb3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f68ee466000)


and log file for the same immediate crash behavior
[377160.log](https://github.com/frostworx/steamtinkerlaunch/files/8959646/377160.log)

**Comment by frostworx** [comment]
1) does the directory `/home/jon/.config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/Modding/MO2/` even exist after extraction and what does it contain?

2) does
`innoextract /home/jon/.config/steamtinkerlaunch/downloads/mo2/Mod.Organizer-2.4.4.exe`
work correctly?
it created an `app` directory in your `$PWD` and should contain `ModOrganizer.exe` besides all other mo2 files.

3) looks like mo2 does not even get installed at all, so I wonder what you meant with your initial issue. did you mean a mo2 installation you did without mo2? if so it is not related here

**Comment by DagothUrTheFalse** [comment]
1. It does not, stopping at the modding folder

2. Warning: Unexpected setup data version: 6.1.0 (unicode)
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Stream error while parsing setup headers!
 ├─ detected setup version: 6.1.0 (unicode)
 └─ error reason: basic_ios::clear: iostream error
If you are sure the setup file is not corrupted, consider 
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error and 3 warnings.

3. No i mean i installed mo2 with steam tinker launch, however during setup for the game i was using i made it a portable profile, i later tried to correct that and make it a non portable profile and deleted the entire mo2 installation. Apologies for sloppy wording.

**Comment by frostworx** [comment]
interesting. it for whatever weird reason your innoextract can't extract your Mod.Organizer-2.4.4.exe file.
maybe the downloaded file is broken?
please paste the output of
`md5sum < /home/jon/.config/steamtinkerlaunch/downloads/mo2/Mod.Organizer-2.4.4.exe`

should be 
`eaef94e94350807d6a73151483f0d46b  -`
_(92268268 bytes filesize)_

which `innoextract --version`
do you have installed?
here:

```
$ innoextract --version
innoextract 1.9
Extracts installers created by Inno Setup 1.2.10 to 6.0.5
```

3) tbh I still do not get it. probably a language barrier on my end - sorry for the confusion. let's ignore this for now :)

**Comment by DagothUrTheFalse** [comment]
1. eaef94e94350807d6a73151483f0d46b  -

2. I have 1.8 installed
innoextract 1.8
Extracts installers created by Inno Setup 1.2.10 to 6.0.2

**Comment by frostworx** [comment]
ah, as you see your innoextract is too old. (your 1.8 supports up to 6.0.2, the MO2 exe is 6.1.0)

_(maybe worth to add a version check in steamtinkerlaunch sometime later)_

**Comment by DagothUrTheFalse** [comment]
How would I update innoextract?

**Comment by frostworx** [comment]
using your package management. this is not steamtinkerlaunch related

**Comment by frostworx** [comment]
if your distro does not offer official newer packages and you do not want to install it manually, you have still the option to temporarily remove/rename your innoextract binary. then steamtinkerlaunch uses the MO2 installer directly via proton
(will take a bit longer, but should work as well)

**Comment by DagothUrTheFalse** [comment]
Thank you, i went with just removing innoextract for a bit as pop os did not supply innoextract 1.9 nor boost which is a manual install requirement.

**Comment by frostworx** [comment]
glad you got it working. happy tinkering :)
