### ISSUE TITLE
MO2 Not Handling Nexus Links

### ISSUE THREAD

**Issue by domglusk** [sonic2kk/steamtinkerlaunch#502]
So this is a bit strange as it WAS using it for maybe 5 mods, then I restarted MO2 and it stopped. The way I got it to run was running nxmhandler.exe, which worked once. Yet now that I run it it's not doing anything. Tested on both Chromium and Firefox. I've completely wiped out Vortex from my install, and the file association in Firefox states its for MO2 Steamtinkerlaunch. Also tested through steamtinkerlaunch mo2 url [link] but sadly it didn't work.

**Comment by frostworx** [comment]
I'd guess this is more a mime type setting issue than a steamtinkerlaunch issue,
so I suggest reading the mime type related hints in your [other issue](https://github.com/frostworx/steamtinkerlaunch/issues/485)
and check your mimeapp settings in `~/.local/share/applications/`
_(f.e. multiple `x-scheme-handler/nxm;x-scheme-handler/nxm-protocol` entries)_

**Comment by domglusk** [comment]
Will do thanks.

**Comment by frostworx** [comment]
please close here if you got it fixed or don't have any other questions

**Comment by domglusk** [comment]
Alright after working on it I was finally able to get it to work by completely refreshing Firefox, which fixed the link. It might have been it was handling an out of date version of steamtinkerlaunch nxm or older mo2 install, but its fixed now.
