### ISSUE TITLE
built-in pressure vessel functions used by anyone?

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#504]
does anybody actually use the built-in [PressureVessel](https://github.com/frostworx/steamtinkerlaunch/wiki/Pressure-Vessel) variables?

- ` PRESSURE_VESSEL_VERBOSE="$STL_PV_VERBOSE" `
- `PRESSURE_VESSEL_SHELL="$STL_PV_SHELL" `
- `PRESSURE_VESSEL_TERMINAL="$STL_PV_TERMINAL"`

If no, I'll likely remove it shortly to clean the `startGame` function a bit _(also saves a bit space in the already too cluttered game settings menu)_

**Comment by zany130** [comment]
I sometimes ( but very rarely)  use  SLR which afaik relies on preassurevessel ? https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/tree/master/pressure-vessel

**Comment by sonic2kk** [comment]
I use the Steam Linux Runtime with SteamTinkerLaunch fairly frequently, quite a lot of native games I own need it forced (at least on Arch). If these PressureVessel variables are needed for the Steam Linux Runtime I guess I've been indirectly relying on them and would be in favour of keeping them :slightly_smiling_face: I've never directly touched these variables from the Game Menu though

**Comment by frostworx** [comment]
yeah, the pressurevessel variables belongs to SLR.
I'm not going to remove SLR support - this would be insane 😀
The three variables can be enabled within steamtinkerlaunch and
are all optional and only meant for debugging.
I didn't use them often myself, so I could not even say if they already exist upstream or are called differently meawhile :)

**Comment by sonic2kk** [comment]
Ah, well in that case I haven't used them :smile: And I'm not particularly attached one way or the other about keeping them, not sure how big the use-case is for specifically debugging pressurevessel is

**Comment by frostworx** [comment]
hehe thanks for the feedback, "usual suspects" :+1: 
I'll remove the pressure vessel stuff "shortly" _(no idea when tbh, RL is turbulent currently and next holidays are close)_
leaving open here for a reminder for myself :)

**Comment by frostworx** [comment]
heh, that was easy :)
[removed](https://github.com/frostworx/steamtinkerlaunch/commit/c696f73ddc17bce14c4fc9510b8744c0f7532c37)

next - specialk (not that easy :))
