### ISSUE TITLE
MO2 and  Vortex are not starting 

### ISSUE THREAD

**Issue by jchallet** [sonic2kk/steamtinkerlaunch#510]
# Please see this [sticky note](https://github.com/frostworx/steamtinkerlaunch/issues/93) for what is required for a good issue

Mod Organizer 2 does nothing at all when the button is clicked on the Steamtinkerlaunch  main menu. Vortex will open a list of menu options but after clicking start will do the same thing. 

I have attached logfiles of steamtinkerlaunch.log after attempting to start both

[logfile-modorganizer2.txt](https://github.com/frostworx/steamtinkerlaunch/files/9021185/logfile-modorganizer2.txt)
[logfile-vortex.txt](https://github.com/frostworx/steamtinkerlaunch/files/9021186/logfile-vortex.txt)

**Comment by frostworx** [comment]
As you can see, your installed games were autodetected.
Now we need to find out what went wrong.
For a clean test, do the following:

1) remove or rename `~/.config/steamtinkerlaunch`
2) delete `/dev/shm/steamtinkerlaunch` recursively
3) `steamtinkerlaunch vortex start`
4) wait, many things happen under the hood, so be patient. The more modable games are installed, the longer it takes. Watch the status windows. You might also want to read the steamtinkerlaunch wiki for vortex meanwhile
5) either see vortex start or check/upload at least the just created `steamtinkerlaunch.log` in `/dev/shm/steamtinkerlaunch/` _(`installDotNet.log` might be interesting as well)_

repeat steps 1-5 with `mo2`

_(just added the same instructions to both the MO2 and Vortex wiki)_

**Comment by frostworx** [comment]
[pong](https://www.reddit.com/r/SteamTinkerLaunch/comments/vnu6os/mo2_and_vortex_wont_start/) 🙄

**Comment by frostworx** [comment]
tested both again and both started as expected using steamtinkerlaunch git master _(autopulling GE-Proton7-24)_

**Comment by jchallet** [comment]
Vortex is starting now, thank you

**Comment by bitterhalt** [comment]
I have followed guide but I just can't get MO2 to start. Vortex works fine.

edit: WOW! I got working now by installing innoextract and deleting /dev/shm/steamtinkerlaunch 
So anyone in Arch remember install innoextract before MO2!
