### ISSUE TITLE
[Problem] SteamTinkerLaunch installs too many ReShade DLLs

### ISSUE THREAD

**Issue by Arcitec** [sonic2kk/steamtinkerlaunch#514]
- Version of STL: https://github.com/frostworx/steamtinkerlaunch/commit/0706fb2b63931cafea47fb6dbd1de330fc96220a
- Game: L.A. Noire on Steam
- Runner: GE-Proton 7.24
- ReShade options (global): Version 5.2.2
- ReShade options (game config): Checkboxes for "Enable, Install, Update" are all enabled.
- Problem: SteamTinkerLaunch installs both d3d9.dll and dxgi.dll into the game folder. The game instantly quits as a result.

This is what the `ReShade_LANoire.log` says:

```
21:18:03:796 [01252] | INFO  | Initializing crosire's ReShade version '5.2.2.1534' (32-bit) loaded from "Z:\home\username\Games\Steam\steamapps\common\L.A.Noire\dxgi.dll" into "Z:\home\username\Games\Steam\steamapps\common\L.A.Noire\LANoire.exe" ...
21:18:03:796 [01252] | WARN  | Another ReShade instance was already loaded from "Z:\home\username\Games\Steam\steamapps\common\L.A.Noire\d3d9.dll"! Aborting initialization ...
21:18:03:796 [01252] | INFO  | Exiting ...
21:18:03:796 [01252] | INFO  | Uninstalling 0 hook(s) ...
21:18:04:797 [01252] | INFO  | Finished exiting.
```

So I started the game with STL again, and while the game was still processing its launcher, I quickly delete d3d9.dll from the game folder. This allows the game to launch properly with ReShade.

The problem is that the game is loading both dxgi.dll and d3d9.dll because it supports both graphics APIs, and as a result ReShade force-quits the game due to the conflict.

Is there any workaround to prevent STL from constantly putting d3d9.dll into the folder? I tried making a 0-byte `d3d9.dll` which is unwritable, but the game itself crashes if I put an empty dummy there...

Perhaps it's too hard to solve via autodetection in case a game uses multiple DirectX architectures, so perhaps it would be best to just add individual checkboxes like this?

- [ ] Don't override d3d9.dll
- [ ] Don't override dxgi.dll
- [ ] etc...

**Comment by frostworx** [comment]
there is a disabled function already which checks the logs automatically and removed d3d9.dll when it finds errors on the next run.
at the same time the variable NOD3D9 is set to 1 in the gameconfig, which prevents installing the dll on future runs.
so for testing you can
- remove the `function maybedrop` opening and closing [here](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L7563)
- or set NOD3D9=1 in your game config manually to prevent future loading

a PR for your checkboxes would be accepted as well if you want to add it

**Comment by Arcitec** [comment]
@frostworx Thanks a lot for the help! That function looks very useful. I am gonna resurrect it. Pull request created.

Here's what modern ReShade does:

```
final
Installers
Redistributables
reshade-shaders
binkw32.dll
check-steam_appid.txt
d3d9.dll                <-- ReShade
d3dcompiler_47.dll
dbghelp.dll
dinput8.dll
dxgi.dll                <-- ReShade
ErrorHandler.dll
fmod_event.dll
fmod_event_net.dll
fmodex.dll
installscript_sdk.vdf
installscript.vdf
LANLauncher.exe
LANoire.exe
LANPatcher.exe
lanvp.ini
metadata.dat
MTLX.dll
PlayLAN.exe
readmeDEU.txt
readmeENG.txt
readmeESP.txt
readmeFRA.txt
readmeITA.txt
readmeRUS.txt
ReShade.ini
ReShade_LANoire.log          <--- that's `ReShade_nameofcallingexefile.log`
ReShade.log
ReShadePreset.ini
ReShade.txt
steam_api.dll
-template
version.txt
```
