### ISSUE TITLE
No wait or main menu windows come up.  Just starts game instead.

### ISSUE THREAD

**Issue by stubkan** [sonic2kk/steamtinkerlaunch#516]
Wanted to try to fix fallout4 so decided to try steamtinkerlaunch -

Wipe and reinstalled fallout4, got latest version of steamtinkerlaunch and make installed it (v10)

Added it as a compatibility tool, so it runs.  Launching fallout4 in steam has a notification pop up (starting game using proton 7.03) and it starts the game.  No tinker main menu or wait requester... 

Can't figure out how to get it to show up.  If I try to run the settings via command line it just says this;

> steamtinkerlaunch settings 377160
/usr/bin/steamtinkerlaunch: line 5257: : command not found

[Fallout 4.log](https://github.com/frostworx/steamtinkerlaunch/files/9048574/Fallout.4.log)

It all seemed to install correctly - log of install is here
https://pastebin.com/15XiGCAD

**Comment by sonic2kk** [comment]
You may be missing `innoextract` or some other dependencies

**Comment by frostworx** [comment]
sounds like a broken `yad` installation.

does `yad-settings` or also just `yad` open a yad window?

does `which yad`
point to
`/usr/local/bin/yad`?

which `YAD` path is configured in `~/.config/steamtinkerlaunch/global.conf`? _(maybe `YAD="/usr/bin/yad"`?)_

**Comment by sonic2kk** [comment]
Looking at how yad was installed from the Pastebin log, it seems like it might point to `/usr/local/bin/yad`

```sh
make[2]: Entering directory '/home/stubkan/tem/yad-dialog-code/src'
 /usr/bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c yad yad-tools yad-icon-browser '/usr/local/bin'
 /usr/bin/mkdir -p '/usr/local/bin'
 /usr/bin/install -c yad-settings '/usr/local/bin'
```

**Comment by stubkan** [comment]
Yad creates the dialog windows right?  I can get windows to come up when I do steamtinkerlaunch launcher menu or other similar global top menus - I can enter my steam collection and click on fallout4 icon and then it launches the game, no wait or menu in between.

Also, I did get some innoextract error message - I fixed that by installing it from repository

**Comment by stubkan** [comment]
![image](https://user-images.githubusercontent.com/34361592/177400514-d147ac4e-40ee-456b-b862-d364bef3fbb2.png)

Also there is this

![image](https://user-images.githubusercontent.com/34361592/177400704-e0efafa1-b308-40c9-b43e-0da940add46f.png)

I'll put the path in and see if that helps

**Comment by stubkan** [comment]
Hot diggity dog the missing yad command was the problem

Got a nice big menu window pop up now, thank you very much for the prompt help
