### ISSUE TITLE
Installing Vortex fails with aborted dotnet installation

### ISSUE THREAD

**Issue by stubkan** [sonic2kk/steamtinkerlaunch#517]
Got a fresh install of steamtinkerlaunch v10 to run Vortex mods on Fallout4.  Running Ubuntu. Tried installing Vortex via the Game Menu or command line via vortex start, both fail.

The issue seems that dotnet failed to install.  The process runs through downloading Proton-GE 7.24 then installing dotnet then goes on to download Vortex then throws a Windows 7 or above is supported error.

Looking in the logs, it seems dotnet install aborts with error 67.  I've found a bunch of other reports and followed the suggestions they have had - which are;

delete the .config steamtinkerlaunch folder
delete the dev shm steamtinkerlaunch folder

It does not succeed in getting Vortex to install.  Perhaps there is a way to use a more accomodating proton version or perhaps a different 32bit version of dotnet that may be easier to install?

installDotNet.log
https://pastebin.com/nFjjygTs

Other posts with the same issue I found

https://www.reddit.com/r/SteamTinkerLaunch/comments/sii14g/vortex_and_mod_organizer_2_unsupported_windows/

https://github.com/frostworx/steamtinkerlaunch/issues/407

**Comment by sonic2kk** [comment]
~~Haven't tried Vortex but just out of curiosity, can you reproduce this with Proton 7.0-3?~~ I see now that STL downloads a custom Proton. Going to try Vortex myself and see if I can reproduce the problem

**Comment by stubkan** [comment]
The Vortex install process appears automated, I dont know how to make it use a different proton version...  Do you know how I can?

**Comment by sonic2kk** [comment]
My bad, I believe STL uses a different Proton version for Vortex. However you might be able to force a custom version? 

https://github.com/frostworx/steamtinkerlaunch/wiki/Vortex#installation

During the installation of Vortex (I'm installing with `steamtinkerlaunch vortex start`) I see that STL outputs

```
Tue Jul  5 22:38:13 BST 2022 INFO - setVortexVars - USEVORTEXPROTON is 'none', so using latest Proton-GE 'GE-Proton7-24' automatically
```

My initial thought is that maybe this is a problem with the latest GE

**Comment by stubkan** [comment]
It seems the only thing I can customize are the prefix paths.

**Comment by stubkan** [comment]
Perhaps the setVortexVars can be set to a previous version of Proton?

**Comment by sonic2kk** [comment]
I was able to install Vortex without any problems, however I'm running on Arch and using the latest git master of STL (57996955fa98a8c281eee04d02ada6be986d759e)

If I recall correctly from the previous issue (#516) you are using Ubuntu, right? I think you have to install manually on Ubuntu anyway. You could try the latest Git master and see if that works any better, though Vortex should work regardless.

A line of interest from your DotNet installation log:

```
warning: You are running winetricks-20210206-next, latest upstream is winetricks-20220411!
```

Are you able to update Winetricks? I'm not sure which version Ubuntu packages or how it all works there, but perhaps you could try using a newer release (the 20210206-next Winetricks dotnet verb might be out of date/incompatible with the newer GE release)

**Comment by stubkan** [comment]
Tried using a different Proton version but it threw an error about that version having no URL to grab

![image](https://user-images.githubusercontent.com/34361592/177422532-bb08783f-44f1-48be-aada-f3d4493865e2.png)

I ran update upgrade, so I think everythings up to date, will try updating winetricks

**Comment by sonic2kk** [comment]
I would be surprised if Ubuntu did not package a release newer than 20210206 as that is quite old (Sometime from 2021 :smile:). For the record I am using `20220411` which according to your log is the latest upstream.

**Comment by stubkan** [comment]
I tried to upgrade it

![image](https://user-images.githubusercontent.com/34361592/177422917-dfef8883-c0e0-4cf8-b1d5-e4e527a5dbb1.png)

I'll try to find a newer version, seems theres a rabbit hole of depreciated repositories

**Comment by sonic2kk** [comment]
According to an AskUbuntu answer from a few years ago (https://askubuntu.com/a/1196637), Ubuntu does package an out-of-date Winetricks release, but you can attempt an update with `winetricks --self-update` which I would guess does an update with the latest stable github release

**Comment by sonic2kk** [comment]
Ah just according to your STL line there, you are using the latest git of STL :smile: Not a big deal but I had assumed you were using v10.0 (unless you upgraded it recently). Either way, my bad, sorry :sweat_smile:

**Comment by stubkan** [comment]
I updated winetricks with that --self-update, that bought it current.

So I an the vortex install again and it got further this time, it seems to have installed and I saw a brief window adding games to a database, then it dropped me back at the command line.  Doesn't seem to actually start.  

Going to have a look at logs

**Comment by sonic2kk** [comment]
Hmm, I wonder if attempting to fully reinstall Vortex might work? Not sure if this is correct but it might just be a case of removing `~/.config/steamtinkerlaunch/vortex`, not sure if there are other files anywhere (`steamtinkerlaunch help` doesn't seem to have an `uninstall` option)

Also glad that updating Winetricks worked. Even though it's general information, it could probably be added as a step to the Ubuntu wiki section. Though I think that can wait until we figure out how to get Vortex up and running first, then have a separate section for perhaps Ubuntu-specific steps for setting up Vortex with STL

**Comment by stubkan** [comment]
I removed the .config/steamtinkerlaunch folder before the install
I'll try again and remove dev sfm steamtinkerlaunch this time

**Comment by sonic2kk** [comment]
Ah thanks! One step ahead :sweat_smile: 

Feel free to attach the relevant logs that you're looking at, probably some relevant stuff in the various logs at `~/.config/steamtinkerlaunch/logs`

**Comment by stubkan** [comment]
Wiping all the folders then running vortex start failed with the dotnet aborted install...

So I tried wiping everything, then running steamtinkerlaunch once, quitting it so it would auto generate the config folders - then running vortex start. 

It installs succesfully, does the same thing, goes through game library then fails to start up.

Including logs from dev shm

[installDotNet.log](https://github.com/frostworx/steamtinkerlaunch/files/9049993/installDotNet.log)

[installVortex_protonrun.log](https://github.com/frostworx/steamtinkerlaunch/files/9049992/installVortex_protonrun.log)

[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/9049996/steamtinkerlaunch.log)

They don't seem too helpful

**Comment by sonic2kk** [comment]
Thanks for the logs, indeed I couldn't see much in them that was of much use.

If you run `steamtinkerlaunch vortex start` from the command line, does STL return any errors?

**Comment by stubkan** [comment]
What is STL?

**Comment by sonic2kk** [comment]
SteamTinkerLaunch, apologies :-) I was wondering basically if when you run `steamtinkerlaunch vortex start` in the command line, do any errors come back

I'm also curious about what behaviour you see. I get a dialog that says SteamTinkerLaunch is scanning for Vortex games shortly before it opens the Vortex window. I believe you get that far (when you said "goes through the game library" but just for reference it looks something like this:

![image](https://user-images.githubusercontent.com/7917345/177428732-f03ed27a-9b83-478d-abcf-0e5a8b845a2b.png)

I don't get any output apart from

```
Tue Jul  5 23:39:26 BST 2022 INFO - startVortex - Starting Vortex without options
```

Which is (as far as I know) expected output. So I am wondering if you get anything relevant with running Vortex from the command line :smile:

**Comment by stubkan** [comment]
Yes, I get that too

![image](https://user-images.githubusercontent.com/34361592/177429183-e19277f3-0cbc-44d6-94c1-4d1909fd3f11.png)

Not the PrepareVortexGameStatus window though, haven't seen that.

The first time run it was making configs for each game, I think.  It was a different message to that one, and it doesn't do it subsequent runs.


It does also say

sed: -e expression #1, char 0: no previous regular expression

When I run it each time.

**Comment by sonic2kk** [comment]
There's some more output there it looks like which I don't know if that's entirely harmless. I think maybe this is failing because it's not showing the dialog window? Maybe some variables aren't being set properly to point to the Vortex games. Even though there's no extra logging after `Starting Vortex without options`.

Do you have this file? `~/.config/steamtinkerlaunch/vortex/stages.txt`? If so, do you have a `vortex` folder in the paths it mentions? For me it created a Vortex folder on my other drives.

I suspect there's some kind of weirdness here with how STL looks for Vortex-compatible games that Ubuntu doesn't like, but I couldn't say for sure what that is really yet

**Comment by sonic2kk** [comment]
So for some reason Vortex isn't getting to the `prepareAllInstalledVortexGames` part for you, at least that's what it seems like is going on for me. I'll have a look through the code and see if I can figure out what might be going wrong, but I'm not sure how long that might take

**Comment by stubkan** [comment]
Yeah theres a stages.txt which points to a staging folder on my Steam drive, at ~/DriveTwo/Vortex with a few folders in there for some games that were created.

Thats odd, there was another folder in the stealtinkerlaunch/vortex area which had a list of steam games with their ID, etc..  I can't see it anymore.

never mind, found it in the compatdata folder.

seenvortexgames.txt with 4 games
tracked files with a bunch
and version with Proton GE 7.24

**Comment by sonic2kk** [comment]
Ah, thanks!

So it's finding your games, but it's not showing the dialog box to look for them, and then presumably failing to start Vortex and exiting out. Very strange...

Just thinking out loud here but: Related to your other issue and the `sed` error, I'm wondering if there's some variable that's not set properly or something, and its causing Vortex to not work. Not really sure what it could be or anything though, but maybe Frostworx will know if we can't solve it in the meantime :-) I'll keep digging

**Comment by stubkan** [comment]
Oh no, my bad - it does pop up I think.  It comes on very quickly I must have missed it.  Doesn't stay for long but I think its that prepareAllInstalledVortexGames

**Comment by sonic2kk** [comment]
Ah! No worries, thank you for the clarification.

I wonder if maybe `prepareAllInstalledVortexGames` is crashing, and that's where the `sed` error is coming from. I'm not sure why that would cause Vortex to not open, though. I'll try and find out where that error could possibly be coming from in the code to hopefully narrow down the cause

**Comment by sonic2kk** [comment]
Out of curiosity, do you know if Vortex is finding the right amount of games? Are there any installed games missing from your list of found vortex games that you know of? Vortex supports a lot of games so it might be a lot to ask if you noticed this :sweat_smile: 

Basically I'm just wondering if there's anything to my theory that the `prepareAllInstalledVortexGames` process fails.

I can't really see anywhere in the Vortex specific sections of the code that `sed` would be erroring out. It must be one of the function calls I'm not following properly

**Comment by stubkan** [comment]
Might be. I do have more than 4 games installed.

List of active games 
![image](https://user-images.githubusercontent.com/34361592/177433185-6f4c619d-b541-4240-8b01-4af4871dd441.png)

I don't know if its relevant but there are 4 games in seenvortexgames.txt but only 3 folders in the staged folder area

The game without a folder is Starbound

**Comment by sonic2kk** [comment]
That certainly sounds to me like SteamTinkerLaunch is falling over before it can find all your installed games. I'll have to check but from your screenshot I'm fairly sure most of those have Vortex support, almost certainly more than 4.

Not entirely sure why STL would be crashing though

**Comment by stubkan** [comment]
What if the installed game was modified? - I modified stalker heavily with mods for example - would Vortex bug out if the game wasnt as it expected to be?

**Comment by sonic2kk** [comment]
That's an interesting point but I'm not sure, I guess it might depend on how heavily the game was modified.

I modded Oblivion and New Vegas, and Vortex was able to open fine for me. But I modded those with MO2, so maybe however that mod manager works is different and doesn't cause a conflict.

I guess it might depend on how stalker was modified and how STL looks for Vortex games. Interesting point though!

**Comment by frostworx** [comment]
hi.
thanks for supporting again @sonic2kk and thanks for a good bugreport @stubkan 

Although you already solved the initial problem let me tell you, that the Vortex wiki also has troubleshooting instructions, which are always a good first step if something goes wrong:
https://github.com/frostworx/steamtinkerlaunch/wiki/Vortex#troubleshooting=


To the current problem (sorry, haven't read your complete discussion _(time...)_, so correct me if I missed something)

 @ https://github.com/frostworx/steamtinkerlaunch/issues/517#issuecomment-1175575801
  the sbrk line looks suspisious and might be the cause of the problem
the log line `Tue  5 Jul 23:17:42 BST 2022 ERROR - prepareVortexGame - variable VGAMEDIR '' is no valid directory - can't continue` doesn't look good - maybe a gamespecific glitch (raw checking Vortex configs, which are written very differently, so not unlikely that some data for some games can not be found)

When following the troubleshooting can you reproduce the problem?

**Comment by stubkan** [comment]
I'll have a look at that page.

Also, I read that Vortex doesn't like stuff on a separate drive - my steam games are on a SSD mounted into a folder on my home directory - the system seems to operate as if it was the same drive though mounted folders instead of drive letters and it has found a few games - but could that be a problem?

Thanks to that wiki I found a page in usr/share/steamtinkerlaunch/misc that lists a bunch of games.  I'm assuming this is the full compatible list

There are a few games I have in that list on there that aren't showing up in Vortex tracked list -
stalker, valheim and subnautica.  I'll try uninstalling them and re-running Vortex.  Would removing games from that text  file list - or games that are supported but not on that list cause problems?

**Comment by stubkan** [comment]
Wiped all the folders to start over after removing a bunch of games from steam.

Forgot to start steamtinkerlaunch to generate config files so installing vortex comes up with dotnet fail

Delete again, start STL via launching Fallout4 in steam, quit, run vortex start,

It seems to install, according to this

![image](https://user-images.githubusercontent.com/34361592/177598099-7a8671db-6df3-40fa-82c5-d3fe4f3ed5ae.png)

But the log says it failed to start because no .exe found so I look in the vortex prefix and it looks like it didn't install in Program Files.  It didn't find any games or run the search for game process this time for some reason.

EDIT

wiped everything did it again like a crazy person expecting a different result.

![image](https://user-images.githubusercontent.com/34361592/177599546-a01ebf68-8b74-4887-9bc8-306cdde42cf7.png)


The sbrk error comes up at the point its running the Vortex Install after downloading Vortex.  This time the dotnet window pops up and it runs the game search.  As usual, Vortex does not start.  Checked the prefix, Vortex installed successfully.

[installDotNet.log](https://github.com/frostworx/steamtinkerlaunch/files/9056569/installDotNet.log)

[installVortex_protonrun.log](https://github.com/frostworx/steamtinkerlaunch/files/9056570/installVortex_protonrun.log)

[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/9056577/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
dotnet is not installed,  I thought you already solved this earlier.
steamtinkerlaunch installs dotnet completely "externally" using winetricks and wine of the configured proton version and actually even logs the exact command, which can be also launched separately without steamtinkerlaunch.
_(means in turn that this likely is no steamtinkerlaunch issue. choosing a different proton version would be a good next step)_

` WINEDEBUG="-all" WINEPREFIX="/home/stubkan/.config/steamtinkerlaunch/vortex/compatdata/pfx" WINE="/home/stubkan/.local/share/Steam/compatibilitytools.d/GE-Proton7-24/files/bin/wine" "winetricks" --unattended "dotnet48"`

**Comment by stubkan** [comment]
Id like to try using a different version of proton and/or a 32bit dotnet install - just dont have any idea how to go about that, as this system seems automated.  I tried changing the proton version to GE Proton 7.13  in the config as you reported it was the first working GE version but it threw an URL not found error

**Comment by stubkan** [comment]
I ran that command

![image](https://user-images.githubusercontent.com/34361592/177603529-a7f1c1b0-8191-4e2f-b68c-d6a256a1da68.png)

Seems the sbrk error comes from dotnet install

**Comment by frostworx** [comment]
which "system is automated"? steamtinkerlaunch?
I suggested to run the installer manually/standalone without steamtinkerlaunch.
the proton ge project page offers multiple release versions, just choose, download and use one.

**Comment by frostworx** [comment]
just retested again _(I guess my 100th vortex install)_ and it installs completely fine via 
`steamtinkerlaunch vortex start`
_(latest git master, winetricks 20220411, GE-Proton7-24)_
my winetricks is slightly different to yours though:

mine:
`Using winetricks 20220411 - sha256sum: 69856050cfe9d97902dfd68c1ad42a10a4be0fe76660744126d7e3ed75610495 with wine-7.0 (Staging) and WINEARCH=win64`

yours:
`Using winetricks 20220411-next - sha256sum: 106f9ed668d592cb44aa48e8bcb86f4123c1e55e638b6d2216c5b746fd840071 with wine-7.0 (Staging) and WINEARCH=win64`

so this *could* be the problem.

the follow up problem on your system is _(snippet from installDorNet.log)_

```
...
Executing load_winxp 
Executing /home/stubkan/.local/share/Steam/compatibilitytools.d/GE-Proton7-24/files/bin/wine winecfg -v winxp64
------------------------------------------------------
warning: Note: command /home/stubkan/.local/share/Steam/compatibilitytools.d/GE-Proton7-24/files/bin/wine winecfg -v winxp64 returned status 127. Aborting.
```

where mine logs:

```
...
Executing load_winxp 
Executing /home/frostwork/.config/steamtinkerlaunch/proton/custom/GE-Proton7-24/files/bin/wine winecfg -v winxp64
------------------------------------------------------
warning: Running /home/frostwork/.config/steamtinkerlaunch/proton/custom/GE-Proton7-24/files/bin/wineserver -w. This will hang until all wine processes in prefix=/home/frostwork/.config/steamtinkerlaunch/vortex/compatdata/pfx terminate

```

and continues the installation successfully afterwards.
so clearly no steamtinkerlaunch issue again and I'm afraid I can't help any further

**Comment by stubkan** [comment]
Okay, was hoping to get it to work with STL as its automating all the difficult stuff - but I guess I'll try to figure out how to use prefixes and install it and make it work separately which is what I was hoping to avoid.

I'd like to request as a feature the ability to use different proton versions, as a safeguard against proton updating, breaking or not running properly on a system like mine - there seems to be partial functionality for this already, under the USEVORTEXPROTON setting in the config files.

**Comment by stubkan** [comment]
Thank you for your help in this thread guys, I hope I find out what is making the sbrk() errors eventually...

**Comment by frostworx** [comment]
wtf

**Comment by stubkan** [comment]
Finally found out what was messing the bed.

There was a line in .profile that said

export GLIBC_TUNABLES=glibc.rtld.dynamic_sort=2

Removing the line fixed the issue. I think it was a line that went in to fix Unreal Engine issues.
