### ISSUE TITLE
xdg-open is possibly handled badly

### ISSUE THREAD

**Issue by HanPrower** [sonic2kk/steamtinkerlaunch#519]
STL doesn't use `xdg-open` properly.

In Flatpak nothing is set by default such as Editors or Browsers due to sandboxing (over-simplification).

However, Flatpak, using portals, can spawn a Window asking the user what to use (I assume it stating the default app is the portal saying so when the window is spawned, but before this it isn't accessible):
![image](https://user-images.githubusercontent.com/1781312/177578117-9c006673-83ee-473f-bcef-39ef8b9e956a.png)

Outside of a Flatpak `xdg-open` generally seems to attempt best-guessing (or the DE does anyway) for opening files it doesn't understand from the mime list:
```
xdg-open dsakd.garbagelol 
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
```
But then Kate opened anyway, as my default text editor.

It seems odd that STL fails to open files via `xdg-open` when it can't figure out an editor instead of just attempting best guesses, especially seeing as `xdg-open` has numerous exit codes to handle certain scenarios:
```
Exit Codes

An exit code of 0 indicates success while a non-zero exit code indicates failure. The following failure codes can be returned:

1

Error in command line syntax.

2

One of the files passed on the command line did not exist.

3

A required tool could not be found.

4

The action failed. 
```

It appears the issue is happening in `updateEditor`?

Maybe instead of failing if an editor can't be set, fallback to just letting `xdg-open` do a best guess?

This would fix `xdg-open` not working in Flatpak as far as opening files goes, and maybe help handle some general edge cases.

**Comment by frostworx** [comment]
thanks for looking into this and reporting!

above commit should do what you need.

If not:
- can you provide a corresponding logfile?
- is xdg-mime available and functional? _(i.e. `xdg-mime query default text/plain`)_

**Comment by frostworx** [comment]
Just remembered, why I decided to use the current implementation using xdg-mime:
when using xdg-open directly for opening the mime-configured text editor, the started game does not exit _(still is seen as running from steam)_. So the workaround was to use xdg-mime, to find out the mime-configured text editor and use it directly instead.

edit: please wait a sec with testing - just rewriting to reflect this in an updated commit.

**Comment by frostworx** [comment]
^ better possible solution

**Comment by HanPrower** [comment]
`xdg-mime` doesn't work in a Flatpak, no, but you look like you're avoiding that now anyway :P

When I try to Edit files via the Editor dialog it lists them all fine, but when I click Edit it always tries to open the "default" file instead of the one I selected:
`Wed  6 Jul 17:01:48 BST 2022 INFO - EditorDialog - Opening Editor '/home/hanfox/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/VRising/none' with selected Config Files`

instead of:
`/home/hanfox/.var/app/com.valvesoftware.Steam/.config/steamtinkerlaunch/gamecfgs/id/489830.conf`

**Comment by frostworx** [comment]
oh, now as you say it, THIS _(as well?)_ might be actually be the reason why I chose `xdg-mime` as workaround.
Sorry, won't work on a new solution as of lack of time and because of [this](https://github.com/frostworx/steamtinkerlaunch/issues/508), so if this is a problem, I suggest I'll disable xdg-open generally when `INFLATPAK=1` to avoid problems at least.

**Comment by HanPrower** [comment]
That's fine.

In regards to things getting "stuck open" can opening files not be forked with ` &` at the end of the command? Or does that not work in this context?

Besides that, after some poking I've figured that `home/hanfox/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/VRising/none` was actually a "mis-configuration" by me. For some reason, at some point, any program in GLOBALS that I hadn't manually set had been set to that.

I made a fresh `.config` and notice that any `GLOBALS` left as `none` (or `$NON`) get set as that instead of left blank, so that probably wants a check when writing .cfgs that `if == $NON skip`? I can take a crack at doing a PR for that, unless it's easy for you to slip in?

As for it not opening using `xdg-open` for some reason once we get to actually trying to open the files for some reason `$STLEDITOR` is blank, even though in `updateEditor` it's populating as it should.

I'm just stating all this as my findings, not expecting you to fix it. It's a very Flatpak issue, I'll do a PR if I find out where it's falling down :thinking:

**Comment by HanPrower** [comment]
So it appears that as part of `EditorDialog` `loadCfg "$STLGAMECFG" X` is run which blanks out `$STLEDITOR` again.

I looked at setting `STLEDITOR` via `updateConfigEntry` as part of `updateEditor`, but as it's a `GLOBAL` it appears to be thrown away then?

I'm a little stuck as to how to rectify the issue w/o throwing messy workarounds in.

For now, if I manually edit, `global.conf` to set `STLEDITOR=xdg-open` it works for me, so at least that's something :sweat_smile:

**Comment by frostworx** [comment]
need some minutes to look into this and my holidays start tomorrow evening - so no promises that I find them before.
