### ISSUE TITLE
add gamescope

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#52]
https://github.com/Plagman/gamescope

**Comment by frostworx** [comment]
doesn't compile ootb currently and I have no need for it

**Comment by Faalagorn** [comment]
gamescope was useful for me launching some games that force fullscreen exclusivity and sometimes fixed a game or two, but it also have a plethora of other nice functions and is actively developed by Valve nowadays so it's worth keeping eye on ;)

**Comment by frostworx** [comment]
Good to know, thx :)

**Comment by Faalagorn** [comment]
btw, here's for anyone wondering what gamescope might be useful: https://www.gamingonlinux.com/2020/09/valve-developer-shows-off-gamescope-for-linux-at-xdc-2020

It should also work as an downsmapler though for some reason I can't get it to work on my side, maybe I'm doing something wrong a things such as `gamescope -f -w 3840 -h 2160 -- glxgears` results in pixelated mess for me instead :/
![screenshot_2020-09-20-163935](https://user-images.githubusercontent.com/4951331/93714021-01920380-fb60-11ea-8e8b-2456ef47ff14.png)

EDIT: Here's the source/more info: https://github.com/Plagman/gamescope/issues/104#issuecomment-691774145

**Comment by frostworx** [comment]
n1! I already have gamescope built in current offline state btw. Not sure which default arguments to choose yet.
![stl-wip](https://user-images.githubusercontent.com/8840590/93715462-a533e180-fb69-11ea-94d6-e29ddc54b93b.jpg)

**Comment by Faalagorn** [comment]
> n1! I already have gamescope built in current offline state btw. Not sure which default arguments to choose yet.
> ![stl-wip](https://user-images.githubusercontent.com/8840590/93715462-a533e180-fb69-11ea-94d6-e29ddc54b93b.jpg)

Default, i.e. none should be fine. Last time I checked there was no good documentation so you had to browse through code for the arguments, though I think not much has changed since. Generally the GOL linux explains some useful options already, but the upscaler is the one I find most useful for some gamers as it's basically what gedosato on Windows did, though like I previously mentioned and GOL article stated, things grabbing focus and stuff are really useful – I'm on Wayland (sway) right now so I get different use case that X11 does too :)

**Comment by frostworx** [comment]
tbh I didn't spend much time on playing with gamescope yet, but thought default "--" would probably be the best choice for default, so I'll leave it "as is". Maybe some drop-down menu presets would make sense later. Thanks for the feedback!

**Comment by frostworx** [comment]
added in https://github.com/frostworx/steamtinkerlaunch/commit/0f5af07f4995df77a3984f269ca2b0acc8ab5f5e

**Comment by frostworx** [comment]
Hey, @Faalagorn!
Any chance you have a solution for the tabs in the Settings Menu work as they should under wayland?
The all open in separate windows in both sway and wayfire and therefore do not work correctly _(in fact the menu is not usable like that)_

**Comment by Faalagorn** [comment]
Hm, I indeed had configuration open 5 windows at once, even worse in sway as it's stacking them – I generally prefer to edit files manually and I don't know YAD, but I guess it must be something stupid. Is it exclusive to Wayland? How does it work under i3wm?

EDIT: It seems that there should be tabs that are not appearing. The GUI is also running on Wayland natively, I haven't tried, but is there an option to force running it through xwayland for troubleshooting?

**Comment by frostworx** [comment]
Thanks for the reply!
Indeed it is wayland exclusive. I haven't tried it in i3wm, but in xfce it is ok.
wayland is partly right here. Yad takes "real windows" for the tabs and merges them into one. Probably wayland can't handle this yet :(
No big deal - I can wait. Was just curious if there could be a workaround.
