### ISSUE TITLE
Ubuntu autoreconf not working

### ISSUE THREAD

**Issue by nex86** [sonic2kk/steamtinkerlaunch#520]
I'm trying to install this on Ubuntu 22.04
I'm following this guide: https://github.com/frostworx/steamtinkerlaunch/wiki/Ubuntu
but at step 2.3 I'm getting the following error:
`tom@probook-ubuntu:~/yad-dialog-code$ autoreconf -ivf && intltoolize
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
configure.ac:132: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
configure.ac:132: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
`

what am I'm missing here?

**Comment by nex86** [comment]
figured out I was missing GLib 2.0 but now I have other GTK related issues

**Comment by frostworx** [comment]
not a steamtinkerlaunch issue apparently. Someone might be able to help if you'd post the corresponding configure.log. I'd suggest to ask upstream though or read some generic howtos for compiling/autoconfig
