### ISSUE TITLE
Editor finds unwanted files (reshade temp files)

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#525]
as of https://github.com/frostworx/steamtinkerlaunch/commit/37a4280017a1451306b9a2ffaa904408a77de3c1 reshade temp files are picked up causing really long load times for the editor window (takes a few minutes to open)

EDIT: image
![image](https://user-images.githubusercontent.com/25832539/180858481-3738cd26-1f41-4c51-b19d-7b7370244d2b.png)

EDIT2: didn't really think it was nessicary but ill add it anyway 
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/9184246/steamtinkerlaunch.log)

only thing it really shows of intrest is this `on Jul 25 03:23:29 PM EDT 2022 INFO - EditorDialog - Found 10989 available Config Files - opening Checklist` showing that its loading a lot of files

**Comment by frostworx** [comment]
reverted
