### ISSUE TITLE
Fork custom command no longer works with any game.

### ISSUE THREAD

**Issue by Crashnoww** [sonic2kk/steamtinkerlaunch#527]
The custom command launches, but the actual game won't. It worked fine before on the same games.

I've tested multiple games, all with the same issue.

I've tried inject custom command and in this case, only the game launches, while the second exe won't.

I'll attach the game log. If you need anything else, let me know.
[782330.log](https://github.com/frostworx/steamtinkerlaunch/files/9208146/782330.log)

System: Steam Deck
STL version: 10.0.20220728

**Comment by frostworx** [comment]
thanks for reporting, I guess this is the issue:
https://github.com/frostworx/steamtinkerlaunch/issues/523#issuecomment-1196954575
TL;DR: could you please check if setting the new option `FORKWAIT` to `2` fixes your issue?

**Comment by Crashnoww** [comment]
It works!

Thank you very much for your excellent work!

**Comment by frostworx** [comment]
Thanks for testing! :)
Would you please test [this commit](https://github.com/frostworx/steamtinkerlaunch/commit/7a5c8c92fc504dd75554bd4adde51de92f1902e3) as well with `FORKWAIT` set back  to `0`?
_(It simply sets the waittime to `2` automatically when `FORKWAIT` is `0`)_
~~Probably a good idea to set the `FORKWAIT` default to `2` directly :)~~ - **done** :)

**Comment by frostworx** [comment]
~~fyi: depending on the reaction on [this](https://github.com/frostworx/steamtinkerlaunch/issues/523#issuecomment-1199371485) the `FORKWAIT` stuff might be removed again.~~
no matter how #523 proceeds, I'll leave `FORKWAIT` as-is
so, please report back if https://github.com/frostworx/steamtinkerlaunch/issues/527#issuecomment-1198298087
works for you
