### ISSUE TITLE
[Bug] Mangohud is always enabled regardless of setting

### ISSUE THREAD

**Issue by Nano-Ocelot** [sonic2kk/steamtinkerlaunch#531]
Even when Mangohud is disabled, the game launches with it enabled. I have narrowed it down to steamtinkerlaunch because launching the game through any other means will not have Mangohud active.

**Comment by frostworx** [comment]
[logs please](https://github.com/frostworx/steamtinkerlaunch/issues/93), likely a configuration issue anyway

**Comment by Nano-Ocelot** [comment]
Hopefully these are what you need. Let me know if you need any others. Thank you.

[sandstorm.log](https://github.com/frostworx/steamtinkerlaunch/files/9244098/sandstorm.log)
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/9244106/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
Hm, both logs don't have a single mangohud hit.
Any chance `MANGOHUD` is set somewhere? It is a mangohud internal variable, steamtinkerlaunch doesn't set it in the configs, but did some time ago - so maybe you're using an old config `~/.config/steamtinkerlaunch/gamecfgs/title/sandstorm.conf`

**Comment by Nano-Ocelot** [comment]
Oh, yeah it has this line. `## Enable MangoHud for this game
MANGOHUD="1"`

I'll delete and remake my configs and report back if that solves it.

**Comment by frostworx** [comment]
hm, that as one line shouldn't matter, but only a standalone `MANGOHUD="1"`
Either way, it could be possible that you have it in some other used config - for example
in `~/.config/steamtinkerlaunch/default_template.conf`

For a quick test you could simply rename your whole `~/frostwork/.config/steamtinkerlaunch/`
and let it re-create on the next try.

**Comment by Nano-Ocelot** [comment]
`~/.config/steamtinkerlaunch/default_template.conf` was also an old config. Remaking it and all the game configs solved the problem! Thank you so much.

**Comment by frostworx** [comment]
Glad you got it solved.
iirc I added a transition function, so this could not happen in theory. If so, I  guess I removed it too quickly again, and you missed that migration function :)
