### ISSUE TITLE
Right way to set mangohud arguments

### ISSUE THREAD

**Issue by tuxtergames** [sonic2kk/steamtinkerlaunch#532]
Hy Guys, I'm try to set mangohud variables inside STL, but its crashing my games, I can set directly to game cofigs inside ".config" folder this way work nice, but I want to set this inside launcher, is it possible?
How to correct way to set this like in steam launch?
Wiki pages are a little confusing, maybe post screen shots help others to understand better, this is my preset on steam.

MANGOHUD=1 MANGOHUD_CONFIG=full,position=top-right,toggle_hud=Shift_R+F11,fps_limit=90+60+0 %command%

I've tried left on mangohud arguments lite these:

MANGOHUD_CONFIG=full,position=top-right,toggle_hud=Shift_R+F11,fps_limit=90+60+0 %command%

full,position=top-right,toggle_hud=Shift_R+F11,fps_limit=90+60+0 %command%

full,position=top-right,toggle_hud=Shift_R+F11,fps_limit=90+60+0

and nothing works, tks for help again, you're doing a great job to linux community.

![image](https://user-images.githubusercontent.com/26095484/182367018-7f281723-0263-478b-bdf0-bc35161a9144.png)

**Comment by frostworx** [comment]
When using steamtinkerlaunch you're supposed to set its options (variables) and not in the steam launch options.
What should work is to add your "`full,position=top-right,toggle_hud=Shift_R+F11,fps_limit=90+60+0`" options in the
"ManguHud arguments" field in the Game Menu.
So you were already pretty close (in your screenshot), but you need to remove the leading "`MANGOHUD_CONFIG=`" and the trailing "`%command&`"

If it still refuses to work, please attach the corresponding log like described [here](https://github.com/frostworx/steamtinkerlaunch/issues/93)

There are some people often helping here with MangoHud issues, so they might have some better ideas when waiting a bit :)

**Comment by tuxtergames** [comment]
> When using steamtinkerlaunch you're supposed to set its options (variables) and not in the steam launch options. What should work is to add your "`full,position=top-right,toggle_hud=Shift_R+F11,fps_limit=90+60+0`" options in the "ManguHud arguments" field in the Game Menu. So you were already pretty close (in your screenshot), but you need to remove the leading "`MANGOHUD_CONFIG=`" and the trailing "`%command&`"
> 
> If it still refuses to work, please attach the corresponding log like described [here](https://github.com/frostworx/steamtinkerlaunch/issues/93)
> 
> There are some people often helping here with MangoHud issues, so they might have some better ideas when waiting a bit :)

Hy, I'm trying to understand what happen here but don't find a right way, I did what you told me, "full,position=top-right,toggle_hud=Shift_R+F11,fps_limit=90+60+0" but doesn't work, looking at the log I see this 

ter 02 ago 2022 12:23:46 -03 SKIP - setSLRReap - No SLR was provided via command line, so configuration USESLR '1' is ignored '' 0
ter 02 ago 2022 12:23:46 -03 INFO - setMaHuCmd - mangohud is enabled
ter 02 ago 2022 12:23:46 -03 INFO - setMaHuCmd - Using mangohud arguments ''
ter 02 ago 2022 12:23:46 -03 INFO - setMaHuCmd - CMDPART - mangohud command '/usr/bin/mangohud full,position=top-right,toggle_hud=Shift_R+F11,fps_limit=90+60+0'

the commands should be in arguments, or am I wrong?

If I set directly in the mangohud config its working, but on a launcher don't.
I send the log attached here, tks for your help.
[1259970.log](https://github.com/frostworx/steamtinkerlaunch/files/9243660/1259970.log)

**Comment by frostworx** [comment]
might be a bug _(I do not use mangohud, so likely that I didn't test it myself - no idea if others did, but I would have expected it tbh)_
Will give it a try _soonish_ and report back _(or fix it directly before)_

**Comment by tuxtergames** [comment]
> might be a bug _(I do not use mangohud, so likely that I didn't test it myself - no idea if others did, but I would have expected it tbh)_ Will give it a try _soonish_ and report back _(or fix it directly before)_

Thank you for hep!!!!!

**Comment by frostworx** [comment]
Oh, heh! Now I understand why you used `MANGOHUD_CONFIG` - it is a `mangohud` internal variable!
Didn't know that :facepalm: 
I think this makes it even a lot easier to maintain if it is working as expected.

Would you mind testing the following? :
replace
`mapfile -d " " -t -O "${#MAHUCMD[@]}" MAHUCMD < <(printf '%s' "$MAHUARGS")`
with
`export MANGOHUD_CONFIG="$MAHUARGS"`
and see if it already just works?

_(the line only appears once in the code - currently it is [here](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L16528))_

**Comment by frostworx** [comment]
hm, no need to test - just did and it doesn't work. damn - it should :)

**Comment by tuxtergames** [comment]
> hm, no need to test - just did and it doesn't work. damn - it should :)
sorry, just see now

**Comment by frostworx** [comment]
Heh, tested with another game - [it](https://github.com/frostworx/steamtinkerlaunch/issues/532#issuecomment-1202974880) does work!
The game I used yesterday apparently has mangohud compatibility problems (likely opengl).

**Comment by frostworx** [comment]
please test above commit  - seems to work fine in a quick test here.

**Comment by frostworx** [comment]
ping

**Comment by tuxtergames** [comment]
> ping

tks man! sorry my delay, lot of work here, with last commit works nice, tks a lot for support us!!!!

**Comment by frostworx** [comment]
thanks for confirming! *closing here*
