### ISSUE TITLE
steamtinkerlaunch ignores mangohud configs

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#534]
possible related to the commit to fix https://github.com/frostworx/steamtinkerlaunch/issues/532

mangohud config files are now ignored when using steamtinkerlaunch
[1198090.log](https://github.com/frostworx/steamtinkerlaunch/files/9256230/1198090.log)

when you pass `MANGOHUD_CONFIG` to mangohud which i'm guessing its still doing if we don't add a argument causes mangohud to ignore all config files, the idea being that if a user is using this they want to override the default configs like this instead of a conf file. (which brings up a suggestion to flightless mango I might make to allow overriding the conf file instead of internal default options)

Anyway fix would probably be (if I am correct) to simply check if the user didn't specify any arguments for `MANGOHUD_CONFIG` and if so do not export `MANGOHUD_CONFIG`

EDIT: hmm seem it already does this https://github.com/frostworx/steamtinkerlaunch/blob/fa82187a4f86f788e72900cf15efbbabef34af37/steamtinkerlaunch#L16928
but for some reason `MAHUARGS` is not getting set to none initialy (this log was from a fresh install where it was set to ` ` not `none` (maybe because when I opend the config to enable mangohud as you can see it the log it also updated `MAHUARGS`?)

Yup apperently thats exactly what happend  I didn't touch the  MAHUARGS in the gui all I did was change the proton version to GE and tick use mangohud

so it seems when the gui is called its called with `MAHUARGS` already populated with ` `

maybe we should have a function or something with checks for ` ` in the config and replaces it with none? though maybe that could break something

**Comment by frostworx** [comment]
Good catch, thanks for reporting. I suspect a recent `$NON` related PR causing this issue.
need to investigate soonish.

**Comment by frostworx** [comment]
I couldn't reproduce `MAHUARGS` being set to " " _( aka ` ` )_
so please retest, ideally with reproducable steps and also append a log as usual!

Looking at the corresponding part of the upstream [MangoHud doc](https://github.com/flightlessmango/MangoHud#mangohud_config-and-mangohud_configfile-environment-variables) `MANGOHUD_CONFIG` overriding `MANGOHUD_CONFIGFILE` might be intended behavior _("This takes priority over any config file")_

There is already a logic checking for "none" btw _(which recently changed through a PR like mentioned above)_.

**Comment by frostworx** [comment]
I can reproduce the issue with a fresh config - it is the PR...
digging it out and reverting...

**Comment by frostworx** [comment]
hm, just reverted it, but recognized that the game I used for testing doesn't like MangoHud by default. So maybe a non-issue.
needs more tests again... :(

**Comment by frostworx** [comment]
not reproducible. reverted the removal of #522 and added some more log lines.
Appending logs makes really sense, as it can save time.

**Comment by zany130** [comment]
as you can see in my first message I did include logs as it has a line saying
> [1198090.log](https://github.com/frostworx/steamtinkerlaunch/files/9256230/1198090.log)

```
 trails of Cold Steel IV (1198090)' with Proton: 'GE-Proton7-28'
Wed Aug  3 10:27:56 PM EDT 2022 INFO - launchSteamGame - Using mangohud arguments ''
```
manaully editing the confing file for this game and setting `MAHUARGS=none` fixes the issue. opening the game menu gui again resets it to ` ` and breaks configs again


EDIT: 
so to reproduce

1. create a test mangohud config file in `~/.config/MangoHud/MangoHud.conf` where you set something easily reconizable maybe change the color or position.
2. set `MAHUARGS=none` and `USEMANGOHUD="1"` manually in the game config file.
3. run the game without opening the steamtinkerlaunch gui
4. see mango hud loading your config file and everything works as expected
5. close the game and relaunch it this time accepting the wait requester to open the steamtinkerlaunch gui
6. go into game menu
7. scroll down to the mangohud arguments section,
8. notice its set to blank
9. click save and play
10. notice mangohud ignores your config and loads default values

**Comment by frostworx** [comment]
heh, sorry I indeed missed your log.
I'm tired of steamtinkerlaunch-
As written above I couldn't reproduce this, but might retry when I find more motivation

edit: of course removing the re-added PR and test if it works without it is an option as well. see also the conversation in the PR for more context

**Comment by HanPrower** [comment]
If it is indeed an issue with the PR blanking out the option when it shouldn't then modifying https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L8913 to the following should fix it:

`						{ [ "$CFGCAT" != "DXVK_LOG_LEVEL" ] && [ "$CFGCAT" != "DXVK_LOG_PATH" ] && [ "$CFGCAT" != "STL_PV_SHELL" ] && [ "$CFGCAT" != "MAHUARGS" ;};}`

**EDIT** Fixed a missing `$`

**Comment by zany130** [comment]
> If it is indeed an issue with the PR blanking out the option when it shouldn't then modifying https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L8913 to the following should fix it:
> 
> ` { [ "$CFGCAT" != "DXVK_LOG_LEVEL" ] && [ "$CFGCAT" != "DXVK_LOG_PATH" ] && [ "$CFGCAT" != "STL_PV_SHELL" ] && [ "$CFGCAT" != "MAHUARGS" ;};}`
> 
> **EDIT** Fixed a missing `$`

yup that fixes it

**Comment by frostworx** [comment]
then this is valid again:
https://github.com/frostworx/steamtinkerlaunch/pull/522#issuecomment-1177699522
because
https://github.com/frostworx/steamtinkerlaunch/commit/11c5f02974e5334fae0d2ce2c7d57928f071a581#diff-77c6d4bb1bf7c1988ff5a068c856b6c24e113663f2e61cb3a2c98723c0fafc04L8912
