### ISSUE TITLE
Running First Time Setup in different prefix

### ISSUE THREAD

**Issue by Jademalo** [sonic2kk/steamtinkerlaunch#536]
I can't tell if this is possible, I assume it is based on the first time setup wiki page but I can't figure out how to do it.

I'm trying to install all of my EA games into the same Origin prefix, to make accessing origin itself a bit easier, to prevent Origin being installed 10+ times, and to try and prevent the myriad of issues Origin has generally. In the launch arguments for my game I have the prefix changed with `STEAM_COMPAT_DATA_PATH`, however steam executes the first time setup `installScript.vdf` *before* the compat data path global variable is set. 
This means that instead of the prereqs and registry settings being installed into the Origin prefix, they are instead installed into the game's prefix. 

I thought I could use stl to re-run the install script in the correct prefix, but I can't seem to get it to work. Using `Steam first run setup` opens the menu to create a custom evaluator script, however clicking `install without saving` doesn't seem to write the required registry entries.

Is there any way to do this, or is it not possible with stl?
The only other workaround I can think of is to symlink the compatdata folder for the initial install, but that feels messy.

Thanks!

**Comment by Jademalo** [comment]
After further experimentation, it seems like there's a bit of weird functionality here.

If I run the first time setup, it copies the contents of the prefix to a `xxxx_steamtinkerlaunch` directory, and creates it from scratch. This seems to happen to the folder set with `STEAM_COMPAT_DATA_PATH` rather than the one based on the game's steam ID, interestingly.

I thought I could skirt round this by setting `STEAM_COMPAT_DATA_PATH` to the `xxxx_steamtinkerlaunch` folder, however this just acted like I had it set to the base `xxxx` folder.

I guess the most concise way of describing what I want to do is to re-run the first time setup in the current prefix folder, without remaking it and without moving everything around.

**Comment by frostworx** [comment]
The [Steam First Time Setup](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-First-Time-Setup) functions are more or less abandoned, as I was the only one using them back while implementing.
In theory they should still work, but all that evaluatorscript stuff from steam is a moving target and can always change/break.

Sorry, can't help any further. Leaving this open here in case someone who uses that function gets the opportunity to help.

**Comment by Jademalo** [comment]
Ah damn, that's a shame! No worries.

**Comment by frostworx** [comment]
[Compatdata Redirect](https://github.com/frostworx/steamtinkerlaunch/wiki/Compatdata-Redirect) might be an other option for your problem btw

**Comment by Jademalo** [comment]
Oooh, that's interesting, I'll give it a shot. Definitely looks easier than manually symlinking, ty!
