### ISSUE TITLE
⚠ "We have just lost cabin pressure" 

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#537]
I have considered long, but decided to mostly stop working on `steamtinkerlaunch` soon for various reasons.

Thank you very much to all people who contributed in either way - you are great!
Without you, `steamtinkerlaunch` wouldn't be the jack-of-all-trades tool it is now.
Hopefully, you will stay on board and keep up helping with making the project even getting better.
I'm confident it is possible, that many more new people will rise and join and make this a vivid community project.

`steamtinkerlaunch` is my baby - I spent much time, energy and gray hairs into it and therefore
won't abandon the project completely, but instead will still occasionally add some more features or fix some bugs,
but simply not like a maniac - it needs to be a fun hobby project and no longer a second unpaid job.

Help each other and have fun!

**Comment by MaggiWuerze** [comment]
Thanks for all your hard work, really appreciate all the time you put into this.

**Comment by r-vd-woude** [comment]
Thanks for the great work @frostworx! I've used STL for a long time now and it works like a charm for me. 
Have a good one!

**Comment by sonic2kk** [comment]
Closing this :-) Thanks for all the awesome effort and I'll try to keep improving steamtinkerlaunch into the future!
