### ISSUE TITLE
STL and game crashing immediatly after lauch of Mass Effect Legendary Edition

### ISSUE THREAD

**Issue by JoeHardi** [sonic2kk/steamtinkerlaunch#539]
I am running STL on ZorinOS and noticed that the launcher and the game (Mass Effect Legendary Edition) ctash immediatly after pressing "play". I am mainly want to get ti to run because of FlawlessWidescreen.

Tried it with default settings - still the same.

STL works perfectly fine with other games, as the regular Proton version on Mass Effect.

Any thoughts? Thanks! And thank you for the great tool!

**Comment by frostworx** [comment]
fixed in git-master _(see #508 - still needs to be tested)_
