### ISSUE TITLE
Recent update broke cheat engine

### ISSUE THREAD

**Issue by VasyaSovari** [sonic2kk/steamtinkerlaunch#542]
# Please see this [sticky note](https://github.com/frostworx/steamtinkerlaunch/issues/93) for what is required for a good issue
Hi all.
CheatEngine no longer launches. Alert states :
`WARNING - disabling 'RUN_CHEATENGINE' because program '7za' was not found`

**Comment by VasyaSovari** [comment]
oh. Issue was resolved by installing p7zip from aur.
Leaving this open so it can maybe be fixed internally

**Comment by zany130** [comment]
you need p7zip to extract the archive cheat engine is in there's nothing steamtinkerlaunch can do about that. As the log mentions the user needs to install a 7zip extracter.

**Comment by VasyaSovari** [comment]
Cool.
I'll leave it to your discretion whether it's worth keeping this open purely so others can read it

**Comment by AliceDTRH** [comment]
I suggest closing it unless you have any other questions related to this, (p)7zip is already listed as an optional dependency everywhere as far as I know, so it's not a bug.
