### ISSUE TITLE
[Question] How do I run custom commands in wine

### ISSUE THREAD

**Issue by AliceDTRH** [sonic2kk/steamtinkerlaunch#544]
I was wondering how I run custom commands like winecfg or explorer inside of the prefix, is there an easy way to do this from Steam tinker launch or should I use a different tool for this?

**Comment by zany130** [comment]
https://github.com/frostworx/steamtinkerlaunch/wiki/Winecfg

![image](https://user-images.githubusercontent.com/25832539/184459208-cea8686e-5903-41c5-8210-1e83c1356615.png)



you can run winetricks also by selecting that option https://github.com/frostworx/steamtinkerlaunch/wiki/Winetricks

p.s: there is a really good wiki you can checkout for faster answers 😉

**Comment by AliceDTRH** [comment]
Thank you, I checked the wiki but I must have missed that option.

**Comment by zany130** [comment]
The wiki can be a bit overwhelming if you're just searching blindly there a page search on the right were it lists the different pages that you can use.
