### ISSUE TITLE
[Question] How can I help?

### ISSUE THREAD

**Issue by AliceDTRH** [sonic2kk/steamtinkerlaunch#545]
I noticed your sticky and I was wondering if there's any way I can be of assistance with anything.
I don't know much about proton or yad but I have experience with Linux and Github and several programming languages.
I'd be happy to help in my spare time.

**Comment by zany130** [comment]
I feel like I remember frostworx  having a section in the readme about how to contribute. But basically, you could help maintain the wiki and check for spelling errors or anything that could be clarified better. You could discuss that here https://github.com/frostworx/steamtinkerlaunch/issues/457. You could make an issue about a bug or a new feature you think should be added, If you are good with bash (don't really need to be a programming wiz) you could contribute a pull request.

**Comment by AliceDTRH** [comment]
Thank you!
