### ISSUE TITLE
[Question] Is there a way to run a game alongside with Textractor?

### ISSUE THREAD

**Issue by WilsonNet** [sonic2kk/steamtinkerlaunch#546]
Hello, I'm trying to figure out a way to run games with [Textractor](https://github.com/Artikash/Textractor)

I want to know if it is possible with steamtinkerlaunch. I managed to run the software inside the steam prefix using a custom command, but not on the same time.

**Comment by zany130** [comment]
take a look here at all the ways to run a custom command https://github.com/frostworx/steamtinkerlaunch/wiki/Custom-Program

you may either want to use the fork or inject options mentioned in the wiki

**Comment by WilsonNet** [comment]
fork worked, thanks!
