### ISSUE TITLE
Vortex & Fallout 4 error

### ISSUE THREAD

**Issue by waelisa** [sonic2kk/steamtinkerlaunch#547]
Vortex show error
`SetupError: Missing: Z:\mnt\2TB-Linux\SteamLibrary\steamapps\common\Fallout 4\data
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:2797:145
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)`

**Comment by waelisa** [comment]
I mean, can't edit or remove Fallout 4 from Vortex

**Comment by sonic2kk** [comment]
Hi, the error you posted doesn't seem to be *all* that relevant unfortunately as it seems like a general Vortex error and not a Wine log. It looks however like it can't find the `data` folder for Fallout 4? This could be a general Vortex problem, I recommend first trying to troubleshoot and find if others have had this problem with Vortex in general.

Otherwise, something may have gone wrong with the Vortex installation. It might be worth trying to reinstall Vortex. I am not totally sure how to do this with STL but I would start by going to the SteamTinkerLaunch config folder (if you installed with Flatpak it might be in a folder named something like `~/.var/com.ValveSoftware`, otherwise it should be at `~/.config/steamtinkerlaunch/`) and renaming your `vortex` folder to something else. I suggest renaming instead of removing just in case :slightly_smiling_face: From there, attempt to reinstall Vortex and set up Fallout 4 again.

If possible, it would also be helpful if you could provide some more information such as:
- `steamtinkerlaunch.log` file, found in `/dev/shm/steamtinkerlaunch.log`. Attempt to run Vortex again and when you get the error, close Fallout 4 from Steam and then attach the log generated
- Distro and Desktop Environment
- SteamTinkerLaunch version
- How you installed SteamTinkerLaunch (Flatpak/Steam Deck/Package Manager/etc)
- What mod(s) you were trying to install when this occurred
- More information about what's going on
- Anything else you think might be helpful :smile: I don't use Vortex so I'm not sure what else might be relevant

**Comment by waelisa** [comment]
I use Solus and Fallout 4 clean, so no mods install, I was using Vortex with Skyrim special edition long time without any problem, when I change game to other games on Vortex okay but Fallout 4 show error, log here
`Mon Aug 22 12:07:36 PM +03 2022 INFO - initAID - Set AID from STEAM_COMPAT_APP_ID to '377160'
Mon Aug 22 12:07:36 PM +03 2022 INFO - initAID - Set OSCDP to STEAM_COMPAT_DATA_PATH '/mnt/2TB-Linux/SteamLibrary/steamapps/compatdata/377160'
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLangFile - Language from command line is 'english'
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLangFile - GLOBALSTLLANGDIR is '/usr/share/steamtinkerlaunch/lang'
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLangFile - Loading found system wide /usr/share/steamtinkerlaunch/lang/english.txt
Mon Aug 22 12:07:36 PM +03 2022 INFO - getCurrentCommandline - No Proton in command line arguments 'vortex start'
Mon Aug 22 12:07:36 PM +03 2022 INFO - saveOrgVars - Storing some original variables to restore them later
Mon Aug 22 12:07:36 PM +03 2022 INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
Mon Aug 22 12:07:36 PM +03 2022 INFO - emptyVars - Set $PATH to '/sbin:/bin:/usr/sbin:/usr/bin:/snap/bin:::'
Mon Aug 22 12:07:36 PM +03 2022 START - ######### Initializing Game Launch 377160 using SteamTinkerLaunch v11.0 #########
Mon Aug 22 12:07:36 PM +03 2022 INFO - main - Starting with a clean log
Mon Aug 22 12:07:36 PM +03 2022 INFO - main - Start creating default configs
Mon Aug 22 12:07:36 PM +03 2022 INFO - createDefaultCfgs - START
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLangFile - Language from command line is 'english'
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLangFile - GLOBALSTLLANGDIR is '/usr/share/steamtinkerlaunch/lang'
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLangFile - Loading found system wide /usr/share/steamtinkerlaunch/lang/english.txt
Mon Aug 22 12:07:36 PM +03 2022 WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
Mon Aug 22 12:07:36 PM +03 2022 INFO - updateEditor - No valid editor found - will fall back to 'xdg-open'.
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLanguage - Loading STLLANG from '/home/wael/.config/steamtinkerlaunch/global.conf'
Mon Aug 22 12:07:36 PM +03 2022 INFO - loadLanguage - STLLANG from '/home/wael/.config/steamtinkerlaunch/global.conf' is 'english'
Mon Aug 22 12:07:36 PM +03 2022 INFO - createDefaultCfgs - setSteamPaths:
Mon Aug 22 12:07:36 PM +03 2022 INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
Mon Aug 22 12:07:36 PM +03 2022 WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
Mon Aug 22 12:07:36 PM +03 2022 INFO - updateEditor - No valid editor found - will fall back to 'xdg-open'.
Mon Aug 22 12:07:36 PM +03 2022 INFO - getGameOS - Starting game OS detection
Mon Aug 22 12:07:36 PM +03 2022 WARN - getGameOS - Could not extract the full game binary path from the incoming game launch command, so assuming this is a Windows game!
Mon Aug 22 12:07:36 PM +03 2022 INFO - setWin - '' determined to be a Windows Game
Mon Aug 22 12:07:36 PM +03 2022 INFO - createDefaultCfgs - createProtonList:
Mon Aug 22 12:07:36 PM +03 2022 INFO - createDefaultCfgs - createProtonList end
Mon Aug 22 12:07:36 PM +03 2022 INFO - listAllSettingsEntries - '/dev/shm/steamtinkerlaunch/setentries.txt' already exists - nothing to do
Mon Aug 22 12:07:36 PM +03 2022 INFO - createDefaultCfgs - STOP
Mon Aug 22 12:07:36 PM +03 2022 SKIP - listSteamLibraries - not recreating already available '/dev/shm/steamtinkerlaunch/SteamLibraries.txt'
Mon Aug 22 12:07:36 PM +03 2022 INFO - setSteamLibraryPaths - STEAM_COMPAT_LIBRARY_PATHS set to '/mnt/2TB-Linux/SteamLibrary/steamapps:/home/wael/.local/share/Steam/steamapps'
Mon Aug 22 12:07:36 PM +03 2022 INFO - setSteamLibraryPaths - STEAM_COMPAT_MOUNTS set to '/home/wael/.local/share/Steam/steamapps/common/Steamworks Shared:/mnt/2TB-Linux/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier'
Mon Aug 22 12:07:36 PM +03 2022 INFO - setSteamLibraryPaths - STEAM_COMPAT_TOOL_PATHS set to '/home/wael/.local/share/Steam/compatibilitytools.d/GE-Proton7-29:/mnt/2TB-Linux/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier:/home/wael/.local/share/Steam/steamapps/common/Steamworks Shared'
Mon Aug 22 12:07:36 PM +03 2022 INFO - main - Checking internal dependencies:
Mon Aug 22 12:07:36 PM +03 2022 INFO - checkIntDeps - Result of version check for yad binary '/usr/bin/yad' is '12.0'
Mon Aug 22 12:07:36 PM +03 2022 INFO - main - Initializing first Proton:
Mon Aug 22 12:07:36 PM +03 2022 INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/steamtinkerlaunch/ProtonCSV.txt' which was created during a previous run
Mon Aug 22 12:07:36 PM +03 2022 INFO - initFirstProton - Initializing Proton
Mon Aug 22 12:07:36 PM +03 2022 INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/wael/.config/steamtinkerlaunch/default_template.conf' is 'proton-7.0-4'
Mon Aug 22 12:07:36 PM +03 2022 INFO - main - Initializing default window resolution
Mon Aug 22 12:07:37 PM +03 2022 INFO - setInitWinXY - Using '1440x810' from config '/dev/shm/steamtinkerlaunch/defres.txt'
Mon Aug 22 12:07:37 PM +03 2022 INFO - main - Checking command line: incoming arguments 'vortex start'
Mon Aug 22 12:07:37 PM +03 2022 INFO - setVortexVars - Using GE-Proton7-27 for vortex
Mon Aug 22 12:07:37 PM +03 2022 INFO - setVortexDLMime - INFO: Linking Nexus Mods downloads to Vortex
Mon Aug 22 12:07:37 PM +03 2022 INFO - setVortexDLMime - Desktopfile /home/wael/.local/share/applications/vortex-steamtinkerlaunch-dl.desktop seems to be up2date
Mon Aug 22 12:07:37 PM +03 2022 INFO - setVortexDLPath - Setting Vortex Download WinDir 'Z:\\home\\wael\\.config\\steamtinkerlaunch\\vortex\\downloads' in Vortex
Mon Aug 22 12:07:37 PM +03 2022 INFO - setVortexConfigVdf - Updating 'config/config.vdf' in the Vortex pfx, to make newly games available when auto-detectable
Mon Aug 22 12:07:37 PM +03 2022 INFO - getRes - Detected screen resolution '1920x1080'
Mon Aug 22 12:07:37 PM +03 2022 INFO - pollWinRes - Using GEOM '--geometry=1002x810+0+0' from '/home/wael/.config/steamtinkerlaunch/guicfgs/1920x1080/377160/SteamTinkerLaunch-PrepareVortexGameStatus.conf'
Mon Aug 22 12:07:37 PM +03 2022 INFO - StatusWindow - for 'Vortex'
Mon Aug 22 12:07:37 PM +03 2022 INFO - updateWinRes - Starting resolution-poll for '/home/wael/.config/steamtinkerlaunch/guicfgs/1920x1080/377160/SteamTinkerLaunch-PrepareVortexGameStatus.conf' with incoming '1002x810'
Mon Aug 22 12:07:37 PM +03 2022 INFO - prepareVortexGame - '"fallout4" (377160)' is already setup for 'Vortex' - remove from '/home/wael/.config/steamtinkerlaunch/vortex/compatdata/seenvortexgames.txt' for retry
Mon Aug 22 12:07:37 PM +03 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Mon Aug 22 12:07:37 PM +03 2022 INFO - getRes - Detected screen resolution '1920x1080'
Mon Aug 22 12:07:37 PM +03 2022 INFO - pollWinRes - Using GEOM '--geometry=1002x810+0+0' from '/home/wael/.config/steamtinkerlaunch/guicfgs/1920x1080/377160/SteamTinkerLaunch-PrepareVortexGameStatus.conf'
Mon Aug 22 12:07:37 PM +03 2022 INFO - StatusWindow - for 'Vortex'
Mon Aug 22 12:07:37 PM +03 2022 INFO - updateWinRes - Starting resolution-poll for '/home/wael/.config/steamtinkerlaunch/guicfgs/1920x1080/377160/SteamTinkerLaunch-PrepareVortexGameStatus.conf' with incoming '1002x810'
Mon Aug 22 12:07:37 PM +03 2022 INFO - prepareAllInstalledVortexGames - Preparing all installed games supported by Vortex
Mon Aug 22 12:07:37 PM +03 2022 INFO - setVortexVars - Using GE-Proton7-27 for vortex
Mon Aug 22 12:07:37 PM +03 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Mon Aug 22 12:07:37 PM +03 2022 INFO - setVortexVars - Using GE-Proton7-27 for vortex
Mon Aug 22 12:07:37 PM +03 2022 INFO - gVSIDs - Searching for SteamIDs in '/home/wael/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/resources/app.asar.unpacked/bundledPlugins'
Mon Aug 22 12:07:37 PM +03 2022 INFO - gVSIDs - Searching for SteamIDs in '/home/wael/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/Application Data/Vortex/plugins'
Mon Aug 22 12:07:37 PM +03 2022 INFO - prepareVortexGame - '"fallout4" (377160)' is already setup for 'Vortex' - remove from '/home/wael/.config/steamtinkerlaunch/vortex/compatdata/seenvortexgames.txt' for retry
Mon Aug 22 12:07:37 PM +03 2022 INFO - prepareVortexGame - '"skyrimse" (489830)' is already setup for 'Vortex' - remove from '/home/wael/.config/steamtinkerlaunch/vortex/compatdata/seenvortexgames.txt' for retry
Mon Aug 22 12:07:37 PM +03 2022 INFO - prepareAllInstalledVortexGames - Applying Vortex settings for all games via autogenerated cmd '/dev/shm/steamtinkerlaunch/vortset.cmd'
Mon Aug 22 12:07:38 PM +03 2022 INFO - updateWinRes - Window 'SteamTinkerLaunch-PrepareVortexGameStatus' is running - polling the resolution
Mon Aug 22 12:07:38 PM +03 2022 INFO - updateWinRes - Found new Window Resolution '1006x810' for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Mon Aug 22 12:07:38 PM +03 2022 INFO - updateWinRes - Window 'SteamTinkerLaunch-PrepareVortexGameStatus' is running - polling the resolution
Mon Aug 22 12:07:38 PM +03 2022 INFO - updateWinRes - Found new Window Resolution '1006x810' for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Mon Aug 22 12:07:42 PM +03 2022 INFO - prepareAllInstalledVortexGames - Symlinks, registry entries and vortex settings for all found supported games should be ready at this point for Vortex
Mon Aug 22 12:07:42 PM +03 2022 INFO - startVortex - Starting Vortex without options
Mon Aug 22 12:07:43 PM +03 2022 INFO - updateWinRes - The Window 'SteamTinkerLaunch-PrepareVortexGameStatus' was closed - saving the last seen resolution '1006x810' into config '/home/wael/.config/steamtinkerlaunch/guicfgs/1920x1080/377160/SteamTinkerLaunch-PrepareVortexGameStatus.conf'
Mon Aug 22 12:07:43 PM +03 2022 INFO - updateConfigEntry - Option 'WINX' is updated with the new value '1006' in config 'SteamTinkerLaunch-PrepareVortexGameStatus.conf'
Mon Aug 22 12:07:43 PM +03 2022 INFO - saveNewRes - Saved new resolution '1006x810' in '/home/wael/.config/steamtinkerlaunch/guicfgs/1920x1080/377160/SteamTinkerLaunch-PrepareVortexGameStatus.conf'
Mon Aug 22 12:07:43 PM +03 2022 INFO - updateWinRes - The Window 'SteamTinkerLaunch-PrepareVortexGameStatus' was closed - saving the last seen resolution '1006x810' into config '/home/wael/.config/steamtinkerlaunch/guicfgs/1920x1080/377160/SteamTinkerLaunch-PrepareVortexGameStatus.conf'
Mon Aug 22 12:07:43 PM +03 2022 INFO - updateConfigEntry - Option 'WINX' is updated with the new value '1006' in config 'SteamTinkerLaunch-PrepareVortexGameStatus.conf'
Mon Aug 22 12:07:43 PM +03 2022 INFO - saveNewRes - Saved new resolution '1006x810' in '/home/wael/.config/steamtinkerlaunch/guicfgs/1920x1080/377160/SteamTinkerLaunch-PrepareVortexGameStatus.conf'
`

**Comment by AliceDTRH** [comment]
I turned the posted logfile into a gist for anyone reading: https://gist.github.com/AliceDTRH/383cbfaf85d0943f482b95e036d202a0

**Comment by frostworx** [comment]
thanks @AliceDTRH , please take care for proper formatting , @waelisa. apparently no human could read your paste _(assuming including you)_
can't see anything suspicious in the log though, so maybe you're affected by #555 as well

**Comment by sonic2kk** [comment]
I think this problem is related to #555, particularly the problem with Vortex removing support for symlinks. Maybe this can be closed and considered part of the Vortex issue.

**Comment by frostworx** [comment]
yes, likely a duplicate and missing feedback on top *closing*
