### ISSUE TITLE
Winetricks Fails to Download DLLs

### ISSUE THREAD

**Issue by NapalmDest54** [sonic2kk/steamtinkerlaunch#549]
I am launch on Steam Deck, but will try on Linux desktop shortly.

I have selected dotnet472 through the winetricks menu. It always attempts to download. I also have tried checking the Winetricks GUI box in the Game Menu, doing so launches Winetricks, it downloads dotnet472, but fails to extract it for missing the extract library (on steam deck only)?

```
Mon Aug 15 04:48:43 PM EDT 2022 INFO - chooseWinetricks - Using '/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks' with version '20220411-next'
Mon Aug 15 04:48:43 PM EDT 2022 INFO - prepareLaunch - checkExtDeps:
Mon Aug 15 04:48:43 PM EDT 2022 INFO - prepareLaunch - checkExtDeps done
Mon Aug 15 04:48:43 PM EDT 2022 INFO - prepareLaunch - setWineVars:
Mon Aug 15 04:48:43 PM EDT 2022 INFO - prepareLaunch - CheckWinetricksLaunch:
Mon Aug 15 04:48:43 PM EDT 2022 SKIP - chooseWinetricks - 'WINETRICKS variable' already exists and points to '/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks'
Mon Aug 15 04:48:43 PM EDT 2022 INFO - installWinetricksPaks - Trying to installing following new or previously missed packages now: 'dotnet472'
Mon Aug 15 04:48:43 PM EDT 2022 INFO - notiShow - Skipping notifier on SteamDeck
Mon Aug 15 04:48:43 PM EDT 2022 INFO - extWine64Run - Command in Proton WINEPREFIX is: WINE="/home/deck/.config/steamtinkerlaunch/proton/custom/GE-Proton7-29/files/bin/wine" WINEARCH=win64 WINEDEBUG="-all" WINEPREFIX="/home/deck/.local/share/Steam/steamapps/compatdata/2320356364/pfx" /home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks --force --unattended dotnet472
```

**Comment by sonic2kk** [comment]
Possibly related to #543, I'm not sure if Winetricks is fully supported on Steam Deck.

I would be interested for you to try on your Linux desktop! Could you also respond with the versions of SteamTinkerLaunch that you're using on Steam Deck and on PC, as well as the distro that you're using on your PC? Thanks! :smile:

**Comment by frostworx** [comment]
steamtinkerlaunch tries to detect if winetricks fails with installing a package by reading its log file.
dotnet install historically can crash/permaloop when installing and winetricks does a lot to circumvent this.
steamtinkerlaunch more or less works as a winetricks wrapper, so this could be anything, but not nessesarily a steamtinkerlaunch issue. I suggest checking the md5sum of the downloaded file in `~/.cache/winetricks/dotnet472/NDP472-KB4054530-x86-x64-AllOS-ENU.exe` first. mine is:

```
# md5sum NDP472-KB4054530-x86-x64-AllOS-ENU.exe 
87450cfa175585b23a76bbd7052ee66b  NDP472-KB4054530-x86-x64-AllOS-ENU.exe
```

either way, it always makes sense to attach a full log, so people would not guess which steamtinkerlaunch version was used or if something else went wrong

**Comment by frostworx** [comment]
possibly related: https://github.com/frostworx/steamtinkerlaunch/issues/555

**Comment by sonic2kk** [comment]
Something to note here as well is this part of your log:

```
Mon Aug 15 04:48:43 PM EDT 2022 INFO - chooseWinetricks - Using '/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks' with version '20220411-next'
```

This is a pretty outdated version of Winetricks to be using with a very new release of GE-Proton. Maybe it's failing because of incompatibilities with the `dotnet` winetrick and the version of Wine attempting to be used?

**Comment by frostworx** [comment]
I just sshed into my steamdeck and executed directly your command:
`WINE="/home/deck/.config/steamtinkerlaunch/proton/custom/GE-Proton7-29/files/bin/wine" WINEARCH=win64 WINEDEBUG="-all" WINEPREFIX="/home/deck/.local/share/Steam/steamapps/compatdata/2320356364/pfx" /home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks --force --unattended dotnet472`
the last stdout line is
`warning: Cannot find cabextract.  Please install it (e.g. 'sudo apt-get install cabextract' or 'sudo yum install cabextract').`
which likely is your problem.
depending on the dependencies of `cabextract` a possible workaround would be to download `cabextract` from the valve or arch mirrors and install it automatically to `/home/deck/stl/deps/usr/bin/`

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/commit/c03f198d56b38d37eb53df9c1637bc30f1b76f4b should work. please test :)

**Comment by frostworx** [comment]
.

**Comment by frostworx** [comment]
missing feedback
