### ISSUE TITLE
Add Non-Steam Game Menu Doesn't List Tags Correctly

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#557]
The "Tags" dropdown in the `steamtinkerlaunch ansg gui` menu won't properly separate tags into separate entries, instead it puts them all on one line (which actually gets cut off for me because there are so many). See below:

![image](https://user-images.githubusercontent.com/7917345/187032885-b519defb-0935-4d6e-a153-ea7e1314f962.png)

Maybe this is caused by too many tags? Haven't looked into the cause :sweat_smile: The "Tags" menu works correctly though:

![image](https://user-images.githubusercontent.com/7917345/187032985-ae9b164c-4c55-49c5-92e1-aca9da993fcf.png)

Hadn't used this menu until earlier today so I never noticed this before.

**Comment by frostworx** [comment]
~~this was intended behavior, and was meant for picking "tags" manually (and therefore not having to open the tags menu).~~
scratch that. I'm pretty sure this was the case initially, but I just checked my function and you're completely right.
I'll continue in PR later.
