### ISSUE TITLE
Adding a Non-Steam Game Doesn't Automatically Select Compatibility Tool/Launch Option

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#558]
Adding a Non-Steam game via `steamtinkerlaunch ansg gui` won't automatically set SteamTinkerLaunch as the compatibility tool or launch option.

I'm not even totally sure if we *can* do this but if we can, we should set it as a compatibility tool for game executables ending with `.exe`, `.lnk` and maybe some other formats we can assume should be launched with Wine/Proton, and set it as a launch option otherwise.

If we can't do this (which is fine imo), we should tell the user to manually set SteamTinkerLaunch as the compatibility tool/launch option. Just reporting this because when I was testing this feature, I was caught off guard that it wasn't launched with STL automatically :-)

EDIT: I guess a user could add it as a launch option by setting `steamtinkerlaunch %command%` as the launch option from the `ansg` menu. Not sure how we should handle the native-Linux case.

**Comment by sonic2kk** [comment]
[ProtonUp-Qt](https://github.com/DavidoTek/ProtonUp-Qt) is able to set the compatibility tool for Steam games. Relevant code is likely [here](https://github.com/DavidoTek/ProtonUp-Qt/blob/main/pupgui2/steamutil.py#L226-L286), seems like they update a `config.vdf` file for a game. I'm not sure if Non-Steam games have this and I haven't checked if/how this works with Non-Steam games yet.

If it works though, STL should be able to do this in some similar way. Not sure if/when I'll have time to look into this specifically but I'll leave the issue open for discussion and for potential contributors :smile:

**Comment by frostworx** [comment]
good find! personally I wasn't confident if manipulating steam internal vdfs was a good idea and therefore I avoided it whereever possible _(it mostly was/is)_
Maybe a good idea to implement it as global option at least though.
*waiting for potential contributors* ;)

**Comment by frostworx** [comment]
Hm, the main "$problem" would be, that this little feature would pull in https://github.com/ValvePython/vdf and/or https://github.com/ValvePython/steam as dependency to calculate the required string for the `localconfig.vdf`.

The package is very likely very mighty and probably would offer multiple new possibilities for new features, but I wouldn't dig though its api for a feature, the users can solve themselves with one click.

Another good example for `steamtinkerlaunch` should have been written in python from scratch, but it is far too late
_(bash still rocks though of course - nut not perfect for such a beast steamtinkerlaunch became)_

In theory, still interesting to have support for those libraries, but I'd guess this likely won't happen.
Sorry...

**Comment by sonic2kk** [comment]
Ah yes ProtonUp-Qt uses the Python vdf library, but there *could* be a way to do this in Bash... probably not in a very pretty though (STL writes to `shortcuts.vdf` I believe, maybe a similar idea could be taken for writing to `localconfig.vdf`)

**Comment by sonic2kk** [comment]
Okay so I had a look. File IO in Bash is something I'm not too familiar with, but it seems like compat tools are stored in `~/.local/share/Steam/config/config.vdf`, and the `config.vdf` seems to be a """normal""" text file, unlike some of the other config files (I believe things like `shortcuts.vdf` use a never VDF version? not sure).

Basically how Steam stores compatibility tools In `config.vdf` is this: Under the `"CompatToolMapping"` block there are a bunch of values that are structured like this (replace `game_appid` with a real AppID):

```
"CompatToolMapping"
{
    "game_appid"
    {
        "name": "Proton-stl"
        "config": ""
        "priority": "250"
    }
}
```
*(`CompatToolMapping` is MUCH bigger than this, this is just an example of one block for one game)*

There is some spacing between the values, which may not be relevant and which Steam might format itself.

For `"priority"`, some games have different values but most seem to be set to `"250"`. [Even ProtonUp-Qt defaults to `"250"`](https://github.com/DavidoTek/ProtonUp-Qt/blob/main/pupgui2/steamutil.py#L248).

So we'd have to edit this section of the `config.vdf` to add a block that looks like the above for the current AppID. Doing that kind of delicate file editing in Bash is probably about as fun as getting a tooth extracted, but then there's the problem of actually knowing the AppID for the Non-Steam game. At present I have no idea how this works and I've spent some time looking into it (see #550, #576).

But in principle, that's how we would set SteamTinkerLaunch as the compatibility tool for an added Non-Steam game. It would probably be nicer to do this in Bash as it would save having to pull in Python and a third-party library as a dependency to do this. And as you mentioned it is something the user can do in one click. But if/when there is an update to getting the non-Steam AppID, half the battle (optimistically ;D) would be won for implementing this.

No worries about not looking into it, this is a very low-priority "problem". But this should describe to any brave soul (maybe future sonic2kk) how in-theory to do this.

**Comment by sonic2kk** [comment]
This issue is kinda blocked until there's a method figured out to generate the AppID for Non-Steam Games. Not sure if I should close it though, maybe close this and re-open if/when some more work is done in that area.

**Comment by sonic2kk** [comment]
Going to close this, as I don't see there being any progress on this in the short-to-medium term
