### ISSUE TITLE
Older DirectX fullscreen only games fail to find display

### ISSUE THREAD

**Issue by VGJUNKY** [sonic2kk/steamtinkerlaunch#564]
These games were not an issue on version 10, but are on the latest PR

While looking at #523 I had a non-steam game unable to run. I've now found out it is unrelated to the fork or inject custom command settings.

I have 2 examples of older games that run fine in proton 7.0-4 both on desktop and game mode on steamdeck but fail on stl with default settings.

Game 1: [Croc 2](https://en.wikipedia.org/wiki/Croc_2) 
**Error message**
![Screenshot_20220830_155429](https://user-images.githubusercontent.com/94434500/187557981-e328fa6c-f571-4591-b1df-92c08c341eb2.png)
**Logs**
[steamtinkerlaunch_croc2.log](https://github.com/frostworx/steamtinkerlaunch/files/9457095/steamtinkerlaunch_croc2.log)
[steam-15252888409685884928_croc2_protonlog.log](https://github.com/frostworx/steamtinkerlaunch/files/9457096/steam-15252888409685884928_croc2_protonlog.log)

Game 2: [Garfield lasagna world tour](https://garfield.fandom.com/wiki/Garfield:_Lasagna_World_Tour)
No Error just a silent crash
**Logs**
[steamtinkerlaunch_garfield.log](https://github.com/frostworx/steamtinkerlaunch/files/9457107/steamtinkerlaunch_garfield.log)
[steam-16340261450566074368_garfield_protonlog.log](https://github.com/frostworx/steamtinkerlaunch/files/9457108/steam-16340261450566074368_garfield_protonlog.log)

Both games force fullscreen with no windowed options naively, there's a workaround which is to enable virtual desktop, but this removes the ability to seperate and easily focus a custom command program (alt tab) as well as steam input doesn't apply custom control bindings to a game running in virtual desktop.

**Comment by frostworx** [comment]
sorry, I can't think of any reason why steamtinkerlaunch could even cause this directly. I'd guess that the wineprefix/compatdata used is kind of borked and therefore would suggest to start with a one for the beginning. 
just found garfield lasagna on archive.org and try to reproduce it when I find the time.

**Comment by frostworx** [comment]
directly tested it and it works fine ootb on my system _(using GE-Proton7-31)_. So I recommend to really start with a clean wineprefix/compatdata

**Comment by sonic2kk** [comment]
I agree with Frostworx, and wanted to mention an easy to way to do this on Steam Deck from Game Mode is by pressing the "Options" (or "Start") button, and under the "Developer" settings you can select "Delete Proton files". Note that this may delete some game-specific things that may not be backed up in the Steam Cloud, such as game saves that are stored in the Windows "My Documents" folder. These would be saved to the wineprefix. And related to discussions on other issues, this will delete any Winetricks installed.

**Comment by VGJUNKY** [comment]
Unfortunately deleting the prefix for both games (using game modes ui) and trying again with stl as the compatibility tool failed in the same way. Since you didn’t have this issue @frostworx it maybe steam deck specific.

I used proton 7 without stl afterwards and it worked.

**Comment by sonic2kk** [comment]
Had a look in the Croc2 log, found this interesting section:
```
Tue Aug 30 02:58:24 PM PDT 2022 STOP - ######### SteamTinkerLaunch v11.1.20220830 #########
Tue Aug 30 02:58:24 PM PDT 2022 STOP - ######### CLEANUP #########
Tue Aug 30 02:58:24 PM PDT 2022 INFO - closeSTL - closing STL
Tue Aug 30 02:58:24 PM PDT 2022 INFO - updateConfigEntry - Emptying 'CUSTOMCMD' for '/home/deck/.config/steamtinkerlaunch/default_template.conf'
Tue Aug 30 02:58:24 PM PDT 2022 INFO - updateConfigEntry - Option 'CUSTOMCMD' is updated with the new value 'echo' in config 'default_template.conf'
Tue Aug 30 02:58:24 PM PDT 2022 INFO - closeSTL - Creating '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
Tue Aug 30 02:58:24 PM PDT 2022 INFO - setPrevRes - Returning to previous screen resolution via 'xrandr -s 0'
Tue Aug 30 02:58:24 PM PDT 2022 INFO - checkPlayTime - The game was not started via 'steamtinkerlaunch' but directly from Steam - skipping Crash Requester
Tue Aug 30 02:58:24 PM PDT 2022 INFO - steamdeckClose - recovering original gtk.css from '/home/deck/.config/gtk-3.0/gtk.css_ORIGNAL'
Tue Aug 30 02:58:24 PM PDT 2022 INFO - closeSTL - Game 'Croc2 (4245217489)' exited - cleaning up custom processes if necessary
Tue Aug 30 02:58:24 PM PDT 2022 INFO - notiShow - Skipping notifier on SteamDeck
Tue Aug 30 02:58:24 PM PDT 2022 INFO - closeTrayIcon - Closing TrayIcon ''
```
In particular, the `xrandr` command is interesting. I wonder if this is why those older games can't find a display device? I know little to nothing about xrandr but I'm fairly sure it's related to setting display modes, so it could be relevant. Maybe some other commands are needed?

The Proton log complains about display modes too, quite a lot:

```
121199.314:0134:0138:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" supported display modes.
121199.314:0134:0138:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" supported display modes.
```
So I guess however the previous resolution is set, these older games don't seem to like. I wonder if this is specific to Non-Steam games?

@VGJUNKY could you test with a GEProton release if possible? Maybe this is a Proton bug(?) that GE has fixes for, but no idea. These are Non-Steam games too so maybe GE has general patches for them that aren't in Proton.

EDIT: Just checked the logs on my laptop and PC, `setPrevRes` isn't called on desktop it seems like, so it might only be called for Steam Deck.

**Comment by sonic2kk** [comment]
Still not sure what causes this but just a heads up that the fix for Non-Steam Games may be reverted soon, though a full fix for the underlying issue should come soon.

Not totally sure it's anything to do with `setPrevRes` anymore as it looks like Garfield doesn't have that, though you mentioned it just silently crashes, so there could be two separate issues.

Maybe you could try forcing the Steam Linux Runtime? I'm not sure how Steam Deck launches Non-Steam games so there could be something the Deck does that STL doesn't. Not sure if the SLR would be related but there's only one way to find out I suppose :smile:

**Comment by VGJUNKY** [comment]
Proton-ge does nothing different. These 2 games work perfectly fine on standard 7 proton in steam. Nor does forcing SLR do anything. Its good that we’ve figured out its steam deck specific at the very least.

I believe the issues are the same cuz the proton logs both indicate it fails to find a display. But I can’t decern anything more specific.

For now I’ll keep this issue open as I’m feeling lazy and want to do a proper writeup when making a new issue. And I don’t have much time for that atm.

**Comment by sonic2kk** [comment]
I wonder if the game is using a different wineprefix with STL versus with a regular Steam launch. Not totally sure what could be causing the Proton log display error but I'll have a look around and see if I can spot anything online for other games.

If your game has a config file anywhere you could try manually editing it and seeing if anything looks off.

Also, maybe Steam isn't correctly deleting the Proton files for Non-Steam games. You could try manually deleting the prefix which is seemingly at `/home/deck/.local/share/Steam/compatdata/3804377994`. Delete the folder called `3804377994` and try running your game again. Though that would be strange as it means STL and Steam are using different prefixes...

**Comment by frostworx** [comment]
I still don't think this is a steamtinkerlaunch issue.
I'd guess as well that the wineprefix could have been partially broken _(this occassionally happens when switching proton versions - not steamtinkerlaunch related)_
Can you reproduce that the games still do work with steamtinkerlaunch 10?

**Comment by VGJUNKY** [comment]
I don’t think i can test 10 on steam deck, it just auto updates to 11 aka newest version

**Comment by frostworx** [comment]
just comment out https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L20153
in v10
