### ISSUE TITLE
Uninstall documentation

### ISSUE THREAD

**Issue by MysticalOS** [sonic2kk/steamtinkerlaunch#566]
Quite simply, can find plenty of install documentation, but can't find any for clean uninstall. If it exists, it should be easier to locate in the wiki/main page.

**Comment by frostworx** [comment]
Quite simple, it is usually uninstalled by using the package management used for installing.
When installing via `Makefile` - it doesn't have an uninstall-section apparently, but is very readable, so the steps can be easily reverted.
All additional data steamtinkerlaunch creates can be found in the user dir `~/.config/steamtinkerlaunch`

PRs for both the uninstall section and the wiki would be accepted of course if done properly.

**Comment by MysticalOS** [comment]
That's fair.

I pretty much installed it on steam deck only to find it's pretty much non functional all around except as a package manager itself. Although it doesn't harm anything staying installed either I suppose since as far as I can see doesn't load unless instructed too as a compat option. Anyways, I'll go ahead and close this.

**Comment by frostworx** [comment]
The [Steam Deck](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Deck) clearly says where it is installed on the Steam Deck. Happy uninstalling!

**Comment by sonic2kk** [comment]
On Steam Deck you can use STL without having to set it as a compatibility tool by entering the path to the script. Something like `/home/deck/stl/prefix/steamtinkerlaunch %command%` should suffice.

Keep in mind STL is designed to be used as a compatibility tool for Proton games (many native Linux titles use Proton on Deck) and only as a launch option for native Linux games. You can choose a Proton version to run your game with from the Game Menu, so if you were concerned about waiting to use STL and say, GE-Proton, no worries there 🙂 

I think it is a bit harsh to deem STL as "non-functional" on Steam Deck, as I can personally vouch that it works quite well on my Steam Deck 😄

**Comment by frostworx** [comment]
tool functionality often depends on the user.
`PEBKAC` people often tend to open incomplete "issues", become harsh, be demanding and never contribute. ¯\\_(ツ)_/¯
