### ISSUE TITLE
Gamescope concatenation does not always work

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#567]
so like I found in https://github.com/frostworx/steamtinkerlaunch/issues/530 gamescope has to be the first command in the final launch command as otherwise it can cause crashes.

 I had thought this was fixed as gamescope was being set as the first command but I noticed today that that is not always the case looking here 

[steamtinkerlaunch-launchSteamGame-STARTDEBUG.txt](https://github.com/frostworx/steamtinkerlaunch/files/9472898/steamtinkerlaunch-launchSteamGame-STARTDEBUG.txt)

you can clearly see `obs-gamecapture` was added before gamescope

the strange thing is this seems to be random sometimes it will place gamescope first other times it will place `obs-gamecapture` first.

here is a full log

[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/9472920/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Huh, this sounds like a nasty bug. If it's random we might have to just check before the final launch options are passed and force GameScope to be the first option. Which sounds like a headache.

> the strange thing is this seems to be random sometimes it will place gamescope first other times it will place obs-gamecapture first.

Just to confirm, does this mean if you were to launch the same game, in the same way, over and over, there is just a random chance Gamescope will end up being positioned wrong?

**Comment by zany130** [comment]
I'm not exactly sure what causes it. I was playing my usual game (cold steel 4) and it was working fine the first two launches and then suddenly stopped working (tried several runs about 5). Disabling the OBS capture option allowed the game to launch  and using the trick i found in the other bug report to add a command after gamescope ( so adding 'obs-gamecapture' after the `--` ) continually allowed the game to run ( again tried about 5 times) the options i had set in steamtinkerlaunch stayed the same between all these runs ( other than obs-gamecapture ofc)

EDIT: only thing i can think of is started happening when i switched to launching the game's launcher instead of directly running the game (but it seems to load OBS -gamecapture before gamescope regardless if i load the launcher or the game now.)

**Comment by sonic2kk** [comment]
Crashing may be related to #568, as SA2 also uses a launcher and it crashes. Indeed the concatenation seems wrong but I don't think this should cause crashing. There could be two separate issues at play here, or it could be that when using the launcher the order of the concatenation gets messed up because of #560.

You could try patch/paste the code in yourself from my PR #569, but no pressure :slightly_smiling_face: 

if the issue with your launcher is related, then funny coincidence we noticed around the same time :sweat_smile:

**Comment by zany130** [comment]
Doesn't seem like my issue is related. I just mentioned the launcher as cold steel 4 has 3 options when you hit play on steam 
1. start game
2. launch configurator/launcher
3. load directly into latest save

My theroy (haven't been able to confirm it) is that switching between these can sometimes cause steamtinker launch to add `obs-gamecapture` before `gamescope` which crashes.

All 3 of these launch options work fine with steamtinkerlaunch though individually and don't cause crashes normally unless `obs-gamecapture` is added before gamescope` 


 You can even test this in a terminal by running `obs-gamecapture gamescope vkcube` which will crash versus `gamescope -- obs-gamecapture vkcube` which will not 
 
 Something to note is not every launch command needs to go after gamescope. for example `gamemoderun gamescope vkcube` works fine

**Comment by zany130** [comment]
interestingly it seems `obs-gamecapture` is actually always set before gamescope even on runs that work.
[steamtinkerlaunch-launchSteamGame-STARTDEBUG.txt](https://github.com/frostworx/steamtinkerlaunch/files/9479993/steamtinkerlaunch-launchSteamGame-STARTDEBUG.txt)


 So what seems to be random is whether or not that will cause a crash 🤔 strange then that running `obs-gamecapture gamescope vkcube` will always crash if I run in a terminal
 
 
 EDIT: something I just realizeed is that even though it does not always crash when `obs-gamecapture` is first it WILL always fall to capture the game. (just captures a blank screen)

Meaning it seems like we might need to add a check to make sure the `obs-gamecpature` goes after gamescopes `--`

**Comment by sonic2kk** [comment]
Ah! Yes, almost everything has to go after gamescope except gamemode. For example `mangogud gamescope -- vkcube` will crash, but `gamescope -- mangohud vkcube` won't.

Similarly, `gamescope -- gamemode vkcube` will crash, but `gamemode gamescope -- vkcube` won't crash.

I guess some kind of check would need to be done before launching the game to move `obs-gamecapture` to be inside of gamescope.

**Comment by zany130** [comment]
Yup, what I'm trying to figure out is how steamtinkerlaunch always add's mangohud after game scope. I don't see anywhere in the code a specific check to make sure mangohud (there is a check to enable gamescope if mangoapp is used) is loaded after gamescope it just always is. My theroy from looking at the code is that mangohud is added after gamescope because that the order of the checks are written in the code and the code is runned from top to bottom, but I tried moving `OBSCAP` further down and it did nothing


EDIT: my theroy was correct I was just moving the wrong thing will have a PR shortly
