### ISSUE TITLE
Launch SW:TOR using STL does not work, V.11.0-1

### ISSUE THREAD

**Issue by r-vd-woude** [sonic2kk/steamtinkerlaunch#571]
Launching the game, ''Star Wars: the Old Republic" using steamtinkerlaunch does not work.

Launching it directly from Steam, with not using STL as a compatibility layer, works as expected however.
Proton version does not matter, STL refuses to launch it, while Steam launches it with whichever Proton version.

I attached the log, but I can really see what is wrong with it.
[1286830.log](https://github.com/frostworx/steamtinkerlaunch/files/9476595/1286830.log)

**Comment by sonic2kk** [comment]
Hi! Looking at the log:

```
Fri  2 Sep 09:43:07 CEST 2022 INFO - startGame - ## STL LAUNCH COMMAND: '/usr/bin/gamemoderun /usr/bin/mangohud /home/ronnie/.config/steamtinkerlaunch/proton/custom/GE-Proton7-31/proton waitforexitandrun /home/ronnie/Games/Games/Steam/steamapps/common/Star Wars - The Old Republic/launcher.exe'
```

I see GameMode and MangoHud here. Are these definitely installed in your system and at these paths? You can find out with `which gamemode` and `which mangohud` respectively. Since the game launches fine with Steam but not with STL, I'm wondering if these launch options are potentially the problem.

Also, have you got a custom command set up with SLT? It looks like it's trying to run a command at `/bin/authy`, which seems like a strange path. STL at the very least can't seem to mark it as a Windows executable, so likely even if it does exist at this path, STL can't launch it as it can't launch it with Proton.

```
Fri  2 Sep 09:43:06 CEST 2022 INFO - prepareLaunch - CheckCustomLaunch:
Fri  2 Sep 09:43:06 CEST 2022 INFO - checkCustomLaunch - USECUSTOMCMD is set to '1' - trying to start custom program '/bin/authy'
Fri  2 Sep 09:43:06 CEST 2022 INFO - checkCustomLaunch - FORK_CUSTOMCMD is set to 1 - forking the custom program in background and continue
Fri  2 Sep 09:43:06 CEST 2022 INFO - launchCustomProg - '/bin/authy' found
Fri  2 Sep 09:43:06 CEST 2022 INFO - launchCustomProg - Changed pwd into the custom directory '/bin'
Fri  2 Sep 09:43:06 CEST 2022 INFO - launchCustomProg - '/bin/authy' doesn't seem to be a MS Windows exe - regular start (without further analysing)
Fri  2 Sep 09:43:06 CEST 2022 INFO - launchCustomProg - FORK_CUSTOMCMD is set to 1 - forking the custom program in background and continue
Fri  2 Sep 09:43:06 CEST 2022 INFO - launchCustomProg - Changing pwd into previous directory
```

The program is set to fork, which is why it didn't show up in the final launch command.

If you have this enabled, maybe it's set to the wrong path somehow, and maybe you could try disabling it? Though I'm not sure why a forked program would cause STL to fall over either. Still :smile: (Maybe trying and failing to run that exe causes STL to fall over for some reason)

**Comment by r-vd-woude** [comment]
Hi Sonic! 
Thanks for your response!

Both the paths for gamemode and mangohud are correct!

Authy is not a Windows executable, but a Linux one! In any case, Authy is now the only one that launches, the game does not. Is is a 2FA program I need to log into the launcher, just easy that it launches alongside the game :).

The game did launch with the exactly the same settings for over half a year now.

Will try to disable gamemode, mangohud and the Authy launch, see if it help!

Thanks again!

Edit: /bin/authy is a symlink for /usr/bin/authy, not really sure when or why it was put there. In any case, it launches when called upon from a terminal.

Edit: fixed it, repointed STL to the manghud binary, not it works. Strange.

**Comment by sonic2kk** [comment]
Ah! I'm not sure why I thought it was a Windows executable, for some reason I got it into my head that it ended with `.exe` 😅 Thanks for clearing that up.

The path to Authy seemed off to me but if it launches (and if it worked before) it's probably unrelated.

I'd just like to confirm a few things (not at my PC so I can't double check the log rn):
- "Only custom command" is **unchecked**, right? I don't remember seeing any relevant logging in the logfile.
- Is there any specific order that Authy and the game need to launch? If Authy needs to launch first you can set a forkwait delay, which is a value in seconds to wait before STL tries launching the game. If it's the opposite, you can use the Inject option.
- You mentioned in the beginning of your issue but just to confirm: You're using STL as a Compatibility Tool and not a launch option? 
    - If you are using STL as a launch option, are you using the Steam Client Beta?

I'm not too sure it would have anything useful but in an attempt to cover all bases, could you also attach a Proton log? You can enable it from STL under Proton options I believe. Then if you could run the game without STL and  attach a Proton log, we can compare them and see if there's anything wrong 😄 If a Proton log isn't generated when running with STL, then there is no need.

Thanks!

**Comment by frostworx** [comment]
I'd start with troubleshooting into the `authy` direction as well.
Does the game start correctly when `USECUSTOMCMD` _(and therefore `authy`)_ is disabled?
No offense, but imho every js/nodejs/electron program is a potential bug/issue source.
Apart from that + everything @sonic2kk already asked

**Comment by sonic2kk** [comment]
Hey @Moonl1ghter, sorry for the ping but have you had a chance to debug further? 😃

**Comment by sonic2kk** [comment]
I think there were some changes to how STL handles incoming args from Steam/games. 

Now that v11.11 is out I'd be really interested to know if there has been any change for you. The game is free and fairly light (though quite a big file) so I could also try to help test at some point in the near future.

**Comment by sonic2kk** [comment]
Cannot reproduce with SteamTinkerLaunch v11.11 from git on Arch Linux + KDE Plasma Wayland. I don't have the custom command used in the original issue, but just launching the game with SteamTinkerLaunch v11.11 and Proton 7.0-4 works as expected. I did not go any further than running the launcher for the game (despite being made by EA, it doesn't use Origin - Win :smile:). This works with and without SteamTinkerLaunch.

I don't know if it was broken on v11.0, but it worked for me. @Moonl1ghter it would be great if you could test again :smile:

**Comment by frostworx** [comment]
To be honest I have more patience here for missing feedback, because @Moonl1ghter is polite, but I'd appreciate progress anyway, because I don't like inactive open issues lying around. 😀
