### ISSUE TITLE
gamescope with mangoapp + games with backslash in launch command

### ISSUE THREAD

**Issue by gu1ll0me** [sonic2kk/steamtinkerlaunch#575]
Pyre game have backslash in launch parameters (`..\`) :

```
/home/user/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=462770 -- /games/steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /games/steam/steamapps/common/Proton 7.0/proton waitforexitandrun /games/steam/steamapps/common/Pyre/x64/Pyre.exe /c ..\ /PerfDashWarnings=false /KeepAllSaves=false
```

When enabling mangoapp in game menu, STL [adds double-quote for each launch parameters](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L15518), but the backslash escape the double-quote and the game refuse to launch.

Adding `sed -i "s/\\\/\\\\\\\/" $STLSHM/maprun.sh` after line 15518 solve the problem by doubling the backslash.

**Comment by sonic2kk** [comment]
Nice catch! If you would like you could test this some more with other games, just to ensure it doesn't break anything, and if/when you're confident, you could open a pull request! :smile: (That way you can get direct credit too :wink:)

I had a look at where you said the fix can go and that all looks sane to me. But if you could test with other games, we'd welcome a PR!

**Comment by frostworx** [comment]
Thanks, good find and fix!
I fully agree with @sonic2kk: A few tests if the patch has any negative impacts _(though unlikely)_ and a proper PR would excellent.

**Comment by gu1ll0me** [comment]
I'm not using gamescope+mangoapp on a daily basis because mangoapp doesn't close properly after the game exit, but I will install some more games this week and make a few tests. I will create a PR if there is no problem.

**Comment by frostworx** [comment]
thanks for testing/contributing! take your time!
I don't use mangoapp, but was believing that it is closed _(killed)_ correctly on game exit _(upstream kills it as well iirc)_
does the [Kill Switch](https://github.com/frostworx/steamtinkerlaunch/wiki/Proton-KillSwitch) work at least?

**Comment by gu1ll0me** [comment]
I can't test the kill switch because there is no `KillSwitch` file or folder in `/dev/shm/steamtinkerlaunch/` when I launch a Proton game. To kill `mangoapp` process, I have to use `killall mangoapp` or hit Steam stop button.

**Comment by frostworx** [comment]
`/dev/shm/steamtinkerlaunch/KillSwitch` should be always created in the function `TrayIconExports`.
It always works very reliable for me, so it would be nice to know why it is not created on your system.
It might also be possible that you missed it because it is auto-removed in `closeSTL`

**Comment by frostworx** [comment]
ok, no logs then... *shrug*
edit: or reply

**Comment by gu1ll0me** [comment]
Sorry, I missed your last message and closed the issue too early.

When checking `Use Mangoapp` option in the game menu, the tray icon close right after the game starts. The game is still running but the log show `## GAMESTOP after '0' seconds playtime`. It explains why I had no KillSwitch file in `/dev/shm/steamtinkerlaunch`.

```
mer 14 sep 2022 13:08:10 EDT INFO - startGame - ## GAMESTART HERE ###
mer 14 sep 2022 13:08:10 EDT INFO - restoreOrgVars - Restoring previously cleared Variables
Wed Sep 14 13:08:10 EDT 2022 INFO - startGame - Using mangoapp
Wed Sep 14 13:08:10 EDT 2022 INFO - gameScopeArgs - Using following gamescope arguments: '--'
mer 14 sep 2022 13:08:10 EDT INFO - startGame - Symlink '/home/user/.config/steamtinkerlaunch/logs/gamelaunch/title/SteamWorld Dig 2.log' already exists
Wed Sep 14 13:08:10 EDT 2022 INFO - runMA - ## MANGOAPP GAMESCOPE LAUNCH COMMAND: '/usr/bin/gamescope --'
mer 14 sep 2022 13:08:10 EDT INFO - startGame - ## GAMESTOP after '0' seconds playtime
mer 14 sep 2022 13:08:10 EDT STOP - ######### SteamTinkerLaunch v11.0 #########
mer 14 sep 2022 13:08:10 EDT STOP - ######### CLEANUP #########
mer 14 sep 2022 13:08:10 EDT INFO - closeSTL - closing STL
mer 14 sep 2022 13:08:10 EDT INFO - updateConfigEntry - Emptying 'CUSTOMCMD' for '/home/user/.config/steamtinkerlaunch/default_template.conf'
mer 14 sep 2022 13:08:10 EDT INFO - updateConfigEntry - Option 'CUSTOMCMD' is updated with the new value 'echo' in config 'default_template.conf'
mer 14 sep 2022 13:08:10 EDT INFO - closeSTL - Creating '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
mer 14 sep 2022 13:08:10 EDT INFO - checkPlayTime - The game was not started via 'steamtinkerlaunch' but directly from Steam - skipping Crash Requester
mer 14 sep 2022 13:08:10 EDT INFO - closeSTL - Game 'SteamWorld Dig 2 (571310)' exited - cleaning up custom processes if necessary
mer 14 sep 2022 13:08:10 EDT INFO - closeTrayIcon - Closing TrayIcon '42084'
```

**Comment by frostworx** [comment]
Thanks for the details. I'll look into this glitch when I find the time.

**Comment by gu1ll0me** [comment]
Thanks. I opened a new issue to track this one.
