### ISSUE TITLE
Trying to run ahk script inside the game prefix (SF5)

### ISSUE THREAD

**Issue by zehthales** [sonic2kk/steamtinkerlaunch#577]
Winetricks have autohotkey app inside the app repository and we can install it inside the game's prefix. I'm trying to run a .ahk file with a SOCD cleaning script to see if would affect the game. Adding the command Autohotkey.exe with the argument as the script.ahk name I could see that it was active at the bottom panel on the Linux environment, but no configuration was applied to the game. 

Is it he right way to do it? Probably I'm missing something or else the script would be applied to the games' input.

STL v11 running on Pop Os 22.04

**Comment by zehthales** [comment]
Good new! I solved it by deleting all wine secondary stuff o my computer (just to ensure that the command would come from the games prefix), saving the folder of an already installed autohotkey (so, install it first through winetricks, go the prefix and save a copy of the app folder, then wipe all other wine prefix on you computer) . Copied the folder to the games' prefix, inside the folder Program and Fliesx86 and added the script.ahk inside it. After this, add chose the Autohotkey.exe file from the folder above as custom command and fork the script.ahk as argument. Save and play. 

Chears!

**Comment by sonic2kk** [comment]
Glad you got it solved! Just so you know, if it's a shell script, STL lets you run scripts when a game starts. If it's an executable STL also lets you start custom executable with your game. But you got it solved so it's no big deal really :smile: 

Closing this now :slightly_smiling_face:
