### ISSUE TITLE
Canberra GTK module error

### ISSUE THREAD

**Issue by kormocicsaba** [sonic2kk/steamtinkerlaunch#578]
![image](https://user-images.githubusercontent.com/107996731/188888730-6017265d-b418-4f19-bd69-ca4f84f4c60b.png)

Someone could help me resolve this? I've tried to install this module, but did not succeed.

**Comment by sonic2kk** [comment]
Is this preventing SteamTinkerLaunch from working? I think I've seen this error before (maybe on Steam Deck) but it didn't affect anything.

That looks like Ubuntu as well. There are a few different ways to install STL on Ubuntu, which way did you install it and, related, which version of STL are you using?

**Comment by frostworx** [comment]
this is a gtk warning _(often just verbose and non-fatal)_ triggered by yad. definitely a yad issue at best, but more likely directly gtk related.
you did not provide any useful information, but I'd guess you have to install the corresponding gtk3 module and only installed the gtk2 build.

**Comment by sonic2kk** [comment]
Were you able to get this issue resolved?

**Comment by frostworx** [comment]
Please only open issues in the future, if you're willing to communicate when people try to help you
