### ISSUE TITLE
Steamtinkerlaunch wont Launch Language Error

### ISSUE THREAD

**Issue by taynotfound** [sonic2kk/steamtinkerlaunch#583]
Nothing works and it always gives me this error:

`Do 15. Sep 17:01:27 CEST 2022 ERROR - loadLanguage - ###############################
Do 15. Sep 17:01:27 CEST 2022 ERROR - loadLanguage - No language file could be loaded! For the initial setup at least one file (default english) is required
Do 15. Sep 17:01:27 CEST 2022 ERROR - loadLanguage - You can ether copy a valid file to '/home/tay/.config/steamtinkerlaunch/lang' or '/usr/share/steamtinkerlaunch/lang' or provide an absolute path via command line using the lang= option
Do 15. Sep 17:01:27 CEST 2022 ERROR - loadLanguage - ###############################
`

Idk what the problem is

**Comment by frostworx** [comment]
Elaborate - how was it installed, which command was used, full logs...

**Comment by Random483** [comment]
I had the same issue. It popped up when I tried to run any command with `steamtinkerlaunch`.

I've attached the log file. I found that by editing `~/.config/steamtinkerlaunch/global.conf` so that `STLLANG="englishUK"` instead of just "english" and manually copying the language files into `~/.config/steamtinkerlaunch/lang` it resolved the issue.

Now to update my yad!

[31337.log](https://github.com/frostworx/steamtinkerlaunch/files/9592615/31337.log)

**Comment by sonic2kk** [comment]
If you installed SteamTinkerLaunch manually, that step of adding the language file is required. If you installed via your package manager though or with `sudo make install`, this should've been managed for you.

If you have to update Yad, are you running on Ubuntu? Just curious :smile: 

P.S. It's not on Flathub yet, but ProtonUp-Qt v2.7.3 has SteamTinkerLaunch support and has code specifically to check and set the language appropriately. If you installed manually (which afaik you have to do on Ubuntu if you aren't using Pacstall), this is a better approach.

If you did install via package manager, maybe this is a package management issue.

**Comment by taynotfound** [comment]
> Elaborate - how was it installed, which command was used, full logs...

idk if it even has any logs. Where can i find them?

**Comment by taynotfound** [comment]
> I had the same issue. It popped up when I tried to run any command with `steamtinkerlaunch`.
> 
> I've attached the log file. I found that by editing `~/.config/steamtinkerlaunch/global.conf` so that `STLLANG="englishUK"` instead of just "english" and manually copying the language files into `~/.config/steamtinkerlaunch/lang` it resolved the issue.
> 
> Now to update my yad!
> 
> [31337.log](https://github.com/frostworx/steamtinkerlaunch/files/9592615/31337.log)

Where do i find the Lang Files?

**Comment by sonic2kk** [comment]
> idk if it even has any logs. Where can i find them?

SteamTinkerLaunch stores logs in various places but the most convenient is likely `/dev/shm/steamtinkerlaunch`. The Readme makes note of [SteamTinkerLaunch logging](https://github.com/frostworx/steamtinkerlaunch#logs).

Could you also detail some other things?
- What version of STL are you using?
- How did you install STL?
- What distribution are you using?

> Where do i find the Lang Files?

This will depend on how you installed SteamTinkerLaunch. If you downloaded it manually, it'll be in the `lang` folder of wherever you downloaded STL. They can also be found [on this repository](https://github.com/frostworx/steamtinkerlaunch/tree/master/lang).

**Comment by taynotfound** [comment]
**Version** 11.0
**How installed** I think it was via the Repo itself. I defo used make install
**Distro** Ubuntu

**Logs** https://hastebin.com/camesuqapi.apache

**Comment by taynotfound** [comment]
Okay copying the file helped. Now i got this error: 

`So 18. Sep 00:09:09 CEST 2022 ERROR - checkIntDeps - xdotool not found!
So 18. Sep 00:09:09 CEST 2022 ERROR - checkIntDeps - '' was not found! Check 'steamtinkerlaunch --help' for alternatives and/or read 'https://github.com/frostworx/steamtinkerlaunch/wiki/Yad'
So 18. Sep 00:09:09 CEST 2022 ERROR - checkIntDeps - Yad version '0' is too old. You need to update to at least '7.2'
`

**Comment by taynotfound** [comment]
Okay xdotool is installed now its only yad

**Comment by taynotfound** [comment]
Okay i think i got it done myself

**Comment by sonic2kk** [comment]
Thanks! So you did a manual install with Ubuntu. You have probably gathered as much by now but please make sure you read the [Hard Dependencies section](https://github.com/frostworx/steamtinkerlaunch/wiki/Installation#hard-dependencies) of the Installation wiki page, as not all distros will package all programs needed for STL.

The [Ubuntu wiki notes](https://github.com/frostworx/steamtinkerlaunch/wiki/Ubuntu) that Ubuntu needs various extra dependencies and details how to install Yad. However it should probably note the step about the language files, I will add this now.

**Comment by taynotfound** [comment]
Thank you! It now seems to work completely fine ^^

**Comment by sonic2kk** [comment]
Glad you got it sorted :-) I am in the process of overhauling the Ubuntu wiki on the back of this issue. Closing this issue now, hope you don't mind. Happy tinkering!

**Comment by Random483** [comment]
> If you installed SteamTinkerLaunch manually, that step of adding the language file is required. If you installed via your package manager though or with `sudo make install`, this should've been managed for you.
> 
> If you have to update Yad, are you running on Ubuntu? Just curious :smile: 
> 
> P.S. It's not on Flathub yet, but ProtonUp-Qt v2.7.3 has SteamTinkerLaunch support and has code specifically to check and set the language appropriately. If you installed manually (which afaik you have to do on Ubuntu if you aren't using Pacstall), this is a better approach.
> 
> If you did install via package manager, maybe this is a package management issue.

Good guess. I'm currently trying a few different distros. This install was on mint, though I had a similar experience installing on PopOS. I believe both are Ubuntu based.

I'm currently trialing manjaro, but I'll bare that tip on ProtonUp in mind if I switch back (I quite liked PopOS).

**Comment by sonic2kk** [comment]
> I believe both are Ubuntu based.

Yup, they're both based on Ubuntu! :smile: 

> I'll bare that tip on ProtonUp in mind if I switch back

ProtonUp-Qt should be available for virtually all (relatively standard) distributions, but you might be able to install via the AUR on Manjaro too :smile: That package is actually maintained by Frostworx, the creator of STL.

The Ubuntu wiki has been updated (https://github.com/frostworx/steamtinkerlaunch/wiki/Ubuntu-&-Derivitives) with instructions for the language files, and the Distro-Specific section of the Installation wiki (https://github.com/frostworx/steamtinkerlaunch/wiki/Installation#ubuntu-and-ubuntu-based-distributions-pop_os-linux-mint-etc) has been updated to reflect these steps as well.

Sorry you ran into this issue, but the updated wiki should prevent others from running into this problem as well.
