### ISSUE TITLE
On Steam Deck, differentiate between running in Game Mode and Desktop Mode

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#590]
There have been a few Steam Deck reports now of SteamTinkerLaunch's Main Menu button bar along the bottom being cut off when running in Desktop Mode. From the code I believe this is because SteamTinkerLaunch hardcodes the UI size to 1280x800. This is good for Game Mode but not good for Desktop Mode. A user might use desktop mode for a number of reasons including modding.

Also, I believe SteamTinkerLaunch disables some features like GameScope when running on Steam Deck. This is a good idea for Game Mode but not for Desktop Mode (though a user that would get GameScope setup on Desktop Mode without having to disable the readonly filesystem is probably rare).

I believe there are other things SteamTinkerLaunch does on Deck that might not be desirable in Desktop Mode, but I can't remember them off the top of my head.

I had an idea on how we could potentially amend this. We could try to differentiate between a user on Steam Deck running in Game Mode and Desktop Mode. I think we could do this by checking if GameScope is currently running, or if the Plasma Desktop session isn't currently running, or if there's a better process/set of processes to check on we could do this too. I believe it should be possible to check if we're running in Game Mode this way, and only limit certain features and set the Yad window size in these instances.

Not totally sure how to implement this, but no rush on any kind of implementation. Really just making this issue to get some discussion going :smile:

**Comment by frostworx** [comment]
Thanks for the report! I'll look into it.
Checking for gamescope running is a good idea 👍

**Comment by frostworx** [comment]
The changes that a user is switching from gamemode to desktop mode and back while steamtinkerlaunch is running is probably close to zero, right?
If so, it would make sense to check the current mode only once when launching and not every time while `pollWinRes` is called to save some cpu cycles.
Should be easy to implement _(maybe tomorrow)_

**Comment by sonic2kk** [comment]
Yes, I don't know if it's possible to do this. I believe user processes should close when switching from Desktop Mode to Game Mode (at least in my experience, Firefox and KDE apps close when I switch to Game Mode).

I'm not too familiar with what it does but I'm pretty sure the user is logged out when they switch to Game Mode, afaik its basically GameScope running `steam -steamdeck -gamepadui` in a separate session with no desktop environment. When you switch from Game Mode to Desktop Mode it shows the KDE Plasma login splash screen, which is why I think it logs the user out when switching.

So I don't believe there should be a case, at least not a reasonable one, where a user would switch from one mode to another while STL is running, as I don't think it can stay running.

Checking on launch is all that should be needed :)

**Comment by frostworx** [comment]
I haven't tested the above commit yet, but pushing it is easier than manually overriding on the Steam Deck :)

**Comment by frostworx** [comment]
Hm, seems like the commit above does what it is supposed to do, but it does not change the core problem, that the minimal size of the the main settings window is already too high for the Steam Deck height of 800.

There are several more or less nice possible workarounds:

- hide/crop the game info to save some space when running in Desktop Mode on the Steam Deck
- raise the amount of columns of the settings menu _(on a regular desktop this can be set by pressing `F1` in most of the different steamtinkerlaunch windows btw)_
- make the settings window scrollable _(can't remember I disabled it here though, so maybe it is a specific design problem here 🤔)_
- all of the above 🤓

**Comment by frostworx** [comment]
the above commit
- hides several game info when `SMALLDESK` is `1` _(set when Desktop Mode is used on the Steam Deck, maybe useful later for other devices/resolutions)_
- makes the settings menu scrollable

probably not necessary to increase the columns

**Comment by frostworx** [comment]
*tested* works fine for me
I think it is time for a new minor release shortly :)

**Comment by sonic2kk** [comment]
I hope to test on my Deck later on too :smile: thank you for the work on this! Once I've gotten to test I think we can close this issue

**Comment by sonic2kk** [comment]
Just tested, looks great on my Deck, thank you! The UI fits in desktop mode without any cutoff and scrolling works perfectly when the window size shrinks. Closing this issue now :smile:

**Comment by frostworx** [comment]
thanks for testing and confirming!👍
