### ISSUE TITLE
[Suggestion] Use native implementation of MO2 from rockerbacon github

### ISSUE THREAD

**Issue by ShneekeyTheLost** [sonic2kk/steamtinkerlaunch#596]
After having updated my distro and gotten Yad to install (had to manually install, the appimage was throwing some kind of xapp-gtk3-module error that has to do with Mint changing its implementation of xapp in Mint 21), I noticed that when installing MO2 that you are using the .exe version from the main repo. 

User rockerbacon has a github with a native implementation fork of MO2. At the moment, it seems primarily focused on bethesda games. It works by injecting itself so when you click on the modded game's run button in steam, instead of directly running the game it instead runs MO2 which can then be used to launch the game itself. Much like how steamtinkerlaunch does, come to think of it. 

Github can be found: [here](https://github.com/rockerbacon/modorganizer2-linux-installer)

Quite frankly, the less we have to fiddle with compatibility layers, the smoother things will go. I've been using this version of MO2 to run heavily modded Fallout 3 and New Vegas (I use OpenMW for Morrowind) pretty easily. Still haven't managed to get TTW to work (that's my next major project). 

Feel free to give it a peek and see if it is worth implementing here.

**Comment by frostworx** [comment]
Thanks for the suggestion, but this doesn't seem to be a native implementation of MO2, but a collection of scripts for using the regular windows MO2. So basically something similar `steamtinkerlaunch` already has, but with other dependencies and of course not intengreated into steamtinkerlaunch. If anyone wants to to contribute a PR we should talk before in detail how to proceed.

**Comment by sonic2kk** [comment]
I think the linked project depends on Protontricks from what I read and indeed it doesn't seem like a native MO2 release.

I'm not sure what advantage using that project would have over what STL does, but I'm not saying there _isn't_ any benefit.

Could you explain what would make using this user's set of scripts for MO2 better than what STL currently does? I've used MO2 to mod Skyrim SE, Oblivion and Fallout: New Vegas without any real issue (had a couple of hiccups in the past that I haven't encountered in a while).

I have no doubt that this project works but STL also works currently, so I'd just like to know the benefits and what we're potentially currently missing out on 😃

**Comment by ShneekeyTheLost** [comment]
Had to use Timeshift to revert OS upgrade due to broken packages that haven't been updated on Mint yet. As a result, no longer on a compatible OS with STL. However, it does seem like you're doing most of what his is doing. Had troubles navigating STL and getting MO2 to play nicely with my already installed F:NV, but I wasn't able to do much tinkering with it. Specifically, running MO2 through STL caused it to think that Steam wasn't installed, and then caused it to think that F:NV wasn't installed. I wasn't able to do much troubleshooting before I had to revert. 

I suspect part of my problem was that I already was using his script to run MO2, so you had recursive MO2 instances going, one from STL then another popping up from his injection. Next time I'll just wipe it clean and start fresh. 

Maybe once Mint 21 finishes dealing with broken mono and xapp dependencies, I'll give it another shot.

**Comment by sonic2kk** [comment]
That sucks about Mint, I'm sorry to hear that!

> Specifically, running MO2 through STL caused it to think that Steam wasn't installed

Someone reported this in another issue with another game, ~~but the issue seemed like it just went away for them. I've never had this so I'm not sure what causes it, sorry.~~ and they fixed it by using MO2 in Game Mode. See this part of the reply in #586:

> As for Steam connectivity, I now launch using the Steam Collection method and not through the MO2 Extra Button

Using the MO2 Steam Collection just defaults to those games using MO2 in GUI Game Mode. Please make sure if you try again that you've read the SteamTinkerLaunch Wiki page for how to use MO2 with STL, as Game Mode is what you'll want to use when you try to launch your games.

When in Standalone Mode, MO2 is run through a separate Wine prefix in `~/.config/steamtinkerlaunch/mo2/compatdata`. This might be why it doesn't find Steam in Standalone Mode, if you were using this.

> Had troubles navigating STL and getting MO2 to play nicely with my already installed F:NV

Yeah, this is to be expected. You'll get the same problem if you try to use Vortex and MO2, on Windows or Linux (it might even end up worse!). I had a similar problem back in the days when I used Windows, where I was using FOMM and saw a suggestion to use MO2. Installed it and New Vegas kept crashing. Then I installed what was Nexus Mod Manager back then and my entire mod install broke.

When modding, a good rule of thumb is to stick to one mod manager, and if you ever have to use two, launch one through MO2 or Vortex (e.g., WyreBash for Oblivion, though MO2 is pretty much entirely compatible with Oblivion these days).

MO2 lets you generate portable instances but some New Vegas mods aren't portable, specifically some texture and model mods will be "hard" installed and it means you have to keep using that installation of MO2. Not anything specific to Linux in my experience, FOMM did something similar back in the day. I guess  it's just not all mods play nice with the virtual filesystem.
