### ISSUE TITLE
github download changed

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#597]
The github internal download urls changed, so multiple download parts in `steamtinkerlaunch` need to be rewritten.
When done `steamtinkerlaunch` will _(likely)_ require `jq` as hard dependency _(until now it was optional)_ because the github api will be used.

**Comment by sonic2kk** [comment]
The GitHub API does have a rate limit per user, but I believe it's fairly high. I think even if a user downloaded every available tool with STL they still wouldn't hit it. You can avoid this by passing a GitHub access token to the API call in the header ('`Authorization`'). 

Maybe as a "precaution" there could be an option to pass an access token to SteamTinkerLaunch? Either via command line and/or in the Global menu 😃

**Comment by frostworx** [comment]
good hint, thanks! didn't know that.
yeah using an optional token probably makes sense. Need to look into it.
seems like
https://github.com/settings/tokens
is the url the user has to visit for getting a token

edit:
the wget syntax from https://superuser.com/a/810160
is probably still valid
