### ISSUE TITLE
SteamTinkerLaunch doesn't add `GAMEID` for native Linux games' meta files

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#604]
Partially related to discussion in #550 

When using SteamTinkerLaunch as a launch option for native Linux games, it seems like the file in `$GEMETA` (`~/.config/steamtinkerlaunch/meta/id/general/<app_id>.conf`) does not get a `GAMEID` written out to it. From investigating the files I have it seems like Proton games always have `GAMEID` but native Linux games do not.

This is namely a problem for using the `getIDFromTitle` function, which is called when running `steamtinkerlaunch getid "Game Name"`. Native games seem to always fail (Portal, Portal 2, Factorio) *unless* they have been ran with Proton before (I ran Half-Life with Portal before and it seems to have this field). Proton games *always* seem to have this field, and usually  `getIDFromTitle` works correctly for these games.

Also, these meta files for native Linux games do not get symlinked to the `title` folder.

I had a look around to see where and how this file is generated to see if I could fix it but I couldn't figure it out (that's where all my PRs came from, I was fiddling around in this part of the code :sweat_smile:)

Below is a log from running native Portal, where I commented out the `400.conf` meta file so STL would re-generate it. From looking at it, it does not even complain that `GAMEID` is missing.

[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/9637815/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
Sorry, still drinking my first coffee and I'm a bit lazy at the moment 😀
[via](https://github.com/frostworx/steamtinkerlaunch/issues/605#issuecomment-1256895858):

`getIDFromTitle` is just a fragile little helper one liner which is barely used in the "active" code
_(basically [my answer over here](https://github.com/frostworx/steamtinkerlaunch/pull/603#issuecomment-1256890258) matches here as well 😀)_
You're right, of course it could be improved a lot, but I'm uncertain if it is even worth the effort.
It would be much easier to simply remove the litle function and nost many people would miss it 😀

**Comment by sonic2kk** [comment]
Now that the issue with the function is resolved I might try taking a look at fixing this. STL gets the AppID correctly for native games so it should just be a matter of writing it out to the meta file. I'll have a look at the logs to and figure out why it writes for proton games but not native games.

Side note, AppIDs for meta files for Non-Steam games aren't written, Proton or Native. Once I know more about how those AppIDs actually work this can be looked into more, just mentioning that I discovered this in my investigation 🔍

**Comment by frostworx** [comment]
have fun 😀

**Comment by sonic2kk** [comment]
So I really just caught on earlier today that #607 will actually work for native Linux games... :woman_facepalming: I feel a little silly now, I just realised that because the implementation in the PR gets the AppID from the config file when `NAME`/`GAMENAME` matches, that this will work for native Linux games.

It would still be nice if STL wrote this out so I'll still investigate this (even just for my own curiosity) but this is probably so inconsequential that the issue can be closed. I am *very* doubtful anyone will ever even realise the AppID is missing for native games, since both `getid` and `gettitle` work. The core """problem""" of this issue (if you can even call it that anymore) is still *technically* correct, STL doesn't wwrite out `GAMEID`, but the actual effect from this problem doesn't exist anymore.

I'm going to close this issue as I don't think this issue will actually affect anyone in any meaningful way, and if I can find a way to fix it I'll still open a PR for review but it'll really only add parity between game files for Proton and Native games.
