### ISSUE TITLE
Some Proton games do not return correct AppID when using getIDFromTitle

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#605]
See also some discussion in #550

`getIDFromTitle` fails for some Proton games (should always fail for native Linux games currently if they've never been ran with Proton before, see #604). For some reason, with some  It seems like this happens when the order of `GAMEID`, `GAMENAME` and `GAMEARCH` in the game meta file is "incorrect" or not what STL is expecting at least.

I tested three games: NieR:Automata, Oblivion and Yakuza 0. Only the last one returned a correct AppID, Automata and Oblivion both returned their `GAMEARCH`.  When I modified the meta config for Automata and Oblivion to have the following order:

```
GAMEID=
GAMENAME=
GAMEARCH=
```

They started to return the correct AppID. It didn't matter where they were in the file, as long as they were together and in this order. This is how Yakuza 0 ordered the variables, so I decided to mirror how that config did it and that's how I discovered the fix.

I wondered how this would work for a game that only has numbers for its name like [21](https://store.steampowered.com/app/938520/Twenty_One/) (store page says "Twenty One", game library says "21"), so I tested it. STL didn't even write the `GAMENAME` for this game (not a big deal since [it doesn't work with Proton](https://github.com/ValveSoftware/Proton/issues/5942)), so I wrote it in myself as just `GAMENAME="21"`. Running `steamtinkerlaunch getid "21"` worked perfectly fine though, again with the order `GAMEID`, `GAMENAME` and `GAMEARCH`.

So it seems like STL is failing here for these games because those 3 variables have to be in a specific order. They can be anywhere in the file it seems like, as long as they are together.

EDIT: Semi-related, it would be nice if we could also search for games based on their `NAME` as well as `GAMENAME`, for example being able to search `DOOM Eternal` instead of `DOOMEternal` and having the ID come back. Maybe this is next part is wishlisty but it would be very cool if this was case insensitive, so `doom eternal` also worked, but not anything too important :smiley:

**Comment by frostworx** [comment]
`getIDFromTitle` is just a fragile little helper one liner which is barely used in the "active" code
_(basically [my answer over here](https://github.com/frostworx/steamtinkerlaunch/pull/603#issuecomment-1256890258) matches here as well 😀)_
You're right, of course it could be improved a lot, but I'm uncertain if it is even worth the effort.
It would be much easier to simply remove the litle function and nost many people would miss it 😀

**Comment by sonic2kk** [comment]
It would be easier to remove it... But sometimes I like a challenge :nerd_face: 

I'm making an attempt at fixing it, seems to mostly work for now. I'll get a PR up once I iron it out a bit more. It doesn't fix the native Linux game issue but that's for a different time :smiley:
