### ISSUE TITLE
Unable to run custom command

### ISSUE THREAD

**Issue by mmbossoni** [sonic2kk/steamtinkerlaunch#613]
## System Information
- SteamTinkerLaunch version: 11.11
- Distribution: Arch Linux
- Installation Method: aur

## Issue Description
I've set a custom command to run with Hades game, but it isn't working. It used to work before, but from logs it seems it is not finding my proton version or something
I use steamtinkerlaunch by setting it as launch options on steam, not as a compat tool.

## Logs
[ProtonCSV.txt](https://github.com/frostworx/steamtinkerlaunch/files/9693626/ProtonCSV.txt)

[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/9693622/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
>  I use steamtinkerlaunch by setting it as launch options on steam, not as a compat tool.

Using SteamTinkerLaunch as a launch option is not supported for Proton. You should be using SteamTinkerLaunch as a compatibility tool. The launch option is meant to be used for native Linux games, which to my knowledge Hades is not. 

> from logs it seems it is not finding my proton version or something

I agree with you, check which version of Proton the game is using in the Game Menu, whilst also making sure you are using SteamTinkerLaunch as a compatibility tool. If all looks correct, try deleting `/dev/shm/steamtinkerlaunch` and running your game again.

As for why this was working previously, I believe the launch command has changed. Looking at this part of your log:

```
dom 02 out 2022 18:21:39 -03 INFO - prepareLaunch - CheckCustomLaunch:
dom 02 out 2022 18:21:39 -03 INFO - checkCustomLaunch - USECUSTOMCMD is set to '1' - trying to start custom program '/home/marcelo/HadesTrainer.exe'
dom 02 out 2022 18:21:39 -03 INFO - checkCustomLaunch - FORK_CUSTOMCMD is set to 0 - starting the custom program regularly
dom 02 out 2022 18:21:39 -03 INFO - launchCustomProg - '/home/marcelo/HadesTrainer.exe' not found - searching in gamedir
dom 02 out 2022 18:21:39 -03 INFO - launchCustomProg - '/home/marcelo/HadesTrainer.exe' also not in '/mnt/games/marcelo/steam/steamapps/common/Hades//home/marcelo/HadesTrainer.exe' - checking if absolute path was provided
dom 02 out 2022 18:21:39 -03 INFO - launchCustomProg - '/home/marcelo/HadesTrainer.exe' is absolute path
dom 02 out 2022 18:21:39 -03 INFO - launchCustomProg - Changed pwd into the custom directory '/home/marcelo'
dom 02 out 2022 18:21:39 -03 INFO - launchCustomProg - '/home/marcelo/HadesTrainer.exe' seems to be a MS Windows program - starting through proton
dom 02 out 2022 18:21:39 -03 INFO - launchCustomProg - '/home/marcelo/HadesTrainer.exe' seems to be a MS gui program - starting regularly
dom 02 out 2022 18:21:39 -03 INFO - setRunProtonFromUseProton - Setting ORUNPROTON to '/home/marcelo/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/marcelo/.local/share/Steam/compatibilitytools.d/latest/proton'
dom 02 out 2022 18:21:39 -03 WARN - extProtonRun - 'proton-unknown-919' seems outdated as the executable /home/marcelo/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/marcelo/.local/share/Steam/compatibilitytools.d/latest/proton wasn't found
dom 02 out 2022 18:21:39 -03 INFO - fixProtonVersionMismatch - Skipping function for 'proton-unknown' Proton version
dom 02 out 2022 18:21:39 -03 INFO - extProtonRun - Continuing with RUNPROTON='/home/marcelo/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/marcelo/.local/share/Steam/compatibilitytools.d/latest/proton'
dom 02 out 2022 18:21:39 -03 ERROR - extProtonRun - When this error occurs, probably the configured Proton (or a similar) version is no longer available.
dom 02 out 2022 18:21:39 -03 ERROR - extProtonRun - Because the RUNPROTON '/home/marcelo/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/marcelo/.local/share/Steam/compatibilitytools.d/latest/proton' isn't ready here yet - please open an issue when you made sure it is set to an existing one and the error persists
```

SteamTinkerLaunch is correctly seeing your launch option, and trying to launch it with your game. It correctly finds the directory of the exe (as far as I can tell it's correct anyway), but then there are two problems:

1. As the logs and yourself pointed out, it's not seeing the right Proton version. However using the launch option you might not even be able to set a Proton version and if you can, you might run into the second point
2. The launch command is now prefixed with `/home/marcelo/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- ` when using STL as a launch option, which is a change I believe was previously in the Steam Beta but which could now be in a stable release. Essentially this is trying to run games with the Steam Linux Runtime (a tool by Valve for native Linux games) which could cause failure, either for the custom command, for Hades or both.

So try using STL as a compatibility tool (run `steamtinkerlaunch compat add` if it's not available as a compat tool and restart Steam), then try setting your Proton version by going to the Game Menu, then try launching your game.

**Comment by mmbossoni** [comment]
Using as a compat tool worked

**Comment by sonic2kk** [comment]
Glad to hear it. In case you missed it, this is documented [on the Readme](https://github.com/frostworx/steamtinkerlaunch#general-usage) :slightly_smiling_face:

**Comment by mmbossoni** [comment]
Just a minor comment.
I've read through readme and maybe it need an update to make it clear it is unsupported. Right now it says

"Using SteamTinkerLaunch as a [compatibility tool](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Compatibility-Tool) is the preferred way of using it with Proton games"

So, it says preferred, not "only way". 
I understand that it was caused by a recent steam update (because it used to work by using it as a custom command).

**Comment by sonic2kk** [comment]
Ah, fair point, though "preferred" was intended to imply "the way that should always work" 😃 It's also noted that the launch option is specifically available for native games and that option doesn't mention Proton games. But I can still understand the confusion.

You're indeed correct though, it was previously possible to use SteamTinkerLaunch as a launch option for Proton games even if that is not how it should've been used. It seems like a recent Steam update changed how arguments are passed and so STL is affected.

It's _probably_ still possible to use STL as a launch option for Proton games if you're using a native Linux custom command with "Only custom command" selected, e.g. running the RuneLite AppImage to play OldSchool RuneScape using a native Linux client. But in most cases you should use the compatibility tool instead of the launch option. I'll have to think of a way to word this in the Readme as this is a valid use-case but likely an uncommon one.

I'll try get a PR up to amend the Readme later today. There are a couple of other areas I noticed that need amended (the Flatpak note directly under it is outdated now as well).

Thanks for the feedback!
