### ISSUE TITLE
Wine FSR removed from upstream GE-Proton

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#617]
As of [GE-Proton7-36](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton7-36), the FSR patches were removed from GE-Proton.

>Due to this commit in upstream proton --
> https://github.com/ValveSoftware/wine/commit/7c5306e3b834a29b66c6d4dc6a1bb901a9ec82c9
> 
> The FSR patches had to be disabled.
> 
> The commit is important because it fixes some problems that were happening with winevulkan, but unfortunately it also patches in a lot of components that were already part of the FSR patch. The problem is that the commit has much of the same contents as the FSR patch, but the FSR patch has the FSR bits all mixed in and its not within my know how to rebase.

 They might still be present in Proton-tkg but they might not be present for long since that Proton commit seems to break the parts of the Wine fshack that the FSR patch touches. Unless Tkg or others go to the effort of maintaining the patch, Wine FSR will not be available in Wine/Proton flavours that adopt this patch.

I'm not sure how this will affect Wine but since this touches Winevulkan it could have a chance of being upstreamed, and so the Wine FSR functionality that SteamTinkerLaunch exposes might become useless. Making this issue to bring attention to this just in case in future we need to remove this feature from STL :slightly_smiling_face:

**Comment by frostworx** [comment]
Thanks for the heads up 👍

**Comment by sonic2kk** [comment]
Upstream rebased and added back FSR patches, this should be irrelevant now 😃

**Comment by frostworx** [comment]
n1
