### ISSUE TITLE
Unable to download nxm links with Mod Organizer 2

### ISSUE THREAD

**Issue by KBouder** [sonic2kk/steamtinkerlaunch#623]
## System Information
- SteamTinkerLaunch version: v11.11
- Distribution: Manjaro KDE
- Installation Method: System-wide Manual Install

## Issue Description
When I try to download a mod off of the Nexus, it asks for an application to associate nxm links with. Selecting ModOrganizer-steamtinkerlaunch-dl.desktop does nothing. I am running MO2 in GameMode. I have tried Firefox (Official Repository), Firefox (Flatpak), and Google Chrome (Flatpak) and neither of them have worked. I've also tried setting the .desktop file as an executable. The game I'm attempting to mod is Skyrim Special Edition. Linking Nexus Mods Account to MO2 worked just fine on all 3 browsers. I followed the troubleshooting steps listed [here](https://github.com/frostworx/steamtinkerlaunch/wiki/Mod-Organizer-2#mod-manager-button-on-nexus-mods-isnt-working), I've also browsed previously opened issues and have not been able to figure anything out from those.

I've been scratching my head at this for the past few hours? Let me know if there's more information I could provide.

### Steam Tinker Deck Logs
[489830.log](https://github.com/frostworx/steamtinkerlaunch/files/9723473/489830.log)
[31337.log](https://github.com/frostworx/steamtinkerlaunch/files/9723474/31337.log) (Curiously this log seems to not generate at all sometimes, if I'm understanding right this may be for running Mod Organizer 2 in Standalone...which shouldn't happen at all when launching the game through GameMode with the MO2 GUI flag set)

[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/9723673/steamtinkerlaunch.log) (Another log for good measure)

### Mod Organizer 2 Logs
[mo_interface.log](https://github.com/frostworx/steamtinkerlaunch/files/9723521/mo_interface.log)
[nxmhandler.log](https://github.com/frostworx/steamtinkerlaunch/files/9723522/nxmhandler.log)

[ModOrganizer-steamtinkerlaunch-dl.zip](https://github.com/frostworx/steamtinkerlaunch/files/9723600/ModOrganizer-steamtinkerlaunch-dl.zip)

**Comment by KBouder** [comment]
Okay, I found something weird out. If I launch Mod Organizer 2 through stl (both Standalone and GameMode) download links do not work. If I have Mod Organizer closed and I click a download link, it launches and downloads work. Isn't that the exact opposite of the way it should be?

**Comment by sonic2kk** [comment]
Hi! Thanks for the very detailed bug report (and for reading the wiki!), it is very helpful :-)

Just on your note:

> ...which shouldn't happen at all when launching the game through GameMode with the MO2 GUI flag set

This is true, but remember to launch MO2 by pressing the "Play" button to use Game Mode as well. If you just use the extra button on the Main Menu, it will just launch MO2 in Standalone Mode. The GUI flag is for launching with the Play button. You might already be doing this, I  haven't dug fully through your logs yet but I wanted to make this distinction juuust in case 😃

Just had a **VERY** quick glance at your log `489830.log` so sorry if this is wrong but I noticed:
```
startGame - ## ORIGINAL INCOMING LAUNCH COMMAND: '/home/kyleb/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=489830 -- /home/kyleb/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /home/kyleb/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /mnt/games/SteamLibrary/steamapps/common/Proton 7.0/proton waitforexitandrun /mnt/ssd/SteamLibrary/steamapps/common/Skyrim Special Edition/SkyrimSELauncher.exe'
```

Don't have time to dig in too deep yet but are you using SteamTinkerLaunch as a launch option for your game by any chance? This shouldn't necessarily cause problems in this specific instance with MO2 but if you are using as a launch option, remember that you should use STL as a compatibility tool for Proton games, and as a launch option only for native Linux games.

Typically I've seen this problem arise when running in Standalone Mode Vs Game Mode (Game Mode always works for me). But there is some work going on around potentially refactoring how MO2 works in newer versions of STL. It's unclear yet to my understanding what causes this in Standalone Mode and why it works in Game Mode, but soon enough for technical reasons (DotNet winetrick is no longer required for MO2 where historically it was) there could be some changes/improvements.

Hope there's something useful here

**Comment by sonic2kk** [comment]
> Okay, I found something weird out. If I launch Mod Organizer 2 through stl (both Standalone and GameMode) download links do not work. If I have Mod Organizer closed and I click a download link, it launches and downloads work. Isn't that the exact opposite of the way it should be?

Hmm, have you ever installed MO2 before outside of STL?  Just wondering if this is definitely the STL MO2 that's launching.

Definitely an interesting problem, I will have to test again on my laptop. Last time I tested though it all worked in Game Mode but not in Standalone Mode.

**Comment by KBouder** [comment]
I understand, I know the difference between launching it in GameMode and Standalone, I was simply trying every single situation to see what works and what doesn't. I am in fact using the command line to launch stl. I remember trying to add it via commandline but was having issues, then my whole OS kinda crashed (pretty sure that's unrelated)...and yep that was exactly the problem. All is working now, ran steamtinkerlaunch compat add via command line, restarted Steam, and now it works perfectly fine. Apologies, I got a little distracted during the installation!

**Comment by sonic2kk** [comment]
Oh no worries! I'm honestly really glad it's resolved. Had a couple of issues with Manjaro myself in the past. Glad to know you understood the difference too, I've personally went to lengths to try and make that as clear in the docs as I could too :-)

Happy modding! If you run into any issues with mods that you're able to fix (e.g. a certain mod needs X flag or you need to install Y winetrick to get this Skyrim mod tool running) please do report back and let us know! That's not to say you will have issues, it's just that if you do and you fix it then having that knowledge documented would be awesome!

**Comment by KBouder** [comment]
I have some experience doing that on the Steam Deck (which I had to send back to Valve for service...sad...) It should be fun to mess around with!

**Comment by KBouder** [comment]
I'm reopening this because I am having a similar issue with my Steam Deck. Although this time no nxmhandler.log seems to be generated.

Edit: I lied
[nxmhandler.log](https://github.com/sonic2kk/steamtinkerlaunch/files/9891349/nxmhandler.log)
Game Launch:
[489830.log](https://github.com/sonic2kk/steamtinkerlaunch/files/9891366/489830.log)
Other logs:
[489830.log](https://github.com/sonic2kk/steamtinkerlaunch/files/9891388/489830.log)
[31337.log](https://github.com/sonic2kk/steamtinkerlaunch/files/9891390/31337.log)

[ModOrganizer-steamtinkerlaunch-dl.zip](https://github.com/sonic2kk/steamtinkerlaunch/files/9891402/ModOrganizer-steamtinkerlaunch-dl.zip)

I didn't see anything out of the ordinary reading through these. Nothing seems to happen when i click a download link on the Nexus. I am using 11.11 like my other machine,  this one is just running SteamOS (Which is very similar to Manjaro KDE)

**Comment by sonic2kk** [comment]
It's unrelated to your issue but you shouldn't be running v11.11. This isn't user error, but for some reason STL seems like it hasn't updated to the latest version for you. Did you install with ProtonUp-Qt by any chance? If so, try opening a terminal and going to `~/stl/prefix` and running `./steamtinkerlaunch`. This should update you to the latest version, I'm not sure why the auto-updating didn't work for you. I don't think it's user-error though.

The log doesn't have the "Seems like we have a Steam Deck here" line for some reason. It's like v11.11 doesn't see that it's a Steam Deck on the initial run, so it doesn't run `steamdedeckt`... Weird...

<hr>

However, regardless, I don't think we can do anything about this until the mo2-overhaul branch is working. Plenty of other users have already reported that NXM links are sometimes not working on Steam Deck. For now the only advice I can give is that make sure you're running MO2 in MO2 Game Mode (not Steam Deck Game Mode - unfortunate naming). From your logs it looks like you are running in Game Mode, though.

The only other thing I can think of is that this was broken in a Wine update. You're using GE-Proton7-37 here, could you try with GE-Proton7-20 and see if that works?

**Comment by KBouder** [comment]
I did install through ProtonUp-Qt. Is that not recommended?

Output
>Fri Oct 28 04:11:40 PM EDT 2022 SKIP - CompatTool - Nothing to do the '/home/deck/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/steamtinkerlaunch' symlink still points to '/home/deck/stl/prefix/steamtinkerlaunch'
Fri Oct 28 04:11:41 PM EDT 2022 INFO - main - No arguments provided. See 'steamtinkerlaunch --help' for possible command line parameters

And it still remains on 11.11

**Comment by sonic2kk** [comment]
> I did install through ProtonUp-Qt. Is that not recommended?

No no it's fine, I was just wondering because a couple of other users had issues auto-updating when they installed with ProtonUp-Qt.

Hmm, so from all of this I have a feeling that it's not that ProtonUp-Qt is broken, but that I am being silly with how I thought the installation worked through ProtonUp-Qt. 

From that folder again in terminal, can you run `git status`? I have a feeling you'll get a message telling you that this isn't a git repo... Which is intended, since it's fetching only the major release and not cloning from Git.

I think when ProtonUp-Qt downloads STL it actually does download the major version, and since it doesn't have any git files, it can't do the updates.

However that still doesn't explain why your logs don't show `steamdedeckt` being called. Other parts of the code correctly see that STL is running on Steam Deck, it mentions the skip of the Yad version check. Not sure what's going on there but maybe it's not too important :sweat_smile: 

<hr>

For now, my recommendation would be to do two things:
- Install STL manually from git with `git clone https://github.com/sonic2kk/steamtinkerlaunch.git`, then run the downloaded script. This will update STL to the latest git for you. This is possible with ProtonUp-Qt but since there are some pending improvements to be made, it might be more straightforward to just do this manually (double clicking and executing the script is enough to get STL to install on Steam Deck)
- Try using MO2 with an older GE-Proton version, like GE-Proton7-20. That's what I'm currently using on my PC and the NXM link handling works when running in Game Mode.

If neither of those two things help, you might just have to wait until the mo2-overhaul branch is merged, though there is no guarantee that this will work. If that's the case, just download mods manually - That's also imo the preferable method anyway, though on rare occasion it's handy to be able to use the Nexus mods button, so I would like to see this working. There's just not a whole lot we can do if this broke in a Wine update, which I suspect it has if the older GE-Proton version works for you.

<hr>

If the older GE-Proton version works, I'll close this and focus on #637 which reports a similar issue.

**Comment by KBouder** [comment]
Yeah the git status command did as expected. First I want to try GE-Proton7-20, although it does not appear in the dropdown on Steam Tinker Launch. It is however selectable within Steam.

Edit: Had to delete shm. My bad.

**Comment by sonic2kk** [comment]
> Yeah the git status command did as expected

Tinkerer's intuition :wink: 

>  First I want to try GE-Proton7-20, although it does not appear in the dropdown on Steam Tinker Launch. It is however selectable within Steam

Hmm, try removing `/dev/shm/steamtinkerlaunch`, restarting Steam and seeing if it shows up then.

**Comment by KBouder** [comment]
> > First I want to try GE-Proton7-20, although it does not appear in the dropdown on Steam Tinker Launch. It is however selectable within Steam
> 
> Hmm, try removing `/dev/shm/steamtinkerlaunch`, restarting Steam and seeing if it shows up then.

Thank you, nxm links did not work using this method. Trying a clean install from git.

This did not seem to work either, although, it did successfully auto update on first launch.

**Comment by sonic2kk** [comment]
Hmm, I'm not sure why they're not working then I'm sorry to say. But since this issue is already reported, would it be fine to close this in favour of #637 to avoid having duplicate issues open? I know yours came first but the other issue covers Vortex and MO2, and is specifically about Steam Deck when this original issue was not :-)

**Comment by KBouder** [comment]
Yeah go ahead. I figured I would just open this one up again instead of making a new issue (cuts down on clutter). Turns out someone else already did exactly that 😂
