### ISSUE TITLE
⚠ Project lead change

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#632]
It is no easy step, but I finally decided to retire as project lead from steamtinkerlaunch and hand it over to @sonic2kk.

It was fun to create it, and I'm happy to have reached 1k stars with a bash script for a niche-niche.
Thanks to all who contributed in one or another way, and please help @sonic2kk wherever possible.

The reddit sub will be closed shortly, as @sonic2kk uses the platform even less than me _(and I already do not really use it 🤓)_.
For any problems, suggestions and contributions you might have, please use the [issue tracker](https://github.com/frostworx/steamtinkerlaunch/issues) _(which was the preferred way already before)_

Have at least as much fun with maintaining as I had, @sonic2kk 🦋
and Happy gaming and tinkering, all!
Peace out,
frostworx

**Comment by sonic2kk** [comment]
Thanks @frostworx for creating this awesome project, and enjoy retirement :nerd_face: It was great discussing this over emails the last couple of days and I'm really happy I can take over and help keep the project going :heart: I've had a ton of fun contributing and I'll do my best to keep it going.

Sorry to everyone who might've used the subreddit, I'm not big on social media and simply cannot maintain it - and a subreddit without a moderator is asking for trouble :sweat_smile:

I still have a few ideas I planned to contribute (with one even mid-development that I should be ready to share soon!) so I plan to keep active development on my end, as well as answering issues. I plan to act the same way I usually do, but now I'll do my best to contribute features and fixes directly.

On top of my own development efforts, I hope the community still feels free to contribute PRs and ideas! I don't bite so please feel free to keep getting involved! Issues and bug reports are welcome. Let's keep SteamTinkerLaunch a community effort :smile: 

I recently started a full-time job so I'll be most active after work / weekends (if I'm not busy playing Cookie Clicker). But I'll be keeping an eye on the issues as much as possible.

Thanks to all users and contributors, and here's to the future of SteamTinkerLaunch! :partying_face:

**Comment by DavidoTek** [comment]
It was great to see how well the project developed in the last years. I'm positive this will continue under the new lead and Steam Tinker Launch will outdo itself more than ever.

Thank you for your great work @frostworx and @sonic2kk !

**Comment by frostworx** [comment]
fyi: just set the reddit sub to private, so it is officially dead but can't be hijacked

**Comment by frostworx** [comment]
_/me tips hat and closes here_
