### ISSUE TITLE
Custom Wine version download may be broken

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#633]
## System Information
- SteamTinkerLaunch version: v11.12.20221020
- Distribution: SteamOS
- Installation Method: Manual

## Issue Description
Just forwarding a report I saw from a few days ago on Reddit about the Wine downloading potentially being broken: https://www.reddit.com/r/SteamTinkerLaunch/comments/y1ssax/set_up_steam_tinker_launch_on_my_steam_deck_to/

As the subreddit will be closed soon, I wanted to forward this bug report on. Might be a similar fix as to what was used for the MO2/Vortex fixes. Will take a look in the near-ish future.

## Logs
N/A :-)

**Comment by frostworx** [comment]
it is already fixed in the mo2 branch

**Comment by sonic2kk** [comment]
Ah awesome, thanks! Closing then :-)
