### ISSUE TITLE
Clickable/Usable Area Bug in Steam Deck GameMode

### ISSUE THREAD

**Issue by SentaiBrad** [sonic2kk/steamtinkerlaunch#640]
## System Information
- SteamTinkerLaunch version: v11.12.20221021-2
- Distribution: SteamOS - In GameMode Only
- Installation Method: ProtonUp-Qt

## Issue Description
Tonight, while testing a bunch of stuff, I came across a scaling and clickable user area while in GameMode. I had a mouse plugged into the Deck so it could be seen visually, but it also affects users using touch. Gamepad Control from the Deck still works.
 
Only in STL menu's does the cursor not go down all the way. The picture with the STL menu shows how far down it will go. The next image is MO2 showing that the mouse can go all the way to the bottom here.

![20221023_204539](https://user-images.githubusercontent.com/26223818/197445672-79c5fced-7a72-49a7-bddb-ff4b51cbd14f.jpg)
![20221023_204459](https://user-images.githubusercontent.com/26223818/197445730-1af16ea7-abbf-424b-b6b5-d212bfffe174.jpg)

**Comment by SentaiBrad** [comment]
Interesting, this seems to be directly linked to the same bug that I reported to Valve. 

https://github.com/ValveSoftware/SteamOS/issues/885

When I performed my fix here for the Steam Deck connected to an External Display (changing the automatic resolution and changing it to 1280x800 manually), it also fixed the usable space problem that I reported here for STL. Unsure if there is a workaround STL can perform in the meantime, but here we are.

Also want to keep this open for the moment as I need to re-test without the External Display.

Edit: yep, perfectly in handheld mode. Apologies, but at least the info now exists for someone else.

**Comment by sonic2kk** [comment]
Ah, so just to confirm, this is a SteamOS bug?

Thanks for being proactive in linking that issue, I'm hoping to add a troubleshooting section to the wiki and I might link this issue and your SteamOS issue on there as well as on the Steam Deck wiki :+1:

**Comment by SentaiBrad** [comment]
Yea, it looks to be a SteamOS bug. Other users are reporting on their GitHub and the Steam Forums about it.

**Comment by sonic2kk** [comment]
Just tested on my TV and I can reproduce. But yeah, it probably isn't something we can do anything about.
