### ISSUE TITLE
MO2 Permissions Error in Steam Deck

### ISSUE THREAD

**Issue by SentaiBrad** [sonic2kk/steamtinkerlaunch#641]
## System Information
- SteamTinkerLaunch version: v11.12.20221021-2
- Distribution: SteamOS - In GameMode Only
- Installation Method: ProtonUp-Qt

## Issue Description
Tonight, I had been changing settings to output a proper 1280x800 for GameMode, and to make sure New Vegas is capped at 60fps. When I tested everything last night in GameMode, I did get the game to launch with no errors and no issues.

After config changing, tonight I am receiving this:

![20221023_204512](https://user-images.githubusercontent.com/26223818/197447466-191f8f41-22d8-42e9-a64d-e81775a3a0c3.jpg)

I am fairly confident I did not change any paths or settings that should be related to this, but I am unsure where or how to look for it.

On a side note related to this, the screen (or STL menu?) flashes and goes black consistently during boot. Both the Game and MO2 prompts do when they did not last night. I didn't think that it was important enough to make a bug ticket on that issue, and is very likely related to this.

## Logs
Since this is happening in GameMode, are the logs being kept when booting to the Desktop Environment, as long as I am not launching STL?

**Comment by SentaiBrad** [comment]
Interesting. I now have the issue in the DE as well.

**Comment by SentaiBrad** [comment]
Apologies, I did end up finding the setting that did this. I still like that the ticket is available for others who may come across the Issue.

I had "GameMode" enabled in the Game Menu under the Tools Option. I had enabled all the "GameScope" stuff previously, attempting to do the scaling and fps limiting with that tool (still having that issue though #639). GameMode got toggled at some point after that testing and during this batch of testing.

**Comment by sonic2kk** [comment]
It sounds like you got it sorted, which is great! But just a heads up, this specific problem is documented on the Modding wiki page: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Modding#errors-around-failed-to-update-mod-list-failed-to-save-

**Comment by SentaiBrad** [comment]
> It sounds like you got it sorted, which is great! But just a heads up, this specific problem is documented on the Modding wiki page: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Modding#errors-around-failed-to-update-mod-list-failed-to-save-

And here I thought I searched well enough. I appreciate it.
