### ISSUE TITLE
Vortex Doesn't Autoconfigure

### ISSUE THREAD

**Issue by KenJyn76** [sonic2kk/steamtinkerlaunch#647]
## System Information
- SteamTinkerLaunch version: latest release and latest master
- Distribution: Arch Linux
- Installation Method: AUR and ProtonUp-Qt

## Issue Description
When attempting to install/start Vortex via STL, it prints a couple errors in the terminal, hangs for a minute or two, and then launches with no auto configuration occurring. It does find my games, and generate the configuration, but it doesn't make it to Vortex. MO2 functions normally. It also appears to fail to install Visual Studio 6.0.6, due to omitting any '.'s in the file path and file name. 

Logs are obtained from AUR steamtinkerlaunch-git, but I also tested AUR steamtinkerlaunch, as well as the latest binaries from ProtonUp-Qt, stable and git. I did do a clean install between tests by removing the .config folder for STL, as well as the /dev/shm/steamtinkerlaunch folder

## Logs

[terminal output](https://github.com/sonic2kk/steamtinkerlaunch/files/9932063/log.txt)
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/9932074/steamtinkerlaunch.log)
[installDotNet.log](https://github.com/sonic2kk/steamtinkerlaunch/files/9932077/installDotNet.log)

**Comment by sonic2kk** [comment]
Hi there! Thanks for opening an issue.

What do you mean by "no auto configuration"? Does Vortex not launch for you, or is there other unexpected behaviour here?

As for DotNet 6 failing, I didn't check the logs yet but you might have more luck using a very recently version of GE-Proton to install Vortex. Try setting the Vortex Proton to the latest GE you can get your hands on and then try reinstalling (remove `~/.config/steamtinkerlaunch/vortex`).

I've never gotten Vortex to launch at all on my PC and I don't use it so I didn't try very hard, but it worked on my laptop a couple of months ago I think. Maybe on my PC I didn't configure the GE version properly.

**Comment by sonic2kk** [comment]
Just got to check the terminal output, seems STL at least attempted to select the correct Proton version.

The path to the executable could be harmless, I noticed a similar problem yesterday when working on HMM support. The other messages here are particularly interesting, the `sed` error is pretty strange.

I'll try and look into this a little bit.

**Comment by sonic2kk** [comment]
Can you check if the folder `~/.config/steamtinkerlaunch/vortex/downloads/site` exists? I suspect it doesn't, and the Vortex download command failed for me because that `site` folder didn't exist. Probably we'll want to create this before attempting to download dotnet6.

**Comment by sonic2kk** [comment]
Just pushed 09c2f57169417a1df4c06760b5bdabf147fb9403 which attempts to fix this problem. If you wouldn't mind, could you try installing Vortex again?

it seems like the GE-Proton issue is a non-issue, but I wonder if maybe your Vortex issues come from dotnet6 not installing. I guess there is only one way to find out :-)

I am also going to attempt to install Vortex here on my PC again and see how it goes. I don't intend on going any further than seeing if Vortex starts and if there is any game autoconfiguration - Though I need you to expand a bit on what exactly you mean and what the "expected" behaviour should be :-) (my PC and laptop both run Arch Linux as well fwiw)

**Comment by sonic2kk** [comment]
Vortex is still installing and finding my games (there are a lot iirc so it might take a while) but with that commit it was able to download and seemingly successfully install dotnet6.

Well Vortex installed seemingly but it won't start for me. But looking in the global menu I was stupidly using GE-Proton7-24.

Selecteing GE-Proton7-38 got Vortex to launch and in the list of games, it has a *ton* of games - Though some are not games that i own it looks like.

Run `steamtinkerlaunch settings` and then in the Global Menu, verify the version of Proton that is selected.

I'm not sure if Vortex is supposed to see and automatically add a game as Managed, but on my system when I clicked "Manage" in the list of games it automatically add the games I tested. The list of games that are autodiscovered are probably limited to the games in this file: https://github.com/sonic2kk/steamtinkerlaunch/blob/master/misc/vortexgames.txt

In briefly testing this seems to be the case. It didn't automatically discover Yakuza 0 (not in that text file), but it did automatically discover No Man's Sky (is in the text file). Gonna test by updating the list of games here and seeing if it allows them to be discovered and set up.

Yup it seems like a game needs to be set in the `vortexgames.txt` file. I wonder if there's a way to automate this somehow.

**Comment by KenJyn76** [comment]
Hi there! 

I'll check if that commit helps shortly. The expected behavior in this case is Vortex detecting my games, and setting the correct paths for downloads and staging folders. Instead, it launches, but there are no managed games, and the paths are incorrect. Pure speculation, but it seems like `vortset.cmd`  isn't running properly. All the configuration files are there, but nothing is applied to Vortex. 

`~/.config/steamtinkerlaunch/vortex/downloads/site` did not exist. Attempting with the latest commit now.

**Comment by KenJyn76** [comment]
Alright,

I tested the latest commit. Indeed, dotnet6 installs properly now, but the configuration still isn't applied. Here's logs, and a screenshot of Vortex for context. I ran `steamtinkerlaunch vortex getset` in the terminal output, showing that everything was detected properly, and simply not applied. 

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/9936454/steamtinkerlaunch.log)
[seenvortexgames.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/9936460/seenvortexgames.txt)
[log2.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/9936461/log2.txt)
![Screenshot_20221104_042920](https://user-images.githubusercontent.com/12451581/199929415-ed36ba81-e099-4a8c-9d21-ad219fbe4838.png)

**Comment by sonic2kk** [comment]
Hi! Glad to hear this got Vortex opening for you. Haven't gotten to check the logs yet (currently just on break) but from your screenshot it just looks like you didn't set Vortex to manage any games yet. 

Search for your game using Vortex's search box and then hover over it and click the "Manage" button.

I'm not sure if this is different from the behaviour on Windows but in my tests, games that STL is able to see (in your case, Skyrim SE and Fallout 4 I think?) which in other words are games stored in the `vortexgames.txt` file, are able to be selected and managed.

Sorry if I'm misunderstanding, I have very limited knowledge of Vortex. But I believe having the games ready to be selected and managed is normal behaviour, unless when you search for a game, hover over it and click "Manage", it throws an error. Then there might be a problem.

I don't know if it's expected for games to be set as "managed" by default - To me that doesn't sound like correct behaviour. In my mind it makes more sense for the games to be seen and ready to then be manually enabled by the user (if you had hundreds of supported Vortex games for example, you wouldn't want them all to be managed in Vortex by default).

However you said the "paths are incorrect". I'm not sure what you mean, maybe the logs have more clues but I can't look at them just yet. I appreciate the patience and sorry for my lack of understanding on Vortex... But hopefully we can get to the bottom of this! Vortexcmd seemed to work with the games I tested on my PC in that the paths were set correctly it seemed like (Vortex was able to open the right folders once they were set as managed, and it didn't throw any errors when setting it as managed).

Good luck! :-)

**Comment by KenJyn76** [comment]
Hey, it does work now! 

Before, when attempting to manage the titles STL had auto detected, Vortex didn't have any information on them and I had to manually set my file paths. After testing that a couple times, I had come to think that it would automatically add the games to the managed games tab, just like how MO2 automatically creates instances. Testing it again, though, hitting "Manage game" auto fills the path, and the staging paths are set properly. I wonder if before vortset.cmd was failing silently because dotnet6 wasn't installed. 

Before, I had to manually select the games, and set the staging paths. 

Thanks!

**Comment by sonic2kk** [comment]
That's great news!

It could just be a difference between MO2 and Vortex but I think Vortex needs you to click "Manage" before your game actually registers as usable in Vortex. Maybe this is a Linux-specific quirk but the paths all work and STL sees your game, so hopefully all is well :-)

I also agree that DotNet6 failing may have caused some other problems. But I'm glad it works for you now! 

Happy gaming!
