### ISSUE TITLE
Install Problem [CompatTool] // New to Linux

### ISSUE THREAD

**Issue by KaliEros** [sonic2kk/steamtinkerlaunch#650]
Hello,

I hope everyone is doing well. I have a feeling the solution to my problem is fairly simple, but I'm brand new to Linux. Never used it before, 100% brand new to Linux. I just received my Steam Deck and am trying to install STL, which looks amazing, to make my gaming experience even more enjoyable. 

That said, I've downloaded the latest STL release and ran steamtinkerlaunch through Konsole. It seemed to run through the install alright, but then it gave me this message: 

SKIP - CompatTool - Nothing to do the '/home/deck/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/steamtinkerlaunch' symlink still points to '/home/deck/stl/prefix/steamtinkerlaunch'.

It's also not showing up as a compatability option in Steam with any of my games. I looked online, searched for help, and found various install methods, such as typing ./steamt into the Terminal, but I just keep receiving the same message. It seems to be telling me something is off with the install path or that they're not matching up, but I didn't find anything about needing to extract the contents/install STL in a particular folder, such as alongside Steam so I'm not sure what I'm missing. Even the STL log isn't showing up for me; I'm assuming because it's not properly installed yet. 

I sincerely apologize if the answer to this is already posted here, but, even after searching the error message in Google I couldn't find anything. Needless to say, especially as one who's never used Linux before today, I'm starting to feel a bit overwhelmed and would greatly appreciate any help. 

Warmly,
K

**Comment by sonic2kk** [comment]
Hi there! It sounds like you just need to restart Steam to get the compatibility tool list to refresh (you also have to do this with GE-Proton).

To restart Steam, you can either restart your Steam Deck, or from Desktop Mode you can open Steam and close it like you would on a regular desktop (top of window -> Steam -> Exit Steam). Note that when you close Steam the Deck controllers will stop working briefly, but once it's fully closed (when the icon disappears from the system tray around the bottom right of the screen) you can just tap on the "Return to Game Mode" desktop icon which will handle opening Steam again. Then once you're back in Game Mode you should have SteamTinkerLaunch available as a compatibility tool.

Try that and see if you have any luck :-)

**Comment by KaliEros** [comment]
Thank you so much! That did it. Now, STL is showing up in both game and desktop mode and the menu works flawlessly thus far, though I'm still learning how to use it of course. The solution was even simpler than I thought it'd be; almost feel a bit foolish for even needing help with it. Thank you again for your help and kindness; it's much appreciated. XDWhile I have this post open, I wonder if I can ask another question related to installation. I'd like to use a trainer for a few games that I've already beaten numerous times and wish to play again without the need to grind so much. Normally, I use WeMod, but I understand that is only for Windows, not Linux. I've read that Cheat Engine is recommended for Steam Deck/Linux and that it works great with STL. I'm just having a hell of a time getting it installed with STL. Whenever I look up the instructions, I find information on how to use Cheat Enginge with STL once it's installed, but not how to install it. On one of the STL information pages, it mentions Cheat Engine and says it's an automatic download, but I'm not sure if that means it's automatically downloaded along with STL or if it means STL would automatically detect Cheat Engine upon downloading and installing it. I spent quite a bit of time this evening looking through all the various STL menu options and couldn't find Cheat Engine for the life of me. If I could get some help with this as well, I'd be most grateful and then, hopefully, I should be good for awhile and not need any additional assistance.Either way, thank you once more for the help already provided. Supportive communities are always wonderful to find. :)
-------- Original message --------From: Eamonn Rea ***@***.***> Date: 11/9/22  1:20 AM  (GMT-08:00) To: sonic2kk/steamtinkerlaunch ***@***.***> Cc: KaliEros ***@***.***>, Author ***@***.***> Subject: Re: [sonic2kk/steamtinkerlaunch] Install Problem [CompatTool] // New to Linux (Issue #650) 
Hi there! It sounds like you just need to restart Steam to get the compatibility tool list to refresh (you also have to do this with GE-Proton).
Try that and see if you have any luck :-)

**Comment by sonic2kk** [comment]
> On one of the STL information pages, it mentions Cheat Engine

Ah, this is my bad. Which page did you read this on? CheatEngine and GameConqueror were recently removed from SteamTinkerLaunch following concerns about redistribution, anti-cheat concerns and upstream behaviour.

I've been trying to remove mention of this from SteamTinkerLaunch around the wiki, sorry for the confusion. You can see more on the [FAQ page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/FAQ#where-did-cheat-enginegameconqueror-go). 

I would **not** recommend using CheatEngine personally. If your trainer is available standalone, you may be able to just add it as a custom program from the Game Menu. Enable the "Use custom command" checkbox and then browse to your custom command executable. Then it'll start with the game.

There is also the option of manually installing CheatEngine, but this is quite advanced and maybe not something a beginner would be comfortable doing.

Hope this helps :-) Closing this as the initial issue is resolved but please feel free to reply if you have more questions!
