### ISSUE TITLE
[Feature Request] D8VK support

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#653]
## System Information
- SteamTinkerLaunch version: v11.12.20221112-7
- Distribution: Arch Linux

## Feature Description
An idea I had the other day was to implement support for [D8VK](https://github.com/AlpyneDreams/d8vk), a fork of DXVK that translates Direct3D 8 calls to Vulkan. I am not sure how many games use this and would benefit from it (maybe some Sonic Adventure mods and really old games?), but I'd like to add a way to enable this per-game and toggle it on and off. I'm not sure specifically if these are games that D8VK helps support with, but [their wiki](https://github.com/AlpyneDreams/d8vk/wiki) has a list of games. 

The enabling part isn't a big deal, probably we can just have a checkbox and when checked and saved per-game, it'll fetch the latest Actions build just like we do for HedgeModManager using nightly.link - D8VK doesn't have any releases to download from. We can store these in a SteamTinkerLaunch downloads folder, and only redownload when the version we have locally is different from the online version.

Looking at [D8VK's setup script](https://github.com/AlpyneDreams/d8vk/blob/master/setup_d3d8.sh), it seems like it automatically backs up the two existing DLLs that it overwrites (`d3d8.dll` and `d3d9.dll`). It also offers a `--symlink` option, though I'm not sure if we want to use that since it means if STL is ever uninstalled, the DLLs will stop working since their original files will be deleted with STL.

The D8VK script also offers an uninstall option, which restores any existing backed up DLLs.

Implementation could be as straightforward as:

```bash
function installD8VK {
    fetchLatestD8VK  # Would handle the version checking and downloading, as well as checking if D8VK already exists in STLCFGDIR
    writelog "INFO" "${FUNCNAME[0]} - Install D8VK for '$AID' to prefix '$GPFX'"
    WINEPREFIX="$GPFX"
    "$D8VKSETUP" "install"
    writelog "INFO" "${FUNCNAME[0]} - Successfully installed D8VK"
}

function uninstallD8VK {
    writelog "INFO" "${FUNCNAME[0]} - Uninstalling D8VK for '$AID' to prefix '$GPFX'"
    WINEPREFIX="$GPFX"
    "$D8VKSETUP" "install"
    writelog "INFO" "${FUNCNAME[0]} - Successfully uninstalled D8VK"
}
```

Very loose draft here, there would need to be more checks for whether the prefix exists at that directory before installing D8VK and other details like that.

I am not sure when I will get a chance to look at this, contributions would be welcome!

**Comment by sonic2kk** [comment]
There could be concerns here if the `d3d8.dll.old` / `d3d9.dll.old` files that are generated by the D8VK script were generated previously i.e. a manual installation of an update DXVK build. There is also the issue of a D8VK update overwriting these 

Though I think the script checks if the `.old` files already exist before creating them, it is still a concern that would need investigated.

**Comment by zany130** [comment]
not to discourage this as it might be useful for older games but one concern is i imagine that this will eventually be merged back into DXVK just as D9VK ( i think it was called that?)

**Comment by sonic2kk** [comment]
Yup D9VK was merged back upstream, though I'm not sure if there are any plans to do this with D8VK. From my brief research it didn't seem like there were, though the maintainer of D8VK does contribute back various things to DXVK.

Definitely a good point and something we should keep in mind! Maybe this would be good to add experimentally into a later version of STL in-between releases, so that if it is merged back upstream we could take it out (not that I foresee removing it being any extra effort, but removing it between releases might be cleaner :smiley:)

**Comment by sonic2kk** [comment]
Small update: Upstream DXVK has removed the install script from git, I am not sure if D8VK has or will follow suit. We may be able to just download the script from an older commit with D8VK and then run that to install (I doubt directory structure or anything is likely to change).

**Comment by sonic2kk** [comment]
Upstream D8VK appears to have kept the install script, and there is even a PR up on their repo to improve it!

Perhaps we can expect this script to remain!

**Comment by sonic2kk** [comment]
Development has begun on this feature on this branch: [`d8vk-support`](https://github.com/sonic2kk/steamtinkerlaunch/tree/d8vk-support).

No functionality at the time of writing, just a checkbox. Should hopefully be straightforward enough, I'll need to get some games together to test this with :-)

**Comment by sonic2kk** [comment]
I decided to stop work on this and look into getting this merged into Winetricks. If it's not accepted upstream for any reason I'll look into this again, so I'll leave this open until either it's merged into Winetricks or until STL implements it if it's not merged upstream.
