### ISSUE TITLE
Refuses to finish installing via ProtonUp-Qt on Steam Deck

### ISSUE THREAD

**Issue by formicsapien** [sonic2kk/steamtinkerlaunch#654]
## System Information
- SteamTinkerLaunch version: v11.11 (and and I tried several others with the same result
- Distribution: Steam OS 3 (steam deck)
- Installation Method: ProtonUp-Qt

## Issue Description
I try to initiate install through ProtonUp-Qt and the installation bar gets stuck at 99%.  I thought it was installing dependencies so I let it sit, but even after 20 minutes it's still stuck there.  After closing, Steam Tinker Launch shows up as a selection in steam, and launching a game with it gives me a delay, but nothing shows up on screen (both desktop mode and game mode).

### EDIT!
_Could be a steam os 3 beta branch issue.  This bug was present with the latest beta, but I reverted to steam os 3 stable, and it seems to be working now.  The installation still hangs at 99%, but it works nonetheless._

**Comment by sonic2kk** [comment]
Thanks for opening an issue!

This is already a known issue, and is not present in ProtonUp-Qt from source. It will be fixed the next time ProtonUp-Qt rolls a new release.

You can install SteamTinkerLaunch manually by downloading from git and double clicking the script. You can also run ProtonUp-Qt from source by following the instructions on their Readme.

Thanks! Closing this as it is known.

**Comment by sonic2kk** [comment]
This is fixed in the latest AppImage : https://github.com/DavidoTek/ProtonUp-Qt/releases
