### ISSUE TITLE
still won't work

### ISSUE THREAD

**Issue by SpAGgeTtie** [sonic2kk/steamtinkerlaunch#656]
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/9996538/steamtinkerlaunch.log)

## System Information
- SteamTinkerLaunch version: 
- Distribution: 
- Installation Method:

**Comment by sonic2kk** [comment]
Hi, thanks but please don't keep opening new issues. Just reply to the one open issue :-) Closing this and #657
