### ISSUE TITLE
STL 11.11 Custom Proton list empty on SteamOS

### ISSUE THREAD

**Issue by zerocoregithub** [sonic2kk/steamtinkerlaunch#666]
Hi everyone,

The game I'm trying to run with an injector requires the latest version of Proton GE in order to run properly on my Steam Deck. However, the list for custom proton installations in STL is completely empty. is there a way to fix this?

**Comment by sonic2kk** [comment]
This should be fixed in the latest git :-) Please try it out and see if you have more success.

Please remember to fill out issue templates properly instead of just submitting free-text issues.

**Comment by sonic2kk** [comment]
@TEEZEROEIGHT Did you have any more success with SteamTinkerLaunch-git?

**Comment by zerocoregithub** [comment]
I had to install the ProtonUp-Qt installation first before it would take the manual install, but it worked! The is issue is fixed. Thanks so much!
