### ISSUE TITLE
F4SE suddenly stopped launching

### ISSUE THREAD

**Issue by kuboslawik** [sonic2kk/steamtinkerlaunch#668]
## System Information
- SteamTinkerLaunch version: v11.11
- Distribution: Manjaro@5.15 kernel
- Installation Method: AUR

## Issue Description
Recently Fallout 4 VR with F4SE stopped launching, no crash, just after timeout of question if to start vortex, i can see that button changes from 'exit game' (or smth like that, not sure how it looks in english steam) to 'play' and nothing happens. Disabling all mods, reinstalling F4SE via Vortex and even manual reinstall didn't help. Tried Proton Experimental and latest Proton-GE to no avail. Game launches fine without steamtinekrlaunch %command%. Also tried removing STL config for this title completely, but fresh one didn't help either.

Log says first something about file not to be found, but previously STL script found it, and it is in the game directory. 

## Logs
`Sun Nov 20 11:57:05 CET 2022 INFO - initAID - Set AID from STEAM_COMPAT_APP_ID to '611660'
Sun Nov 20 11:57:05 CET 2022 INFO - initAID - Set OSCDP to STEAM_COMPAT_DATA_PATH '/home/kuba/.local/share/Steam/steamapps/compatdata/611660'
Sun Nov 20 11:57:05 CET 2022 INFO - loadLangFile - Language from command line is 'english'
Sun Nov 20 11:57:05 CET 2022 INFO - loadLangFile - SYSTEMSTLCFGDIR is '/usr/share/steamtinkerlaunch'
Sun Nov 20 11:57:05 CET 2022 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Sun Nov 20 11:57:06 CET 2022 INFO - loadLangFile - Loading found system wide /usr/share/steamtinkerlaunch/lang//english.txt
Sun Nov 20 11:57:06 CET 2022 INFO - getCurrentCommandline - Found Proton in command line arguments '/home/kuba/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=611660 -- /home/kuba/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/kuba/.local/share/Steam/steamapps/common/Proton - Experimental/proton waitforexitandrun /home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/Fallout4VR.exe'
Sun Nov 20 11:57:06 CET 2022 INFO - saveOrgVars - Storing some original variables to restore them later
nie, 20 lis 2022, 11:57:06 CET INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
nie, 20 lis 2022, 11:57:06 CET INFO - emptyVars - Set $PATH to '/home/kuba/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:'
nie, 20 lis 2022, 11:57:06 CET START - ######### Initializing Game Launch 611660 using SteamTinkerLaunch v11.11 #########
nie, 20 lis 2022, 11:57:06 CET INFO - main - Starting with a clean log
nie, 20 lis 2022, 11:57:06 CET INFO - main - Start creating default configs
nie, 20 lis 2022, 11:57:06 CET INFO - createDefaultCfgs - START
nie, 20 lis 2022, 11:57:06 CET INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
nie, 20 lis 2022, 11:57:06 CET INFO - loadLangFile - Language from command line is 'english'
nie, 20 lis 2022, 11:57:06 CET INFO - loadLangFile - SYSTEMSTLCFGDIR is '/usr/share/steamtinkerlaunch'
nie, 20 lis 2022, 11:57:06 CET INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
nie, 20 lis 2022, 11:57:06 CET INFO - loadLangFile - Loading found system wide /usr/share/steamtinkerlaunch/lang//english.txt
nie, 20 lis 2022, 11:57:06 CET INFO - loadLanguage - Loading STLLANG from '/home/kuba/.config/steamtinkerlaunch/global.conf'
nie, 20 lis 2022, 11:57:06 CET INFO - loadLanguage - STLLANG from '/home/kuba/.config/steamtinkerlaunch/global.conf' is 'english'
nie, 20 lis 2022, 11:57:06 CET INFO - createDefaultCfgs - setSteamPaths:
nie, 20 lis 2022, 11:57:06 CET INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
nie, 20 lis 2022, 11:57:06 CET INFO - getGameOS - Starting game OS detection
nie, 20 lis 2022, 11:57:06 CET INFO - getGameOS - Making some checks on '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/Fallout4VR.exe' to determine the OS version of the game
nie, 20 lis 2022, 11:57:06 CET INFO - getGameOS - Looks like this is a Windows game!
nie, 20 lis 2022, 11:57:06 CET INFO - setWin - 'Fallout4VR' determined to be a Windows Game
nie, 20 lis 2022, 11:57:06 CET INFO - listAllSettingsEntries - '/dev/shm/steamtinkerlaunch/setentries.txt' already exists - nothing to do
nie, 20 lis 2022, 11:57:07 CET INFO - createDefaultCfgs - STOP
nie, 20 lis 2022, 11:57:07 CET SKIP - listSteamLibraries - not recreating already available '/dev/shm/steamtinkerlaunch/SteamLibraries.txt'
nie, 20 lis 2022, 11:57:07 CET INFO - setSteamLibraryPaths - STEAM_COMPAT_LIBRARY_PATHS set to '/home/kuba/.local/share/Steam/steamapps'
nie, 20 lis 2022, 11:57:07 CET INFO - setSteamLibraryPaths - STEAM_COMPAT_MOUNTS set to '/home/kuba/.local/share/Steam/steamapps/common/SteamVR:/home/kuba/.local/share/Steam/config:/home/kuba/.local/share/Steam/logs:/home/kuba/.local/share/Steam/steamapps/common/Steamworks Shared:/home/kuba/.local/share/Steam/steamapps/common/Proton - Experimental:/home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier:/home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'
nie, 20 lis 2022, 11:57:07 CET INFO - setSteamLibraryPaths - STEAM_COMPAT_TOOL_PATHS set to '/home/kuba/.local/share/Steam/steamapps/common/Proton - Experimental:/home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier:/home/kuba/.local/share/Steam/steamapps/common/Steamworks Shared:/home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'
nie, 20 lis 2022, 11:57:07 CET INFO - main - Checking internal dependencies:
nie, 20 lis 2022, 11:57:07 CET INFO - setAwkBin - Found 'gawk' as an 'awk' variant. It should work without any issues, because 'gawk' was tested completely
nie, 20 lis 2022, 11:57:07 CET INFO - checkIntDeps - Result of version check for yad binary '/usr/bin/yad' is '12.0'
nie, 20 lis 2022, 11:57:07 CET INFO - main - Initializing first Proton:
nie, 20 lis 2022, 11:57:07 CET INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/steamtinkerlaunch/ProtonCSV.txt' which was created during a previous run
nie, 20 lis 2022, 11:57:07 CET INFO - initFirstProton - skipping function, because Proton version is provided by commandline (steamtinkerlaunch used via 'Steam Launch Option')
nie, 20 lis 2022, 11:57:07 CET INFO - main - Initializing default window resolution
nie, 20 lis 2022, 11:57:07 CET INFO - setInitWinXY - Using '1440x810' from config '/dev/shm/steamtinkerlaunch/defres.txt'
nie, 20 lis 2022, 11:57:07 CET INFO - main - Checking command line: incoming arguments '/home/kuba/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=611660 -- /home/kuba/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/kuba/.local/share/Steam/steamapps/common/Proton - Experimental/proton waitforexitandrun /home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/Fallout4VR.exe'
nie, 20 lis 2022, 11:57:07 CET SKIP - getGameOS - ISGAME is already set to '2' - nothing to determine
nie, 20 lis 2022, 11:57:07 CET INFO - linkLog - Symlink '/home/kuba/.config/steamtinkerlaunch/logs/steamtinkerlaunch/title/Fallout 4 VR.log' already exists
nie, 20 lis 2022, 11:57:07 CET START - ######### Game Launch: Fallout 4 VR (611660) #########
nie, 20 lis 2022, 11:57:07 CET INFO - prepareLaunch - Game launch args '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/Fallout4VR.exe'
nie, 20 lis 2022, 11:57:07 CET INFO - prepareLaunch - Gamedir '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR'
nie, 20 lis 2022, 11:57:07 CET INFO - prepareLaunch - Proton wineprefix '/home/kuba/.local/share/Steam/steamapps/compatdata/611660/pfx'
nie, 20 lis 2022, 11:57:07 CET INFO - prepareLaunch -------------------
nie, 20 lis 2022, 11:57:07 CET INFO - prepareLaunch - CreateGameCfg:
nie, 20 lis 2022, 11:57:07 CET SKIP - updateConfigFile - Config file '/home/kuba/.config/steamtinkerlaunch/gamecfgs/id/611660.conf' already at version 'v11.11'
nie, 20 lis 2022, 11:57:07 CET INFO - linkGameCfg - Symlink '/home/kuba/.config/steamtinkerlaunch/gamecfgs/title/Fallout 4 VR.conf' already exists
nie, 20 lis 2022, 11:57:07 CET INFO - prepareLaunch - First LoadCfg: /home/kuba/.config/steamtinkerlaunch/gamecfgs/id/611660.conf
nie, 20 lis 2022, 11:57:07 CET INFO - loadCfg - '/home/kuba/.config/steamtinkerlaunch/gamecfgs/id/611660.conf' START
nie, 20 lis 2022, 11:57:07 CET INFO - loadCfg - Loading game config '/home/kuba/.config/steamtinkerlaunch/gamecfgs/id/611660.conf'
nie, 20 lis 2022, 11:57:07 CET INFO - migrateCfgOption - File '/home/kuba/.config/steamtinkerlaunch/dxvk/611660.conf' does not exist - nothing to do
nie, 20 lis 2022, 11:57:07 CET INFO - loadCfg - '/home/kuba/.config/steamtinkerlaunch/gamecfgs/id/611660.conf' STOP
nie, 20 lis 2022, 11:57:07 CET INFO - prepareLaunch - OpenTrayIcon:
nie, 20 lis 2022, 11:57:07 CET INFO - autoCollectionSettings - Searching collections for game '611660' in 'sharedconfig.vdf'
nie, 20 lis 2022, 11:57:07 CET SKIP - autoCollectionSettings - Config '/usr/share/steamtinkerlaunch/collections/.conf' not found - skipping
nie, 20 lis 2022, 11:57:07 CET SKIP - autoCollectionSettings - Config '/home/kuba/.config/steamtinkerlaunch/collections/.conf' not found - skipping
nie, 20 lis 2022, 11:57:07 CET INFO - setFullGameExePath - Using the directory '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR' of the used custom command as absolute game exe path
nie, 20 lis 2022, 11:57:07 CET INFO - openTrayIcon - Opening trayIcon:
nie, 20 lis 2022, 11:57:07 CET INFO - setRunWineServer - Initiated from 'TrayIconExports'
nie, 20 lis 2022, 11:57:07 CET WARN - setRunWineServer - Couldn't find the wine binary for the proton in path '/home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/kuba/.local/share/Steam/steamapps/common/Proton - Experimental/proton' - falling back to 'wine' for plain RUNWINE and 'wineserver' for RUNWINESERVER
nie, 20 lis 2022, 11:57:07 CET INFO - prepareLaunch - sortGameArgs:
nie, 20 lis 2022, 11:57:07 CET SKIP - sortGameArgs - Sorting the game arguments is disabled
nie, 20 lis 2022, 11:57:07 CET INFO - prepareLaunch - AskSettings:
nie, 20 lis 2022, 11:57:07 CET INFO - askSettings - Using game specific requester timeout '2'
nie, 20 lis 2022, 11:57:07 CET INFO - askSettings - Opening Requester with timeout '2'
nie, 20 lis 2022, 11:57:07 CET INFO - getGameTextFiles - Searching for at least one editable textfile in '/home/kuba/.local/share/Steam/steamapps/compatdata/611660/pfx/drive_c/users/steamuser'
nie, 20 lis 2022, 11:57:07 CET INFO - getRes - Detected screen resolution '1920x1080'
nie, 20 lis 2022, 11:57:07 CET INFO - pollWinRes - Using GEOM '--geometry=709x365+0+0' from '/home/kuba/.config/steamtinkerlaunch/guicfgs/1920x1080/template/SteamTinkerLaunch-OpenSettings.conf'
nie, 20 lis 2022, 11:57:07 CET INFO - setShowPic - Determining game picture
nie, 20 lis 2022, 11:57:07 CET INFO - updateWinRes - Starting resolution-poll for '/home/kuba/.config/steamtinkerlaunch/guicfgs/1920x1080/611660/SteamTinkerLaunch-OpenSettings.conf' with incoming '709x365'
nie, 20 lis 2022, 11:57:07 CET INFO - setShowPic - Using '/home/kuba/.config/steamtinkerlaunch/games/header/611660.jpg' as game picture
nie, 20 lis 2022, 11:57:07 CET INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-OpenSettings'
nie, 20 lis 2022, 11:57:08 CET INFO - updateWinRes - Window 'SteamTinkerLaunch-OpenSettings' is running - polling the resolution
nie, 20 lis 2022, 11:57:11 CET INFO - askSettings - TIMEOUT - Starting game without opening the Settings Menu
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - Second LoadCfg after menus: /home/kuba/.config/steamtinkerlaunch/gamecfgs/id/611660.conf
nie, 20 lis 2022, 11:57:11 CET INFO - loadCfg - '/home/kuba/.config/steamtinkerlaunch/gamecfgs/id/611660.conf' START
nie, 20 lis 2022, 11:57:11 CET INFO - loadCfg - Loading game config '/home/kuba/.config/steamtinkerlaunch/gamecfgs/id/611660.conf'
nie, 20 lis 2022, 11:57:11 CET INFO - migrateCfgOption - File '/home/kuba/.config/steamtinkerlaunch/dxvk/611660.conf' does not exist - nothing to do
nie, 20 lis 2022, 11:57:11 CET INFO - loadCfg - '/home/kuba/.config/steamtinkerlaunch/gamecfgs/id/611660.conf' STOP
nie, 20 lis 2022, 11:57:11 CET INFO - setDxvkVars - Exporting variable 'DXVK_FRAME_RATE=none' to limit game framerate
nie, 20 lis 2022, 11:57:11 CET INFO - autoCollectionSettings - Searching collections for game '611660' in 'sharedconfig.vdf'
nie, 20 lis 2022, 11:57:11 CET SKIP - autoCollectionSettings - Config '/usr/share/steamtinkerlaunch/collections/.conf' not found - skipping
nie, 20 lis 2022, 11:57:11 CET SKIP - autoCollectionSettings - Config '/home/kuba/.config/steamtinkerlaunch/collections/.conf' not found - skipping
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - sortGameArgs again, in case something changed above:
nie, 20 lis 2022, 11:57:11 CET SKIP - sortGameArgs - Sorting the game arguments is disabled
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - symlinkSteamUser:
nie, 20 lis 2022, 11:57:11 CET SKIP - symlinkSteamUser - Symlinking steamuser is disabled - Checking if a symlink needs to be reverted
nie, 20 lis 2022, 11:57:11 CET SKIP - symlinkSteamUser - '/home/kuba/.local/share/Steam/steamapps/compatdata/611660/pfx/drive_c/users/steamuser' is no symlink - nothing to do
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - restoreSteamUser:
nie, 20 lis 2022, 11:57:11 CET INFO - restoreSteamUser - Using configured value 'none' for RESTORESTEAMUSER
nie, 20 lis 2022, 11:57:11 CET INFO - restoreSteamUser - Restoration of steamuser data is disabled with RESTORESTEAMUSER being 'none
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - prepareProton:
nie, 20 lis 2022, 11:57:11 CET INFO - setRunWineServer - Initiated from 'setNewProtVars'
nie, 20 lis 2022, 11:57:11 CET WARN - setRunWineServer - Couldn't find the wine binary for the proton in path '/home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/kuba/.local/share/Steam/steamapps/common/Proton - Experimental/proton' - falling back to 'wine' for plain RUNWINE and 'wineserver' for RUNWINESERVER
nie, 20 lis 2022, 11:57:11 CET INFO - prepareProton - Checking the Proton version is not required, because Steam Launch Option is used. Proton version set in Steam is 'proton-unknown-982'
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - setLinGameVals :
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - CheckTweakLaunch:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - checkXliveless:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - chooseWinetricks:
nie, 20 lis 2022, 11:57:11 CET INFO - chooseWinetricks - Using systemwide winetricks with version '20220411'
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - checkExtDeps:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - checkExtDeps done
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - setWineVars:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - CheckWinetricksLaunch:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - CheckWineCfgLaunch:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - CustomRegs:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - TogWindows:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - StateSteamWebHelper:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - InstallReshade:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - installDepth3DReshade:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - checkReshade:
nie, 20 lis 2022, 11:57:11 CET INFO - autoCollectionSettings - Searching collections for game '611660' in 'sharedconfig.vdf'
nie, 20 lis 2022, 11:57:11 CET SKIP - autoCollectionSettings - Config '/usr/share/steamtinkerlaunch/collections/.conf' not found - skipping
nie, 20 lis 2022, 11:57:11 CET SKIP - autoCollectionSettings - Config '/home/kuba/.config/steamtinkerlaunch/collections/.conf' not found - skipping
nie, 20 lis 2022, 11:57:11 CET INFO - setFullGameExePath - Using the directory '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR' of the used custom command as absolute game exe path
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - useSpecialK:
nie, 20 lis 2022, 11:57:11 CET INFO - setFullGameExePath - Using the directory '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR' of the used custom command as absolute game exe path
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - configureGeoElf:
nie, 20 lis 2022, 11:57:11 CET INFO - setFullGameExePath - Using the directory '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR' of the used custom command as absolute game exe path
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - ChooseShaders:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - UseNyrnaz:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - UseReplay:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - CheckSBSVRLaunch:
nie, 20 lis 2022, 11:57:11 CET INFO - prepareLaunch - Vortex is enabled - startVortex:
nie, 20 lis 2022, 11:57:11 CET INFO - setVortexVars - Using GE-Proton7-41 for vortex
nie, 20 lis 2022, 11:57:11 CET INFO - askVortex - Opening Vortex Requester with timeout '2'
nie, 20 lis 2022, 11:57:11 CET INFO - getRes - Detected screen resolution '1920x1080'
nie, 20 lis 2022, 11:57:11 CET INFO - pollWinRes - Using GEOM '--geometry=1440x810+0+0' from '/home/kuba/.config/steamtinkerlaunch/guicfgs/1920x1080/611660/SteamTinkerLaunch-OpenVortex.conf'
nie, 20 lis 2022, 11:57:11 CET INFO - setShowPic - Determining game picture
nie, 20 lis 2022, 11:57:11 CET INFO - updateWinRes - Starting resolution-poll for '/home/kuba/.config/steamtinkerlaunch/guicfgs/1920x1080/611660/SteamTinkerLaunch-OpenVortex.conf' with incoming '1440x810'
nie, 20 lis 2022, 11:57:11 CET INFO - setShowPic - Using '/home/kuba/.config/steamtinkerlaunch/games/header/611660.jpg' as game picture
nie, 20 lis 2022, 11:57:11 CET INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-OpenVortex'
nie, 20 lis 2022, 11:57:12 CET INFO - updateWinRes - The Window 'SteamTinkerLaunch-OpenSettings' was closed - the resolution didn't change - nothing to do
nie, 20 lis 2022, 11:57:12 CET INFO - updateWinRes - Window 'SteamTinkerLaunch-OpenVortex' is running - polling the resolution
nie, 20 lis 2022, 11:57:15 CET INFO - askVortex - TIMEOUT - Not starting Vortex
nie, 20 lis 2022, 11:57:15 CET INFO - prepareLaunch - CheckVortexSELaunch with argument '0':
nie, 20 lis 2022, 11:57:15 CET INFO - checkVortexSELaunch - using argument 1 '0' as SECHECK
nie, 20 lis 2022, 11:57:15 CET INFO - checkVortexSELaunch - SELAUNCH set to '0' - skipping any SE checks and directly starting what is configured in '/home/kuba/.config/steamtinkerlaunch/gamecfgs/id/611660.conf'
nie, 20 lis 2022, 11:57:15 CET INFO - prepareLaunch - checkMO2:
nie, 20 lis 2022, 11:57:15 CET INFO - prepareLaunch - setNewRes:
nie, 20 lis 2022, 11:57:15 CET INFO - getRes - Detected screen resolution '1920x1080'
nie, 20 lis 2022, 11:57:15 CET INFO - prepareLaunch - customUserScriptStart:
nie, 20 lis 2022, 11:57:15 CET INFO - prepareLaunch - redirectSCDP:
nie, 20 lis 2022, 11:57:15 CET INFO - redirectSCDP - Using Proton version 'unknown-982' for 'compatdata' directory name
nie, 20 lis 2022, 11:57:15 CET INFO - redirectSCDP - Using regular compatdata '/home/kuba/.local/share/Steam/steamapps/compatdata/611660'
nie, 20 lis 2022, 11:57:15 CET INFO - prepareLaunch - checkIGCSInjector:
nie, 20 lis 2022, 11:57:15 CET INFO - prepareLaunch - checkOpenVRFSR:
nie, 20 lis 2022, 11:57:15 CET INFO - prepareLaunch - CheckFWS:
nie, 20 lis 2022, 11:57:15 CET INFO - loadCustomVars - Empty global config '/home/kuba/.config/steamtinkerlaunch/gamecfgs/customvars/global-custom-vars.conf' for user defined custom variables not loaded
nie, 20 lis 2022, 11:57:15 CET INFO - loadCustomVars - Empty game-specific config '/home/kuba/.config/steamtinkerlaunch/gamecfgs/customvars/611660.conf' for user defined custom variables not loaded
nie, 20 lis 2022, 11:57:15 CET INFO - prepareLaunch - CheckCustomLaunch:
nie, 20 lis 2022, 11:57:15 CET INFO - checkCustomLaunch - USECUSTOMCMD is set to '1' - trying to start custom program '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/f4sevr_loader.exe'
nie, 20 lis 2022, 11:57:15 CET INFO - checkCustomLaunch - FORK_CUSTOMCMD is set to 0 - starting the custom program regularly
nie, 20 lis 2022, 11:57:15 CET INFO - launchCustomProg - '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/f4sevr_loader.exe' not found - searching in gamedir
nie, 20 lis 2022, 11:57:15 CET INFO - launchCustomProg - '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/f4sevr_loader.exe' also not in '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR//home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/f4sevr_loader.exe' - checking if absolute path was provided
nie, 20 lis 2022, 11:57:15 CET INFO - launchCustomProg - '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/f4sevr_loader.exe' is absolute path
nie, 20 lis 2022, 11:57:15 CET INFO - launchCustomProg - Changed pwd into the custom directory '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR'
nie, 20 lis 2022, 11:57:15 CET INFO - launchCustomProg - '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/f4sevr_loader.exe' seems to be a MS Windows program - starting through proton
nie, 20 lis 2022, 11:57:15 CET INFO - launchCustomProg - '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/f4sevr_loader.exe' seems to be a MS gui program - starting regularly
nie, 20 lis 2022, 11:57:15 CET INFO - setRunProtonFromUseProton - Setting ORUNPROTON to '/home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/kuba/.local/share/Steam/steamapps/common/Proton - Experimental/proton'
nie, 20 lis 2022, 11:57:15 CET WARN - extProtonRun - 'proton-unknown-982' seems outdated as the executable /home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/kuba/.local/share/Steam/steamapps/common/Proton - Experimental/proton wasn't found
nie, 20 lis 2022, 11:57:15 CET INFO - fixProtonVersionMismatch - Skipping function for 'proton-unknown' Proton version
nie, 20 lis 2022, 11:57:15 CET INFO - extProtonRun - Continuing with RUNPROTON='/home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/kuba/.local/share/Steam/steamapps/common/Proton - Experimental/proton'
nie, 20 lis 2022, 11:57:15 CET ERROR - extProtonRun - When this error occurs, probably the configured Proton (or a similar) version is no longer available.
nie, 20 lis 2022, 11:57:15 CET ERROR - extProtonRun - Because the RUNPROTON '/home/kuba/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/kuba/.local/share/Steam/steamapps/common/Proton - Experimental/proton' isn't ready here yet - please open an issue when you made sure it is set to an existing one and the error persists
nie, 20 lis 2022, 11:57:15 CET INFO - launchCustomProg - Changing pwd into previous directory
nie, 20 lis 2022, 11:57:15 CET INFO - checkCustomLaunch - ONLY_CUSTOMCMD is set to 1 means only custom program '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/f4sevr_loader.exe' is supposed to start - exiting here
nie, 20 lis 2022, 11:57:15 CET INFO - checkCustomLaunch - ## CUSTOMCMD STOPPED after '0' seconds playtime
nie, 20 lis 2022, 11:57:15 CET INFO - closeSTL - closing STL
nie, 20 lis 2022, 11:57:15 CET INFO - updateConfigEntry - Emptying 'CUSTOMCMD' for '/home/kuba/.config/steamtinkerlaunch/default_template.conf'
nie, 20 lis 2022, 11:57:15 CET INFO - updateConfigEntry - Option 'CUSTOMCMD' is updated with the new value 'echo' in config 'default_template.conf'
nie, 20 lis 2022, 11:57:15 CET INFO - closeSTL - Creating '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
nie, 20 lis 2022, 11:57:15 CET INFO - checkPlayTime - The game was not started via 'steamtinkerlaunch' but directly from Steam - skipping Crash Requester
nie, 20 lis 2022, 11:57:15 CET INFO - closeSTL - Game 'Fallout 4 VR (611660)' exited - cleaning up custom processes if necessary
nie, 20 lis 2022, 11:57:15 CET INFO - closeTrayIcon - Closing TrayIcon '34644'
nie, 20 lis 2022, 11:57:15 CET INFO - updateWinRes - The Window 'SteamTinkerLaunch-OpenVortex' was closed - the resolution didn't change - nothing to do
nie, 20 lis 2022, 11:57:16 CET INFO - closeSTL - Removing '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
nie, 20 lis 2022, 11:57:16 CET STOP - ######### closeSTL SteamTinkerLaunch v11.11 #########
nie, 20 lis 2022, 11:57:16 CET INFO - writeLastRun - Recreating /home/kuba/.config/steamtinkerlaunch/logs/steamtinkerlaunch/lastrun.txt
nie, 20 lis 2022, 11:57:16 CET INFO - storeMetaData - Saving metadata for game 'Fallout 4 VR (611660)'
nie, 20 lis 2022, 11:57:16 CET INFO - getArch - Architecture for '/home/kuba/.local/share/Steam/steamapps/common/Fallout 4 VR/Fallout4VR.exe' is 64bit
nie, 20 lis 2022, 11:57:16 CET INFO - storeMetaData - '/home/kuba/.config/steamtinkerlaunch/meta/eval/id/evaluatorscript_611660.vdf' does not exists`

**Comment by sonic2kk** [comment]
The Proton version in your log seems like it's not being found. Try changing the Proton version in the game menu and see if that helps :-)

It seems like you had Proton Experimental selected and it updated, and STL v11.11 can't resolve a mismatch for Proton Experimental. This is fixed in git, but not in a release yet.

**Comment by sonic2kk** [comment]
Also, `steamtinekrlaunch %command%` is **incorrect usage for Proton games, you should be using SteamTinkerLaunch as a compatibility tool as noted on the Readme. The launch option is only for native games!!**

**Comment by kuboslawik** [comment]
> Also, `steamtinekrlaunch %command%` is **incorrect usage for Proton games, you should be using SteamTinkerLaunch as a compatibility tool as noted on the Readme. The launch option is only for native games!!**

This fixed the issue, I changed compatibility tool to Proton-GE when i was playing with ProtonUp-Qt. Then different version was checked in STL, and caused problems. Thank you very much for help, it works now.
