### ISSUE TITLE
Sonic Frontiers closes right after launch when HMM's modloader is installed

### ISSUE THREAD

**Issue by McSkellyHo** [sonic2kk/steamtinkerlaunch#670]
## System Information
- SteamTinkerLaunch version: v11.12.20221121-3
- Distribution: SteamOS  
- Installation Method: Manual

## Issue Description
When I launch Sonic Frontiers with HMM's (installed with and ran with STL), the game closes after a few seconds, both when using version 1.1.1 of the loader and 1.1.0. If I uninstall the mod loader in HMM, the game launches fine. Sonic Forces works with mods just fine. I tried to launch Frontiers again with modloader v1.1.0 to make sure the logs are current, of course the issue stayed the same.

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10059873/steamtinkerlaunch.log)
[installDotNet.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10059875/installDotNet.log)

**Comment by sonic2kk** [comment]
Thanks for the report!

I know I've asked you to do this about a million times now, but could you delete the Frontiers prefix, launch Sonic Frontiers from Steam once until it gets to the main menu and then close the game. Then re-run HMM, and then attach the `steamtinkerlaunch.log` and `installDotNet.log` again? That way I can see what goes on during a "fresh" run of Frontiers. You don't need to remove any other files, just the Frontiers prefix (`rm -rf /home/deck/.local/share/Steam/steamapps/compatdata/1237320` should do it).

The logs you provided was insightful, SteamTinkerLaunch is actually finding Sonic Frontiers (not sure why I thought it wasn't able to, my bad!) and tries to install dotnet48. However in your installDotNet log it just says that dotnet48 is already installed. This may be a bit misleading as I think this message comes back even if dotnet48 installation doesn't work.

Also, from Desktop Mode, could you go to the Steam client > click the "Manage" cog button > Manage > Browse local files (see screenshot for visual) and see where exactly Sonic Frontiers is installed?

![image](https://user-images.githubusercontent.com/7917345/203151528-b8746522-7483-4ee7-85f7-d5d74e780829.png)

I would assume it would be at `/home/deck/.local/share/Steam/steamapps/common/SonicFrontiers`, but basically I'm trying to rule out that Sonic Frontiers' "expected" prefix location is correct. 

Thanks!

**Comment by McSkellyHo** [comment]
> I would assume it would be at /home/deck/.local/share/Steam/steamapps/common/SonicFrontiers

That is precisely where it is! Should I have the mod loader uninstalled? Last time when I ran the game after removing the prefix, the mod loader was installed and it failed to launch properly.

**Comment by sonic2kk** [comment]
Ah! Yes, it's probably a good idea to test first with the modloader uninstalled. That way you can test as if the game were vanilla if that makes sense. The game *should* launch in that instance.

So I would delete the modloader and then delete the prefix + launch the game once. If you already deleted the prefix, you can go to the Sonic Frontiers folder at that path mentioned and remove `d3d11.dll` (this file is the modloader).

This should boot the game up "clean". After launching the game with the modloader removed, you can then launch HMM which should set up dotnet48 for Sonic Frontiers. And then you can attach the logs and I can get a look at what exactly is going on with `installDotNet` and `steamtinkerlaunch` during that fresh setup period.

**Comment by McSkellyHo** [comment]
The game launched no problem when the modloader wasn't installed.
[installDotNet.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10060410/installDotNet.log)

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10060405/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Thanks! The logs are interesting - It seems to be *very* quick at installing `dotnet48`. I'm going to test again on my PC and compare the length of the logs, because to be honest the log doesn't have any errors but it also doesn't look "correct". This isn't any user error on your end as far as I can tell, so don't worry about that :-)

Just out of curiosity, you can try installing the modloader again and trying to launch Sonic Frontiers. If it still doesn't work, you can try restarting your Steam Deck and seeing if the game launches from Game Mode (unlikely to make a difference, but I am just curious).

Tangentially related side question: Do you have an external display connected to your Steam Deck? It isn't a problem if you do, but I had a friend try out HMM with STL and they had some issues until they disconnected from an external display and restarted -- That, from my understanding of the conversation, fixed the issue (and I know myself that SteamOS can sometimes have some weird glitches after connecting / disconnecting from displays, though they are mostly fixed now).

**Comment by McSkellyHo** [comment]
I have no other devices connected to my Steam Deck, no monitor, keyboard, mouse, or anything like that. Frontiers didn't launch when I installed the mod loader just now. I'll try restarting my Steam Deck and launching the game from game mode.

**Comment by sonic2kk** [comment]
Huh very interesting, installing dotnet48 is very quick on my PC. Just a bit quicker than what your logs show. And the logs are virtually identical.

I would wager that dotnet48 is installing correctly then. I wonder why Frontiers is crashing then... Maybe there'll be some more hints on the HMM side. I'll keep looking for now though, this is very interesting.

**Comment by McSkellyHo** [comment]
My Steam Deck took really long to restart, in fact I had to manually hold the power button when the screen was black but the cooling was still blowing air (I think this was caused by me accidentally launching the game before restarting and being unable to abort the launch right away). 
I’m now waiting for Sonic Frontiers to launch in game mode. It’s been about 2-3 minutes and it’s just spinning the loading wheel around the Steam logo so I don’t think it’s gonna launch in game mode either.

Update: If I press the Steam button and “view game details” it doesn’t even say the game is running, despite it being shown in the little steam menu.

**Comment by sonic2kk** [comment]
I've had that issue with other games, it could just be a SteamOS glitch unrelated.

I was able to suddenly reproduce the crashing on my PC after several deletions of the prefix and reinstalls of dotnet48. I enabled Proton logging and it's complaining about a missing `mscoree.dll` - I'll look into this and maybe this is the source of the probem.

**Comment by McSkellyHo** [comment]
Is the `mscoree.dll` a mod loader requirement? Odd that it wasn't installed automatically like `d3d11.dll` if that's the case.

**Comment by sonic2kk** [comment]
`mscoree.dll` I believe is a requirement of dotnet, which is a requirement of the modloader (the Proton log lists it as required for `d3d11.dll`). I think that's the order of dependency.

Not sure why I am only getting this error message *now*. I've been investigating to see if I can find out what causes this error, it seems to be a generic winetricks/dotnet issue, but I'll keep looking.

**Comment by sonic2kk** [comment]
@McSkellyHo Could you run the game with the launch option `PROTON_LOG=1 %command%`? This will create a Proton log file in your home directory. Then attach the file `steam-1237320.log` to your issue. I'm interested to see if you're experiencing the same issue that I am now.

If so, then we can say I am able to reproduce the same problem (and not just symptoms of a different problem) and I can investigate from there, when I know I'm on the right track :-)

**Comment by McSkellyHo** [comment]
I got the file but github just randomly decided to not let me send. When I drag it in, it tells me to try again and the in-browser file select doesn't show majority of my files.

**Comment by sonic2kk** [comment]
That's strange. Try changing the extension to `.txt` just in case :-)

**Comment by McSkellyHo** [comment]
That doesn't work either, the browser's file select just completely changed in appearance and only shows folders but not any files, not even zip file

**Comment by sonic2kk** [comment]
You can paste your log here and send a link to it: https://pastebin.com/index.php :-)

**Comment by McSkellyHo** [comment]
https://pastebin.com/p5vTK5cu
Thanks, and sorry about the complication

**Comment by sonic2kk** [comment]
Not a problem :-)

I suppose the "good news" is that I'm seeing the same issue that you are it seems like -- Our Proton logs are both complaining about a missing `mscoree` and a missing `d3d11.dll`. I'll investigate this and see if I can figure out why it's not finding these DLLs.

**Comment by McSkellyHo** [comment]
Alright that's good, at least it's possible to find a solution to the problem!

**Comment by sonic2kk** [comment]
I'll take a look into it and fix it as soon as I can. Thanks for all the help!

I'll be taking a break soon, I'm getting a little burned out and at the time of writing I have a little bit of a cold so I'm not in the best state to dig deeply into issues.

But I'll keep testing and seeing what I can do to resolve the problem eventually. Not sure why it's only affecting me now, my guess is something weird to do with DotNet and mono...

**Comment by McSkellyHo** [comment]
Oh don't worry about it! Your work on this is already incredible and you've been immensely helpful. Don't overwork yourself! Didn't you say that STL is a free time project of yours?

**Comment by sonic2kk** [comment]
Yeah, STL is my after-work project that I adopted from the previous maintainer (and creator) Frostworx :-)

**Comment by sonic2kk** [comment]
I rebooted and now Sonic Frontiers loads just fine with mods... Gosh this is very strange. I'll have to keep investigating

**Comment by McSkellyHo** [comment]
Ah I see, well that just makes you being able to work on this so much and being so responsive even more impresive. 

> I rebooted and now Sonic Frontiers loads just fine with mods

Now I'm even more confused than before.

**Comment by sonic2kk** [comment]
I'm just confusing myself now to be honest :sweat_smile: I'll take a look at this again in the future.

I can reproduce Sonic Frontiers and now Sonic Origins crashing. Something is definitely going wrong with that `mscoree.dll`, and I'm not sure what it is.

No more time today, and I may be silent on this for a while, but I will continue to investigate in the background over the next probably max few weeks.

**Comment by McSkellyHo** [comment]
I see, I tried to launch Forces just to make sure it still works and it does. But I get this weird popup whenever I launch Forces, just clicking yes starts the game no problem, I'm not sure what that's about
![image](https://user-images.githubusercontent.com/78847349/203174555-88e8e195-7e38-4145-bfaf-8e00973dadfb.png)

> No more time today, and I may be silent on this for a while

I have to go for today as well. Take your time! I know next to nothing about this stuff but what I do know is that it's super complicated.

**Comment by sonic2kk** [comment]
> I see, I tried to launch Forces just to make sure it still works and it does. But I get this weird popup whenever I launch Forces, just clicking yes starts the game no problem, I'm not sure what that's about

This is normal, even good behaviour. It's an issue to do with installing dotnet48 into a prefix. This is the error that I used to get indicating success, but now I don't get it and my 64bit games aren't getting dotnet48 installed correctly it seems like. Not sure what's causing this to be totally honest, but I guess my starting point is figuring out what is going wrong with dotnet48.

**Comment by McSkellyHo** [comment]
Ohh I see. Well hopefully the fix for the problem with `mscoree.dll` isn't too complicated. Best of luck!

**Comment by McSkellyHo** [comment]
After getting the 64 bit, version 10.0.14393.0 from https://www.dll-files.com/mscoree.dll.html
and putting the installed mscoree.dll file into the folder where the sonic frontiers exe file is located, I was able to launch the game with mode no problem!

**Comment by sonic2kk** [comment]
Oh gosh I am so delighted haha, and I'm going to quickly try and implement automatic downloading of this DLL for 64bit games (should be a few line change). Then I'll test if that fixes it for me, and if it does I'll get it pushed up and that should fix 64bit games.

As the other user noted on the HMM issue, this **is** likely a dotnet installation issue, and this is just a workaround. But it's a workaround that seems to work consistently, so for *now* I don't mind implementing this glue-and-tape fix.

Eventually this should not be needed, but if it works, it works :smile: I will close this issue now since we know how to fix it (or *should* know how to fix it) and I'm planning to push up the relevant code change asap.

**Comment by sonic2kk** [comment]
Actually, we may not have permission to download the DLL automatically from that site, just looking at their readme.

If it was available elsewhere e.g. on Internet Archive we could probably use that, but it doesn't seem to be. Damn

**Comment by sonic2kk** [comment]
The workaround is known, and at worst I can document this on the wiki if it can't be fixed :-)

Thanks for being so involved, and at long last, enjoy Sonic Frontiers! I know it might've ended up being a little more effort than it was worth on your end for this, but I hope if you ever re-install or have to use HMM elsewhere that STL makes your life a bit easier for modding on Linux.

**Comment by McSkellyHo** [comment]
Thank you for being so helpful and working on this awesome tool for modding! And while sure it was hard to get it to work and it took a while, it still works in the end and this will allow the experience to be smoother from now on. Plus you’re the one doing most the work, I was just relaunching and sending logs haha, I had a thought that I found funny that I was kind of like a testing program in this lol

**Comment by sonic2kk** [comment]
Those logs are a lifeline for developers when trying to recreate issues :-) You were a tester and a very patient and helpful one at that. Here's to a stable HMM release for STL v12!
