### ISSUE TITLE
One-Time Run doesn't open browser even with xdg-utils installed

### ISSUE THREAD

**Issue by KShivum** [sonic2kk/steamtinkerlaunch#672]
## System Information
- SteamTinkerLaunch version: v11.11
- Distribution: Fedora 37
- Installation Method: ProtonQT

## Issue Description
So I'm trying to launch a mod installer for Persona 5 using the [guide here](https://gamebanana.com/tuts/15409) but since I can't use protontricks with tinker launcher, I'm running everything through the one time run. (I have installed this correctly before with the given methods and know how it is supposed to work) and when I run the actual mod installer (not the actual game, another one time run) I know it'll say that I need to install another run time package and it will open a browser to the link. Using proton tricks it will open the link on the browser, but it doesn't on steam tinker launch. This isn't really a big issue, but I think it should be noted

## Logs
Nothing in there seems useful but...
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10071720/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Interesting! I will be honest, I am not sure how to fix this, as I wouldn't have expected `xdg-utils` to be used at all with Wine.

I wonder how Protontricks / Winetricks is able to do this

**Comment by KShivum** [comment]
Actually I just tried and swapped the compatibility to experimental in steam and ran protontricks on the executable and it ended up running correctly without popping up the you need to download x prompt. Am I using one time run wrong? Is it not meant for installing stuff like dependencies and running a program in the prefix?

**Comment by sonic2kk** [comment]
One-Time Run is meant for running an executable once in the same prefix as the game, at least to my understanding that's the rationale behind the feature. An example of this might be the Resident Evil 4 HD mod installer.

For installing dependencies though, hmm... I kind of want to bring this functionality in by allowing a one-time run of Winetricks GUI and Winecfg in the prefix in the One-Time run UI (a WIP implementation that sorta works-ish is in STL git at the moment).

For installing dependencies into a game's prefix you can use SteamTinkerLaunch's Winetricks menu :-)

<hr>

If Proton Experimental in Steam worked, you can set the STL Proton version to Experimental as well and see if that works.

**Comment by KShivum** [comment]
Yeah I've been poking at it for about two hours, it is using the same prefix as the steam chosen experimental. Using Winetricks doesn't seem to work in this instance because winetricks doesn't support .Net 7 desktop runtime yet it seems.

**Comment by sonic2kk** [comment]
Jesus Christ.

**Comment by KShivum** [comment]
Yeah just delete the issue, since I can't. Isn't worth a new tag for something I probably messed up. Removed irrelevant info from previous comment as it ended up being a rant. Sorry about that.

**Comment by sonic2kk** [comment]
I'm sorry, I try to be polite with my conduct, but I was not here.

As for the label, it's a standard GitHub label. And for deleting, I tend to keep issues around instead of deleting them.

Hope you get Persona working, use what works for you.

**Comment by KShivum** [comment]
You were fine, I was just frustrated, so I made some indirectly rude remarks in my rant and went off topic. Thanks for the help.
