### ISSUE TITLE
Add 7-zip dependency for HedgeModManager

### ISSUE THREAD

**Issue by wof8317** [sonic2kk/steamtinkerlaunch#681]
## System Information
- SteamTinkerLaunch version: latest git build
- Distribution: SteamOS

## Feature Description

For decompressing mods that are packaged in RAR or 7z archives, HedgeModManager looks for 7-zip installed on the system. Since winetricks supports installing 7-zip through there (winetricks), it may be a good idea to add 7-zip as a dependency for HedgeModManager.

**Comment by sonic2kk** [comment]
Thanks for the suggestion!

This is correct, there is a 7zip winetrick available. However, I already attempted this (as well as WinRAR) and it doesn't fix the issue. This would need to be addressed upstream I figure, either by looking for the Winetrick or (preferably) looking for `p7zip` on the user's system :-)

If you know of a way to get the Winetrick to work or any needed workaround we can reopen this to try and fix the problems but in my tests across 3 machines, the issue persisted even with the Winetrick.

I tried both adding the Winetrick to the list of Winetricks in the STL code, as well as manually installing from the command line (each time with a clean HMM prefix). The dialog still popped up with HMM claiming that it couldn't find 7zip. I'm not aware of any uses of this Winetrick that I could use as a reference anywhere in STL or similar, I figure the Winetrick installation is supported for purposes other than applications using it. The WinRAR winetrick also didn't work, giving the same dialog.

**Comment by wof8317** [comment]
If I remember correctly, all that hmm needs is the path to the 7-zip installation folder either through the registry, or through the Windows Path environment variable. If you installed it in the hmm prefix itself, hmm should be able to detect it as long as hmm is ran in its prefix.

**Comment by sonic2kk** [comment]
Interesting, I just tried again and was still unable to get it to work. I totally agree with the core here, that supporting this extraction is ideal, but I am not sure if the 7zip Winetrick can fix it :-(

Most distributions come with either some form of 7z/p7zip/etc (including Steam Deck) and/or a program that can extract these archives (such as Ark on KDE). HMM could support using native 7zip (it supports some native actions) but if you are able to get the 7zip winetrick to work please let me know. At worst, even if it doesn't work on my end, I could just add the winetrick in the list that gets installed to the HMM prefix.

Thanks :-) Going to reopen in this case just in case there can be further discussion here

**Comment by wof8317** [comment]
I would recommend having stl manually download the installer file from 7zip's website and execute it in the prefix the same way that stl downloads HMM and executes it in the same prefix.

**Comment by sonic2kk** [comment]
Not a bad idea, I can look into testing that. Is there a way to run the installer silently (without an installation prompt - fully automated basically?) If not maybe innoextact can be used for this.

**Comment by wof8317** [comment]
just pass the "/S" flag followed by /D="C:\Program Files\7-Zip" (default install directory). Also the flags are case sensitive.

**Comment by sonic2kk** [comment]
Haven't had time to look into this but wanted to give a proper comment instead of a reaction and say that I will give this a try and see how it goes once I have some free time.

If you, or anyone else reading this, would like to contribute here, please feel free!

**Comment by sonic2kk** [comment]
I checked the [Winetricks code](https://github.com/Winetricks/winetricks/commit/b7d8a4714449d586d884a2cc1c64f8ee683f4c26) and it seems to do exactly the same thing as you suggested, so in the latest git I added the 7zip dependency installation. This will only work for new installations because of the way I have some checks setup. There have been reports of dotnet48 installation failing unless you use Proton 5.0, so I would keep this in mind if you have to remove the prefix.

I tried the 7zip dependency in the past and it did not help. I tried just now and I was able to *update* a mod that requires 7zip to install, so... I'm not sure, you mileage may vary! Feel free to try it out and see if it works. Good luck! :-)

**Comment by sonic2kk** [comment]
Closing now, please re-open if it does not work :-)
