### ISSUE TITLE
Mod Organizer 2 Error - "7z.dll not found" 

### ISSUE THREAD

**Issue by Michael-Sebero** [sonic2kk/steamtinkerlaunch#684]

**Comment by sonic2kk** [comment]
Thanks for opening an issue!

When creating an issue you would've been presented with an issue template. Please edit your opening issue to follow this issue template, including attaching a log file of your attempted MO2 launch. You haven't provided any information that would help with debugging here. Giving a more detailed description other than a few words would be helpful to include in your edit.

Thanks! 

No other users have reported having to do this and I haven't had to do this, but you could try manually installing 7zip into your MO2 Wineprefix at `~/.config/steamtinkerlaunch/mo2/compatdata/pfx` I believe is the path. But I'm not sure that'll help, this sounds like it might be an installation issue or something.

I am also unable to find anything online about MO2 requiring 7zip.

**Comment by sonic2kk** [comment]
Closing as OP did not update their issue to follow the issue template and provide more information. Bug reports must adhere to the issue template and provide more than just one line to describe the problem.

Please re-open if you have time to spend on the debugging effort and provide further information. MO2's `dlls` folder should come with 7z so this sounds line an install problem, but without any logs or further information, no help can be provided here unfortunately.
