### ISSUE TITLE
Steam Deck Keyboard Invoked Forever on Game Closed.

### ISSUE THREAD

**Issue by freddyguythe10th** [sonic2kk/steamtinkerlaunch#686]
When exiting a game, the steam loading screen opens and the on-screen keyboard pops up. Only way to stop it is restarting steam.

**Comment by sonic2kk** [comment]
How is this related to SteamTinkerLaunch ? You also did not follow the issue template at all.

**Comment by sonic2kk** [comment]
The latest Steam Client Beta mentions this as a client bug that was fixed:

> Fixed keyboard re-opening incorrectly on game exit 

Given this note, and the lack of information and input from OP, I am assuming this is a Steam Client bug and closing this issue. Please re-open if you believe this is a SteamTinkerLaunch issue and attach appropriate information as requested on the issue template.
