### ISSUE TITLE
Hedgehog Mod Manager won't start

### ISSUE THREAD

**Issue by tmvkrpxl0** [sonic2kk/steamtinkerlaunch#693]
## System Information
- SteamTinkerLaunch version: steamtinkerlaunch-v11.12.20221217-1
- Distribution: KDE Neon 5.26 based on Ubuntu 22.04
- Installation Method: git clone https://github.com/sonic2kk/steamtinkerlaunch.git

## Issue Description
Hedgehog mod manager won't start.
Initially it failed to download, which is also shown in the log I attached below. However I was able to just skip through tat part by modifying `steamtinkerlaunch.sh` file to get exact url it downloads from and extracting it into `~/.config/steamtinkerlaunch/downloads/hedgemodmanager/HedgeModManager.exe`
I used `git reset --hard` to revert changes afterward.
After that it fails to launch silently.
I have removed `&> /dev/null` from function `startHMM` in the `steamtinkerlaunch.sh` to made wine print logs, and I discovered that it fails with some issue with dotnet framework? 
It uses is GE-Proton-7.38
It is worth noting that exact same error has happened when I installed dotnet 4.8 from [official microsoft page](https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0) and tried to launch HMM using wine-staging (7.22) that I got from package manager.

## Logs
`/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`: https://hastebin.com/vusoqibuje.yaml
`terminal log`:
```
❯ ./steamtinkerlaunch hmm start nightly
WARNING: Can't reach GitHub - Not attempting to download HedgeModManager
Checking latest available HedgeModManager Development version
Latest HedgeModManager is already downloaded or was downloaded previously
Found up-to-date HedgeModManager executable - Nothing to download
Finished installing HedgeModManager
Adding HedgeModManager to application menu and setting up link handlers
Setting up installed HedgeModManager compatible games
Sonic Generations: Installing 'd3dcompiler_47' for Direct3D 11 mod support
Finished configuring installed HedgeModManager games
Starting HedgeModManager
❯
```
`wine log`: https://hastebin.com/kakemowizi.yaml

**Comment by sonic2kk** [comment]
Hi, thanks for the extensive research here!

It seems like your Winetricks version is very out-of-date, as is typical of most distributions. See the log line:

```
2022. 12. 18. (일) 06:43:12 KST INFO - chooseWinetricks - Using systemwide winetricks with version '20210206'
```

You'll want to update your Winetricks with `sudo winetricks --self-update`, as per the instructions on the [Hedge Mod Manager wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Hedge-Mod-Manager#linux-desktop). HMM requires various Winetricks to work and one of those is `dotnet48`, which we install using Winetricks. If the version of Winetricks is too old, various winetricks verbs including `dotnet48` will fail to install.

For `dotnet48` to succeed with Winetricks, entirely unrelated to SteamTinkerLaunch, Winetricks version `20220411-next` is required.

You may also want to use a more recent version of GE-Proton, but it *should* be fine with GE-Proton7-38. Vanilla Proton, however, **will** fail to install `dotnet48`.

> It is worth noting that exact same error has happened when I installed dotnet 4.8 from [official microsoft page](https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0) and tried to launch HMM using wine-staging (7.22) that I got from package manager.

Hmm, it is possible that there is an incompatibility here with Winetricks and dotnet48 unrelated to STL. But then again, Winetricks could have other workarounds. One of the main differences if I recall correctly is that Winetricks removes wine-mono which is installed by default into Proton prefixes, but is incompatible with the `dotnet48` winetrick.

The Winetricks version is the main thing that stands out to me though, You may need to remove the HMM prefix and try installation again, which you can do manually or with `steamtinkerlaunch hmm uninstall`.

<hr>

Also:

> Initially it failed to download, which is also shown in the log I attached below. However I was able to just skip through tat part by modifying `steamtinkerlaunch.sh` file to get exact url it downloads from and extracting it into `~/.config/steamtinkerlaunch/downloads/hedgemodmanager/HedgeModManager.exe`


This is interesting. I'm not sure if there's much that can be done here, maybe this is a network issue? Some users have reported issues on some networks where they cannot download various files using Bash. But either way thanks for bringing this to my attention.

<hr>

With some luck, ensuring Winetricks is up-to-date should fix the problem. Distributions are *renowned* for packaging criminally out-of-date Winetricks, which is incompatible with newer versions of Wine including Proton, Wine stable and Wine staging. I believe there is an open issue on the Winetricks issue tracker about releasing a new version of Winetricks more frequently to address this, but I'm not sure of the status of this and also, STL is not associated with Winetricks, we just hook into it :-)

**Comment by tmvkrpxl0** [comment]
There seems to be issue with my installation of `ca-certiciates`, even other programs can't download anything using `curl` due to ssl error. I have re-installed it and now It's working.
Basically, it wasn't able to download anything on its own previously.
It's working now :+1:

**Comment by sonic2kk** [comment]
Awesome, I'm glad it's fixed :smile: 

Happy tinkering!
