### ISSUE TITLE
Vortex and MO2 not starting anymore

### ISSUE THREAD

**Issue by Plamper** [sonic2kk/steamtinkerlaunch#695]
## System Information
- SteamTinkerLaunch version: v11.12.20221219-1
- Distribution: SteamOS 3.4
- Installation Method: Proton-UP-Qt (git version)

## Issue Description
I wanted to dive into Skyrim modding, so I tried installing Vortex and had it working. But then it suddenly wouldn't work anymore, so I tried deleting everything associated with steamtinkerlaunch and reinstalling. No Luck. Then I thought might aswell use MO2 installed that got it working exactly 1 time. After I closed MO2 for the first time it wouldn't start back up. (On a sidenote the recent version change of innoextract broke MO2 for SteamOS 3.3.3). Things I already tried: Using commandline interface of stl, the YAD-gui started from steam, not using Proton-UP-Qt to install and copy and pasting the wine command into the terminal.

## Logs

[489830.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10270903/489830.log)

I tried running this but I don't know if that Command is even right. 
`
WINEPREFIX="/home/deck/.config/steamtinkerlaunch/mo2/compatdata/pfx" "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-43/files/bin/wine" "/home/deck/.config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe" -i "Skyrim Special Edition"
`
Output:

```
wine: using kernel write watches (experimental).
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: using kernel write watches (experimental).
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
wine: using kernel write watches (experimental).
00d0:err:module:import_dll Library dxva2.dll (which is needed by L"C:\\Modding\\MO2\\dlls\\Qt5WebEngineCore.dll") not found
00d0:err:module:import_dll Library Qt5WebEngineCore.dll (which is needed by L"C:\\Modding\\MO2\\dlls\\Qt5WebEngineWidgets.dll") not found
00d0:err:module:import_dll Library Qt5WebEngineWidgets.dll (which is needed by L"C:\\Modding\\MO2\\ModOrganizer.exe") not found
00d0:err:module:LdrInitializeThunk Importing dlls for L"C:\\Modding\\MO2\\ModOrganizer.exe" failed, status c0000135

```

**Comment by sonic2kk** [comment]
Hi, thanks for opening an issue!

Can you check to make sure MO2 is installed at `/home/deck/.config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/Modding/MO2/`?

The command you showed looks correct, and it looks like GE-Proton at least is unable to run MO2. You could try an older version of GE-Proton like GE-Proton7-42 and see if that works. Maybe the latest version of GE-Proton is failing here.

If they suddenly stopped working I would guess it's a Wine-related issue.

> On a sidenote the recent version change of innoextract broke MO2 for SteamOS 3.3.3

Ah that sucks, I guess I'll hold off releasing STL v12 until SteamOS 3.4 is out at least.

**Comment by sonic2kk** [comment]
I just tested on PC and MO2 is failing to launch with GE-Proton7-43, but it works with GE-Proton7-42.

You can change the MO2 Proton version in the Global Menu, I would recommend matching it with the game Proton. I personally use Proton 7.0-5 to run New Vegas/Oblivion and MO2.

This should resolve your issue all being well! Good initiative to try running the EXE manually, that was a big hint that this was a Proton version issue.

**Comment by Plamper** [comment]
Yes, that fixed it for me too. Had to delete the entire prefix tho, as the GE-Proton7-43 seems to brick the install completely.

**Comment by sonic2kk** [comment]
Awesome, glad it's working now! Hopefully the next release of GE-Proton won't have this issue and things will go smoothly again.

Happy tinkering :-)

**Comment by sonic2kk** [comment]
SteamOS 3.4 is out now in stable, so the innoextract version bump should now be a non-issue :-) Thanks for bringing that to my attention, but I guess it didn't really impact many users since no one reported it.
