### ISSUE TITLE
Game doesn't launch after closing Vortex (Fo4)

### ISSUE THREAD

**Issue by Raptime** [sonic2kk/steamtinkerlaunch#70]
I created a Vortex category, added Fallout4 and Vortex is successfully launched when I start Fallout4 in steam but when I close Vortex the game doesn't launch. Looking at processes, when Vortex is running:

> $ ps -ef | egrep "wine|stl|C\:"
> xxxx      299751  299750  0 Sep22 ?        00:00:00 /bin/bash /usr/bin/stl /home/xxxx/.local/share/Steam/steamapps/common/Proton 5.0/proton waitforexitandrun /home/xxxx/.local/share/Steam/steamapps/common/Fallout 4/Fallout4Launcher.exe
> xxxx      300603  299751  2 Sep22 ?        00:00:24 C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe --game fallout4
> xxxx      300606  299750  3 Sep22 ?        00:00:37 /home/xxxx/.local/share/Steam/steamapps/common/Proton 5.0/dist/bin/wineserver
> xxxx      300610  299750  0 Sep22 ?        00:00:00 C:\windows\system32\services.exe
> xxxx      300613  299750  0 Sep22 ?        00:00:00 C:\windows\system32\winedevice.exe
> xxxx      300621  299750  0 Sep22 ?        00:00:00 C:\windows\system32\plugplay.exe
> xxxx      300633  299750  0 Sep22 ?        00:00:06 C:\windows\system32\explorer.exe /desktop
> xxxx      300659  299750  2 Sep22 ?        00:00:31 C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe --type=gpu-process --field-trial-handle=728,12024882521006927186,2886464628144094265,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --gpu-preferences=KAAAAAAAAADgAAAwAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAACgAAAAEAAAAIAAAAAAAAAAoAAAAAAAAADAAAAAAAAAAOAAAAAAAAAAQAAAAAAAAAAAAAAAFAAAAEAAAAAAAAAAAAAAABgAAABAAAAAAAAAAAQAAAAUAAAAQAAAAAAAAAAEAAAAGAAAA --mojo-platform-channel-handle=732 --ignored= --type=renderer  /prefetch:2
> xxxx      300705  299750  0 Sep22 ?        00:00:00 C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe --type=utility --field-trial-handle=728,12024882521006927186,2886464628144094265,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --lang=en-US --service-sandbox-type=network --mojo-platform-channel-handle=924 /prefetch:8
> xxxx      300756  299750  4 Sep22 ?        00:00:47 C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe --type=renderer --js-flags=--max-old-space-size=4096 --field-trial-handle=728,12024882521006927186,2886464628144094265,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --disable-gpu-compositing --lang=en-US --app-path=C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar --node-integration --node-integration-in-worker --webview-tag --no-sandbox --no-zygote --enable-remote-module --background-color=#fff --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=7 --no-v8-untrusted-code-mitigations --mojo-platform-channel-handle=1252 /prefetch:1
> xxxx      300788  299750  0 Sep22 ?        00:00:00 C:\windows\system32\svchost.exe -k netsvcs
> xxxx      300795  299750  0 Sep22 ?        00:00:00 C:\windows\system32\rpcss.exe
> xxxx      300815  299750  1 Sep22 ?        00:00:15 C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\async.js gb5dzvrb

Once I close Vortex, all of this is gone:
> $ ps -ef | egrep "wine|stl|C\:"
> xxxx      301931  253687  0 00:23 pts/0    00:00:00 grep -E --color=auto wine|stl|C\:

Am I doing something wrong?

**Comment by frostworx** [comment]
Hm, your Vortex process doesn't close correctly. This should be also visible in your FO4 logfile under
/.config/stl/logs/

Do you see something useful when you start/close Vortex via commandline like:
`stl vortex start`? _(could f.e. be also wine --version related)_
Here the process probably doesn't exit correctly as well.

**Comment by frostworx** [comment]
Would be also good to know if
`stl vortex getset`
closes correctly after listing the vortex settings.

Anyway I'll also change the hard-coded WINEDEBUG="-all" entry in function wineVortexRun to a variable with the next release.

**Comment by Raptime** [comment]
Hey thanks for helping me!
This is what I see in the FO4 log file:

> Wed Sep 23 21:18:04 EDT 2020 SKIP - setVortexSELaunch - special exe 'f4se_loader.exe' for 'Fallout 4 (377160)' not found in gamedir '/home/xxxx/.local/share/Steam/steamapps/common/Fallout 4' - not enabling SELAUNCH in '/home/xxxx/.config/stl/gamecfgs/377160.conf'
> Wed Sep 23 21:18:04 EDT 2020 OK - startVortex - vortex exited - starting game now
> Wed Sep 23 21:18:04 EDT 2020 INFO - launchSteamProtonGame - checkVortexSELaunch:
> Wed Sep 23 21:18:04 EDT 2020 SKIP - setVortexSELaunch - special exe 'f4se_loader.exe' for 'Fallout 4 (377160)' not found in gamedir '/home/xxxx/.local/share/Steam/steamapps/common/Fallout 4' - not enabling SELAUNCH in '/home/xxxx/.config/stl/gamecfgs/377160.conf'
> Wed Sep 23 21:18:04 EDT 2020 INFO - launchSteamProtonGame - checkCustomLaunch:
> Wed Sep 23 21:18:04 EDT 2020 INFO - launchSteamProtonGame - checkStraceLaunch:
> Wed Sep 23 21:18:04 EDT 2020 INFO - launchSteamProtonGame - checkNetMonLaunch:
> Wed Sep 23 21:18:04 EDT 2020 INFO - launchSteamProtonGame - default proton command: /home/xxxx/.local/share/Steam/steamapps/common/Proton 5.0/proton waitforexitandrun /home/xxxx/.local/share/Steam/steamapps/common/Fallout 4/Fallout4Launcher.exe
> Wed Sep 23 21:18:04 EDT 2020 INFO - launchSteamProtonGame - starting 'Fallout 4 (377160)' with Proton: 'proton-5.0-9' with 'gamemoderun'
> Wed Sep 23 21:18:04 EDT 2020 STOP - ######### SteamTinkerLaunch v1.6.6 #########
> Wed Sep 23 21:18:04 EDT 2020 INFO - closeSTL - game Fallout 4 (377160) exited - cleaning up custom processes if necessary
> Wed Sep 23 21:18:04 EDT 2020 INFO - closeSTL - recreating /home/xxxx/.config/stl/logs/lastrun.txt
> Wed Sep 23 21:18:04 EDT 2020 STOP - #########  closeSTL SteamTinkerLaunch v1.6.6 #########

I installed f4se just in case but my proton is not compatible so I got this instead:

> Wed Sep 23 21:32:11 EDT 2020 INFO - setVortexSELaunch - found special exe 'f4se_loader.exe' for 'Fallout 4 (377160)' in gamedir '/home/xxxx/.local/share/Steam/steamapps/common/Fallout 4'
> Wed Sep 23 21:32:12 EDT 2020 BUG - setVortexSELaunch - the current proton version is not compatible with f4se_loader.exe
> Wed Sep 23 21:32:12 EDT 2020 BUG - setVortexSELaunch - you might want to use a custom proton version from https://github.com/Patola/wine/releases instead!
> Wed Sep 23 21:32:32 EDT 2020 OK - startVortex - vortex exited - starting game now
> Wed Sep 23 21:32:32 EDT 2020 INFO - launchSteamProtonGame - checkVortexSELaunch:
> Wed Sep 23 21:32:32 EDT 2020 INFO - setVortexSELaunch - found special exe 'f4se_loader.exe' for 'Fallout 4 (377160)' in gamedir '/home/xxxx/.local/share/Steam/steamapps/common/Fallout 4'
> Wed Sep 23 21:32:33 EDT 2020 BUG - setVortexSELaunch - the current proton version is not compatible with f4se_loader.exe
> Wed Sep 23 21:32:33 EDT 2020 BUG - setVortexSELaunch - you might want to use a custom proton version from https://github.com/Patola/wine/releases instead!
> Wed Sep 23 21:32:44 EDT 2020 INFO - setVortexSELaunch - starting game
> Wed Sep 23 21:32:44 EDT 2020 INFO - launchSteamProtonGame - checkCustomLaunch:
> Wed Sep 23 21:32:44 EDT 2020 INFO - launchSteamProtonGame - checkStraceLaunch:
> Wed Sep 23 21:32:44 EDT 2020 INFO - launchSteamProtonGame - checkNetMonLaunch:
> Wed Sep 23 21:32:44 EDT 2020 INFO - launchSteamProtonGame - default proton command: /home/xxxx/.local/share/Steam/steamapps/common/Proton 5.0/proton waitforexitandrun /home/xxxx/.local/share/Steam/steamapps/common/Fallout 4/Fallout4Launcher.exe
> Wed Sep 23 21:32:44 EDT 2020 INFO - launchSteamProtonGame - starting 'Fallout 4 (377160)' with Proton: 'proton-5.0-9' with 'gamemoderun'
> Wed Sep 23 21:32:44 EDT 2020 STOP - ######### SteamTinkerLaunch v1.6.6 #########
> Wed Sep 23 21:32:44 EDT 2020 INFO - closeSTL - game Fallout 4 (377160) exited - cleaning up custom processes if necessary
> Wed Sep 23 21:32:44 EDT 2020 INFO - closeSTL - recreating /home/xxxx/.config/stl/logs/lastrun.txt
> Wed Sep 23 21:32:44 EDT 2020 STOP - #########  closeSTL SteamTinkerLaunch v1.6.6 #########

Using stl vortex getset, I didn't see anything wrong, except that it outputs my home directory at the end (same if I lauch vortex from stl):

> $ stl vortex getset
> Wed Sep 23 09:42:59 PM EDT 2020 SKIP - updateConfigFile - config file /home/xxxx/.config/stl/vortex/vortex.conf already at version v1.6.6
> wineserver: using server-side synchronization.
> 
> info: Epic games launcher not found error=File not found. (2) 'SOFTWARE\WOW6432Node\Epic Games\EpicGamesLauncher'
> settings.automation.deploy = true
> settings.automation.enable = false
> settings.automation.minimized = false
> settings.automation.start = false
> settings.downloads.maxChunks = 4
> settings.downloads.maxParallelDownloads = 1
> settings.downloads.minChunkSize = 1048576
> settings.downloads.path = "Z:\\home\\xxxx\\.config\\stl\\vortex\\downloads"
> settings.downloads.showDropzone = true
> settings.downloads.showGraph = true
> settings.firststeps.dismissAll = false
> settings.firststeps.steps.profile-visibility = true
> settings.firststeps.steps.todo-tutorial-vid = true
> settings.fnis.autoRun = false
> settings.gameMode.discovered.fallout4.hidden = false
> settings.gameMode.discovered.fallout4.path = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Fallout 4"
> settings.gameMode.discovered.fallout4.tools.f4se.custom = false
> settings.gameMode.discovered.fallout4.tools.f4se.defaultPrimary = true
> settings.gameMode.discovered.fallout4.tools.f4se.exclusive = true
> settings.gameMode.discovered.fallout4.tools.f4se.hidden = false
> settings.gameMode.discovered.fallout4.tools.f4se.id = "f4se"
> settings.gameMode.discovered.fallout4.tools.f4se.name = "Fallout 4 Script Extender"
> settings.gameMode.discovered.fallout4.tools.f4se.path = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Fallout 4\\f4se_loader.exe"
> settings.gameMode.discovered.fallout4.tools.f4se.relative = true
> settings.gameMode.discovered.fallout4.tools.f4se.requiredFiles = ["f4se_loader.exe"]
> settings.gameMode.discovered.fallout4.tools.f4se.shortName = "F4SE"
> settings.gameMode.discovered.fallout4.tools.f4se.timestamp = 1600911080114
> settings.gameMode.discovered.fallout4.tools.f4se.workingDirectory = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Fallout 4\\"
> settings.gameMode.pickerLayout = "small"
> settings.gameMode.searchPaths = []
> settings.interface.advanced = false
> settings.interface.currentTheme = "__default"
> settings.interface.dashboardLayout = ["Starter","Extensions","Recently Managed","Go Premium","Announcements","Changelog","News","Latest Mods","Issues"]
> settings.interface.desktopNotifications = true
> settings.interface.hideTopLevelCategory = false
> settings.interface.language = "en"
> settings.interface.primaryTool.fallout4 = "f4se"
> settings.interface.profilesVisible = false
> settings.interface.relativeTimes = true
> settings.mods.activator.fallout4 = "hardlink_activator"
> settings.mods.cleanupOnDeploy = false
> settings.mods.confirmPurge = true
> settings.mods.installPath.fallout4 = "Z:\\home\\xxxx\\.config\\stl\\vortex\\staging\\fallout4\\mods"
> settings.mods.showDropzone = true
> settings.nexus.associateNXM = true
> settings.plugins.autoEnable = false
> settings.plugins.autoSort = true
> settings.profiles.activeProfileId = "GYy55RQsb"
> settings.profiles.lastActiveProfile.fallout4 = "GYy55RQsb"
> settings.profiles.nextProfileId = "GYy55RQsb"
> settings.saves.monitorEnabled = true
> settings.tables.mods.attributes.script-extender-error-check.enabled = false
> settings.update.channel = "stable"
> settings.window.customTitlebar = true
> settings.window.maximized = false
> settings.window.position.x = 38
> settings.window.position.y = 178
> settings.window.size.height = 864
> settings.window.size.width = 1536
> settings.window.tabsMinimized = false
> settings.window.zoomFactor = 1
> settings.workarounds.userSymlinks = false
> /home/xxxx

Is my issue related to f4se? Does stl expects me to use f4se or can I play without it?

**Comment by frostworx** [comment]
No, f4se is not required _(In fact I just tried it and the wineconsole complained about a wrong parameter using it, maybe I never tested it for FO4)_
FO4 works fine here with Vortex, so it doesn't seem to be a stl problem.
What also looks suspicious is, that STOP is logged withing the same seconds as when it was started.
This means Vortex quit correctly (which also indicates that stl vortex getset quits correctly) and Fallout4 should start on its own.
I miss read your initial request, and your process output was while Vortex was running regularly, so it seems to work as expected.

You might want to enable the PROTON_LOG and check that. For now, it looks like the problem is outside stl.
Sorry that I don't have better hints other than
- does it work without Vortex
- does it work without stl
- tried with a new WINEPREFIX

Good luck so far.

**Comment by Raptime** [comment]
After a few more tests:
- does it work without Vortex: no, I get the stl popup about settings, but then it exits and no game launch
- does it work without stl: yes, FO4 starts just fine

I'll keep digging, maybe I have something wrong with my FO4 installation. I'll try with a different game.

**Comment by frostworx** [comment]
Hmm, this is the first time I hear that a game fails to start with stl, but works without. Would be interesting what the whole log says
and/or if you also have problems with other games.

**Comment by frostworx** [comment]
One of the few settings which are enabled by default in stl atm is
`PULSE_LATENCY_MSEC=60`
You might want to disable it and see if that helps.
I'll add a toggle button around PULSE_LATENCY_MSEC in the next version, so it will be no longer enabled by default.

**Comment by Raptime** [comment]
Mystery solved!
stl tries to start the game with gamemoderun by default (which I do not have on my system):
> Thu Sep 24 18:43:59 EDT 2020 INFO - launchSteamProtonGame - starting 'Fallout 4 (377160)' with Proton: 'proton-5.0-9' with 'gamemoderun'

I had to explicitely add USEGAMEMODERUN=0 to the game config and now it starts the game as expected:
> Thu Sep 24 18:52:35 EDT 2020 INFO - launchSteamProtonGame - starting 'Fallout 4 (377160)' with Proton: 'proton-5.0-9'

**Comment by frostworx** [comment]
n1!
That will be no longer enabled by default as well in the next release.
