### ISSUE TITLE
Unable to launch HMM

### ISSUE THREAD

**Issue by SupDos** [sonic2kk/steamtinkerlaunch#701]
## System Information
- SteamTinkerLaunch version: v12
- Distribution: SteamOS
- Installation Method: ProtonUp-qt

## Issue Description
I can't get HMM to actually launch. I have tried setting different Proton versions in stl > Global > hmm (7.0, Experimental, Latest GE), uninstalling hmm and then reinstalling, and none of them work. 

I tried looking around and found #662 where they were also having a similar issue, however (from what I can tell) dotnet installs fine for me, unlike their issue.
I hope I didn't gloss over an issue that fixed this somehow, sorry in advance if I did 
## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10317540/steamtinkerlaunch.log)
[installDotNet.logHMMPREFIX](https://github.com/sonic2kk/steamtinkerlaunch/files/10317559/installDotNet.logHMMPREFIX.txt)

**Comment by sonic2kk** [comment]
Hi! Very strange indeed and thanks for actually doing a bit of research beforehand! Indeed, dotnet seems like it installs fine from your log as well, so I don't think this is a dotnet issue (thank god :sweat_smile:)

I recommend trying GE-Proton7-42, as GE-Proton7-43 has issues with several programs (MO2 and Vortex). Another user mentioned [very briefly in passing](https://github.com/sonic2kk/steamtinkerlaunch/issues/699#issuecomment-1364703413) that games should run with 43 and not 42, so it may be worth trying GE-Proton7-42. It could be that 42 has some issues, though you mentioned that latest experimental Proton did not work and it worked just fine for me on PC.

You could go to `~/.config/steamtinkerlaunch/downloads/hedgemodmanager` and make sure the downloaded executable is more than 0 bytes, as it could be the case that the downloaded executable is invalid for some reason. If it is 0 bytes, just remove the `hedgemodmanager` folder and re-run HMM.

One last-resort step could be to run `steamtinkerlaunch hmm uninstall` which will remove the prefix and other files, then change the HMM Proton version to Proton 5.0, and then re-run `steamtinkerlaunch hmm install`. Some users, mainly Steam Deck users strangely, have reported more success with Winetricks in general with Proton 5.0. You can install that version of Proton from Steam in Desktop Mode by searching for Proton 5.0, the same way you would on your regular Linux PC. You can change the HMM Proton version in the Global Menu.

Hopefully one of these steps resolves it!

**Comment by sonic2kk** [comment]
Just a quick scan, I haven't timed it but the other winetricks seemed to install kinda fast. Maybe they're failing too, though I'm not sure. This *could* be an installation problem with GE-Proton7-43.

It's definitely worth trying a reinstall with Proton 5.0 and if that fails, GE-Proton7-42.

**Comment by SupDos** [comment]
> the other winetricks seemed to install kinda fast

I think you were right. I reinstalled hmm with Proton 5.0, and while the dotNet installation took around the same time, the other part ('d3dx9' 'vcrun2019' 'd3dcompiler_47') took a few minutes, compared to a few seconds before

It didn't launch with Proton 5 though, so after installing, I switched hmm to GE 7-42 and it launched! Thank you for your help :)

**Comment by sonic2kk** [comment]
I'm so glad it works!! Happy modding my friend :-)
