### ISSUE TITLE
Add in wiki how to add steamtinkerlaunch for alternate game runners such as Lutris

### ISSUE THREAD

**Issue by redirectto** [sonic2kk/steamtinkerlaunch#703]
## System Information
> - SteamTinkerLaunch version: v12.0
> - Distribution: SteamOS

## Feature Description

> I've been looking for a way to implement steamtinkerlaunch on non-steam games from alternate game runners with no luck (Lutris, Bottles, Heroic Games Launcher).
> 
> If there is a way of doing that it would be really nice if that is added to the wiki.

**Comment by sonic2kk** [comment]
To use SteamTinkerLaunch with Non-Steam Games, add them as a Steam shortcut and set SteamTinkerLaunch as the compatibility tool (or `steamtinkerlaunch %command%` for native games)

Using SteamTinkerLaunch for games is only supported when used through the Steam client. If there is a way to use it with Lutris or with games you can run through Lutris/third party programs, I am unaware of it. It isn't really "intended" usage though, given that the project is called **Steam**TinkerLaunch.

I am also absolutely uninterested in Heroic Games. Games purchased on the Epic Games Store will **never** be supported by SteamTinkerLaunch.

Hopefully that answers your question! :-)
