### ISSUE TITLE
add Tray Icon Menu

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#71]
A stl Tray Icon Menu might be nice, which lives until the game/stl closed.
Haven't tested much yet, but it looks like it can only call "external" commands and no internal functions.
Anyway I'm sure this can be useful.
Using this ticket to collect some ideas.

Starting with:
- "Pick Window and get the Window Name" _(using xwininfo, useful f.e. for not auto-detected game windows in Stereo3D VR mode) (the picked window name could be automatically picked up by the waiting for window function)_

**Comment by Antiquete** [comment]
Can yad be used for this?
Reference [this](https://github.com/v1cont/yad/issues/59#issuecomment-544598752) and [this](https://github.com/Boteium/bashbullet2/blob/a1861edd00a3582942f0037603947ce7bb0c11db/bashbullet2#L38-L41)

**Comment by frostworx** [comment]
Sorry, I'm not sure what you want to ask.

**Comment by Antiquete** [comment]
Sorry, english not my native language so that might not have been clear. I was suggesting using yad --skip-taskbar for adding tray icon and using left and right click as actions similar to bashbullet.

**Comment by frostworx** [comment]
It is not my native language as well, so maybe that was the problem :)
Currently I only have this commented out line
https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L971
which opens a trayicon with right click dummy menu fine. It just looks like that you can only open external programs with it and no (stl) internal functions. Haven't looked too deep though yet :)

**Comment by Antiquete** [comment]
How about setting up a separate script for every single internal function we need in the menu and then calling that script instead?

**Comment by frostworx** [comment]
I'd like to keep it together in one single file if possible, to keep the "installation" for the user simple. That's why I also embedded the icons as base64 string and not simply as bundled assets and added the `DLGLOBAL` function.
Every required function could be added as command line parameter and the tray-icon menu could call "$0" with the required parameter, but that is not very nice as well.
Until there are no more use cases for implementing a tray icon menu I do not worry too much tbh though :)

**Comment by frostworx** [comment]
It is possible to call internal functions like
`bash -c pickWindowName`
when the function was exported before with
`export -f pickWindowName`

**Comment by frostworx** [comment]
added in https://github.com/frostworx/steamtinkerlaunch/commit/c6548fcb4bdbb185dc8ae259602b9f3f296d4905
