### ISSUE TITLE
HedgeModManager won't start

### ISSUE THREAD

**Issue by tmvkrpxl0** [sonic2kk/steamtinkerlaunch#711]
## System Information
- SteamTinkerLaunch version: steamtinkerlaunch-v12.0
- Distribution: Kubuntu Neon 5.26, based on Ubuntu 22.04
- Installation Method: ProtonUp-QT

## Issue Description
When I run `steamtinkerlaunch hmm start` it fails to launch

## Logs
 `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`: https://hastebin.com/ubakokozan.apache
 stdout: https://hastebin.com/uzonelafud.properties
 I've modified script little bit so that it also prints out wine command and wine output into stdout.
 wine command: `WINEPREFIX=/home/tmvkrpxl0/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx /home/tmvkrpxl0/.local/share/Steam/compatibilitytools.d/GE-Proton7-43/files/bin/wine /home/tmvkrpxl0/.config/steamtinkerlaunch/downloads/hedgemodmanager/HedgeModManager.exe `

**Comment by sonic2kk** [comment]
Did you attempt to install with Proton 5.0, as has been extensively documented in previous issues, as well as on [the Hedge Mod Manager wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Hedge-Mod-Manager#dependencies) and the [FAQ](https://github.com/sonic2kk/steamtinkerlaunch/wiki/FAQ)?

You should also ensure your Winetricks is up-to-date, as many distros will often package an out-of-date Winetricks version.

Closing as this is probably the 10th duplicate issue. Do research before opening issues please.
