### ISSUE TITLE
Wiki fixes - remove cheat tool usage references.

### ISSUE THREAD

**Issue by Lamphobic** [sonic2kk/steamtinkerlaunch#713]
Not a bug report or feature request (unless this should count as a feature request in which case apologies.) so done as a non-templated issue

I haven't comprehensively looked through the wiki but there are at least a couple high visibility references to using cheat engine and gameconquerer that can easily mislead people since they were removed. Specifically under https://github.com/sonic2kk/steamtinkerlaunch/wiki#tools and https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Collections#steam-collections

Mayhaps remove them?

**Comment by sonic2kk** [comment]
Definitely a good suggestion! I combed the wiki when I initially removed the tools but I suppose I missed this! I'll get these removed ASAP, thank you for making this issue and bringing it up! I'm not at my PC right now and unfortunately GitHub doesn't have great collaborative wiki support from what I understand, so it'll have to wait temporarily. I'll close this issue once I get around to removing these tools.

If you notice any more, feel free to comment on #457 with links to the pages just as you have done here. It's not a big deal to open another issue if you'd prefer though :-)

Thanks for bringing this to my attention!

**Comment by sonic2kk** [comment]
These pages should be updated now to remove mention of CheatEngine and GameConqueror. I also did a quick comb of the wiki again and didn't catch any other direct references, but I did update a screenshot that included the CheatEngine button.

Thanks again and please do report any other mentions that you see, or suggest any further improvements to the wiki. Generally #457 is probably the best place to bring these up, but if you would prefer make a separate issue please go ahead.

Thanks! Closing this issue now as the wiki should be updated :-)
