### ISSUE TITLE
Nier: Automata Waitrequester window not showing

### ISSUE THREAD

**Issue by LoKolbasz** [sonic2kk/steamtinkerlaunch#718]
## System Information
- SteamTinkerLaunch version: v12.0
- Distribution: Arch Linux
- Installation Method: AUR

## Issue Description

When trying to launch Nier: Automata via steamtinkerlaunch the `waitrequester` window displays only for the first time after installing steamtinkerlaunch. Even then, when clicking the `"Main Menu"` button the new menu doesn't display, and the game launches after a few seconds.

## Logs

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10387544/steamtinkerlaunch.log)
[524220.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10387545/524220.log)

## What I've tried so far

* Tried launching **Metal Gear Rising: Revengence** and **Insurgency sandstorm**. I was able to open the menu options with both of them.
* Restarting **Steam**
* Restarting the computer
* Increasing the requester timeout to 10
* Deleting both `~/.config/steamtinkerlaunch` `/dev/shm/steamtinkerlaunch/` and reinstalling the AUR package
  * The combination of these seems to have reset the program showing the `waitrequester` window with the behavior described above.

**Comment by sonic2kk** [comment]
Do you perhaps not have locales configured correctly on your system? Games like NieR:Automata require correctly configured locales, as the "real" game name has that pesky trademark symbol. There is some basic documentation on this on the [troubleshooting wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Troubleshooting#steamtinkerlaunch-starts-my-game-does-not-show-the-wait-requester). If you run a SteamTinkerLaunch command from the command line like `steamtinkerlaunch settings` and get a warning along the lines of "Locale Not Supported By C Library", then it is more than likely a locale issue. I battled with this for almost a year until I figured out the cause.

It's strange that it shows up the first time and not on subsequent loads though.

If you have other games that have symbols like this in their name, can you see if you can reproduce the issue with those games?

**Comment by LoKolbasz** [comment]
### Thanks for the quick response,

### The Issue

It turned out that it was indeed a locale problem. The KDE Plasma locale conflicted with the Arch Linux locale. When running the `locale` command it showed `LANG=C.UTF-8`, but when running `steamtinkerlaunch`  I couldn't see any error messages in the terminal.

### The Solution

The [ArchWiki](https://wiki.archlinux.org/title/locale#My_system_is_still_using_wrong_language) suggests removing the `~/.config/plasma-localerc` file but I ended up just editing the `LANG` variable to the proper utf-8 value.

#### A small suggestion

While searching for a solution I tried finding a solution through the [wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/) without following the `troubleshooting` link in the readme. However I couldn't find the [*Troubleshooting*](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Troubleshooting) page. So I think it would be a good idea to add a quick link for the page to the [wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/).

Thanks again for the help.

**Comment by sonic2kk** [comment]
Glad you got it sorted! I had a very similar problem which is why I documented.

That's a great suggestion to document the troubleshooting page on the wiki, probably in the links section under "Usage". Actually I'm not sure why it wasn't there to begin with, that was very silly on my part :-)

I'll update the links and then close this issue if that's alright. Thanks!

**Comment by sonic2kk** [comment]
Link has been added. Thanks for taking the time to search the wiki too, a lot of users don't bother.

Happy tinkering! *Closing*
