### ISSUE TITLE
Settings app is massive

### ISSUE THREAD

**Issue by LiamDawe** [sonic2kk/steamtinkerlaunch#73]
So uh, on first launch it gave me the biggest window I've ever seen :P https://imgur.com/a/IJqqLSF

Doesn't seem like I can resize it either.

**Comment by frostworx** [comment]
Which resolution is this?
Default is 1920x1080 (minimum - if the menu needs more it gets bigger)
Yes, you can't scale the window, but you can define width&height under Global Settings Tab (or edit global.conf).
I'm on a 3840x2160 desktop and the window is 2660x1433 which looks pretty good and that's the only resolution tested for now.
Might also help to disable the bundled gtk css (Global Settings Tab, the 2nd checkbox "Enable stl Steam theme")

**Comment by frostworx** [comment]
Oh, in case it is the css, help is very welcome to improve it :)

**Comment by frostworx** [comment]
hm, a 1920x1080 resolution and disabling the css doesn't help here :(

**Comment by frostworx** [comment]
I guess I'll have to replace the hardcoded font size with variables

**Comment by frostworx** [comment]
Disabling the CSS and reducing the general gtk fontsize works. So it is the CSS

**Comment by frostworx** [comment]
Yeah, me again.
I'll remove the font from the css completely and define all font-sizes directly with yad parameters using variables.
*should work*

**Comment by LiamDawe** [comment]
This is 1080p but I have two monitors, so perhaps something is detecting it at double resolution?

**Comment by frostworx** [comment]
Nah it is the hard-coded font-size in the CSS (which matches here to the upscaled Steam client resolution).
Please disable the CSS and check if the setting Menu has normal resolution when using your system gtk.
(fortunately I have no font definitions in the setting Menu, so this should work ootb)

**Comment by kkga** [comment]
On a 4k display the scale of the settings window is 4x (instead of 2x): https://0x0.st/iUHz.png

what does it depend on? any tips how to fix this?

**Comment by frostworx** [comment]
Please disable the CSS and check if the setting Menu has normal resolution when using your system gtk.

**Comment by kkga** [comment]
Yes, disabling the theme CSS fixed it, thank you :+1:

**Comment by frostworx** [comment]
nice, thanks for testing! (damn css!)

**Comment by frostworx** [comment]
@kkga:
would you please comment out/remove both
"font:" lines
in
`~/.local/share/themes/stl-steam/gtk-3.0/gtk.css`
and check if the css looks good without it?

one is on the top in
`.background {`
the other at the bottom in
`button {`

**Comment by kkga** [comment]
it does make it a bit more usable, but still not ideal.
the window becomes wider that the screen even though I have the width set to 1600px.
also looks like some parts of the UI are still not scaled properly, like the checkboxes.

![image](https://user-images.githubusercontent.com/1460122/94284831-98ddc900-ff5b-11ea-8d26-85a2eabe2456.png)

**Comment by dhollinger** [comment]
I'm also seeing these issues. My gtk.css I pulled from github don't have the font values at all, but it's still more than twice the size of my 1080p screen with no scrolling capabilities and it also appears that I cannot move the window, either

**Comment by frostworx** [comment]
I updated the gtk.css some hours ago which should fix at least the checkboxes.

The size of the window should now completely depend on the gtk font you use in your settings.
No matter which theme I use here (stl-steam or adwaita-dark, with a too big font the window is too big as well.
I use Arial Standard 18 here for now and the window looks acceptable with stl-steam and good with adwaita-dark (2579x1720)
With Arial Standard 9 the checkboxes are too big with stl-steam but it looks fine with adwaita-dark (1936x1096).
Of course so many options in one window needs some space, so it might be simply too much for 1080p (Arial Standard 9 should fit though). No idea if yad supports scroolbars, which would be perfect of course.

I consider to completely discard the stl-steam css stuff, as it costs too much "design time". Bad luck there's no fully fledged
steam gtk3 theme available.

**Comment by frostworx** [comment]
Yes yad supports scrolling simply with "--scroll" parameter

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/commit/4626cb047cb52dc16d4d86b18d889679fa34df4b
Might make playing with the size a bit easier.
The window is scalable now (the width+height do not autoupdate in the config, so changes can't be saved like that and will be lost - that's why I set it to fixed) and there is a scrollbar now.

**Comment by frostworx** [comment]
Probably the best option we have for multiple resolutions is
leaving scrolling enabled and
either removing the columns in the first 3 Tabs, so all 5 Tabs have one scrollable column
or make the columns configurable.
I'm now back on 3840x2160 desktop,  the stl resolution is set to 1200x800 in the 'Global Settings' and the gui looks good
with 18px font with both themes.
Any thoughts/suggestions welcome!

**Comment by frostworx** [comment]
Just released https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.0.3
```
added Column Selection for all Tabs to the Global Settings.
Should help with low screen resolutions
```
I also already updated AUR :)

**Comment by frostworx** [comment]
Is everybody happy with the changes in v2.0.3 and with the just released https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.0.4 _(which makes yad optional and opens the https://github.com/frostworx/steamtinkerlaunch#Editor-Dialog
instead of the https://github.com/frostworx/steamtinkerlaunch#Settings-Menu)_?
IMHO it is impossible to do more, but feel free to make suggestions! :)

**Comment by Antiquete** [comment]
> Is everybody happy with the changes in v2.0.3 and with the just released https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.0.4 _(which makes yad optional and opens the https://github.com/frostworx/steamtinkerlaunch#Editor-Dialog instead of the https://github.com/frostworx/steamtinkerlaunch#Settings-Menu)_?

Yes, atleast on my end, yad seems to be much more reliable post update 2.0.4. Settings inside global.conf also seem to control window size efficiently. I think we can safely close this and continue discussion in #81

**Comment by frostworx** [comment]
Thanks for the communication, @Antiquete
