### ISSUE TITLE
ERROR - startGame - Could not determine pid of wineserver

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#730]
## System Information
- SteamTinkerLaunch version: v12.12.20230129-1
- Distribution: Garuda Linux
- Installation Method: AUR

## Issue Description
Games do not launch with steamtinkerlaunch. (they do without)

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10548125/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Does this happen with v12 stable? Just wondering if it was some kind of regression with STL git or maybe something changed with the Steam client somehow.

**Comment by sonic2kk** [comment]
I can't reproduce with a handful of games I tested (on my Arch Linux PC and on Steam Deck) using STL git on my PC and STL v12 on my Steam Deck. I made sure to use Proton 7.0-5 and to use GameScope with the same options I could see that you were using from your log. I tested the following games:
- Cookie Clicker
- STEINS;GATE 0
- Sonic Adventure 2

I had a skim of the log and I can see the log line in question here:

```
Tue Jan 31 10:35:42 AM EST 2023 ERROR - startGame - Could not determine pid of '/home/zany130/.local/share/Steam/steamapps/common/Proton 7.0/dist/bin/wineserver'
```

Do you by any chance have any lingering wineserver processes? Sometimes some programs I run through Wine don't close properly (e.g. Amazon Music) and this causes games to not load. I can't recall if games without STL work. I would figure that it could be the case that a lingering wineserver process causes issues, if STL is looking for a wineserver and there are other ones that may be confusing it, I guess that could cause a problem. My understanding of how the PID check works here is not very deep as this is the first time I have really looked at it, but I think this could be the case.

Hopefully that's all it is and either quitting those processes or restarting can fix the issue :-)

**Comment by zany130** [comment]
I didn't get to testing stable, however,
I was testing so more, and strangely I can't reproduce it anymore. I restarted steam (new big picture sometimes bugs out after several game launches), and now it works :man_shrugging: 

It looks like something might of been out of whack with steam (though it is strange that on the same run of steam, I could play with proton 7.0-5 directly and couldn't with STL. I did test several times before restarting steam, so it wasn't just a one-time error with that specific game launch)

Sorry about that maybe I should of finish testing before reporting :sweat: 


EDIT: I just saw your message.
Yes, that actually could explain what happened, as I think closing steam also closes all wine processes started by it. So probably had a lingering wine process that was killed when I restarted steam

**Comment by sonic2kk** [comment]
No worries, it seems like something that could be specific to Steam / Steam Beta maybe, or just Wine in general having a little hiccup :-) Thanks!

(*Also nice to see GameScope being used hehe, I have fun working on the STL config for it :smile:)

**Comment by zany130** [comment]
yup good job on the new config it came out really good :heart:  strange though it ran fine without STL but maybe that's because of gamescope or something? when I ran directly with proton I didn't add gamescope or anything else to the launch commands.

**Comment by sonic2kk** [comment]
I think SteamTinkerLaunch won't start a game if it can't find the wineserver PID, which Steam doesn't do afaik (or if it does, it does it differently maybe). Since a specific STL check is causing the game to not launch I _think_ that's the problem :sweat_smile:
