### ISSUE TITLE
Tooltips in Settings Menu not displaying properly

### ISSUE THREAD

**Issue by ecbfry** [sonic2kk/steamtinkerlaunch#74]
When I open the settings menu, what I assume to be a tooltip is displayed immediately after the menu item, e.g.

GameMode!Enable GameMode for this game

This makes the settings menu very wide as there is so much text to fit in.

Am I missing a dependency?

![image](https://user-images.githubusercontent.com/50292974/94305034-7aca9580-ff68-11ea-9982-d2cd6e49ff70.png)

**Comment by ecbfry** [comment]
I'm guessing it could be because the version of yad in ubuntu 20.04 is v0.40.0, which is nearly 3 years old...

**Comment by frostworx** [comment]
Very likely that is the issue, please check that and tell us!

**Comment by frostworx** [comment]
...
