### ISSUE TITLE
A way to launch Tinkerlaunch with Steam Deck without launching game?

### ISSUE THREAD

**Issue by FormBurden** [sonic2kk/steamtinkerlaunch#740]
Hi, been using Steamtinkerlaunch for a good year now, really awesome software.

I was wondering if their is a way to launch STL without launching a game from Steam? Why? I mod Skyrim quite a lot, and sometimes can be hours, but I would rather not have my game time on Steam go up if I'm not actually playing it. I know, kinda dumb, but that's just me. Is there a way? 

Or would this have to be a different install method than the Steam Deck method to install STL? 

Thanks for your time!

**Comment by sonic2kk** [comment]
> I was wondering if their is a way to launch STL without launching a game from Steam? Why? I mod Skyrim quite a lot, and sometimes can be hours, but I would rather not have my game time on Steam go up if I'm not actually playing it. I know, kinda dumb, but that's just me. Is there a way?

There sure is! If you run `steamtinkerlaunch settings`, it will open the main menu for the last game you were playing. To select a different game, you can run `steamtinkerlaunch settings <app_id>`, which I actually didn't know until just now :wink:)

This works on both desktop and Steam Deck, however you'll have to have SteamTinkerLaunch on your path to do this - ProtonUp-Qt does this automatically including on Steam Deck, and on Desktop if you installed via package manager it should also be on your path. If you type `steamtinkerlaunch` from the command line and you get an error like "command not found", you can go to the folder where SteamTinkerLaunch is installed and run `./steamtinkerlaunch settings` instead (this runs the script directly).

iirc SteamTinkerLaunch started off as a command line tool, and has a *lot* of command-line functionality that I think goes mostly unused from what I have seen online. You can see all the command-line functionality available by typing `steamtinkerlaunch help` - I use it a lot for fetching AppIDs and Steam Deck compatibility info :-)

SteamTinkerLaunch is one big Bash script, and a lot of what it does "behind the scenes" is also exposed as command-line functionality. For example the "ModOrganizer 2" button on the main menu does pretty much the same thing as running `steamtinkerlaunch mo2 start` from the command line. Same goes for Vortex.

Let me know if this solves your issue.

**Comment by FormBurden** [comment]
Oh wow, I can't believe I didn't think about this. I've used the settings quite a few times in the past. Just didn't occur to me on the Steam Deck. Thanks for this! Tested, and everything works like normal.

**Comment by sonic2kk** [comment]
Glad to hear it! Happy tinkering :-)
