### ISSUE TITLE
HMM not working

### ISSUE THREAD

**Issue by DarkSparkish** [sonic2kk/steamtinkerlaunch#741]
## System Information
- SteamTinkerLaunch version: v11.12.20221211-1
- Distribution: EndeavourOS (Arch Linux)
- Installation Method: AUR

## Issue Description
As of recent, HedgeModManager decided to stop working. It has worked before, but since about the start of this year, I've noticed that HMM refuses to boot. I can boot Sonic Frontiers with the mods and cheats I've enabled before, but I can't launch HMM itself to pick and choose which mods and cheats I want. I've tried to reinstall HMM, but I still get no dice. The same applies to Sonic Generations, which I've had working effortlessly in the past. Maybe it's not an issue that's relevant to SteamTinkerLaunch,, but I still want to bring it up here in case it is. 

## Logs

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10716897/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Hi there! I don't think this is a SteamTinkerLaunch issue as nothing has really change with HMM support, it is possible that some of the HMM dependencies changed but I haven't heard anything about that, and the current latest HMM 7.9-0 works for me on my machine (also running Arch Linux). However, I will still attempt to help out.

First off, you are using an *incredibly* outdated version of SteamTinkerLaunch. That build is from December 11th 2022. You should update to SteamTinkerLaunch v12.0, though I don't recall there being many HMM changes past that point, you shouldn't stick to such an old release. The AUR package shouldn't even be using such an old release, it should be using [v12.0](https://aur.archlinux.org/packages/steamtinkerlaunch).

As well as this, you are also using an old version of Winetricks. You are using `20220411`, when the latest is ~~`20220411-next`~~ actually I just ran the self-update command, and the latest stable is actually [`20230212`](https://github.com/Winetricks/winetricks/releases/tag/20230212), and self-update brings me to `20230212-next`.

Instructions for updating Winetricks is available on the wiki.

Also ensure that the version of Proton you're running HMM with still exists. If it was a vanilla Proton build or something it may need bumped. I don't recall if STL handles version mismatches for these programs.

I'm not sure why HMM would've stopped working. I'm not sure how you reinstalled it, but you could try reinstalling it again using `steamtinkerlaunch hmm uninstall`, then reinstall, **ensuring you follow the guidance on the relevant wiki pages to install it with Proton 5.0**. Perhaps the prefix got messed up somehow, that's my only guess at the moment.

Do you know if any of the Winetricks dependencies for Hedge Mod Manager changed or if it requires other Winetricks?

If you run `steamtinkerlaunch hmm start` from the 

Also, the log you attached looks like a launch of Sonic Frontiers and not Hedge Mod Manager... You should launch Hedge Mod Manager and then attach the logfile, though I don't expect to gleam anything useful from it. After reinstalling you should also attach the `installDotNet` log for HMM itself (iirc it should be named like `installDotNet.log HMM`). That log file will give us a hint if dotnet48 is failing to install.

If the issue persists after this, you can try manually running the HMM prefix from the command line outside of STL and seeing if it comes back with any Wine errors. When running HMM, the `steamtinkerlaunch.log` file will show the following towards the bottom:
```
Sun 12 Feb 19:11:41 GMT 2023 INFO - startHMM - Starting HedgeModManager in prefix '/home/user/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx' with Wine '/home/user/.local/share/Steam/compatibilitytools.d/GE-Proton7-42/files/bin/wine' and using executable at '/home/user/.config/steamtinkerlaunch/downloads/hedgemodmanager/HedgeModManager.exe'
```

This means you can build the manual Wine command with this information. Please remember to change the paths to the one in the output command, do not blindly just copy/paste this command: `WINEPREFIX="/path/to/prefix" "/path/to/bin/wine" "/path/to/HedgeModManager.exe"`. Then whatever errors HMM is running into will be shown, probably.

<hr>

I don't think this is an STL issue but some kind of issue you'll need to troubleshoot regarding running Wine applications on your system.

Good luck!

**Comment by sonic2kk** [comment]
Out of curiosity I tried running with the latest Proton Experimental and Proton 7.0-6e, and I tried those both with the latest stable 7.9-0 and the latest nightly (thesupersonic16/hedgemodmanager@cb4490a). Both versions of Proton worked flawlessly for me with both stable and nightly.

This definitely seems like something related to the prefix got messed up, and even though you tried reinstalling, perhaps you missed a step somewhere.

**Comment by DarkSparkish** [comment]
I get a pop-up window stating: "rundll32.exe - The application could not be started" each time I try and boot HMM from a fresh reinstall. I could also be getting it at times when opening Sonic Frontiers. Could this correlate to anything?

**Comment by sonic2kk** [comment]
No, that is expected, [as per the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Hedge-Mod-Manager#installation). This is an issue related to dotnet48 not being fully supported with Proton and is known behaviour.
