### ISSUE TITLE
GNU make missing from hard dependencies for manual install

### ISSUE THREAD

**Issue by flisk** [sonic2kk/steamtinkerlaunch#746]
Just a quick note: on https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#hard-dependencies, GNU make is missing from the hard dependencies. Make isn't actually installed on every Linux system by default.

**Comment by sonic2kk** [comment]
I didn't know this, and this has been overlooked for a long time. I added a note about it, thanks!

I noted that this is only required for system-wide root installs, the kind that use `make install`, and I would like to confirm that this is correct, right? I don't believe that `make` is required anywhere else.

If this is right, though this *could* mean `make` falls under "Optional", technically so would some of the other hard dependencies. I would prefer to list `make` as a hard dependency as you suggested.

Let me know if you want any further edits for this :-)

**Comment by flisk** [comment]
Thanks for the quick response! I just reported this for a friend who ran into the problem while trying to `make install`, so as far as I know it's only required for that, but I really wouldn't know.

**Comment by sonic2kk** [comment]
Cheers, I always welcome contributions/corrections to docs :-)

Closing this issue as this should be solved now, thanks!
