### ISSUE TITLE
settings do not open

### ISSUE THREAD

**Issue by Raptime** [sonic2kk/steamtinkerlaunch#75]
Oh boy

> $ stl settings 
> which: no geany in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
> which: no netstat in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
> which: no vr-video-player in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
> Fri Sep 25 11:26:42 PM EDT 2020 WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
> which: no geany in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
> which: no gedit in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
> which: no leafpad in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
> which: no kwrite in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
> Fri Sep 25 11:26:43 PM EDT 2020 SKIP - updateEditor - no valid editor found - leaving 'xdg-open'
> Fri Sep 25 11:26:43 PM EDT 2020 INFO - openSettings - opening Settings
> yad: cannot create shared memory for key 31337: File exists

**Comment by Antiquete** [comment]
> yad: cannot create shared memory for key 31337: File exists

That's probably due to a stray yad instance, `ipcrm -M 31337` will kill it. However, even after that I was unable to open setting menu using `stl settings` on my end too.

**Comment by frostworx** [comment]
Yes, when yad fails it doesn't free its shm and blocks it for the further attempts.
I already have commented out `ipcrm -M 31337` in the code, but I'm not sure yet if it is a good idea (on the other hand it shouldn't hurt, so I might just add it at the beginning and at the end).

`which` should not be verbose of course, I'll redirect the output to /dev/null to silence it.

**Comment by Antiquete** [comment]
Could there be a check of some kind to make sure yad launched correctly? If not, scripts informs the user and opens the settings file in traditional way using the xdg-open.

**Comment by frostworx** [comment]
I don't think you can capture the yad launch somewhere (I do not really know yad though), but I considered adding an option to not use yad at all (and therefore not depend on it).
It worked fine without til the 2.0 release so yad should still not be a hard dependency.
Apart from that yad is a mighty beast, but it apparently also leads to many new issues, which should be optional.

**Comment by frostworx** [comment]
https://github.com/frostworx/steamtinkerlaunch/issues/78
