### ISSUE TITLE
MO2 installed & configured via the terminal in desktop mode launches without access to my portable instance, mods, and mod lists 

### ISSUE THREAD

**Issue by MustacheEmperor** [sonic2kk/steamtinkerlaunch#751]
## System Information
- SteamTinkerLaunch version: v12.0
- Distribution: SteamOS
- Installation Method: Package Manager 

## Issue Description

I installed ModOrganizer2 from the terminal using the provided command `steamtinkerlaunch mo2 start`. I followed the prompts to create a portable instance on my SD card, then configured a modlist for Skyrim SE. 

I launched Skyrim with SteamTinkerLaunch set as its compatibility tool, and opened the STL menu. There I switched the category to MO2, and set it to "gui" instead of "disabled." When I hit "Play" or skip the menu prompt when launching Skyrim, MO2 starts up but my mod list is not visible. I checked the MO2 settings menu and it's pointed at Wine's virtual C:\ folder for the base installation with hardcoded directories for everything else. 

Does STL support using portable instances with MO2? How can I point STL's "Game Mode" installation of MO2 to the same folders I configured it with on the desktop?  Otherwise, what's the best way to proceed if I want to install mods on my SD card, for a copy of Skyrim SE also installed on the SD card?

**Comment by sonic2kk** [comment]
I believe instances are managed using MO2 in Standalone Mode, e.g. `steamtinkerlaunch mo2 start` or using the ModOrganizer 2 button. Using MO2 in Game Mode should use the the modlist properly, if it's not you should be able to select it from the MO2 UI.

This seems like more of a general MO2 usage question which I cannot answer much, and I don't mod games on my Steam Deck where I can help it.

> Does STL support using portable instances with MO2?

I remember Frostworx, the creator and the one who implemented this, referring to portable instances, and I vaguely remember some other users mentioning using portable instances without issue. So I think so? But I am not totally sure, sorry :frowning: 

For me if I go to the MO2 File Menu -> Manage Instance and double click on a different instance, it will switch to it. Perhaps this will work for you too? You should be able to do this from MO2 Game Mode I think as you're just switching to the **same** game instance.

> Otherwise, what's the best way to proceed if I want to install mods on my SD card, for a copy of Skyrim SE also installed on the SD card?

I think you can point MO2 to use a different mods folder, under Tools -> Paths -> and from here you can change the mods folder path. However if you already have a mod list configured I would say surely there must be a way to point MO2 to use this. I am not an avid MO2 user, I have only modded games on my desktop using whatever the default MO2 instance settings were so I am unsure of more advanced MO2 usage on Linux or Windows.

**Comment by sonic2kk** [comment]
Oh I just remembered, a user had to jump through extra hoops to do this on Steam Deck, see [their instructions here](https://github.com/sonic2kk/steamtinkerlaunch/issues/692). These steps meant mostly nothing to me but it was documented on the modding wiki. It seems like the SD card on the Steam Deck causes issues though.

**Comment by sonic2kk** [comment]
One other thing I'd like to point out: Package Manager installations of SteamTinkerLaunch on Steam Deck **are not supported**.  Likely unrelated to this issue, I'm just letting you know that no support will be given for a package manager installation on Steam Deck, and you WILL lose SteamTinkerLaunch when you update.

Please install SteamTinkerLaunch manually or with ProtonUp-Qt on Steam Deck instead of with Pacman.

**Comment by MustacheEmperor** [comment]
Thanks for the support. I found this project via the top google results for getting ModOrganizer 2 to run on the steam deck, so I thought it might be a common use case. 

I tried editing the instance settings within the MO2 window opened by STL to match the profile I already configured, and that seems to work - it's loading my profiles, and I can launch the game. I've only tried with a couple simple graphics mods, but it looks like it's working. 

That said, SteamTinkerLaunch can't even see the instance I created from the desktop view. I checked the Instances menu after launching MO2 from the STL game menu, and SteamTinkerLaunch can't see any instances except for the "Portable" instance of Skyrim SE it's created for itself. 

When I launch MO2 from the console command on desktop, it can see the instance created by SteamTinkerLaunch, and the instance I created and configured. I think that this does indicate an issue with STL or its documentation, since I would expect the intended behavior is that the instances accessible from within the view launched from the terminal in desktop are also accessible from the game mode. But that is of course up to the project's maintainers, and I might be doing something that's not meant to be supported. I have a decent knowhow of Linux, but know next to nothing about the proton/wine compatibility universe. 

Thanks for linking that other user's issue. I haven't messed with manual symlinking at all, I just utilize the library management built into the steam GUI. I think their problems may not apply to me since I'm not swapping around SD cards, so it looks like the simpler solution worked in my case. 

I'll leave it up to maintainers whether or not instances created in desktop not appearing in game mode should be tracked as an issue or if this should be closed. I noticed that MO2 did not detect my Skyrim SE install when launched - it autodetected the games on my internal storage, but I had to manually locate the folder on my SD card with SSE.

**Comment by sonic2kk** [comment]
>  I found this project via the top google results for getting ModOrganizer 2 to run on the steam deck, so I thought it might be a common use case.

That's neat to hear! Unfortunately I don't know much about more advanced MO2 usage. I will point out too that MO2 is only part of what STL does and it was created **without** the Steam Deck in mind - SteamTinkerLaunch is first and foremost a tool for the Linux Desktop.

Having said that, I don't know if MO2 portable instances work differently on the desktop. Perhaps however Wine maps the SD card is causing issues but that's just a (slightly educated) guess based on the little I understand from the user's comment I linked.

> I'll leave it up to maintainers whether or not instances created in desktop not appearing in game mode should be tracked as an issue or if this should be closed. I noticed that MO2 did not detect my Skyrim SE install when launched - it autodetected the games on my internal storage, but I had to manually locate the folder on my SD card with SSE.

The maintainer is only me :-) It will be up to the community to submit fixes for this I think. I don't think the wiki really documents portable instances much aside from the link I gave you which can be found on the general modding page. Imo unless a user steps up to improve or better document this process, that's all the documentation required for now. SteamTinkerLaunch is intended for tinkerers (like yourself it sounds like) and tinkerers are good at contributing documentation improvements and sometimes even features and bug fixes.

It sounds like you got it working albeit with some manual intervention required, so I'll close this issue. My lack of knowledge on general MO2 usage is probably not ideal here, I understand the process mostly of how STL sets up the MO2 wine stuff but for MO2 application behaviour I'm much less knowledgable unfortunately.

My hope is that someone kind volunteer(s) can come forward from the community and help document and maintain SteamTinkerLaunch. If you would like to and have some time (after you're done adventuring around Skyrim 😉) please feel free to write out some documentation (ideally in the dedicated wiki issue) if you feel there should be better documentation. You can outline where you want it to go on the wiki and I'll update it. Unfortunately GitHub is not great for collaborative wiki editing as far as I know so I think this is the most painless way. Feel free to attach it as a markdown doc if it gets too long :-)

Thanks for reporting and investigating, and getting involved, and sorry again that I couldn't be of too much, but I'm more than open to documentation improvements (across all of STL) and code contributions, so if you see anyone around that's interested please do encourage them to improve STL for everyone! Support coming from people that are familiar with MO2 will have better results than me trying to understand and implement something, and I don't have as much time at the current moment to research and deeply contribute to STL MO2 stuff.

Good luck!
