### ISSUE TITLE
Steams Browser makes logging into Nexus Impossible

### ISSUE THREAD

**Issue by Krythulu** [sonic2kk/steamtinkerlaunch#752]
## System Information
- SteamTinkerLaunch version: v12
- Distribution: SteamOS
- Installation Method: ProtonUp-Qt

## Issue Description
I've been attempting to install mods for about 4 hours now, seeing that my game is installed via SD Card I've been trying to use this as an alternative to MO2 for Linux but due to how the Steam Deck Game mode is made, using MO2 via STL in Game mode is impossible. Launching New Vegas for example, clicking MO2, opening the Nexus webpage for New Vegas, then trying to Log in leads to an endless loading screen. Because of this installing mods while in Game Mode is impossible. 

This problem both stops the ability to install mods via the Vortex and the Manual link as both require the user to sign into an account to download. Making this program completely unusable

**Comment by sonic2kk** [comment]
You shouldn't mod from Game Mode on Steam Deck, I believe this is even noted on the wiki. You should mod from Desktop Mode. Why on earth are you trying to do this from Game Mode?

This is general Steam Deck usage for all GUI applications, you're going to run into a lot of ossues.

Also, link handling may not work at all, you should install mods manually.

> Making this program completely unusable

It should be clear that when using *any* GUI program, you should avoid doing it from Game Mode on your Steam Deck. This would be like trying to use MO2 to mod inside of GameScope on a Linux Desktop, it just doesn't make any sense.

**Comment by Krythulu** [comment]
apologies, I'm still new to the steam deck and genuinely thought this was unusable

**Comment by sonic2kk** [comment]
SteamTinkerLaunch is for experienced Linux users, ideally thise who have already used it on their desktop 👍 If you don't have a Linux Desktop I don't recommend using SteamTinkerLaunch
