### ISSUE TITLE
Ubisoft Connect has network error when running STL, works without STL.

### ISSUE THREAD

**Issue by veritas0x0** [sonic2kk/steamtinkerlaunch#753]
## System Information
- SteamTinkerLaunch version: v12.0
- Distribution: SteamOS
- Installation Method: ProtonUp-Qt

## Issue Description
Ubisoft Connect added as non-Steam game. Works as expected when not using STL, when STL is set, Ubisoft Connect does not have a network connection. Ensured network killswitch is not enabled, disabling STL and switching to Proton-GE 49 directly works properly.

## Logs
[logs.tar.gz](https://github.com/sonic2kk/steamtinkerlaunch/files/10830228/logs.tar.gz)
[steamtinkerlaunch.tar.gz](https://github.com/sonic2kk/steamtinkerlaunch/files/10830229/steamtinkerlaunch.tar.gz)

**Comment by sonic2kk** [comment]
I don't have any Ubisoft games to test with and don't plan to buy any, but I don't have much interest in trying to work around invasive launchers. Likely there is some DRM issue with Ubisoft Connect similar to what appears to go wrong with the new EA app.

You can try with SteamTinkerLaunch-git (available from ProtonUp-Qt under Advanced Mode, pointing it out as not everyone enables this) as it has some Steam Linux Runtime fixes, but unless someone with these games steps up and can fix it, SteamTinkerLaunch won't support these games.

**Comment by sonic2kk** [comment]
Just re-read and seen you added Ubisoft Connect as a Non-Steam game. This isn't intended usage and will actually never really be supported from the SteamTinkerLaunch side. SteamTinkerLaunch doesn't support playing games bought on other storefronts.

As well as this, SteamTinkerLaunch is **not** here to provide support with every third-party app you can run as a custom program. Users are the ones that have to do the legwork to get custom programs to run, just like they would when running custom programs with Proton outside of SteamTinkerLaunch. You are expected to be a tinkerer when using Steam**Tinker**Launch.
