### ISSUE TITLE
Vortex is different after upgrade

### ISSUE THREAD

**Issue by Raptime** [sonic2kk/steamtinkerlaunch#76]
Upgraded to 2.0.3-1 and Vortex now says that I have to purge my mods because they were installed by a different Vortex instance, is it intended?

**Comment by frostworx** [comment]
I haven't touched anything Vortex related and have no idea how any stl update should trigger that requester anyway.
Did you maybe change the wine version used for vortex or removed your vortex wineprefix in between?
Would be interesting to know what caused this.

**Comment by Raptime** [comment]
It could very well be a mistake on my side, I messed around with the configs quite a bit, I just reinstalled my mods and it's all fine now :)

**Comment by frostworx** [comment]
Ah good to hear! :)
