### ISSUE TITLE
⚠ Translating SteamTinkerLaunch

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#760]
This issue exists to bring awareness to keeping the SteamTinkerLaunch translation files up-to-date. 

SteamTinkerLaunch is currently available in 8 languages:
- Chinese
- Dutch
- English (including English UK)
- French
- German
- Italian
- Polish
- Russian

This is great, but unfortunately I only speak English, and whenever I add new features the translation files do not get translated strings. There are currently several untranslated strings. All translations except for English are community-submitted and community-maintained.

If anyone is able and willing, updates to the translation files would be very welcome! You don't have to update the entire translation, just the strings here and there that you know how to translate is enough. Likewise, if you want to submit a **new** translation, the same applies - though of course, please try and translate as much as you can! Further information can be found in the [CONTRIBUTING.md](https://github.com/sonic2kk/steamtinkerlaunch/blob/master/CONTRIBUTING.md#translations-1) file.

Many thanks to all who have taken the time to submit their translations :slightly_smiling_face:

**Comment by Laz55** [comment]
Still issues on  with Days Gone , Steelrising,  Resident Evil 5 not loading up Steam tinker.

**Comment by sonic2kk** [comment]
The Chinese translation received a great update in #856.

**Comment by sonic2kk** [comment]
The Steam Deck Compatibility strings were updated in #887 based on the latest available from the Steam Client at time of writing ([SteamDatabase link](https://github.com/SteamDatabase/SteamTracking/tree/master/ClientExtracted/steamui/localization)).

These translated strings are only as good as the ones provided by the Steam Client, so if these change they would still need to be updated.

**Comment by sonic2kk** [comment]
This did not garner as much community interest as I had hoped. I'll close this but please don't hesitate to submit translations! It will be an ongoing effort but all work is appreciated.

**Comment by Laz55** [comment]
It was never fixed and never worked the installation  didn't work. I didn't
know why you marked it as closed and fixed.
