### ISSUE TITLE
Can't get ReShade working with FFXIV, documentation unclear

### ISSUE THREAD

**Issue by yaomtc** [sonic2kk/steamtinkerlaunch#762]
## System Information
- SteamTinkerLaunch version: 12.0
- Distribution: Arch Linux
- Installation Method: Package manager / AUR

## Issue Description
I'm following [the instructions here](https://github.com/sonic2kk/steamtinkerlaunch/wiki/ReShade), but it's a bit unclear. 

1. It tells me to rename files in RESHADESRCDIR, but where is it?
2. It says "in Game Menu and Game Config". Do I need to change settings in both? If not, this should say "or"
3. It says "they will be placed in the game directory under the required name" but I don't see any of these files in the game directory, despite these settings enabled:

- Game Shaders > reshade-shaders
- Game Menu > ReShade Enable, ReShade install, ReShade update
- Alternative game exe path: ~/.local/share/Steam/steamapps/common/FINAL FANTASY XIV Online/game/

Due to the files not being present, when I start the game, the ReShade overlay does not appear.

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10974853/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Sorry, ReShade support was added a long time ago and not by me, I am unfamiliar with how it works. However, I thought it was just a case of enabling and using it. I have never used ReShade before ever including with STL, but I will try to answer your questions as best as I can :-)

1. I don't see anything on the linked wiki page for renaming any files
2. You don't need to do it in both places, the Game Menu modifies the Game Config. The part of the wiki you're referring to is letting you know where `INSTALL_RESHADE` is located (and the variable name). Updates to documentation are very welcome as the ReShade wiki was written by someone who was not a native English speaker and has only seen [minor revisions](https://github.com/sonic2kk/steamtinkerlaunch/wiki/ReShade/_compare/c82678fae1de936c38191d29108df3679a8a5074...de42aa9ffa5a7bf96fa9c8047a76cc0752c6da44).
3. The files it's referring to are the DLLs correct? The `d3dcompiler_47.dll` I believe is what should be added somewhere in the game files for FFXIV (downloaded as `d3dcompiler_47_64.dll` but renamed by STL if I recall from the code correctly)

Looking at the logs I can't see any logging information about ReShade being enabled. Is the "ReShade Enable" checkbox checked on the Game Menu?

<hr>

Though I am an outsider looking in here as I am not a big fan or user of tools like ReShade, I would also agree that the documentation is unclear and could be improved. However I am not in a great position to update it very much. The parts which I do understand were those that were added fairly recently by a contributor who made some improvements to ReShade support, as I reviewed those and was familiar with the PR related to those improvements, but the rest is foreign to me as I only understand at a very high level how ReShade is meant to be used.

cc @zany130, I believe you are more familiar with ReShade, so any insight that you have here would be welcome too :-)

**Comment by yaomtc** [comment]
1. Here is the relevant portion:

> If DOWNLOAD_RESHADE is set to 1, all required files for ReShade are [downloaded](https://github.com/frostworx/steamtinkerlaunch/wiki/Downloads) once into RESHADESRCDIR of course, you can install all files manually as well. **make sure to rename all files correctly:**

> 64bit d3dcompiler_47.dll: -> d3dcompiler_47_64.dll 32bit d3dcompiler_47.dll: -> d3dcompiler_47_32.dll ReShade64.dll, ReShade32.dll: renaming is not required as they will be placed in the game directory under the required name.
2. Good to know, thank you.
3. I have the reshade-shaders folder and d3d-compiler_47.dll (which I have now renamed to d3dcompiler_47_64.dll, and after running the game I now have another d3dcompiler_47.dll). However I do not have either ReShade64.dll or ReShade32.dll. Not sure why.

Yes, "ReShade enable" is checked as mentioned above

If I can manage to get ReShade working via SteamTinkerLaunch, I'll correct/improve that wiki page myself

**Comment by sonic2kk** [comment]
> However I do not have either ReShade64.dll or ReShade32.dll. Not sure why.

Ahhh and I guess this would be why ReShade is not loading? I would guess that the d3d DLL(s) interface with the ReShade DLL(s) and inject it into the game, which loads the ReShade overlay you mentioned.

Okay, my next question then is to ensure that `Install ReShade` is checked. I'm just going by the tooltip which says "Install ReShade into the game directory". From reading the wiki (though it is somewhat unclear to me) it seems that both the "Use ReShade" and "Install ReShade" checkboxes have to be enabled before the ReShade DLLs will be installed to the selected game folder.

If both of these options were not enabled try enabling them and launching the game. If it still doesn't work please attach another log, I'd like to sift through it and see what ReShade logging I can find.

> If I can manage to get ReShade working via SteamTinkerLaunch, I'll correct/improve that wiki page myself

Much appreciated! :smile: 

<hr>

Also, I just checked for you, and `RESHADESRCDIR` is in `~/.config/steamtinkerlaunch/downloads/reshade`. Though again you shouldn't need to touch anything here I don't think. Just letting you know :-)

**Comment by zany130** [comment]
Cleaned up the wiki by moving the manual installation into its own place. You shouldn't need to do anything manually.

As sonic2kk mentioned, you need to make sure you enable both the use and install ReShade options. Kinda confusing I agree; I  have considered merging the two functions but never got around to it 😅

Basically, the enable option is there for disabling/reenabling (it adds a `_off` to the end of the file if I remember correctly ReShade and the install option actually copies the files for you into the correct place

so fun fact if you check install but don't check to enable I think it will copy the files but then disable them

**Comment by zany130** [comment]
Also, @yaomtc brought up a good point @sonic2kk  in the wiki we refer to different steamtinkerlaunch locations by there configurable environment variable, and I don't think we really document what they refer to anywhere in the wiki?


EDIT: there's this wiki page https://github.com/sonic2kk/steamtinkerlaunch/wiki/Paths  but it doesn't mention the default locations

EDIT2: did a quick and dirty edit of that page to include the default paths based on what's written out on my global config file.

Maybe we should make the page more visible? (better name and in the quick links)

**Comment by sonic2kk** [comment]
Been a few days, was there any update here? Did enabling both options lead to any success?

On a related note, merging the two ReShade options into one somehow is probably a good idea and something I'll make a note of for a future enhancement. No plans to work on it immediately but could be a good area for potential interested contributors

**Comment by yaomtc** [comment]
> despite these settings enabled:
> [...]
> * Game Menu > ReShade **Enable**, ReShade **install**, ReShade update
