### ISSUE TITLE
Using Gamescope GUI to configure it crashes games

### ISSUE THREAD

**Issue by kaymueller** [sonic2kk/steamtinkerlaunch#763]
## System Information
- SteamTinkerLaunch version: 12.0-2
- Distribution: Manjaro
- Installation Method: AUR

## Issue Description
When I use the Gamescope Button in the main menu to configure it, every game will crash immediately. 

## Fix/Workaround
What fixes it for me is going into the game menu, scrolling down to the gamescope arguments and removing the leading "Spacebar" in the text box. I also have to remove this leading "Spacebar" every time I go back to the game menu to not let the game crash at start.

**Comment by sonic2kk** [comment]
I didn't experience this on 12.0 but can you still reproduce this with 12.12? It had a significant change to GameScope logic.

However a leading spacebar would probably cause a crash, I could see that happening. I didn't notice anything before in v12 though and I didn't notice anything like this when testing the changes v12.12. The leading spacebar would probably throw off how the GameScope arguments are constructed, it may try to insert some kind of blank argument which will usually cause commands to fail. For example, `"gamescope" "--" "supertuxkart"` will work, but `"gamescope" "--" "" "supertuxkart"` will fail.

It would also be helpful if you could outline what GameScope options you are using, if the issue persists with v12.12

**Comment by kaymueller** [comment]
Sorry, I actually didn't see that there was a new release from two days ago. That was stupid.

Tested one more time with old Version:
1. Went into the game menu
2. deleted all the arguments in the gamescope textbox
3. went back to main menu and set gamescope up again through the GUI
4. Crash

So I removed 12.0-2 from the AUR, upgraded STL with ProtonUp-Qt. Tested again:
1. Went into the game menu
2. deleted all the arguments in the gamescope textbox
3. went back to main menu and set gamescope up again through the GUI 
4. **No** Crash

> even tho, there is still a leading Space in the arguments text box

So whatever it was that mangled it, it's gone now

**Comment by sonic2kk** [comment]
I think there may have been a couple of options that put in a trailing space when there shouldn't have been. I remember fixing something around that for the GameScope overhauls. There is also a lot more catching for removing trailing spaces in the GameScope command. Most of the GameScope code was completely overhauled with v12.12 so there were a lot of things that could've fixed it.

I'm very glad to hear it's working now! I'll see if I can update the AUR package later, I think I have the permissions now to update it. No worries about not seeing the release either, it's easy to miss. I know I usually just rely on the package manager to update stuff for me ;-) Plus it seems like something was broken in v12 though, but thankfully it's fixed now.

Thank you for testing! :-)
