### ISSUE TITLE
Overriding Steam Tray Icon

### ISSUE THREAD

**Issue by PeakKS** [sonic2kk/steamtinkerlaunch#765]
## System Information
- SteamTinkerLaunch version: v12.0
- Distribution: Gentoo
- Installation Method: Portage, guru overlay

## Issue Description
Whenever I click the steam tray icon it opens steamtinkerlaunch instead. If I right click the icon I still get the steam settings though.
[tray_icon_hijack.webm](https://user-images.githubusercontent.com/48360696/226355488-2c739e7a-aa9d-4d80-a0b2-97b3ae526e14.webm)

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11018798/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
This is a Desktop Environment/Yad issue and not a SteamTinkerLaunch issue, there isn't anything I can really do about this I'm afraid. Sorry about that :frowning: 

It might be worth trying to reproduce generally with Yad and reporting it upstream if you can do it with a minimal reproduction test-case.

<hr>

As a workaround, if you don't use the tray icon, you can disable it in the SteamTinkerLaunch Global Menu: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Tray-Icon

<hr>

There were no changes to the tray icon addition for a *very* long time, but just as a courtesy heads-up, you're using an outdated version of SteamTinkerLaunch. You might want to ask whoever the STL Gentoo package maintainer is to update it :-)

The Yad version in use is also very old, v10.1, which is from [May 2021](https://github.com/v1cont/yad/releases/tag/v10.1). It is possible that a newer version of Yad could fix this issue. The latest available Yad version is 12.3, so I would also recommend trying that before potentially reporting any issues upstream.

**Comment by PeakKS** [comment]
Did a bit more digging and it seems this is an issue with the  [tray icons reloaded gnome extension](https://github.com/MartinPL/Tray-Icons-Reloaded/blob/5891310a217cd80416c057d87d4a25e4787afb92/AppManager.js#L97). If steam is not already open it prefers steamtinkerlaunch for whatever reason.

**Comment by sonic2kk** [comment]
Thanks, I will make a note of this on the wiki :+1: 

EDIT: Added: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Tray-Icon#gnome-tray-icons-reloaded-extension
