### ISSUE TITLE
HMM no longer launching on Deck after a reinstall 

### ISSUE THREAD

**Issue by EVDESTROYER** [sonic2kk/steamtinkerlaunch#766]
## System Information
- STL Version: 12.12
- Distribution: SteamOS
- Installation Method: Flatpak with ProtonUp-Qt

## Issue Description
After the recent Sonic Frontiers update, the game was no longer launching. After trying a couple different solutions, I decided to try and reinstall HMM and STL entirely to see if that would fix the problem. Unfortunately, now HMM is not launching at all. I have tried uninstalling and reinstalling both STL and HMM several times with Proton 5.0, using different versions of Proton to launch it, deleted my winetricks folder, and deleted the HMM compatdata folder. When I am installing it, a winetricks gui that didn't show up when I installed it before pops up several times (shown below), I'm not sure if it's related to the issue.

## Logs

[steamtinkerlaunch-install.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11064870/steamtinkerlaunch-install.log)
[steamtinkerlaunch-post-install.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11064872/steamtinkerlaunch-post-install.log)
![winetricksgui](https://user-images.githubusercontent.com/118212562/227596612-2b9d306e-6e5e-47b4-9ff3-24a32a5193a2.jpg)

**Comment by sonic2kk** [comment]
By the sounds of it, this is a DotNet and Wine issue and not something I can fix, sorry. You can try manually installing `dotnet48` with Winetricks using various different versions of Proton/Wine etc, but I'm not a Wine developer and can't fix the unreliability of dotnet48 failing to install on the Steam Deck.

Sorry I can't help much more :frowning: I believe GamingOnLinux has a guide that goes through a more granular and manual dotnet48 installation process for Steam Deck specifically, perhaps that will be of some use to you. But really this is some kind of Wine issue and not something really anyone could do anything about. dotnet is a massive pain for gaming on Linux in general but seems to generally work fine on desktop, though I've seen for other games especially the last few months that dotnet48 just does not work for them.

There should also be some HMM Wine output in `/dev/shm/steamtinkerlaunch`. You could take a look at that and see if you can figure out any missing DLLs or components that may need to be installed manually.
