### ISSUE TITLE
Log typo

### ISSUE THREAD

**Issue by Welld1s** [sonic2kk/steamtinkerlaunch#768]
Tue Mar 28 02:33:50 PM MSK 2023 INFO - setFullGameExePath - User did not enable 'CUSTOMCMDRESHADE' - Using the game's exe **directroy** as the ReShade installation directory

directroy -> directory

**Comment by sonic2kk** [comment]
Thanks! Feel free to open a PR if you'd like, or I can fix it myself. Either works :-)

**Comment by Welld1s** [comment]
Done.
https://github.com/sonic2kk/steamtinkerlaunch/pull/769
