### ISSUE TITLE
User tweak file vs gamecfg file

### ISSUE THREAD

**Issue by Raptime** [sonic2kk/steamtinkerlaunch#77]
Hello,
Should I make edits to the gamecfg file or should I use a tweak file? What's recommended and why have both?

**Comment by frostworx** [comment]
Please read the README.
Your personal config files are the gamefiles, the small tweakfiles are supposed to be user-exchangable override files which fix things and make games to work ootb.
So when f.e. someone got a game to work, the required tweaks could be added here as pull request, so the tweak
will be part of https://github.com/frostworx/steamtinkerlaunch/tree/master/tweaks/user
and the game works for everybody ootb.

**Comment by Raptime** [comment]
Roger that, thanks for the clarification!

**Comment by frostworx** [comment]
yw. Feel free to contribute tweaks if you have some ready ;)
