### ISSUE TITLE
How i use steamtinkerlaunch on a Wiiu game? (cemu)

### ISSUE THREAD

**Issue by Conan179** [sonic2kk/steamtinkerlaunch#775]
Hello.
How can I use steamtinkerlaunch on a Wiiu game running in cemu?
Cemu is Native Linux, if I enter steamtinkerlaunch in the command line, where it already says "vblank_mode=0 %command% -f -g "Z:/run/media/400gb/Emulation/roms/wiiu/roms/einspiel.wua", it doesn't even start.

**Comment by sonic2kk** [comment]
If `vblank_mode=0 steamtinkerlaunch  %command% <rest-of-command-here` doesn't work then I'm not sure. Given the path I *assume* you're not on Steam Deck, where #630 prevents native STL from working in Game Mode.

One possible solution is to copy that command and set it as the game arguments in STL, but I am not sure if this works for Cemu. See the below screenshot:

![image](https://user-images.githubusercontent.com/7917345/229293480-f6444574-274f-4c10-ae48-08bc98e844bf.png)

Take care to remove trailing spaces from the beginning and end as well, if there are any.

I am not sure how Steam manages exporting environment variables here so you may have to manually add this as an environment variable for your game, though Cemu should use Vulkan so I don't know if this option does anything...

<hr>

Also, you would've been presented with an issue template when you created your issue. Please take care to fill this in when reporting issues - Although this is not a bug, even if STL doesn't work with something like Cemu it would be an enhancement :-)

Good luck!

**Comment by sonic2kk** [comment]
Bump, normally wouldn't bump so soon but as this was a usage question rather than a bug report just wondering if there was any resolution.

**Comment by Conan179** [comment]
I haven't gotten around to testing it yet, I was too busy at the weekend. -.-

And sorry for the "bug" label, that was a misjudgment on my part, sorry.

**Comment by sonic2kk** [comment]
No rush, a minor observation from the code suggests that paths with spaces may cause issues which is something I am looking into anyway :-) The quotes will be stripped from the file path once saved but I am unsure if this would cause issues. I don't have Cemu installed to test but in my testing it didn't cause any game crashes, but it is something to keep in mind if you run into further issues.

You also should not need `Z:\` since Cemu is native Linux, simply passing ` -f -g "/run/media/400gb/Emulation/roms/wiiu/roms/einspiel.wua"` should work I think? `Z:\` is for Wine only, unless Cemu for some reason expects this kind of path formatting. Not related to STL usage or anything it was just something I wanted to point out, along with the vblank observation :slightly_smiling_face:

**Comment by Conan179** [comment]
>  should work I think? `Z:\` is for Wine only, unless Cemu for some reason expects this kind of path formatting.

I can explain that now, I made a mistake, the cemu where emudeck uses is not native but a windows exe.
Yesterday I went through the emudeck github and looked at the start script (I currently don't have access to my steamdeck) https://github.com/dragoonDorise/EmuDeck/blob/main/tools/launchers/cemu.sh

># Cemu.exe location
>CEMU="/run/media/mmcblk0p1/Emulation/roms/wiiu/Cemu.exe"

So the error is from the device and not stl doing something wrong. I'm sorry.

**Comment by sonic2kk** [comment]
No worries, thanks for the follow-up. You may be able to set the Cemu start script as the STL custom program though when it comes to passing arguments to custom commands, that's not something I've tried before. You'll be on your own when it comes to tinkering around here, but hopefully it goes ok! 

Good luck and happy tinkering :-)

**Comment by Conan179** [comment]
So I can now explain how I came to the conclusion that cemu was native. I had a small graphics bug in the "preview" channel that tricked me into thinking it was native.
![2023-04-04 19 26 13](https://user-images.githubusercontent.com/1906242/229894102-84563ef9-0538-444c-bcc7-f74f177fdacd.jpg)
But when I start the game and exit it again, the menu looks like this:
![2023-04-04 20 46 16](https://user-images.githubusercontent.com/1906242/229894284-94baf650-7c11-4e60-ae37-9617ff5efec7.jpg)
And that's how it goes, of course.
![2023-04-04 20 52 04](https://user-images.githubusercontent.com/1906242/229894524-99fa55b3-48d7-4a6e-ab30-ae5574da0aa2.jpg)
![2023-04-04 20 52 09](https://user-images.githubusercontent.com/1906242/229894542-51c53d09-c4ae-46a0-875e-e762d320d729.jpg)
Yes, I know version V11.11 is outdated, I was concerned with the "Cheatengine" program that was still part of it.
