### ISSUE TITLE
Vortex can't open Google Chrome for download/login on Steam Deck

### ISSUE THREAD

**Issue by FahriBilici** [sonic2kk/steamtinkerlaunch#777]
I installed steamtinkerlaunch using protonQt. then added `$HOME/stl/prefix/steamtinkerlaunch %command%` as launch options to Baldur's Gate 3. Then I downloaded and installed vortex and I can open the vortex. When I tried to enter my account using buttons it didn't automatically open the nexus website but I copied the link on the screen and paste it on to browser then I could authorize it. But now when I click to get more mods or other links it doesn't open anything in my browser. I opened the nexus webpage and click the vortex button and I can choose steamtinkerlaunch for the program it can automatically detect vortex and import it but I can open the browser from the vortex. Is this a known bug or did I miss something?

**Comment by sonic2kk** [comment]
This is just unreliable under Wine. #637 seemed to be resolved based on testing but I am not interested in spending more time on NXM link handling when manual workarounds exist (just manually putting links into the browser as you mentioned).

Closing as it's a very minor issue that probably results from a Wine compatibility issue.

Also, in future, please don't ignore the issue template. It exists for a reason.

**Comment by sonic2kk** [comment]
Actually if it's just the links to open the browser from Vortex I doubt this is a SteamTinkerLaunch issue to begin with and is almost certainly related to Wine.

**Comment by FahriBilici** [comment]
For login we can do manually but for downloading mods the problem starts. İ added a collection to vortex than for all of them it asked me to download mods from mods page and download button doesnt open browser as i told. İ didnt use vortex before but i guess it should download am i right?

**Comment by sonic2kk** [comment]
You can manually download and import mods to Vortex though, can't you? I don't use Vortex but that's my understanding from your description, that it's just automatic mod loading which doesn't work.

> doesnt open **browser** as i told

As in pressing a button *inside* Vortex doesn't open the browser, right? That sounds like a Wine bug, not a SteamTinkerLaunch issue.

If STL downloads Vortex and gets it to run, you're kind of on your own from there. I can't provide general support for using programs under Wine, and if it will load the mods but it just requires a bit more effort then I don't think it's a big issue at all.

**Comment by FahriBilici** [comment]
okay, last question when I write steamtinkerlaunch on konsole it says command not found. when installation asked me to add it as path parameter I accepted. is there another problem

**Comment by sonic2kk** [comment]
Not sure but you can run from the installation directory, the path stuff is intended for Linux Desktop, the primary platform as it sees the most testing.

**Comment by FahriBilici** [comment]
I just tried again and it throws error kioexec copying (Failed) Application closed unexpectedly and kioexec copying (Failed) to Home/.cache/kioexec/krunb/29792_0/sso . is this the problem you mentioned? When I opened my issue it just doesn't open and there was no error I clicked nothing except the bouncing the chrome icon next to my mouse for 3 seconds.

**Comment by sonic2kk** [comment]
That's not an error related to SteamTinkerLaunch, that's related to KDE. Definitely sounds like some kind of KDE/Wine error, nothing to do with SteamTinkerLaunch I'm afraid
