### ISSUE TITLE
Shader repo

### ISSUE THREAD

**Issue by Desertwolf89** [sonic2kk/steamtinkerlaunch#778]
Not sure if I'm doing something wrong. But when I click on the shader repo button. I only get the option for one repo which is astrayfx. So I need to manually add them or should they be preloaded?

**Comment by sonic2kk** [comment]
Only the `astrayfx` repo is available, [as noted on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Shader-Repositories#shader-repos):

> [repocustomlist.txt] currently only contains the AstrayFX repo by BlueSkyDefender, because pcgamingwiki doesn't link to the repo directly

Other shader repos can be added manually to `~/.config/steamtinkerlaunch/shaders/repocustomlist.txt` (path may be different if using Flatpak or if you specified a custom one in the config file). The path here is not totally clear (though it is mentioned in the STL config file) so I will update the wiki now to be more explicit.

Be sure to follow the guidance on the wiki page on the syntax of the custom shader file.

**Comment by zany130** [comment]
actually, it should automatically add these repos https://www.pcgamingwiki.com/wiki/ReShade#List_of_known_shader_repositories

steamtinkerlaunch *should* be downloading all those repo links into your steamtinkerlaunch shaders folder ( by default on non-flatpack it is `/home/USERNAME/config/steamtinkerlaunch/downloads/shaders/`) as `repolist.txt.`

then if you want to add any additional shader repos you would create `/home/USERNAME/.config/steamtinkerlaunch/downloads/shaders/repocustomlist.txt`

for example here is my files 

[repocustomlist.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/11184223/repocustomlist.txt)
[repolist.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/11184224/repolist.txt)


If this is not working for you please follow the issue template for a bug report and include logs.

it may be failing to get the repos from pcgamingwiki for some reason

**Comment by sonic2kk** [comment]
I had no idea about this, good catch @zany130 ! And exactly right then, we'll need some logs to follow-up here. Maybe some links have changed or perhaps there is/was a network issue (several users apparently have network issues downloading stuff with STL and other tools such as ProtonUp-Qt).

I just pressed the "Game Shaders" button on the Game Menu and it started downloading a bunch of shaders. My `repolist.txt` is very similar to the one provided, with only a handful less. It does take quite a long time it seems (it's been trying to download one called "MLUT" for several minutes now alone), but it seems like there is some issue.

Once downloaded this is what showed up for me in the Game Shaders list:

![image](https://user-images.githubusercontent.com/7917345/230744587-78089c39-3ae7-4b49-9622-d3e1a8e32ff0.png)

I don't use shaders so I cannot say for sure what is going wrong. I suspect it would be some kind of network issue though, if it could not get the shaders from the pcgamingwiki (maybe it was down, or is/was blocking connects). It would be interesting to see the logs.

**Comment by Desertwolf89** [comment]
I'll have to  get you the logs when I get home. But I did install it via protonqt. Would that more than likely be a possible issue?

**Comment by sonic2kk** [comment]
I don't think so, the shader repo should be in the same location. Installing via ProtonUp-Qt just puts the files in a different place than if you installed with your package manager, and Flatpak is only for use with Steam Flatpak.

I wrote the SteamTinkerLaunch install support for ProtonUp-Qt.

Also, be sure to **fill out the entire issue template, please do not just post logs!!** You would be better off either opening a new issue or leaving a comment/updating the OP issue with the issue template information. It is EXTREMELY irritating trying to get users to fill out the issue template and I am honestly tired of asking over and over again, so I am making it explicit that you MUST fill out the entire issue template. Also be sure to **upload the logs as a file to GitHub**, do **not** post a wall of text, or upload elsewhere.

**Comment by sonic2kk** [comment]
Just happened to browse r/linux_gaming and saw a user mention that they were also missing various shader repos. Not sure what's up there. Maybe PCGamingWiki is blocking the requests to download the repos, the same way GitHub occasionally blocks downloads of Yad?

The shader download stills works fine for me.

**Comment by Desertwolf89** [comment]
I apologize. I ended up getting frustrated and uninstalled it through protonqt and reinstalled it through the command lines and everything worked perfectly

**Comment by sonic2kk** [comment]
Not sure why ProtonUp-Qt didn't work, the paths should be set up the same. I would say it's probably more likely that there was some network issue initially that wasn't happening now.

Glad it's working for you now though, thanks for updating :-) I will close this now.

**Comment by SmurgBurglar** [comment]
I had the same issue, i installed though proton-qt and none of the shaders installed i think it might have something to do with not having internet access on first launch i had to do a clean install to fix it

**Comment by sonic2kk** [comment]
> i think it might have something to do with not having internet access on first launch i had to do a clean install to fix it

Yes, that might be it. You're expected to have Internet access when installing SteamTinkerLaunch.
