### ISSUE TITLE
"Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies"

### ISSUE THREAD

**Issue by ghost** [sonic2kk/steamtinkerlaunch#787]
When I attempt to launch HMM through STL, Konsole returns the following:

(1)(deck@steamdeck steamtinkerlaunch-12.12)$ ./steamtinkerlaunch hmm start
Invalid number of options.
Preparing to install SteamTinkerLaunch on Steam Deck
Invalid number of options.
Updating SteamTinkerLaunch to latest git

Dependency 'innoextract' already installed, nothing to do.
Dependency 'cabextract' already installed, nothing to do.
Dependency 'yad' already installed, nothing to do.
Invalid number of options.

Finished updating SteamTinkerLaunch ('v14.0.20230414-5')!
Invalid number of options.
Checking latest available HedgeModManager Release version
Latest available version is '7.9' - Checking to see if we are up-to-date
Latest HedgeModManager is already downloaded or was downloaded previously
HedgeModManager is up-to-date
Finished installing HedgeModManager
Adding HedgeModManager to application menu and setting up link handlers
Setting up installed HedgeModManager compatible games
Invalid number of options.
Finished configuring installed HedgeModManager games
Starting HedgeModManager
Invalid number of options.
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. File not found.
at HedgeModManager.HedgeApp.Main(String[] args)
(deck@steamdeck steamtinkerlaunch-12.12)$

Please help, I would like to play the speedy blue hedgehog game.

**Comment by sonic2kk** [comment]
Sorry, I'm not a Wine developer. I can't answer problems related to it not starting with Wine crashes. However it sounds like something is missing. You might want to try re-installing, but I can't really give help or advice. Try searching around to see what is missing with regards to this Wine error and what tinker steps are needed, but unfortunately I can't be the one to give support for Wine errors for any program. 

A quick ddg search suggests this is related to .NET not working correctly with this Wine version, but I have no idea as I am not a Wine developer.
