### ISSUE TITLE
yad settings fails to launch with yad>=7.0

### ISSUE THREAD

**Issue by Antiquete** [sonic2kk/steamtinkerlaunch#79]
This is an upstream [bug](https://github.com/v1cont/yad/issues/105) in yad

**Comment by frostworx** [comment]
I have yad-7.2-1 here and the settings work as expected

**Comment by frostworx** [comment]
I haven't seen your pull request before. It looks harmless so I see no reason to not merge it when it helps someone. Thank you! :)

**Comment by Antiquete** [comment]
Thanks! I think the segfaults might only be affecting present arch versions of yad. I am using  yad 7.2 (GTK+ 3.24.23) btw.

**Comment by frostworx** [comment]
But I'm on arch as well.

**Comment by Antiquete** [comment]
That's weird, then maybe it is the Desktop Environment. I am using KDE fwiw.

**Comment by frostworx** [comment]
Yeah, strange. I'm on xfce4 with
```
de_DE.UTF-8 UTF-8
en_US.UTF-8 UTF-8
```
locale.
