### ISSUE TITLE
Vortex not starting even with latest tkg release

### ISSUE THREAD

**Issue by Yasuhan** [sonic2kk/steamtinkerlaunch#799]
## System Information
- SteamTinkerLaunch version: 14.0
- Distribution:  Arch Linux
- Installation Method: AUR

## Issue Description

Basically no matter how I try it, Vortex just won't start. Doesn't matter if I launch it through the terminal or from the STL GUI. I'm using the latest version of TKG that Protonup-Qt offers, and made sure to set it in the global menu. This is also how I installed it to begin with. The game I'm testing with - Witcher 3 - shows up properly in the games list, too. Any help is appreciated, or if I can provide more info.

## Logs

Small part of the log with what's valid for this. For some reason it keeps waiting for a Window to appear that never does. 

```Fri May  5 07:02:21 PM CEST 2023 INFO - StatusWindow - for 'Vortex'
Fri May  5 07:02:21 PM CEST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Fri May  5 07:02:21 PM CEST 2023 INFO - prepareVortexGame - '"witcher3" (292030)' is already setup for 'Vortex' - remove from '/home/kfittkau/.config/steamtinkerlaunch/vortex/compatdata/seenvortexgames.txt' for retry
Fri May  5 07:02:21 PM CEST 2023 INFO - getRes - Detected screen resolution '1920x1200'
Fri May  5 07:02:21 PM CEST 2023 INFO - pollWinRes - Using GEOM '--geometry=1440x900+0+0' from '/home/kfittkau/.config/steamtinkerlaunch/guicfgs/1920x1200/292030/SteamTinkerLaunch-PrepareVortexGameStatus.conf'
Fri May  5 07:02:21 PM CEST 2023 INFO - StatusWindow - for 'Vortex'
Fri May  5 07:02:21 PM CEST 2023 INFO - updateWinRes - Starting resolution-poll for '/home/kfittkau/.config/steamtinkerlaunch/guicfgs/1920x1200/292030/SteamTinkerLaunch-PrepareVortexGameStatus.conf' with incoming '1440x900'
Fri May  5 07:02:21 PM CEST 2023 INFO - prepareAllInstalledVortexGames - Preparing all installed games supported by Vortex
Fri May  5 07:02:21 PM CEST 2023 INFO - setVortexVars - Using experimental-8.0-20230426 for vortex
Fri May  5 07:02:21 PM CEST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Fri May  5 07:02:21 PM CEST 2023 INFO - setVortexVars - Using experimental-8.0-20230426 for vortex
Fri May  5 07:02:21 PM CEST 2023 INFO - gVSIDs - Searching for SteamIDs in '/home/kfittkau/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/resources/app.asar.unpacked/bundledPlugins'
Fri May  5 07:02:21 PM CEST 2023 INFO - prepareVortexGame - '"witcher3" (292030)' is already setup for 'Vortex' - remove from '/home/kfittkau/.config/steamtinkerlaunch/vortex/compatdata/seenvortexgames.txt' for retry
Fri May  5 07:02:21 PM CEST 2023 INFO - prepareAllInstalledVortexGames - Applying Vortex settings for all games via autogenerated cmd '/dev/shm/steamtinkerlaunch/vortset.cmd'
Fri May  5 07:02:22 PM CEST 2023 SKIP - updateWinRes - Timeout waiting for Window 'SteamTinkerLaunch-VortexOptions'
Fri May  5 07:02:22 PM CEST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Fri May  5 07:02:22 PM CEST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Fri May  5 07:02:23 PM CEST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Fri May  5 07:02:23 PM CEST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Fri May  5 07:02:24 PM CEST 2023 INFO - prepareAllInstalledVortexGames - Symlinks, registry entries and vortex settings for all found supported games should be ready at this point for Vortex
Fri May  5 07:02:24 PM CEST 2023 INFO - startVortex - Starting Vortex without options
Fri May  5 07:02:24 PM CEST 2023 SKIP - updateWinRes - Timeout waiting for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Fri May  5 07:02:24 PM CEST 2023 SKIP - updateWinRes - Timeout waiting for Window 'SteamTinkerLaunch-PrepareVortexGameStatus'
Fri May  5 07:02:26 PM CEST 2023 INFO - startVortex - Vortex exited - starting game now```

**Comment by sonic2kk** [comment]
Are you sure you're using the latest version of Proton-tkg based on Wine Master from ProtonUp-Qt and not the regular Proton-tkg? The wiki specifically notes that it has to be a build of Proton based on Wine 8.4 or higher (Tkg is probably based on Wine-staging 8.7 by now).

<removed as ProtonUp-Qt does not offer the latest Wine-tkg build, as made obvious by the fact that it does not reference Wine 8.4+>

I can't see the Proton version from the log you provided.

**Comment by sonic2kk** [comment]
Hmm actually it seems like ProtonUp-Qt may not offer the latest Wine master, maybe something changed here as it used to offer newer versions (I installed a build of 8.6 from it about a week ago).

Try installing the build of Proton-tkg based on Wine Master manually. Remember that you should verify that the Proton version you're using is using an up-to-date Wine binary as well.

**Comment by Yasuhan** [comment]
I'm pretty sure it's a correct version, unless I'm missing something here? 

![image](https://user-images.githubusercontent.com/30007466/236562293-9c6dd79c-7673-4842-80cf-455a76e4f475.png)

**Comment by sonic2kk** [comment]
That looks like it might be based on Proton Experimental instead of Wine master. I'm downloading a build manually to confirm. Though it says 8.7, maybe it doesn't have the relevant Wine component, or maybe 8.7 is unfortunately incompatible.

The Wine master CI has been failing for a while it looks like, but the builds on Wine Master are named differently to what you have shown. Here is the build I'm using to run Vortex (the latest passing CI for Wine master builds): https://github.com/Frogging-Family/wine-tkg-git/actions/runs/4737124542

The version you're using is Proton_tkg_experimental, likely based on Valve's Wine Bleeding Edge, whereas the Wine master builds are named like `proton_tkg_8.6.1.r3.g4eb322dc`.

I also just checked and the wiki does link to the Wine Master workflow.

**Comment by Yasuhan** [comment]
Okay, downloading that seems to have fixed it and Vortex is launching now. Didn't expect the other build to be so different, as it also had 8.7.

**Comment by sonic2kk** [comment]
Vortex actually updated when I restarted it to 1.8.1 Beta and it still works when using the CI I linked:

![image](https://user-images.githubusercontent.com/7917345/236564122-76a60d57-2dd0-4be7-ba5d-3c40beb3a002.png)

That build is based on Wine 8.6, but there doesn't appear to be a passing build on the CI for any newer Wine version. It may still be possible to build a version based on Wine 8.7 locally but I haven't tried (I'm also unsure of how to build based on Wine Master locally). If Valve's Proton Bleeding Edge is using Wine 8.7 and does include the relevant `DiscardVirtualMemory`, it is possible that Wine 8.7 is incompatible with Vortex.

STL isn't really responsible for fixing or debugging Wine breakages but I'm glad it's working :-) Will close this now.

**Comment by sonic2kk** [comment]
Turns out the issue with "Proton-tkg (Wine Master)" not listing the proper CI builds was a bug in ProtonUp-Qt as a result of more than 30 recent build failures for this Proton-tkg CI. I got a PR up to fix it on the ProtonUp-Qt side, so once it's merge and the builds of Proton-tkg (Wine Master) start passing again, they will probably be based on Wine 8.7 or higher and I will be able to test if Vortex is indeed incompatible with Wine 8.7 or if it's just Valve's Wine.

**Comment by sonic2kk** [comment]
Heads up: GE-Proton8-2 should also work now.
