### ISSUE TITLE
Suggestion: Make yad settings window scale dynamically

### ISSUE THREAD

**Issue by Antiquete** [sonic2kk/steamtinkerlaunch#81]
### Problem
Right now the size of yad settings window is static. It is either fetched from global.conf or if settings are missing there then directly from stl script. This causes issues for people with different resolutions #73 

### Solution
Make STLSETWIDTH and STLSETHEIGHT scale dynamically based on a percentage of user's resolution. This will make ui scale consistently across resolutions.

### How to implement this?
I am thinking of using xrandr in some form to fetch resolution and then simply setting height and width based on that. Xrandr is preferred since that generally comes preinstalled with most linux distros, however, any other alternative is also good enough.

**Comment by Antiquete** [comment]
Just now noticed that xrandr also comes in as a dependency for steam itself, so it can be used without adding any extra dependency on stl's side.

**Comment by Antiquete** [comment]
I will branch this and see if I can get this to work on my end.

**Comment by frostworx** [comment]
This looks like a very nice idea and implementation. Thanks for the contribution!
