### ISSUE TITLE
Infinite loop when trying to find proton simmilar version

### ISSUE THREAD

**Issue by Dandraghas** [sonic2kk/steamtinkerlaunch#817]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Fedora 38
- Installation Method: Installed from source

## Issue Description

when proton version is not found steamtinkerlaunch tries to search for simmilar version but it's doing nothing and goes into infinite loop

also i get notification spam:
![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/91272905/5876efe0-7c2f-4921-a862-30cd12c7235b)

## Logs
https://gist.github.com/Dandraghas/c68326f7caabca0eee4194003a87d82a

**Comment by sonic2kk** [comment]
I guess there is no similar version for STL to find. You should be able to change the Proton version to an installed version. If it can't find one still and you know there is one, remove `/dev/shm/steamtinkerlaunch`.

Don't have any issues on-hand but similar issues have been reported sporadically for a couple of years at least. I fixed the cases which affected me with Proton Experimental version increments, but for vanilla Proton STL could always find a similar version. It was able to bump from 8.0-2c to 8.0-2d recently for example, so maybe if there is absolutely no fallback STL needs a better way to catch it (e.g. just crash).

**Comment by sonic2kk** [comment]
I'm having some difficulty re-creating the problem, so for now trying to select a Proton version which does exist may be the best resolution. After that the problem should go away. Please re-test when you have a chance.

If you think your selected Proton version should exist but does not, you can do one of two things:
- Check `/dev/shm/steamtinkerlaunch`, and open the `ProtonCSV.txt` file. From here, you can inspect the path of the Proton versions STL can see (these are formatted as `proton_name;/path/to/proton`). If the path to your Proton version looks incorrect, you can try to manually amend it here.
- Remove the Proton version from this file, and manually add the Proton version with `steamtinkerlaunch acp /path/to/proton/folder`.

In some cases, invalid Proton versions are fixed after removing `/dev/shm/steamtinkerlaunch` (afaik `/dev/shm` is generally cleared after a reboot as well). As mentioned in the first reply, this may solve the issue as well.

**Comment by sonic2kk** [comment]
Did any of the above solutions work for you?

**Comment by sonic2kk** [comment]
Closing due to lack of response. Happy tinkering!
