### ISSUE TITLE
STL does not respect notification settings

### ISSUE THREAD

**Issue by Amzd** [sonic2kk/steamtinkerlaunch#818]
## System Information
- SteamTinkerLaunch version:  v12.12 
- Distribution: Nobara 37
- Installation Method: `sudo dnf install steamtinkerlaunch`

## Issue Description

In gnome settings you can disable notifications per app (see attached screenshot), which I assumed STL would respect. I have found that I can disable the notifications through global settings (https://github.com/sonic2kk/steamtinkerlaunch/wiki/Notifier) but maybe it would be nice if STL respected the gnome settings instead of users having to search the wiki for this.

![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/17001151/1abe9139-8d3c-4486-9998-3a211cabef11)

**Comment by sonic2kk** [comment]
This is likely a problem with the notifier program that STL uses. You can check what command it is using, usually it is `notify-send`, but may be configured differently if this is unavailable, and likewise the user can choose a different one.

With notifications disabled on GNOME you can try using the given command that STL uses to manually invoke a notification from your terminal, i.e. `notify-send test`.

STL is not doing anything to ignore notifications on the code side, it just calls the given notifier which is almost always `notify-send`. This may be either an upstream issue, or maybe STL has to configure something to tell notify-send to respect the GNOME setting.

On KDE, notify-send notifications are correctly suppressed by the system in Do Not Disturb.

**Comment by sonic2kk** [comment]
Looking at the screenshot again, it looks like this may be for Desktop Menu entries and not running processes. If GNOME tries to set this based on XDG entries then it is expected that this won't work.

This is nothing from what I can see that SteamTinkerLaunch can/should fix, rather it seems however GNOME implements this does not actually support disabling notifications from scripts.

SteamTinkerLaunch is not really an "application" but rather a script. If GNOME does not offer a way to mute notifications from specific scripts, SteamTinkerLaunch can't do anything. All SteamTinkerLaunch does is call the notifier specified in the config files (configurable from the Global Menu) and it's up to the Desktop Environment to do the rest.

Closing as this is not a SteamTinkerLaunch issue.

P.S. if GNOME tries to manage this by child processes or something, turning off notifications for Steam may also work, but no guarantees.

**Comment by sonic2kk** [comment]
Oh, I should also note one more thing that I forgot to reply to:

> [...] instead of users having to search the wiki for this

It is expected that users will read the wiki. SteamTinkerLaunch is for technical users.

**Comment by Amzd** [comment]
Thanks for info :+1:
