### ISSUE TITLE
Skyrim: voices and music don't work in game mode

### ISSUE THREAD

**Issue by Sbuitenkamp** [sonic2kk/steamtinkerlaunch#819]
So when I run skyrim special edition through Mod Organiser 2 game mode (from the separate GUI pop up after the main menu one) I will have no music at the menu screen and no voices for characters. But if I run it through MO2 from the main menu it will have voices and music just fine, but since it's not in game mode it will run at a whole 4 frames per second.

**Comment by sonic2kk** [comment]
Sounds like some Proton/mod issue, not a SteamTinkerLaunch issue. I would recommend checking the Proton versions or looking for general guidance when using mods on Linux. Sorry but issues with mods/modding games aren't related to SteamTinkerLaunch provided the mod tool itself runs.

I recall a long time ago that Skyrim SE needed a bunch of workarounds to get audio to work. Try playing without mods, then with mods, play around with Proton versions, etc. But mod support is not related to SteamTinkerLaunch.

Remember that in Game Mode and Standalone Mode, Skyrim will run in different prefixes with different Proton versions. in Game Mode, MO2 and the game run in the Skyrim game prefix. In Standalone Mode, it runs in the MO2 prefix at `~/.config/steamtinkerlaunch/mo2/compatdata/pfx`. The Proton versions are different too, Game Mode uses the game's Proton version, and Standalone Mode uses the MO2 Proton version.

Depending on what version of STL you're using, MO2 may be using the Steam Linux Runtime in Game Mode but not in Standalone Mode. This can be toggled for Game Mode in the Game Menu. However probably the most likely situation is that this is some form of mod/game issue. You'll have to tinker around and find out what's wrong. I used MO2 to mod Skyrim SE a long time ago and it worked perfectly fine. I have also recently used it to mod New Vegas and Oblivion and it works fine as well.
