### ISSUE TITLE
Optionally save resolution of all Windows sizes individually on change

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#83]
An option to automatically save the Settings resolution on exit would be nice.
This maybe also could obsolete the width/height menu entries completely.

**Comment by frostworx** [comment]
Haven't looked too close at it yet, but depending on an external windowtool to get its own "yad resolution" would be pretty ugly, especially as it would have to loop in the background while the settings menu is open.

**Comment by frostworx** [comment]
I have an unpolished working background loop working. Will probably check tomorrow if I'll add it.

**Comment by Antiquete** [comment]
> An option to automatically save the Settings resolution on exit would be nice.
> This maybe also could obsolete the width/height menu entries completely.

That seems to be a great idea! Width and height entries have mostly become redundant after implementing dynamic scaling.

> I have an unpolished working background loop working. Will probably check tomorrow if I'll add it.

Superb! This hopefully will take care of resolution issues completely.

**Comment by frostworx** [comment]
Changed the title to reflect the new goal better:
Every gui element will have its own size settings which will be saved automatically when changed when function is enabled.
Window sizes will be stored into an extra "gui.conf" which won't show up in the Settings Menu to keep things clean.

Thanks again for the feedback @Antiquete! Very appreciated!

**Comment by frostworx** [comment]
Took me a while to find the reason for broken game/ default template breakage.
It was this change https://github.com/frostworx/steamtinkerlaunch/commit/9c9d785b1e12c9d651745898c7d8d3368aa53649#diff-7646b54bb4e9ecea20a0ca57e3b2f794R900 of your pull request https://github.com/frostworx/steamtinkerlaunch/pull/80
@Antiquete which I haven't even seen. No big deal, I'm glad I found it, but wanted to let you know.

**Comment by frostworx** [comment]
implemented in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.0.5

**Comment by yochananmarqos** [comment]
With 2.0.5, I receive this error running `stl settings`:

```
/usr/sbin/stl: line 184: 1920
1920: syntax error in expression (error token is "1920")
```

**Comment by frostworx** [comment]
Just added xorg-x11 as optional dependency in AUR, I guess this caused your error.
Now either I'll make it a hard dependency or harcode some defaults if xrandr is not installed.

**Comment by yochananmarqos** [comment]
`xrandr` is not a valid package name, it's `xorg-xrandr`. I already have that installed.

**Comment by yochananmarqos** [comment]
What logs would you like?

**Comment by frostworx** [comment]
`~/.config/stl/logs/stl.log`
is the relevant one in this case.
Please try with current master, as I've added some more log output

**Comment by yochananmarqos** [comment]
It's fixed with the latest [commit](https://github.com/frostworx/steamtinkerlaunch/commit/e564f44cf280046746d0b0436dfbd6474f2757e5).

```
Mon Sep 28 01:05:19 PM MDT 2020 INFO - calculateDefaultResolutions - 'xrandr' found screenresolution '1920x1080
1920x1080'
Mon Sep 28 01:05:19 PM MDT 2020 WARN - calculateDefaultResolutions - '1920x1080
1920x1080' is invalid - calculating with fallback screenresolution for default values
Mon Sep 28 01:05:19 PM MDT 2020 WARN - useFallBackResolution - calculating with fallback screenresolution '1920x1080' for default values
Mon Sep 28 01:05:19 PM MDT 2020 INFO - prepareGUI - using 'yad' for the GUI
Mon Sep 28 01:05:19 PM MDT 2020 INFO - openSettings - opening Settings
```

**Comment by frostworx** [comment]
nice, thx. that helps to fix the core problem.

**Comment by yochananmarqos** [comment]
I just noticed another log file appeared alongside `stl.log` called `31337.log`:

```
Mon Sep 28 01:05:19 PM MDT 2020 INFO - openSettings - getting current Settings resolution
Mon Sep 28 01:05:19 PM MDT 2020 SKIP - updateWinRes - SAVESETSIZE is enabled, but 'xwininfo' was not found which is required for this function
Mon Sep 28 01:07:42 PM MDT 2020 INFO - openSettings - exiting GUI
Mon Sep 28 01:07:42 PM MDT 2020 INFO - openSettings - cleaning YadFiles
Mon Sep 28 01:07:42 PM MDT 2020 INFO - openSettings - cleaned YadFiles
```

I don't have `xorg-xwininfo` installed, perhaps mention that's also required for the settings window in the README and optdepends() description.

**Comment by frostworx** [comment]
I removed "uniq" from @Antiquete pull-request, when migrating the function.
Would you please check if
_xrandr --current | grep "\*" | uniq | awk '{print $1}'_
gives a valid out?

**Comment by frostworx** [comment]
good find @ xorg-xwininfo! *adding*

**Comment by yochananmarqos** [comment]
> Would you please check if
> `xrandr --current | grep "*" | uniq | awk '{print $1}'`
> gives a valid out?

Yes, it appears so:
```
1920x1080
1920x1080
```

**Comment by frostworx** [comment]
So
`xrandr --current | grep "*" | awk '{print $1}' | uniq`
should work, right?

edit: assuming this is a dual head setup.
This would only work if both screen have the same resolution.
Is it save to assume that the first of both screens usually is the gameing monitor? then I'd simply add  head -n1

**Comment by frostworx** [comment]
tested it on a dualhead systgem with different resolutions and will use
`xrandr --current | grep "*" | awk '{print $1}' | sort -gur | head -n1`
which defaults to the biggest resolution available.

**Comment by yochananmarqos** [comment]
> So
> `xrandr --current | grep "*" | awk '{print $1}' | uniq`
> should work, right?

Yep.
```
1920x1080
```

> assuming this is a dual head setup

Yep.

**Comment by frostworx** [comment]
Yep. I just leave
` xrandr --current | grep "*" | awk '{print $1}' | sort -gur | head -n1`
It is good enough for me.

**Comment by Antiquete** [comment]
> Took me a while to find the reason for broken game/ default template breakage.
> It was this change [9c9d785#diff-7646b54bb4e9ecea20a0ca57e3b2f794R900](https://github.com/frostworx/steamtinkerlaunch/commit/9c9d785b1e12c9d651745898c7d8d3368aa53649#diff-7646b54bb4e9ecea20a0ca57e3b2f794R900) of your pull request #80
> @Antiquete which I haven't even seen. No big deal, I'm glad I found it, but wanted to let you know.

Thanks for checking that out, might have been stray code that I forgot while testing on my end. It wasn't supposed to be part of that commit.

> Yep. I just leave
> ` xrandr --current | grep "*" | awk '{print $1}' | sort -gur | head -n1`
> It is good enough for me.

This works on my end too. Also thanks for the latest update, gui seems to be scaling much better right now from the get go.

**Comment by frostworx** [comment]
ty :)
