### ISSUE TITLE
SKSE Wont load from MO2

### ISSUE THREAD

**Issue by Parilia** [sonic2kk/steamtinkerlaunch#836]
## System Information
- SteamTinkerLaunch version: v12.12 
- Distribution: Nobara
- Installation Method: protonUpQT

## Issue Description
when trying to launch SKSE from within MO2 (I am fairly sure that's how you are supposed to launch it when modding through MO2) It says it relays on steam and that I must log into steam, I am ofc logged in and telling it to either log in or to ignore I get this error:
REL/Relocation.h(567) failed to open file 

## Logs
Tue 13 Jun 17:55:45 BST 2023 INFO - setflatpak - started SteamTinkerLaunch from /home/parilia/stl/prefix/steamtinkerlaunch
Tue 13 Jun 17:55:45 BST 2023 INFO - initAID - Set AID from STEAM_COMPAT_APP_ID to '489830'
Tue 13 Jun 17:55:45 BST 2023 INFO - initAID - Set OSCDP to STEAM_COMPAT_DATA_PATH '/mnt/Data/SteamLibrary/steamapps/compatdata/489830'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Language from command line is 'english'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/parilia/stl/prefix/lang'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Found user-installed /home/parilia/.config/steamtinkerlaunch/lang/english.txt, attempting to update it
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Found lang file to replace the existing user-installed file with under '/home/parilia/stl/prefix/lang/english.txt'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Loading found user-installed /home/parilia/.config/steamtinkerlaunch/lang/english.txt
Tue 13 Jun 17:55:45 BST 2023 WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
Tue 13 Jun 17:55:45 BST 2023 INFO - updateEditor - No valid editor found - will fall back to 'xdg-open'.
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLanguage - Loading STLLANG from '/home/parilia/.config/steamtinkerlaunch/global.conf'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLanguage - STLLANG from '/home/parilia/.config/steamtinkerlaunch/global.conf' is 'englishUK'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLanguage - Now load the language file 'englishUK'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Language from command line is 'englishUK'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/parilia/stl/prefix/lang'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Command line language 'englishUK' is no file - trying to find its absolute path
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Found user-installed /home/parilia/.config/steamtinkerlaunch/lang/englishUK.txt, attempting to update it
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Found lang file to replace the existing user-installed file with under '/home/parilia/stl/prefix/lang/englishUK.txt'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Loading found user-installed /home/parilia/.config/steamtinkerlaunch/lang/englishUK.txt
Tue 13 Jun 17:55:45 BST 2023 INFO - updateConfigEntry - Option 'STLLANG' is updated with the new value 'englishUK' in config 'global.conf'
Tue 13 Jun 17:55:45 BST 2023 INFO - setLocalInstall - Looks like we have a non-root local install here - Updating paths...
Tue 13 Jun 17:55:45 BST 2023 INFO - updateConfigEntry - Option 'GLOBALCOLLECTIONDIR' is updated with the new value '/home/parilia/stl/prefix/collections' in config 'global.conf'
Tue 13 Jun 17:55:45 BST 2023 INFO - getCurrentCommandline - No Proton in command line arguments 'mo2 start'
Tue 13 Jun 17:55:45 BST 2023 INFO - saveOrgVars - Storing some original variables to restore them later
Tue 13 Jun 17:55:45 BST 2023 INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
Tue 13 Jun 17:55:45 BST 2023 INFO - emptyVars - Set $PATH to '/home/parilia/.local/bin:/home/parilia/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/parilia/.dotnet/tools:/var/lib/snapd/snap/bin::'
Tue 13 Jun 17:55:45 BST 2023 START - ######### Initializing Game Launch 489830 using SteamTinkerLaunch v12.12 #########
Tue 13 Jun 17:55:45 BST 2023 INFO - main - Starting with a clean log
Tue 13 Jun 17:55:45 BST 2023 INFO - main - Start creating default configs
Tue 13 Jun 17:55:45 BST 2023 INFO - createDefaultCfgs - START
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Language from command line is 'english'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/parilia/stl/prefix/lang'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Found user-installed /home/parilia/.config/steamtinkerlaunch/lang/english.txt, attempting to update it
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Found lang file to replace the existing user-installed file with under '/home/parilia/stl/prefix/lang/english.txt'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Loading found user-installed /home/parilia/.config/steamtinkerlaunch/lang/english.txt
Tue 13 Jun 17:55:45 BST 2023 WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
Tue 13 Jun 17:55:45 BST 2023 INFO - updateEditor - No valid editor found - will fall back to 'xdg-open'.
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLanguage - Loading STLLANG from '/home/parilia/.config/steamtinkerlaunch/global.conf'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLanguage - STLLANG from '/home/parilia/.config/steamtinkerlaunch/global.conf' is 'englishUK'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLanguage - Now load the language file 'englishUK'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Language from command line is 'englishUK'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/parilia/stl/prefix/lang'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Command line language 'englishUK' is no file - trying to find its absolute path
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Found user-installed /home/parilia/.config/steamtinkerlaunch/lang/englishUK.txt, attempting to update it
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Found lang file to replace the existing user-installed file with under '/home/parilia/stl/prefix/lang/englishUK.txt'
Tue 13 Jun 17:55:45 BST 2023 INFO - loadLangFile - Loading found user-installed /home/parilia/.config/steamtinkerlaunch/lang/englishUK.txt
Tue 13 Jun 17:55:45 BST 2023 INFO - updateConfigEntry - Option 'STLLANG' is updated with the new value 'englishUK' in config 'global.conf'
Tue 13 Jun 17:55:45 BST 2023 INFO - createDefaultCfgs - setSteamPaths:
Tue 13 Jun 17:55:45 BST 2023 INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
Tue 13 Jun 17:55:45 BST 2023 WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
Tue 13 Jun 17:55:45 BST 2023 INFO - updateEditor - No valid editor found - will fall back to 'xdg-open'.
Tue 13 Jun 17:55:45 BST 2023 INFO - getGameOS - Starting game OS detection
Tue 13 Jun 17:55:45 BST 2023 WARN - getGameOS - Could not extract the full game binary path from the incoming game launch command, so assuming this is a Windows game!
Tue 13 Jun 17:55:45 BST 2023 INFO - setWin - '' determined to be a Windows Game
Tue 13 Jun 17:55:45 BST 2023 INFO - createDefaultCfgs - createProtonList:
Tue 13 Jun 17:55:45 BST 2023 INFO - createDefaultCfgs - createProtonList end
Tue 13 Jun 17:55:45 BST 2023 INFO - listAllSettingsEntries - '/dev/shm/steamtinkerlaunch/setentries.txt' already exists - nothing to do
Tue 13 Jun 17:55:46 BST 2023 INFO - createDefaultCfgs - STOP
Tue 13 Jun 17:55:46 BST 2023 SKIP - listSteamLibraries - not recreating already available '/dev/shm/steamtinkerlaunch/SteamLibraries.txt'
Tue 13 Jun 17:55:46 BST 2023 WARN - setSteamLibraryPaths - Library folder '/mnt/46eda0ad-30b3-4b6a-ad75-4097cd6f1f5e/SteamLibrary/steamapps' does not seem to be a valid directory, even though this comes from Steam itself - Ignoring, but please report if this is invalid or causes issues
Tue 13 Jun 17:55:46 BST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_LIBRARY_PATHS set to '/mnt/Data/SteamLibrary/steamapps:/home/parilia/.local/share/Steam/steamapps'
Tue 13 Jun 17:55:46 BST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_MOUNTS set to '/home/parilia/.local/share/Steam/steamapps/common/Steamworks Shared:/home/parilia/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier:/mnt/Data/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper'
Tue 13 Jun 17:55:46 BST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_TOOL_PATHS set to '/home/parilia/.local/share/Steam/steamapps/common/Steamworks Shared:/home/parilia/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier:/mnt/Data/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper'
Tue 13 Jun 17:55:46 BST 2023 INFO - main - Checking internal dependencies:
Tue 13 Jun 17:55:46 BST 2023 INFO - checkIntDeps - Result of version check for yad binary '/usr/bin/yad' is '9.3'
Tue 13 Jun 17:55:46 BST 2023 INFO - main - Initializing first Proton:
Tue 13 Jun 17:55:46 BST 2023 INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/steamtinkerlaunch/ProtonCSV.txt' which was created during a previous run
Tue 13 Jun 17:55:46 BST 2023 INFO - initFirstProton - Initializing Proton
Tue 13 Jun 17:55:46 BST 2023 INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/parilia/.config/steamtinkerlaunch/default_template.conf' is 'GE-Proton8-3'
Tue 13 Jun 17:55:46 BST 2023 INFO - main - Initializing default window resolution
Tue 13 Jun 17:55:46 BST 2023 INFO - setInitWinXY - Using '1440x810' from config '/dev/shm/steamtinkerlaunch/defres.txt'
Tue 13 Jun 17:55:46 BST 2023 INFO - main - Welcome to SteamTinkerLaunch
Tue 13 Jun 17:55:46 BST 2023 INFO - removeEmptyFiles - Removing empty files from '/home/parilia/.config/steamtinkerlaunch/games/appinfo'
Tue 13 Jun 17:55:46 BST 2023 INFO - removeEmptyFiles - Removing empty files from '/home/parilia/.config/steamtinkerlaunch/games/header'
Tue 13 Jun 17:55:46 BST 2023 INFO - main - Checking command line: incoming arguments 'mo2 start'
Tue 13 Jun 17:55:46 BST 2023 INFO - setMO2Vars - Found the variable for the game wineprefix '/mnt/Data/SteamLibrary/steamapps/compatdata/489830/pfx', so using a portable instance of 'mo2'
Tue 13 Jun 17:55:46 BST 2023 INFO - setMO2Vars - The mo2 helper-file is set to '/home/parilia/stl/prefix/misc/mo2games.txt'
Tue 13 Jun 17:55:46 BST 2023 INFO - setMO2Vars - Preparing Proton variables for a portable mo2 instance
Tue 13 Jun 17:55:46 BST 2023 INFO - setMO2Vars - Using proton version 'proton-8.0-2d', which is currently configured for the game none
Tue 13 Jun 17:55:46 BST 2023 INFO - setMO2Vars - Using proton-8.0-2d for ModOrganizer
Tue 13 Jun 17:55:46 BST 2023 INFO - setModWine - DNPROTON is '/home/parilia/.local/share/Steam/steamapps/common/Proton 8.0/proton'
Tue 13 Jun 17:55:46 BST 2023 INFO - setModWine - DNPROTON is a file -- it is '/home/parilia/.local/share/Steam/steamapps/common/Proton 8.0/proton'
Tue 13 Jun 17:55:46 BST 2023 SKIP - prepareMO2 - portable instance running - nothing to prepare
Tue 13 Jun 17:55:46 BST 2023 INFO - prepareMO2 - No ModOrganizer instance provided
Tue 13 Jun 17:55:46 BST 2023 INFO - setMO2Vars - The 'mo2' instance was already set to 'portable' during this run
Tue 13 Jun 17:55:46 BST 2023 INFO - setMO2Vars - The mo2 helper-file is set to '/home/parilia/stl/prefix/misc/mo2games.txt'
Tue 13 Jun 17:55:46 BST 2023 INFO - setMO2DLMime - Desktopfile '/home/parilia/.local/share/applications/ModOrganizer-steamtinkerlaunch-dl.desktop' looks to be up2date
Tue 13 Jun 17:55:46 BST 2023 INFO - startMO2 - Starting '/mnt/Data/SteamLibrary/steamapps/compatdata/489830/pfx/drive_c/Modding/MO2/ModOrganizer.exe'
Tue 13 Jun 17:55:46 BST 2023 INFO - startMO2 - WINEDEBUG="-all" WINEPREFIX="/mnt/Data/SteamLibrary/steamapps/compatdata/489830/pfx" "/home/parilia/.local/share/Steam/steamapps/common/Proton 8.0/dist/bin/wine" "/mnt/Data/SteamLibrary/steamapps/compatdata/489830/pfx/drive_c/Modding/MO2/ModOrganizer.exe"
Tue 13 Jun 17:56:11 BST 2023 INFO - MainMenu - Clicked '0' - 'EXIT'
Tue 13 Jun 17:56:11 BST 2023 INFO - MainMenu - exiting 'Settings Menu' and opening 'Exit'
Tue 13 Jun 17:56:11 BST 2023 INFO - closeSTL - closing STL
Tue 13 Jun 17:56:11 BST 2023 INFO - updateConfigEntry - Emptying 'CUSTOMCMD' for '/home/parilia/.config/steamtinkerlaunch/default_template.conf'
Tue 13 Jun 17:56:11 BST 2023 INFO - closeSTL - Creating '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
Tue 13 Jun 17:56:11 BST 2023 INFO - checkPlayTime - The game was not even started
Tue 13 Jun 17:56:11 BST 2023 INFO - closeSTL - Game 'The Elder Scrolls V: Skyrim Special Edition (489830)' exited - cleaning up custom processes if necessary
Tue 13 Jun 17:56:11 BST 2023 INFO - closeTrayIcon - Closing TrayIcon '128610'
Tue 13 Jun 17:56:11 BST 2023 INFO - updateWinRes - The Window 'SteamTinkerLaunch-MainMenu' was closed - the resolution didn't change - nothing to do
Tue 13 Jun 17:56:12 BST 2023 INFO - closeSTL - Removing '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
Tue 13 Jun 17:56:12 BST 2023 STOP - ######### closeSTL SteamTinkerLaunch v12.12 #########
Tue 13 Jun 17:56:12 BST 2023 INFO - writeLastRun - Recreating /home/parilia/.config/steamtinkerlaunch/logs/steamtinkerlaunch/lastrun.txt
Tue 13 Jun 17:56:12 BST 2023 INFO - storeMetaData - Saving metadata for game 'Skyrim Special Edition (489830)'
Tue 13 Jun 17:56:12 BST 2023 INFO - getArch - Architecture for '/mnt/Data/SteamLibrary/steamapps/common/Skyrim Special Edition/SkyrimSELauncher.exe' is 64bit
Tue 13 Jun 17:56:12 BST 2023 INFO - storeMetaData - Symlink '/home/parilia/.config/steamtinkerlaunch/meta/eval/title/evaluatorscript_Skyrim Special Edition.vdf' already exists

**Comment by sonic2kk** [comment]
Are you trying to launch Skyrim by using MO2 in Standalone Mode instead of Game Mode? The error you're describing usually happens if you're using MO2 either via `steamtinkerlaunch mo2 start` or from the Main Menu. From looking at the logs it's hard to tell because it wasn't attached as a file and is a bit harder to read.

If the issue persists, try disabling the Steam Linux Runtime, though New Vegas and Oblivion work fine for me. It has been a long time since I modded SkyrimSE, but from what I recall I didn't have to launch SKSE as a separate executable. I don't really remember very clearly though, I just remembered it being like New Vegas where NVSE is installed as a mod.

However regardless, issues with modding games are not SteamTinkerLaunch issues. If MO2 loads it's up to users to figure out the rest. I'll leave this open to see if the issue can be resolved and potentially documented on the wiki, but this isn't a SteamTinkerLaunch bug.

**Comment by sonic2kk** [comment]
After a find in page (should've did that first, my bad) it does indeed look like you're using `steamtinkerlaunch MO2 start` or the Main Menu button (which runs this command internally).

I'm not at home at the moment so I'm writing this on my phone. If the issue persists or I made a mistake I'll look more in-depth in a little bit. I believe the differences between Standalone Mode and Game Mode are noted on the ModOrganizer 2 wiki page.

**Comment by Parilia** [comment]
Can confirm i was using standalone but after more reading I managed to get Game mode working however the issue still persists in game mode. 
It no longer asks about steam but i do get the same error 
![Screenshot_20230613_194938](https://github.com/sonic2kk/steamtinkerlaunch/assets/22579268/9fbee096-f767-4c57-a183-b33bb68621ab)

**Comment by sonic2kk** [comment]
This is probably some kind of issue with SKSE/a mod you are using and not STL. Have you confirmed that all of your mods are compatible? A quick search for error indicates that it comes from mods being incompatible or old mod files lingering around. For Skyrim specifically, it seems some mods may require Anniversary Edition, or special versions to work with/without AE. See here: https://www.reddit.com/r/SkyrimHelp/comments/rllb1f/enginefixesdll_relrelocationh567_failed_to_open/

I bring this up because it looks like you have several mods. It might be worth trying just SKSE on its own. At present it can be difficult to find information, as a lot of mod support is on Reddit and many subreddits are private at the moment.

However this is delving a little bit into mod support territory, so I think I will close this issue. I cannot really give much support in the way of modding. Good luck!

**Comment by Parilia** [comment]
Okay well thank you for the support you did give =D

**Comment by sonic2kk** [comment]
Just noticed one mod in particular: You're using SSE Fixes and the mod title indicates that it is only for Skyrim 1.5.39-1.5.97. The latest version of Skyrim I believe is 1.6.X is the latest version (I am not sure how versioning works with/without the AE DLC). Please make sure this is compatible with your game version. That mod seems to offer a release for 1.6.629 and above (at writing, Steam News says the latest Skyrim SE version is AE 1.6.640).

From searching for the error mentioned I did see some users mentioning that this has been a painpoint and a potential cause of this error.

**Comment by Parilia** [comment]
yea I saw it too and kicked myself, its now running and i am so relieved. Thank you again  =D

**Comment by sonic2kk** [comment]
Very glad it's all working for you, happy gaming! :-)
