### ISSUE TITLE
No new release since issue #779 was fixed. (Vortex Special Characters)

### ISSUE THREAD

**Issue by rowanthemodder** [sonic2kk/steamtinkerlaunch#839]
## System Information
- SteamTinkerLaunch Version: 12.12
- Distribution: Nobara Linux 37
- Installation Method: Protonup-QT / Built from source (commit 2a4db27)
## Issue Description
As of opening this issue there hasn't been a new release for SteamTinkerLaunch as a whole since this bug was fixed.

This entirely prevents Skyrim modding for most users using SteamTinkerLaunch and Vortex Mod Manager because FNIS (The mod most affected) is a requirement for pretty much anything that adds content to Skyrim. I've personally installed from source to fix this on my machine but I imagine this is preventing a whole tens of us from modding Skyrim :stuck_out_tongue: .

**Comment by sonic2kk** [comment]
This isn't a bug, just use SteamTinkerLaunch from source. What's the problem with that? It can even be installed from ProtonUp-Qt.

Also, SteamTinkerLaunch's primary purpose isn't for modding. I don't understand the issue with just using a git build, SteamTinkerLaunch is just a Bash script. And if it's really, really a big issue, a non-root install with the locale variable removed would fix the problem too.

For anyone reading this that wants a patchfile for some reason, you can make one from the PR #784

**Comment by sonic2kk** [comment]
There is no hard and fast rule about when I make an STL release, really just whenever I feel like it and have a name picked. The changelog isn't significant enough imo for a new release, and I'd like to fully implement #788 and work on #838 at minimum before a new release.

I wouldn't expect a new release for at least a few months.
