### ISSUE TITLE
Mod Manager 2 Web URL Portal does not work

### ISSUE THREAD

**Issue by jarrard** [sonic2kk/steamtinkerlaunch#851]
Can't open any MO2 link commands or commands into default browser. 

EDIT

As it turns out I was trying to use a preconfigured instance of MO2 which was pre setup. 

It seems things ONLY work with STL if you start a BRAND NEW MO2 install, no option or functionally to hook into pre-installed MO2 such as those from Wabbajack.

**Comment by jarrard** [comment]
I'll close this for now since you can swap in your own MO2 as a symlink and all is dandy. 

Sure it would be nice to just have some option to point STL to your preferred MO2 instance and have it symlink and hotwire it all in, but this works fine.

**Comment by sonic2kk** [comment]
There is no support for wabbajack in STL. See #305.

**Comment by jarrard** [comment]
Yeah I used a VM to install the package.  Someone has managed to get WJ working under Linux but its got problems.

**Comment by sonic2kk** [comment]
I'm not sure if it's what you were referring to in your OP, but NXM links and such are not supported anymore. They break very often and I'm not interested in trying to fix them.

It should also be noted that for any chance of NXM links to work, you need to use MO2 Game Mode. But the usage you have described, while nifty, is not supported by STL in general. Maybe one day if someone makes a PR, but STL isn't a modding tool :-)

**Comment by jarrard** [comment]
I was not specifically talking about NXM but opening links within the MO2 app.  
However installing MO2 vis STL then mapping over my standalone solves that.
