### ISSUE TITLE
Hedgemodmanager not opening after an otherwise seemingly succesful install

### ISSUE THREAD

**Issue by MialTheMimiga** [sonic2kk/steamtinkerlaunch#858]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: SteamOS
- Installation Method: ProtonUp-Qt

## Issue Description
After having installed Hedgemodmanager the most success i've actually gotten in launching it comes from using proton_TKG_6.17.r0.g5f19a815, but even then, it crashes before I can actually use it. while proton_tkg_7.6.r12.g51472395 jus hangs while installing.

## Logs
6.17: [steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12026030/steamtinkerlaunch.log)
7.6 [steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12026096/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Dotnet issues cannot be resolved by me, you'll have to try and troubleshoot this on your own. I haven't been able to replicate the issue and it seems dotnet48 has issues with Proton in general (it broke Vortex but luckily it was no longer required and has been removed there).

Sorry but you'll have to tinker for this one. No one has stepped up to help maintain HMM so there's not much I can do for an issue I can't replicate. And I'm not a Wine Dev so I can't investigate the more technical end (one user tried to a while back but it never materialised into anything).
