### ISSUE TITLE
Initial installation on Steam Deck

### ISSUE THREAD

**Issue by papawheelie** [sonic2kk/steamtinkerlaunch#863]
Maybe this is a very simple question and I'm just missing something obvious but how do I install steamtinkerlaunch from the ZIP folder? Ive tried dragging the steamtknkerlaunch file out from the extracted ZIP and using the terminal to run the lines in the instructions, but that just gives me an error. Im sure I did something wrong in the initial installation and would love if someone could point me in the right direction! Thanks!

**Comment by sonic2kk** [comment]
No problem :-) All you have to do to install SteamTinkerLaunch is double-click on the script file. If it is not marked as executable, mark it as such (either from the KDE properties file dialog or with `chmod +x`). Alternatively you can run `./steamtinkerlaunch`, the same way you would with any other script. Then it'll install automatically to `~/stl`. It will take time to fetch some dependencies, such as Yad, but in my experience it should take no more than about a minute *at most* (though it will vary depending on your Internet connection).

The [Installation Wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#install) has a section for how to install on Steam Deck. The process for installing SteamTinkerLaunch is as straightforward as executing a script the same way you would on your Linux Desktop.

As a courtesy warning as well, if you downloaded SteamTinkerLaunch v12.12, you probably don't want to use that. You should install from git, as v12.12 is very outdated. See the [changelog](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog) for more details. There are no plans to release a new SteamTinkerLaunch stable anytime in the near future.
