### ISSUE TITLE
Compatdata redirect to mayor version folder

### ISSUE THREAD

**Issue by cyberconan** [sonic2kk/steamtinkerlaunch#866]
## System Information
- SteamTinkerLaunch version: 12.12
- Distribution: Arch Linux

## Feature Description
I'm using compatdata redirect to global-proton directory, is an incredible and amazing option because I have a big compatdata folder with all requirements for diferent games (ubisoft connect, rockstar, directx, vcruntimes, ...). The only problem than I see happens when a Proton version have a minor upgraded because a new compatibility folder is created.

For solve this, I keep manually a structure folder like this:

![Screenshot_20230722_103757](https://github.com/sonic2kk/steamtinkerlaunch/assets/1497109/841c54c5-8af4-48b4-ad54-032926f78e95)

As you can see, for example, I'll keep a "compatdata-proton-8.0" and -2d and 3c versions are linked to "real folder". All my games using proton 8 version are always connected to this folder regardless they are using -2d or 3c version. Same with proton GE-8 or experimental versions.

Is possible to implement an option than can active compatdata folder names have mayor version names? Thank you so much for your work and dedication.

**Comment by sonic2kk** [comment]
This is done for prefix compatibility, as updating prefixes to different Proton versions is risky and can result in breakages. And going between different Proton major versions, such as Proton 7.0 to Proton 8.0, can be especially risky and *will* require the prefix to be updated to account for new DLLs, etc.

If I am understanding correctly,you can an option to only have new compatdata folders redirect for major Proton version changes, such as Proton 6/7/8, and probably also counting Experimental as a separate version. Then your folder structure would only have, for example, `compatdata-proton-8`.

I think this would be an ok idea to implement. It is definitely ***NOT*** desirable, but it is possible and we could add a checkbox. As far as implementation goes, I think we should disregard minor Proton version bumps when the option is enabled, such as Proton 8.0-3c. The same should go for Experimental bumps as well, just have one `compatdata-proton-experimental`. But we *should* still bump for new GE-Proton/tkg/etc versions.

One way to go about implementing this would be to derive the redirect folder name from the Proton folder name. Having this behind a checkbox means it will not be the default behaviour, so we don't need to worry about this being a "breaking" change. So in cases where a user already has `compatdata-proton-8.0-3c`, when they enable the checkbox they will then get `compatdata-proton-8.0`.

Deriving the folder name should be as simple as replacing spaces with `-` with a simple `sed`.

<hr>

I did not implement the compatdata redirect and am not very familiar with how it works, but this should not be too difficult. It should be a case of re-using the existing logic but using a different folder naming logic.

No ETA on an implementation, just whenever I am motivated, but thanks for the suggestion!

**Comment by sonic2kk** [comment]
Actually, aren't `compatdata-proton-8.0-3c` and folders like that a symlink to `compatdata-proton-8.0`?

**Comment by cyberconan** [comment]
Yes, the option could be only enabled with a checkbox in global configuration near "Symlink compatdata" and only if this one is enabled. Replacing -Xx with -sed is a good idea, more clear than remove the subversion code. As you said, this should not be difficult, maybe only be carefully with "steamuser symlink" options.

About GE-Proton8, only this week are released -7,-8 and -9 versions. I have tested several games linked to base GE-Proton8 folder and all works perfect, libraries inside are updated when launch first game. But of course, is better not mix GE-Proton7 with GE-Proton8, same like Proton 5, 6, 7 or 8 compatdata folders.

Thank you very much for considering the suggestion.

**Comment by cyberconan** [comment]
> Actually, aren't `compatdata-proton-8.0-3c` and folders like that a symlink to `compatdata-proton-8.0`?

This is my folder now. I have several symlinks as you can see.

![Screenshot_20230722_174020](https://github.com/sonic2kk/steamtinkerlaunch/assets/1497109/9c5442ae-a4ac-43c3-a18b-489a7b3bd98f)

PS: I found SteamTinker this week, if not I would have many many more folders linked :-)

**Comment by sonic2kk** [comment]
Looking at the symlinks, it looks like this feature request is already implemented? Proton 8.0-2d and Proton 8.0-3c already point to `~/.config/steamtinkerlaunch/proton/compatdata/compatadata-proton-8.0`. The GE-Proton versions also point to `compatdata-proton-GE-8`.

Please let me know if I'm misunderstanding. Did you create these symlinks yourself? I re-read your OP issue and it sounds like you might be, so I'd just like to confirm. If you created those symlinks (i.e. `compatdata-proton-8.0-2d -> /home/karl/.config/steamtinkerlaunch/proton/compatdata/compatdata-proton-8.0`) then that's fine, and that means what STL needs to implement is essentially what you have manually done. And in my opinion, if STL does not already do this, it is a useful feature to add, so this is a good feature proposal.

When I have some more time I'll investigate the code and the existing behaviour for myself, this isn't something I have touched before so it would be good regardless for me to get a little bit more background.

**Comment by cyberconan** [comment]
Exactly @sonic2kk. I created those simlinynks manually when a new version arrived. Basically I have the "Auto last Proton" and "Auto last Proton GE" options enabled. When I launch a game and a new Proton version appear, SteamTinker create a new compatdata-proton-XXXX folder than I remove and replace with a symlink to sed version. Then, all games launched later than use the same Proton version, updates the proton version in their conf files and use the linked global folder.

**Comment by sonic2kk** [comment]
Okay, that makes sense then. STL just needs to automate what you're doing manually now.

Thanks for clarifying, getting these kinds of details straight is useful for referencing when I'm writing an implementation (especially if I do it after some time has passed). It's also good to be able to point to after implementation to show how the feature came about.

When I have some time I will take a look at implementing this., I don't see it being a huge undertaking, since really it should just be a case of slightly altering the logic for how the compatdata is *named* (and then the name that STL checks for before creating a new symlink). But I've said this before and been burned ;-) 

Someone else is free to pick it up in the meantime if they really want but at the time of writing I think this is something I'd be happy to take a look at.

**Comment by sonic2kk** [comment]
I took a stab at implementing this. There is no UI option yet but an initial implementation was ridiculously easy to do. All that was needed was a conditional check and we can set the name of the Proton version in the redirect folder to `${USEPROTON%-*}`.

As an aside, the logic in that function could be massively improved, but that is not something I want to touch right now. There is a lot of duplicated logic that could be done better. The wiki also notes that there is opportunity for improvement, and incidentally also notes there is room for feature suggestion, so nice one!

I will get a PR up for this shortly.

**Comment by sonic2kk** [comment]
PR is up to implement this (#867). If you're able to I would really appreciate some testing on this. To test the PR you can either uninstall your existing STL from the AUR, or overwrite it with a manual root install by cloning the branch from the PR and running `sudo make install`.

You can also uninstall from the AUR and re-install with something like ProtonUp-Qt, which lets you install from branches directly when selecting "SteamTinkerLaunch-git" with Advanced Mode enabled.

**Comment by cyberconan** [comment]
Wow, great!! I'm going to change the STL-git PKGBUILD for get compatredir-major-proton instead master and test. Tomorrow I have a travel, my holidays ends :-(, but I'm going to start test and give you feedback soon. Thanks!!

**Comment by sonic2kk** [comment]
Changing the PKGBUILD is equally valid (haven't checked but I've done this before when testing some other projects, so it should work :slightly_smiling_face:)

Good luck! I can leave this issue and the PR open until you're free to test, this isn't massively urgent :-)

EDIT: Once this is merged to master, it will probably stay there for quite a while. I don't plan on releasing a new STL stable for a while, probably not anytime this year anyway. So if you want to use this feature you can use STL from git (Though feel free to switch back to the master branch once this is merged).

**Comment by cyberconan** [comment]
I have tested with various games:
- One game never launched before with STL. Set the new option ONLYPROTMAJORREDIRECT="1" and perfect, compatdata linked to compatdata-proton-8.0.
- Two games than were launched previously and had compatdata-proton-8.0-2d and 8.0-3c. After set the new option, both compatdata folders were linked to compatdata-proton-8.0.
- One game than was launched previously with compatdata-proton-GE-8-6. Option enabled and STL changes compatdata link to compatdata-proton-GE-8.
By the moment everything perfect. I'm going to enable the option massively in all games config and do more test.
Great great!!

**Comment by sonic2kk** [comment]
Those test results sound excellent, basically that the feature is working exactly as intended! I will probably merge this sometime over the next couple of days unless something really urgent happens and this feature cannot be merged.

I really appreciate you taking the time to test and verify that this works. As an aside, when looking at the code, it seems like some functionality related to this may have been intended to work in the past, but perhaps no longer does. The code already checks for the Proton version having a minor version before setting the name of the compatdata, so all that was needed for this change was to use `${USEPROTON%-*}` for the redirect compatdata name (this is Bash parameter expansion syntax that was even already in the code, which turns strings like `proton-8.0-2c` into `proton-8.0`, or `GE-Proton8-6` into `GE-Proton-8`).

Once I merge this feature into master, I'll close this issue :-)

**Comment by sonic2kk** [comment]
I also just did a quick test even with some older and more exotic Proton versions (Proton Experimental, Proton 6.3, a really old build of Proton-stl) and things worked fine, mainly I was concerned about how it was going to get the name for those Proton versions but it works fine. So edge cases seem good too.

**Comment by sonic2kk** [comment]
#867 was merged, this has been implemented now. Just another reminder that to use this you'll want to switch over to SteamTinkerLaunch from git.

Thanks for the feature request, I hope it helps you. Happy tinkering!
