### ISSUE TITLE
[Request] Wiki Addition | Steam Flatpak & SteamTinkerLaunch Flatpak

### ISSUE THREAD

**Issue by Sethox** [sonic2kk/steamtinkerlaunch#874]
## System Information
- SteamTinkerLaunch version:   v12.12 (Flatpak)
- Distribution: Arch Linux

## Feature Description

I request to add some advice into the wiki (under [Caveats](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Flatpak#caveats)) to the reader on the occasion the Flatpak Steam does not detect the Flatpak version of SteamTinkerLaunch. A [comment was made](https://github.com/sonic2kk/steamtinkerlaunch/issues/27#issuecomment-1616188425) that makes it advisable to do when such an occurrence happens.

Run
`flatpak run --command="/app/utils/steamtinkerlaunch/bin/steamtinkerlaunch" com.valvesoftware.Steam compat add`
on the console/terminal once and Flatpak Steam will detect Flatpak SteamTinkerLaunch as normal, provided Steam isn't launched when using the command. 

**Note:** Flatpak versions only.

**Comment by sonic2kk** [comment]
I did consider document it, but there is an open issue at the Flatpak repo asking users who experience this to help troubleshoot what causes the problem, as myself and the maintainer cannot reproduce it. It might be better to let users run into this in the hopes that they can help fix the underlying issue.

I may document it on the wiki later with an additional note asking users to help troubleshoot the problem, that may be the best compromise.

Thanks!

**Comment by Sethox** [comment]
Thanks for the fast reply. Closing until further notice then.

**Comment by sonic2kk** [comment]
[Updated the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Flatpak#caveats), was at work and didn't have a chance to update it until now. I didn't mean for you to close the issue or dismiss the proposal :-) The updated text is as follows:

> There is an [open issue](https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch/issues/110) on the Flatpak repo tracking an intermittent problem requiring an additional step for SteamTinkerLaunch to appear as a compatibility tool within Steam. If you experience this issue please report it over on the Flatpak repo and if you can, help troubleshoot the cause of the issue so that it can be fixed, as it seems to be difficult to reproduce.

**Comment by Sethox** [comment]
@sonic2kk You are absolutely right, my bad.

**Comment by termdisc** [comment]
For flatpaks, I suggest adding:

for bash: add `alias steamtinkerlaunch="flatpak run --command=steamtinkerlaunch com.valvesoftware.Steam"` to `~/.bashrc` 

for fish: run `alias --save steamtinkerlaunch="flatpak run --command=steamtinkerlaunch com.valvesoftware.Steam"`

This will make it easier to run `steamtinkerlaunch <args>` in the terminal, including `steamtinkerlaunch compat add`. If you're feeling really experimental, these could be added automatically using `tee` or `>>` during setup.
