### ISSUE TITLE
Steam Deck, starting custom forked command (trainer) not working anymore

### ISSUE THREAD

**Issue by sevenpastzeero** [sonic2kk/steamtinkerlaunch#875]
## System Information
- SteamTinkerLaunch version: v14.0.20230729-1 and Protonup-qt 12.12
- Distribution: SteamOS
- Installation Method: Protonup-qt both stable and master. And manual install.

## Issue Description
I've been using STL for a few months now and it was working fine until yesterday, when all of the sudden it no longer start trainer.exe in the background along with the game. I haven't changed any options, always used 'use custom command' and 'fork custom command'.
It now starts the trainer, but not the game.exe, until I close the trainer, then the game starts.
I tried reinstalling, completely removing stl and reinstall again. Both versions from protonup (my old working version was 12.12 from protonup), and installing v14 through cli.
If I use the option 'inject command' it works ok. But I never used the option before.

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12235285/steamtinkerlaunch.log) from /dev/shm after last running the game.

[412020.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12235291/412020.log) game log file from .config folder.

[lastrun.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/12235296/lastrun.txt)

**Comment by sonic2kk** [comment]
This is probably a Steam Client issue and not something STL can do anything about. If v12.12 stopped working too it's possibly the Steam Client at fault. STL just launches the process and if Steam can't do it anymore then it's probably a bug with Steam.

You can check the code to see how STL launches the process, it just runs it with Proton. Injecting the custom command also does the same thing, it just has a delay by default. It even uses the same function to launch, `launchCustomProg`.

What could also be happening is that this is an issue specific to your custom program and not STL or Steam.

You should also note that injecting the custom command overrides the "fork" option, as the tooltip on the checkbox tells you. So using your game and trainer probably doesn't work with the fork option anymore for whatever reason.

I tested on my Arch PC and using the fork and inject options worked no problem with a couple of different games and custom programs (tested with `v14.0.20230729-1`).

Closing as this isn't an STL issue.

**Comment by sonic2kk** [comment]
I just did a quick test and can partially and inconsistently re-create the issue you described on my Steam Deck. Sometimes both the game and custom program open fine, other times the custom program opens and the game will not open until the custom program is closed. When inject is used, the delay is probably what resolves the issue. I never had a case where the game itself would not launch after the custom program was closed. The game either always started as normal with the custom program, or after the custom program was closed.

This is either some strange race condition as a result of the Steam Deck speed that I can't re-create on my PC, but more than likely, this is some Steam Client bug, as Steam is probably doing some funky process checking stuff on the Steam Deck to tell which game started first, where to launch the Steam Overlay, and so on.

So more than likely this is a Steam Client bug specific to the Steam Deck. It isn't something STL can resolve.

Both my PC and Steam Deck are running the same Steam Client build (1690583737, Fri Jul 28 19:44 UTC -08:00). Since they're both running the same version and this behaviour is specific to the Steam Deck, this is the Steam Client at fault.

**Comment by sevenpastzeero** [comment]
Thank you for doing the tests, and confirming it is not STL issue. I guess Steam Client broke the fork command. I will stick to Inject option form now on.

**Comment by Laz55** [comment]
Basically  there is no solution? Basically  once again valve/steamdeck messed something  up. This is why I hate Linux always taking one step forward  while than taking a step back.

**Comment by Mte90** [comment]
I am able to replicate always on Steam Deck with a game and the fork command.
The trainer is executed at first but not the game. I had to close 2 times the trainer and on third time the game start together with the trainer.

Maybe a solution can be a delay setting to run another command? in this way the game start and the trainer after few seconds.

**Comment by sonic2kk** [comment]
This is already possible with the inject option, which was already mentioned in this issue and on the wiki. It also solved this issue.

I believe there's also a delay option for forked commands but I didn't check. Play around with the options, but this functionality already exists.

**Comment by Laz55** [comment]
The injection  option does not work at all. The individual  that mentioned
it  never gave a solution.

**Comment by sonic2kk** [comment]
The user stated the following at time of writing (emphasis by me).

>  I guess Steam Client broke the fork command. **I will stick to Inject option form now on.**

Keep in mind that if this is broken, it's up to Valve to resolve this behaviour, not STL. Steam Deck is not a priority platform.

**Comment by Laz55** [comment]
Hi


Yes that isn't a solution  or fix the problem is apparently  not having
Framework  dot4.8 which  is a nightmare  too install  on Linux well
because  Linux is a terrible  software.

**Comment by sonic2kk** [comment]
Linux is not Windows. If you want flawless support for your Windows software, don't use Linux.

Please also keep conversations on topic and be more polite. Comments like the above and several of your other comments across SteamTinkerLaunch come across as very entitled and rude. You've expressed your hatred for Linux plenty, it's not relevant to SteamTinkerLaunch which is for Linux enthusiasts.

**Comment by Laz55** [comment]
Hi


Neevr said  it was.  The issue  is Linux  and the program is a windows
based which pretty  much all Trainers are made with  window's.  Windows is
fine it's Linux.  Not having dot.4.8 is what's causing  the fork function
not recognize  the trianer.  So, the fork function  does work it's just
that I am missing  dot4.8 framework  which is a nightmare  too install  on
Steamdeck  Os Linux.  Linux is a terrible  software.  Your program  is
excellent it's just Linux is terrible  which is is why less than 4% of user
worldwide  use it.

**Comment by Laz55** [comment]
I am blunt and dirct which your taking as rude, well you  need too get out
of the hous into the world  dude because  being blunt/direct isn't rude.
Perhaps  interacting  with humans  outside  of texts,  etc.. will help.
