### ISSUE TITLE
Cheat Engine

### ISSUE THREAD

**Issue by FallenGodAngel** [sonic2kk/steamtinkerlaunch#884]
Hi SteamTinkerLaunch Developer , sorry for my English but its not my first language. I just want to request the option of Cheat Engine again into the game menu check boxes. The point is this Some friends and I we use cheat engine to play moded games like Elden Ring with mods that have an online differet that doesnt affect legit players. I use the cheat engine because the tables are made for only that tool. Now the issue is we have tried opening CE with wine and running the ceserver as a sudo but it doesnt open the game process to run the tables. I think CE will not affect gamers performance at all. Most gamers play legit , another likes to play Mods like a I do with my friends for fun and others just cheat and no one likes them. This is a humble request with all due respect. I want to say thank you because your STL is awesome.

**Comment by sonic2kk** [comment]
Thanks for opening an issue, however Cheat Engine has been removed from SteamTinkerLaunch for numerous reasons.

Games which use invasive anti-cheat technology, such as Elden Ring, are likely to flag Cheat Engine and thus SteamTinkerLaunch as a whole as a cheat tool. This puts users of SteamTinkerLaunch at risk if they use it with games without cheating.

Secondly, Cheat Engine is not a very trustworthy program from what I have seen. It has been noted here and elsewhere that they package some shady adware, as well as they and others gating cheat tables behind a paywall.

Finally, it is actually **against the Cheat Engine license** for SteamTinkerLaunch to have support for Cheat Engine. It violates the Cheat Engine license for SteamTinkerLaunch to distribute and install it. Previously we used the Chocolatey package manager package (a Windows package manager), which also seemed to strip a lot of the adware, but this was against the Cheat Engine license and so was removed from SteamTinkerLaunch and thereafter from the Chocolatey repositories. Therefore, we **cannot** have Cheat Engine support in SteamTinkerLaunch, even if I wanted to add it, which to be blunt, I don't :sweat_smile: 

In sort, Cheat Engine was removed from SteamTinkerLaunch for specific reasons and it will not be returning. You can read more about the removal of Cheat Engine at #618 and [on the FAQ](https://github.com/sonic2kk/steamtinkerlaunch/wiki/FAQ#where-did-cheat-enginegameconqueror-go).

I recognise that you may be having difficulty using Cheat Engine, but it is not STL's place to advise on how to use programs with Wine under Linux. Having said that, using `sudo` for anything running under Wine is probably not the way to go, so I suspect you might be on the wrong track.

There may be a fork of SteamTinkerLaunch available which implements Cheat Engine, but this would be **entirely unofficial**, so I cannot vouch for the changes made, the up-to-dateness, or anything else with that project. Such a project is also in direct violation of Cheat Engine's license, so you would be using such a project entirely at your own risk, if the project still exists at all.

I hope this reply has helped clear things up on why Cheat Engine was removed, and why it actually *cannot* be readded. :slightly_smiling_face:

**Comment by FallenGodAngel** [comment]
Thank you so much for the response and also for the clarification. I completely understand now , however  I want to thank you for the STL . Its amazing and appreciate the great work you have done.

**Comment by sonic2kk** [comment]
No problem at all, there have been ups and downs for sure but as long as I'm still using STL I'll keep maintaining and expanding it :slightly_smiling_face: Happy tinkering!

**Comment by FallenGodAngel** [comment]
Hello Sonic2kk,

I've been wondering about how you managed to make CE recognize the currently running game application in a way that is visible to CE itself. I've been trying to achieve this manually by running the CE Server, then going to the network section in CE and locating the app, but I haven't been able to find any relevant data. Would it be possible for you to share some insights on this process, or if it's not too complex, maybe guide me through creating a small standalone application just for this purpose? I apologize for seeking your assistance on this matter, but I believe in reaching out to someone who has already succeeded and gained valuable experience. I've been struggling with setting up CE individually for about 2 months now and haven't made any progress.

Thank you very much for your time and expertise. Your assistance would mean a lot to me.

**Comment by FallenGodAngel** [comment]
Hey Sonic , I got it running using protonhax. I will do a tutorial on youtube in case someone ask how again :) thanks for everything :)

**Comment by sonic2kk** [comment]
I did not actually write the Cheat Engine integration, it was written by the previous maintainer Frostworx before I took over the project.

However, it looks like Cheat Engine was just installed to the game prefix and then the Cheat Engine executable was just launched in the game prefix. I am not sure that anything relating to a Cheat Engine server needed, at least I don't see anything like that in older releases of SteamTinkerLaunch (v11.11).

STL lets you select a custom executable to launch, so it should be able to do the same thing Protonhax is doing. Installation could be performed manually or with One-Time Run, if it uses an installer program (which I believe it does).

**Comment by FallenGodAngel** [comment]
[how open cheat engine with protonhax.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/12448748/how.open.cheat.engine.with.protonhax.txt)

**Comment by jon-bit** [comment]
@FallenGodAngel Do you have anything for mint?

**Comment by sonic2kk** [comment]
The steps here for Protonhax apply to SteamTinkerLaunch, as noted already. All those steps are doing is running the Cheat Engine executable in the game prefix, which STL already allows for. You can do this either with a custom command, or with One-Time Run.

However, the only steps in that guide which are specific to Arch Linux is the installation of Protonhax. All you'll need to do if you want to use Protonhax is to install it on Linux Mint.

**Comment by sonic2kk** [comment]
I am going to lock this as this has gotten off-topic, and I do not condone usage or discussion of Cheat Engine.

SteamTinkerLaunch is not a cheat tool, and this issue tracker is not a discussion board for tools that support has been explicitly removed for.
