### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#89]
Not a fix goal, but more a poll:

Would anybody be interested in multi-language support and/or also willing to contribute translations for different languages?

The raw idea is to have one "language" directory with one file per language in it, and let the user choose one via dropdown menu. The selected file would be sourced on stl launch and all variables are translated.
Initially the english file would be sourced, so new/untranslated parts are filled anyway.
_(by using `source` it is also no problem to include Variables)_

```
**Example:**

`language/english.txt`:
`NOZEN="zenity support is not implemented in this function"`

`language/german.txt`:
`NOZEN="Diese Funktion hat keine zenity Unterstützung"`
```

**Comment by frostworx** [comment]
I already started with extracting all Strings into an external "english.txt" and implemented a Language Selection.
So at least my English and German Translation will be available.

**Comment by Pyr0x1** [comment]
Hi, if this will be implemented I can help with italian translation.

**Comment by frostworx** [comment]
[v2.3.0](https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.3.0) with translation is released.
Thank you @Pyr0x1!

**Comment by Pyr0x1** [comment]
Great, I'll start working on it asap 👌

**Comment by frostworx** [comment]
Thank you very much! Take your time, I'm really happy that you help! :)

**Comment by frostworx** [comment]
Also here thank you very much @Pyr0x1! :+1:

**Comment by frostworx** [comment]
Doesn't look like there's a major interest in contributing to the project, so closing here
