### ISSUE TITLE
Can't download custom proton

### ISSUE THREAD

**Issue by daemonspudguy** [sonic2kk/steamtinkerlaunch#890]
## System Information
- SteamTinkerLaunch version:  12.12
- Distribution:  Debian 13
- Installation Method:  ProtonUp-QT

## Issue Description

I can't download any Proton versions.

**Comment by daemonspudguy** [comment]
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12500341/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Do you have `jq` installed? It is unclear from your log if you attempted to download a custom Proton version before attaching.

`jq` is noted on the [Installation wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#dependencies-1) as a highly recommended dependency when installing SteamTinkerLaunch, including for downloading custom Proton versions.

**Comment by daemonspudguy** [comment]
Apparently I did not. I'm installing it now,

**Comment by sonic2kk** [comment]
By the way, it is not explicitly relevant for this issue, but SteamTinkerLaunch v12.12 is very outdated. Please use a release of SteamTinkerLaunch from git (available from ProtonUp-Qt in advanced mode).

**Comment by daemonspudguy** [comment]
I've been using the latest released version because I've historically had many problems using GitHub CI builds from master.

**Comment by sonic2kk** [comment]
SteamTinkerLaunch does not have any GitHub CI builds, it is just a Bash script. You could view using SteamTinkerLaunch from git as similar to using `winetricks --self-update`.

The latest release is from March, and I don't have any plans to release a new version anytime soon, so my recommendation to all users is always to use the most up-to-date git release.

**Comment by daemonspudguy** [comment]
A combination of switching to the Git version and installing jq worked.

**Comment by sonic2kk** [comment]
Glad to hear it! ProtonUp-Qt points out in its SteamTinkerLaunch description that SteamTinkerLaunch has a number of hard dependencies and optional dependencies. Be sure to read the wiki to view these and make sure you have the relevant dependencies for the functionality you're trying to use.

> SteamTinkerLaunch has a number of Optional Dependencies which have to be installed separately for extra functionality. Please see the Optional Dependencies section of the SteamTinkerLaunch Installation guide on its GitHub page..

Happy tinkering!
