### ISSUE TITLE
allow nvim for AUR install

### ISSUE THREAD

**Issue by slbsh** [sonic2kk/steamtinkerlaunch#891]
the install script for the aur package (ver. 12.12-1) requires either `vim` or `gvim`,
prob a good idea to optionally allow `neovim` and `neovide`. 

No idea if this is cause of another dependency, just throwin it out there

**Comment by sonic2kk** [comment]
Thanks!

This would be better to request on the AUR page though. I think it was requested previously, the AUR package maintainer would be more suited to comment on whether or not nvim is an acceptable dependency.
