### ISSUE TITLE
⚠️ SteamOS 3.5 Support

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#907]
## System Information
- SteamTinkerLaunch version: v14.0.20230916-2
- Distribution: SteamOS

## Feature Description
SteamOS 3.5 is available on the Preview channel now with some updates to the Arch Linux installation. As per [Valve's official announcement](https://store.steampowered.com/news/app/1675200/view/3686804163591367815):

> An upgraded Arch Linux base for the operating system.

Historically, we had to bump some dependency versions to be compatible with the newer Arch Linux packages, such as `innoextract` which is for some reason required for MO2 to install properly on SteamOS. We should probably revisit this in general to check if it's still required, but I cannot test as I don't mod games on my Steam Deck. I'm also wondering if the Yad AppImage still works, it probably does and we should bump it anyway (as suggested in #859), but I'm more concerned with whether or not it works.

I'm opening this issue to track if anything in SteamTinkerLaunch has broken in SteamOS 3.5 Preview. I don't anticipate many (any?) changes to the Arch base packages that would impact SteamTinkerLaunch between 3.5 going from Preview -> Beta -> Stable, so we really only need to be concerned with issues surrounding SteamOS 3.5 Preview.

If anyone is able, please try out the SteamOS 3.5 Preview and report back with any issues :-) If there are none, we can close this issue.

**Comment by frosty5689** [comment]
Looks like innoextract 1.9-7 is not supported by Steam OS 3.5 due to missing libboost shared library of the matching version

Edit: Tried innoextract 1.9-8 and that worked. It is a problem with how cutting edge Archlinux is, even a slight difference in version uses a different version of shared lib :/

**Comment by sonic2kk** [comment]
Thanks for checking, I had a hunch on this! A similar issue came up with the bump to SteamOS 3.4.

I'll probably make a SteamOS 3.5 branch with the bumped innoextract, which I'll keep up-to-date with master until SteamOS 3.5 is out.

I would not say it's a problem with Arch though, it's specifically because SteamOS uses an Arch snapshot an has an immutable filesystem. If users could more easily install dependencies it would function the same way it does on desktop. The snapshot SteamOS uses is far from cutting edge, too (in fact, these days Arch is barely cutting edge by default :slightly_smiling_face:).

**Comment by sonic2kk** [comment]
Created a SteamOS 3.5 branch, if any other changes are required (such as a cabextract bump or anything else like maybe a Yad version bump?) that can be handled on that branch for now, as generally these bumps are not backwards compatible with the older Arch snapshots used by older SteamOS releases. Hopefully, though, no other changes should be needed.

Manually removing the installed innoextract or running `steamtinkerlaunch cleardeckdeps` and then re-running STL should reinstall the dependencies and  thus bump to a newer version :-)

Once SteamOS 3.5 is out I will merge this branch in.

**Comment by frosty5689** [comment]
```
steamtinkerlaunch mo2 start
Preparing to install SteamTinkerLaunch on Steam Deck
Downloading latest SteamTinkerLaunch

Dependency 'innoextract' already installed, nothing to do.
Dependency 'cabextract' already installed, nothing to do.
Dependency 'yad' already installed, nothing to do.

Finished installing SteamTinkerLaunch ('v14.0.20231008-1')!
Sat Oct  7 03:09:56 PM PDT 2023 INFO - setModWine - Downloading: 'https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-16/GE-Proton8-16.tar.gz'
/home/deck/stl/prefix/steamtinkerlaunch: line 3936: [: : integer expression expected
Sat Oct  7 03:09:57 PM PDT 2023 ERROR - setModWine - DNPROTON was not found - can't continue
/home/deck/stl/prefix/steamtinkerlaunch: line 3936: [: : integer expression expected
/home/deck/stl/prefix/steamtinkerlaunch: line 3936: [: : integer expression expected
```

Trying to install MO2 from commandline and got these errors. Not sure if this is a known issue and there is a solution or a Steam OS 3.5 specific issue.

**Comment by sonic2kk** [comment]
~~Is your MO2 Proton version set correctly?~~ Hmm it looks like it couldn't download a MO2 Proton version for some reason. I wonder if downloading Proton versions is broken again.

I doubt it's SteamOS specific, but I don't know as I am very against using mod tools on SteamOS. For more help you should open another issue and attach full, complete logs and any other information that might be relevant.

Also, it looks like you didn't change to the correct branch? The version is `v14.0.20231008-1`, it should be `v14.0.20231008-2 (steamos-3.5)`. Make sure you checked out the correct branch when you cloned.

<hr>

Fwiw couldn't re-create the problem on my PC, and the line referenced in the error is to `if [ "$CUPROTOCOMPAT" -eq 1 ]; then`, which is a check in `dlCustomProton` for where to extract the Proton version. However, that wouldn't cause a failure on its own. It seems that either the Proton version failed to download (perhaps a network/github issue) or STL could not extract it.

I have not tested on SteamOS, and will not be testing as I for the most part avoid tinkering on SteamOS, but I don't see why there would be a specific issue with it on SteamOS, since the `dlCustomProton` function is pretty universal.

**Comment by sonic2kk** [comment]
Seems like the only thing needed for SteamOS 3.5 support is the innoextract bump.

Closing this issue as no one has reported problems outside of the innoextract bump. We might have to unfortunately make a new release when SteamOS 3.5 is out, bleh.

**Comment by Velonox** [comment]
For me I am trying to install Hedgemodmanager and at a certain point it gets stuck after the 2.5 update when before it had no issues

**Comment by sonic2kk** [comment]
Sounds like a Wine compatibility issue that no one can fix. Also, that's unrelated to this issue, and afaik no one can help. The Steam Deck is a bad device to mod on, please don't do it, and SteamTinkerLaunch will likely not be supported on SteamOS for much longer.

If you can find the exact Wine issue feel free to submit a PR to fix it, otherwise I am not interested in troubleshooting mod tools problems on SteamOS as it is a bad device to mod on.
