### ISSUE TITLE
Screen keeps going black while gaming

### ISSUE THREAD

**Issue by Cyberopiates** [sonic2kk/steamtinkerlaunch#914]
Sorry guys i’m a total noob, i’m trying to find the issue on this and not sure what’s causing it, i’m only using the Reshade function for my Sims 4
Is there anything missing?
## System Information
- SteamTinkerLaunch version: 
- Distribution: 
- Installation Method: Protonup qt

## Issue Description
 The screen keeps going black suddenly mostly around the same time which is after about 15 minutes or so after entering my save. If i have it on main menu for longer it never happened and it works perfectly fine with the Reshade. Fyi i only use this for Reshade for my Sims 4 game lol 
But yeah am i doomed #or is it something fixable? Am i missing something?  

## Logs
another one from game 
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
Setting breakpad minidump AppID = 1222670
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561199072118046 [API loaded no]
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
info:  Game: EABackgroundService.exe
info:  DXVK: v2.3-1-g5828f0e2b9b233b
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x2d4addae0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
warn:  OpenXR: Unable to get required Vulkan instance extensions size
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
warn:  OpenXR: Unable to get required Vulkan Device extensions size
info:  AMD Custom GPU 0405 (RADV VANGOGH):
info:    Driver : radv 23.0.99
info:    Memory Heap[0]: 
info:      Size: 3050 MiB
info:      Flags: 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[5]: Property Flags = 0xe
info:      Memory Type[6]: Property Flags = 0xe
info:      Memory Type[8]: Property Flags = 0xc6
info:      Memory Type[10]: Property Flags = 0xce
info:    Memory Heap[1]: 
info:      Size: 6101 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[3]: Property Flags = 0x7
info:      Memory Type[4]: Property Flags = 0x7
info:      Memory Type[7]: Property Flags = 0xc1
info:      Memory Type[9]: Property Flags = 0xc7
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
Fossilize INFO: Overriding serialization path: "/home/deck/.local/share/Steam/steamapps/shadercache/1222670/fozpipelinesv6/steamapprun_pipeline_cache".
Fossilize INFO: Overriding serialization path: "/home/deck/.local/share/Steam/steamapps/shadercache/1222670/fozpipelinesv6/steamapprun_pipeline_cache".
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
Fossilize INFO: Overriding serialization path: "/home/deck/.local/share/Steam/steamapps/shadercache/1222670/fozpipelinesv6/steamapprun_pipeline_cache".
Fossilize INFO: Overriding serialization path: "/home/deck/.local/share/Steam/steamapps/shadercache/1222670/fozpipelinesv6/steamapprun_pipeline_cache".
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
Fossilize INFO: Overriding serialization path: "/home/deck/.local/share/Steam/steamapps/shadercache/1222670/fozpipelinesv6/steamapprun_pipeline_cache".
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
pid 7553 != 7552, skipping destruction (fork without exec?)

**Comment by sonic2kk** [comment]
There isn't much information to go on, but this isn't a SteamTinkerLaunch issue, if the screen keeps going black it could be related to ReShade or a game bug. Sorry, this isn't a Linux gaming support forum. Closing.

Fyi, the log you provided is from the game log. If you think there are issues here you might be better off reporting this to a forum related to your Linux distribution, or a general Linux gaming support forum.

**Comment by Cyberopiates** [comment]
Thankyou for clearing that up
