### ISSUE TITLE
Outdated Windows (Vortex Installation)

### ISSUE THREAD

**Issue by DaddyDarko** [sonic2kk/steamtinkerlaunch#924]
## System Information
- SteamTinkerLaunch version: v12.12 
- Distribution: Nobara Linux 38 (KDE Plasma) x86_64
- Installation Method: Package Manager

## Issue Description
So, I'm on Nobara, and STL is prepackaged with it (thankfully, as I can't even install pacstal on Nobara). Took me a bit to figure out the yad problem, but I did. However, I can't find any way of launching STL by itself. I have to enter the command line argument for (in my case Fallout 4) and then it runs before launching the game. Here's where my problems start (as there is no documentation that I can find for using STL on Nobara or Fedora for that matter) So, I run Fallout, STL pops up, I clicked on Vortex, Install, Install again, and it hung on the dotnet installation, errors out and tells me it can't proceed, I've already screwed up and clicked "Ignore" so I don't remember what, exactly, the error message said, but it gave me an "Abort", "Retry" which opens up a webpage for problems on Windows, which doesn't help me, and "Ignore". After having clicked "Ignore" it instantly stopped, and doesn't open Vortex now. I can't find anyway to delete what it did install, and have no idea where to go from here. the error message reads that "Vortex 1.8 and above is not compatible with your operating system. windows 10 or newer is required to run correctly.  

Any help would be appreciated.

**Comment by sonic2kk** [comment]
SteamTinkerLaunch v12.12 is outdated, please update to SteamTinkerLaunch-git.

However the issue you mentioned is an intermittent Wine issue, create a new prefix when using a newer STL version and Proton version (latest GE usually works) and try again.

Also, you should not be using SteamTinkerLaunch as a command line argument in this instance. Use it as a compatibility tool option. The readme mentions this.

> I can't find anyway to delete what it did install, and have no idea where to go from here.

SteamTinkerLaunch creates a Vortex prefix at `~/.config/steamtinkerlaunch/vortex/compatdata`. Remove this to uninstall Vortex. I believe this is mentioned on the STL wiki.

> However, I can't find any way of launching STL by itself

Not sure how that's relevant to this issue, but you can do it from the commandline. Remember, SteamTinkerLaunch is a tool for experienced Linux users. If you don't use the commandline frequently and/or you aren't comfortable with it, STL may not be for you.

<hr>

I'm not trying to be rude so please don't take it the wrong way but did you read the Readme and Vortex wiki before opening this issue? I believe these should have answered the questions (Readme tells you how to use STL with games, Wiki tells you about commandline usage and to use STL-git with Vortex, changelog outlines Vortex improvements).
