### ISSUE TITLE
When is version 14.* released?

### ISSUE THREAD

**Issue by JohnDoe-404** [sonic2kk/steamtinkerlaunch#925]
Hello. When is version 14.* released? Currently only version 12.12 is available. I would like to update already.

**Comment by sonic2kk** [comment]
There is nothing stopping you from updating. Just install to SteamTinkerLaunch-git, SteamTinkerLaunch is just a Bash script. There is no compilation needed, just `git clone` and `sudo make install`, or add the script to your PATH variable and use it that way. Some repositories such as the AUR and Pacstall already package STL-git, though it is very straightforward to install a git version regardless.

I have no plans for v14.0 anytime in the near future.
