### ISSUE TITLE
[Feature Request] Launch Menu configuration

### ISSUE THREAD

**Issue by tralph3** [sonic2kk/steamtinkerlaunch#95]
I would like to request the ability to edit Launch Menu's for any game, allowing us to add custom entries with different names and executables, the same way [Steam Edit](https://steamedit.tg-software.com/) does it.

**Comment by frostworx** [comment]
Thanks for the suggestion.
Just took a quick look at the URL and that is much more invasive than I initially thought.
I do not want to alter Steam's own internal configurations, so I'm afraid I won't implement changing any titles.
I'm still interested in adding custom entries from stl though, but I do not even know if it would be even possible.
The idea to have a choice between multiple start options per game sounds interesting _(TBH I thought that was your main request)_. It might be a good reason to re-implement the "tweaks", but I'm not sure yet if and how this should be handled best.

**Comment by tralph3** [comment]
That's okay if you want to keep Steam itself intact, and just change the games and manage wrappers. I actually didn't try to run the program through wine and see if it works at all, in any case I might end up doing a program myself to do this.

**Comment by frostworx** [comment]
I decided to not implement multiple start options for one single game and I'm _(currently?)_ not interested in spending time in analyzing the "add custom game" function from the steam client.
I wish you much fun with rolling your own program.
