### ISSUE TITLE
When launching a game with a custom command, tool options do not work

### ISSUE THREAD

**Issue by Rabcor** [sonic2kk/steamtinkerlaunch#954]
## System Information
- SteamTinkerLaunch version: 12.12
- Distribution: Manjaro
- Installation Method: AUR (yay)

## Issue Description
If I configure a game to launch with a custom command instead of normally, None of the tool options (mangohu at least) seem to be working. If I launch the game without the custom command, it works normally.

On the other hand, if I use steam's own launch options to activate the tools (e.g. mangohud %command%) then it does work, however for some of them (like gamemode and prime-run) if they are active that way steamtinkerlaunch will take an incredibly long time (up to a couple of minutes) to load.

Tested games:
BeamNG.Drive (BeamMP)
Skyrim (SKSE)

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13067564/steamtinkerlaunch.log) (BeamNG)
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13067590/steamtinkerlaunch.log) (Skyrim)

**Comment by sonic2kk** [comment]
There is a checkbox for this on the Game Menu, grouped with the other custom program options (#732). External programs such as MangoHud are only passed when this checkbox is enabled, and when "Only custom command" is used. This is working on my end as I use this semi-frequently.

Did you forget to enable this? Based on the log it appears so as it doesn't log anything about `EXTPROGS_CUSTOMCMD`, but I'd like to confirm.

**Comment by Rabcor** [comment]
> There is a checkbox for this on the Game Menu, grouped with the other custom program options (#732). External programs such as MangoHud are only passed when this checkbox is enabled, and when "Only custom command" is used. This is working on my end as I use this semi-frequently.
> 
> Did you forget to enable this? Based on the log it appears so as it doesn't log anything about `EXTPROGS_CUSTOMCMD`, but I'd like to confirm.

It was not enabled, I didn't even notice it in fact (the label doesn't make much sense to me, which is the reason), but enabling it did indeed solve this issue.

I aplogize for creating a duplicate issue, I will just shamelessly blame git's god awful issue search function (I searched 'custom command' and it did not show up on the first page, in fact there were only 2 results that even had 'custom command' in it's tags or title in the first place)
