### ISSUE TITLE
Custom Environment Variables

### ISSUE THREAD

**Issue by Rabcor** [sonic2kk/steamtinkerlaunch#955]
## System Information
- SteamTinkerLaunch version: 12.12
- Distribution: Manjaro

## Feature Description
Please enable setting custom environment variables so that settings not covered by steamtinkerlaunch's many tickboxes can be enabled somehow (or in case they fail)

**Comment by sonic2kk** [comment]
This is already set up both globally for every game launched with SteamTinkerLaunch, or locally for per-game environment variables. Check the Game Files menu to see the checkbox to open and edit this file. [This is also documented on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/ENV-Variables), as this feature was added a very long time ago.

If the menu is too overwhelming, you can always edit the global, default, and per-game config files manually at `~/.config/steamtinkerlaunch`. The wiki documents various paths you may need as well. You can even set these values individually rom the commandline.

Also, please use SteamTinkerLaunch from git, v12.12 is very old.

**Comment by Rabcor** [comment]
I see, thanks, web search has failed me.
