### ISSUE TITLE
Unable to start games, get fullscreen black window, or fullscreen transparent window

### ISSUE THREAD

**Issue by viggy96** [sonic2kk/steamtinkerlaunch#96]
This issue occurs on several games. The games that I tested are Hades, Project Cars 2, Control, and The Witcher 3. The same issue occurs on all games.
Here is the log for Hades, this game produces a fullscreen black window: 
[1145360.log](https://github.com/frostworx/steamtinkerlaunch/files/5342630/1145360.log)
Here is the log for Project Cars 2, this one produces a fullscreen transparent window:
[378860.log](https://github.com/frostworx/steamtinkerlaunch/files/5342632/378860.log)

I am using gamemode, and MangoHUD. I have no issues running these games with both gamemode and MangoHUD without stl.

Neither log file shows any errors, or anything that would suggest anything wrong.

**Comment by frostworx** [comment]
I see you have vkBasalt enabled. Does it work when you disable it?
If no, would you please also post the logs of Witcher 3 and Control?
I don't own Hades and I'd like to avoid downloading the >50GB ProjectCars2 game for testing.

**Comment by frostworx** [comment]
just gave Control a quick try with gamemode and MangoHud enabled it it works as expected.
left vkBasalt disabled (which is default)

**Comment by viggy96** [comment]
@frostworx Interesting... I think GOverlay had vkbasalt enabled globally, and it was doubly enabled somehow. Yeah, I disabled vkBasalt in stl, and the games are working just fine as expected.
Thanks for your work. I was sick of adding "gamemoderun %command%" to every single game.

**Comment by frostworx** [comment]
nice!
Before stl I wrote [this little script ](https://gist.github.com/frostworx/36bd76e705a0c87af523fa57cfeebaf8) to set `gamemoderun %command%` for every game. _(also mentioned in the [stl readme](https://github.com/frostworx/steamtinkerlaunch#steam-launch-option))_
