### ISSUE TITLE
Vortex always has the error about 1.8.0+ only works with Windows 10 even after wiping files for a fresh install

### ISSUE THREAD

**Issue by Fembussy69** [sonic2kk/steamtinkerlaunch#978]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: EndeavourOS (Arch-based)
- Installation Method: Package Manager (yay - pamac helper)

## Issue Description
Vortex fails to start even after wiping caches and config files clean. I wanted to mod Fallout 4 again, not sure if the game matters.
The first time I installed Vortex, it ran fine, but I messed up something and wanted to start over, so I read the wiki, wiped the files for a fresh start, installed again, but now I continuously get the 1.8.0+ Windows 10 only error. I made sure it will use GE-Proton8-2 or the latest GE-Proton8-23. I hope I didn't miss anything in the wiki for Vortex, but I don't think I did.

https://appdb.winehq.org/objectManager.php?sClass=version&iId=41567

I checked for issues with wine and don't see anything, so I don't think it's a wine problem.

## Logs
Fri Nov 17 03:37:45 PM CST 2023 INFO - setflatpak - started SteamTinkerLaunch from /usr/bin/steamtinkerlaunch
Fri Nov 17 03:37:45 PM CST 2023 INFO - initAID - Set AID from STEAM_COMPAT_APP_ID to '377160'
Fri Nov 17 03:37:45 PM CST 2023 INFO - initAID - Set OSCDP to STEAM_COMPAT_DATA_PATH '/home/fembussy/Samsung860EVO_1TB/SteamLibrary/steamapps/compatdata/377160'
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLangFile - Language from command line is 'english'
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/usr/share/steamtinkerlaunch/lang'
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLangFile - Loading found system wide /usr/share/steamtinkerlaunch/lang/english.txt
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLanguage - Loading STLLANG from '/home/fembussy/.config/steamtinkerlaunch/global.conf'
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLanguage - STLLANG from '/home/fembussy/.config/steamtinkerlaunch/global.conf' is 'english'
Fri Nov 17 03:37:45 PM CST 2023 INFO - setLocalInstall - Looks like we don't have a local non-root install
Fri Nov 17 03:37:45 PM CST 2023 INFO - updateConfigEntry - Option 'GLOBALCOLLECTIONDIR' is updated with the new value '/usr/share/steamtinkerlaunch/collections' in config 'global.conf'
Fri Nov 17 03:37:45 PM CST 2023 INFO - getCurrentCommandline - No Proton in command line arguments 'vortex install gui'
Fri Nov 17 03:37:45 PM CST 2023 INFO - saveOrgVars - Storing some original variables to restore them later
Fri Nov 17 03:37:45 PM CST 2023 INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
Fri Nov 17 03:37:45 PM CST 2023 INFO - emptyVars - Set $PATH to '/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:::'
Fri Nov 17 03:37:45 PM CST 2023 START - ######### Initializing Game Launch 377160 using SteamTinkerLaunch v12.12 #########
Fri Nov 17 03:37:45 PM CST 2023 INFO - main - Starting with a clean log
Fri Nov 17 03:37:45 PM CST 2023 INFO - main - Start creating default configs
Fri Nov 17 03:37:45 PM CST 2023 INFO - createDefaultCfgs - START
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLangFile - Language from command line is 'english'
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/usr/share/steamtinkerlaunch/lang'
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLangFile - Loading found system wide /usr/share/steamtinkerlaunch/lang/english.txt
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLanguage - Loading STLLANG from '/home/fembussy/.config/steamtinkerlaunch/global.conf'
Fri Nov 17 03:37:45 PM CST 2023 INFO - loadLanguage - STLLANG from '/home/fembussy/.config/steamtinkerlaunch/global.conf' is 'english'
Fri Nov 17 03:37:45 PM CST 2023 INFO - createDefaultCfgs - setSteamPaths:
Fri Nov 17 03:37:45 PM CST 2023 INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
Fri Nov 17 03:37:45 PM CST 2023 INFO - getGameOS - Starting game OS detection
Fri Nov 17 03:37:45 PM CST 2023 WARN - getGameOS - Could not extract the full game binary path from the incoming game launch command, so assuming this is a Windows game!
Fri Nov 17 03:37:45 PM CST 2023 INFO - setWin - '' determined to be a Windows Game
Fri Nov 17 03:37:45 PM CST 2023 INFO - createDefaultCfgs - createProtonList:
Fri Nov 17 03:37:45 PM CST 2023 INFO - createDefaultCfgs - createProtonList end
Fri Nov 17 03:37:46 PM CST 2023 INFO - listAllSettingsEntries - '/dev/shm/steamtinkerlaunch/setentries.txt' already exists - nothing to do
Fri Nov 17 03:37:46 PM CST 2023 INFO - createDefaultCfgs - STOP
Fri Nov 17 03:37:46 PM CST 2023 SKIP - listSteamLibraries - not recreating already available '/dev/shm/steamtinkerlaunch/SteamLibraries.txt'
Fri Nov 17 03:37:46 PM CST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_LIBRARY_PATHS set to '/home/fembussy/Samsung860EVO_1TB/SteamLibrary/steamapps:/home/fembussy/.local/share/Steam/steamapps:/home/fembussy/Samsung870QVO_2TB/SteamLibrary/steamapps:/home/fembussy/Seagate_HDD_2TB/SteamLibrary/steamapps:/home/fembussy/WDEZEX_HDD_1TB/SteamLibrary/steamapps'
Fri Nov 17 03:37:46 PM CST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_MOUNTS set to '/home/fembussy/Samsung860EVO_1TB/SteamLibrary/steamapps/common/Steamworks Shared:/home/fembussy/Samsung860EVO_1TB/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier:/home/fembussy/Seagate_HDD_2TB/SteamLibrary/steamapps/common/SteamLinuxRuntime:/home/fembussy/Seagate_HDD_2TB/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier:/home/fembussy/WDEZEX_HDD_1TB/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper'
Fri Nov 17 03:37:46 PM CST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_TOOL_PATHS set to '/home/fembussy/Samsung860EVO_1TB/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier:/home/fembussy/Samsung860EVO_1TB/SteamLibrary/steamapps/common/Steamworks Shared:/home/fembussy/Seagate_HDD_2TB/SteamLibrary/steamapps/common/SteamLinuxRuntime:/home/fembussy/Seagate_HDD_2TB/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier:/home/fembussy/WDEZEX_HDD_1TB/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper'
Fri Nov 17 03:37:46 PM CST 2023 INFO - main - Checking internal dependencies:
Fri Nov 17 03:37:46 PM CST 2023 INFO - checkIntDeps - Result of version check for yad binary '/usr/bin/yad' is '13.0'
Fri Nov 17 03:37:46 PM CST 2023 INFO - main - Initializing first Proton:
Fri Nov 17 03:37:46 PM CST 2023 INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/steamtinkerlaunch/ProtonCSV.txt' which was created during a previous run
Fri Nov 17 03:37:46 PM CST 2023 INFO - initFirstProton - Initializing Proton
Fri Nov 17 03:37:46 PM CST 2023 INFO - initFirstProton - No Proton version available in template yet - searching for one
Fri Nov 17 03:37:46 PM CST 2023 INFO - initFirstProton - Updated 'USEPROTON' in '/home/fembussy/.config/steamtinkerlaunch/default_template.conf' to ''
Fri Nov 17 03:37:46 PM CST 2023 INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/fembussy/.config/steamtinkerlaunch/default_template.conf' is 'proton-8.0-4c'
Fri Nov 17 03:37:46 PM CST 2023 INFO - main - Initializing default window resolution
Fri Nov 17 03:37:46 PM CST 2023 INFO - setInitWinXY - Using '2580x1080' from config '/dev/shm/steamtinkerlaunch/defres.txt'
Fri Nov 17 03:37:46 PM CST 2023 INFO - main - Welcome to SteamTinkerLaunch
Fri Nov 17 03:37:46 PM CST 2023 INFO - removeEmptyFiles - Removing empty files from '/home/fembussy/.config/steamtinkerlaunch/games/appinfo'
Fri Nov 17 03:37:46 PM CST 2023 INFO - removeEmptyFiles - Removing empty files from '/home/fembussy/.config/steamtinkerlaunch/games/header'
Fri Nov 17 03:37:46 PM CST 2023 INFO - main - Checking command line: incoming arguments 'vortex install gui'
Fri Nov 17 03:37:46 PM CST 2023 INFO - getRes - Detected screen resolution '3440x1440'
Fri Nov 17 03:37:46 PM CST 2023 INFO - pollWinRes - Using harmless '--center' as variable 'GEOM', because there are multiple side-effects in yad if the string is empty
Fri Nov 17 03:37:46 PM CST 2023 INFO - pollWinRes - Creating initial '/home/fembussy/.config/steamtinkerlaunch/guicfgs/3440x1440/377160/SteamTinkerLaunch-installVortexGui.conf' with unused default values
Fri Nov 17 03:37:46 PM CST 2023 INFO - updateConfigEntry - 'COLCOUNT' option missing in config 'SteamTinkerLaunch-installVortexGui.conf' - adding a new line
Fri Nov 17 03:37:46 PM CST 2023 INFO - updateWinRes - Starting resolution-poll for '/home/fembussy/.config/steamtinkerlaunch/guicfgs/3440x1440/377160/SteamTinkerLaunch-installVortexGui.conf' with incoming '2580x1080'
Fri Nov 17 03:37:46 PM CST 2023 INFO - setShowPic - Determining game picture
Fri Nov 17 03:37:46 PM CST 2023 INFO - setShowPic - Using '/home/fembussy/.config/steamtinkerlaunch/games/header/377160.jpg' as game picture
Fri Nov 17 03:37:46 PM CST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-installVortexGui'
Fri Nov 17 03:37:46 PM CST 2023 INFO - getLatestVortVer - Search for latest Vortex stable Release
Fri Nov 17 03:37:47 PM CST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-installVortexGui'
Fri Nov 17 03:37:48 PM CST 2023 INFO - getLatestVortVer - Found 'vortex-setup-1.9.8.exe'
Fri Nov 17 03:37:48 PM CST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-installVortexGui'
Fri Nov 17 03:37:49 PM CST 2023 SKIP - updateWinRes - Timeout waiting for Window 'SteamTinkerLaunch-installVortexGui'
Fri Nov 17 03:37:54 PM CST 2023 INFO - getRes - Detected screen resolution '3440x1440'
Fri Nov 17 03:37:54 PM CST 2023 INFO - pollWinRes - Using GEOM '--geometry=2580x1080+0+0' from '/home/fembussy/.config/steamtinkerlaunch/guicfgs/3440x1440/377160/SteamTinkerLaunch-DownloadVortexStatus.conf'
Fri Nov 17 03:37:54 PM CST 2023 INFO - updateWinRes - Starting resolution-poll for '/home/fembussy/.config/steamtinkerlaunch/guicfgs/3440x1440/377160/SteamTinkerLaunch-DownloadVortexStatus.conf' with incoming '2580x1080'
Fri Nov 17 03:37:54 PM CST 2023 INFO - StatusWindow - for 'Downloading 'Vortex''
Fri Nov 17 03:37:54 PM CST 2023 INFO - getLatestVortVer - Search for latest Vortex stable Release
Fri Nov 17 03:37:54 PM CST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadVortexStatus'
Fri Nov 17 03:37:55 PM CST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadVortexStatus'
Fri Nov 17 03:37:55 PM CST 2023 INFO - getLatestVortVer - Found 'vortex-setup-1.9.8.exe'
Fri Nov 17 03:37:55 PM CST 2023 INFO - getRes - Detected screen resolution '3440x1440'
Fri Nov 17 03:37:55 PM CST 2023 INFO - pollWinRes - Using GEOM '--geometry=2580x1080+0+0' from '/home/fembussy/.config/steamtinkerlaunch/guicfgs/3440x1440/377160/SteamTinkerLaunch-InstallVortexStatus.conf'
Fri Nov 17 03:37:55 PM CST 2023 INFO - updateWinRes - Starting resolution-poll for '/home/fembussy/.config/steamtinkerlaunch/guicfgs/3440x1440/377160/SteamTinkerLaunch-InstallVortexStatus.conf' with incoming '2580x1080'
Fri Nov 17 03:37:55 PM CST 2023 INFO - StatusWindow - for 'Installing 'Vortex''
Fri Nov 17 03:37:55 PM CST 2023 INFO - setVortexVars - Using GE-Proton8-23 for vortex
Fri Nov 17 03:37:55 PM CST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-InstallVortexStatus'
Fri Nov 17 03:37:55 PM CST 2023 INFO - setModWine - DNPROTON is '/home/fembussy/.config/steamtinkerlaunch/proton/custom/GE-Proton8-23/proton'
Fri Nov 17 03:37:55 PM CST 2023 INFO - setModWine - DNPROTON is a file -- it is '/home/fembussy/.config/steamtinkerlaunch/proton/custom/GE-Proton8-23/proton'
Fri Nov 17 03:37:55 PM CST 2023 SKIP - installVortex - '/home/fembussy/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe' does already exists - nothing to install - skipping
Fri Nov 17 03:37:56 PM CST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadVortexStatus'
Fri Nov 17 03:37:56 PM CST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-InstallVortexStatus'
Fri Nov 17 03:37:57 PM CST 2023 SKIP - updateWinRes - Timeout waiting for Window 'SteamTinkerLaunch-DownloadVortexStatus'
Fri Nov 17 03:37:57 PM CST 2023 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-InstallVortexStatus'
Fri Nov 17 03:37:58 PM CST 2023 SKIP - updateWinRes - Timeout waiting for Window 'SteamTinkerLaunch-InstallVortexStatus'
Fri Nov 17 03:39:07 PM CST 2023 INFO - VortexOptions - Selected 'DONE' - Closing Menu
Fri Nov 17 03:39:23 PM CST 2023 INFO - MainMenu - Clicked '0' - 'EXIT'
Fri Nov 17 03:39:23 PM CST 2023 INFO - MainMenu - exiting 'Settings Menu' and opening 'Exit'
Fri Nov 17 03:39:23 PM CST 2023 INFO - closeSTL - closing STL
Fri Nov 17 03:39:23 PM CST 2023 INFO - updateConfigEntry - Emptying 'CUSTOMCMD' for '/home/fembussy/.config/steamtinkerlaunch/default_template.conf'
Fri Nov 17 03:39:23 PM CST 2023 INFO - closeSTL - Creating '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
Fri Nov 17 03:39:23 PM CST 2023 INFO - checkPlayTime - The game was not even started
Fri Nov 17 03:39:23 PM CST 2023 INFO - closeSTL - Game 'Fallout 4 (377160)' exited - cleaning up custom processes if necessary
Fri Nov 17 03:39:23 PM CST 2023 INFO - closeTrayIcon - Closing TrayIcon '56000'
Fri Nov 17 03:39:24 PM CST 2023 INFO - closeSTL - Removing '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
Fri Nov 17 03:39:24 PM CST 2023 STOP - ######### closeSTL SteamTinkerLaunch v12.12 #########
Fri Nov 17 03:39:24 PM CST 2023 INFO - writeLastRun - Recreating /home/fembussy/.config/steamtinkerlaunch/logs/steamtinkerlaunch/lastrun.txt
Fri Nov 17 03:39:24 PM CST 2023 INFO - storeMetaData - Saving metadata for game 'Fallout 4 (377160)'
Fri Nov 17 03:39:24 PM CST 2023 INFO - updateConfigEntry - 'GAMENAME' option missing in config '377160.conf' - adding a new line
Fri Nov 17 03:39:24 PM CST 2023 INFO - getArch - Architecture for '/home/fembussy/Samsung860EVO_1TB/SteamLibrary/steamapps/common/Fallout 4/Fallout4Launcher.exe' is 64bit
Fri Nov 17 03:39:24 PM CST 2023 INFO - storeMetaData - Symlink '/home/fembussy/.config/steamtinkerlaunch/meta/eval/title/evaluatorscript_Fallout 4.vdf' already exists
Fri Nov 17 03:39:30 PM CST 2023 INFO - startVortex - Vortex exited - starting game now

**Comment by sonic2kk** [comment]
You're using SteamTinkerLaunch v12.12, which is outdated. Please try a reinstall with SteamTinkerLaunch-git. There should be an AUR package you can use with 

Also, this error is Wine-specific, and not something afaik that SteamTinkerLaunch can fix. I also don't experience it, sometimes it happens on fresh installs for some users and sometimes it goes away on its own (I have seen reports of it with MO2 that just went away).

I don't think this issue is what is causing Vortex problems though, I suspect either Vortex is broken again or the issue is that Vortex v1.8.0 does not install properly with the very old SteamTinkerLaunch v12.12.

> I checked for issues with wine and don't see anything, so I don't think it's a wine problem.

Do keep in mind that the versions of Wine used and reported on WineHQ are entirely separate from the custom Wine builds used by Proton flavours, and contain many different patches. Plus, Proton is very Steam-specific, and uses things like the Steam Linux Runtime and custom prefix creation logic that differs a great deal from regular Wine :-)

For Proton, [Valve have forked Wine](https://github.com/ValveSoftware/Wine) and it has been heavily modified compared to base Wine. Valve's Wine has many branches and forks, and even GE-Proton uses the bleeding-edge branch but with even more custom patches on top (including patches from pending Valve Wine PRs).

>  I hope I didn't miss anything in the wiki for Vortex, but I don't think I did.

Not really, don't worry :-)

I think if anything the only thing you might have missed is the Vortex changes on the wiki changelog, the issue template does say to check this beforehand, but don't worry too much over it.

Just try using STL-git for now, I will probably not be releasing a stable STL anytime soon, it's just a Bash script so it's pretty pointless to make a release that does the same thing as downloading the repo code with the green button on the main page.

<hr>

Vortex still installs correctly on my PC last time I checked, so hopefully it works with an up-to-date git version.

Should the error persist, try double-checking the Wine version set in the Vortex prefix with `winecfg`. If you try to install Vortex with the latest STL-git and it gives this error, first make sure the prefix exists (in your case likely at `~/.config/steamtinkerlaunch/vortex/compatdata/pfx` and make sure it looks like a healthy prefix i.e. not empty, expected directory structure for `drive_c` and so on), and if it does you can run `steamtinkerlaunch vortex winecfg` to run Winecfg in the prefix. If you've never used this program, it comes as standard with many Wine and Proton flavours, and is used to tweak Wine prefixes. It has a dropdown to edit the Windows version.

Everything it does can manually be done from the registry by the way, but the keys are often cumbersome to edit (unless you're used to editing the Windows registry, which I am not :wink:). [WineHQ does note some useful ones though](https://wiki.winehq.org/Useful_Registry_Keys), so if you find one that you want to tweak, you can edit either with a Wine command directly (make sure to use the GE-Proton wine executable or else you might bork your prefix) or running GE-Proton's regedit
