### ISSUE TITLE
⚠️ New enough yad version required! (debian based distributions use an ancient yad version)

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#98]
I only tested with yad 7.2 on Arch Linux where everything works as expected.
Looks like at least debian based distributions use an ancient yad version 0.40 which simply doesn't have all the features required for stl.
I have no clue why but unfortunately none of the two issues opened here never were properly confirmed
_(#74 and #97)_.
In case someone wants to help it would be nice if this could be confirmed.
Adding a _yad --version_ check to stl would make sense then.

**Comment by RockafellaJaz** [comment]
I have tried YAD (v0.40) in linux mint 19.3 and ubuntu 20.04 and can confirm on my install upgrading from 0.40 to the latest version from github (v7.2) fixed issues with the descriptions being written after the menu item rather than in a tooltip as mentioned in [#74](https://github.com/frostworx/steamtinkerlaunch/issues/74).
If anyone is interested I used the following commands:
```
sudo apt install git libglib2.0-dev libtool autoconf automake intltool libgtk-3-dev build-essential
git clone https://github.com/v1cont/yad.git yad-dialog-code
cd yad-dialog-code
autoreconf -ivf && intltoolize
./configure && make
sudo make install
gtk-update-icon-cache
```

**Comment by frostworx** [comment]
added a yad version check in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.3.0

**Comment by frostworx** [comment]
Would be interesting to know why debian based distributions use such an old yad version. Is there simply no maintainer?

**Comment by kadogo** [comment]
Look like there is a maintainer but maybe yad is not really used in Debian (https://tracker.debian.org/pkg/yad). Without STL I didn't know it existed. There is an issue for upgrade the version but.. it's pretty old (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919785)

But the compilation is very straighforward. I guess not everyone have it easy to compile application too.

Maybe something that could be tried is building an appimage for yad? I can take a look when I have few time.

**Comment by frostworx** [comment]
Thanks for linking the issue tracker, Might motivate some ambitious debianers to motivate the package maintainer there.
IMHO any linux user should know the basics of a default compile from source, but this should be avoided by providing packages
wherever possible. AFAIK yad is not often used in bigger projects generally and still it is a mighty zenity successor which other distributions have in their package management.

**Comment by frostworx** [comment]
@kadogo created a yad appimage here: https://github.com/frostworx/steamtinkerlaunch/issues/119#issuecomment-717888312

**Comment by staticnation** [comment]
Linux Mint 20.04
ERROR yad version '0.40.0' is too old. You need to update to at least '7.0'

**Solution**: 

Download: [YadAppImage](https://github.com/frostworx/steamtinkerlaunch/files/5451226/yad-appimage.zip)
place `stl` and `Yad-313ada9-x86_64.AppImage` into `/usr/local/bin/`
**change line 26** of **stl file** from `YAD="yad`" to `YAD="Yad-313ada9-x86_64.AppImage"
`
now you can just `stl %command%` from steam

**Comment by kadogo** [comment]
I added a version build against Debian Stretch that is for now LTS on  https://github.com/kadogo/easy-builder. So the libraries issue must be lower normaly. The AppImage provided before was build on my Debian Buster system.

The repo contain the Dockerfile and script that I used to build the AppImage for trust reason or if you want a more updated version of Yad.

**Comment by frostworx** [comment]
Here's another solution with compiling yad manually (you should really get it into your package management :)):

https://github.com/frostworx/steamtinkerlaunch/issues/123#issuecomment-721147337

**Comment by frostworx** [comment]
~~Until it is not clear that the reason for the #124 bug is using an AppImage, I hide @staticnation workaround
I hope you understand this.~~
`(AppImage is not and won't be supported by steamtinkerlaunch directly generally)`, but unhide above message, as it can be helpful anyway for one or another.

**Comment by LuvIsBadToTheBone** [comment]
in linux mint 20.1 is ancient yad version 00.40 running.apt-get no work so i downloaded from here : https://github.com/v1cont/yad
all u need to do is compile i open terminal and insert autoreconf -ivf && intltoolize then configure make make install.
then i got version 9.1 (GTK+ 3.24.20) for yad and Frostworx code is running.

**Comment by frostworx** [comment]
Thanks for trying to help @LuvIsBadToTheBone!
As you described it is indeed pretty easy to compile an own yad binary from source _(and it is a good practice to start compiling, which can improve ones linux experience a lot generally)_. I guess most people who haven't compiled anything before are just a bit afraid from compiling.

**Comment by frostworx** [comment]
Closing again _(leaving as sticky)_, as we have collected enough help for `yad`, and it should be pretty obvious that this is no `steamtinkerlaunch` issue. Thanks again for everybody who tried to help above.

**Comment by frostworx** [comment]
Fyi: I'll make the yad binary configurable via command line, so a user can define a custom yad binary,
which will be saved into the global config and used _(f.e. `stl yad /path/to/custom/yad`)_.
On that way a global/system wide yad installation will no longer be required.

As the recently added [Conty](https://github.com/frostworx/steamtinkerlaunch/wiki/Conty) has built in yad, I'll also add a direct
`stl yad conty` shortcut, which will download the latest conty and configure that as "yad executable".
Also, @kadogos [appimage](https://github.com/frostworx/steamtinkerlaunch/files/5451226/yad-appimage.zip) from [here](https://github.com/frostworx/steamtinkerlaunch/issues/119#issuecomment-717888312) will have an extra` stl yad ai` shortcut with the same functionality. If someone has different/newer solutions feel free to suggest them.

**Comment by frostworx** [comment]
Fyi:
https://github.com/frostworx/steamtinkerlaunch/issues/207
or directly in the Wiki:
https://github.com/frostworx/steamtinkerlaunch/wiki/Custom-Yad

**Comment by perroboc** [comment]
Just gonna leave these easy to follow instructions for Debian based distros (tested on Pop! OS)
```bash
sudo apt install build-essential intltool autoconf git libgtk-3-dev
git clone https://github.com/v1cont/yad
cd yad
autoreconf -ivf && intltoolize
./configure && make
sudo make install
gtk-update-icon-cache
```
You should get a beautiful new app:
![image](https://user-images.githubusercontent.com/2722773/235277134-19e116b3-fa84-4547-8a11-a71d1f7f5bd3.png)

**Comment by ItsRogueRen** [comment]
> Just gonna leave these easy to follow instructions for Debian based distros (tested on Pop! OS)
> 
> ```shell
> sudo apt install build-essential intltool autoconf git libgtk-3-dev
> git clone https://github.com/v1cont/yad
> cd yad
> autoreconf -ivf && intltoolize
> ./configure && make
> sudo make install
> gtk-update-icon-cache
> ```
> 
> You should get a beautiful new app: ![image](https://user-images.githubusercontent.com/2722773/235277134-19e116b3-fa84-4547-8a11-a71d1f7f5bd3.png)

YOU ARE A FUCKING LIFE SAVER

I have spent an hour trying to figure out how the hell to install this on Pop!_OS and had almost just given up. Whoever said installing from source is easy has forgotten what its like to not be a programmer/developer

**Comment by sonic2kk** [comment]
> Whoever said installing from source is easy has forgotten what its like to not be a programmer/developer

Not necessarily these fields, but STL is for technical users, hence the "Tinker" in the title. Source installation is easy on a distro with up-to-date packages such as Arch Linux.

Also, it's not SteamTinkerLaunch's fault if a distribution doesn't package Yad, and you're expected to know how to troubleshoot missing dependencies from your distribution, as you would be when installing any package from source. The dependencies are listed on the wiki, it's up to the user to manage those dependencies however they like.

These steps are somewhat unnecessary because you can use a Yad AppImage. The wiki has documentation on using a custom Yad version. Pacstall may also work to install STL on Debian-based distros, which will install a more up-to-date Yad. If you can't/don't want to use Pacstall, refer to the [Yad wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Yad) on how to install the Yad AppImage.

You could create/request a PPA for STL for Debain-based distros if installing from source is difficult on these distros, but out-of-date distro packages is not a project maintainer's problem.

**Comment by RedSnt** [comment]
Thanks a bunch @perroboc - that saved me a lot of hassle. MX Linux is based on Debian and still, in 2024, running Yad v.0.40 😥

**Comment by TovanySnek** [comment]
i've been having some issues compiling yad as it just returns 
"configure.ac" is required when i type in "autoreconf -ivf && intltoolize"
any idea why that could be?

doing this since linux mint doesnt have an updated yad

**Comment by sonic2kk** [comment]
You could always just use the [Yad AppImage](https://github.com/sonic2kk/steamtinkerlaunch/wiki/yad#appimage) instead of compiling yourself. If you would prefer avoid using AppImages then that's fair enough.

However specifics on compiling Yad should be brought up elsewhere, the SteamTinkerLaunch issue tracker is not the right place to get support on compiling a third-party program (much less on a 4 year old issue :-)).

I could not tell you why you're getting these errors, perhaps you are missing some package, but you should double-check the latest guidance on [the Yad project repository](https://github.com/v1cont/yad). If you continue to run into trouble, perhaps open an issue on the Yad repo to ask for further guidance.

Good luck!

**Comment by yixophoenix** [comment]
Fucking linux man, I just want to run cheatengine for eldenring to get a fkn loadscreen bug fix for seamless coop. And now I'm stuck trying to figure out why mint has 0.40 in software manager, there's no .deb, why autoreconf -ivf && intltoolize gives 
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: running: autopoint --force
Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 293.
autoreconf: error: autopoint failed with exit status: 2
and what the fuck to do from here on out.

**Comment by Cagnaz** [comment]
> Fucking linux man, I just want to run cheatengine for eldenring to get a fkn loadscreen bug fix for seamless coop. And now I'm stuck trying to figure out why mint has 0.40 in software manager, there's no .deb, why autoreconf -ivf && intltoolize gives autoreconf: export WARNINGS= autoreconf: Entering directory '.' autoreconf: running: autopoint --force Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 293. autoreconf: error: autopoint failed with exit status: 2 and what the fuck to do from here on out.

I encountered the same problem, this did the trick for me:

sudo apt-get install autopoint
sudo apt-get install gettext

pray that will help you too
