### ISSUE TITLE
Can't open menu, can't install mo2, nothing works on Steam Deck

### ISSUE THREAD

**Issue by AzaleaCatgirl99** [sonic2kk/steamtinkerlaunch#980]
I've been trying to get mods running on Skyrim on my Steam Deck which is why I came to this tool. I've done exactly what the installation instructions say and absolutely nothing works. I try to install mo2 and it says "it's installed", but I don't even know how to open mo2. I can't even use commands without installing all of this tool all over again. When I try to start a game like Skyrim using the compatibility tool, it takes an age to "launch" and nothing shows up at all.

I have no clue what I've done wrong, but something isn't clicking.

**Comment by AzaleaCatgirl99** [comment]
Nvm got it working.

**Comment by sonic2kk** [comment]
Glad you got it, but in future when you open a bug report, please fill out the issue template. Also, if MO2 is the only reason you're using STL, you may not have a good experience, as it is a tool for Linux users to tinker, not a modding frontend.

> I can't even use commands without installing all of this tool all over again.

Uh, that isn't what's happening. STL is polling for updates. The SteamTinkerLaunch log should you understand what's happening in future.

<hr>

Another good tip is to look through recent commits, PRs, the wiki, and issues. MO2 needs STL with at least 06625b623e2cf900d239c0d4b74cdf932d9e2b39 to install correctly as innoextract needs a version bump for SteamOS 3.5. Likewise, make sure you're always running at *least* the latest SteamOS stable, though the Beta channel is definitely better for an enthusiast-orientated tool like STL. The wiki also notes that the latest STL from git should be used at all times, especially on SteamOS which is virtually unsupported at this point. For recent issues, MO2 needed a tweak to ignore pre-releases (#973).
