### ISSUE TITLE
HDR not enabling in the game settings on an OLED Steam Deck

### ISSUE THREAD

**Issue by Warmasterchief** [sonic2kk/steamtinkerlaunch#981]
## System Information
- SteamTinkerLaunch version: 12.12
- Distribution: SteamOS
- Installation Method: Package Manager

## Issue Description
HDR cannot be enabled on an OLED Steam Deck when using Steam Tinker Launch.  Not using Steam Tinker Launch will give the ability to turn ON HDR in the game settings. Games I’ve tried: Cyberpunk 2077, Spider-Man Remastered, and Spider-Man Miles Morales.

**Comment by sonic2kk** [comment]
Not an STL bug, this isn't something we disable or have ***any*** control over, this will be a GameScope session issue on the Steam Deck. Sorry. You could try toggling the DXVK HDR flag I *guess* on the Game Menu, but I doubt it makes a difference, these are also DX12 games and I don't think DXVK would control that, it would be up to GameScope. [Looking at the patch notes for DXVK v2.1](https://github.com/doitsujin/dxvk/releases/tag/v2.1), it may have an impact somehow, but eh. I doubt it'll help, I think this is a GameScope limitation.

If this really does fix the problem, you can set DXVK HDR setting to true in the default game settings template, either from the "Default" button on the Main Menu and enabling the checkbox under "Proton options", or by editing `default.conf` directly in `~/.config/steamtinkerlaunch` and setting `DXVK_HDR=1`.

Two other things to note: Using STL via package manager is not supported on SteamOS, and SteamTinkerLaunch v12.12 is very out of date, you should be using the latest version from git.

**Comment by sonic2kk** [comment]
If this does fix the issue, I wonder if it's worth ignoring this flag altogether on SteamOS Game Mode now.

**Comment by Warmasterchief** [comment]
Just to follow up, changing the DXVK HDR to true fixed it! Thanks for the help.

**Comment by sonic2kk** [comment]
That is pretty interesting. Thanks for getting back, that's very useful to know! Glad it's resolved :-)

Just to re-iterate: You might want to set this as the default in your SteamTinkerLaunch "Default" settings. But, I guess on Steam Deck Game Mode we can ignore this setting. I'll do that when I have some time, and in the meanwhile, I documented this on the Steam Deck wiki page.

I don't have my Steam Deck OLED yet but when it's here sometime next week I'll do some follow-up testing to confirm ignoring this setting in Steam Deck Game Mode works. But either way, force enabling this flag on your Default settings shouldn't pose any issues.

I imagine in future, once this is on the broader Linux desktop, this will be enabled by default, and probably the flag won't exist, so STL can remove it. But in the meanwhile it has to be enabled outside of Steam Deck Game Mode. I wonder if the HDR options are enabled for GameScope on the Linux Desktop if we should also force enable `DXVK_HDR`. That might be a good QoL feature.

Thanks for such an early Steam Deck OLED report :smile:
