### ISSUE TITLE
MangoHud wiki page unclear w.r.t relation between `USEMANGOHUD` and `MANHUVAR`

### ISSUE THREAD

**Issue by pynappo** [sonic2kk/steamtinkerlaunch#987]
https://github.com/sonic2kk/steamtinkerlaunch/wiki/MangoHud#enabling-mangohud says:

> There are two ways of enabling MangoHud: The MangoHud binary (USEMANGOHUD), or the MangoHud environment variable (MAHUVAR). If you've used MangoHud before, this should be familiar to you.

I understood this to mean that I only have to enable `MAHUVAR` for MangoHud to appear in games with Vulkan and it would be fine. After doing so, I was subsequently confused on why MangoHud wasn't appearing in said games. It turns out that [`MAHUVAR` is only used if `USEMANGOHUD == 1`](https://github.com/sonic2kk/steamtinkerlaunch/blob/a698f728290aae11b4fcaf6ea3450d2aacf11cb7/steamtinkerlaunch#L12329). I think one way to clarify this would be to change the linked section to something along the lines of:

"To use MangoHud, `USEMANGOHUD` must be enabled. If the option for the MangoHud variable (`MAHUVAR`) is also enabled, then the [MangoHud variable](https://github.com/sonic2kk/steamtinkerlaunch/wiki/MangoHud#mangohud-variable) is used, else, the [regular MangoHud invocation](https://github.com/sonic2kk/steamtinkerlaunch/wiki/MangoHud#mangohud-1) is used."

Alternatively the shell script could be changed to match the wiki, where `MAHUVAR == 1` automatically enables `USEMANGOHUD` or something, but that seems like more hassle.

**Comment by sonic2kk** [comment]
Yeah, the wiki can be updated. Usually though you don't need to use `MAHUVAR`. If you're still confused you normally only need to enable mangohud. That appends the MangoHud binary to the launch options (something like `/usr/bin/mangohud` most of the time).

It's still a reasonable change we can make but I wanted to point it out in case you were still unsure.

> Alternatively the shell script could be changed to match the wiki, where MAHUVAR == 1 automatically enables USEMANGOHUD or something, but that seems like more hassle.

Yes, this isn't feasible. `USEMANGOHUD` is the overarching option and the one 90% of use cases covers.

**Comment by sonic2kk** [comment]
[Updated the wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/MangoHud) to match your suggestions, though with a slightly different structure, it was largely copy and pasted from your suggestion. If GitHub allowed better wiki collaboration, I would have allowed you to submit an edit request yourself, but sadly it does not offer such an option.

Thank you a lot though!
