### ISSUE TITLE
STL fails to execute winetricks wmp10

### ISSUE THREAD

**Issue by RockafellaJaz** [sonic2kk/steamtinkerlaunch#99]
STL Version: v2.2.3
Linux Mint 19.3 XFCE.
proton-5.0-10-rc4
Freshly created prefix by steam.

I have only tested this on the Giana Sisters games.

The STL script launches and creates the dummy 32bit prefix but fails to install wp10 with winetricks and then just launches the game which freezes as the hack has not been installed.

Looking at the log file I can see the entry: 
    'wmp10hack - creating dummy 32bit WINEPREFIX and installing wmp10 into it'.
Then 20 seconds later the entry: 
    'launchSteamGame - default game start command'.

I can run winetricks from the terminal and have successfully installed wmp10 into the 32bit prefix by executing the command myself.

Looking at the STL script I can see the point where it attempts to run winetricks but do not see why it would be failing.

I did notice that there are checks to see if wmp10 is installed but did not see anything to check if the install of wmp10 failed and output that into the log, a check for this might be useful to highlight if there is an issue.

This could just be some weird issue with my setup but I would have thought that if I could run winetricks from the terminal that the script could execute it also.

Just to clarify I can launch the games and play them there is no issues with that as I have manually installed the required wmp10 files.

**Comment by frostworx** [comment]
Regarding wmp10 issues I added a notifier some days ago
https://github.com/frostworx/steamtinkerlaunch/commit/f60e518592651b12dc17803e7f0ce5724cf1e1a4

"I would have thought that if I could run winetricks from the terminal that the script could execute it also"
Of course, it can, but calling programs (including winetricks) from the steam env works differently than directly from the terminal.
As I can't test every system and contributions to the project are almost non-existent it might not work everywhere.

I already considered dumping the whole function and simply extract the MP10Setup.exe pulled from winetricks, so this might change in case I'll keep on releasing updates to the project.

**Comment by frostworx** [comment]
Already implemented offline.
The new function doesn't require winetricks anymore but only cabextract

**Comment by RockafellaJaz** [comment]
Thanks for the fast response. 
I did see the notifier you mentioned and that it checks for wmpasf.dll but there is no log message if it does not find wmpasf.dll.
Hopefully the cabextract solution will solve my issue.

**Comment by frostworx** [comment]
added in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.3.0
