### ISSUE TITLE
Only Flawless Widescreen is opened. Not the game process with it.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [sonic2kk/steamtinkerlaunch#996]
## System Information
- SteamTinkerLaunch version: steamtinkerlaunch-v12.12 (12.12-1 according to the package manager)
- Distribution: Nobara Linux (Fedora 38)
- Installation Method: Package Manager (Here's the specific package : https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara/package/steamtinkerlaunch/)

## Issue Description
When ticking the ["Use FlawlessWidescreen"](https://github.com/sonic2kk/steamtinkerlaunch/wiki/FlawlessWidescreen) option in the Game Menu setting page, saving the config and playing the game only seems to launch FlawlessWidescreen. This makes the main tool useless, as it can't Memory Edit the actual game, that's supposed to be launched at the same time.
If you do close FlawlessWidescreen, however, it does launch the game correctly, but of course, without FlawlessWidescreen.

## Logs
`/dev/shm/steamtinkerlaunch/steamtinkerlaunch-iscriptevaluator-45740.log` Test with Dead Rising 2.
```
lun. 11 déc. 2023 07:35:12 CET INFO - findEarlyProt - Trying to get a proton version from '/home/pm/.config/steamtinkerlaunch/gamecfgs/id/45740.conf'
lun. 11 déc. 2023 07:35:12 CET INFO - findEarlyProt - Searching 'GE-Proton8-22' in '/dev/shm/steamtinkerlaunch/ProtonCSV.txt'
lun. 11 déc. 2023 07:35:12 CET INFO - findEarlyProt - Found 'GE-Proton8-22' in '/dev/shm/steamtinkerlaunch/ProtonCSV.txt'
lun. 11 déc. 2023 07:35:12 CET INFO - checkFirstTimeRun - Writing 'EARLYPROT=/home/pm/.config/steamtinkerlaunch/proton/custom/GE-Proton8-22/proton' into '/dev/shm/steamtinkerlaunch/evalprot-45740.conf'
lun. 11 déc. 2023 07:35:12 CET INFO - checkFirstTimeRun - Both the copy '/home/pm/.config/steamtinkerlaunch/meta/eval/id/evaluatorscript_45740.vdf' of the original and a custom '/home/pm/.config/steamtinkerlaunch/meta/eval/id/custom/evaluatorscript_45740.vdf' are missing - trying to get the original'
lun. 11 déc. 2023 07:35:12 CET INFO - checkFirstTimeRun - 'evaluatorscript' START - '/home/pm/.config/steamtinkerlaunch/proton/custom/GE-Proton8-22/proton run /home/pm/.local/share/Steam/legacycompat/iscriptevaluator.exe legacycompat\evaluatorscript_45740.vdf'
lun. 11 déc. 2023 07:35:12 CET INFO - waitForEvaluatorscript - Waiting for '/home/pm/.local/share/Steam/legacycompat/evaluatorscript_45740.vdf' to appear
lun. 11 déc. 2023 07:35:12 CET INFO - waitForEvaluatorscript - Copied '/home/pm/.local/share/Steam/legacycompat/evaluatorscript_45740.vdf' to '/home/pm/.config/steamtinkerlaunch/meta/eval/id/evaluatorscript_45740.vdf'
lun. 11 déc. 2023 07:35:56 CET INFO - createModifiedEvalsc - Copying '/home/pm/.config/steamtinkerlaunch/meta/eval/id/evaluatorscript_45740.vdf' to '/home/pm/.local/share/Steam/legacycompat'
lun. 11 déc. 2023 07:35:56 CET INFO - createModifiedEvalsc - Replacing placeholders with real paths in '/home/pm/.local/share/Steam/evaluatorscript_45740.vdf'
lun. 11 déc. 2023 07:35:56 CET INFO - runEvacInstall - 'evaluatorscript' - START - STEAM_COMPAT_DATA_PATH="/mnt/Opinion/SteamLibrary/steamapps/compatdata/45740" '/home/pm/.config/steamtinkerlaunch/proton/custom/GE-Proton8-22/proton run /home/pm/.local/share/Steam/legacycompat/iscriptevaluator.exe evaluatorscript_45740.vdf'
lun. 11 déc. 2023 07:36:00 CET INFO - checkFirstTimeRun - 'evaluatorscript' - STOP - '/home/pm/.config/steamtinkerlaunch/proton/custom/GE-Proton8-22/proton run /home/pm/.local/share/Steam/legacycompat/iscriptevaluator.exe evaluatorscript_45740.vdf'
```
`/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`
```
lun. 11 déc. 2023 07:46:41 CET INFO - setflatpak - started SteamTinkerLaunch from /usr/bin/steamtinkerlaunch
lun. 11 déc. 2023 07:46:41 CET INFO - initAID - Set AID to PLACEHOLDERAID '31337'
lun. 11 déc. 2023 07:46:41 CET INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
lun. 11 déc. 2023 07:46:41 CET INFO - loadLangFile - Language from command line is 'english'
lun. 11 déc. 2023 07:46:41 CET INFO - loadLangFile - SYSTEMSTLCFGDIR is '/usr/share/steamtinkerlaunch'
lun. 11 déc. 2023 07:46:41 CET INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
lun. 11 déc. 2023 07:46:42 CET INFO - loadLangFile - Loading found system wide /usr/share/steamtinkerlaunch/lang//english.txt
lun. 11 déc. 2023 07:46:42 CET WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
lun. 11 déc. 2023 07:46:42 CET INFO - updateEditor - No valid editor found - will fall back to 'xdg-open'.
lun. 11 déc. 2023 07:46:42 CET INFO - loadLanguage - Loading STLLANG from '/home/pm/.config/steamtinkerlaunch/global.conf'
lun. 11 déc. 2023 07:46:42 CET INFO - loadLanguage - STLLANG from '/home/pm/.config/steamtinkerlaunch/global.conf' is 'english'
lun. 11 déc. 2023 07:46:42 CET INFO - setLocalInstall - Looks like we don't have a local non-root install
lun. 11 déc. 2023 07:46:42 CET INFO - updateConfigEntry - Option 'GLOBALCOLLECTIONDIR' is updated with the new value '/usr/share/steamtinkerlaunch/collections' in config 'global.conf'
lun. 11 déc. 2023 07:46:42 CET INFO - getCurrentCommandline - No Proton in command line arguments '-v'
lun. 11 déc. 2023 07:46:42 CET INFO - saveOrgVars - Storing some original variables to restore them later
lun. 11 déc. 2023 07:46:42 CET INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
lun. 11 déc. 2023 07:46:42 CET INFO - emptyVars - Set $PATH to '/home/pm/.cargo/bin:/home/pm/.local/bin:/home/pm/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/pm/.dotnet/tools:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin:/opt/rocm/hip/bin:/var/lib/snapd/snap/bin:/home/pm/.spicetify:/home/pm/.spicetify:'
lun. 11 déc. 2023 07:46:42 CET START - ######### Initializing Game Launch 31337 using SteamTinkerLaunch v12.12 #########
lun. 11 déc. 2023 07:46:42 CET INFO - main - Starting with a clean log
lun. 11 déc. 2023 07:46:42 CET INFO - main - Start creating default configs
lun. 11 déc. 2023 07:46:42 CET INFO - createDefaultCfgs - START
lun. 11 déc. 2023 07:46:42 CET INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
lun. 11 déc. 2023 07:46:42 CET INFO - loadLangFile - Language from command line is 'english'
lun. 11 déc. 2023 07:46:42 CET INFO - loadLangFile - GLOBALSTLLANGDIR is '/usr/share/steamtinkerlaunch/lang'
lun. 11 déc. 2023 07:46:42 CET INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
lun. 11 déc. 2023 07:46:42 CET INFO - loadLangFile - Loading found system wide /usr/share/steamtinkerlaunch/lang/english.txt
lun. 11 déc. 2023 07:46:42 CET WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
lun. 11 déc. 2023 07:46:42 CET INFO - updateEditor - No valid editor found - will fall back to 'xdg-open'.
lun. 11 déc. 2023 07:46:42 CET INFO - loadLanguage - Loading STLLANG from '/home/pm/.config/steamtinkerlaunch/global.conf'
lun. 11 déc. 2023 07:46:42 CET INFO - loadLanguage - STLLANG from '/home/pm/.config/steamtinkerlaunch/global.conf' is 'english'
lun. 11 déc. 2023 07:46:42 CET INFO - createDefaultCfgs - setSteamPaths:
lun. 11 déc. 2023 07:46:42 CET INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
lun. 11 déc. 2023 07:46:42 CET WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
lun. 11 déc. 2023 07:46:42 CET INFO - updateEditor - No valid editor found - will fall back to 'xdg-open'.
lun. 11 déc. 2023 07:46:42 CET INFO - getGameOS - Starting game OS detection
lun. 11 déc. 2023 07:46:42 CET INFO - getGameOS - STEAM_COMPAT_DATA_PATH is not defined, so this is either a Linux Game or no game was started at all
lun. 11 déc. 2023 07:46:42 CET INFO - listAllSettingsEntries - '/dev/shm/steamtinkerlaunch/setentries.txt' already exists - nothing to do
lun. 11 déc. 2023 07:46:42 CET INFO - createDefaultCfgs - STOP
lun. 11 déc. 2023 07:46:42 CET SKIP - listSteamLibraries - not recreating already available '/dev/shm/steamtinkerlaunch/SteamLibraries.txt'
lun. 11 déc. 2023 07:46:42 CET INFO - setSteamLibraryPaths - STEAM_COMPAT_LIBRARY_PATHS set to '/home/pm/.local/share/Steam/steamapps:/mnt/Neige/SteamLibrary/steamapps:/mnt/Opinion/SteamLibrary/steamapps:/mnt/Soulagement/SteamLibrary/steamapps:/mnt/Yak/SteamLibrary/steamapps'
lun. 11 déc. 2023 07:46:42 CET INFO - setSteamLibraryPaths - STEAM_COMPAT_MOUNTS set to '/home/pm/.local/share/Steam/steamapps/common/Steamworks Shared:/mnt/Opinion/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper:/mnt/Yak/SteamLibrary/steamapps/common/SteamLinuxRuntime:/mnt/Yak/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier:/mnt/Yak/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper'
lun. 11 déc. 2023 07:46:42 CET INFO - setSteamLibraryPaths - STEAM_COMPAT_TOOL_PATHS set to '/home/pm/.local/share/Steam/steamapps/common/Steamworks Shared:/mnt/Opinion/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper:/mnt/Yak/SteamLibrary/steamapps/common/SteamLinuxRuntime:/mnt/Yak/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier:/mnt/Yak/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper'
lun. 11 déc. 2023 07:46:42 CET INFO - main - Checking internal dependencies:
lun. 11 déc. 2023 07:46:42 CET INFO - setAwkBin - Found 'gawk' as an 'awk' variant. It should work without any issues, because 'gawk' was tested completely
lun. 11 déc. 2023 07:46:42 CET INFO - checkIntDeps - Result of version check for yad binary '/usr/bin/yad' is '9.3'
lun. 11 déc. 2023 07:46:42 CET INFO - main - Initializing first Proton:
lun. 11 déc. 2023 07:46:42 CET INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/steamtinkerlaunch/ProtonCSV.txt' which was created during a previous run
lun. 11 déc. 2023 07:46:42 CET INFO - initFirstProton - Initializing Proton
lun. 11 déc. 2023 07:46:42 CET INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/pm/.config/steamtinkerlaunch/default_template.conf' is 'proton-8.0-4'
lun. 11 déc. 2023 07:46:42 CET INFO - main - Initializing default window resolution
lun. 11 déc. 2023 07:46:42 CET INFO - setInitWinXY - Using '2580x1080' from config '/dev/shm/steamtinkerlaunch/defres.txt'
lun. 11 déc. 2023 07:46:42 CET INFO - main - Welcome to SteamTinkerLaunch
lun. 11 déc. 2023 07:46:42 CET INFO - removeEmptyFiles - Removing empty files from '/home/pm/.config/steamtinkerlaunch/games/appinfo'
lun. 11 déc. 2023 07:46:42 CET INFO - removeEmptyFiles - Removing empty files from '/home/pm/.config/steamtinkerlaunch/games/header'
lun. 11 déc. 2023 07:46:42 CET INFO - main - Checking command line: incoming arguments '-v'
```

**Comment by sonic2kk** [comment]
Interesting, I'll try find some time to take a look. I don't really know what Flawless Widescreen is or how it's implemented in STL.

Also, is there a list of games somewhere that I can use Flawless Widescreen with? It would be nice if there was a simple game I could test with.

Can you reproduce this on master? STL v12.12 is very old, you probably want to avoid using it.

A couple of things to note though from your log:
- Your Yad version looks pretty out-of-date, it likely isn't affecting anything here but this is just a courtesy warning that you're a few major versions behind
- In future, please attach logs as files, the issue template requests this as well (emphasis by me): "Ensure that you are **attaching** the log [...]"

**Comment by sonic2kk** [comment]
Pushed a tentative fix with 9366dd440fe11bf43412e9fb1c3a35290a1ee61f. I recall a similar issue with x64dbg where the program would start but not the game, ~~and a magic sleep time of `5` instead of `2` fixed it~~ Seems like x64dbg never actually used `2`, but it was a value I tested during development, and `5` was the lowest value that worked in #950.

FlawlessWidescreen was also using `2` as a sleep time. So I pushed a change for the FlawlessWidescreen launch to take `5` seconds before it tries to run with Proton.

This should be available with `v14.0.20231212-1` (heh, coincidence that it's also 1212). Not sure if it fixes it yet, I haven't tested yet, this was just an observation.

**Comment by PoorPocketsMcNewHold** [comment]
> Interesting, I'll try find some time to take a look. I don't really know what Flawless Widescreen is or how it's implemented in STL.
> 
> Also, is there a list of games somewhere that I can use Flawless Widescreen with? It would be nice if there was a simple game I could test with.

This is a piece of utility, which hosts different kinds of memory hacking bits for different games, to allow for better support of Ultrawide ratio screens, in different video games. Goes from Black-Bar disablers to FOV camera tweaks.
They got a small, non-exhaustive list there on their website, but they do support more games than that. https://www.flawlesswidescreen.org/#Supported
Even if you don't have any use for this software, you could always load a supported game, and see if it can't poke around with some of those games, values, like Fov.

> Can you reproduce this on master? STL v12.12 is very old, you probably want to avoid using it.
Doing it from git, with ProtonUp-QT

> A couple of things to note though from your log:
> 
>     * Your Yad version looks pretty out-of-date, it likely isn't affecting anything here but this is just a courtesy warning that you're a few major versions behind
yad-9.3-5.fc38
That's just the latest version available for Fedora 38 on Fedora. https://packages.fedoraproject.org/pkgs/yad/yad/

>     * In future, please attach logs as files, the issue template requests this as well (emphasis by me): "Ensure that you are **attaching** the log [...]"
Missed the precision. Would have naturally done it if i haven't told myself that they were small enough.

**Comment by sonic2kk** [comment]
> Doing it from git, with ProtonUp-QT

This will do a local install and won't override the package manager install, since ProtonUp-Qt doesn't install anything system-wide by design.

Make sure you're using v14.0.20231212-1, the latest version as of less than an hour ago (you can re-install to replace the local install), and see if the extra sleep time fixed the issue. STL won't automatically update or anything, so you can manually update.

> Even if you don't have any use for this software, you could always load a supported game, and see if it can't poke around with some of those games, values, like Fov.

Yes, I didn't add Flawless Widescreen support, but unlike other things STL does it's very much along the lines of things I'm interested in supporting.

> That's just the latest version available for Fedora 38 on Fedora.

You can build / download a newer AppImage of Yad and point STL to use that ([wiki link](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Yad#appimage)), but it's a shame it's so out of date. No worries though, just figured I'd let you know :-)

**Comment by sonic2kk** [comment]
I'm not totally sure how FlawlessWidescreen is supposed to work, but on master, it looks like it detects the game process properly now. I tested with KOTOR, I first had to launch the game with it and then install the necessary plugin, then do a re-launch since it couldn't detect the already running process (not a bug, just a limitation of running under Wine).

I didn't notice a real change in behaviour but KOTOR is buggy under Wine to begin with, still, it detected the process.

Please test if master (v14.0.20231212-1) works for you, as it appears to be working in my tests :-)

![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/7917345/ff8be2d0-6de3-4891-b4df-06925cfd3080)

**Comment by PoorPocketsMcNewHold** [comment]
I'm having issues making the master version work *(as it just is stuck, launching the game. I even deleted the previous game configs)*. So, I'll close this issue, hopefully considering indeed fixed, since you could actually confirm working properly.
Gonna wait for the package maintainer to update it then, it ain't too bad for me. Thanks !

**Comment by sonic2kk** [comment]
I don't think GE packages STL-git, and you will probably have to wait several months before STL v14.0 (#992). But good luck!

**Comment by PoorPocketsMcNewHold** [comment]
Btw, had to update that. Yes, It does work years later. 
Version : steamtinkerlaunch-v14.0.20241228-1
![Image](https://github.com/user-attachments/assets/df9d1137-1bba-475e-8f73-1468916dd93f)
